### ISSUE TITLE
Karma test runner adapter/plugin?

### ISSUE THREAD

**Issue by bpatram** [postmanlabs/newman#1002]
I think it would be amazing to make a plugin/adapter for [Karma](http://karma-runner.github.io/1.0/index.html). That would allow people to more easily integration newman into an existing test process. Unfortunately, I do not have the knowledge or time to begin development of such a plugin. But I think it would be important to know if this is even something people want.

Info on how to create Karma plugins: http://karma-runner.github.io/1.0/dev/plugins.html

**Comment by kunagpal** [comment]
@bpatram Thanks for your suggestion. While Newman can already be easily integrated into existing test suites, we'd also like to know why you believe that a Karam plugin is even needed.
