### ISSUE TITLE
Feature Request: Pass environment variables on the command line

### ISSUE THREAD

**Issue by michaelajr** [postmanlabs/newman#1013]
We could really use a way to pass an environment variable on the command line. We have set up environments and can specify an environment file from the command line, but I do not want to put secrets in the environment files. Things like oauth2 secret key should be passed in for a run and added to (or override) variables specified in the environment file.

**Comment by michaelajr** [comment]
This would be useful when running from Jenkins. We could put the oauth2 secret in the Credentials Store and pass it to the pipeline code suing the `withCredentials` wrapper.

**Comment by kunagpal** [comment]
@michaelajr Support for this is being worked on in #1138, we'll update this thread with time 😄

**Comment by michaelajr** [comment]
@kunagpal GREAT! Thank you!

**Comment by kunagpal** [comment]
@michaelajr This has been released with Newman `v3.8.0`, please see https://github.com/postmanlabs/newman#newman-run-collection-file-source-options for details on how to use this feature 😄

**Comment by yw-m-id** [comment]
It seems we can passing `--env-var "my_environment_variable=foo" too, but not documented in README.md file (https://github.com/postmanlabs/newman#newman-run-collection-file-source-options) @kunagpal

**Comment by blueelvis** [comment]
@yw-m-id - The documentation still doesn't list this out. Do you know if a variable is passed via both the environment file and as an environment variable, which is going to take precedence?

**Comment by JesperA75** [comment]
The variable overwrites the environment json file

**Comment by ZelimDamian** [comment]
> The variable overwrites the environment json file

Does it completely disable the environment json or simple overrides the values in the json by the ones specified in the command line?
