### ISSUE TITLE
Environments/Globals Newman re-use 

### ISSUE THREAD

**Issue by pfazzino** [postmanlabs/newman#102]
Trying to work out how best to structure my environments/globals in postman to make re-use in newman as easy as possible. I have a number of scenarios to test which require different input data which up till now I've used environments for. I also use globals for common variables across all scenarios. There's no explicit support in newman afaics to allow me to pass both.

One way around this I thought was to make each environment a data file and consider it an iteration and use the globals as an environment file to pass in however the environment file format is not directly usable as a set of variables in a data file iteration which means some pre-processing is required.

Another thought I had was to merge the globals with each environment file and just run newman for each environment but this would be a manual process (there's no ability to export an environment and merge the globals in a single step). Even better would be for newman to support multiple environment files and treat it as a flat variable list, that way I could pass the environment and the globals at the same time.

Has anyone else faced this issue and how did you deal with it? Any thoughts appreciated.

**Comment by bandtank** [comment]
How do you export a collection that includes globals? I can't figure it out. Also, is `npm update -g newman` the right way to update newman?

**Comment by smrutikore** [comment]
Yes for update this is d way. But you might need to use sudo as root.

**Comment by abhijitkane** [comment]
@bandtank Globals are not part of collections. You need to export them from the environments menu > Manage environments > Globals > Download.
