### ISSUE TITLE
Running the postman script using Newman on remote Jenkins server

### ISSUE THREAD

**Issue by bijoej** [postmanlabs/newman#1020]
Hi,
 Can anyone let me know how to run the Postman generated json script on a remote Jenkins server using Newman.

 My requirement is:
 - I have created lots of tests and can run it easily locally from terminal using Newman command
 - I basically want to run the test from remote Jenkins 

What should I do for this?

Regards,
Bijo

**Comment by kunagpal** [comment]
http://blog.getpostman.com/?s=newman+jenkins

**Comment by bijoej** [comment]
Sorry for the late reply...

Since my Json file is in my local, can I generate the sharelink and pass that in jenkins job to run my tests? 
In the following way under "Execute Shell":-

newman -c https://www.getpostman.com/collections/d1574ef972de1ee4a7c2 --exitCode 1

But it fails immediately while running.
Do we need "Newman" to be installed in the Jenkins Server first?

Regards,
Bijo

**Comment by bijoej** [comment]
Finally I succeeded to run in a dockerized manner.
Thanks for your help

Regards,
Bijo

**Comment by FractalSeed** [comment]
In new version you just run 
`newman run CollectionName.postman_collection.json`

If you are running the as Execute Shell option, the build will fail

### Setup
![image](https://user-images.githubusercontent.com/6602679/33212852-dc5cdc62-d14a-11e7-9158-ede29a66891c.png)

### Result
![image](https://user-images.githubusercontent.com/6602679/33212796-a77b5000-d14a-11e7-9693-2bf986aaf07f.png)

**Comment by trollcodelord** [comment]
Hi Guys,

I'm using Newman but i have few questions 

Do we need "Newman" to be installed in the Jenkins Server?? 
Can we run Newman via Jenkins Server like rcon job ??
Is there any template where we get response VS time graph in output?

Thanks in Advance

**Comment by MulderWhite** [comment]
@trollcodelord Newman is a command line tool to run postman collections.
So in order to run it from jenkins, you may use shell script feature of Jenkins Pipeline or Jenkins freestyle projects through which you can run the newman command as per the Newman [documentation](https://www.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman).

**Comment by rahuldash171** [comment]
> Finally I succeeded to run in a dockerized manner.
> Thanks for your help
> 
> Regards,
> Bijo

Hi please tell the process . How did you run it
