### ISSUE TITLE
Reference Error - Navigator not defined when using JSEncrypt library to encode the Password

### ISSUE THREAD

**Issue by chit786** [postmanlabs/newman#1021]
1. Newman Version (can be found via `newman -v`):

3.5.2

 2. OS details (type, version, and architecture):
WIN7 / 32 bit
 3. Are you using Newman as a library, or via the CLI?

CLI
 3. Did you encounter this recently, or has this bug always been there:

Tried first time and received error.
 4. Expected behaviour:

 5. Command / script used to run Newman:

C:\Users\UID\Postman>newman run collection.json -e environment.json -g global.json -d "data.json" -n 1 -k

 6. Sample collection, and auxilliary files (minus the sensitive details):
          All data is sensitive so can´t share.
 7. Screenshots (if applicable):

This is the output on command window
  #  failure        detail

 1.  ReferenceErr.  navigator is not defined
                    at test-script
                    inside "getpublickey" of ""

**Comment by shamasis** [comment]
Can you provide the script that you're using inside test or prerequest? (Remove sensitive aspects)

By knowing the script / libraries that you are calling from inside the script, I can confirm whether it is an issue in our library or not. 

Otherwise, all I can conclude is you are referring to "navigator" somewhere and Newman is will not have browser specific variables. 

It could also be a bug where one of the built in libraries packaged with Newman has a bug. I will need more data to proceed.

**Comment by chit786** [comment]
Thank you for response , I am using JSEncrypt JavaScript code to encrypt the PIN inside one of the get response in test script where it's failing. But in postman it's working fine. Only issue is while trying with newman.

**Comment by czardoz** [comment]
@chit786, looks like your library is trying to access some browser related features, which are not supported in Newman (or even our non-chrome apps). We've included CryptoJS in the sandbox, maybe you could use that as an alternative?

**Comment by chit786** [comment]
@czardoz thanks for your suggestion and yes I went through the encryption library and it does uses navigator, which is expected to work in chrome apps. However I replaced it in code to use the chrome specific string values wherever the navigator is used and its working fine, so now I get next exception with window is not defined which is again a browser specific.  And now i am stuck how to replace window object .
Also I am not sure how exactly I can replace JSEncrypt's RSA encryption using CryptoJS existing libraries. as our application is using JSEncrypt to work with and my task is to test a login feature implemented using JSEncrypt.

Any suggestions are much appreciated. 

Thanks again!

**Comment by chit786** [comment]
https://npmcdn.com/jsencrypt@2.3.0 this is the encryption library I used in test-script which is failing so would like to know which is the similar encryption I can use from the CryptoJS. Thank you!

**Comment by czardoz** [comment]
@chit786 I have never used JSEncrypt before, so I cannot tell more about alternative functionality in CryptoJS. It does however support AES, DES & Triple DES. Check out these links for more information:

https://www.npmjs.com/package/crypto-js
https://code.google.com/archive/p/crypto-js/

**Comment by chit786** [comment]
Thanks Aniket I solved it! changed encoding javascript and I am successfully able to encode using JSEncrypt.

Note : JSEncrypt itself uses asymmetric encoding as compared to CryptoJS so can't use it in my scenario since I am pretty restricted to use JSEncrypt.

thank you for your support ~chitrang

**Comment by xuelangZF** [comment]
I have seen the same problem, what did you mean by "changed encoding javascript"? @chit786

**Comment by chit786** [comment]
@xuelangZF I do not remember exactly, I encountered this problem in my previous project, but as I remember correctly it had something to do within the encoder , where it was trying to access browser commands like `this` or `window` , I made them browser independent . Hope this helps.

**Comment by xuelangZF** [comment]
I'm not good at js and I thought it can't get rid of browser dependencies.  Thank you very much for pointing it out to me.  @chit786
