### ISSUE TITLE
Automating AWS API Testing Using Postman and Newman

### ISSUE THREAD

**Issue by kariasbolster** [postmanlabs/newman#1030]
I was given the task to automate API testing and came across postman which was great because it supports AWS Signature authentication. So I played with it and the results were good, I am able to successfully test my api. So this was all done manually, I have a code to generate my access key Id, secret key Id  and session token and manually add them in the authentication tab. So what I wanted to know now is, is there a way to automate this process? I thought at first I can just use newman and use newman option global variables for those 3 infos from my code but when I take a look at the postman collection exported from postman, there is no entry for authentication in there. Is there someway I can accomplish what I want?

**Comment by kunagpal** [comment]
@kariasbolster To ensure that authentication details are included in exported collections, the `Save helper data to request` checkbox next to the authentication fields will have to be checked. If you'd like to use dynamically generated AWS API access keys, you'll have to:

1. Add a request to your collection to generate an id-key pair using the AWS IAM API: http://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateAccessKey.html.

2. The response from this endpoint can be parsed to yield a fresh keypair for each collection run (which will then have to be saved as environment variables).

3. You'd also want to add a separate request to clear the generated keypair, using: http://docs.aws.amazon.com/IAM/latest/APIReference/API_DeleteAccessKey.html

**Comment by kariasbolster** [comment]
Hi @kunagpal thanks for the answer. I don't think I will be needing ( or maybe I don't have the knowledge yet ) to do step 2 and 3 as I already have a code to get the AccessKey, SecretKey and SessionToken. So I tried step 1, the save helper data to request, and  when I exported my collection, the helper attributes are included in the collection.json. That's all good, but the next thing I want to know is if I change the AccessKey, SecretKey and SessionToken using my javascript code( I generate new values  everytime the tests are run particularly after every merge ), would it also update the headers? Because in postman, when I set the authorization to AWS Signature, and then input the required details, it will automatically generate the header fields for me.

**Comment by czardoz** [comment]
@kariasbolster, you can set the value of the keys to Postman variables. 

e.g:

Access Key: `{{my_access_key}}`

In your pre-request script, you can then use the Sandbox helper functions to change these values:
```
postman.setEnvironmentVariable('my_access_key', 'ABCDEFGHI');
```

For more information, check out our documentation: https://www.getpostman.com/docs/postman/environments_and_globals/variables

Hope this helps :)

**Comment by kariasbolster** [comment]
@czardoz thanks for the answer.  this helps. but i now have a next question, my keys are programmatically generated. I have a code to generate them and it seems I can't add my code in the pre-requisite script tab, so I thought since I'm using newman, I'll just add newman into my code and then add the environment variables in there, but the problem if I use that is I lose the out of the box functionality of postman for creating the Authorization header which is necessary to make http calls to aws api endpoints. And I don't want to do it myself as I don't have the capability to do so, I tried for two days but I cannot make it work in postman. So I relied on that out of the box functionality.

**Comment by czardoz** [comment]
@kariasbolster AWS Auth _is_ supported out of the box in Postman and Newman. You just need to set the correct AWS Access Key and Secret Key in Postman. 

So basically, you don't need custom code to generate them programmatically.

**Comment by kariasbolster** [comment]
@czardoz Oh okay I thought its only supported in postman. So you mean, I can just the same Access Key and Secret for all my future http calls? Sorry Im not really a technical guy but I'm trying to learn. But what about the Session Token? It expires every hour. The reason why they told me to generate new Access Key, Secret Key is because Session Token expires every hour that is why I need to login again using their library which will give me new access key, secret key and session token.

**Comment by czardoz** [comment]
@kariasbolster The validity of Access Key and Secret depends on your particular AWS Account policies, so you should talk to someone who manages your AWS Account for details around that.

Essentially, it is possible to have an Access Key & Secret of indefinite validity. However, that may not be compliant with your organizations security policies. In that case, you would need to use a Session Token. 

As @kunagpal pointed out, there are ways to get the Session token, but exactly how to do that is outside Postman's scope, and the answer lies in your organization's security policies.

As long as you have the session token, you can use Postman & Newman out of the box, by specifying it as an environment variable and making sure you set the value of `Session Token` to your variable name, e.g: `{{my_session_token}}`.

If you have your own code which fetches the Session Token, you can write it to an environment file and give the file to newman. e.g:
```
newman run collection.json -e environment.json
```

The environment.json file needs to have contents similar to this: 
```
{
  "id": "043ddbc2-1fbb-242f-9c39-dc89e08d4a65",
  "name": "my-env",
  "values": [
    {
      "key": "my_session_token",
      "type": "text",
      "value": "!!!! PUT YOUR TOKEN HERE !!!!",
      "enabled": true
    }
  ],
  "_postman_variable_scope": "environment",
}
```

**Comment by kariasbolster** [comment]
@czardoz Oh great! Thanks a lot @czardoz , you helped me big time.

**Comment by kunagpal** [comment]
@kariasbolster Marking this issue as resolved. Feel free to re-open if you're facing issues 😄
