### ISSUE TITLE
Data Variables Can't Be Used In Request Body?

### ISSUE THREAD

**Issue by kariasbolster** [postmanlabs/newman#1032]
I have different scenarios for my api testing and the data for those scenarios are inside a json file which I passed in newman as a data variable file. But it doesn't seem to work. Is there another way I can accomplish this?

 This is what my request body looks like 
```
{
  "venture": data.requestBody.venture,
  "country": data.requestBody.country,
  "departmentType": data.requestBody.departmentType,
  "priceChangeType": data.requestBody.priceChangeType,
  "shipmentType": data.requestBody.shipmentType,
  "fileName": data.requestBody.fileName,
  "modifiedBy": data.requestBody.modifiedBy
}
```

**Comment by czardoz** [comment]
@kariasbolster Here's a walkthrough on how to use Data Variables: http://blog.getpostman.com/2014/10/28/using-csv-and-json-files-in-the-postman-collection-runner/

Basically, your data file needs to contain something like this:
```
[
  { venture: 'abc', country: 'some name' ... modifiedBy: 'pqr' }
]
```
and your request body needs to contain:
```
{
  "venture": {{venture}},
   ... other properties similarly changed
  "modifiedBy": {{modifiedBy}}
}
```

**Comment by kariasbolster** [comment]
@czardoz this is what my data variables file looks like
```
[
    {
        "requestBody": {
            "venture": "ventures.ZALORA",
            "country": "countries.SG",
            "departmentType": "departments.MERCHANDISE",
            "priceChangeType": "priceChangeTypes.PERMANENT",
            "shipmentType": "shipmentTypes.OUTRIGHT",
            "fileName": "merchandise_permanent-md_outright_valid.xlsx",
            "modifiedBy": "testautomation@testmail.com"
        },
        "expect": "SUCCESS",
        "withToken": true
    }
]
```
So data variables only work on the first level?

**Comment by czardoz** [comment]
@kariasbolster Yes :)

**Comment by kariasbolster** [comment]
@czardoz so I tried your answer and modified my body to this.

<img width="604" alt="screen shot 2017-05-19 at 5 59 41 pm" src="https://cloud.githubusercontent.com/assets/16870304/26243012/fcf04fd6-3cbc-11e7-8cf8-d69cb6aaf7fd.png">

However the values weren't substituted as you can see in the request below

![screen shot 2017-05-19 at 5 59 01 pm](https://cloud.githubusercontent.com/assets/16870304/26243055/1b70b4f0-3cbd-11e7-877f-02d518e401a6.png)

**Comment by kariasbolster** [comment]
@czardoz never mind my last question stupid of me, I did not enclosed the {{}} in parenthesis.
