### ISSUE TITLE
Provide the custom report path from command ??

### ISSUE THREAD

**Issue by codeKonnect** [postmanlabs/newman#1038]
Hello all,

This is more like a query than an issue.

I wanted to know if there is any way where we can pass the custom report template(path) to the newman command in jenkins so that it picks this path and generates the report. I am trying to modify the existing Junit template to meet our requirements for minimal log.

Thanks in advance,
codeKonnect

**Comment by kunagpal** [comment]
@codeKonnect The JUnit reporter does not support a custom template yet, but this could be a useful addition.

**Comment by codeKonnect** [comment]
@kunagpal  Thank you for the faster response.
Is this feature available for the other reporters ? like HTML report?
If yes , is it possible to pass the path of the report template from command ?

**Comment by kunagpal** [comment]
@codeKonnect Yes, the HTML reporter supports custom templates via the `--reporter-html-template` option. This template must be a [handlebars](http://handlebarsjs.com/) file, and must accept the template object here: https://github.com/postmanlabs/newman/blob/develop/examples/reports/html-reporter-template-data.json

**Comment by czardoz** [comment]
Closing this, @codeKonnect feel free to reopen if you're having issues :)
