### ISSUE TITLE
newman CLI does not offer any way to persist variables across requests

### ISSUE THREAD

**Issue by punitag** [postmanlabs/newman#1042]
newman version 3.6.0

**Comment by wooramy** [comment]
Not sure if related, but I found a regression from newman 3.6.0 which works fine on newman 3.5.1.

1. Send POST request and save ID from the response to postman environment variable like
  - `postman.setEnvironmentVariable('itemId', body.id);`
2. Send multiple GET request using {{id}} variable
  - `GET /items/:itemId`

Result: `:itemId` does not get replaced with saved environment variable but sent as raw :itemId string.

**Comment by czardoz** [comment]
@wooramy Yours seems to be a different issue, can you open a new issue?

@punitag you can use `postman.setEnvironmentVariable()` to set values which persist variables across requests, see https://www.getpostman.com/docs/chaining_requests for details :)
