### ISSUE TITLE
Feature request for specififying postman environment variable on command line

### ISSUE THREAD

**Issue by wierzba3** [postmanlabs/newman#1046]
I asked about this in the slack chat and I was told it would be in a future release.
How can I follow this feature so I can know when it is live?

**Comment by shamasis** [comment]
We will update this issue once we release something that allows you to send data from CLI args to the collection run.

**Comment by czardoz** [comment]
@wierzba3 @shamasis This is a duplicate of https://github.com/postmanlabs/newman/issues/1013, so we can track the updates there. 

Closing this issue in favor of #1013
