### ISSUE TITLE
newman run collection.json -e env.json --reporters html" throws error

### ISSUE THREAD

**Issue by therahulprasad** [postmanlabs/newman#1047]
1. Newman Version (can be found via `newman -v`): 3.6.0
 2. OS details (type, version, and architecture): Ubuntu 16.04 64bit
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: recently
 4. Expected behaviour: no-error
 5. Command / script used to run Newman: 
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by czardoz** [comment]
@therahulprasad need more details on what the errors are (preferably a screenshot of your terminal).

**Comment by czardoz** [comment]
Closing in favour of #1048, which has details about the error :)

**Comment by therahulprasad** [comment]
Don't know why Github created two issues, I just edited the description.
