### ISSUE TITLE
Unable to handle https requests

### ISSUE THREAD

**Issue by jarrod-marshall** [postmanlabs/newman#105]
I am attempting to test a service that exposes its API over https.
Everything works fine hitting this URL in Postman but when executing this in Newman I receive an error.

EXCEPTION - Syntax Error: Unexpected token u
RequestError: dfaa2798-66f5-00df-89f277629098 terminated. Error: undefined.

**Comment by pradgnya1** [comment]
Hi 
I am having the same issue with latest newman code - 1.2.16.
I can make calls in Postman package app but when I try to run the same collection using newman I am getting the error "RequestError: a65e56d2-e801-0e50-4634-6648b640eba3 terminated. Error: undefined".
I am using jumphost to connect to the services which are behind firewall.

Thanks

**Comment by abhijitkane** [comment]
@pradgnya1 Can you try the -k and -l flags? The -k flag will disable strict SSL checking.

**Comment by pradgnya1** [comment]
Thanks Abhijit using -k helped resolve the issue.

**Comment by pradgnya1** [comment]
I was able to get away from RequetError but it is still not able to go to the write service I am getting status =400.
1. Servers are behind firewall
2.Using Jumphost to access the services
3.using port forwarding
 
Running a simple collection which makes call to - https://localhost:4324/xyzKey/Id/8675309

Results in 400
newman -kl -c ~/Documents/getwithnotest.json

Iteration 1 of 1
400 611ms GetContentKey https://localhost:4324/contentKey/playableEntityId/8675309

Thanks in advance

**Comment by pradgnya1** [comment]
I looked more and I see issue thet is due to - No required SSL certificate was sent.
I have already opened the connection and it should go to there.

**Comment by tejdev** [comment]
I am having same issue working with postman calling a https service, but Newman fails with ssl hello server request failed. Anybody Abel to crack this?

**Comment by abhijitkane** [comment]
@pradgnya1 @tejdev Can you try the `--insecure` and/or `--tls` options? The `--insecure` option will disable strict SSL checks.

**Comment by tejdev** [comment]
I tried those options and this api needs ssl.

**Comment by tejdev** [comment]
These are like enterprise apis which need ssl and Ian just not able to get respond with success using Newman. If there is an option to disable ssl, that means Newman should be able to call https right. I'm trying to understand how will it know the details about which cert to use etc..

**Comment by jackrabb1t** [comment]
I tried using the insecure and tls options ( trying different combinations ), but I still continue to get this error.

Newman version 1.2.28

**Comment by krishna6100** [comment]
I am also facing the same issue with ssl certificates, is there any update on this ?
Using newman version -2.1.1

**Comment by riccardo-89** [comment]
hi, also having same issue trying to contact api gateway with newman, any news?
