### ISSUE TITLE
Newman run should not return success with a not found collection

### ISSUE THREAD

**Issue by etaty** [postmanlabs/newman#1055]
**I believe this bug can have huge consequence with an continuous integration system!!!**

 1. Newman Version (can be found via `newman -v`): 3.6.0
 2. OS details (type, version, and architecture): docker & osx
 3. Are you using Newman as a library, or via the CLI? cli
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
`newman run https://www.getpostman.com/collections/651de8da5b5f-not-found`
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):
<img width="575" alt="screen shot 2017-06-03 at 10 27 38" src="https://cloud.githubusercontent.com/assets/461170/26752432/530bd0b2-4847-11e7-9a10-f86a5934e346.png">

Steps to reproduce the problem:

`newman run https://www.getpostman.com/collections/651de8da5b5f-not-found`
`echo $?` shows `0`

**Comment by shamasis** [comment]
Very valid. This should be for both collection and environments. Global too. 

Ideal behaviour:

- this should apply for both URL and file based arguments

- it should not fail for empty collection / environment

- it should fail if the input object does not have base structure of collection / environment 

- it should fail on non 200 response from input URLs (but should follow redirects)

**Comment by Nasafato** [comment]
That would be awesome. Also, it would be nice if you included Folders in there, too. Since if you try to run `newman` on a folder that doesn't exist, it will also pass all the tests #1061.

**Comment by kunagpal** [comment]
@etaty A fix for this bug has been added in #1115

**Comment by kunagpal** [comment]
@etaty This bug has been fixed in Neman v3.7.5

**Comment by jvkaam** [comment]
Are you sure this is fixed? I'm running with 3.8.0 and when I feed newman with a regular json file (not a postman collection) it exits without an errorlevel..

**Comment by kunagpal** [comment]
@jvkaam It appears that your issue is distinct from the thread here, could you open fresh issue at https://github.com/postmanlabs/newman/issues/new? Thanks!

**Comment by jvkaam** [comment]
Thanx, added: [https://github.com/postmanlabs/newman/issues/1171]

**Comment by RodrigoFragoso** [comment]
https://github.com/postmanlabs/newman/issues/1055 - Was this issue resolved? I am facing a difficulty in version 5.0.1 Newman, if I pass a FOLDER, I receive the successful response.

**Comment by m3dbedb** [comment]
in 5.3.2 non-existing folder breaks the execution with no error:
(folder 2 does not esist)
root@kern62:/git/pb-test-v1 #  newman run pb_v1_auto.json -e  stand-env.json --folder 1 --folder 2
output:
newman

PBauto v1 - v2

┌─────────────────────────┬──────────┬──────────┐
│                         │ executed │   failed │
├─────────────────────────┼──────────┼──────────┤
│              iterations │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│                requests │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│            test-scripts │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│      prerequest-scripts │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│              assertions │        0 │        0 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 6ms                       │
├───────────────────────────────────────────────┤
│ total data received: 0B (approx)              │
└───────────────────────────────────────────────┘
