### ISSUE TITLE
set exit code on failed tests.

### ISSUE THREAD

**Issue by DotNetRockStar** [postmanlabs/newman#1059]
Hi there.  I have been searching and searching for how to enable exit code > 0 when a test fails but i cannot get it to work to save my life.

**newman version:** 3.6.0
**command that runs tests:** newman run https://api.getpostman.com/collections/{myCollectionId}?apikey={myApiKey}

What do I need to add to this command to make the console return an exit code > 0 when execution of these tests fail?  If you could please paste an example that would be most helpful.  

Thanks in advance.

**Comment by kunagpal** [comment]
@DotNetRockStar A non zero exit code is returned by default for collection run failures. Could you share more details about the node version(`node -v`), and the operating system/environment where newman is being used? Also, could you check and share the exit code for `newman run ...` as follows:
For Windows:
```
echo %errorlevel%
```

Other operating systems:
```
echo $?
```

**Comment by DotNetRockStar** [comment]
Something I forgot to leave out is that I am using Powershell to script execution of the tests inside of Octopus Deploy.

In command prompt:
when i did echo %errorlevel% the value is:
1

I am on Windows 10
I also need to run this on Windows 2012 R2

If the exit code is working in a batch file/command prompt then it should be working in powershell right?  The problem is that my powershell script is not suggesting that it is exiting with the code 1.

**Comment by kunagpal** [comment]
Since you're using PowerShell, could you check the return code as follows:
```
// newman run .... goes here
echo $LastExitCode
```

```
// newman run ... goes here
echo $?
```

**Comment by DotNetRockStar** [comment]
Thanks @kunagpal.  The exit code is indeed that is returned is 1. Should I store this in a variable, test to see if it is greater than 0, then issue an actual exit of the script if it is > 0?  Or is the intention that newman should be performing the "exit 1"?

**Comment by kunagpal** [comment]
https://octopus.com/blog/powershell-exit-codes

**Comment by czardoz** [comment]
@DotNetRockStar Newman has no control over your shell script, so you will have to issue it manually. 

If you want it to happen automagically, I guess you can refer to this: https://stackoverflow.com/questions/9948517/how-to-stop-a-powershell-script-on-the-first-error :)

**Comment by DotNetRockStar** [comment]
Okay, cool.  That is exactly what I was about to try.  I'll look for the exit code and handle it in the script appropriately.  Thanks!
