### ISSUE TITLE
HTML Reporter exception

### ISSUE THREAD

**Issue by DotNetRockStar** [postmanlabs/newman#1060]
I am getting a very weird error when I try to run tests and use the html reporter to spit out an html file for me.  Here is the command I am using (api key starred out for security purposes):
C:\Users\MY_USERNAME\AppData\Roaming\npm\newman run https://api.getpostman.com/collections/01bfe56f-9cdd-7b94-3b66-9f8f6cc82ddc?apikey=************ --reporters cli,html --reporter-silent --reporter-html-export "c:/test/Authorization.html"

I am using Windows Server 2016
I am running Newman version 3.6.0
c:/test folder exists before executing command.
Attached is the command prompt error I get

<img width="561" alt="newman error" src="https://user-images.githubusercontent.com/9408944/26950302-c733fd06-4c62-11e7-932d-61bc499e6125.png">

Thanks in advance!

**Comment by kunagpal** [comment]
Duplicate of #1048

**Comment by DotNetRockStar** [comment]
Wait, so this is a duplicate of #1048 and it was resolved saying that I need to comment out a line of code from the actual source to fix this?  It is not clear to me what the solve was in #1048.

**Comment by kunagpal** [comment]
The issue has been fixed in #1062, I'll update this thread when a new version has been released.

**Comment by czardoz** [comment]
I just re-opened it. Github had auto-closed it because of the PR description, @DotNetRockStar :smile:

**Comment by kunagpal** [comment]
This issue has been fixed in Newman v3.6.1, do check it out 😄
