### ISSUE TITLE
How can I fail Jenkins build if any assertions fail using newman run?

### ISSUE THREAD

**Issue by rajbhandaris** [postmanlabs/newman#1064]

**Comment by kunagpal** [comment]
By default Newman exits with a non-zero return code for failed runs. More information can be found here: https://github.com/postmanlabs/newman/issues/1020#issuecomment-301399504. Feel free to revert if you're facing issues 😄

**Comment by rajbhandaris** [comment]
information here http://blog.getpostman.com/2015/09/03/how-to-write-powerful-automated-api-tests-with-postman-newman-and-jenkins/ ONLY works for newman but not for newman run
I am using newman version 3.5.2
Sample newman run command: newman run test.postman_collection.json -e test.postman_environment.json

**Comment by kunagpal** [comment]
Yes, as this post was written for a version of Newman that is now deprecated. You can check out https://github.com/postmanlabs/newman/blob/develop/MIGRATION.md to bridge the gap, so to speak.

**Comment by rajbhandaris** [comment]
can you give me a working example?

**Comment by czardoz** [comment]
@rajbhandaris Newman will by default exit with a non-zero status code. I am not all that familiar with Jenkins, so I cannot give you a working example, but there are a number of Jenkins users on our Postman Community Slack. Feel free to join up [here](https://www.getpostman.com/slack-invite), and I am sure someone will be able to help you out :)

**Comment by rajbhandaris** [comment]
I have joined the Postman Community Slack channel and posted my question. I don't know who will respond to my question when. Please do not close this issue until it is resolved. Thanks!

**Comment by czardoz** [comment]
@rajbhandaris Feel free to comment here if you're having issues with Newman, and I will re-open this issue :)

For help with Jenkins, I won't be able to help much unfortunately, but the Jenkins docs should help: https://jenkins.io/doc/pipeline/tour/running-multiple-steps/
