### ISSUE TITLE
Facing Issue while generating Newman report Through Jenkins Pipeline

### ISSUE THREAD

**Issue by abhishek-kandala** [postmanlabs/newman#1068]
Hello,
I am trying to generate Newman Report through Jenkins Pipeline. I have added my postman collection in my bitbucket repository and add the location in jenkinsfile.yaml "newmanScriptDir: test". I have even added "mail" parameter to whom I need to send the HTML reports. My scenario is after the API is deployed to an environment it should run my collection and generate the Newman report and send it as an attachment.
Currently, in Jenkins, the API is getting deployed but while running the collection it's generating an error " Failed in Newman Branch" but its able to fetch the collection. I can see that in the Jenkins build console.log. 
Command used in Jenkins pipeline is "newman run test/postman_collection.json --insecure --reporters html"

**Comment by czardoz** [comment]
@abhishek-kandala Your best bet is to enable the CLI reporter using `--reporters html,cli` and debugging the error from there. I suspect it has nothing to do with Newman, and are probably actual errors caught by Newman. 

If you think it's a Newman bug, feel free to re-open this issue :)
