### ISSUE TITLE
CSS styles missing in HTML report when opened from Jenkins UI dashboard

### ISSUE THREAD

**Issue by mayukataoka** [postmanlabs/newman#1069]
newman 3.6.1.

  
The CSS styles are missing in the HTML test report when it is opened from the Jenkins UI dashboard.  Without using the Jenkins UI, if I directly open the html report.  The CSS styles work.

**Comment by czardoz** [comment]
It's probably your servers content security policy that is now allowing the styles to show up. Unfortunately, there's nothing we can do in this case.
