### ISSUE TITLE
Not able to execute Postman collection when base URL is passed from Env Variable

### ISSUE THREAD

**Issue by mrjaiswar** [postmanlabs/newman#1071]
Newman version - 3.1.1
windows 7 64 bit
Nodejs v5*

Same works when I execute from Postman when throws error when executed via Newman
Command line - newman run https://www.getpostman.com/collections/3b56786e1884f1f74e62

Error - 
Test Newman

→ Authenticate
  POST {{url}}/api/user/authenticate [errored]
  2? ReferenceError in test-script

┌─────────────────────────┬──────────┬──────────┐
│                         │ executed │   failed │
├─────────────────────────┼──────────┼──────────┤
│              iterations │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│                requests │        1 │        1 │
├─────────────────────────┼──────────┼──────────┤
│            test-scripts │        1 │        1 │
├─────────────────────────┼──────────┼──────────┤
│      prerequest-scripts │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│              assertions │        0 │        0 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 2.5s                      │
├───────────────────────────────────────────────┤
│ total data received: 0B (approx)              │
├───────────────────────────────────────────────┤
│ average response time: 0ms                    │
└───────────────────────────────────────────────┘

  #  failure        detail

 1.  Error          Invalid URI
                    "http:///%7B%7Burl%7D%7D/api/user/authenticate"
                    at request
                    inside "Authenticate" of "Test Newman"

 2.  ReferenceErr.  responseCode is not defined
                    at test-script:1:32
                    inside "Authenticate" of "Test Newman"

![image](https://user-images.githubusercontent.com/11874038/27088840-6ddc32e2-5076-11e7-8179-4bdd8b37df90.png)

 1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by czardoz** [comment]
@mrjaiswar Check the readme for an example of how to provide an environment to Newman (it's the `--environment` option).
