### ISSUE TITLE
Newman run DELETE request fails - ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by cedricherve** [postmanlabs/newman#1072]
1. Newman Version (can be found via `newman -v`): v3.3.0
 2. OS details (type, version, and architecture): Windows
 3. Using newman as a library of NodeJs 6.1.0
 4. Bug always occured

Steps to reproduce the problem:

1. I use postman to execute my API automated tests
2. I export my collection containing about 4-6 requests (GET, POST, PUT, DELETE)
3. I run newman with the followings command line

`newman run -k MY_COLLECTION.postman_collection.json --environment $ENVIRONMENT.postman_environment.json --folder MY_FOLDER --reporters cli,json,html,junit --reporter-json-export outputfile_MY_FOLDER.json --reporter-html-export --reporter-junit-export --timeout-request $TIMEOUT --bail`

4. I expect to have my tests passed just like in newman : all tests ok apart from DELETE which fails with the following error

` 1.  Error    ESOCKETTIMEDOUT
              at request
              inside "PRIVATE - users [DELETE]" of "USERS"
`
![screenshot](https://user-images.githubusercontent.com/8657436/27125702-6c923830-50f5-11e7-981d-7825d0fc058a.png)

I searched in many forums, might be an issue with content-type & content-length response when HTTP CODE is 204 which would mean that newman expects a json response. A response which remains empty by the way with HTTP CODE 204.

But not sure about it?

Can you please confirm ? Known issue or something wrong/missing with my environment ?

**Comment by czardoz** [comment]
@cedricherve A socket timeout means that Newman could not connect to your server. Do you use a firewall or a proxy? Those sometimes block DELETE requests.

**Comment by cedricherve** [comment]
In fact i'm a local environment

I can see trace and logs on my API server side : deletion is well done, ie newman is able to access to the server.

Just remains this issue with newman and esockettimeout.

Is there a way to see verbose logs with newman?

**Comment by czardoz** [comment]
Yes, can you set an environment variable "NODE_DEBUG" to the value "http" and run Newman? It would help us debug. Remember to scrub out any sensitive information, endpoints, auth data etc.

**Comment by cedricherve** [comment]
Before launching the newman command line, I set 
'set NODE_DEBUG=http'

FI, I'm on a windows environment.

But it changes nothing on my terminal, none additional logs.

Anyway, I found in xml report result the following error

```
  <testsuite name="PRIVATE - families [DELETE]" id="7793ddca-64c0-4bc0-ab42-7884e582f8e8" tests="0" time="0">
    <error>
      <![CDATA[Iteration: 0
RequestError: Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (<PATH>AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\node_modules\postman-request\request.js:786:19)
    at ClientRequest.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:626:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)

---
]]>
    </error>
```

Just confirm that it's a esockettimeout

`  self.req.on('socket', function(socket) {
    var setReqTimeout = function() {
      // This timeout sets the amount of time to wait *between* bytes sent
      // from the server once connected.
      //
      // In particular, it's useful for erroring if the server fails to send
      // data halfway through streaming a response.
      self.req.setTimeout(timeout, function () {
        if (self.req) {
          self.abort()
          var e = new Error('ESOCKETTIMEDOUT')
          e.code = 'ESOCKETTIMEDOUT'
          e.connect = false
          self.emit('error', e)
        }
      })
    }`

I don't see how newman could fail at timeout if request response status code is 204 (ie. no content), why should it be waiting for any response?

A workaround for my automated test should be to set header status code to 201 but it would not be compliant with REST rules.

**Comment by czardoz** [comment]
@cedricherve I _think_ your server might be setting a content-length / content-type header, which can be confusing for Node.

I cannot say for sure without debug logs though. Can you try setting the `NODE_DEBUG` variable to `http,https,net`?

**Comment by kunagpal** [comment]
@cedricherve Does this issue still persist for you?

**Comment by cedricherve** [comment]
At the moment no, I using a framework API which by default set content-length / content-type to output response.
Just like czardoz said: I think that should be the key element to workaround this behaviour from newman.

Anyway I think I won't use newman at the end to automate full tests : on my portal, and with postman it works, I am not going to change source code just to make the automated test work with newman.

I don't know if I should close this defect, because to me it remains a defect. What do you think?
