### ISSUE TITLE
using newman to run file-post request, the file path being defined in data file (option -d)

### ISSUE THREAD

**Issue by sophiejacquin** [postmanlabs/newman#1073]
Newman Version (can be found via newman -v): 3.5.2
    OS details (type, version, and architecture): ubuntu 16,04 64 bits
    Are you using Newman as a library, or via the CLI? CLI
    Did you encounter this recently, or has this bug always been there: always
    Expected behaviour: 

I want to send a post-file request from newman, I follow what is explained [here](https://www.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman)
and it works well as long as the file to post is fix in advance in the collection. However I'm trying to run newman with a file upload for different set of files. I'm using "-d" and specifying a json file with the additional filepaths. Unfortunately, it iterates with only the one file mentioned in the collection.
I guess that the problem is due to the fact that in the formdata for the type "file" there is no key "value" but a key "src".
Does a solution already exist to overcome this issue?

**Comment by kunagpal** [comment]
@sophiejacquin Could you share the collection and data file that causes this issue? Also, for the sake of completeness, please mention your Node version as well. 😄

**Comment by sophiejacquin** [comment]
@kunagpal My node version is v6.10.3.
For example these are problematic files ( I just change the extension as json format is not accepted):
[data.json.txt](https://github.com/postmanlabs/newman/files/1094011/data.json.txt)

[database_init.postman_collection.json.txt](https://github.com/postmanlabs/newman/files/1094004/database_init.postman_collection.json.txt) 

My problem is that when i run the collection with the data file 

newman run ./postman_collections/pre_post_treatment/database_init.postman_collection.json -e ./postman_environments/test2_superadmin.postman_environment.json  -d ./test_data/data.json 
it is not the datafiles defined in data.json that are used:
```
"opdp_file":"opdb/database2/opdb.sql",
    "dbtenant_file": "opdb/database2/dbtenant.sql",
    "dbmonitor_file": "opdb/database2/dbmonitor.sql",
    "dbadmin_file":"opdb/databaes2/dbadmin.sql"
```
 but allways the one  files mentionned in the collection:
```
{
							"key": "opdb_file",
							"type": "file",
							"src": "opdb/database1/opdb.sql"
						},
						{
							"key": "dbtenant_file",
							"type": "file",
							"src": "opdb/datbase1/dbtenant.sql"
						},
						{
							"key": "dbmonitor_file",
							"type": "file",
							"src": "opdb/database1/dbmonitor.sql"
						},
						{
							"key": "dbadmin_file",
							"src": "opdb/databse11/dbadmin.sql",
							"type": "file"
						},
						

```

**Comment by kunagpal** [comment]
As a temporary workaround, could you see if the following collection works for you?
```json
{
	"variables": [],
	"info": {
		"name": "database_init",
		"_postman_id": "81282ddb-f869-cf82-8a9e-81e85e6f1ebe",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "initialize_database",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"tests[\"Status code is 200 -> \"+ responseCode.code] = responseCode.code === 200;",
							"",
							""
						]
					}
				}
			],
			"request": {
				"url": "{{base_url}}/api/v1/admin/databases/load_from_files",
				"method": "POST",
				"header": [
					{
						"key": "Authorization",
						"value": "Token {{Token}}",
						"description": ""
					}
				],
				"body": {
					"mode": "formdata",
					"formdata": [
						{
							"key": "opdb_file",
							"type": "file",
							"src": "{{opdb_file}}"
						},
						{
							"key": "dbtenant_file",
							"type": "file",
							"src": "{{dbtenant_file}}"
						},
						{
							"key": "dbmonitor_file",
							"type": "file",
							"src": "{{dbmonitor_file}}"
						},
						{
							"key": "dbadmin_file",
							"type": "file",
							"src": "{{dbadmin_file}}"
						}
					]
				},
				"description": "load mysql file into the databases"
			},
			"response": []
		}
	]
}
```

**Comment by kunagpal** [comment]
Hey @sophiejacquin, does this issue still persist for you with the latest versions of Newman (v3.7.6) and the app (5.1.2)?

**Comment by rkortmann** [comment]
@kunagpal I'm on Newman 3.7.6 and still get this issue. Using the `src` attribute hardcoded works correctly, but passing the `src` attribute with a variable attempts to pass the variable name as a string resulting in: `form-data: ENOENT: no such file or directory, open '{{file}}'`

Relevant folder in collection file
```
{
	"name": "Create Content",
	"event": [
		{
			"listen": "test",
			"script": {
				"type": "text/javascript",
				"exec": [
					"var res = JSON.parse(responseBody);",
					"",
					"if(responseCode.code === 200 && res.status == \"ok\") {",
					"    tests[\"Response OK\"] = true;",
					"} else {",
					"    console.log(res);",
					"}",
					"",
					"if(res.data.content_id) {",
					"    postman.setEnvironmentVariable(\"beer_E_content_id\", res.data.content_id);",
					"    tests[\"Beer E Content ID \" + res.data.content_id] = true;",
					"}"
				]
			}
		}
	],
	"request": {
		"url": "http://localhost/v1/contents",
		"method": "POST",
		"header": [
			{
				"key": "Authorization",
				"value": "Bearer {{test_token}}",
				"description": ""
			}
		],
		"body": {
			"mode": "formdata",
			"formdata": [
				{
					"key": "file",
					"src": "{{file}}",
					"type": "file",
					"value": ""
				},
				{
					"key": "name",
					"value": "{{name}}",
					"description": "",
					"type": "text"
				},
				{
					"key": "content_type_id",
					"value": "{{content_type_id}}",
					"description": "",
					"type": "text"
				},
				{
					"key": "client_id",
					"value": "{{test_org_id}}",
					"description": "",
					"type": "text"
				},
				{
					"key": "tags",
					"value": "{{tags}}",
					"description": "",
					"type": "text"
				},
				{
					"key": "content_action",
					"value": "{{content_action}}",
					"description": "",
					"type": "text"
				}
			]
		},
		"description": ""
	},
	"response": []
}
```

Data file:
```
[
    {
        "file" : "content/oc_beer_emoji_dude.png",
        "name" : "Beer Emoji Dude",
        "content_type_id" : "emo",
        "tags" : "{\"topic\":[{\"val\":\"drunk\"}],\"sen\":[{\"val\":\"happy\"}],\"geo\":[{\"val\":\"bar's\"}],\"cult\":[],\"brs\":\"889C7B\",\"lic_type\":\"C4C23D\",\"lic_term\":\"E\",\"lic_origin\":\"E Partners\"}",
        "content_actions" : "{}"
    }
]
```

**Comment by sophiejacquin** [comment]
Hello,

@kunagpal  Sorry for not having answer earlier, but the work around works very well!

Thank you !

**Comment by kunagpal** [comment]
@rkortmann Apologies for the delay but this looks like an issue with the environment variable setup.
@sophiejacquin Glad to hear it worked out for you 😄

**Comment by andreapaddeu** [comment]
@sophiejacquin where are your sql files located? in the same dir as your collection?
