### ISSUE TITLE
Send notification with test result to different channels(feature request)

### ISSUE THREAD

**Issue by pradeepkusingh** [postmanlabs/newman#1075]
1. Newman Version (can be found via `newman -v`): : NA
 2. OS details (type, version, and architecture): Linux
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: NA
 4. Expected behaviour: Send notification to different channel like emails, Slack
 5. Command / script used to run Newman: NA
 6. Sample collection, and auxilliary files (minus the sensitive details):NA
 7. Screenshots (if applicable):NA

**Comment by kunagpal** [comment]
@pradeepkusingh This can be done by adding a request to your collection, which points to a preconfigured Slack web hook url. Slack web hook urls are documented here: https://api.slack.com/incoming-webhooks

**Comment by pradeepkusingh** [comment]
How can I capture the result to send on notification ?

Thanks,
Pradeep Singh
Please excuse typos.
