### ISSUE TITLE
PUT Request not working

### ISSUE THREAD

**Issue by jltoo** [postmanlabs/newman#1078]
I'm trying to do a PUT Request via terminal using newman but instead it just do a GET request. This is working using POSTMAN and when I run it using newman this part just fails.

Version and environment information:
-->
 1. Newman Version (can be found via `newman -v`): 3.6.1
 2. OS details (type, version, and architecture): MACOS Sierra 10.12.1
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Recently
 4. Expected behaviour: should run a PUT request rather than GET Request
 5. Command / script used to run Newman: 
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):
<img width="717" alt="screen shot 2017-06-15 at 1 13 38 pm" src="https://user-images.githubusercontent.com/11288433/27166354-917896d0-51cc-11e7-8e7b-539425dd5649.png">

**Comment by czardoz** [comment]
Check your redirection settings. You can turn auto-redirect off in Newman using a command line flag :)

**Comment by jltoo** [comment]
@czardoz I got it working now. It's with the URL I've used. I removed the "/" before the parameters and now it works. I'm not sure why this is running PASSED with POSTMAN . Thanks anyway.
