### ISSUE TITLE
Can not run other command in bat file after newman command

### ISSUE THREAD

**Issue by sisillV** [postmanlabs/newman#1090]
Hi Newman team,
I try to run a bat file that first change my database then run postman test and then clear the data base.
I I do steps manually in the console everything is ok.
But when i put them in bat file, the command after newman command don't start at all and the cmd is closed.

Can you give me some advice?

bat file :
```
c:
cd C:\Users\yyyy\Documents\Postman
ChangeDB.exe
newman run XXXXXX.postman_collection.json -g globals.postman_globals.json -r html
CleanDB.exe
```

After "newman run XXXXXX.postman_collection.json -g globals.postman_globals.json -r html"
the cmd is closed.
The problem is not in CleanDB.exe I can not run even "cd C:\Users\test" or "pause" after newman command

Version and environment information:
-->
 1. Newman Version (can be found via `newman -v`):3.6.1
 2. OS details (type, version, and architecture):Win 10
 3. Are you using Newman as a library, or via the CLI? not library
 3. Did you encounter this recently, or has this bug always been there: always
 4. Expected behaviour:
 5. Command / script used to run Newman:

bat file :
```
c:
cd C:\Users\yyyyy\Documents\Postman
ChangeDB.exe
newman run XXXXXX.postman_collection.json -g globals.postman_globals.json -r html
CleanDB.exe
```
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by kunagpal** [comment]
@sisillV To ensure continuity across batch file commands, you'll have to prepend `call` to any custom commands, like so:
```bat
cd C:\Users\yyyyy\Documents\Postman
ChangeDB.exe
call newman run XXXXXX.postman_collection.json -g globals.postman_globals.json -r html
CleanDB.exe
```

**Comment by sisillV** [comment]
Thank you! It is working like this.
