### ISSUE TITLE
TeamCity keep logging this  exception "Incorrect property name." in logs

### ISSUE THREAD

**Issue by kharod** [postmanlabs/newman#1112]
In my TeamCity Build logs, I see the following:

##teamcity[testStarted name='xxxxTest Namexxxx' captureStandardOutput='true']
[11:41:22]
Incorrect property name.
Valid property list format is (name( )*=( )*'escaped_value'( )*)* where escape symbol is "|"

**Comment by kunagpal** [comment]
@kharod The newman teamcity reporter is a custom reporter, please file this issue at https://github.com/leafle/newman-reporter-teamcity/issues/new

**Comment by kharod** [comment]
Thanks @kunagpal
