### ISSUE TITLE
Powershell can't seem to properly handle the output from newman reporters

### ISSUE THREAD

**Issue by jnarwold** [postmanlabs/newman#1116]
Version and environment information:
-->
 1. Newman Version: 3.7.0
 2. OS details: Windows 10
 3. I'm running Newman via bash script & powershell script
 4. Did you encounter this recently, or has this bug always been there: Recently. New code, new issue.
 5. Expected behaviour: Same output for both powershell & cmd
 6. Command / script used to run Newman:

```powershell
$collection='https://www.getpostman.com/collections/xxxxxx';
$environment='QA.postman_environment.json';
$output=$(newman run $collection -e $environment --reporter-cli-no-failures --reporter-cli-no-assertions --reporter-cli-no-console --no-color);

Write-Host $output;
```

```bash
collection='https://www.getpostman.com/collections/xxxxxx'
environment='QA.postman_environment.json'
newman_args='--reporter-cli-no-failures --reporter-cli-no-assertions --reporter-cli-no-console --no-color'
output=$(newman run $collection -e $environment $newman_args)
verbose=1

if [ "$verbose" -gt 0 ] ; then
    echo "$output"
fi
```

For both paths, my tests are run and I get the proper results. The problem I'm having is in the output of those results and the discrepancy between bash and powershell. My bash console renders things beautifully:

![image](https://user-images.githubusercontent.com/1001669/27933513-66d67504-6267-11e7-804d-96ae61fb4168.png)

Powershell on the other hand, not so much:
![image](https://user-images.githubusercontent.com/1001669/27933483-43629526-6267-11e7-8507-b76ccc264791.png)

Does powershell not support this format or am I just doing something totally off kilter in my script?

**Comment by shamasis** [comment]
Turn off coloured output. `--no-color` or something similar.

**Comment by kunagpal** [comment]
@jnarwold Could you also add `--disable-unicode` to your `newman run ...` command and see if that helps?

**Comment by jnarwold** [comment]
Good call @kunagpal - looking quite a bit closer to what I was expecting:

![image](https://user-images.githubusercontent.com/1001669/27964945-a7d10ffe-62ff-11e7-8bbe-ac23a5413229.png)
