### ISSUE TITLE
"ReferenceError" describe is not defined from Newman

### ISSUE THREAD

**Issue by bijoej** [postmanlabs/newman#1128]
Hi,

 I was using Postman with plenty of tests in collection and it runs fine from Postman.
 I had installed Newman and all the tests runs fine from command line using Newman.
 Also integrated to Jenkins and works so good.

 But recently came to know about PostmanBDD and tried making the tests using BDD style Java Script coding following the link: https://www.npmjs.com/package/postman-bdd. It runs fine from Postman but gives me the error while running from Newman.

 I have installed all latest versions of Newman then tried updating Node, Mocha many things but no luck.

Screenshot
![newman error screenshot](https://user-images.githubusercontent.com/16103948/28210180-0eeeab4a-688e-11e7-8959-e1a6ea920b77.png)

Could you please help me on this.

Regards
Bijo

**Comment by BigstickCarpet** [comment]
Hi, @bijoej.  I'm the author of PostmanBDD, and I'd be glad to help you with this problem.  I test Postman BDD in the Postman app and in the Newman CLI on my Mac. I also test it using Newman on [Linux](https://travis-ci.org/BigstickCarpet/postman-bdd/jobs/241760921#L1509) and [Windows](https://ci.appveyor.com/project/BigstickCarpet/postman-bdd/build/1.0.36/job/ressrhn1m4edcalb#L1612), but perhaps my tests don't cover your use-case.  If so, I definitely want to address that.

Can you do a few things to help me diagnose this issue for you...

1. Please tell me what operating system you're using

2. Please tell me what version of the Postman app you're using (go to Settings -> About). Also please indicate whether you're running "_Postman for Chrome_" or one of the native apps (such as "_Postman for Windows_")

3. Please tell me what version of Newman you're using (`newman -v`)

4. Try running the [Postman BDD example collection](https://documenter.getpostman.com/view/220187/postman-bdd-examples/6Z3uY71) in your Postman app and in Newman, and let me know if it runs successfully for you.
**Postman App:** You need to **disable** the "_Automatically follow redirects_" option first
**Newman:** `newman run postman_bdd_collection.json --ignore-redirects`

5. If possible, please send me a sample collection that reproduces the problem

**Comment by bijoej** [comment]
Hi @BigstickCarpet,

 Please find the answers for you Questions below:

1. OS X EI Capitan Version: 10.11.6
2. Postman App Version: 5.0.2 [Postman for Chrome]
3. Newman Version: 3.7.5
4. Tried the sample and it fails the Cookies Tests while running from Postman but all the tests goes green from Newman.
5. Screenshot of Tests TAB in Postman:
![postman_tests_tav_screenshot](https://user-images.githubusercontent.com/16103948/28262423-cbb0f528-6ada-11e7-90da-b5e033db3351.png)

**Comment by BigstickCarpet** [comment]
@bijoej - I recommend that you install [Postman for Mac](https://www.getpostman.com/apps).  The Postman for Chrome app [is deprecated](https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html), and we're encouraging all users to [migrate to the native apps](http://blog.getpostman.com/2017/03/14/going-native/).

It looks like you're not installing PostmanBDD as part of your collection.  Please see the [installation instructions](https://github.com/BigstickCarpet/postman-bdd/#installation).  Basically, you need to make sure that your collection starts with a `GET` request to `http://bigstickcarpet.com/postman-bdd/dist/postman-bdd.min.js`; otherwise, PostmanBDD isn't available, which is why you get the "_describe is not defined_" error message.

**Comment by bijoej** [comment]
Thanks @BigstickCarpet ...finally got it resolved.
First mistake from my side was, I ran the postman installation before making the other tests but didn't have it in my collection.
Secondly after keeping the postmanBDD GET request in my collection, it was still failing as the postmanBDD GET request was running after my test, so changed the order and it worked.

Thanks once again.

**Comment by BigstickCarpet** [comment]
Happy to help.  Glad you got it working!

**Comment by michelics** [comment]
Hello,

I need help about header configuration for GET Postman BDD:

![image](https://user-images.githubusercontent.com/15693278/36806044-9ce939e2-1c9d-11e8-9031-e739fcab3666.png)

Can someone help me? :)

**Comment by RamyaRamasamyCentrica** [comment]
hi i followed the above steps. I copied that postman-bdd.min.js and I opened using webserver in my machine like http://localhost:8090/postman/postman-bdd.min.js and moved it as first request .still i'm getting describe is not defined error.Please help me
