### ISSUE TITLE
Is it compulsory to provide full path of the newman,in order to run the postman json files

### ISSUE THREAD

**Issue by ckanakadas** [postmanlabs/newman#1134]
I have a bamboo plan which is connected to run the node.js files. But when i run the **newman run command** in the server its running fine. But when i try to run from the bamboo UI im getting below error
module.js:471
throw err;
Error: Cannot find module '/datavg/bamboo-home/xml-data/build-dir/131073/ZD-TES-JOB1/newman'
at Function.Module._resolveFilename (module.js:469:15)

But when i give full path like /usr/bin/newman its working fine. How to sort this ?

**Comment by ckanakadas** [comment]
Its very urgent can you please provide the solution

**Comment by kunagpal** [comment]
@ckanakadas Could you also share:
* The target operating system involved.
* The version of Newman for which this happens.
* The relevant bamboo CLI configuration, sans sensitive details.
* The version of Node(`node -v`) and npm(`npm -v`) on which this happens.

In addition to the above, please mention whether Newman was installed globally (using `npm install -g newman`, or locally (without the `-g` flag).

**Comment by ckanakadas** [comment]
newman 3.7.6  and 3.10.10
Both the ways the newman is installed
Linux

**Comment by kunagpal** [comment]
@ckanakadas Based on the error message, it appears that the global Newman installs just fine, as `newman run ...` works correctly. As pointed out earlier, it'll be difficult to determine the exact cause without the relevant Bamboo configuration, as well as the node file being run. Please share those details, as well as how and where `/usr/bin/newman` is being used.

**Comment by ckanakadas** [comment]
@bamboo configuration plan the /usr/bin/newman is used
The configuration is in the client server and we dont have access for it

**Comment by zhlei616** [comment]
Hi there,
Did you resolve this issue? I got same issue now, if I run it in cmd window, everything is fine, but when I run the same command in Bamboo plan, got following error, I'm using the same bamboo admin user.
'newman' is not recognized as an internal or external command,
operable program or batch file.

**Comment by shamasis** [comment]
This appears to be a Bamboo specific issue. I'm afraid, none of us use Bamboo out here. But I did spot a number of issues (both solved and still open) around NodeJS CLI packages not properly working on Bamboo. Most of them were usually a configuration change or little tweaks to fix.

Have a look at https://confluence.atlassian.com/bamboo/getting-started-with-node-js-and-bamboo-687213472.html and https://confluence.atlassian.com/bamboo/getting-started-with-node-js-and-bamboo-687213472.html

Google has some useful resources. Also, we can discuss this on the Postman Community https://community.getpostman.com/ to see if anyone having worked with Bamboo has something more to add.
