### ISSUE TITLE
Newman html report is not showing separate failed test like cli output.

### ISSUE THREAD

**Issue by Srisaibersys** [postmanlabs/newman#1141]
1. Newman Version: 3.7.6
 2. OS details (type, version, and architecture): Windows 7, 64 bit
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Seeing it First Time
 4. Expected behaviour: html report should show separated failed test like CLI
 5. Command / script used to run Newman: `newman run "data.postman_collection.json" -e "prod.postman_environment.json" --reporters cli,html --reporter-html-export report.html` 
  7. Screenshots (if applicable): 
![report](https://user-images.githubusercontent.com/18466695/28551613-588745c6-70a6-11e7-8db2-e3b9b6870205.png)

*Step to Reproduce*
1. Run command `newman run "data.postman_collection.json" -e "pro
d.postman_environment.json" --reporters cli,html --reporter-html-export report.html`
2. This is generating CLI & Html report. Looks like CLI is printing failed test at the end. 
3. I couldn't see failed test in the HTML report. Do we need to provide any configuration option to show only failed test in html report.
4. I need something similar highlighted at the end of above screenshot in html report.

**Comment by kunagpal** [comment]
@Srisaibersys Although the inbuilt HTML reporter does not show failed assertion details like the CLI reporter, you can accomplish this by building your own custom reporter, by following the instructions here: https://www.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman#custom-reporters

Feel free to get back if you're facing difficulties 😄

**Comment by Srisaibersys** [comment]
Hey @kunagpal,

Thank you to pointing me to correct way to move with this.

I tried to create custom `myreporter` which is named as `newman-reporter-myreporter`
**Steps Followed**
* `npm init`
* Added index.js
* Installed this package locally using running `npm install` in the same directory.
* If I look for locally installed packages(`npm list`) then it's showing me that package(`newman-reporter-myreporter@1.0.0`) in the list

Now I am trying to run api tests using command

**Comment by dlpooja89** [comment]
@Srisaibersys Can you share the custom report you created ?

**Comment by cbarlow1993** [comment]
I'm getting an identical issue. 
The documentation is not clear on how one creates, installs and uses a new customer reporter. There are examples of custom reporters but no help on how to use them. If anyone has any guidance, I'd love to hear.

**Comment by kunagpal** [comment]
@cbarlow1993 While the custom reporter documentation is currently present here: https://www.getpostman.com/docs/v6/postman/collection_runs/command_line_integration_with_newman#custom-reporters, I'll be adding it to the repository README in a few days, which will help prevent unnecessary redirection.

**Comment by pragyaparashar** [comment]
Hi, 
I want to count no. of assertions in all the test cases of a suite and print it in table. I tried a lot but not sure how to do that. Can anyone help me with that.
