### ISSUE TITLE
Newman HTML Report for Failure

### ISSUE THREAD

**Issue by harikirancs224** [postmanlabs/newman#1150]
1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

I was looking at the html report generated and l also integrated with jenkins but I was wondering I was unable to look at the failures
Example:
          I have a failure in 50th result but I need to scroll down to all and find which is a failure 
          no link to click on the failures which will scroll you there

**Comment by kunagpal** [comment]
@harikirancs This can be accomplished with the help of a custom HTML reporter template, documented [here](https://github.com/postmanlabs/newman#html-reporter-options). A sample of the data object passed to the HTML reporter template can be found here: https://github.com/postmanlabs/newman/blob/develop/examples/reports/html-reporter-template-data.json.

Feel free to get back if you have any other questions 😄
