### ISSUE TITLE
Issue while publishing Newman html report in Jenkins

### ISSUE THREAD

**Issue by KishoreMeda** [postmanlabs/newman#1151]
Hi,
Help required while publishing Newman HTML in Jenkins Post-Action.
Jenkins is not identifying Test Results from HTML report.

**Comment by kunagpal** [comment]
@KishoreMeda https://wiki.jenkins.io/display/JENKINS/HTML+Publisher+Plugin would shed some more light on this issue.

**Comment by KishoreMeda** [comment]
Hi Kunagpal,
Thanks for the quick response. 
Actually I am able to publish the html report as a link within Jenkins page but, it is not considering to display in "Test result trend". Appreciate if you provide help to configure "Test Result Trend" from newman generated html report.

Thanks & Regards,
Kishore

**Comment by prakharjoshi** [comment]
@KishoreMeda AFAIK this has nothing to do with Newman HTML report. There must be some configuration issue with your Jenkins.

Hope this helps you https://stackoverflow.com/questions/7731146/jenkins-test-result-trend-graph-empty-but-tests-are-run

**Comment by KishoreMeda** [comment]
@prakharjoshi Thanks for the info. Yes, I have done this already. 
Actual problem started with JUnit report only because, postman/newman considering each assertion within the Test script as a single 'testcase' while generating xml (JUnit) report. i.e., If a test script has 5 assertions newman JUnit report is giving count as 5 testcase so, JUnit report trend is displayed wrongly.

**Comment by prakharjoshi** [comment]
@KishoreMeda The things you mentioned above is the normal behaviour of Newman and the default reports work with the normal behaviour of Newman.

Each request can have multiple assertions and Newman will show the result for each assertion for a request. So Junit reporter is also providing an output with the same behaviour where each `testsuite` element is a request and under each element, we have `testcase` which are assertions for each request.

If you want the custom output you can create custom reporters https://github.com/postmanlabs/newman#creating-and-using-custom-reporters. There is a link of custom reporter created for Newman, you can refer to that too. Hope that helps you :)

**Comment by KishoreMeda** [comment]
@prakharjoshi Thanks for your prompt response.
I agree with you that JUnit report has the testsuite element for a request but, still I am not able to find the number of executions from that because JUnit report is treating multiple executions of a same test as single and all assertions are coming within a single testsuite (instead multiple testsuite/s) so, execution count is mismatching from actual count. I have created my own wrapper/script to generate custom JUnit kind of report from postman's html report to solve this issue.

**Comment by prakharjoshi** [comment]
@KishoreMeda As I mentioned earlier `testsuite` represent a request and `testcase`  under each `testsuite` represent assertions, so you will get multiple `testcase` for a `testsuite`.

So Junit reporter will trend to show single `testsuite` for a request and under that `testsuite` you will get multiple `testcase` (which represent assertions).  This is the behaviour of Newman and that is what is shown in Junit reporter. Even when you run Newman and choose reporter as cli you will observe the same behaviour. 

If you want some customized reporter you can go ahead and create a custom reporter according to your requirements. Hope that helps you.

**Comment by KishoreMeda** [comment]
@prakharjoshi Hi, yes I agree with you but, hear count is mismatched between html report and JUnit report because JUnit report has single testsuite for a request which have posted with different input however, html report has two different test requests. 
For example if i make a same get request with two different parameters HTML report has two saperate requests but, in JUnit report has single "TestSuite" with multiple "Testcases(assertions)" so, if you count how many requests you have made, HTML gives two but JUnit gives only one (this is wrong).
No worries, I thought it is Newman's behavior of creating JUnit so, I have my own wrapper to correct JUnit report details.

I am happy to close this case if you are ok with it.
Thanks & Regards,
Kishore

**Comment by prakharjoshi** [comment]
@KishoreMeda Can you provide the collection on which you are facing such issue? (Feel free to remove sensitive data from the collection)

**Comment by prakharjoshi** [comment]
@KishoreMeda seems like you have found your solution. Closing this issue, feel free to open it.

**Comment by trollcodelord** [comment]
Hi Guys,

I'm using Newman but i have few questions

Do we need "Newman" to be installed in the Jenkins Server??
Can we run Newman via Jenkins Server like rcon job ??
Is there any template where we get response VS time graph in output?

Thanks in Advance
