### ISSUE TITLE
Fail to authenticate via NTLM

### ISSUE THREAD

**Issue by AndreySurzhan** [postmanlabs/newman#1152]
1. Newman Version: `3.7.5`
 2. OS details (type, version, and architecture): `Win 7 Enterprise SP1 64-bit`
 3. Are you using Newman as a library, or via the CLI?: `CLI`
 3. Did you encounter this recently, or has this bug always been there: `n/a`
 4. Expected behavior: `newman should support NTLM auth`
 5. Command / script used to run Newman: `see below in test steps`
 6. Sample collection, and auxilliary files (minus the sensitive details): `n/a`
 7. Screenshots (if applicable): `n/a`
8. Node version: `6.9.4`

**Steps to reproduce:**
1. Have service with NTLM auth
2. Create postman collection with GET endpoint to that service
3. Setup test that endpoint with valid auth credentials (see `collection example`)
4. Run test 

```
newman run <COLLECTION URL/FILE PATH> --color --environment <ENV URL/FILE PATH> --reporters junit,cli,html --reporter-junit-export test_junit_format.xml --reporter-html-export test_html_format.html
```

**Actual result**: request fails with Auth error

**Collection example**
```
{
	"variables": [],
	"info": {
		"name": "-----",
		"_postman_id": "-----",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "Setup",
			"description": "----",
			"item": [
				{
					"name": "----",
					"event": [
						{
							"listen": "test",
							"script": {
								"type": "text/javascript",
								"exec": [
									""
								]
							}
						}
					],
					"request": {
						"url": {
							"raw": "----",
							"protocol": "https",
							"host": [
								"----",
								"---",
								"----"
							],
							"auth": {
								"user": "----",
								"password": "-----"
							},
							"path": [
								"-",
								"-",
								"-",
								"-"
							],
							"query": [
								{
									"key": "s-",
									"value": "-",
									"equals": true,
									"description": ""
								}
							],
							"variable": []
						},
						"method": "GET",
						"header": [],
						"body": {},
						"description": "-"
					},
					"response": []
				}
			]
		}
	]
```

Thanks

**Comment by shamasis** [comment]
NTLM is still under development. We will look into the issue reported though.

**Comment by czardoz** [comment]
@AndreySurzhan, you've chosen to provide a username and password as a part of your URL, which results in Basic Auth, not NTLM. In order to use NTLM, you need to define an `auth` key in your request. Check schema.getpostman.com for the exact structure :)

**Comment by AndreySurzhan** [comment]
@shamasis @czardoz Thanks for your responses.
@czardoz Looking at the [collection schema v2.0.0](http://schema.getpostman.com/json/collection/v2.0.0/collection.json) and there is no HTML auth type.
As @shamasis mentioned it is under development.

I guess there is no way run tests with requests that are using HTML auth via newman  right now, is it?

**Comment by kunagpal** [comment]
@AndreySurzhan Could you try this out with Newman v3.8.3 and see if it works correctly?

**Comment by AndreySurzhan** [comment]
@kunagpal I wish I could. But we've reworked our API recently. So I cannot retest it. We are not using NTLM auth anymore. Sorry
Let me know if I can do anything else

**Comment by AndreySurzhan** [comment]
I would appreciate a link to the commit with change that I can take a look at though

**Comment by kunagpal** [comment]
@AndreySurzhan This commit is not in Newman, but in `postman-runtime`, an underlying library that is used to ensure uniformity. The pull request in question can be found here: https://github.com/postmanlabs/postman-runtime/pull/390

**Comment by johan-v-r** [comment]
Hi All

The NTLM Authentication (Beta) in postman currently works fine for our site. However I'm still having issues executing this with newman cli.

After exporting from Postman Collection v2.1, my request looks like:
```
{
"name": "Index",
"event": [
	{
		"listen": "test",
		"script": {
			"type": "text/javascript",
			"exec": [
				"pm.test(\"Status code is 200\", function () {",
				"    pm.response.to.have.status(200);",
				"});",
				"",
				"pm.test(\"Body matches string\", function () {",
				"    pm.expect(pm.response.text()).to.include(\"test\");",
				"});"
			]
		}
	}
],
"request": {
	"auth": {
		"type": "ntlm",
		"ntlm": [
			{
				"key": "username",
				"value": "user",
				"type": "string"
			},
			{
				"key": "password",
				"value": "xxxxxxx",
				"type": "string"
			},
			{
				"key": "domain",
				"value": "",
				"type": "string"
			},
			{
				"key": "workstation",
				"value": "",
				"type": "string"
			},
			{
				"key": "disableRetryRequest",
				"value": false,
				"type": "boolean"
			}
		]
	},
	"method": "GET",
	"header": [],
	"body": {},
	"url": {
		"raw": "http://foo.bar.net",
		"protocol": "http",
		"host": [
			"foo",
			"bar",
			"net"
		]
	},
	"description": ""
},
"response": []
```

Any help would be appreciated.

**Comment by rathodamol** [comment]
Is there any update on the issue on NTLM auth using the newman cli ? 
I am still stuck :)
