### ISSUE TITLE
Running with a json file (not a postman collection) doesn't set an errorlevel

### ISSUE THREAD

**Issue by jvkaam** [postmanlabs/newman#1171]
1. Newman Version 3.8.0
 2. OS details (Windows 7):
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Yes always been there
 4. Expected behaviour: setting of errorlevel
 5. Command / script used to run Newman:
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

When you feed newman with a regular json file (not a postman collection) it seems it's running without a problem.. it doesn't set the errorlevel. 
The way we use Newman is by calling an api that uses our raml to generate a postman collection that also includes schema's and test scripts.. sometimes this goes wrong and an error is returned. The error is formatted as a json file. Newman should check if the file or url to run is a valid postman collection..

**Comment by prakharjoshi** [comment]
@jvkaam Newman will not attempt to validate the passed collection file against the schema. We can consider adding a `--strict` option (or something similarly named) to enforce valid collections.

In your case, you can keep a check on API response (which generates a postman collection) and then pass it to newman.

**Comment by jvkaam** [comment]
@prakharjoshi thanks for your response. The --strict option would be nice and for us to do a schema check on our generated postman collection is something we are considering but I still think that if we call Newman with a json file that's clearly not a postman collection you should set the errorlevel.

**Comment by shamasis** [comment]
The strict mode would open up a huge pit for newman to fall into! This would mean we would need to track collection schema versions in newman as well as add handling to URL response handlers. That's quite a lot of work and that too in the wrong place (sorry). 

Collection schemas are available for download and TV4 or there validation CLI can do the trick.

Closing this for now.
