### ISSUE TITLE
Existing global variables do not update their values if you try to change them using setGlobalVariable()

### ISSUE THREAD

**Issue by concordion2k** [postmanlabs/newman#1176]
1. Newman Version (can be found via `newman -v`): **3.8.0**
 2. OS details (type, version, and architecture): **macOS 10.12.6**
 3. Are you using Newman as a library, or via the CLI? **CLI**
 3. Did you encounter this recently, or has this bug always been there: **Recently**
 4. Expected behaviour: **Global variables can have their values overwritten using Newman as the test runner**
 5. Command / script used to run Newman:
```
newman run \
    https://www.getpostman.com/collections/collection-id \
    --global-var "groundboltBaseUrl=localhost:5020" \
    --global-var "groundboltToken=token"
```
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by concordion2k** [comment]
When I tried to reproduce this in the Postman UI, I could not. Global variables can be overwritten there.

**Comment by kunagpal** [comment]
@concordion2k Is this issue specific to variables passed via `--global-var`, regular global variables, or just any global variables?

**Comment by concordion2k** [comment]
The specific variable I was having an issue with was not one of the variables I passed via `--global-var`. My use case is specific to using regular global variables when running a collection using Newman.

**Comment by kunagpal** [comment]
I was unable to reproduce this issue on Node v6.11.2, Newman v3.8.1, with the following collection and global file:

Collection
```json
{
	"variables": [],
	"info": {
		"name": "newman-github-1176",
		"_postman_id": "96e4c39a-869c-d80d-eab3-17fca37d6400",
		"description": "An attempt to reproduce the issue outlined in https://github.com/postmanlabs/newman/issues/1176\n",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "https://postman-echo.com/get",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"tests['Global foo should have an initial value of `bar`'] = postman.getGlobalVariable('foo') === 'bar';",
							"postman.setGlobalVariable('foo', 'newval');",
							"",
							"tests['Global foo should have the value `newval`'] = postman.getGlobalVariable('foo') === 'newval';",
							"",
							"tests['Global alpha should have an initial value of `beta`'] = postman.getGlobalVariable('alpha') === 'beta';",
							"postman.setGlobalVariable('alpha', 'gamma');",
							"",
							"tests['Global alpha should have the value `gamma`'] = postman.getGlobalVariable('alpha') === 'gamma';",
							""
						]
					}
				}
			],
			"request": {
				"url": "https://postman-echo.com/get",
				"method": "GET",
				"header": [],
				"body": {},
				"description": ""
			},
			"response": []
		}
	]
}
```

Globals
```json
{
  "id": "673a4256-f5a1-7497-75aa-9e47b1dbad4a",
  "name": "Postman Globals",
  "values": [
    {
      "key": "foo",
      "value": "bar",
      "description": "",
      "type": "text",
      "enabled": true
    }
  ],
  "_postman_variable_scope": "globals",
  "_postman_exported_at": "2017-08-19T20:35:20.291Z",
  "_postman_exported_using": "Postman/5.2.0-beta05"
}
```

The command used was: `newman run collection.json -g globals.json --global-var "alpha=beta"`.

**Comment by concordion2k** [comment]
to be clear, I did not supply a globals JSON file to the command. only --global-var items.

**Comment by kunagpal** [comment]
Yes, either way, the update sequence works. Could you try this out with Newman v3.8.1 and let me know if you're having difficulties?

**Comment by concordion2k** [comment]
I upgraded to Newman 3.8.1, and my test still fails.

I have a request that pulls a phone number and processes it to read "%2B16035554321". I set this to a new global at runtime in the pre-request script of the test. I use the global in the test, and it works.

A second test later in the suite sets a new value to the same global above. I use it in the request, and the old value is used instead of the new value I set.

**Comment by kunagpal** [comment]
@concordion2k Alright, could you share the collection that causes this?

**Comment by concordion2k** [comment]
https://www.getpostman.com/collections/458ed771c8543e4a5dc6

**Comment by prakharjoshi** [comment]
@concordion2k I looked into the collection you provided. 

1. In `Customer Search Via Phone Num` request, you are setting `customer_phone_number` as a local environment variable and not as a Global environment variable. 

2. Now in the other request `Verify Number` you have set the `customer_phone_number` as the global variable.

As local environment overwrites the global environments, you are seeing the old value of `customer_phone_number`.

So in the second request when you were trying to get the value of  `customer_phone_number`, you are getting the value which is set in the first request (as that is local environment).

One way is you can set the `customer_phone_number` in the first request as global environment instead of the local environment and try that out again.

Let us know if that helps you :)

**Comment by concordion2k** [comment]
... and here I thought I caught all instances of setEnvironmentVariable.

Thank you for that. All is now well.

**Comment by concordion2k** [comment]
This is resolved. Thank you - apologies for not catching that nagging environment method.
