### ISSUE TITLE
Collection get does fail

### ISSUE THREAD

**Issue by carstenmuellerlemberg** [postmanlabs/newman#1182]
Hello,

as of today newman 3.8.1 running in node.js  6.9.* stopped working.
The issue we get is:

/app/node_modules/postman-collection/lib/collection/request.js:55
method: (_.get(options, 'method', 'GET')).toUpperCase()
TypeError: Cannot read property 'toUpperCase' of null

We reference the collectionusing newman.option:
newmanOptions.collection = "https://api.getpostman.com/collections/collectionid?apikey"

Same for environments.

It worked smooth till yesterday then it  stopped.
Is there a change on Postman cloud?

Regards,
Carsten

**Comment by kunagpal** [comment]
@carstenmuellerlemberg This appears to be an issue with a malformed request method in your collection, and is not related to the Node version. Could you share the reduced collection JSON that causes this so that we may confirm? Feel free to remove any sensitive details.

**Comment by carstenmuellerlemberg** [comment]
The collection JSON is return directly from Postman cloud. I can share via mail it if required. It is currently 44K lines.

**Comment by carstenmuellerlemberg** [comment]
We analyzed the issue and found that the JSON we get has an invalid entry.
First of all no postman id second that invalid JSON part.

               "request": {
                    "url": null,
                    "method": null,
                    "header": [],
                    "body": {},
                    "description": null
                },
                "response": []
            }

We seeing currently some issues syncing collections between postman and postman cloud.

**Comment by kunagpal** [comment]
@carstenmuellerlemberg Thanks for responding, that sheds more light on this issue. I've added a fix for the original error message you shared here:  https://github.com/postmanlabs/postman-collection/issues/444.

As for synchronization issues, I'm looping in @kamalaknn and @sobtiankit, who can dig deeper into this.

**Comment by kunagpal** [comment]
@carstenmuellerlemberg Thanks for responding, that sheds more light on this issue. I've added a fix for the original error message you shared here:  https://github.com/postmanlabs/postman-collection/issues/444.

As for synchronization issues, I'm looping in @kamalaknn who can dig deeper into this.

**Comment by kunagpal** [comment]
@carstenmuellerlemberg Could you try this out with Newman v3.8.3-beta.1?

**Comment by kunagpal** [comment]
This should have been fixed in Newman v3.8.3, feel free to revert if you have any other queries 😄
