### ISSUE TITLE
Feature Request: Parallel Run Support for load testing

### ISSUE THREAD

**Issue by jcoutu-va** [postmanlabs/newman#1190]
I often have to load test api endpoint and ensure that under load the system still maintains our 95% percentile performance characteristics. I can encode these as tests, but I then need to put the system under load.  Currently I use multiple parallel runs of my newman script to achieve this.   Support for load testing would be a nice next feature.

**Comment by kunagpal** [comment]
Related to #744

**Comment by carstenmuellerlemberg** [comment]
This is a requirement we also have. Would also be nice to be configured in Postman Monitor cloud service

**Comment by shamasis** [comment]
Indeed. We are definitely considering working on this in near future, but not in Newman though. 

Closing this as duplicate of #744

**Comment by duddu** [comment]
https://github.com/postmanlabs/postman-runtime/pull/867
