### ISSUE TITLE
[Postman Sandbox] Can Browserify be made a devDependency

### ISSUE THREAD

**Issue by kbuzby** [postmanlabs/newman#1207]
1. Newman Version (can be found via `newman -v`): 3.8.2
 2. OS details (type, version, and architecture): Windows 10 x86_64
 3. Are you using Newman as a library, or via the CLI? library
 3. Did you encounter this recently, or has this bug always been there: recently
 4. Expected behaviour: Browserify is a devDependency

The Browserify package is a pretty heavy package and has a lot of dependencies itself. According to this code from [/lib/bundle/index.js](https://github.com/postmanlabs/postman-sandbox/blob/4071f70d4d94158f2fc8ed69bc5bc28356172f74/lib/bundle/index.js) in the postman-collection repository it is only necessary for developing the module:

```javascript
// The modules for browserification should only be required during development of this module and as such a production
// installation should not even trigger require of this module. But in case it does, let's make the error message a bit
// more consumable.
try {
    browserify = require('browserify');
    browserifyBuiltins = require('browserify/lib/builtins');
}
catch (e) {
    console && console.error('sandbox: bundling triggered in production module installation mode');
    throw e;
}
```

Shouldn't this just be a devDepedency then? Which would significantly reduce the dependencies brought along when installed in a non-development setting.

**Comment by shamasis** [comment]
Yeah. Seems to me as a mistake. The whole idea of taking the pains to cache bundle was to not include dependency on browserify. @postmanlabs/newman-geneticists or anyone send a PR please.

**Comment by shamasis** [comment]
Ok, I have gone ahead and send the PR. It was trivial. :-)

**Comment by kbuzby** [comment]
Awesome, thanks @shamasis !

**Comment by jonathan-kosgei** [comment]
@shamasis I'm still getting this error on 5.1.2.

```
undefined INFO sandbox: Cannot find module '../.cache/bootcode' Require stack: -
ERROR sandbox: bundling triggered in production module installation mode
ERROR Uncaught Exception {"errorType":"Error","errorMessage":"Cannot find module 'browserify'\nRequire stack:\n- 
```
