### ISSUE TITLE
Running newman via NodeJS does not replace the global variables you set in the command line

### ISSUE THREAD

**Issue by andrewowen** [postmanlabs/newman#1208]
1. Newman Version: 3.8.2
 2. OS 10.12.5
 3. Using via Node with Newman as a package dependency
 3. Today 09/20/17
 4. Should take globals set via the `--global-var` key and insert where needed
 5. `node runner.js --global-var "foo=bar"`
 6. 
```
{
	"variables": [],
	"info": {
		"name": "api-integration",
		"_postman_id": "..."
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "User Login",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"",
							"pm.test(\"Card Status returns and is Active\", function () {",
							"    var jsonData = pm.response.json();",
							"    pm.expect(jsonData.CardStatus).to.eql(\"Active\");",
							"});"
						]
					}
				}
			],
			"request": {
				"url": {
					"raw": "....",
					"host": [
						"{{...}}"
					],
					"path": [

	
					],
					"query": [
						{
							"key": "credential1",
							"value": "{{email}}",
							"equals": true,
							"description": ""
						},
						{
							"key": "credential2",
							"value": "{{password}}",
							"equals": true,
							"description": ""
						}
					],
					"variable": []
				},
				"method": "GET",
				"header": [ ...]
				"body": {},
				"description": "...."
			},
			"response": []
		}
	]
}
```
 7. Screenshots (if applicable):

**Comment by kunagpal** [comment]
@andrewowen This is expected behaviour, `--global-var` was introduced to allow users to include sensitive variables without having to add them to an environment JSON. However, you can parse the CLI args from `process.argv` and include them in the options to the `newman.run` command if needed.

**Comment by andrewowen** [comment]
but shouldn't this work the same way regardless if I use `newman run` or a JS file that does `newman.run`?

**Comment by kunagpal** [comment]
Well no, because `--global-var` is an option that makes sense for `newman run`, but not to a script that contains `newman.run`.
