### ISSUE TITLE
HTML Reporter will not fail or create results if directories do not exist

### ISSUE THREAD

**Issue by kbuzby** [postmanlabs/newman#1209]
1. Newman Version (can be found via `newman -v`): 3.8.2
 2. OS details (type, version, and architecture): Windows 10 x86_64
 3. Are you using Newman as a library, or via the CLI? library
 3. Did you encounter this recently, or has this bug always been there: encountered today
 4. Expected behaviour: Either error if directories don't exist or try to create them.
 5. Command / script used to run Newman:
```javascript
let options = {
                collection: collection,
                environment: environment,
                globals: globals,
                insecure: true, 
                reporters: 'html',
                reporter: {
                    html: {
                        export: /*<SOME PATH THAT DOESN"T ALREADY EXIST HERE>*/
                    }
                }
            }
        
            newman.run(options);
```

Runs that are processed via this set of options will run and complete fine. If I use a different reporter, or the default HTML reporter options I get the expected output. However, when I provide a path that does not exist yet, it will just run without reporting or erroring. 

I understand it might not be feasible to recursively create directories if they don't exist, but if I'm expecting output to go there, I don't want errors just swallowed so that I have to spend time debugging and figuring out why they weren't created.

Additionally, if they are required to be pre-existing, then at the very least the documentation should say so.

**Comment by kbuzby** [comment]
Actually, this might be a bug just that the export path is not working, at least for the html reporter. I can't get it to provide an output even using an existing path. It's only providing a report when I don't provide the "reporter" option.

**Comment by prakharjoshi** [comment]
@kbuzby Thanks for reporting that issue. It seems to be a bug in Newman. We will get back to you once we have a fix for the same.

**Comment by prakharjoshi** [comment]
@kbuzby Can you provide me the path where you are exporting the reports and also can you confirm you are running Newman in Administrative Mode.

I am not able to replicate the same issue.

**Comment by kbuzby** [comment]
I found a process.exit() in my main loop that was getting called before Newman could finish running.

I believe I've got this running correctly now, thank you for looking into this though!
