### ISSUE TITLE
Scripts are failing in newman where as it is working in Postman

### ISSUE THREAD

**Issue by nikhileshshah** [postmanlabs/newman#1239]
**Overview:** We have created End To End automation script in Postman, now we were trying to execute postman collections using Newman so that we can run regression and get HTML report.  

**Issue:** We were able to run postman client collection using Newman but few of the Test script were failing and we did not get any reason and step name that where & why exactly it is failing. When we run same collection through postman it is working as expected. 

**Our approach:**  We are developing 3rd party SDK and it is completely customization customer can change key and its type, so we have to validate the both Key and value which we passed in request body and validate same in get API.

**Version and environment information:**

 1. Newman Version : 3.8.3
 2. OS details (type, version, and architecture): Win 8
 3. Are you using Newman as a library, or via the CLI? : As a Library
 3. Did you encounter this recently, or has this bug always been there: I tested above mentioned issue on 3.8.1//2/3 
 4. Expected behavior: It should run all the script like postman client
 5. Command / script used to run Newman: 
`call Newman run "C:\Temp\Automation1\QA\Automation\Basic.json" --environment "C:\Temp\Automation1\QA\Automation\Basicenvironment.json" --reporters html --reporter-html-export FieldTypeBasic.html`
 6. Postman Create Test Script: 
We are storing Create request both key and value in environment so that we can compare with GET  response

**Comment by shamasis** [comment]
Not sure there is enough information for me to go on. Can you do console.log on the responses and check whether Postman and newman returns same response?

Also, maybe log `expKeys` and `data` to see what difference you see in Postman vs Newman?

**Comment by nikhileshshah** [comment]
ok will try and come back soon.

**Comment by nikhileshshah** [comment]
Hello,

I tried on on postman by added console.log for for expkeys and data and I am getting response as expected whereas I dont know how to log in Newman.

Thank You
