### ISSUE TITLE
Newman Parallel collection execution 

### ISSUE THREAD

**Issue by Gans79** [postmanlabs/newman#1255]
Hi,
Does newman has any option to run collections in parallel ? 
can you let us know with an example snippet 

Regards
Ganesh

 1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by kunagpal** [comment]
https://github.com/postmanlabs/newman/blob/develop/examples/parallel-collection-runs.js
