### ISSUE TITLE
Add support to run newman from yaml files

### ISSUE THREAD

**Issue by gaieges** [postmanlabs/newman#1258]
This is simply a feature request to support the ability to run yaml files (both collections and environments) via newman in the same way that json is run.

The benefit that this would provide is to allow for easier access to modify and write postman files by hand instead of having to manage the json syntax, which could then be used to convert on the fly and upload to postman api

@macejiko

**Comment by kunagpal** [comment]
Could you provide more context on how this is useful? You can use the [Postman app](https://getpostman.com/apps) to interact with collections in a streamlined manner.

**Comment by gaieges** [comment]
Readability of the files (ie if i dont want to use the app)

**Comment by benhowes** [comment]
@gaieges we built tavern for exactly this reason (plus a few others). https://taverntesting.github.io/

**Comment by gaieges** [comment]
@benhowes - thanks for sharing that .. looks pretty great and addresses some of the issues that we've had with the json aspect of newman/postman.  

Just for some additional color here, we're having a tricky time getting developers to engage in using postman even after building some framework'ing that integrates it into our CI.  My assumption is that since it's not native to a text editor (especially coming in as a non-postman user), and easily understood by reading the collection files, that barrier to entry is high and not worth the ramp up, which leads to only a few people managing tests which is recipe for trouble.

This ticket was intended to help ease that, and Tavern looks like it may too.

**Comment by ryancastle** [comment]
Piping YAML to newman CLI works well, and IDEs support using the Postman collection JSON Schema with YAML files.

```
❯ cat newman.yaml 
info:
  name: Newman YAML Test
  schema: https://schema.getpostman.com/json/collection/v2.1.0/collection.json
item:
  - name: Simple GET Request
    request:
      method: GET
      url: https://postman-echo.com/

❯ newman run /dev/stdin < <(yq -ojson e newman.yaml)
newman

Newman YAML Test

→ Simple GET Request
  GET https://postman-echo.com/ [200 OK, 44.03kB, 2.3s]
```
