### ISSUE TITLE
A very basic question, Is it possible to get the actual response of a GET request in a JSON file using NEWMAN.

### ISSUE THREAD

**Issue by rahuln93** [postmanlabs/newman#1259]
1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by kunagpal** [comment]
This can be accomplished using Newman as a library, as follows:
```
var newman = require('newman'); // Ensure that you have run `npm i newman` in the current directory

newman
  .run({
    collection: 'path to collection file or actual JSON itself',
    environment: 'similar to above, optional'
  })
  .on('request', function (err, data) {
     // err, data can be used to write to files using the node fs module.
  });
```

**Comment by jisooh** [comment]
An older version of Newman used to output the response to the json logs. However, I do not see this anymore and see a response stream instead. Is there no way to get the response of requests anymore because using Newman as a module?

**Comment by patrickhitch** [comment]
Apparently not. I better example of how to use 'data' being passed to callback would be nice though.

**Comment by rahuln93** [comment]
Just use Bash files for API calls, thats what i did.
