### ISSUE TITLE
Feature request: Add option to "Open.." a file to newman native app instead of just importing it

### ISSUE THREAD

**Issue by gaieges** [postmanlabs/newman#1280]
Feature request: be able to edit a collection file on disk on the fly, instead of having to import and export the collection as desired.

The case that I run into that is an annoyance from time to time is during editing of a collection file in git that gets used downstream in my CI pipeline.  In its current form, I'm required to import the existing collection from git, and then export it to the file system in it's place once I'm done.  

It'd be great instead to just be able to open a file and save it directly to where I opened it from, and then git commit and have my CI pipeline use it.

**Comment by gaieges** [comment]
If this should go in another repo please let me know, wasn't sure which this applied to

**Comment by kunagpal** [comment]
@gaieges This issue tracker is for Newman, the CLI companion to Postman. Your issue is related to the Postman app, please create an issue for the same here: https://github.com/postmanlabs/postman-app-support/issues/new

Thanks! 😄

**Comment by gaieges** [comment]
Figured that might be the case, sorry, and thank you!
