### ISSUE TITLE
Setting global variables from file

### ISSUE THREAD

**Issue by Sam-Levene** [postmanlabs/newman#1284]
I'd like to know if it is possible to pass global vars from a file now that the `-d` flag is no longer an option.

I can see the `-g` flag but using that doesn't insert my global variables, which are stored in JSON format and instead resolves to:
` {{domain}}/[MYURL]`

where `{{domain}}` should equate to `"domain": "[MYDOMAIN]"`

**Comment by Sam-Levene** [comment]
Nevermind

**Comment by kunagpal** [comment]
The `-d` flag is indeed valid, but is for iteration data, not globals. Could you also share:
1. The Newman and Node versions (`node -v`, `newman -v`)?
2. The command/script used to run newman.
