### ISSUE TITLE
Request works in Postman and fails in Newman

### ISSUE THREAD

**Issue by Sam-Levene** [postmanlabs/newman#1293]
**1. Newman Version (can be found via `newman -v`):** 3.8.3
**2. OS details (type, version, and architecture):** Docker / Linux via VM Virtualbox and Windows 7 64-bit Host PC
**3. Are you using Newman as a library, or via the CLI?** CLI
**4. Did you encounter this recently, or has this bug always been there:** Recently Encountered
**5. Expected behaviour:** Newman to work in the same manner as Postman
**6. Command / script used to run Newman:** `newman run -e EnvironmentVariables.postman_environment.json -x -r junit,cli,xml,html --globals globals.json Public_API_Tests.postman_collection.json --color`
**7. Sample collection, and auxilliary files (minus the sensitive details):** I cannot provide this as it correlates to a workplace environment with sensitive data
**8. Screenshots (if applicable):**

![ss-01](https://user-images.githubusercontent.com/19433453/33064733-98ca5316-ce9e-11e7-92b1-bbdf5b84dc22.PNG)
_Postman Run_

![ss-02](https://user-images.githubusercontent.com/19433453/33064659-5f4711e2-ce9e-11e7-9bfb-f9fdc12a6daa.PNG)
_Newman Run_

**EDIT:** I think it might have something to do with Cookies, but I cannot be certain, as removing the cookies on Postman throws a _**401: Unauthorized**_ as opposed to a **_400: Bad Request_**.

**Comment by mayank13** [comment]
You might want to check if data is escaped properly when trying it newman.

**Comment by Sam-Levene** [comment]
I'm sending the PATCH request as a JSON, it shouldn't need escaping

**Comment by kunagpal** [comment]
@Sam-Levene Could you check if this issue persists with Newman v3.9.1 as well?

**Comment by Sam-Levene** [comment]
@kunagpal - No; This has been resolved independently of an app-version fix.

**Comment by Sam-Levene** [comment]
@kunagpal - I have attempted to use Newman v3.9.2 and have come to the realisation that it is not a newman issue, but a proxy one as we are attempting this issue behind a corporate proxy.
