### ISSUE TITLE
TypeError while using newman.run. The same parameters work fine with CLI.

### ISSUE THREAD

**Issue by mayank13** [postmanlabs/newman#1294]
1. Newman Version (can be found via `newman -v`): 3.8.3
 2. OS details (type, version, and architecture): Linux/Ubuntu 16.04 64-bit
 3. Are you using Newman as a library, or via the CLI? Library
 3. Did you encounter this recently, or has this bug always been there: Recently
 4. Expected behaviour: Should print out the output to the console. Instead errors out with a type error
 5. Command / script used to run Newman:
```

function runHardcoded(){
  newman.run({
    collection: 'https://api.getpostman.com/collections/<collection id>?apikey=api_key',
    reporters: ['cli'],
    environment: 'https://api.getpostman.com/environments/<env_id>?apikey=api_key,
    folder: "Start"
  }, function(){
    sails.log.info("Done Running the folder of the collection");
  })
  
}
```
 6. Sample collection, and auxilliary files (minus the sensitive details): "https://api.getpostman.com/collections/${COLLECTION_UID}?apikey=${POSTMAN_API_KEY}"
 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/2232732/33068495-90b54ac6-ced7-11e7-9012-86d08a0daf62.png)

Steps to reproduce the problem:

1. Use newman.run and pass the following parameters:

- Collection as a url  from POSTMAN Pro API
- Environment as a url  from POSTMAN Pro API
- Folder within a collection name 

Refer screenshot.

**Comment by kunagpal** [comment]
@mayank13 It looks like you're using the same id for both: your collection and environment. Please see https://github.com/postmanlabs/newman#using-newman-with-the-postman-pro-api for complete instructions. In the meantime, I'll confirm whether this error can be handled better on the Newman side of things.

**Comment by mayank13** [comment]
Hey! Sorry about that. That's was a  typo while creating the issue. I am using the correct ID's . Can you please check and let me know. Same parameters work fine with Newman CLI.

**Comment by mayank13** [comment]
Deleted and used a different environment. Seems to be working Ok now. Closing the issue. Will report again if something similar happens.
