### ISSUE TITLE
Newman Report - Multiple sets of same request is shown for multiple iteration even though the pass/fail count is already included in the first request

### ISSUE THREAD

**Issue by azharmohammedk** [postmanlabs/newman#1295]
Postman for Windows
Version 5.3.2
win32 6.1.7601 / x64

Issue Report:
[Newman Report Issue.docx](https://github.com/postmanlabs/newman/files/1492644/Newman.Report.Issue.docx)

I have 1 collection with 1 request having 2 tests which I am running for 2 iterations.
I am using data from data file (CSV) which has two iterative data
When I run this using postman collection runner, I see 4 tests in total with all 4 passed which is correct
When I run the same using newman report, I see 2 requests and each having 2 tests but the count is incremented for each iteration showing a wrong picture that totally 8 tests have been run. Attaching detailed snapshot.
Please fix the issue.

**Comment by kunagpal** [comment]
@azharmohammedk This has been fixed in https://github.com/postmanlabs/newman/pull/1553, and will be rolled out with the next release.
