### ISSUE TITLE
Newman as node js project

### ISSUE THREAD

**Issue by dlpooja** [postmanlabs/newman#1297]
Hi ,
How do we specify path to export junit or html report in node js file.
My file looks like this

newman.run({
    collection: 'C:/.../I.json',
    iterationData:'C:/../test_data.json',
    reporters: ['cli' ,'junit'],
      environment:'C:/Users/../Local_Env.json'
}, function (err) {
	if (err) { throw err; }
    console.log('collection run complete!');
})

I want to specify export path for my junit report . how can i specify the path?

**Comment by deepakpathania** [comment]
Hey @dlpooja. You can specify the export path for reporters by using reporter specific options which you can specify using the `reporter` option. 
For eg, here is what your code block would look like with a specified path for your junit report.
```javascript
newman.run({
    collection: 'C:/.../I.json',
    iterationData:'C:/../test_data.json',
    reporters: ['cli' ,'junit'],
    reporter: { junit : { export : 'path/to/report/reportName.xml' } },
    environment:'C:/Users/../Local_Env.json'
}, function (err) {
    if (err) { throw err; }
    console.log('collection run complete!');
});
```
Newman would try to create the folder and files(if they don't already exist) specified in the export path, provided there are no permission issues. 
For eg. something like `{ export : 'junitReports/report1/xmlResults.xml' } }` would create the specified folders in the root directory and add the file there.

Feel free to reach out in case this doesn't resolve your query.
