### ISSUE TITLE
ReferenceError in test-script while using pm.test

### ISSUE THREAD

**Issue by RuniQa** [postmanlabs/newman#1305]
Hello,
I am using Octopus and Newman to deploy and test my service. When I run Newman command line to test deployed service I am getting an error "ReferenceError in test-script" and test is failing. There is no such an issue when I run it on my local machine. I'm not sure if it is a lack of a library or a bug.

 1. Newman Version 3.5.2
 2. Octopus Deploy server.
 3. I am using Newman via the CLI.
 3. It was there since I have started to use Newman on Octopus server.
 4. Expected behaviour: working pm.test
 5. Command / script used to run Newman: n.a.
 6. Sample collection, and auxilliary files (minus the sensitive details): n.a.
 7. Screenshots (if applicable):

![screenshot 53_censored](https://user-images.githubusercontent.com/33484160/33265303-6addf99e-d371-11e7-98ae-14910c18e4ad.jpg)
![screenshot 52_censored](https://user-images.githubusercontent.com/33484160/33265308-6e6c022c-d371-11e7-935d-9bab57549a6f.jpg)

**Comment by kunagpal** [comment]
Newman v3.5.2 does not support the `pm.*` API. Could you try this out with v3.8.3 and confirm?

**Comment by RuniQa** [comment]
@kunagpal Thank you for fast response. I have updated to 3.8.3 but I still have the same issue.

**Comment by kunagpal** [comment]
@RuniQa I'm afraid I don't have sufficent information to go on. Could you send a screenshot from the bottom of the collection run report? This is the section after the final summary table, that contains additional details on test and script failures.

**Comment by RuniQa** [comment]
In fact it is still the same issue. I am sending you my mockup collection together with screenshot. 
![screenshot 55_censored](https://user-images.githubusercontent.com/33484160/33271544-d43959b8-d387-11e7-9ca2-274376c3aba6.jpg)
[Octo Integration Test.postman_collection.json.zip](https://github.com/postmanlabs/newman/files/1506185/Octo.Integration.Test.postman_collection.json.zip)

**Comment by kunagpal** [comment]
Could you also scroll down in the Octopus UI and share a screenshot of the end segments of the collection run log?

**Comment by RuniQa** [comment]
![screenshot 56](https://user-images.githubusercontent.com/33484160/33272087-638567dc-d389-11e7-957f-79d9c23cb22f.jpg)

**Comment by kunagpal** [comment]
Alright, could you add `newman --version` before the `newman run` command in your pipeline? I'd like to confirm that this is an issue with the latest version (Just being extra cautious 😄 )

**Comment by RuniQa** [comment]
That is correct. It seems that my Octopus Deploy server has been using different user profile than I supposed. I updated Newman on all my profiles and now it is working. Thank you for support.

**Comment by kunagpal** [comment]
@RuniQa Glad it worked out for you 😄
