### ISSUE TITLE
How to set setTimeout/Thread.sleep in newman

### ISSUE THREAD

**Issue by shubhamj-cuelogic** [postmanlabs/newman#1318]
How to set setTimeout/Thread.sleep in newman(postman's node module).

I am using below function :

```
setTimeout(function(){ 

        console.log('sleep for ten min');
    }, 600000);
```

Above function works perfectly in collection runner of postman.

But when I tried newman it is throwing error as

'setTimeout is not available inside sandbox and has no side-effect.'
I have found a similar thread like below:

https://github.com/postmanlabs/newman/issues/304

But they also haven't provided any solution.

Is there anyway by which I can mark my single API to delay for a time period.

I am already using Newman parameter --delay-request 60000 which delay between API's so it won't work for it.

Version and environment information:
OS : 
Newman as a CLI

 1. Newman Version (can be found via `newman -v`):  3.6.1
 2. OS details (type, version, and architecture): Win 10 - 64 bit
 3. Are you using Newman as a library, or via the CLI? - Yes
 3. Did you encounter this recently, or has this bug always been there: I just tried
 4. Expected behaviour: Need to wait as per given time
 5. Command / script used to run Newman: newman run .....
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

![post](https://user-images.githubusercontent.com/6291660/33481950-c2a6199c-d6bc-11e7-9388-55858ccd8cd7.JPG)

I also posted this question here:

https://stackoverflow.com/questions/47592791/how-to-set-settimeout-thread-sleep-in-newman

**Comment by kunagpal** [comment]
@shubhamj-cuelogic Newman v3.6.1 does not support setTimeout and other related functions. Could you try this out with v3.8.3?

**Comment by shubhamj-cuelogic** [comment]
Thanks @kunagpal ... It is working with v 3.8.3 ..
It really help :)
