### ISSUE TITLE
How to distinguish multiple runs with a single request in test report

### ISSUE THREAD

**Issue by jun1983** [postmanlabs/newman#1322]
I am researching if newman / postman can be used for the API auto testing of my project.  
Not sure how to do a test-driven testing to a single API, my personal solution is indicating a list of data in pre-script, then using setNextRequest to control the flow to loop or end. This basically works for me. 

However, one big problem is that all these requests are merged together in the test report. I tried to look into the html report template, I could see all details were at item or request level, for example, id="collapse-request-{{item.id}}".  Can we use a runtime-timestamp or unique sequence number to identify a sent request individually? Like what we can see in Postman console.

**Comment by shamasis** [comment]
Yeah. The events triggered by Newman has the first argument as `cursor`. It contains request ID and execution ID. 

You’ll have to copy one of our reporters and create your own. Simply listen to all events by Newman and log true first argument and you’ll see the pattern. :-)

**Comment by jun1983** [comment]
@shamasis Thanks very much for your quick response. I used {{index}} to have my problem solved. Anyway, I could not see execution.id, can you tell me how to use it and how to listen to all events from Newman. I wish a place what I can find all available argument I can use in the report.
