### ISSUE TITLE
Folder parameter behavior change in 3.9.0

### ISSUE THREAD

**Issue by al-tr** [postmanlabs/newman#1324]
Did the behavior of `--folder` parameter change on minor version release?

Version and environment information:
 1. Newman Version: 3.8.3 - 3.9.0
 2. OS details: windows 7 x64
 3. CLI
 3. Did you encounter this recently, or has this bug always been there: recently
 4. Expected behaviour: folder parameter runs the specified folder, not returning 0 tests run
 5. Command / script used to run Newman: newman run col.postman_collection.json --folder direct_read_only
 6. Sample collection, and auxilliary files: [col.postman_collection.json.txt](https://github.com/postmanlabs/newman/files/1535220/col.postman_collection.json.txt)
 7. Screenshots: none

Steps to reproduce the problem:
1. npm install -g newman@3.8.3
2. newman run col.postman_collection.json --folder direct_read_only
3. 1 execution
4. npm install -g newman@3.9.0
5. newman run col.postman_collection.json --folder direct_read_only
6. no executions

**Comment by deepakpathania** [comment]
Hey @al-tr, thanks for reporting this. I was able to reproduce this issue locally where even if the supplied folder name exists, newman just gracefully exits without executing the requests in that item group. Will keep you updated on it.

**Comment by deepakpathania** [comment]
Hey @al-tr, we are working on fixing this issue, you can track progress in #1326.
Thanks for your patience.

**Comment by deepakpathania** [comment]
Hey @al-tr, this has been fixed and released in [3.9.1](https://github.com/postmanlabs/newman/releases/tag/v3.9.1). Go ahead and try it and feel free to reach out in case you have any other queries. :smile:

**Comment by al-tr** [comment]
@deepakpathania works weel, thanks, all builds are using the latest vesion again :hammer_and_wrench:
