### ISSUE TITLE
The NULL values captured from previous URLs in Newman is not passing properly in next subsequent URL.

### ISSUE THREAD

**Issue by anilsbs** [postmanlabs/newman#1328]
Hi Team,
we are executed REST URL's using postman. The multiple REST URL's are collected and executed as part of a postman collection.  All REST URL's are executed properly without any issue from postman collection console.  The postman collection scripts ran from command console using Newman command and some of the REST URLs ran from command console using Newman are getting 400 HTTP error code (BAD REQUEST). The reason for this issue is NULL values captured from previous URLs  response are captured in postman environment variables and Newman is not properly passing in next subsequent REST URL's. Kindly guide me on the same how to resolve it.

**Comment by kunagpal** [comment]
@anilsbs I'm afraid I don't have sufficient information to go on. Could you provide the following details?
1. The Newman and Node versions (`newman -v', `node -v`)
2. The collection and environment files used in the run (feel free to redact sensitive details)
3. The command/script used to run Newman.

**Comment by anilsbs** [comment]
The Newman version is 3.8.2 and the node version is v6.11.3.

Please find the collection and environment files as attached by removed all sensitive details it.

The command/script used to run Newman is "newman run C:\hudson\NEW.postman_collection.json --delay-request 2000 -e C:\hudson\Test.postman_environment.json --export-environment C:\hudson\Test.postman_environment.json"

The issue here is 
The value is captured in environment variable "paramater_B" is NULL value from REST URL 1 server response and this value should be passed to REST URL 2 payload data. In POSTMAN, the NULL value is passed properly and server will responded properly with 200 HTTP status code for REST URL 2. whereas the same collection ran from NEWMAN will return with 400 HTTP status code for REST URL 2. 

So, if you hardcode the NULL value directly in payload of REST URL 2, will receive proper server response with HTTP status code 200 from NEWMAN. 

Hence NULL values captured in environment variable is not passed properly in NEWMAN. Could you kindly guide us how to debug how the values are sent to server by NEWMAN.

[PostMan scripts.zip](https://github.com/postmanlabs/newman/files/1547269/PostMan.scripts.zip)
