### ISSUE TITLE
Cannot read property 'toString' of undefined while using Postman link checker.

### ISSUE THREAD

**Issue by oabdelsamad** [postmanlabs/newman#1329]
All, 

I am using the postman link checker (
http://blog.getpostman.com/2017/06/23/check-for-broken-links-on-your-website-using-a-postman-collection/) and it's working just fine on the postman app. But when running it using the newman run command, it threw "Cannot read property 'toString' of undefined" error. Any thoughts? Below are the OS and all related info I have.

 1. Newman Version: 3.9.0
 2. OS details): 10.13 (17A365) High Sierra
 3. Are you using Newman as a library, or via the CLI? As a library
 3. Did you encounter this recently, or has this bug always been there: Only when I run the postman link checker.
 4. Expected behaviour: I should have the postman link checker working find with no issues.
 5. Command / script used to run Newman: `newman run <collection link>`
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable): ![screen shot 2017-12-08 at 6 02 33 pm](https://user-images.githubusercontent.com/21035790/33773908-341314a6-dc42-11e7-874a-9b6870571db2.png)

**Comment by kunagpal** [comment]
This because the variable definition of `{{start_url}}` is missing. Try using the `--global-var` option, like so:
```
newman run <collection link> --global-var start_url=<your start url goes here>
```

**Comment by oabdelsamad** [comment]
Thank you @kunagpal! I tried that but I am still getting the same error.

**Comment by prakharjoshi** [comment]
@oabdelsamad this collection requires an environment when you run it through Postman app you are running it with Link Checker environment. Here also when you are running this collection with Newman try running it with the environment like `newman run <collection_link> -e <environment_link>`.

Also, Do not change the order of requests, the collection link you are using has a different order of requests then the original collection.

**Comment by oabdelsamad** [comment]
@prakharjoshi You are the best! It's working now. Many thanks!
