### ISSUE TITLE
How to repeat postman link checker for different URLs but in same collection? 

### ISSUE THREAD

**Issue by oabdelsamad** [postmanlabs/newman#1333]
Hello, 

How can I do a link checker using http://blog.getpostman.com/2017/06/23/check-for-broken-links-on-your-website-using-a-postman-collection/ but for different URLs in the same collection?

**Comment by prakharjoshi** [comment]
@oabdelsamad This collection picks the URL values provided in the environment. So if you change values of environment variables (`start_url` and `root_url`), this collection will check links to that URL.

**Comment by oabdelsamad** [comment]
Thank you @prakharjoshi
