### ISSUE TITLE
Postman link checker crawl on one page. 

### ISSUE THREAD

**Issue by oabdelsamad** [postmanlabs/newman#1335]
Hey all, 
I am using postman link checker (http://blog.getpostman.com/2017/06/23/check-for-broken-links-on-your-website-using-a-postman-collection/). Is there any way to check all links that are on xx page and not crawl those links?

**Comment by prakharjoshi** [comment]
@oabdelsamad I am afraid there is no existing solution for this right now. One way is you can modify the collection according to your needs.

**Comment by oabdelsamad** [comment]
Thank you @prakharjoshi for the quick response. I will try to do so, until we have this feature to postman link checker, hopefully 😄

**Comment by OlegKorn** [comment]
try this
idk what you mean by "crawl" links, but this checks all the links of a site

https://github.com/OlegKorn/test_tasks/tree/main/Postman%20snippets/postman%20-%20check%20all%20nested%20links%20of%20a%20site
