### ISSUE TITLE
newman does not run a folder

### ISSUE THREAD

**Issue by amnoman** [postmanlabs/newman#1337]
1. Newman Version (can be found via `newman -v`): 3.9.0
 2. OS details (type, version, and architecture): Microsoft Windows [Version 10.0.15063], 64-bit
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: recently
 4. Expected behaviour: Should able to a run folder from the collection
 5. Command / script used to run Newman: newman run Test.postman_collection.json --folder TestDelay
 6. Sample collection, and auxiliary files (minus the sensitive details): 

[Test.postman_collection.json.zip](https://github.com/postmanlabs/newman/files/1548257/Test.postman_collection.json.zip)

 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/28634757/33837970-aa97c046-de53-11e7-935d-41eba6823b88.png)

![image](https://user-images.githubusercontent.com/28634757/33837951-9d7f4d98-de53-11e7-8841-cb53b2d3349e.png)

**Comment by kunagpal** [comment]
This has been fixed in `v3.9.1`
