### ISSUE TITLE
Multiple Collection Execution Capability?

### ISSUE THREAD

**Issue by wjbrooks1981** [postmanlabs/newman#134]
Working with newman has been great for an individual execution of a collection.    However, I am starting to want a chain of collections to run.  Is there an example out there for this or is this not a possibility?  

I am executing from code using:
Newman.execute(testCollection, Newman.newmanOptions);

**Comment by bruno-lopes** [comment]
This is a very good question. @wbrooks1981 you found an answer to your case, but in my opinion, Newman should permit that we pass a Postman dump file (possibly with lots of collections), and use this as parameter, in order to run all the collections defined in Postman.
