### ISSUE TITLE
Have doubt in json report generated by newman via CLI

### ISSUE THREAD

**Issue by svenkat1** [postmanlabs/newman#1340]
1. Newman Version (can be found via `newman -v`): 3.9.1
 2. OS details (type, version, and architecture): ubuntu 64 bit
 3. Are you using Newman as a library, or via the CLI? both library and CLI
 3. Did you encounter this recently, or has this bug always been there: Encountered recently
 4. Expected behaviour: As like previous newman version json report format

Hi,
I installed the latest newman version 3.9.1 in which i encounter some changes in json report format. in older version the failure block in json report seems to be look like this

in newman@3.8.3

"failures":[
{
"error":{
"name":"AssertionFailure",
"index":1,
"message":"{\"entityType\":\"test 1\",\"description\":\"Getting all the raw data\",\"url\":\"https://localhost:8080/getAll\",\"request\":\"Empty Request Payload\",\"response\":{\"fault\":{\"code\":\"900901\",\"message\":\"Authentication Failure\",\"description\":\"INVALID credentials\"}},\"errorCode\":401,\"expectedCode\":200}",
"stack":"AssertionFailure: Expected tests[\"{\"entityType\":\"test 1\",\"description\":\"Getting all the raw data\",\"url\":\"https://localhost:8080/getAll\",\"request\":\"Empty Request Payload\",\"response\":{\"fault\":{\"code\":\"900901\",\"message\":\"Authentication Failure\",\"description\":\"INVALID credentials\"}},\"errorCode\":401,\"expectedCode\":200}\"] to be true-like\n at Object.eval test.js:2:1)",
"checksum":"5bd74809ab7b9bec1137968bc9cd97f8",
"id":"34f6ca0c-77fe-4b68-8259-f9bde6d6cdd7",
"timestamp":1513084691328,
"stacktrace":[
{
"fileName":"test.js",
"lineNumber":2,
"functionName":"Object.eval",
"typeName":"Object",
"methodName":"eval",
"columnNumber":1,
"native":false
}
]
},
"at":"assertion:1 in test-script",
"source":{},
"parent":{},
"cursor":{}
}
]

but in new version the message information inside the failure block is get changed like this 

in newman@3.9.1

"failures":[
{
"error":{
"name":"AssertionError",
"index":0,
"message":"expected false to be truthy",
"stack":"AssertionError: expected false to be truthy\n at Object.eval sandbox-script.js:1:1)",
"checksum":"54fe6e22b5978c6c9702219249d63138",
"id":"42f3b44d-c3b1-4df5-ba90-fae78a186b03",
"timestamp":1513085479803,
"stacktrace":[
{
"fileName":"sandbox-script.js",
"lineNumber":1,
"functionName":"Object.eval",
"typeName":"Object",
"methodName":"eval",
"columnNumber":1,
"native":false
}
]
},
"at":"assertion:0 in test-script",
"source":{},
"parent":{},
"cursor":{}
}
]

Here i am giving the json failure block for the same failure with two different newman version.
Is it intentionally changed or bug in the new version.I depending upon the failure block error message and forming a my own html report based on the failure block. so Please look into it and clarify my doubt so i can plan and work accordingly with this changes

Thanks and Regards,
Satheesh

**Comment by harryi3t** [comment]
@svenkat1  I can't reproduce the 1st block using newman@3.8.3

I ran newman with a simple collection having 1 reqest and following test script.
```js
tests['legacy format fail'] = false;
pm.test('new format fail', function () {
    pm.expect(1).to.equal(2);
});
```
These are the output 
# newman@3.8.3  -------------- newman@3.9.1
![newman-run-report-2017-12-13-13-50-55-657-0_json_ _newman](https://user-images.githubusercontent.com/5207331/33943645-b570ae68-e03f-11e7-85b7-baf3aaec6e72.jpg)

The highlighted differences are the ones I could see and all of these are intentional.

### Workaround
If you just want to get the test name and the failure message, you can use `assertions` instead of `failures`
![newman-run-report-2017-12-13-13-50-55-657-0_json_ _newman](https://user-images.githubusercontent.com/5207331/33943957-a547847a-e040-11e7-8c2f-c4c2f6305790.jpg)

Let me know if you need further clarification :)

**Comment by svenkat1** [comment]
Thank you Hari, Now I am clear with new changes and want to do some code refactoring in my code with your new changes.

**Comment by harryi3t** [comment]
Happy to help you :)
