### ISSUE TITLE
Get status code.

### ISSUE THREAD

**Issue by oabdelsamad** [postmanlabs/newman#1345]
Hi all,

Not sure if it's the right place to ask this, but is there anyway to get responseCode for all links in a web page?

Thanks in advance.

**Comment by kunagpal** [comment]
Within the test script for a request, you can use the all-new `pm.*` API to fetch response details, like so:
```js
pm.response.code // this contains the actual response code.
```

More details here: https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference
