### ISSUE TITLE
NewMan removes leading zeros from string data that looks like a number

### ISSUE THREAD

**Issue by mgroeneweg** [postmanlabs/newman#1346]
1. Newman Version (can be found via `newman -v`): 3.9.1
 2. OS details (type, version, and architecture): Windows 10, 64bits
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: today
 4. Expected behaviour: Do not take off leading zeros from string values.
 5. Command / script used to run Newman: newman run TestLeadingZeros.postman_collection.json -d TestLeadingZeros.csv --reporters cli,json --reporter-json-export testreport.json
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

The CSV contains a value "008727100". It is enclosed in quotes. NewMan passes "8727100" to the server, which leads to a failure. These values are codes, not numbers.
When I run using collection runner, it leaves the value intact.

I reproduced this using a google search for 000123.
When running using collection runner, it searches for 000123.
When running using newman, it searches for 123

When a value is enclosed in quotes, it should not be interpreted but passed on to the service call as is.

I attached the files, but had to rename everything to txt extension.

[TestLeadingZeros.txt](https://github.com/postmanlabs/newman/files/1558672/TestLeadingZeros.txt)
[TestLeadingZeros.postman_collection.txt](https://github.com/postmanlabs/newman/files/1558673/TestLeadingZeros.postman_collection.txt)
[TestLeadingZeros.postman_collectionrunner_test_run.txt](https://github.com/postmanlabs/newman/files/1558675/TestLeadingZeros.postman_collectionrunner_test_run.txt)
[testreport newman.txt](https://github.com/postmanlabs/newman/files/1558677/testreport.newman.txt)

**Comment by codenirvana** [comment]
@mgroeneweg a fix has been added in #1609 which will be rolled out with the v4 release.

You can test this using [v4.0.0-beta.2](https://www.npmjs.com/package/newman/v/4.0.0-beta.2).

**Comment by codenirvana** [comment]
@mgroeneweg This has been fixed in Newman v4.0.0.

**Comment by ajaygoeleb** [comment]
@codenirvana I just upgraded newman to 4.3.1 but it seems like it is still dropping leading zero :-(

**Comment by codenirvana** [comment]
@ajaygoeleb Make sure you wrap your number in quotes. Example:
```csv
data1, data2
"00123", 00123
```

Will be converted to:
```json
{
    "data1": "00123",
    "data2": 123
}
```
