### ISSUE TITLE
Postman integration with Stash

### ISSUE THREAD

**Issue by Gans79** [postmanlabs/newman#1349]
1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

I was exploring the Team library feature on Pro and found it very useful for team collaboration .
But my company uses atlassian stash for all storage , is there a way we can integrate our team library with Stash ?

**Comment by Gans79** [comment]
It is also a security concern to store all collections on postman servers , if we can integrate with our enterprise Stash it will be better secured

**Comment by shamasis** [comment]
Moved to https://github.com/postmanlabs/postman-app-support/issues/4695
