### ISSUE TITLE
Basic Auth fails with Collection v2.1+Newman

### ISSUE THREAD

**Issue by sanvipy** [postmanlabs/newman#1352]
1. Newman Version (can be found via `newman -v`): 3.8.1
 2. OS details (type, version, and architecture): Win 7, 64 Bit
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: After the v2.1
 4. Expected behaviour: Basic Auth should work in both v2.0 and v2.1
 5. Command / script used to run Newman: newman run Test.postman_collection.json -e SGP_SIT.postman_environment.json -g globals.postman_globals.json -r cli,html -k --ignore-redirects 
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/18203625/34190618-be0bddb2-e57c-11e7-825c-e2c97241079f.png)
![image](https://user-images.githubusercontent.com/18203625/34190624-c9cdd13c-e57c-11e7-836c-6bf0bdeaff64.png)

When run as Collection  v2
![image](https://user-images.githubusercontent.com/18203625/34190668-0aa9553c-e57d-11e7-976f-1a870e42a4ed.png)

When run as Collection v2.1
![image](https://user-images.githubusercontent.com/18203625/34190697-33fa2aec-e57d-11e7-87c6-dc1c4810ca4e.png)

I tried setting auth at collection level and using Inherit Auth from Parent at step level, still ended up with 401 error for v2.1 

Note: Everything works fine in Postman, issue is when running through Newman

Summary:
Using a collection using basic  auth
1. Export the collection as v2, trigger through Newman --> 201 Success Response Code
2. Re-export the same collection as v2.1, trigger through Newman --> 401 Unauthorised

**Comment by kunagpal** [comment]
@sanvipy Could you confirm that this bug is present in Newman v3.9.1 as well?

**Comment by sanvipy** [comment]
Ahh, why didnt I think of updating Newman. 

Yes, It works well with v3.9.1. 

Thanks @kunagpal !!
