### ISSUE TITLE
Newman run multiple folders in collection.

### ISSUE THREAD

**Issue by oabdelsamad** [postmanlabs/newman#1359]
Hi all, 

As far as running a specific folder in collection can be done using **--folder** command. Is there any way to run multiple folders?

**Comment by kunagpal** [comment]
This can be accomplished by using Newman as a library:
```js
var async = require('async'), // https://www.npmjs.com/package/async
  newman = require('newman');

async.parallel([
  async.apply(newman.run, options), // options here is an object with keys: collection, folder, etc
  async.apply(newman.run, options2) // options2 here is an object with keys: collection, folder, etc
], function (err, result) {
  // handle here
});
```

**Comment by oabdelsamad** [comment]
Thank you @kunagpal for your help!
Marking this as closed.

**Comment by codenirvana** [comment]
@oabdelsamad Ability to select multiple folders has been added in **Newman v4.1.0** by specifying `---folder` option multiple times.
