### ISSUE TITLE
Feature Request: Newman command line switch to only output failed results (i.e. errors) to the output json file (as opposed to outputting passed and failed results). 

### ISSUE THREAD

**Issue by leonvangendt** [postmanlabs/newman#136]
Hi guys, for us Newman would be useful if it could output only failed results instead of both successes and failures.... The advantage is that someone in the team can monitor that file for failures and act on them, rather than have to scan through all the results to find the failures to deal with them. 
e.g. newman -c apitests.json -b '02 new basket' -e environment.json -o output.json -f

**Comment by shamasis** [comment]
newman now  (v3.x) has separate `failure` and `executions` array in `json` reporter

```
newman run my-collection.json --reporters cli,json
```

The report will be saved in `newman/html-run-report.html`

**Comment by shmup** [comment]
@shamasis it will be saved as a .json file, not .html

This issue comes up when googling for a problem, and maybe you'll wanna correct your comment. I am interested in knowing more about the reporters. Could you link to the docs in your comment as well?

**Comment by shmup** [comment]
@shamasis removed comment you were probably notified about, because I see that indeed the reporter options are right in the repo README. :)
