### ISSUE TITLE
Newman Custom reports - Unable to print the response headers by using {{response.header}}

### ISSUE THREAD

**Issue by mdfarhanin** [postmanlabs/newman#1376]
1. Newman Version (can be found via `newman -v`): 3.9.2
 2. OS details (type, version, and architecture): Mac OS 10.13.1
 3. Are you using Newman as a library, or via the CLI?: CLI
 3. Did you encounter this recently, or has this bug always been there: Not sure
 4. Expected behaviour: Displays the headers
 5. Command / script used to run Newman: newman run SignOn-Demo.json -d postmandata.csv -e hint3.json -r cli,html --reporter-html-export report.html --reporter-html-template template.hbs
 6. Sample collection, and auxiliary files (minus the sensitive details): HBS file attached
[template.hbs.zip](https://github.com/postmanlabs/newman/files/1624459/template.hbs.zip
 7. Screenshots (if applicable):

**Comment by mdfarhanin** [comment]
Steps:
1. Use the template as provided in the attachment
2. Run any API - output into a html report
3. Verify if response headers are printing

Expected: Response headers are displayed
Actual: No response headers are displayed - It shows the following
[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]

**Comment by kunagpal** [comment]
@mdfarhanin This is happening because the `headers` property is an object. When handlebars attempts to stringify this object for HTML rendering by calling the `.toString` method on it, a bunch of `[object Object]`. You'll have to use handlebars iteration helpers to traverse the `headers` object and display individual keys and values.
```hbs
{{#each request.headers}}
   {{! Replace this line with appropriate HTML tags using @key and @value }}
{{/each}}
```

**Comment by mdfarhanin** [comment]
Awesome it worked - We can close the issue. Thanks.

**Comment by ssharmasurender3** [comment]
@kunagpal : can you specify the exact keyword to be used
i tried:
{{this.key}}
{{@this.key}}

but nothing worked
