### ISSUE TITLE
postman/newman_ubuntu1404   testscript   error

### ISSUE THREAD

**Issue by zhengyp** [postmanlabs/newman#1378]
Testscript run OK in runner or Windows batch command
![default](https://user-images.githubusercontent.com/24307317/34867260-6a685708-f7ba-11e7-9180-9e540f8e90b9.png)

but when I run the same scripts in docker container its raised some unexpected test error,wolud u pls help me .  scripts and printscreen as blow
var jsonData = JSON.parse(responseBody);
tests["Your test name "] = jsonData.isSuccess === true;
pm.test("Status code is 200", function () {
    pm.response.to.have.status(200);
});
![default](https://user-images.githubusercontent.com/24307317/34867290-85a51380-f7ba-11e7-83f9-fab81326f7d8.png)

**Comment by kunagpal** [comment]
@zhengyp Could you add the following statement to the beginning of your test script and verify that the response is valid JSON?
```js
console.log(pm.response.text());

// rest of the test script goes here
```

**Comment by zhengyp** [comment]
@kunagpal Thank you ！Its all about my own problem .
I figured out its a network problem , if I docker run the script with public network URL everything will be ok . 
thanks anyway！

**Comment by kunagpal** [comment]
@zhengyp Glad it worked out for you. I'm marking this issue closed.
