### ISSUE TITLE
JSON cli reporter output is not in the format expected by the default handlebars template

### ISSUE THREAD

**Issue by mikecg** [postmanlabs/newman#1391]
1. Newman Version (can be found via `newman -v`): 3.8.3
 2. OS details (type, version, and architecture): windows 10 x64
 3. Are you using Newman as a library, or via the CLI? both
 3. Did you encounter this recently, or has this bug always been there: always
 4. Expected behaviour: I would expect that the JSON returned by the JSON cli reporter could be used with the [default handlebars template](https://github.com/postmanlabs/newman/blob/develop/lib/reporters/html/template-default.hbs) for the HTML cli reporter. That way, I could easily modify the handlebars template, and have sample data available. It looks like the template expects a different JSON schema than the one output by the JSON reporter. Can we have an option to output JSON in that format? Or is the schema specified somewhere?
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by kunagpal** [comment]
@mikecg The HTML and JSON reporters are entirely different, as they serve different purposes and provided different details about the collection run. If you're looking to add additional details to the HTML reporter, you can do so using your own custom templates with the `--reporter-html-template <path-to-handlebars-template>`. A sample of the JSON passed to the HTML report template is provided here for reference: https://github.com/postmanlabs/newman/blob/develop/examples/reports/html-reporter-template-data.json. Note that additional details cannot be added to the sample JSON template. If you do need additional details, or a high degree of customization, you'd want to look at https://www.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman#custom-reporters instead. Hope this helps 😄

**Comment by mikecg** [comment]
Thank you. That sample JSON template gives me the information I needed.
