### ISSUE TITLE
 Add a filter in html report

### ISSUE THREAD

**Issue by Schveitzer** [postmanlabs/newman#1395]
Version and environment information:

 1. Newman Version (can be found via `newman -v`):  3.6.1
 2. OS details (type, version, and architecture): Ubuntu 16.04
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: No
 4. Expected behaviour: Have the ability to filter the items in the html report by failure or success.
 5. Command / script used to run Newman: newman run postman_collection.json --environment postman_environment.json -r html
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

I would like to request the addition of a simple filter in the html report that makes it possible to filter the items by failure or by success.

**Comment by kunagpal** [comment]
@Schveitzer While this is currently beyond the scope of the current HTML reporter, this can be accomplished via the custom HTML report templates (https://github.com/postmanlabs/newman#html-reporter-options), or custom Newman reporters (https://www.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman#custom-reporters)

**Comment by Schveitzer** [comment]
Many thanks for the feedback. :D

**Comment by MarcosEllys** [comment]
Hello, I also filter this, so I create my custom template with this filter and other things [newman-html-report-template-verbose
](https://github.com/MarcosEllys/newman-html-report-template-verbose)

**Comment by Schveitzer** [comment]
@MarcosEllys Thank you! :D
