### ISSUE TITLE
newman adds an equals "=" character to a query parameter that has no value

### ISSUE THREAD

**Issue by betson-nuovo** [postmanlabs/newman#1398]
Configuring a URL of the following form in a postman collection (tested with 5.5.0 and 5.6.0-canary01): 
`https://www.google.com?equals`
will result in newman making the request with an added equals "=" character:
`GET https://www.google.com?equals=`

In my use case, we have several endpoints which will fail with this added equals character. 
 
 1. Newman Version (can be found via `newman -v`): 3.9.3
 2. OS details (type, version, and architecture): OSX 10.12.6
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Only tested with this version
 4. Expected behaviour: 
Expect to make the call without the added "=" character
 5. Command / script used to run Newman: 
`newman run Basic-Equals-Repro.postman_collection.json -r cli,json --reporter-json-export equals-sign-report.json`
 6. Sample collection, and auxiliary files (minus the sensitive details):
[EqualsTest.zip](https://github.com/postmanlabs/newman/files/1662233/EqualsTest.zip)

**Comment by shamasis** [comment]
This does not happen in Postman Native App? We did put a lot of safeguards against this. @kunagpal can you have a look?

**Comment by betson-nuovo** [comment]
Tested with the postman app itself and I am seeing my endpoints fail, whereas a curl succeeds.
Tested with Postman 5.5.0, 5.5.2, 5.6.0-canary01

**Comment by Carmot** [comment]
cURL code auto generated by Postman v5.5.2 for: GET https://www.google.com?equals

curl -X GET \
  'https://www.google.com?equals='

**Comment by kunagpal** [comment]
@betson-nuovo @Carmot Could you also share the collections that are behaving as described above?

**Comment by betson-nuovo** [comment]
@kunagpal sample collection already attached to the initial post

**Comment by kunagpal** [comment]
@betson-nuovo Thanks, I was able to reproduce this issue with the collection you shared. 😄 

I'll update this thread when a fix is out.

**Comment by betson-nuovo** [comment]
Thanks @kunagpal. Confirmed that editing the json collection and setting `"value": null` makes the correct call when executing in newman.

**Comment by Mina05** [comment]
@kunagpal When will this issue be in progress? We have very large collections and it would be nice if this could be fixed.

**Comment by matiasmatteucci** [comment]
We need this to be fixed too.

**Comment by JebediahSpringfield** [comment]
Just to put some pressure on the issue.

My problem happens in a very simple example
Request:   GET http://10.2.1.1/api?{{myVar}}
Pre-request Script: pm.globals.set("myVar", "param=paramValue");

Result: GET http://10.2.1.1/api?param=paramValue=

My workaround is adding the '&' so it creates a useless '=' parameter: 
Pre-request Script: pm.globals.set("myVar", "param=paramValue" + "&");

**Comment by kamalaknn** [comment]
Hi, we've pushed a fix for this in our latest Canary apps. You can find the link to download the app [here](https://www.getpostman.com/canary).

Collections exported from this app will NOT add a trailing `=` when run with newman.

**Comment by bartdkmediahuis** [comment]
@kamalaknn : Any idea when this will be deployed to the stable newman version ? We do have a lot of tests failing on this bug. Switching to canary is not an option at the moment.

**Comment by shadone** [comment]
Hi there,

I just hit the same issue - Postman app work correctly and does *not* append trailing`=` sign but the newman cli does. Is there a chance this will be fixed?

**Comment by kunagpal** [comment]
@shadone Which Newman version are you on?
