### ISSUE TITLE
How can we write test script for below response

### ISSUE THREAD

**Issue by ranujn** [postmanlabs/newman#1411]
I am getting below response from API

{
    "user": {
        "userRoles": [
            "xyzkjdshfls",
            "abcdsjfhls",
            "uhtkjshfls"
        ]
    }
}

I tried to use with userRoles(0) === "xyzkjdshfls" , userRoles.has("xyzkjdshfls") but its not working for me.

Can anyone tell me how we can verify in Test Script for this response.

**Comment by prakharjoshi** [comment]
@ranujn in the test script you won't be getting the response directly, it will be available to you in the variable called `responseBody`. This `responeBody` will contain the string so you have to parse it fetch the API response like this 
```
let response = JSON.parse(responseBody); 
```
 Now the response contains the actual API response. You can get values like `response.user`. For more information read these docs https://www.getpostman.com/docs/postman/scripts/postman_sandbox. Also you can use PM APIs to fetch the response.

**Comment by ranujn** [comment]
Thanks for quick response. I am using these 2 statement

var json = JSON.parse(responseBody);
var user= json.user;

after that I tried below statement
user.userRoles(0) === "xyzkjdshfls" , user.userRoles.has("xyzkjdshfls")

**Comment by prakharjoshi** [comment]
@ranujn can you provide the error that you are getting. Also, there are specific ways through which you should assert and test the response. Check [here](https://www.getpostman.com/docs/postman/scripts/test_examples).

**Comment by Izidi** [comment]
@ranujn I think that you want to change this to:
`pm.expect(pm.response.json.user.userRoles[0]).to.eql("xyzkjdshfls")`
