### ISSUE TITLE
Design for "Resolve sync conflicts" UI

### ISSUE THREAD

**Issue by ionutincau** [postmanlabs/newman#1418]
In the Resolve sync conflicts UI is a lot of whit space for item type, item id, property name, and the values I care about (server value and local value) are on the right are on right side in small columns.

Please make this screen bigger, maybe with a side by side view of changes (like git diff), and maybe item type, id on top like a title not a column

**Comment by ionutincau** [comment]
Also thanks :) Postman is awesome!

**Comment by kunagpal** [comment]
@ionutincau Thanks for the love, much appreciated. This issue tracker is exclusive to Newman. Could you create this issue here: https://github.com/postmanlabs/postman-app-support/issues/new? Thanks!
