### ISSUE TITLE
Allow for btoa function in tests/pre-request scripts

### ISSUE THREAD

**Issue by zakhenry** [postmanlabs/newman#142]
Part of my authentication negotiation scheme involves passing base64 encoded strings around (JSON web token).

In postman I can use the btoa() function to encode my strings, but this function is unavailable to newman.

Can this function (and the atob counterpart) please be added to newman?

**Comment by gornialberto** [comment]
It seems with the latest release it dind't work anymore!

There was an error in evaluating the Pre-request Script:  TypeError: btoa is not a function
