### ISSUE TITLE
Newman fails to bail out

### ISSUE THREAD

**Issue by prateeksarda** [postmanlabs/newman#1422]
1. Newman Version (can be found via `newman -v`): 3.9.1
 2. OS details (type, version, and architecture): Linux
 3. Are you using Newman as a library, or via the CLI? Newman NodeJS library
 3. Did you encounter this recently, or has this bug always been there: Recently
 4. Expected behaviour: Collection to bail out for test assertion failure
 5. Command / script used to run Newman: 
newman.run({
				bail : true, // even tried with bail : ['failure']
				collection : require(collection)
});
 6. Sample collection, and auxiliary files (minus the sensitive details):
[sample.postman_collection.zip](https://github.com/postmanlabs/newman/files/1716765/sample.postman_collection.zip)
 7. Screenshots (if applicable):

Sample collection is just for reproducing the issue.

**Comment by kunagpal** [comment]
@prateeksarda Apologies for the delay, the `bail` option will stop the collection run after the current request's test script has completed, and not send any further requests. I've corrected our docs to reflect this here: https://github.com/postmanlabs/newman/pull/1442

**Comment by prateeksarda** [comment]
@kunagpal So bail is used to stop the collection during any failures in test script.
What if i have two assertion (in my case as mentioned in screenshot) and want to stop the request as soon as first assertion fails?

**Comment by kunagpal** [comment]
@prateeksarda This can be accomplished by using Newman programatically, and calling `process.exit(1);` inside the event listener for tests if a test has failed. Newman run events are documented here: https://github.com/postmanlabs/newman#newmanrunevents

**Comment by prateeksarda** [comment]
@kunagpal Thank you, that could work.

**Comment by kunagpal** [comment]
@prateeksarda No, as the Node process itself will come to a halt. Is there any special handling being done in the `done` event listener?

**Comment by kunagpal** [comment]
@prateeksarda The absence/presence of a `done` event listener won't affect actual execution, as these events are merely extensions to allow a greater depth of customizable behaviour, as is the case here. Once `process.exit` has been called for a failed test, the collection run will be stopped as well.

**Comment by kunagpal** [comment]
@prateeksarda The documentation for `--bail` has been updated now. Thanks for reporting this, feel free to get back if you have any other questions 😄
