### ISSUE TITLE
Environment Variables Sent as String instead of Int when added into POST Body

### ISSUE THREAD

**Issue by Izidi** [postmanlabs/newman#1431]
1. Newman Version - 3.9.3
2. OS details (type, version, and architecture): Windows 10
3. Are you using Newman as a library, or via the CLI? CLI
3. Did you encounter this recently, or has this bug always been there: _Always - only used current version_
4. Expected behaviour: Taking a variable from the collection variables is being sent as a string instead of as an int.

**Steps to reproduce the problem:**

1. Have an endpoint which is expecting an int from within the body of the POST.
2. Use the curly braces in order to grab the value from the environment variables. e.g. 
```
"placeholders": {
    	"object_guid": {{object_guid}}
    }
```

This is working as expected in Postman and the test will pass however in sending the same test through newman, the variable is being saved as for example `{ "object_guid": '38' }` which then causes later tests which are expecting an int to fail.

**Comment by prakharjoshi** [comment]
@Izidi Can you please share the collection and environment (If any) for which you are facing this issue. Feel free to remove sensitive information from collection and environment.

**Comment by kunagpal** [comment]
@Izidi Could you try this out with Newman v3.9.4 and confirm that it works correctly?

**Comment by Izidi** [comment]
@kunagpal sorry for the delays in responding. This is working for me now using v3.9.4. 

Thanks 👍
