### ISSUE TITLE
is there any way to display pass percentage in terminal/html report ?

### ISSUE THREAD

**Issue by jayanthktn** [postmanlabs/newman#1436]
Postman for Windows
Version 5.3.2
Win 7 / x64
Newman 3.9.3

My request is to display the pass percentage in the console log - Much easier for management people.
Additionally adding percentage of passed Test cases . 79 passed out of 93 means = 84.94%..

Something like that.

**Comment by kunagpal** [comment]
While this isn't possible in the default reporter, setting percentage reports up using a custom reporter is quite straightforward, as can be seen below.

1. You can start off by checking out our docs for custom Newman reporters here: https://www.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman#custom-reporters
2. Next, you can build on top of the existing [HTML reporter](https://github.com/postmanlabs/newman/tree/develop/lib/reporters/html) to add your own helper for percentage calculations. This can be done by including the following snippet in your custom reporter code:
```js
handlebars.registerHelper('percent', function (passed, failed) {
  return (passed * 100 / (passed + failed)).toFixed(2);
});
```

3. Now, you can use compute percent values anywhere in your report by including the following statement in the handlebars template:
```hbs
{{percent cumulativeTests.passed cumulativeTests.failed}}
```

4. Note that the javascript code for your custom reporter will have to reference the path to your modified handlebars template.

Feel free to revert if you have any questions 😄

**Comment by jayanthktn** [comment]
I am getting the following error .

\helper-missing.js:19
      throw new _exception2['default']('Missing helper: "' + arguments[arguments.length - 1].name + '"');
      ^
Error: Missing helper: "percent"



Here's my main code,
 <script type="text/javascript">
    function writeJSON(mode, text) {
      if (mode == 1) {
        try {
          var ptext = text.replace(/&quot;/g, '"');
          // see also https://stackoverflow.com/questions/3700326/decode-amp-back-to-in-javascript
          document.write(JSON.stringify(JSON.parse(ptext), null, 4));
        } 
        catch (err) {
          // simply output as normal text if parsing as json fails
          document.write(text);
        } 
      } else {
        document.write(text);
      }
    }
  </script>

  <script type="text/javascript">
    handlebars.registerHelper('percent', function (passed, failed) {
        return (passed * 100 / (passed + failed)).toFixed(2);
      });
  </script>

</head>
<body>
  <div class="container">
    <h3>Newman Report</h3>
    <div class="row">
      {{#with summary}}
        <div class="col-md-3">Collection</div><div class="col-md-9">{{collection.name}}</div>
        {{#if collection.description}}<div class="col-md-3">Description</div><div class="col-md-9">{{collection.description}}&nbsp;</div>{{/if}}
      {{/with}}
        <div class="col-md-3">Time</div><div class="col-md-9">{{timestamp}}</div>
        <div class="col-md-3">Exported with</div><div class="col-md-9">Newman v{{version}}</div>
        <div class="col-md-12">&nbsp;</div>
        <div class="col-md-4">&nbsp;</div><div class="col-md-4"><strong>Total</strong></div>
        <div class="col-md-4"><strong>Failed</strong></div>
        <div class="col-md-4"><strong>Passed Percentage</strong></div>
      {{#with summary}}
        {{#with stats}}
          <div class="col-md-4">Iterations</div><div class="col-md-4">{{iterations.total}}</div><div class="col-md-4">{{iterations.failed}}</div>
          <div class="col-md-4">Requests</div><div class="col-md-4">{{requests.total}}</div><div class="col-md-4">{{requests.failed}}</div>
          <div class="col-md-4">Prerequest Scripts</div><div class="col-md-4">{{prerequestScripts.total}}</div><div class="col-md-4">{{prerequestScripts.failed}}</div>
          <div class="col-md-4">Test Scripts</div><div class="col-md-4">{{testScripts.total}}</div><div class="col-md-4">{{testScripts.failed}}</div>
          <div class="col-md-4">Assertions</div><div class="col-md-4">{{assertions.total}}</div>
          <div class="col-md-4">{{assertions.failed}}</div>
          <div class="col-md-4">{{percent assertions.total assertions.failed}}</div>
        {{/with}}

        <div class="col-md-12">&nbsp;</div>
        <div class="col-md-6">Total run duration</div><div class="col-md-6">{{duration}}</div>
        <div class="col-md-6">Total data received</div><div class="col-md-6">{{responseTotal}} (approx)</div>
        <div class="col-md-6">Average response time</div><div class="col-md-6">{{responseAverage}}</div>

        <div class="col-md-12">&nbsp;</div>
        <div class="col-md-3"><strong>Total Failures</strong></div><div class="col-md-6"><strong>{{failures}}</strong></div>
      {{/with}}
    </div>

    <br/><h4>Requests</h4>

    {{#each aggregations}}
        {{#if parent.name}}
        <div class="panel-group" id="collapse-folder-{{parent.id}}" role="tablist" aria-multiselectable="true">
            <div role="tab" id="folderHead-{{parent.id}}">
                <h4 style="font-size: 18px;" class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#folderData-{{parent.id}}" ><strong>{{parent.name}}</strong></a></h4>
            </div>
            <br/>
            <div id="folderData-{{parent.id}}" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="folderHead-{{parent.id}}">
            {{> aggregations}}
            </div>
        </div>
        {{else}}
        {{> aggregations}}
        {{/if}}
    {{/each}}
  </div>
</body>
</html>

{{#*inline "aggregations"}}
    {{#each executions}}
        <div class="panel-group" id="collapse-request-{{item.id}}" role="tablist" aria-multiselectable="true">
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="requestHead-{{item.id}}">
                    <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#requestData-{{item.id}}" >{{item.name}}</a></h4>
                </div>

                <div id="requestData-{{item.id}}" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="requestHead-{{item.id}}">
                    <div class="panel-body">
                        {{#with request}}
                            {{#if description.content}}
                                <div class="col-md-4">Description</div><div class="col-md-8" style="white-space: pre-wrap;">{{description.content}}</div>
                                <div class="col-md-12">&nbsp;</div>
                            {{/if}}

                            <div class="col-md-4">Method</div><div class="col-md-8">{{method}}</div>
                            <div class="col-md-4">URL</div><div class="col-md-8"><a href="{{url}}" target="_blank">{{url}}</a></div>
                            <div class="col-md-4">Request Headers</div><div class="col-md-8 preformatted">{{headers}}</div>
                            <div class="col-md-4">Request Body</div><div class="col-md-8 preformatted">{{body}}</div></div>
                        {{/with}}

                        <div class="col-md-12">&nbsp;</div>
                        <div class="col-md-4">Mean time per request</div><div class="col-md-8">{{mean.time}}</div><br/>
                        <div class="col-md-4">Mean size per request</div><div class="col-md-8">{{mean.size}}</div><br/>

                        <div class="col-md-12">&nbsp;</div>
                        <br/><div class="col-md-4">Total passed tests</div><div class="col-md-8">{{cumulativeTests.passed}}</div>
                        <div class="col-md-4">Total failed tests</div><div class="col-md-8">{{cumulativeTests.failed}}</div><br/>

                        <div class="col-md-12">&nbsp;</div>
                        <br/><div class="col-md-4">Status code</div><div class="col-md-8">{{response.code}}</div><br/>
                        <br/><div class="col-md-4">Response Headers</div><div class="col-md-8">
<ul>{{#each response.header}} 
  <li>{{this.key}}:  {{this.value}}</li>
{{/each}}</ul>
&nbsp;
</div><br/>
                        <br/><div class="col-md-4">Response body</div><div class="col-md-8 preformatted">{{response.body}}</div><br/>

                        {{#if assertions.length}}
                            <div class="col-md-12">&nbsp;</div>
                            <div class="col-md-4">Tests</div>

                            <div class="col-md-8">
                                <table class="table table-responsive table-condensed">
                                    <thead><tr><th>Name</th><th>Pass count</th><th>Fail count</th></tr></thead>
                                    <tbody>{{#each assertions}}<tr><td>{{this.name}}</td><td>{{this.passed}}</td><td>{{this.failed}}</td></tr>{{/each}}</tbody>
                                </table>
                            </div>
                        {{/if}}
                    </div>
                </div>
            </div>
    {{/each}}
{{/inline}}

Or If you share me your personal mail, i ll share my custom template.

**Comment by kunagpal** [comment]
@jayanthktn The `handlebars.registerHelper` call has to go within the custom reporter code, not in the script tags in the template. A sample of the file I was referring to can be found here: https://github.com/postmanlabs/newman/blob/develop/lib/reporters/html/index.js.

Using the steps mentioned here: https://www.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman#custom-reporters, you can build your own custom reporter that works with percent calculations as well.

**Comment by jayanthktn** [comment]
Hi Kunagpal,

I am not much aware of handlebars, i have only one .hbs file. do i need to change in hbs file or need to write separate js file.


Thanks,
Jayanth

**Comment by kunagpal** [comment]
@jayanthktn The `.hbs` file will contain just the template content (of the form `{{...}}`). The actual logic to will have to go into a separate JS file. A starter template can be picked up from https://github.com/postmanlabs/newman/blob/develop/lib/reporters/html/index.js. Once you've added the `handlebars.registerHelper` snippet in this file, you can publish these files as a custom reporter, which can then be used within Newman.

**Comment by jayanthktn** [comment]
Thanks kunagpal. It's worked.
