### ISSUE TITLE
Newman doesn't understand `pm.command`

### ISSUE THREAD

**Issue by mtoothman** [postmanlabs/newman#1439]
1. Newman Version (can be found via `newman -v`): 3.4.2
 2. OS details (type, version, and architecture): macOS 10.13.3 (High Sierra
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: always
 4. Expected behaviour: Able to export from Postman and run collection with newman.
 5. Command / script used to run Newman: 
`newman -e foo.postman-environment.json bar.postman-collection.json
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

newman output
```
→ set_session_value
  POST https://my-site/api/user_management/set_session_value [200 OK, 247B, 84ms]
  1⠄ ReferenceError in test-script

→ get_session_value
  POST https://my-site/api/user_management/get_session_value [200 OK, 284B, 79ms]
  2⠄ ReferenceError in test-script
```
```
  #  failure                       detail

 1.  ReferenceError                pm is not defined
                                   at test-script
                                   inside "set_session_value" of "augmenter-ed minimal"

 2.  ReferenceError                pm is not defined
                                   at test-script
                                   inside "get_session_value" of "augmenter-ed minimal"
```

**Comment by kunagpal** [comment]
@mtoothman The pm API is available with Newman v3.6.0 and above, as can be seen here: https://github.com/postmanlabs/newman/blob/develop/CHANGELOG.yaml

**Comment by mtoothman** [comment]
@kunagpal sorry about that, thanks for the info.

**Comment by rohitkashyapvatta** [comment]
@kunagpal : I am on latest newman version newman@3.9.3 and still getting this error:

ReferenceError    pm is not defined                                     
                       at prerequest-script   

Could you please advise on the solution?
