### ISSUE TITLE
Failed to run postman script through Newman when running behind corporate proxy

### ISSUE THREAD

**Issue by vijaygroovey** [postmanlabs/newman#1445]
1. Newman Version (can be found via `newman -v`):3.9.3
 2. OS details (type, version, and architecture):Windows 10
 3. Are you using Newman as a library, or via the CLI? :CLI
 3. Did you encounter this recently, or has this bug always been there: THis is the first script I am running through Newman behind proxy
 4. Expected behaviour: Should work as same when We run through Postman 
 5. Command / script used to run Newman: newman run [Script Name].json - html
 6. Sample collection, and auxiliary files (minus the sensitive details): Not getting any error details just script is failed 
 7. Screenshots (if applicable):

**Comment by kunagpal** [comment]
@vijaygroovey Could you take a look at https://github.com/postmanlabs/newman#proxy and confirm that the required system environment variables are being set?

**Comment by vijaygroovey** [comment]
Setproxy resolved this issue.
