### ISSUE TITLE
when running in newman alll HEAD request tests fail that work fine in postman

### ISSUE THREAD

**Issue by aprixon01112017** [postmanlabs/newman#1449]
Postman 5.5.3 on Windows 10
newman 3.9.3
collection v2.1.0

when running in newman alll HEAD request tests fail that work fine in postman

**Comment by kunagpal** [comment]
@aprixon01112017 Could you also provide a sample collection that would help us reproduce this issue?  Please mention the command/script used to run Newman as well.

**Comment by aprixon01112017** [comment]
Got it:

When saving the collection Postman adds a body property to the HEAD request. I guess I duplicated it from the corresponding GET request. In Postman the Body tab for HEAD is deactivated, but it is in the JSON file.

newman apparently doesn't ignore it the same ways so the tests fail.

**Comment by kunagpal** [comment]
@aprixon01112017 Thanks for sharing that, we'll use this information to improve upon the request body handling mechanisms. 😄

**Comment by aprixon01112017** [comment]
Actually it seems to be a body from a response that is added to the HEAD entry
