### ISSUE TITLE
Question: using authorization types with Newman

### ISSUE THREAD

**Issue by hitcl08** [postmanlabs/newman#1460]
Hi there,

Just wanting to find out if there is a way to use authorization types with Newman. Specifically **OAuth 2.0**. I see it can be done using Postman but can't find anything in Newman.

Is there a feature for this in Newman or should I look at other ways of going about authorization

Version and environment information:

 1. Newman Version (can be found via `newman -v`): 3.9.3
 2. Are you using Newman as a library, or via the CLI? using via CLI
 7. Screenshots:

![authorization types](https://user-images.githubusercontent.com/33255357/37092502-d709199a-2214-11e8-9688-3bf60dfe0b09.png)
![oauth2_0 type](https://user-images.githubusercontent.com/33255357/37092501-d6be1d00-2214-11e8-8168-8bea98054d08.png)

**Comment by kunagpal** [comment]
Hey @hitcl08, you'll have to save your request to a collection, export that collection, and provide the file path as the first command to the `newman run ...` command. In the exported collection JSON file, you'll see an `auth` property that contains all the required properties for OAuth2 request handling.

In other words, no additional work is required to get OAuth2 working, all you have to do is export the collection from the app and run it in Newman 😄

**Comment by NethajiV** [comment]
On exporting I can see the OAuth2 in the collection. But when I run the newman I got 401 access token invalid. Any suggestions please
