### ISSUE TITLE
Postman console log not allowing to write string in next line

### ISSUE THREAD

**Issue by mituljain19** [postmanlabs/newman#1477]
I am trying to display string into multilines with \n

Example: var mystr='line\n another line\n another line'; console.log(mystr);

Expecting: 
line
another line
another line

Getting: lineanother lineanother line

Note: it is working as expected in firefox scratchpad.

**Comment by mituljain19** [comment]
Dear Kunal,
Any updates??

**Comment by kunagpal** [comment]
Hey @mituljain19, sorry for the delay. I've managed to reproduce this, and will update this thread when any progress is made.

**Comment by kunagpal** [comment]
Hey @mituljain19, a quick update: The string representation you see in the console output is intended to be as is (so as to provide exact string representations for better debugging). You can use separate console.log statements to achieve the desired newline effect.
