### ISSUE TITLE
'JSONError in test-script' after migration to Desktop Postman 

### ISSUE THREAD

**Issue by Alextunchii** [postmanlabs/newman#1483]
Newman 3.9.3
Mac OS Version 10.12.6

Hi!
Finally migrated to Desktop Postman from Chrome App and encountered a small issue.
I have been using newman for API tests in TeamCity and after migrating to 'new' Postman I have some error related to JSON parse (i think)

`POST https://1.amazonaws.com/dev/api/v1/auth/sign-up [400 Bad Request, 900B, 363ms]
  1⠄ JSONError in test-script
`

As it seen, it's just POST request where I parse body, here is the full testBody:
```
let Email = JSON.parse(responseBody);
postman.setEnvironmentVariable("email", Email.data.user.email);
console.log(Email);

var env = postman.getEnvironmentVariable('registration_email'); 
env = parseInt(env) + 1;
postman.setEnvironmentVariable("registration_email", env);

var reg = postman.getEnvironmentVariable('emails_registration');
if (reg === undefined) {
    reg = '';
}
postman.setEnvironmentVariable("emails_registration", reg);
reg += ', ' + postman.getEnvironmentVariable('prefix_re_email') + postman.getEnvironmentVariable('registration_email') + '@gmail.com';

tests["Status code is 200"] = responseCode.code === 200;
tests["Response time is less than 9000ms"] = responseTime < 9000;
```

This is a [console.log](https://www.dropbox.com/s/xwhy479h2wwb60h/1522348369674.jpg?dl=0) from Postman
In newman console log is not shown

The response body is very distinct. And in Postman no one error is present,
but what a strange thing for me, that this POST request (Sign Up) in newman has 400 responseCode but anyway passes parsed email to next POST request(login) and the login is successful.

How is it possible, if 400, a user is not registered and accordingly he can't log in, I don't know how.
I can provide additional info and data if needed.

This is only in one test out of 150

If delete it:
```
var env = postman.getEnvironmentVariable('registration_email'); 
env = parseInt(env) + 1;
postman.setEnvironmentVariable("registration_email", env);

var reg = postman.getEnvironmentVariable('emails_registration');
if (reg === undefined) {
    reg = '';
}
postman.setEnvironmentVariable("emails_registration", reg);
reg += ', ' + postman.getEnvironmentVariable('prefix_re_email') + postman.getEnvironmentVariable('registration_email') + '@gmail.com';
```
the result is the same

**Comment by Alextunchii** [comment]
strange, but resolved just by this changes:
1. moved places for 1 and 3 row
2. changed the name of a variable 

let JsonEmail = JSON.parse(responseBody);
console.log(JsonEmail);
postman.setEnvironmentVariable("email", JsonEmail.data.user.email);

**Comment by Sha-123** [comment]
if anyone found solution, please share it

**Comment by shamasis** [comment]
The solution was in the last reply - the variable names within the script needed to be fixed.
