### ISSUE TITLE
Getting error - "TypeError handler._sign is not a function" in jenkins

### ISSUE THREAD

**Issue by vinaysuri1** [postmanlabs/newman#1486]
I have created postman scripts - exported my collection - pushed to my GIT repo - ran collection using newman - created a job in jenkins with GIT URL - triggered the job

Scripts are working fine in POSTMAN.
Scripts are working fine in NEWMAN.
But I am getting following error in JENKINS - console output - 
TypeError handler._sign is not a function

Please help...
Thanks in advance

**Comment by kunagpal** [comment]
Closing as a duplicate of #1484
