### ISSUE TITLE
i have downloaded newman  .zip and i have installed all prerequisites nodejs v8.9.0,git cmd.while running npm install newman --global;got npm ERR! code ENOSELF npm ERR! Refusing to install package with name "newman" under a package npm ERR! also called "newman". Did you name your project the same npm ERR! as the dependency you're installing? npm ERR! npm ERR! For more information, see: npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>  npm ERR! A complete log of this run can be found in: npm ERR!     C:\Users\sxn8309\AppData\Roaming\npm-cache\_logs\2018-04-06T10_24_48_938Z-debug.log;so i renamed the package.json name as newman1,after renaming and running newman run examples/sample-collection.json;newman is not recognised as the valid comman.Please help opn this.

### ISSUE THREAD

**Issue by sankar91** [postmanlabs/newman#1487]
1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

i have downloaded newman  .zip and i have installed all prerequisites nodejs v8.9.0,git cmd.while running npm install newman --global;got npm ERR! code ENOSELF npm ERR! Refusing to install package with name "newman" under a package npm ERR! also called "newman". Did you name your project the same npm ERR! as the dependency you're installing? npm ERR! npm ERR! For more information, see: npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>  npm ERR! A complete log of this run can be found in: npm ERR!     C:\Users\sxn8309\AppData\Roaming\npm-cache\_logs\2018-04-06T10_24_48_938Z-debug.log;so i renamed the package.json name as newman1,after renaming and running newman run examples/sample-collection.json;newman is not recognised as the valid comman.Please help opn this.

**Comment by kunagpal** [comment]
@sankar91 I've edited the original title for brevity. npm does not allow installing packages as dependencies themselves. You can install Newman with `npm i -g newman` without having to download any zipped archives.
