### ISSUE TITLE
newman HTML report only display first Iteration value that comes from csv file

### ISSUE THREAD

**Issue by hasanyc** [postmanlabs/newman#1489]
So in my csv file I have 37 values and when I run via terminal it triggers 37 iterations with no issue.: https://screencast.com/t/cftzQla6Iml
This is my script look like: https://screencast.com/t/eTWPiXctou9

Inside the HTML report, it does shows correct Iterations 37 and Request shows 703 since i had 19 postman request. 
However method URL keep showing first value from csv file. After 19th Method URL it should display 2nd value from csv file but it's not doing that
See the issue in HTML Report: https://screencast.com/t/qWZWw0VoC6B

npm version is 5.6.0 and newman version is 3.9.3

-->

**Comment by kunagpal** [comment]
Apologies for the delay @hasanyc, but this is intended behaviour. The inbuilt HTML reporter aggregates statistics across multiple iterations.

**Comment by yandongyan** [comment]
I encounters the same issue. Is there any workaround to solve this?
