### ISSUE TITLE
HTML report needs to include request response payloads

### ISSUE THREAD

**Issue by EtonDoze** [postmanlabs/newman#1493]
1. Newman Version: 3.9.3
 2. OS details (type, version, and architecture): Mac OSX 10.11.6
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Its an enhancement request
 4. Expected behaviour: newman report to include Request Response Payloads along with Method Name, URL
 5. Command / script used to run Newman: newman run collection.json -r html
 6. Sample collection, and auxiliary files (minus the sensitive details): https://github.com/postmanlabs/newman/blob/develop/examples/reports/sample-collection-report.html

Steps to reproduce the problem:

1. Run newman test via CLI with html report
2. Open report file in browser.
Consider collapse-expand widget for long-form payloads.
Consider HAR as additional format - http://www.softwareishard.com/har/viewer/

**Comment by tegomass** [comment]
Hi,

The request/response payload can be get with `requset.body` and `response.body`.
If you add in your .hbs report this information, you should have what you want.

Example : 
Add :
```
<div class="col-md-12">&nbsp;</div>
<br/><div class="col-md-4">Request body</div><div class="col-md-8">{{request.body}}</div><br/>
<div class="col-md-12">&nbsp;</div>
<br/><div class="col-md-4">Response body</div><div class="col-md-8">{{response.body}}</div><br/>
```
After : 
`<br/><div class="col-md-4">Status code</div><div class="col-md-8">{{response.code}}</div><br/>`

**Comment by tegomass** [comment]
You can add it into a `textarea`, the output should be better.
```
<div class="col-md-12">&nbsp;</div>
<br/><div class="col-md-4">Request body</div><div class="col-md-8"><textarea disabled rows="8" cols="70">{{request.body}}</textarea></div><br/>
<div class="col-md-12">&nbsp;</div>
<br/><div class="col-md-4">Response body</div><div class="col-md-8"><textarea disabled rows="8" cols="70">{{response.body}}</textarea></div><br/>
```

👍

**Comment by shamasis** [comment]
We will not add this feature in HTML reporter since response can be of various types. I suggest someone create a reporter that saves every request response to file.
