### ISSUE TITLE
Get request has body with invalid details when ran through newman

### ISSUE THREAD

**Issue by santhosh2512** [postmanlabs/newman#1501]
1. Newman Version (can be found via `newman -v`):3.9.3
 2. OS details (type, version, and architecture):Version 6.0.10
win32 6.1.7601 / x64
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there: Always noticed this issue
 4. Expected behaviour:Due to wrong request, invalid response we are getting and due to that upcoming request are failing
 5. Command / script used to run Newman: We have run it though jenkins
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/38418500/38793864-91b6e950-4170-11e8-9460-641fe0e6d1d3.png)

**Comment by kunagpal** [comment]
@santhosh2512 GET request bodies are not supported currently. I'll mark this as a feature request. 😄

**Comment by santhosh2512** [comment]
Hi,

That was not my issue actually. I am saying while running collection using Newman, it sends wrongly framed request. I did not pass body contents in GET request but not sure from where the body contents are picked and sent in a request.

Its a bug.

Thanks

**Comment by santhosh2512** [comment]
thanks for the explanation. I have removed the body by changing it to POST. This issue can be closed.
