### ISSUE TITLE
Error replacing {{variable}} with value when 'variable' = 0 in body of POST request

### ISSUE THREAD

**Issue by dvan93** [postmanlabs/newman#1505]
Postman for Windows 6.0.10
Newman 3.9.3
Windows 10, 10.0.15063, x64

When running newman via CLI with a postman collection, environment/data/global variables inserted into JSON body of a POST request (e.g. {{variable_name}}) are removed (become blank in request) **when the value of the variable is equal to 0 (int)**. This causes request to fail as the JSON is no longer valid.

Sample JSON in POST request body:

This bug can be reproduced via the attached postman collection.
{
	"valuesFromEnvironment": 
	{
		"zero": {{zero}},
		"one": {{one}}
	},
	"valuesHardCoded":
	{
		"zero": 0,
		"one": 1
	}
}

In the pre-request script, I set global variables 'zero' equal to 0 (int) and 'one' equal to 1.
I expect the request to be sent with the JSON body as:

{
	"valuesFromEnvironment": 
	{
		"zero": 0,
		"one": 1
	},
	"valuesHardCoded":
	{
		"zero": 0,
		"one": 1
	}
}

But instead it is:
{
	"valuesFromEnvironment": 
	{
		"zero": ,
		"one": 1
	},
	"valuesHardCoded":
	{
		"zero": 0,
		"one": 1
	}
}

For comparison, the 'valuesHardCoded' are there to show that the process of replacing {{zero}} with the value 0 is where failure occurs, as the hard coded values remain unchanged.

This bug does not seem to be present in Newman 3.8.3 (I've only looked at versions 3.8.3 and 3.9.3). 

Here's the command I used to run my collection via the command line:
 newman run .\NewmanErrorDemonstration.postman_collection.json

See the attached screenshot and postman collection file for more details.

![newmanerror](https://user-images.githubusercontent.com/24846412/39219581-a4c568e0-47e8-11e8-8660-cb40d8392222.PNG)

[NewmanErrorDemonstration.postman_collection.zip](https://github.com/postmanlabs/newman/files/1944993/NewmanErrorDemonstration.postman_collection.zip)

**Comment by kunagpal** [comment]
@dvan93 Could you try this out with Newman 3.9.4 and confirm that it works correctly?
