### ISSUE TITLE
Immediate changes not reflected in jenkins

### ISSUE THREAD

**Issue by shubsaini09** [postmanlabs/newman#1506]
1. Newman Version (can be found via `newman -v`): 3.9.3
 2. OS details (type, version, and architecture): Rhel 7.1
 3. Are you using Newman as a library, or via the CLI? Using Jenkins
 3. Did you encounter this recently, or has this bug always been there: Recently
 4. Command / script used to run Newman: newman run your-link

If you make any change in the collection and run your build in jenkins, then build runs using old changes until a period of time. Immediate effect does not take place. Is this expected or what is the problem?

**Comment by shubsaini09** [comment]
For sometime it was 5 minutes but now i see no changes. Even after an hour i see my jenkins taking old changes. My link is of the form: https://www.getpostman.com/collections/076fa3034435234. Also refer to this issue [#4491](https://github.com/postmanlabs/postman-app-support/issues/4491)

**Comment by kunagpal** [comment]
Interesting. While we take a closer look at this, could you switch to using the Postman API instead? This will ensure that the latest edition of your collection is fetched for the run. More details on this can be found here: https://github.com/postmanlabs/newman#using-newman-with-the-postman-api

**Comment by shubsaini09** [comment]
I see that you want me to access my collection using a different form of URL. I did that but i won't be able to test if what you said fixed my issue or not until my issue [#4491](https://github.com/postmanlabs/postman-app-support/issues/4491) is fixed. My changes are not syncing with postman's server due to which i am getting old date of collection even after going through your way.

**Comment by codenirvana** [comment]
@shubsaini09 is this issue still reproducible?

**Comment by DannyDainton** [comment]
Closing this issue as we haven't seen other users facing the same problem.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Comment by gitNewstreettech** [comment]
Hey Danny I am also facing the same issue, my changes are not reflecting for one of my pipeline, even I am building the fresh image without using the cache.
