### ISSUE TITLE
Please explain how to create this (below screenshot) from Postman or please suggest any other tool to test API and generate HTML reports. Please help.

### ISSUE THREAD

**Issue by samreenadil** [postmanlabs/newman#1512]
![image](https://user-images.githubusercontent.com/38338777/39329463-5ea063da-496c-11e8-8add-735afe41e378.png)

**Comment by prakharjoshi** [comment]
Hi @samreenadil the above screen shot that you mentioned is Postman runner screen shot which you will see when you run the collection through Postman App.

Regrading HTML reporter, Newman supports HTML reporter and you can extract the summary in HTML from Newman run by passing an extra CLI option `--reporter-html`. Check this out for better understanding https://github.com/postmanlabs/newman#html-reporter-options
