### ISSUE TITLE
How to run docker for newman with environment and global json 

### ISSUE THREAD

**Issue by sivcan** [postmanlabs/newman#1514]
Issue originally opened by [Saripr](https://github.com/saripr) 

https://github.com/postmanlabs/postman-app-support/issues/4504

--

Running newman docker with json throws could not find the file even though the file exists in the path and the path is correct
App Details:

Version 6.0.10
newman 3.9.1

Postman for Ubuntu
Version 6.0.10
ubuntu 16.04 LTS

Issue Report:
Did you encounter this recently, or has this bug always been there:yes
Expected behaviour:Tests should run 
Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Screenshots (if applicable)

Steps to reproduce the problem:
Tried adding docker for newman with below commands:

1.Pulling the image:docker pull postman/newman_ubuntu1404
2.docker run --name=“newman” -v /tests/apitest.json:/tmp/newman -t postman/newman_ubuntu1404 run “https://www.getpostman.com/collections/collectionId” --environment = ~/envt/staging.json --globals = ~/data/globals.json and it throws below error even tough the given path is right and json file is present in the path:

<p><b>unable to read data from file “~/environments/staging.json”
ENOENT: no such file or directory, open ‘~/environments/staging.json’ </b></p>

So how do I run docker for newman with environment and globals JSON

**Comment by saripr** [comment]
Also tried in a newman version 3.9.2 and still having the issue

**Comment by kunagpal** [comment]
@saripr Apologies for the delay, you'll have to run as follows:
```
docker run --name=“newman” -v ~/envt:/tmp/newman -t postman/newman_ubuntu1404 run “https://www.getpostman.com/collections/collectionId” --environment staging.json --globals globals.json
```

**Comment by josephthanaraja** [comment]
Hello I have three different collections (GET and POST) and wanted to run multiple newman commands in Single Docker container but it is not working. If I create three container it is working fine. Is it possible to use one container and use three newman run command?.

Working one(two docker with two newman separately):-
docker run ---name uatpostman1 postman/newman:ubuntu run collection1.json -d collectionData1.json  -r cli,junit,htmlextra --reporter-htmlextra-export /var/newman/collection2.html 
docker run ---name uatpostman2 postman/newman:ubuntu run collection2.json -d collectionData2.json  -r cli,junit,htmlextra --reporter-htmlextra-export /var/newman/collection2.html

Expected one(One Docker with 2 Newman run):-
docker run ---name uatpostman postman/newman:ubuntu run collection1.json -d collectionData1.json  -r cli,junit,htmlextra --reporter-htmlextra-export /var/newman/collection1.html postman/newman:ubuntu run collection2.json -d collectionData1.json  -r cli,junit,htmlextra --reporter-htmlextra-export /var/newman/collection2.html

Please help
