### ISSUE TITLE
Jenkins Console Output doesn't display the detailed test run result.

### ISSUE THREAD

**Issue by asalavadigit** [postmanlabs/newman#1524]
Jenkins console output displays just the SUCCESS/FAILURE message after the job is executed for the postman collection using newman. I would like the result to be displayed with more details with the test run like iterations, pass and fail status. any help would be appreciated!

![image](https://user-images.githubusercontent.com/38331691/39769436-d034774a-52b1-11e8-86d3-2dc89a0d866a.png)

However, I am getting the detailed result when i run the same newman command from Command Line.

![image](https://user-images.githubusercontent.com/38331691/39769504-03e9bc1c-52b2-11e8-9e43-e640f9b2bd16.png)

**Comment by abhishekprsetty** [comment]
run this command to save the output:  newman run mycollection.json --reporters cli,json --reporter-json-export outputfile.json

**Comment by abhishekprsetty** [comment]
Yes it was issue with Node version. On upgrading it. It worked fine. 
Thanks a lot. 👍

**Comment by asalavadigit** [comment]
Thanks for the response. However, I would like to view the detailed result on the Jenkins console output itself.  am i missing any additional step to display the result?

**Comment by lexon** [comment]
What is the exact command you execute? Did you provide the cli reporter?
For me it’s working fine, although running on OS C.

**Comment by kunagpal** [comment]
@asalavadigit This can be accomplished by using a JUnit parsing plugin for Jenkins, as has been described here: https://wiki.jenkins.io/display/JENKINS/JUnit+Plugin

**Comment by shanthalarb** [comment]
asalavadigit  , Did you found a solution ? Even I don't see result in Jenkins console. 

![image](https://user-images.githubusercontent.com/41392923/43668564-a4ecbbf4-974b-11e8-8af8-b2115b34c127.png)


Any help will be appreciated!

**Comment by MahmudulMannan08** [comment]
@kunagpal the issue is not resolved. Please reopen this. I am also having same issue

**Comment by MahmudulMannan08** [comment]
> asalavadigit , Did you found a solution ? Even I don't see result in Jenkins console.
> 
> ![image](https://user-images.githubusercontent.com/41392923/43668564-a4ecbbf4-974b-11e8-8af8-b2115b34c127.png)
> 
> Any help will be appreciated!

I guess you also copied shell executable path C:\Windows\system32\cmd.exe on Jenkins configuration. I think if we do that it is not actually running our shell commands inside the project. You can run without any commands at all and it will still show success!

**Comment by aspoehrer** [comment]
I am reviewing this with the same issue and dont see any resolution. Got the same result - SUCCESS but no details as showing in some examples. I need it to show up in Jenkins too. Any help is appreciated!

**Comment by deshpandeji** [comment]
I am facing same issue. Please let me know if there is any solution for this.
Thanks in advance :)

**Comment by byalavarti** [comment]
Any updates on this?

**Comment by emirsalihagic** [comment]
I am facing same issue and there is no explanation over here how to solve issue but issue is closed

**Comment by pgroot91** [comment]
Also facing this issue its almost we are missing some steps to make it working. Tutorial is just bad and not clearly up to date.

**Comment by DannyDainton** [comment]
Hey folks,

As the originally opened issue doesn't contain enough context and information about what is happening during the Jenkins run - could anyone explain the full details of the issue they are seeing, when running the Collection with Newman via Jenkins?

@Sushmithashetty-gep As you're the latest person to report the problem - Can you add more details here?

There are a bunch of Newman <> Jenkins tutorials out there but I know that Valentin Despa always gives a great explanation and something easy to follow with:

https://youtu.be/7ar4-O3vNiM

This videos is slightly older now and shows the older Postman app version but the same Jenkins steps would still apply here.
