### ISSUE TITLE
Not able to run newman command, getting error on Ubuntu 14.04

### ISSUE THREAD

**Issue by abhishekprsetty** [postmanlabs/newman#1526]
1. Newman Version (can be found via `newman -v`):
On executing this command, getting error: usr/local/lib/node_modules/newman/bin/newman.js:235
        _.forEach(reporters, (reporter) => { parsed[reporter] = {}; });
                                         ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

 2. OS details (type, version, and architecture):
Ubuntu 14.04
 3. Are you using Newman as a library, or via the CLI?
Using via CLI
 3. Did you encounter this recently, or has this bug always been there:
I have just installed node and npm and trying to run the command of newman
newman run Ingestion.postman_collection.json -e env.json
node -v
v0.10.25

npm -v 
1.3.10

 4. Expected behaviour:
Should be able to run the tests but its throwing on error:
/usr/local/lib/node_modules/newman/bin/newman.js:235
        _.forEach(reporters, (reporter) => { parsed[reporter] = {}; });
                                         ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

 5. Command / script used to run Newman:
newman run Ingestion.postman_collection.json -e env.json : Both the files are present in the same path

 6. Sample collection, and auxiliary files (minus the sensitive details): any sample json also I am not able to run
<img width="745" alt="screen shot 2018-05-09 at 1 35 09 pm" src="https://user-images.githubusercontent.com/34807579/39803150-c2e333a6-538d-11e8-864e-d88cc7f703ed.png">

 7. Screenshots (if applicable):

Steps to reproduce the problem:
1. After installing node and npm , I have installed newman following this link:https://www.getpostman.com/docs/v6/postman/collection_runs/command_line_integration_with_newman

on running above command getting the error
please help

**Comment by kunagpal** [comment]
@abhishekprsetty Newman does not support versions of Node below v4, you'll have to upgrade your Node version to at-least the latest v4.x release, which is v4.9.1 at the time of writing.

**Comment by abhishekprsetty** [comment]
Yes on upgrading it. Worked fine thanks 👍
