### ISSUE TITLE
Accessing an single array item in handlebars template does not work

### ISSUE THREAD

**Issue by cbarlow1993** [postmanlabs/newman#1541]
1. Newman Version (can be found via `newman -v`): 3.9.3
 2. OS details (type, version, and architecture): Windows 10
 3. Are you using Newman as a library, or via the CLI? Both
 3. Did you encounter this recently, or has this bug always been there: Only recently used newman, can't say.
 4. Expected behaviour: As per the handlebar docs, individual nested array values should be accessible
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

This has plagued me for days and I've managed to do enough debugging to isolate the issue to what I believe is something to do with Newman (although I'm not sure why!)

When trying to use the notation to get a single value of an Array in a handlebars template, no value is returned. i.e body.formdata.[1].value

I've tested using handlebars out the box with a simple node script (see raw_test.js), with the same templates and the same JSON from file and it works fine, but not when run through Newman. 

Steps to reproduce the problem:

1. Edit: lib/reporters/html/template-default.hbs to include some nested array values. See attached example file I used. template-default.hbs. (or create custom html report)
2. Run a collection that includes some form data parameters using the html reporter.
`newman run collection.json -d data.csv -r html`
3. Review the report and see that all nested data does not get output in the template. 
4. Try run `raw_test.js` - `npm install ` first - and see that `output_from_raw_test.html` does populate the data. 
5. Both newman and raw_test.js use handlebars v 4.0.11 so I'm unsure what's going on!

Files available in zip: 
[newman_error.zip](https://github.com/postmanlabs/newman/files/2030715/newman_error.zip)

**Comment by cbarlow1993** [comment]
@kunagpal Thanks for the response. I'm not trying to loop through the data. That works fine, as does the example above. 

I'm trying to just reference the first item in the array, for example body.formdata.[0].value, without wanting loop through the rest of it. 

Sorry for the confusion.

**Comment by kunagpal** [comment]
@cbarlow1993 Yes, this was an example that could be expanded. For your specific use case, you could use the following:
```hbs
<div>Value of 'body.formdata.[0].value': The value is: [ {{body.formdata.members.[0].value}} ]</div>
```

**Comment by cbarlow1993** [comment]
Completely missed the adjustment - thanks for setting me straight!

Is there a summary of the differences between why this behaviour might run in Newman but not in normal handlebars. Just in case I come across something similar in the future?

**Comment by cbarlow1993** [comment]
Great, thanks for the clarification 😄. I'll close this issue now.
