### ISSUE TITLE
Environment variables used as query parameters are used literally %7B%7Byikes%7D%7D

### ISSUE THREAD

**Issue by MarkSonghurst** [postmanlabs/newman#1556]
1. Newman Version (can be found via `newman -v`): 3.9.4
 2. OS details (type, version, and architecture): CentOS 7.latest
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Don't know, was blocked by #1465 previously.
 4. Expected behaviour: Environment variables in URL to be resolved by newman.
 5. Command / script used to run Newman:
```newman run postman/API_v3.postman_collection.json -e postman/deimos.postman_environment.json --insecure --bail```
 6. Sample collection, and auxiliary files (minus the sensitive details): attached

1. My API URL path (I've intentionally excluded the hostname) in Postman is written as follows: 
```/users/{{UserID}}?org={{OrgID}}```

2. The `{{...}}` environment variables are set in a previous API call, they all have valid values (numbers).

3. When run by Postman and Runner, the URL (as reported by my API daemon) looks like this: 
```GET="/users/10615?org=0"```

4. When the same collection is run in newman, the URL appears like this:
```GET="/users/%7B%7BUserID%7D%7D?org=%7B%7BOrgID%7D%7D"```

[snippet.json.txt](https://github.com/postmanlabs/newman/files/2042402/snippet.json.txt)

**Comment by MarkSonghurst** [comment]
This was a bug in my Test script which was not assigning environment variables correctly.
Kinda ugly that newman doesn't detect and warn on this, but at least I figured it out. 
Closing the issue.

**Comment by kunagpal** [comment]
@MarkSonghurst Thanks for sharing that, we could consider adding a CLI reporter flag that displays warnings on missing variables.

**Comment by MarkSonghurst** [comment]
I think that would be really useful!
