### ISSUE TITLE
Getting error about block scoped variable, PR submitted

### ISSUE THREAD

**Issue by rawaludin** [postmanlabs/newman#1571]
I'm using postman on docker, getting this error:

```
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

After some investigation, I believe the problem was in node version. I made a PR to bump the version.

https://github.com/postmanlabs/newman/pull/1570

Can anyone check? Thanks.

**Comment by kunagpal** [comment]
@rawaludin This has been fixed in Newman v3.10.0 😄
