### ISSUE TITLE
Modification of handlebar template (template.hbs) to display results iteration-wise in newman HTML report

### ISSUE THREAD

**Issue by vinaysuri1** [postmanlabs/newman#1572]
Hi all,

**How do I modify the handlebar template (template.hbs) so that results are displayed iteration-wise in newman HTML report?**

As of now, the report getting generated has all the assertions (from all the iterations) - listed down in one block. 
And as many iterations are there - that many number of blocks are repeated with same data i.e. list of assertions.

Version and environment information:
 1. Newman Version - 3.9.3
 2. OS details - Windows Server 2008 R2 Enterprise (64 bit)
 3. Did you encounter this recently, or has this bug always been there: Was there from quite some time
 4. Expected behaviour:  Need to display results iteration-wise for newman HTML report
 5. Command / script used to run Newman:
newman run "<collection name>" -d "<data file name>" -n 2 --color --reporters cli,html --reporter-html-template template.hbs --reporter-html-export outputfile.html

TIA,
Regards,
Vinay

**Comment by kunagpal** [comment]
@vinaysuri1 The inbuilt HTML reporter aggregates run statistics across all iterations, so the data object provided to render the template contains aggregated information. A way around this is to write your own reporter, as has been explained here: https://github.com/postmanlabs/newman#creating-custom-reporters.

Feel free to reach if you have any other questions 😄
