### ISSUE TITLE
Common Test at the folder level are not showing up in xml reports

### ISSUE THREAD

**Issue by mverma-va** [postmanlabs/newman#1573]
1. Newman Version: 3.8.3
 2. OS details (type, version, and architecture): Win10, x64
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: recently
 4. Expected behaviour: xml Report should contain common test results for each api call
 5. Command / script used to run Newman: newman run soti_connect.postman_collection.json -e dev_env.postman_environment.json -k -x --no-color --reporters junit
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by deepakpathania** [comment]
Hey @mverma-va, can you try updating to the latest version, that is, 3.9.4 and see if the still persists for you? Please provide additional details about the issue if it does. Thanks.

**Comment by mverma-va** [comment]
Thanks @deepakpathania , updating to the latest version 3.9.4 fixed the problem, closing the issue.
