### ISSUE TITLE
GET API response is not displayed in newman output

### ISSUE THREAD

**Issue by awang2003** [postmanlabs/newman#158]
newman -c testcase.json -e environment.json -s command successfully executed the API specified in the testcase.json file, it returned 200 response code and time it took, but the API response was not displayed.  Do I need to setup other parameters?  Thanks.

**Comment by coltonlw** [comment]
There should be a CLI option for this, I think the most useful option would be print response body on test failure

**Comment by chetanhonnavile** [comment]
I was looking for a similar kind of thing from newman.

how can i print the response body on failure and success ?

**Comment by pshivapr** [comment]
You can print the response using console.log command. An example below to append your tests
		"event": [
			{
				"listen": "test",
				"script": {
					"type": "text/javascript",
					"exec": [
						"var jsonData = pm.response.json();",
						"console.log(jsonData)"
					]
				}
			}
		]

**Comment by dudestc** [comment]
Could someone share entire steps to output API response in output file.
