### ISSUE TITLE
--reporter-junit-export syntax is inconsistent (and not documented?)

### ISSUE THREAD

**Issue by zcoffin86** [postmanlabs/newman#1590]
Other command line options like `--environment` accepts an `=` delimiter, whereas `--reporter-junit-export` does not. Why is this? Where is this documented? Only after checking out the repository and reading MIGRATION.md was this apparent.

For example, in the command line `newman run "test/postman/newman/v1.postman_collection.json" --environment="test/postman/newman/environments/Quality.postman_environment.json" --reporters="junit,cli" --reporter-junit-export=target/test-reports/TEST-newman-report.xml` the environment is correctly picked up, reporters both are applied, but the reporter-junit-export goes to the default path and filename instead of the specified path and filename.

TIA

**Comment by codenirvana** [comment]
@zcoffin86 Thanks for reporting this, a fix has been added in #1594 which will be rolled out with the next release.

**Comment by kunagpal** [comment]
@zcoffin86 This has been fixed in Newman v3.10.0 😄
