### ISSUE TITLE
Pulling environmental variables from the Postman profile

### ISSUE THREAD

**Issue by Katolus** [postmanlabs/newman#1597]
Hi there,

I was wondering whether it is possible to run a collection using environmental variables stored in the Postman profile without exporting them to a .json file? 

`newman run "sample.postman_collection.json" -e ${Postman's environment identification}`

Another approach to this problem would be to export the environmental variables using newman's cli, before running the collection. Question is whether that is possible?
I tried using,

`newman run --export-environment .` 

however, it doesn't seem to work that way.

**Comment by shamasis** [comment]
Have you looked into - https://docs.api.getpostman.com ? `newman` can procure environment from URLs. There is no way to get collection from app's storage location yet. But that is a great thought.

**Comment by kunagpal** [comment]
@Katolus Do take a look at https://github.com/postmanlabs/newman#using-newman-with-the-postman-api as well 😄
