### ISSUE TITLE
I am getting this error - "Please specify a Postman Collection either as a file or a URL"

### ISSUE THREAD

**Issue by princedrez** [postmanlabs/newman#160]
Error: Please specify a Postman Collection either as a file or a URL. what am i doing wrong here

I am trying the following commands, but still getting the error.

newman -c c:\Add a document.json.postman_collection
newman -c c:\Add a document.json

**Comment by akapoor47** [comment]
What do you mean when you said you need to escape the file name? Can you please give the exact command required to execute.
Here is what I am trying - Under collection folder there is one JSON (I am using mac, if that makes a difference)
newman -c "/Users//Collections"

**Comment by smrutikore** [comment]
After collection you should also mention the json file name with the
extension.
