### ISSUE TITLE
even after successful installation of Newman, "-bash: newman: command not found"  error is thrown

### ISSUE THREAD

**Issue by amitsaxena4u** [postmanlabs/newman#1604]
I have installed NPM and then Newman successfully but when I am trying to check Newman version or running newman for  run my JSON file, it is always giving me error as : -" bash: newman: command not found"
NPM version installed is: 6.1.0
Newman version installed as shown after installation is: newman 3.9.4

Version and environment information:
-->
 1. Newman Version (can be found via `newman -v`): throws -bash: newman: command not found
 2. OS details (type, version, and architecture): Mac OS High Sierra - 10.13.5
 3. Are you using Newman as a library, or via the CLI? simply installeed using npm install -g newman
 3. Did you encounter this recently, or has this bug alw
<img width="802" alt="screen shot 2018-07-01 at 9 26 49 am" src="https://user-images.githubusercontent.com/35827399/42130489-f559530e-7d10-11e8-9348-0b0254806251.png">
ays been there: I am trying first time
 4. Expected behaviour: Newman should be identfied as command on terminal and do as expected
 5. Command / script used to run Newman: newman -v
 6. Sample collection, and auxiliary files (minus the sensitive details): not tried yet
 7. Screenshots (if applicable):

**Comment by kunagpal** [comment]
@amitsaxena4u This issue is nvm specific, there's an extensive discussion on the same here: https://github.com/creationix/nvm/issues/668. 😄

**Comment by qburst-deepu** [comment]
Happened to me too, but when i install this using brew it's working
