### ISSUE TITLE
How to get a document id out of a json file that I ran in newman and store it in the environment variable?

### ISSUE THREAD

**Issue by princedrez** [postmanlabs/newman#162]
I added a file using newman...in the json file i declared 

var data = JSON.parse(responseBody);
postman.setEnvironmentVariable("Folder1Doc1_id", data.id);

how can i get Folder1Doc1_id and use it in an api and run it in a collection?

I tried but i keep getting errMsg": "Argument: ID (Integer) was the wrong type", also Folder1Doc1_id is not stored in the envirnoment variables after I ran newman 

thanks.

**Comment by shamasis** [comment]
This seems to be pending for long. Can somebody from the original participants summarise this if it is still relevant? Else, scheduling for close in near future.

**Comment by kunagpal** [comment]
@princedrez Closing the issue due to inactivity. Do let us know if this problem still persists.
