### ISSUE TITLE
JUnit reporter does not create any summary report .txt file, only the .xml files

### ISSUE THREAD

**Issue by madalinaptj** [postmanlabs/newman#1621]
1. Newman Version (can be found via `newman -v`): 3.9.4
 2. OS details (type, version, and architecture): Windows 10 with local Jenkins server
 3. Are you using Newman as a library, or via the CLI? .js file (below) executed with node command in Jenkins
 3. Did you encounter this recently, or has this bug always been there: I'm new to the tool
 4. Expected behaviour: JUnit reporter creates .txt files also with the summary of the tests in order to integrate results into SonarQube
 5. Command / script used to run Newman:
var newman = require('newman'); // require newman in your project

`// call newman.run to pass `options` object and wait for callback
newman.run({
    collection: require('./Postman Echo.postman_collection.json'),
    reporters: 'junit'
}, function (err) {
    if (err) { throw err; }
    console.log('collection run complete!');
});` 

 6. Sample collection, and auxiliary files (minus the sensitive details): Postman Echo

If this feature will not be supported, then could you please suggest a solution?

**Comment by kunagpal** [comment]
@madalinaptj You can customize the file to which reports are written as follows:
```js
newman.run({
  collection: require('./Postman Echo.postman_collection.json'),
  reporters: 'junit',
  report: {
    junit: {
      export: 'YOUR CUSTOM TXT FILE PATH GOES HERE'
    }
  }
}, function (err) {
  if (err) { throw err; }
  console.log('collection run complete!');
});
```

**Comment by madalinaptj** [comment]
Hi @kunagpal,

I'm sorry, I realize I did not express myself clearly. 
I don't want to change the path of the export file, I need to have 2 files: 1 with the .xml JUnit log and the other in .txt format with just the summary of the results.

The .txt file would contain something like this:
-------------------------------------------------------------------------------
Test set: Postman Echo
-------------------------------------------------------------------------------
Tests run: 45, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 3.2 s - in Postman Echo

I tried the solution you mention above and it doesn't change anything for me. Maybe I am not using it correctly.

Please advise.

Thank you!
Madalina

**Comment by kunagpal** [comment]
@madalinaptj This can be done using https://www.npmjs.com/package/newman-reporter-text :)

**Comment by madalinaptj** [comment]
@kunagpal I used this text reporter but the result is a full log of the tests execution. What I need is just a summary report, so just 1 line in a .txt file that sums up how many tests were run successfully and how many passed.

I thought about maybe parsing myself the JUnit .xml file and determining this, but I am not yet sure how I would achieve that.

I thought you might consider adding this option to the JUnit reporter since it would be very useful for anyone trying to integrate with SonarQube or any similar plugin that needs a summary report of all tests, not just a log. 

For example, running JUnit tests in a Maven project with the Maven Surefire plugin does exactly this https://maven.apache.org/surefire/maven-surefire-plugin/

**Comment by kunagpal** [comment]
@madalinaptj This can be accomplished by using Newman programmatically, like so:
```js
const fs = require('fs'),
  newman = require('newman');

newman.run({ <regular options go here> }, function (err, summary) {
  if (err) { throw err; }

  const { total, pending, failed } = summary.run.stats.tests;
  fs.writeFileSync('report.txt', `Test set: ${summary.collection.info.name}\nTests run:${total}, Failures: ${failed}, Skipped: ${pending}`);
});
```

**Comment by madalinaptj** [comment]
@kunagpal This is great! Thank you so much for this! It's exactly what I was looking for.
The only change I made was to use ${summary.collection.name} because otherwise it throws an undefined error.

This is a very nice example of how to output simple files that might be needed for other plugins (like SonarQube) and how easy they can be achieved by using Newman programmaticall. Hope it will help others that are new to the tool like me! :)

Many thanks again for spending the time to help me! Really fast response, also. :)

**Comment by kunagpal** [comment]
@madalinaptj I see, there is a difference between tests and assertions. I understand that you were looking for the respective category counts of various assertion results. Feel free to let me know if you have any other questions 😄

**Comment by michaelajr** [comment]
A summary file in XML is need (maybe TXT would work too, IDK) for the FailSafe verify goal to work correctly. I start the app instrumented for JaCoCo in the pre-integration-test phase - run newman using the ant plugin - and then dump the report and stop the app - FailSafe needs to be bound to the verify phase so we know if tests failed. It does this by reading the summary report.
