### ISSUE TITLE
Can't set up multiple reporters

### ISSUE THREAD

**Issue by georgekucher** [postmanlabs/newman#1624]
1. Newman Version 3.10.0
 2. OS details Windows Server 2012R2
 3. Newman CLI
 3. Encountered recently
 4. Expected behavior:
Newman uses both reporters specified
 5. Command / script used to run Newman:
newman run Collections\$collectionName.json -e Environments\$environmentName.json --disable-unicode -r cli,teamcity
6. Actual behavior:
Newman uses ONLY FIRST reporter specified.

Issue wasn't present is 3.8.0.

**Comment by kunagpal** [comment]
@georgekucher I'm unable to reproduce this with Newman v3.10.0, for various combinations of both: inbuilt and external reporters. It should be noted that the TeamCity reporter provides CLI output. Using the CLI and teamcity reporters together will cause the output from both to be mixed. Needless to say, this is likely to confuse any TeamCity report parser.

For your specific use case, I got the following output with `--disable-unicode -r cli,teamcity`, I saw the following output (both for v3.10.0 as well as 3.8.0, with v0.1.11 of the teamcity reporter):
```terminal
newman

Sample Postman Collection
##teamcity[testSuiteStarted name='Sample Postman Collection' flowId='1531473508712.2136']

Root A simple GET request
##teamcity[testStarted name='A simple GET request' captureStandardOutput='true' flowId='1531473508712.2136']
  GET https://postman-echo.com/get?source=newman-sample-github-collection [200 OK, 580B, 1120ms]
  Pass  expect response be 200
  Pass  expect response json contain args
##teamcity[testFinished name='A simple GET request' duration='1120' flowId='1531473508712.2136']

Root A simple POST request
##teamcity[testStarted name='A simple POST request' captureStandardOutput='true' flowId='1531473508712.2136']
  POST https://postman-echo.com/post [200 OK, 613B, 256ms]
##teamcity[testFinished name='A simple POST request' duration='256' flowId='1531473508712.2136']

Root A simple POST request with JSON body
##teamcity[testStarted name='A simple POST request with JSON body' captureStandardOutput='true' flowId='1531473508712.2136']
  POST https://postman-echo.com/post [200 OK, 617B, 292ms]
##teamcity[testFinished name='A simple POST request with JSON body' duration='292' flowId='1531473508712.2136']

-------------------------------------------------
|                         | executed |   failed |
--------------------------+----------+-----------
|              iterations |        1 |        0 |
--------------------------+----------+-----------
|                requests |        3 |        0 |
--------------------------+----------+-----------
|            test-scripts |        1 |        0 |
--------------------------+----------+-----------
|      prerequest-scripts |        0 |        0 |
--------------------------+----------+-----------
|              assertions |        2 |        0 |
-------------------------------------------------
| total run duration: 1775ms                    |
-------------------------------------------------
| total data received: 927B (approx)            |
-------------------------------------------------
| average response time: 556ms                  |
-------------------------------------------------
##teamcity[testSuiteFinished name='Sample Postman Collection' flowId='1531473508712.2136']
```

The above is a mix of CLI and TeamCity outputs, but TeamCity details have not been lost, per se.

Additionally, there is an option for reporter authors to mark their reporters as dominant, as can be seen here: https://github.com/postmanlabs/newman/blob/develop/lib/reporters/cli/index.js#L366. I can see that this option has not been used within the TeamCity reporter.

**Comment by georgekucher** [comment]
I had a similar report on old CI server running Windows 7
By the way installing newman 3.8.0 (which is installed on old CI) on new CI (Win server) and trying to run tests with both reporters says "newman run: error: Unrecognized arguments: cli."
Magic?

**Comment by georgekucher** [comment]
```
##teamcity[testFinished name='Public Jobs/Get Auth Token Job More' duration='9' flowId='1531476768304.5103']
##teamcity[testStarted name='Public Jobs/Public Job List' captureStandardOutput='true' flowId='1531476768304.5103']
##teamcity[testFinished name='Public Jobs/Public Job List' duration='70' flowId='1531476768304.5103']
##teamcity[testStarted name='Public Jobs/Public Job Add' captureStandardOutput='true' flowId='1531476768304.5103']
##teamcity[testFinished name='Public Jobs/Public Job Add' duration='109' flowId='1531476768304.5103']
##teamcity[testStarted name='Public Jobs/Public Job Detail' captureStandardOutput='true' flowId='1531476768304.5103']
##teamcity[testFinished name='Public Jobs/Public Job Detail' duration='52' flowId='1531476768304.5103']
##teamcity[testStarted name='Public Jobs/Public Job Update' captureStandardOutput='true' flowId='1531476768304.5103']
##teamcity[testFinished name='Public Jobs/Public Job Update' duration='76' flowId='1531476768304.5103']
```
this is with teamcity only

**Comment by georgekucher** [comment]
May problem is in Windows Server2010R2

**Comment by kunagpal** [comment]
@georgekucher Ah, this could be a Windows-specific issue. As you can see from our Changelog here: https://github.com/postmanlabs/newman/blob/develop/CHANGELOG.yaml#L65, we had changed our underlying CLI parser library, which could have caused this behaviour. Could you enclose the `-r` arguments in quotes, like so: `-r "cli,teamcity"` and let me know if that works for you?

Thanks! 😄

**Comment by georgekucher** [comment]
yes it works))
thanks!!
