### ISSUE TITLE
Now a days, Newman stopping in-between the requests and started to run again if more than 100 requests.

### ISSUE THREAD

**Issue by SowmyaT** [postmanlabs/newman#1629]
Version and environment information:

 1. Newman Version (can be found via `newman -v`): **3.10.0**
 2. OS details (type, version, and architecture): **MacOS Sierra & osx**
 3. Are you using Newman as a library, or via the CLI? :  **LIBRARY**
 3. Did you encounter this recently, or has this bug always been there: **Recently**
 4. Expected behaviour: **It should be applicable for whole 3000 requests if i try to run. After that only it will be stopped. Earlier, it was perfectly worked done even 2000 requests**
 5. Command / script used to run Newman: **script**
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):
<img width="600" alt="screen shot 2018-07-16 at 12 05 46 pm" src="https://user-images.githubusercontent.com/17422722/42745703-cf72537e-88f1-11e8-9eb7-588bcd838239.png">

**Comment by SowmyaT** [comment]
@kunagpal Any update on this.

**Comment by kunagpal** [comment]
@SowmyaT Apologies for the delay. Please see my comment here: https://github.com/postmanlabs/newman/issues/1355#issuecomment-406868194 for additional context (and a possible resolution too!).
