### ISSUE TITLE
Single Collection : session cookies are not managed well : Can not have two requests with and without auth

### ISSUE THREAD

**Issue by musanas** [postmanlabs/newman#1635]
Hey,
Assume I have a single collection.
In this collection I have two requests, both hitting on the same api end point.
I have configured my first request with a basic authentication.
I have configured my second request with no authentication
I add various tests for these two checking both happy paths and not so happy paths. All these are done in postman GUI.

Now I am running this collection in Newman
I would expect my second request gets hit with out any authentication
But seems like its picking up the session from the the first request cookies, and eventually being send with authentication, this will make all my tests fails
and I can not have single collection witt these types of requests.

I understand we have request to delete cookies etc 
https://github.com/postmanlabs/postman-app-support/issues/3312
But I guess, my usecase should work as am expecting here .
 i can find workaround if i reverse the order of requests in the collection, like request with out auth first then the other one, **but that will work only if the collection is being hit only once
If the collecton is configured to run multiple times in Newman with -n tag, it will eventually take up cookies from previ request and tests will fail**.

Newman verson: 3.9.4
Postman version : 6.1.4

Thanks
Musaffir

**Comment by GrogyLbn** [comment]
Hello,

I have the same issue.
I make a first request to a login api to get my session id cookie.
When i do my seconde request my session cookie is not use and have a 401.

Regard's
Grégory

**Comment by sedge** [comment]
I'm experiencing something similar and it's really frustrating 😭

Considering this is fundamentally different behaviour from the GUI it makes me wonder what else is different in the two environments. Is this documented somewhere?

**Comment by codenirvana** [comment]
You can now programmatically manipulate cookies before sending the request...
Refer to https://github.com/postmanlabs/postman-app-support/issues/3312#issuecomment-516965288 for more details.
