### ISSUE TITLE
Newman can't read variable from enviroment

### ISSUE THREAD

**Issue by civonavets** [postmanlabs/newman#1638]
1. Newman Version (can be found via `newman -v`): 3.10.0
 2. OS details (type, version, and architecture): Win 10 Home x64 v1803 ( Build 17134.165 )
 3. Are you using Newman as a library, or via the CLI?: CLI
 3. Did you encounter this recently, or has this bug always been there: Recently
 4. Expected behaviour: Since it executes in Postman, it should execute in Newman as well
 5. Command / script used to run Newman: npm run switch (using custom reporter from https://www.getpostman.com/docs/v6/postman/collection_runs/command_line_integration_with_newman )
 6. Sample collection, and auxiliary files (minus the sensitive details): https://stackoverflow.com/questions/51502489/postman-script-executes-flawlessly-in-postman-failed-in-newman?noredirect=1#comment89974636_51502489
 7. Screenshots (if applicable):
![postman](https://user-images.githubusercontent.com/28680216/43211781-4281b44c-902a-11e8-8a98-ba13b2671c71.png)
![postman_isolated_1](https://user-images.githubusercontent.com/28680216/43211790-4762f494-902a-11e8-9f4d-0e6a99e7993d.png)
![newmanrun](https://user-images.githubusercontent.com/28680216/43211796-4c21b25e-902a-11e8-8d01-0a4bb0be897f.png)

Tried to do something like(there could be some semantics error in there, not the point):
![other way](https://user-images.githubusercontent.com/28680216/43211966-bfa2d4e2-902a-11e8-9c2d-aec111582e81.png)
Still not working in Newman. Everything stated runs in postman flawlessly. Is this a bug or im i missing something?

**Comment by civonavets** [comment]
Steps to reproduce the problem: (since it wasn't included in the bug itself)

1. Download http://s000.tinyupload.com/index.php?file_id=01550279211467632549
2. npm install - for dependencies
3. npm run switch - to run it

**Comment by codenirvana** [comment]
@civonavets I see you're using `pm.environment.get("switch");` in the test script but in `newman.run` options `globals` is set not `environment`.

You need to update the options in `switch.js` to:
```javascript
{
   collection: require('../rules splitted/switch.json'),
   environment: require('../alch_env_dev.json'),  // Postman Environment Variables
   reporters: 'cli',
   bail: false
}
```

In case you want to use Global Variables, use `pm.globals.get`.  Also, you can check our [guide on Variables](https://www.getpostman.com/docs/v6/postman/environments_and_globals/variables) to know more.

**Comment by civonavets** [comment]
@codenirvana You are absolutely right. Despite the fact that I double checked everything, I don't know how I missed the global part.

**Comment by arun290636** [comment]
@codenirvana  I am facing the similar problem. Can you please help here - https://github.com/postmanlabs/newman/issues/1975
