### ISSUE TITLE
Execute sync for collections

### ISSUE THREAD

**Issue by gadelkareem** [postmanlabs/newman#166]
I think a sync version of execute is important in case we need to test a collection of json files. Is that already there?
Currently I am modifying the delay option in this ex:
```
glob("collections/*.json", null, function (er, files) {
  files.forEach(function (file) {
    console.log(file);
    // read the collectionjson file
    var collectionJson = JSON5.parse(fs.readFileSync(file, 'utf8'));
    newmanOptions.delay += 1000;
    Newman.execute(collectionJson, newmanOptions);
  });
});
```

**Comment by czardoz** [comment]
@gadelkareem You can optionally give a callback to newman, which should help:

``Newman.execute(collectionJson, newmanOptions, callback);``

**Comment by gadelkareem** [comment]
Thanks @czardoz, what are the parameters for the callback. Can you give an example for looping through the collection files?

**Comment by shamasis** [comment]
Synchronous execution of collections will not be feasible. The amount of anti-pattern it brings to current NodeJS and collection run paradigm that it would end up being equivalent to developing Newman twice over!

Closing this issue.
