### ISSUE TITLE
I have developed a postman collection. exported as json and runing from jenkins with batch command as.... "newman -c CollectionName.json -O output.json – H Reports.html". Binary getting populated in jenkins screen.

### ISSUE THREAD

**Issue by 121arijit** [postmanlabs/newman#1674]
I have developed a postman collection. exported as json and runing from jenkins with batch command as.... "newman -c CollectionName.json -O output.json – H Reports.html". Binary getting populated in jenkins screen....  
Example... (copied from jenkins console)[90mâ”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€[39m[90mâ”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€[39m[90mâ”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”�[39m [90mâ”‚[39m [90mâ”‚[39m executed [90mâ”‚[39m failed [90mâ”‚[39m [90mâ”œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€[39m[90mâ”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€[39m[90mâ”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤[39m [90mâ”‚[39m [32miterations[39m [90mâ”‚[39m 1 [90mâ”‚[39m 0 [90mâ”‚[39m [90mâ”œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€[39m[90mâ”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€[39m[90mâ”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤[39m

**Comment by kunagpal** [comment]
@121arijit Please upgrade to the latest version of Newman and use the following command:
```console
npm install --global newman-reporter-html
newman run CollectionName.json -r json,html --reporter-json-export output.json –-reporter-html-export Reports.html --disable-unicode --color off
```

**Comment by 121arijit** [comment]
Hi Kunagpal,
Thanks for your support, I have tested above command and below error is showing in jenkins console.

the file at Reports.html does not contain valid JSON data
Unexpected token < in JSON at position 0 while parsing near '<!DOCTYPE html><htm...'
Build step 'Execute Windows batch command' marked build as failure
Finished: FAILURE

**Comment by 121arijit** [comment]
Thanks , it is working fine now
