### ISSUE TITLE
Newman unexpectedly returning multiple times

### ISSUE THREAD

**Issue by anthonyherron** [postmanlabs/newman#168]
I'm running Newman inside of a node application. If I call Newman twice in the same app, it returns say 4 times for some reason. I'm wondering if this is expect and if this can be avoided somehow? As an example I've taken the sample code provided in the readme and creating something simple to show the issue. I would expect to call Newman and for it to asynchronously callback correctly and the correct number of times. Is this at all possible?

In this example I have 2 collections. One checking the BBC website, the other Github. Both have 1 test which is testing that the HTTP response code is 200.

#### app.js
```javascript
var fs = require('fs');
var JSON5 = require('JSON5');
var Newman = require('newman');

// read the collectionjson file
var collectionJson = JSON5.parse(fs.readFileSync("./collection.json", 'utf8'));
var collectionJson2 = JSON5.parse(fs.readFileSync("./collection2.json", 'utf8'));

// define Newman options
newmanOptions = {
    iterationCount: 1,                    // define the number of times the runner should run
    outputFile: "outfile.json",            // the file to export to
    asLibrary: true,                        // this makes sure the exit code is returned as an argument to the callback function
    stopOnError: true
}

// Optional Callback function which will be executed once Newman is done executing all its tasks.
Newman.execute(collectionJson, newmanOptions, function(exitCode) {
	console.log('1st callback: Newman finished with exit code: ' + exitCode);
});

Newman.execute(collectionJson2, newmanOptions, function(exitCode) {
	console.log('2nd callback: Newman finished with exit code: ' + exitCode);
});
```

The above code returns with the following console logs:

``` bash
Iteration 1 of 1

Iteration 1 of 1
200 140ms BBC website 200 response check http://www.bbc.co.uk
200 140ms BBC website 200 response check http://www.bbc.co.uk


Output Log: /Users/anthony/Desktop/simple_newman_test/outfile.json
1st callback: Newman finished with exit code: 0
2nd callback: Newman finished with exit code: 0


Output Log: /Users/anthony/Desktop/simple_newman_test/outfile.json
1st callback: Newman finished with exit code: 0
2nd callback: Newman finished with exit code: 0


Output Log: /Users/anthony/Desktop/simple_newman_test/outfile.json
1st callback: Newman finished with exit code: 0
2nd callback: Newman finished with exit code: 0


Output Log: /Users/anthony/Desktop/simple_newman_test/outfile.json
1st callback: Newman finished with exit code: 0
2nd callback: Newman finished with exit code: 0
200 572ms Github website 200 response check https://github.com
```
Thank you for your time.

**Comment by neillboyd** [comment]
+1 on looking for a fix for this :-) At the moment I have to run multiple newman tasks in different .js files and daisy chain them.

@uxtracer - did you find that clearing the cache worked? I tried to do the same but couldn't get it working...

**Comment by idlem1nd** [comment]
+1 on looking for a fix for this. When running trying to queue up multiple newman tasks I get the same issue (I'm using queue-async, but even with a concurrency of 1 it doesn't work). I couldn't get the cache clearing from @uxtracer to work either.

**Comment by sbutalia** [comment]
Adding this code after execute is complete helped in my case ...

Under Newman.js -> execute -> if (typeof callback === "function")
```
line 80:                this.removeAllListeners();
```

**Comment by gadelkareem** [comment]
@sbutalia solution fixed it for me. I hope this can be added to newman@1

**Comment by abhijitkane** [comment]
@czardoz

**Comment by shamasis** [comment]
This is being addressed in upcoming newman v3.x. In fact it is already fixed there. Try it out if possible - https://github.com/postmanlabs/newman/tree/feature/v3

**Comment by shamasis** [comment]
This has been addressed in newman v3

```
newman.run(options, callback); // calls callback only once
```
