### ISSUE TITLE
Journal not posting even with status 200 OK

### ISSUE THREAD

**Issue by noibfromgloib** [postmanlabs/newman#1685]
1. Newman Version (can be found via `newman -v`):3.10.0
 2. OS details (type, version, and architecture): Windows 10 x64
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: I haven't ever had it work
 4. Expected behaviour: That the journal posts through CLI and GUI
 5. Command / script used to run Newman: newman run "json to run path" -e "[json environment path"

I run the json file in the CLI and I get a status of 200 OK however the journal does not show up in intacct:
![image](https://user-images.githubusercontent.com/42596363/44441134-58474080-a588-11e8-8b4e-37ce6da560eb.png)

I run the same json file in the GUI, I get a status of 200 OK and the journal is in intacct.

Before adding the -e environment path file, I was getting status 401, but the -e cleared that up. Why would the journal post fine through the GUI but not the CLI?

**Comment by shamasis** [comment]
That shouldn’t happen. It should go through the GUI as well as the CLI.

Now, to debug this, we need to know more. First, I don’t know what API we are talking about here? If it is a well known public API, can you share more details that are not sensitive?
