### ISSUE TITLE
Command java script substr not working in Newman but working Postman

### ISSUE THREAD

**Issue by Guilherme-Sensedia** [postmanlabs/newman#1689]
Command java script SUBSTR not working in Newman but working Postman.

**Comment by kunagpal** [comment]
@Guilherme-Sensedia Could you share the Node version you're on? I wasn't able to reproduce this with Newman v4 and Node v8.x

**Comment by Guilherme-Sensedia** [comment]
@kunagpal node version: v10.8.0

**Comment by Guilherme-Sensedia** [comment]
@kunagpal I'm go update node version for more tests

**Comment by Guilherme-Sensedia** [comment]
@kunagpal I'm use node version v8.11.4 and newman version 4.0.2, but not working command substr javascript.

![captura de tela de 2018-08-24 11-08-27](https://user-images.githubusercontent.com/40179240/44589165-2e5f6b00-a78e-11e8-8fbc-c99a1891f350.png)

**Comment by codenirvana** [comment]
@Guilherme-Sensedia Are you using `substr` in your test script?
As you mentioned its working in the App, can you share your test script(minus sensitive data)?

Also, share the command used to execute the Newman run, because if you are using the environment variables in App you need to pass the same in Newman as well.

**Comment by Guilherme-Sensedia** [comment]
I use substr in test script.

Command used:

var jsonData = JSON.parse(responseBody);

var mensagem_email = jsonData.snippet;

mensagem_email = unescape(mensagem_email);

mensagem_email = mensagem_email.substr(72, 6);  

console.log("test: " + mensagem_email);

postman.setEnvironmentVariable("senha_email", mensagem_email);

pm.test("Status code is 200 e a senha: " + mensagem_email, function () {
    pm.response.to.have.status(200);
});

**Comment by codenirvana** [comment]
@Guilherme-Sensedia The test script looks fine to me.
That error is possible only if `mensagem_email` is set to `undefined`, Can you debug on `responseBody` to verify response is sent correctly?

**Comment by Guilherme-Sensedia** [comment]
Command substr working in newman, my mistake.

@codenirvana you know url for redirects in newman, i use in postman:
https://www.getpostman.com/oauth2/callback

But not working in newman.

**Comment by codenirvana** [comment]
@Guilherme-Sensedia Can you create a separate issue for this with detailed description and steps to reproduce.
