### ISSUE TITLE
Multiple newman runs in Jenkins job - report issue

### ISSUE THREAD

**Issue by Sephirioth** [postmanlabs/newman#1690]
Hello,

I have some innue running my tests on Jenkins.
I've manage to make it doing single rest like that:
SVN report is triggering Jenkins job and in Building I'm doing newman run etc...
After that I'm pushing report.html in e-mail with job status. It works ok but...

I need now to trigger primary test package and generate report from it and then, depending on svn commit comment (I'm grabbing from it number of API to be tested inside $comment) I need to run second package for specific API.

Right now I was trying to resolve this like that:
Two newman run in Jekins job (two separate Execute shell script's)  - it works if assertions are ok, but when any assertion fails in first newman run, the second newman run with second test package isn't starting.  

Another idea was to make job run always as Success. Newman runs are ok and reports from them also. But I'm receiving email labeled as success even if one of test paskages fails.

How shoul I do it properly or hw to make it run for me?
Is there any possibility to gram from newman info about test run fails or not and pass it to Jenkins  and then determine if run is sucess or fail? If it is possible I'll be able to force newman runs and build reports and after that pass the status for Job to be success if every test run is ok, and fail if any of them is failed.

**Comment by cbarrerah** [comment]
Hi,

Maybe you can set the -x option on the newman run, and parse the resulting junit results for each newman run on the jenkinsfile, and depending on the presence of failures in them, trigger a boolean that gives the global PASS/FAIL status of the whole Job.

If you don't pass the -x parameter to the newman execution, any newman run that fails will stop the whole pipeline and mark it as failure.

If you find another way, let me know :)

**Comment by aberx1** [comment]
Hi,
Jenkins executes by building block.
To have it continue you could place both newman run commands in the same shell script.
Another option is to place it in different pipelines and trigger them from the main pipeline while saying that it can continue and does not have to wait for the result.

**Comment by codenirvana** [comment]
Closing since this issue is not related to Newman and a workaround https://github.com/postmanlabs/newman/issues/1690#issuecomment-463505351 exist.
