### ISSUE TITLE
Newman docker jenkins pipeline collections issue

### ISSUE THREAD

**Issue by kieronlangdon** [postmanlabs/newman#1692]
Hi,
Im seeing an issue as part of the jenkins pipeline which uses the newman_ubuntu1404 docker image
1 out of 10 times it will find the collection in the workspace
The code is housed in github and pulled from artifactory 
This is my step in the larger jenkins file:
```
stage('Automation') {
    node('ts-build') {
      def collectionName = 'collections/something.postman_collection.json'
      docker.image('postman/newman_ubuntu1404').inside("--entrypoint=''"){
        sh "newman run '$collectionName'"
     }
  }
}
```
Example error seen:
[projectbuildname_master-FOSPOKGVSAWFE7SOECOW3VH7STOR2NG44KPBCXIO4PUTQPHZI5DA] Running shell script
+ newman run collections/something.postman_collection.json

  error: ENOENT: no such file or directory, open 'collections/something.postman_collection.json'

Any help on this would be appreciated!

**Comment by kunagpal** [comment]
@kieronlangdon Apologies for the delayed response, could you update the `sh` section in your build block to include an `ls -la;` before the `newman run ...` command and share the results?

**Comment by kieronlangdon** [comment]
Sorry for the late reply,
Got it sorted, needed a 
sh "cd ../" to find the dir in the workspace
So
```
stage('Automation') {
node('ts-build') {
      def collectionName = 'collections/something.postman_collection.json'
      docker.image('postman/newman_ubuntu1404').inside("--entrypoint=''"){
       sh "cd ../"        
       sh "newman run '$collectionName'"
     }
  }
}
```
Hopefully this is useful to others!
Please close this
