### ISSUE TITLE
Scripts run in Postman but throws error in Newman

### ISSUE THREAD

**Issue by debjchak** [postmanlabs/newman#1695]
1. Newman Version:4.0.2,Postman Version:6.2.5
 2. OS details (type, version, and architecture): Windows 7,64 bit production Imagev1.16.00.AO.B19
 3. Newman via the CLI
 3. Did you encounter this recently, or has this bug always been there: Recently started using
 4. Expected behaviour: Scripts run through Postman passed and Newman should also have passed
 5. Command / script used to run Newman: "newman run Collection1"
 6. Sample collection, and auxiliary files (minus the sensitive details): https://www.getpostman.com/collections/e20dc7daa589e7dd2a22
Screen shot:
![image](https://user-images.githubusercontent.com/42804200/44786021-690f3c00-abb0-11e8-8adb-069c1914d9ee.png)

Steps to reproduce the problem:

1. Have written scripts in Postman 
2. Generated link for the collection
3. Ran command newman run https://www.getpostman.com/collections/e20dc7daa589e7dd2a22
4.Throws error in newman(unexpected token u in json in position0,self signed certificate) but these errors do not appear in postman
5.Another issue is if i use a global variable in the postman endpoint,newman doesn't detect it and throws another error saying Invalid url"

**Comment by codenirvana** [comment]
@debjchak you can disable SSL verification check and allow self-signed SSL certificate by using `--insecure` flag.

- `JSONError` is because of `pm.response.json()`  in test script tries to JSON parse response body but the request is failed because of SSL verification first.

- To use `global variables` you need to specify them like `--global-var "url=http://localhost"`.

Check all the available Newman options [here](https://github.com/postmanlabs/newman#newman-run-collection-file-source-options).

**Comment by debjchak** [comment]
Hi Udit,

Since I am completely new to Postman and Newman, I really do not know how 
to execute the solutions you provided.Could you please elaborate a bit to 
explain how to I run the command to allow self signed SSL certificate by 
using the insecure flag?
Also, i need to know how to use --global-var "url=http://localhost"?Should 
I just type this in before running my collection in Command Prompt ?




Thanks & Regards,

DEBJANI CHAKRABORTY
IBM Test and Defect Management team-BAT
IBM Client Innovation Center - India


Phone: +91 33 71088911 | Mobile: +91 9830432288
E-mail: debjchak@in.ibm.com


DLF SEZ,Plot:11F/1 Action Area-II,Blc:1C
Rajarhat, Kolkata 700156
West Bengal Ind

**Comment by codenirvana** [comment]
@debjchak you can use the above mentioned options like this:
```
newman run https://www.getpostman.com/collections/e20dc7daa589e7dd2a22 --insecure --global-var "url=http://localhost"
```

You can know more  about using Postman and Newman from the following documentations:
- [Postman Documentation](https://www.getpostman.com/docs/)
- [Newman Documentation](https://github.com/postmanlabs/newman/blob/develop/README.md)

**Comment by debjchak** [comment]
Hi Udit,

Thanks for your quick response. The issue I am facing now is with global 
variables. Everything works as expected if I do not use Global variables 
in my url. but the moment I use them, i get the following error. Please 
suggest.






Thanks & Regards,

DEBJANI CHAKRABORTY
IBM Test and Defect Management team-BAT
IBM Client Innovation Center - India


Phone: +91 33 71088911 | Mobile: +91 9830432288
E-mail: debjchak@in.ibm.com


DLF SEZ,Plot:11F/1 Action Area-II,Blc:1C
Rajarhat, Kolkata 700156
West Bengal Ind

**Comment by codenirvana** [comment]
@debjchak Can you specify the error and Newman command used?

**Comment by debjchak** [comment]
Hi,
The errors I receive are 
1. "connect ECONNREFUSED 127.0.0.1:80"
2.Unexpected token u in JSON at position 0 at assertion :0 in test script

**Comment by codenirvana** [comment]
@debjchak I see that you updated the request URL to `{{url}}/applyUPUI`.
Now using `--global-var "<global-variable-name>=<global-variable-value>"` option, you can replace the **{{url}}**(*global-variable-name*) with the required requesl URL(*global-variable-value*).

The above error is because you used `--global-var "url=http://localhost"` directly from my previous example, here you need to change `http://localhost` with your request URL `https://10.144.3....` (as seen in the screenshot above).

**Comment by debjchak** [comment]
Below is my command for which I still receive error stating "Invalid URI".
newman run https://www.getpostman.com/collections/e20dc7daa589e7dd2a22 --insecure --global-var "<url>=<https://10.144.31.156/apic-dev/sb/primaryrepository/api/productmovements>"

**Comment by codenirvana** [comment]
@debjchak You are missing **global-variable-name** i.e `url` in you case. It should be:
```
newman run https://www.getpostman.com/collections/e20dc7daa589e7dd2a22 --insecure --global-var "url=https://10.144.31.156/apic-dev/sb/primaryrepository/api/productmovements"
```

**Comment by debjchak** [comment]
The Global variable name got hidden some how. Rectified now.All work as expected. Thank you so much for the quick responses and resolution.

**Comment by Riya1823** [comment]
![image](https://user-images.githubusercontent.com/46278421/70312611-fcb2cc00-1839-11ea-8668-24eca28b50bf.png)

Newman version 4.5.6
Postman-win64-7.10.0
node version 6.10.0
Created Collection
AuthLogin - Pre-request Script with json stored in variable and set the variable in environment to use it in body, wrote two test test in test.

Then exported collection v2.1 and saved this file as postman collection
![image](https://user-images.githubusercontent.com/46278421/70312917-8fec0180-183a-11ea-805a-be7a366f36cb.png)
and also saved environment variables
and ran newman on cmd - newman run AutomationScript.postman_collection -e STG.postman_environment.json
