### ISSUE TITLE
Newman version mismatch after upgrading to v4

### ISSUE THREAD

**Issue by AisoRed** [postmanlabs/newman#1697]
**Version and environment information:**
 1. Newman Version (can be found via `newman -v`):  **3.10.0 or 4.1.0**
 2. OS details (type, version, and architecture):  Windows 7 64-bit
 3. Are you using Newman as a library, or via the CLI?  CLI
 3. Did you encounter this recently, or has this bug always been there:  Just tried to update.
 4. Expected behaviour:  I expect to be on version 4.1.0.
 5. Command / script used to run Newman:  N/A
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/1385257/44811234-b7651080-ab99-11e8-91c5-649a35c0c658.png)

I ran the suggested update line: `npm update -g newman`
After the update completed, I ran the two version checks:
`npm show newman version`
`newman --version`

These checks reported different version numbers. (4.1.0 and 3.10.0, respectively)

Running `npm update -g newman` again does nothing.

**Comment by kunagpal** [comment]
@AisoRed This could be happening due to an issue with your version of `npm`. Could you try `npm i -g newman` and confirm that the latest version installs correctly?

**Comment by AisoRed** [comment]
This worked for me. Thank you!

My `npm` was on version `5.6.0` when I first tried this.

**Comment by kunagpal** [comment]
@AisoRed Thanks for sharing that, npm v5.6.0 is known to have more than it's fare share of quirky bugs. :sweat_smile:
