### ISSUE TITLE
New man unable to locate teamcity reporter

### ISSUE THREAD

**Issue by kthulsidoss** [postmanlabs/newman#1702]
Hi I installed team city reporter at 
C:\Users\Administrator>npm install -g newman-reporter-teamcity
+ newman-reporter-teamcity@0.1.11
updated 1 package in 2.484s

┌────────────────────────────────────────────────────────────────────┐
│                      npm update check failed                       │
│                Try running with sudo or get access                 │
│                to the local update config store via                │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\Administrator\.config │
└────────────────────────────────────────────────────────────────────┘
How ever i get the following error when i run it via jenkins

Started by user unknown or anonymous
[EnvInject] - Loading node environment variables.
Building in workspace C:\JenkinsMFD\workspace\MDS_R9_GETMetaMarketDataUsedByISIN_POSTMAN_Test
 > C:\Git\bin\git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > C:\Git\bin\git config remote.origin.url git@algogit.canlab.ibm.com:CM/mds.git # timeout=10
Fetching upstream changes from git@algogit.canlab.ibm.com:CM/mds.git
 > C:\Git\bin\git --version # timeout=10
using GIT_SSH to set credentials ssh key
 > C:\Git\bin\git fetch --tags --progress git@algogit.canlab.ibm.com:CM/mds.git +refs/heads/*:refs/remotes/origin/*
 > C:\Git\bin\git rev-parse "refs/remotes/origin/R9-Master^{commit}" # timeout=10
 > C:\Git\bin\git rev-parse "refs/remotes/origin/origin/R9-Master^{commit}" # timeout=10
Checking out Revision 439384b5d0eede35fdc9a08195877bd5f02b75b8 (refs/remotes/origin/R9-Master)
 > C:\Git\bin\git config core.sparsecheckout # timeout=10
 > C:\Git\bin\git checkout -f 439384b5d0eede35fdc9a08195877bd5f02b75b8
Commit message: "Merge remote-tracking branch 'origin/R9-Master' into R9-74909-74875"
 > C:\Git\bin\git rev-list --no-walk 439384b5d0eede35fdc9a08195877bd5f02b75b8 # timeout=10
Copied 4 artifacts from "MDS_R9_Gradle_Build_All" build number 5
[MDS_R9_GETMetaMarketDataUsedByISIN_POSTMAN_Test] $ powershell.exe -NonInteractive -ExecutionPolicy ByPass "& 'C:\Windows\TEMP\jenkins4154847198781943227.ps1'"
The hostname of this machine is env:WORKSPACE\util\testing\FunctionalTests\PostManFiles
The Json file is GETMetaMarketDataUsedByISIN.postman_collection.json
The environment file is C:\JenkinsMFD\workspace\MDS_R9_GETMetaMarketDataUsedByISIN_POSTMAN_Test\util\testing\FunctionalTests\PostManFiles\MFD_R9.postman_environment.json
The data  file is C:\JenkinsMFD\workspace\MDS_R9_GETMetaMarketDataUsedByISIN_POSTMAN_Test\util\testing\FunctionalTests\PostManFiles\SecuritiesMapper_Test_IDs_20180328_ISIN_Meta_Combined.csv
newman: "teamcity" reporter could not be loaded.
  run `npm install newman-reporter-teamcity`

C:\Users\Administrator>

**Comment by kunagpal** [comment]
@kthulsidoss Could you also share the exact command/script used to run Newman? Also, could you share the result of `where newman` and `npm config get prefix`? Thanks!

**Comment by kthulsidoss** [comment]
Hi thank you for the quick response -appreciate it , please kindly add to doc the following 👍 
this needs to be added 👍 
•One tricky thing is to get Jenkins to recognize npm commands. To do this, I had to copy the NPM packages to a location that Jenkins can have access to. That is why I change to the directory to C:\npm\node_modules\newman\bin with the CD command
e.g 👍 copy from C:\Users\Administrator\AppData\Roaming\npm to C:\npm * so that jenkins can access these installs .. this is a very good point 

now it works 

one more thing where to see the report ? i have jenkins 
e.g ##teamcity[testSuiteStarted name='GETMetaMarketDataUsedByISIN' flowId='1536142202929.8062']
##teamcity[testStarted name='GET Meta marketData Used BY ISIN' captureStandardOutput='true' flowId='1536142202929.8062']
##teamcity[testFinished name='GET Meta marketData Used BY ISIN' duration='5969' flowId='1536142202929.8062']
##teamcity[testStarted name='GET Meta marketData Used BY ISIN' captureStandardOutput='true' flowId='1536142202929.8062']
##teamcity[testFinished name='GET Meta marketData Used BY ISIN' duration='3828' flowId='1536142202929.8062']
##teamcity[testStarted name='GET Meta marketData Used BY ISIN' captureStandardOutput='true' flowId='1536142202929.8062']
##teamcity[testFinished name='GET Meta marketData Used BY ISIN' duration='2891' flowId='1536142202929.8062']
##teamcity[testStarted name='GET Meta marketData Used BY ISIN' captureStandardOutput='true' flowId='1536142202929.8062']
##teamcity[testFinished name='GET Meta marketData Used BY ISIN' duration='3015' flowId='1536142202929.8062']
##teamcity[testStarted name='GET Meta marketData Used BY ISIN' captureStandardOutput='true' flowId='1536142202929.8062']
##teamcity[testFinished name='GET Meta marketData Used BY ISIN' duration='2937' flowId='1536142202929.8062']
##teamcity[testStarted name='GET Meta marketData Used BY ISIN' captureStandardOutput='true' flowId='1536142202929.8062']
##teamcity[testFinished name='GET Meta marketData Used BY ISIN' duration='3375' flowId='1536142202929.8062']
##teamcity[testSuiteFinished name='GETMetaMarketDataUsedByISIN' flowId='1536142202929.8062']
Finished: SUCCESS

**Comment by kunagpal** [comment]
@kthulsidoss Glad it worked out for you, we'll add some more docs around usage in Jenkins :)
