### ISSUE TITLE
Wrong SSL Version

### ISSUE THREAD

**Issue by xell66** [postmanlabs/newman#1703]
1. Version 4.1.0
 2. Ubuntu 16.04.1 LTS 
 3. CLI use
 3. Did you encounter this recently, or has this bug always been there: -
 4. Expected behaviour: get response
 5. Comand: 'newman run collection.json --ssl-client-cert client.cer --ssl-client-key keyfile.key'
 

Hi there,
I have a Problem with Newman and I am not sure if its a Bug. First thing, this works on the same machine with the Postman application and the same URLs and certificates. I need to check if a connection is allowed with specific authetication certificates and want to automate this tests with newman. --insecure doesn't help and dont change the error. Has anyone an Idea? Thanks!

Comand in cli: 'newman run collection.json --ssl-client-cert client.cer --ssl-client-key keyfile.key'

LOGFILE:

→ Case1 
  GET https://XXXXX [errored]
     tunneling socket could not be established, cause=write EPROTO 140000783112000:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:

→ Case2
  GET https://XXXXX [errored]
     tunneling socket could not be established, cause=write EPROTO 140000783112000:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:

→ Case3
  GET https://XXXXXX [errored]
     tunneling socket could not be established, cause=write EPROTO 140000783112000:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:

→ Case4
  GET https://XXXXXX [errored]
     tunneling socket could not be established, cause=write EPROTO 140000783112000:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:

**Comment by kunagpal** [comment]
@xell66 
> tunneling socket could not be established, cause=write EPROTO 

This commonly occurs when you're using a proxy, but there's an attempt to send an HTTPS request via an HTTP proxy. Could you confirm that the `HTTPS_PROXY` environment variable is set correctly?

Similar to: https://github.com/postmanlabs/newman/issues/235

A detailed explanation can be found here:
1. https://github.com/nodejs/node-v0.x-archive/issues/6779
2. https://github.com/nodejs/node/issues/3692

**Comment by xell66** [comment]
Thanks for the advice. The Problem was that I used https_proxy and not HTTPS_PROXY.

**Comment by kunagpal** [comment]
@xell66 That's odd, the variable should work regardless of case 🤔

**Comment by shamasis** [comment]
Marking this as solved for now. Will revisit case issue during future chores.

**Comment by mukeshsinghbhakuni590** [comment]
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/react-calendar failed, reason: write EPROTO 140381526140736:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mukesh/.npm/_logs/2019-03-13T20_06_18_691Z-debug.log




-----------------------------------------------------------------------------------------------------------------------
got the above error while installing react-router-dom or any other package with npm
npm version : 6.7.0
nodejs version : 4.2.6

**Comment by shamasis** [comment]
@mukeshsinghbhakuni590 - not sure how that relates to this issue. What am I missing?

**Comment by mukeshsinghbhakuni590** [comment]
> @mukeshsinghbhakuni590 - not sure how that relates to this issue. What am I missing?

I m not relating it i m asking the solution to this issue.
Thanks.

**Comment by shamasis** [comment]
@mukeshsinghbhakuni590 Ok. The issue you’re posting seems to me like an npm issue and not anything related to Newman. Can you try running `npm set strict-ssl false` before `npm install`? If that doesn’t work, you should create a new issue on the correct project.
