### ISSUE TITLE
newman 4.1.0 doesn't execute test scripts and assertions

### ISSUE THREAD

**Issue by m3dbedb** [postmanlabs/newman#1706]
1. Newman Version: 4.1.0
 2. OS details: windows 7 32
 3. Are you using Newman as a library, or via the CLI? Newman is used via CLI
 3. Did you encounter this recently, or has this bug always been there: This is my first exercise with newman, I didn't try older versions
 4. Expected behaviour: old-style test scripts to be executed (the scripts work sucsessfully with runner 6.x for windows) according to newman documentation (it is stated to support all libraries, etc. supported by postman app). The result should contain script execution information.
 5. Command / script used to run Newman: **newman run postman_collection3082018.json -e environment05092018.json** (version 2.0 made with postman for chrome 5.5.3)
 6. Sample collection, and auxiliary files (minus the sensitive details): applied
 7. Screenshot:

--------------------------T----------T----------¬
¦                         ¦ executed ¦   failed ¦
+-------------------------+----------+----------+
¦              iterations ¦        1 ¦        0 ¦
+-------------------------+----------+----------+
¦                requests ¦       11 ¦        0 ¦
+-------------------------+----------+----------+
¦            test-scripts ¦        0 ¦        0 ¦
+-------------------------+----------+----------+
¦      prerequest-scripts ¦        0 ¦        0 ¦
+-------------------------+----------+----------+
¦              assertions ¦        0 ¦        0 ¦
+-------------------------+----------+----------+
¦ total run duration: 448ms                     ¦
+-----------------------------------------------+
¦ total data received: 8.16KB (approx)          ¦
+-----------------------------------------------+
¦ average response time: 17ms                   ¦
L------------------------------------------------
Steps to reproduce the problem:

1. run newman command listed above

[environment05092018.zip](https://github.com/postmanlabs/newman/files/2355804/environment05092018.zip)

**Comment by codenirvana** [comment]
@m3dbedb I am not able to reproduce this issue, tried with the same collection and environment as well.

Can you try to reinstall Newman and check if the issue persists?

**Comment by m3dbedb** [comment]
Sure, but I can't uninstall it:
>**npm uninstall newman**
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\user\pac
kage.json'
>**npm init**
C:\Users\user>**npm uninstall newman**
up to date in 0.098s
C:\Users\user>**npm install newman**

> npm ERR! code ENOSELF
> npm ERR! Refusing to install package with name "newman" under a package
> npm ERR! also called "newman". Did you name your project the same
> npm ERR! as the dependency you're installing?

**Comment by codenirvana** [comment]
@m3dbedb Looks like Newman is installed globally. To uninstall run:
```console
$ npm uninstall -g newman
```

and re-install using:
```console
$ npm install -g newman
```

**Comment by m3dbedb** [comment]
After reinstallation test scripts appeared in newman test run details table, but newman didn't use environment variables and didn't execute test scripts as I stated in my first message. If I open the same collection and environment in postman app, everything works good.

newmal run output with my comments begining with `***` applied
[newmanlog.txt](https://github.com/postmanlabs/newman/files/2365483/newmanlog.txt)

**Comment by codenirvana** [comment]
@m3dbedb From the logs shared I can see you are missing the `-e` option to specify an environment file path.
```console
$ newman run test_collection05092018.json -e environment05092018.json
```

Also, note that your environment variable `url` is ending with a leading `/` which will make `{{url}}/start` have two `/`s.

**Comment by m3dbedb** [comment]
Thank you, now everything goes fine, and there in no mistake in url:
url = http://192.168.6.6:8089/api/v1
 {{url}}/serv makes http://192.168.6.6:8089/api/v1/serv

**Comment by shamasis** [comment]
Great to see all issues solved. Closing the issue.

**Comment by manv992** [comment]
when trying to run the newman report from the local from the commandline
<img width="447" alt="newman" src="https://user-images.githubusercontent.com/73941016/98105892-978aaf00-1ebe-11eb-9538-18037f8980f9.PNG">
