### ISSUE TITLE
Using --no-color flag causes newman to fail

### ISSUE THREAD

**Issue by chrisgbaker** [postmanlabs/newman#1709]
Possible regression on https://github.com/postmanlabs/newman/issues/808

Running the command 

`npx newman run ./postman_collection.json -e ./postman_environment.json -r cli,junit --reporter-junit-export ./Test-Results.xml --disable-unicode --no-color`

has been working in our CI/CD environment for some time, but tests have also been broken for awhile. looking into logs, it appears the `--no-color` flag was removed? Is this intentional?

The output of the command now: 
```
error: unknown option `--no-color'
```

**Comment by codenirvana** [comment]
@chrisgbaker The behavior of `color` option is changed in `Newman v4`.

For Disabling the colored output:

**V3 command**
```console
$ newman run collection.json --no-color
```

**V4 equivalent**
```console
$ newman run collection.json --color off
```

Check [V3 to V4 migration](https://github.com/postmanlabs/newman/blob/develop/MIGRATION.md#migrating-from-v3-to-v4) guide to know more.

**Comment by ArtVandelay101** [comment]
Hi,

Although I'm using the '--color off' option I'm still getting the color output (weird characters) when I run following cmd in TFS:

`run $(Build.SourcesDirectory)\src\Postman\xxx.json -e $(Build.SourcesDirectory)\src\Postman\DEV.postman_environment.json -g "$(Build.SourcesDirectory)\src\Postman\xxx.postman_globals.json" --delay-request 50 --reporter-html-export --folder "xxx" --color off`

Any ideas where I went wrong?

Thanks, AV.

**Comment by ArtVandelay101** [comment]
thanks, that was it :)
