### ISSUE TITLE
Request: Better error information

### ISSUE THREAD

**Issue by jaredmcateer** [postmanlabs/newman#171]
I had a request in a collection that was erroneously parsing the body of the request (I had thought I removed it but I had forgot to save.) When the error is output with the `stopOnError` flag is stops on the error but doesn't display which request had generated the error. Without the `stopOnError` flag set it continues so you can see the request but the error is displayed before the request information which makes it look like it belongs to the request before it.

POSTMan seems to use the `stopOnError` flag and as such it's collection runner never displays the request being made, however, if you monitor the xhr requests in devtools you can see the request being made. This was pretty confusing and I wasted about 10 minutes troubleshooting the wrong request.

I would suggest that newman output the request it failed on before it outputs the error to make it clear what's happening.

**Comment by shamasis** [comment]
This is being addressed in upcoming newman v3.x. In fact it is already fixed there. Try it out if possible - https://github.com/postmanlabs/newman/tree/feature/v3

**Comment by shamasis** [comment]
newman v3 now has the following

programatically:

- in summary object has `executions` array and the last item should have all relevant info
- there is also a separate `failures`array that keeps track of failures and it has `item` object in it which has `request`

CLI:
- the CLI stops on error when `--bail` is true having information regarding last failure
