### ISSUE TITLE
Security Issue with Alpine-based Docker Images

### ISSUE THREAD

**Issue by namelessvoid** [postmanlabs/newman#1715]
Hello there!

The current release of Alpine 3.8.1 contains an important security fix for the apk package manager: https://alpinelinux.org/posts/Alpine-3.8.1-released.html

Are there any plans to upgrade the alpine based newman image `newman_alpine33` to the latest version?

Maybe I could provide a pull request updating the image. A first round of testing revealed no compatibility breaking changes introduced by Alpine 3.8. However I would need some information about the best way to provide the image: as a new `newman_alpine38`? IMHO a general image not tied to a specific OS version could be provided as well, i.e. replacing `newman_alpine33` with an image called `newman_alpine`. This allows you to transparantly upgrade the alpine version without requiring actions from users.

**Comment by kunagpal** [comment]
@namelessvoid Thanks for bringing this up, feel free to send a pull request to create a new `newman_alpine` image. The `newman_alpine33` would eventually be deprecated (in the long-term future), we'll leave that as is for now (except Node and Newman version updates, of course).

**Comment by lajos-thiel-fielmann** [comment]
@kunagpal Would you be able to build and push newman_alpine to docker hub so we can use it in our builds without having to build from dockerfile?

**Comment by kunagpal** [comment]
@lajos-thiel-fielmann We're in the midst of updating our build scripts to account for this change, and will have the images ready shortly. 😄
