### ISSUE TITLE
running tests in parallel , there is no request to the server at all 

### ISSUE THREAD

**Issue by kthulsidoss** [postmanlabs/newman#1718]
Hi greetings. Here is the postman parallel request that i adopted 
https://github.com/postmanlabs/newman/blob/896a7b61955ee59bc8bfcfa144e7c5aa3639194e/examples/parallel-collection-runs.js , with help from the support i added the options to get the console output.
How ever i dont see the responses
C:\npm\node_modules>node parallel-collection-runs.js
newman

MFD_R9
newman

MFD_R9
newman

MFD_R9

┌─────────────────────────┬──────────┬──────────┐
│ │ executed │ failed │
├─────────────────────────┼──────────┼──────────┤
│ iterations │ 0 │ 0 │
├─────────────────────────┼──────────┼──────────┤
│ requests │ 0 │ 0 │
├─────────────────────────┼──────────┼──────────┤
│ test-scripts │ 0 │ 0 │
├─────────────────────────┼──────────┼──────────┤
│ prerequest-scripts │ 0 │ 0 │
├─────────────────────────┼──────────┼──────────┤
│ assertions │ 0 │ 0 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 265ms │
├───────────────────────────────────────────────┤
│ total data received: 0B (approx) │
├───────────────────────────────────────────────┤
│ average response time: 0ms │
└───────────────────────────────────────────────┘

┌─────────────────────────┬──────────┬──────────┐
│ │ executed │ failed │
├─────────────────────────┼──────────┼──────────┤
│ iterations │ 0 │ 0 │
├─────────────────────────┼──────────┼──────────┤
│ requests │ 0 │ 0 │
├─────────────────────────┼──────────┼──────────┤
│ test-scripts │ 0 │ 0 │
├─────────────────────────┼──────────┼──────────┤
│ prerequest-scripts │ 0 │ 0 │
├─────────────────────────┼──────────┼──────────┤
│ assertions │ 0 │ 0 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 516ms │
├───────────────────────────────────────────────┤
│ total data received: 0B (approx) │
├───────────────────────────────────────────────┤
│ average response time: 0ms │
└───────────────────────────────────────────────┘

┌─────────────────────────┬──────────┬──────────┐
│ │ executed │ failed │
├─────────────────────────┼──────────┼──────────┤
│ iterations │ 0 │ 0 │
├─────────────────────────┼──────────┼──────────┤
│ requests │ 0 │ 0 │
├─────────────────────────┼──────────┼──────────┤
│ test-scripts │ 0 │ 0 │
├─────────────────────────┼──────────┼──────────┤
│ prerequest-scripts │ 0 │ 0 │
├─────────────────────────┼──────────┼──────────┤
│ assertions │ 0 │ 0 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 407ms │
├───────────────────────────────────────────────┤
│ total data received: 0B (approx) │
├───────────────────────────────────────────────┤
│ average response time: 0ms │
└───────────────────────────────────────────────┘
MFD_R9 ran successfully.
MFD_R9 ran successfully.
MFD_R9 ran successfully.

C:\npm\node_modules>

as you can see it is not running any of the tests ? please help to solve this

**Comment by kthulsidoss** [comment]
There is no responses back at all as you can see from total data received so this output saying that MFD_R9 ran successfully is misnomer ?
Tx
K.thulsi Doss

**Comment by codenirvana** [comment]
@kthulsidoss Can you share a sample collection (minus the sensitive details) and the script used to run Newman with this behavior?

**Comment by kthulsidoss** [comment]
Hi since this is more of IBM environment , please schedule a webex/goto meeting where we can show the screen tx k.thulsi

**Comment by kthulsidoss** [comment]
i see the response after tweaking my collection containing the request. How to make postman to send the response to html ? i changed the option to reporters: [ 'html','cli'] it does not do that.

**Comment by codenirvana** [comment]
@kthulsidoss [HTML Reporter](https://github.com/postmanlabs/newman-reporter-html) won't include response in the report.
You can check #1493 thread for more detail.

**Comment by kthulsidoss** [comment]
okay we can close this
