### ISSUE TITLE
mac postman app curl not url encode

### ISSUE THREAD

**Issue by vincepeng** [postmanlabs/newman#1720]
mac 6.3.0  

### curl not urlencode
**origin** :`http://partner.qima-inc.com:7001/partner/com.youzan.beauty.partner.api.naturade.promotion.group.GroupActivityService/1.0.0/getGroup?json={"activityId":"1","userId":102707,"shopId":1138}`

**use app curl** 

curl -X GET \
  'http://partner.qima-inc.com:7001/partner/com.youzan.beauty.partner.api.naturade.promotion.group.GroupActivityService/1.0.0/getGroup?json={%22activityId%22:%221%22,%22userId%22:102707,%22shopId%22:1138}' \
  -H 'X-Requested-With: XMLHttpRequest'
`

**use chrome app:**

`curl -X GET \
  'http://partner.beauty.qima-inc.com:7001/partner/com.youzan.beauty.partner.api.naturade.pay.OrderRefundService/1.0.0/refund?json=%7B%22userId%22%3A%2227%22%2C%22orderNo%22%3A%22NR180909001636005888425%22%2C%22refundFee%22%3A1%7D' \
  -H 'x-requested-with: XMLHttpRequest'`

**Comment by shamasis** [comment]
Thanks for reporting. I am reporting the issue in the right issue tracker on your behalf. Please follow up at: https://github.com/postmanlabs/postman-app-support/issues
