### ISSUE TITLE
Unable to generate output.json with time stamp in file name.

### ISSUE THREAD

**Issue by 121arijit** [postmanlabs/newman#1727]
I am using command as ---> newman run Collection1.json -r json,html --reporter-json-export newman/output.json –-reporter-html-export newman/Reports.html 

Report getting generated with a timestamp in the file name but ouput.json file doesn't have any timestamp in the file name and it is getting overwritten every time. Is there any other option or command I can use to generate an ouput.json with the timestamp in the filename.

"newman":"4.0.1",
"newman-reporter-html": "1.0.1",
OS : windows 10
Running through windows batch file.

![imp](https://user-images.githubusercontent.com/11265383/45890497-bc0b9600-bde0-11e8-81b5-45bd27c98760.jpg)

**Comment by kunagpal** [comment]
@121arijit See https://stackoverflow.com/questions/203090/how-do-i-get-current-datetime-on-the-windows-command-line-in-a-suitable-format
