### ISSUE TITLE
Custom error messages in color

### ISSUE THREAD

**Issue by MStahl15** [postmanlabs/newman#1728]
Version and environment information:
 1. Newman Version: 4.1.0
 2. OS details:  Windows 10
 3. Are you using Newman as a library, or via the CLI?: CLI

I am using the "--color on" which works great but...

Is there a way to apply color to a error message that is caught and thrown other than the generic error messages that appear at the end of the request path?  

For example I'm grabbing my response  and outputting the error via:
console.log("Error: " + response.message);  
![githubticketnewmanerrorincolor](https://user-images.githubusercontent.com/10409834/45892634-e4b27200-bd85-11e8-858f-3d2829dde176.png)

**Comment by shamasis** [comment]
Hey - use console.error() 😛 it will do the job. 

Do post a screen of what you finally get!
