### ISSUE TITLE
Syntax Error in Semaphore Build

### ISSUE THREAD

**Issue by cajund** [postmanlabs/newman#1729]
Hi Folks,

I have API tests set up to run during a Semaphore build. The following lines used to work, but I am now getting an error when these commands are issued:

First this runs fine:

```
sudo apt-get -y update
sudo apt-get -y install nodejs
sudo apt-get -y install npm
sudo npm i newman -g
sudo ln -s /usr/bin/nodejs /usr/bin/node
```

Then this results in an error:

```
newman run https://api.getpostman.com/collections/$SEARCH_COLLECTION?apikey=$POSTMAN_API_KEY --environment https://api.getpostman.com/environments/$POSTMAN_ENV?apikey=$POSTMAN_API_KEY
```

Here's the error:

```
/usr/local/lib/node_modules/newman/bin/newman.js:57
        let options = util.commanderToObject(command),
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

This is a bare bones machine from Semaphore. The specs are here (Ubuntu 16.04 LTS 64-bit):

https://semaphoreci.com/docs/supported-stack.html#docker-light-platform

Is there something else that needs to be installed as part of the `npm i` command?

Let me know what more information I can provide. I have not tried to replicate this outside of the Semaphore build environment. However, these commands have worked in the past with no problems.

Thanks for any help you can provide.

**Comment by kunagpal** [comment]
@cajund It looks like you're on Newman v4 or above, which drops support for Node v4. You'll have to use at least Node v6, which can be done as follows:
```console
curl https://deb.nodesource.com/setup_8.x | bash;
apt-get install -y nodejs;
npm install -g newman;
```

**Comment by cajund** [comment]
Thanks!
