### ISSUE TITLE
Cipher customization support

### ISSUE THREAD

**Issue by Ramya-From-Postman** [postmanlabs/newman#1732]
The collections that are run using Newman is not working & resulting in the following error while the same works with curl command & when run through postman app. Please help resolve the issue.

```
Here is the command i ran

NODE_OPTIONS='--tls-cipher-list="ECDHE-RSA-AES128-GCM-SHA256:RC4"' newman run NewCollection.postman_collection.json

and the output is

newman

NewCollection

→ Get Users 
//endpoint URL is replaced with the actual API URL
GET https://{{endpoint URL}}/users [errored] 
This socket is closed 
2. Status code is 200 
3. Response time is less than 200ms

┌─────────────────────────┬──────────┬──────────┐ 
│ │ executed │ failed │ 
├─────────────────────────┼──────────┼──────────┤ 
│ iterations │ 1 │ 0 │ 
├─────────────────────────┼──────────┼──────────┤ 
│ requests │ 1 │ 1 │ 
├─────────────────────────┼──────────┼──────────┤ 
│ test-scripts │ 1 │ 0 │ 
├─────────────────────────┼──────────┼──────────┤ 
│ prerequest-scripts │ 1 │ 0 │ 
├─────────────────────────┼──────────┼──────────┤ 
│ assertions │ 2 │ 2 │ 
├─────────────────────────┴──────────┴──────────┤ 
│ total run duration: 131ms │ 
├───────────────────────────────────────────────┤ 
│ total data received: 0B (approx) │ 
├───────────────────────────────────────────────┤ 
│ average response time: 0ms │ 
└───────────────────────────────────────────────┘

# failure detail 

1. Error This socket is closed 
at request 
inside "Get Users" 

2. AssertionError Status code is 200 
expected { Object (id, _details, ...) } to have property 'code' 
at assertion:0 in test-script 
inside "Get Users" 

3. AssertionError Response time is less than 200ms 
expected undefined to be a number or a date 
at assertion:1 in test-script 
inside "Get Users"

```
Version and environment information:
-->
 1. Newman Version (can be found via `newman -v`): 3.9.3 
 2. OS details (type, version, and architecture): mac OSX high sierra 10.13.4 
 3. Are you using Newman as a library, or via the CLI? : CLI
 3. Did you encounter this recently, or has this bug always been there:
i am starting with newman first time so just experienced it...but i saw on the forums that people have hit this issue a year or two ago as well. 
 4. Expected behaviour: The expected behavior is newman should be able to execute the collection but its failing with the error i mentioned above and i will include it in the screen shot as well 
 5. Command / script used to run Newman: node --tls-cipher-list="ECDHE-RSA-AES128-GCM-SHA256:RC4" newman run {collection name}

**Comment by shamasis** [comment]
Ciphers are fixed while making request. Let’s take this up as a feature request to configure ciphers using easy to use protocol profile flags @udit.vasu

**Comment by codenirvana** [comment]
With the new request settings in the Postman app, you can specify any custom cipher suit.
