### ISSUE TITLE
Using -stopOnError prevents output via -H

### ISSUE THREAD

**Issue by NeilCross** [postmanlabs/newman#174]
I'm getting the issue above where if there's a failing test the execution stops as expected, however no output is generated on either -H or -o.

That may be an edge case that won't be used so often (as you may prefer to use -x rather than -s for report/output purposes) but the behaviour described was unexpected by me as a user if nothing else.

**Comment by shamasis** [comment]
This is being addressed in upcoming newman v3.x. In fact it is already fixed there. Try it out if possible - https://github.com/postmanlabs/newman/tree/feature/v3

**Comment by NeilCross** [comment]
Nice work
