### ISSUE TITLE
Getting Error Unexpected end of input at test-script

### ISSUE THREAD

**Issue by SDixit1** [postmanlabs/newman#1749]
I am running my  collection via  POSTMAN its running successfully but if I run the same collection via Command line (newman collection ) its giving error. my Request is SOAP request (xml).

my test script is 

 var jsonObject = xml2Json(responseBody);
console.log(jsonObject);
pm.test("Status code is 200", function () {
    pm.response.to.have.status(200);
});

pm.test("Verify CPWN", function () {
      pm.expect(jsonObject['soap:Envelope']['soap:Body']['ns1:confirmOrderResponse']['ns1:confirmOrderReturn']['ns2:confirmOrderResponseDetails']['ns3:CPWNRef']).to.eql('1538996411111');
      
});

![newmanerror](https://user-images.githubusercontent.com/42669483/46860083-89fdba80-ce07-11e8-9a49-b57cf3c07c02.JPG)

**Comment by kunagpal** [comment]
@SDixit1 In your second pm.test block, you've split the first argument to `pm.expect` across multiple lines, which in this case is invalid JavaScript. You can rewrite this as follows:
```js
var path = ['soap:Envelope', 'soap:Body', 'ns1:confirmOrderResponse', 'ns1:confirmOrderReturn', 'ns2:confirmOrderResponseDetails', 'ns3:CPWNRef'].join('.');

pm.test("Verify CPWN", function () {
    pm.expect(jsonObject).to.nested.include({ [path]: '1538996411111' });
});
```
