### ISSUE TITLE
Export a different environment filename per iteration

### ISSUE THREAD

**Issue by Ramya-From-Postman** [postmanlabs/newman#1752]
I’m using Newman and want to do the following: I want Newman to export the environment filename with a timestamp for each iteration. I can't seem to get this to work using the params. Here is my command which I thought would work. I’m on a mac running this command on my machine. Newman is only creating 1 filename with the timestamp. It’s not creating a unique filename for each run.

```console
newman run filename.postman_collection.json -e QA3.postman_environment.json --export-environment QA3_$(date +%Y%m%d_%H%M).postman_environment.json -n 2
```

After it runs the collection 2 times, I'm expecting to see 2 environment files each with the timestamp.

**Comment by codenirvana** [comment]
Closing as workaround exist https://github.com/postmanlabs/newman/issues/1752#issuecomment-429813523
