### ISSUE TITLE
Run Multiple collection with different Data file

### ISSUE THREAD

**Issue by SDixit1** [postmanlabs/newman#1760]
Hi,
Could you please suggest how to execute multiple  collections with different testdata file.
Collection1.json - Testdata1.json 
collection2.json - Testdata2.json 
-
-
-
collectionN.json - TestdataN.json

**Comment by kunagpal** [comment]
Closing as a duplicate of https://github.com/postmanlabs/newman/issues/1316. The example provided there can be expanded upon to satisfy this use case.
