### ISSUE TITLE
Docker image not able to export html because 4.0.0 change extracted html reporter

### ISSUE THREAD

**Issue by Singwai** [postmanlabs/newman#1762]
1. Newman Version (can be found via `newman -v`): 4.1.0
 2. OS details (type, version, and architecture): docker with any image ( alpine or ubuntu).
 3. Are you using Newman as a library, or via the CLI?: cli
 3. Did you encounter this recently, or has this bug always been there: since 4.0.0
 4. Expected behaviour: docker image able to export test result to html. 
 5. Command / script used to run Newman:
```
docker run --rm --volume="myfolder:/etc/newman" -t postman/newman_alpine33 run  requests.postman_collection.json -e ./env/env.postman_environment.json  --reporters cli,html --reporter-html-export /tmp/test-results/outputfile.html
```

 6. Sample collection, and auxiliary files (minus the sensitive details): n/a
 7. Screenshots (if applicable):
```
newman: "html" reporter could not be loaded.
  run `npm install newman-reporter-html`

newman
```

Steps to reproduce the problem:
docker run with `--reporters html --reporter-html-export out.html`

**Comment by kunagpal** [comment]
@Singwai See https://github.com/postmanlabs/newman/tree/develop/docker#using-newman-docker-images-with-custom-reporters for documentation on how to use Docker images with custom reporters.

**Comment by kunagpal** [comment]
@Singwai See https://github.com/postmanlabs/newman/issues/1759#issuecomment-431560704 for context on why the HTML reporter was turned into its own package.

**Comment by kunagpal** [comment]
Duplicate of https://github.com/postmanlabs/newman/issues/1759
