### ISSUE TITLE
Newman v4 deprecates support for the v1 collection format

### ISSUE THREAD

**Issue by davidmpaz** [postmanlabs/newman#1763]
Hi,

thanks for postman! I just start using the test scripts feature these days and did noticed this message in cli output:

```
newman: Newman v4 deprecates support for the v1 collection format
  Use the Postman Native app to export collections in the v2 format
```
I get this when invoking `newman` from `cli`. So, my expectations are that, I will have my collection exposed through links with support to the newest version. If older version is needed some alternative link should be provided maybe?

Does this make sense to you guys? Or am i missing something here?

 1. Newman Version (can be found via `newman -v`): **4.1.0**
 2. OS details (type, version, and architecture): **Linux 4.15.0-36-generic x86_64 x86_64 x86_64 GNU/Linux**
 3. Are you using Newman as a library, or via the CLI? **CLI**
 3. Did you encounter this recently, or has this bug always been there: **Dont know, just started using the feature now :)**
 4. Expected behaviour: **Postman links export proper version of format**
 5. Command / script used to run Newman: **newman run [collection url] -e localEnvFile.json**

Steps to reproduce the problem:

1. run `newman` as cli tool with any collection link

Thanks in advance for your time,
Cheers,
David

**Comment by codenirvana** [comment]
@davidmpaz Is the collection URL generated from `Share Collection` or you are using [Postman API](https://docs.api.getpostman.com/) to fetch the collection?

**Comment by dchBrandify** [comment]
@codenirvana I get this error when using the collection URL generated from Share Collection.
Is Postman updating the Share Collection functionality to support v2 format?

**Comment by codenirvana** [comment]
@dchBrandify Yes, keeping this thread open until Share Collection adds support for`v2` format.

**Comment by davidmpaz** [comment]
Hi @codenirvana, 

thanks for answering. My first attempt was to use the `Share Collection` approach. 

Later, did tried to find alternatives and head up with the Postman API, which yes, it solved my problem of having a reliable export.

I also think keeping the thread open untill supports for v2 lands in the `Share Collection` functionality is a good idea.

Cheers

**Comment by Ssuhaaktas** [comment]
Hi @codenirvana ,

any updates about this issue? still waiting for v2 support with "Share Collection".

Thank you.

**Comment by Keshav16021991** [comment]
HI @codenirvana ,
This issue is blocking me on test suite containing v1 and v2 both APIs, please whomsoever concerned fix this issue asap.

**Comment by shamasis** [comment]
This is just a warning message and doesn’t block anything. @Keshav16021991, could you upgrade to latest Newman and tell me what’s blocking Newman usage?

**Comment by Keshav16021991** [comment]
Actually, I have Newman version 4.3.1 but for this version when I am
running my suit it throwing me an exception with that v1 APIs not supported
in version 4, But I am having v1 API, then how to go further.

**Comment by shamasis** [comment]
This is only warning message that it will be removed in future major version upgrade. It works just as normal now.

**Comment by codenirvana** [comment]
Closing based on https://github.com/postmanlabs/newman/issues/1763#issuecomment-456312964
