### ISSUE TITLE
Custom reporters could not be loaded.

### ISSUE THREAD

**Issue by Ocsidot** [postmanlabs/newman#1766]
1. Newman Version:  **4.1.0**
 2. OS details: **Win7 64 bits**
 3. Are you using Newman as a library, or via the CLI? **CLI**
 3. Did you encounter this recently, or has this bug always been there: **Since my update to 4.0.1**
 4. Expected behaviour: **My custom exporter should work :)**
 5. Command / script used to run Newman:  newman run myCollection.json --reporters cli,html,xml
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

![2018-10-24 15_09_37-cmder](https://user-images.githubusercontent.com/6094145/47432825-68a1b480-d79f-11e8-94a6-bfdbcc0381a4.png)

I've created an exporter based on the JUnit one. In fact, I've added some fields in the export and modify the format. From my local directory, I've installed my new package (newman-reporter-xml) with npm install -g (since my newman is installed globally)

Before the update my exporter worked.

Regards

**Comment by codenirvana** [comment]
@Ocsidot This should not happen. You need to make sure that:
- Newman & custom reporter are installed in the same root path (`npm root -g`).
- Name of the package is of the form `newman-reporter-xml`.

**Comment by Ocsidot** [comment]
Here is the result of the npm list -g command. As you can see, both newman and my reporter are installed as the same level and can be found by npm
[npm-tree.txt](https://github.com/postmanlabs/newman/files/2510711/npm-tree.txt)

And a screenshot of the node module root path
![2018-10-24 15_42_28-node_modules](https://user-images.githubusercontent.com/6094145/47434759-84a75500-d7a3-11e8-8461-6552bbae86ef.png)

Regards

**Comment by codenirvana** [comment]
@Ocsidot This looks fine. How did you installed the custom reporter?
Can you try installing the package using [npm pack](https://docs.npmjs.com/cli/pack), and check if the issue persists?

**Comment by martijnvandervlag** [comment]
I noticed this during developing my own reporter! I noticed that if I comment ``` util = require('./util'), ``` and copy the function needed from ``` util.js ``` to ```index.js``` it works!

I have not investigated futher what is causing this issue but it seems to be in ```util.js```.

**Comment by Ocsidot** [comment]
@codenirvana I've tried and I have the same behavior :(
@martijnvandervlag I've also tried it and no change. 

I'll attached another reporter that was developed, named output and maybe you can find the issue on it
[newman-reporter-output.zip](https://github.com/postmanlabs/newman/files/2514313/newman-reporter-output.zip)

Regards

**Comment by codenirvana** [comment]
@Ocsidot I found two issues in the reporter code.

1. At `Line:14` change `getFullName:` to `getFullName =`.
2. At `Line:93` variable `body` is declared already at `Line:75`.

**Comment by Ocsidot** [comment]
Code fixed but the issue remains here is the console output.

newman: "output" reporter could not be loaded.
please install reporter using npm

**Comment by codenirvana** [comment]
@Ocsidot can you share the updated reporter code?

**Comment by codenirvana** [comment]
@Ocsidot This works fine for me.
Just make sure reporter is installed in the same root directory as of Newman.

For debugging, try switching to the directory and running Newman like:
```console
$ node newman/bin/newman.js run path/to/sample.json --reporters cli,output --reporter-output-export 'output-report.xml'
```

**Comment by Ocsidot** [comment]
@codenirvana Did you tried to install output reporter and run it?

I've checked that my reporter is installed in the same root directory as of Newman

**Comment by codenirvana** [comment]
@Ocsidot Yes, try directly moving the reporter to the directory. Don't install like: `npm i <folder>`.
I am facing issue with the packaged(`npm pack`) version.

**Comment by Ocsidot** [comment]
@codenirvana Finally, I've found where to place my package to make it works  :smile: 

If my package is in C:\Users\MyUser\AppData\Roaming\npm\node_modules\newman\node_modules, the exporter works

**Comment by codenirvana** [comment]
@Ocsidot Great to hear that!
You can also check other custom reporters like [newman-reporter-html](https://github.com/postmanlabs/newman-reporter-html) for reference.
