### ISSUE TITLE
noAssertions cli option not working in script, newman 4.1.0

### ISSUE THREAD

**Issue by JordanFriendshuh** [postmanlabs/newman#1768]
Version and environment information:
-->
 1. Newman Version 4.1.0
 2. Ubuntu 16.04
 3. Using newman as library

I encountered this bug when I upgraded to 4.1.0 from 3.8.3.  I do not see in the docs that this should have changed.

Basically what I am looking for is silent except the summary table.

newman call:
`newman.run({collection: currentCollection,
                        environment: environment,
                        globals: environment,
                        reporters: 'cli',
                        reporter: {cli: {noAssertions: true}}
                    })` 
The output is as if I had noAssertions: false.

**Comment by JordanFriendshuh** [comment]
Actually, it is different than no assertions, but I'm getting output that I don't want and don't know how to get rid of.  I want the summary table and failures, but I don't see an option to make this output go away except with silent.
I have tried noAssertions: true, noConsole: true, noBanner: true, noSuccessAssertions: true
`❏ 00. Mgmt
↳ Login (Org 1)
  POST https://fnetidentityapi-test.herokuapp.com/v2/auth/login [200 OK, 6.13KB, 92ms]

↳ Get Unit Id
  GET http://localhost:4000/v1/admin/units [200 OK, 6.4KB, 103ms]

↳ LRG2 Status Post
  POST http://localhost:4000/v3/status [200 OK, 566B, 352ms]

↳ LRG2 Status Post Same Guid
  POST http://localhost:4000/v3/status [200 OK, 566B, 347ms]

↳ Upload Work - Save to gallery
  POST http://localhost:4000/v3/upload/attachments [201 Created, 1.34KB, 739ms]

`

**Comment by codenirvana** [comment]
@JordanFriendshuh That's the expected behavior which got fixed in #1367
