### ISSUE TITLE
Lodash _.isPlainObject() returns false on a json decoded requestBody

### ISSUE THREAD

**Issue by xiphiaz** [postmanlabs/newman#177]
```js
var responseData = JSON.parse(responseBody);

tests["Reponse data is object"] = _.isObject(responseData); //true with postman && newman
tests["Reponse data is plain object"] = _.isPlainObject(responseData); //true postman && false with newman
```

The reason this is annoying is that lodash considers an array an object, which is not helpful when trying to assert the json response is an array not a single object.

I suspect that it is down to the JSON parser returning a different kind of object in Chrome vs Node.js

**Comment by abhijitkane** [comment]
We'll look into this. In the mean while, you can use
```!(responseData instanceof Array) && (responseData instanceof Object)``` for the second test.

**Comment by czardoz** [comment]
Not much we can do here if the runtime differences are causing this. The suggested workaround does the trick.
