### ISSUE TITLE
Upload multiple files not working using newman command

### ISSUE THREAD

**Issue by Sjain01** [postmanlabs/newman#1772]
newman version = 4.1.0
Using it as CLI to run via Jenkins

Running an API using Newman command in Jenkins which currently uploads a single file. My requirement is to upload multiple files using this same API.

My current code which uploads a single file looks like this:-

                    "header": [],
                    "body": {
                        "mode": "formdata",
                        "formdata": [
                            {
                                "key": "file",
                                "description": "Jpeg image or video (mov or mp4)",
                                "type": "file",
                                "src": "C:\\Test\\abc.jpeg"
                            }
                        ]
                    }

In this very same code, I want to upload multiple files. 

I tried following solution but nothing works:

                "header": [],
                "body": {
                    "mode": "formdata",
                    "formdata": [
                        {
                            "key": "file",
                            "description": "Jpeg image or video (mov or mp4)",
                            "type": "file",
                            "src": "C:\\Test\\abc.jpeg"
                        },
                        {
                            "key": "file",
                            "description": "Jpeg image or video (mov or mp4)",
                            "type": "file",
                            "src": "C:\\Test\\def.jpeg"
                        }

                    ]
                }
Please advise on how can this be achieved.

**Comment by OliverZou** [comment]
test run  for uploading a file usig form-data also results a fail........maybe the same issue,help

**Comment by codenirvana** [comment]
>I tried following solution but nothing works

@Sjain01 What's the response you received for the second example?

I tried to reproduce this, works as expected:
```javascript
"body": {
  "mode": "formdata",
  "formdata": [
    {
      "key": "file",
      "type": "file",
      "src": "./a.data"
    },
    {
      "key": "file",
      "type": "file",
      "src": "./data.csv"
    }
  ]
}
```

**Response:**
![file-upload](https://user-images.githubusercontent.com/4865836/48346218-7365b000-e6a0-11e8-9501-56ac340b0e7a.png)

**Comment by Sjain01** [comment]
Could make it work using multi-post request to upload files post discussion with a developer who confirmed that backend doesn't support uploading multiple images using single post request.

So this issue can be closed.
