### ISSUE TITLE
Error: you are not authorized by the server

### ISSUE THREAD

**Issue by Dennizzzzz** [postmanlabs/newman#1773]
1. Newman Version (can be found via `newman -v`): 4.1.0
 2. OS details (type, version, and architecture): Windows 10 Pro.
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: recently
 4. Expected behaviour: Run collection from postman web
 5. Command / script used to run Newman: newman run https://web.postman.co/collections/[guid]?workspace=[guid]
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

Steps to reproduce the problem:

1. Open command line
2. > newman run [url to my collection]
3. > response: error: You are not authenticated by the server.

I want to run a collection from the web using newman run https://web.postman.cp/etc. etc.

I get the error : 
You are not authenticated by the server.

Where am I not authorized? Is this the postman server where the collection is stored? Do i need to configure newman with username/password for the postman collection or something? Do i need to share my collection?

If I just export my collection to my own drive, everything works. But then if i change my collection or only one request, I need to export my entire collection again (instead of just hitting ctrl+s).

**Comment by kunagpal** [comment]
@Dennizzzzz See https://github.com/postmanlabs/newman#using-newman-with-the-postman-api for information on how to run a from a URL. The Postman Dashboard collection links are meant to be human-friendly.

**Comment by Dennizzzzz** [comment]
Thanx for the info.
