### ISSUE TITLE
How can I automate the process of sharing collection via postman? Could it be done using newman ?

### ISSUE THREAD

**Issue by ajijshaikh** [postmanlabs/newman#1777]
1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by shamasis** [comment]
As of now, Newman can only execute a collection already shared. You could put in a word in our community forum (community.getpostman.com) to expose the sharing feature via Postman API.
