### ISSUE TITLE
Newman library on AWS Lambda keeps using same request

### ISSUE THREAD

**Issue by amyyuqian** [postmanlabs/newman#1781]
1. Newman Version (can be found via `newman -v`): 4.1
 2. OS details (type, version, and architecture): Node.js 8.10
 3. Are you using Newman as a library, or via the CLI? Library
 3. Did you encounter this recently, or has this bug always been there: always been there afaik
 4. Expected behaviour: Newman should run the collection with a new datafile
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

I'm using the Newman library on a Node server on AWS Lambda but even when I change the datafile that is provided, every new lambda call uses the datafile from the very first request. The datafile being sent through Newman is the correct one, but Postman keeps reading in the old datafile for some reason. I've tried playing around with the exportEnvironment and exportGlobals options but they haven't changed anything - it still keeps sending the same old datafile.

Here is a code snippet:

```
    newman.run({
                collection: require('./postman/postman_script.json'),
                environment: require('/tmp/env_vars.json'),
                globals: require('./vars/globals.json'),
                iterationData: require('/tmp/datafile.json'),
                reporters: 'cli',
                iterationCount: (payload.iteration || 1) // TODO
            }).on('start', function (err, args) {
                console.error('starting collection run');
                let f = fs.readFileSync('/tmp/datafile.json');
                console.log(f.toString());
            })
            .on('done', function (err, summary) {
                if (err || summary.error) {
                    console.error('collection run encountered an error. please try again');
                    reject(err);
                } else {
                    console.log('collection ran successfully');
                    func.fetchVarFromFile('/tmp/env_vars.json', 'accountInfo').then((data) => {
                        let f = fs.readFileSync('/tmp/datafile.json');
                        console.log(f.toString());
                        fs.unlinkSync('/tmp/datafile.json');
                        fs.unlinkSync('/tmp/env_vars.json');
                        console.log('result');
                        console.log(data.accountInfo);
                        resolve(result);
                        return data;
                    })
                }
            });```

**Comment by kunagpal** [comment]
@amyyuqian This is happening because the disk you're writing the file back to is scrapped post Lambda run, effectively leading to your changes being lost. Each Lambda invocation starts from a state that is defined and maintained separately by AWS Lambda. In order to affect changes onto a data file, you could either store it in S3, fetch before the run and write it back once done. Alternatively, you can take a look at https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionCode.html for information on how to update Lambda code via API calls from within the Lambda function.
