### ISSUE TITLE
Iteration flag for newman

### ISSUE THREAD

**Issue by stofte** [postmanlabs/newman#1782]
What's the proper way to indicate to newman when running as an npm package that it should iteration N number of times? Doesn't seem to matter what option I use, such as "n" or "iteration-count" or "iterationCount".

var newman = require('newman');

newman.run({
  collection: 'API.postman_collection.json',
  environment: { key: 'URL', value: process.env.URL },
  reporters: ['cli'],
  n: 100
});

**Comment by kunagpal** [comment]
@stofte This can be done via the `iterationCount` option.

**Comment by stofte** [comment]
@kunagpal Thanks, I could swear I tried that, but oh well! :)
