### ISSUE TITLE
Make custom reporter event regstration possible via library usage

### ISSUE THREAD

**Issue by tkruse** [postmanlabs/newman#1788]
Hi,

I want to extend newman behavior with something like a custom reporter, but I don't want to go through the process of publishing and letting my module be found by newman via require.

it seems to me the documentation covers writing custom reporters, publishing them, and using them via cli-options (with support of all emitted events listed in https://github.com/postmanlabs/newman#newmanrunevents), and also how to run newman as a library.

What I don't see is how to run newman as a library and also register event listeners to the same events. is this possible in a clean way using the api?

**Comment by tkruse** [comment]
This relates to #935, but for using newman as a library.

**Comment by tkruse** [comment]
Ah, sorry. I guess that is

    newman.run({
    }).on(...)

**Comment by shamasis** [comment]
@tkruse - glad you found it. I also think a link to programmatic usage of Newman would be great in the reporter section. Will keep a note.
