### ISSUE TITLE
Newman CLI treating strings in CSV differently from POSTMAN - parsing failure

### ISSUE THREAD

**Issue by Kamoshin1** [postmanlabs/newman#1790]
1. Newman Version (can be found via `newman -v`): 4.2.2
 2. OS details (type, version, and architecture): Windows 10 Pro Version 1803  Running all files locally, but hitting internal API
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there:  This is a new collection
 4. Expected behaviour: I need to use a CSV file to import data into the response body of POST requests.  All values MUST be strings.  My CSV works correctly in POSTMAN, but fails with **error: Invalid closing quote at line 2; found "\"" instead of delimiter ","** in NEWMAN.
 5. Command / script used to run Newman:  newman run allPatients.postman_collection.json -e New_QA.postman_environment.json -d 2.csv
 6. Sample collection, and auxiliary files (minus the sensitive details): 

_In POSTMAN, when I run the requests, all values are strings and must be surrounded by doubled quotes._  I use a CSV file that looks like this:

"bin","pcn","group_id","member_id","last_name","first_name","dob","sex","pharmacy_npi","prescriber_npi"
"""012353""","""01920000""","""TESTD  273444""","""Z9699879901""","""Covg""","""MC""","""19500101""","""2""","""1427091255""","""1134165194"""

--------------------------

When I run the same CSV data file in NEWMAN, I get the error above.  I have tried a few options I've seen on this forum without any luck such as using Escape syntax for double quotes such as:
"/"text/"" 

The only things I've tried that have not failed pre-run with an error like above include removing the double-quotes entirely or replacing them with single-quotes.  When I do this, I get 400 Bad Request, which I suspect is due to me sending invalid data-types.

 7. Screenshots (if applicable):

**Comment by Kamoshin1** [comment]
Please close this issue.  It was the result of human error.  

I was able to fix this by correctly using the syntax suggested elsewhere.

"bin","pcn","group_id","member_id","last_name","first_name","dob","sex","pharmacy_npi","prescriber_npi"
"\"012353\"","\"01920000\"","\"TESTD  273444\"","\"Z9699879901\"","\"Covg\"","\"MC\"","\"19500101\"","\"2\"","
\"1427091255\"","\"1134165194\""

**Comment by codenirvana** [comment]
@Kamoshin1 Glad you found the fix.
Updated your previous comment. You can wrap the CSV data in back-ticks(```).

 Also, we are working on both Newman & App to have parity in CSV parsing.
