### ISSUE TITLE
Use of conditional statement results in assertion failure

### ISSUE THREAD

**Issue by Sjain01** [postmanlabs/newman#1796]
Newman Version: 4.1.0

I am using following conditional statement as test-script:-

    if (tests["Body does have verification finished string"] = (responseBody.has("verification.finished"))){
     console.log('Hi');
     }
     else {
     postman.setNextRequest("Webhooks Url status check");
      }
     If the condition is false, the Jenkins job fails with an assertion error in the script stating.

     1. Body does have verification finished string
     2â „ AssertionFailure in test-script

     Attempting to set next request to Webhooks Url status check

when executed via Jenkins, the job is failing. I do not understand the reason, It should simply execute the false condition instead of throwing assertion failure. 

I am using --bail option to stop the run if any of the assertions fails, can this be caused by --bail? If so, how can I put a stop to the run after a certain amount of next requests else I am afraid it can go into infinite loop.

**Comment by codenirvana** [comment]
@Sjain01 Using `--bail` flag, if any of the assertions fails it stops the collection execution.

Here, you can just check for the existence of the required string in the response body like this:
```javascript
if (!pm.response.text().includes('verification.finished')) {
  postman.setNextRequest("Webhooks Url status check");
}
```
