### ISSUE TITLE
How to run local postman collection with newman?

### ISSUE THREAD

**Issue by ChillarAnand** [postmanlabs/newman#1798]
In the docs, there are examples to run a downloaded collection from postman and postman URL collections. But there is no documentation on how to run postman collections in my local system. How can I run those collections with newman from CLI?

I don't want to download postman collection and run it because whenever there is an update, I have redownload it.

**Comment by codenirvana** [comment]
@ChillarAnand you can specify the file path or URL of the postman collection.

If I understand your question correctly, you don't want to export the collection every time you make changes. In that case, you can use [Postman API](https://www.getpostman.com/docs/v6/postman/postman_api/intro_api) to get the synced copy of your collection.

**Comment by ChillarAnand** [comment]
@codenirvana You are right. I dont want to export it everytime.

I want to avoid Postman API calls. Doesn't postman store collections on local system?

**Comment by codenirvana** [comment]
@ChillarAnand No, you have to use Postman API for that.
