### ISSUE TITLE
Modifying data in one workspace modifies data in other workspaces too

### ISSUE THREAD

**Issue by debjchak** [postmanlabs/newman#1819]
Newman Version:4.0.2,Postman Version:6.2.5
OS details (type, version, and architecture): Windows 7,64 bit production Imagev1.16.00.AO.B19
Newman via the CLI
Did you encounter this recently, or has this bug always been there: Recently started using
Expected behaviour: Scripts modified in one workspace should not reflect in others
 Could you please let me know why a script or a collection modified in one workspace modifies scripts/collections in other workspaces too?How do I avoid this?

Thanks
Debjani

**Comment by shamasis** [comment]
Postman workspaces allow you to neatly classify your collections based on your collaboration needs. https://www.getpostman.com/workspaces

Please use the appropriate issue tracker if you want more help. https://github.com/postmanlabs/postman-app-support


https://www.getpostman.com/community
