### ISSUE TITLE
403 forbidden error [behind a corportate network]

### ISSUE THREAD

**Issue by ackris** [postmanlabs/newman#1820]
Hi Everyone

 1. Newman Version (can be found via `newman -v`): _**version is 4.6**_
 2. OS details (type, version, and architecture): _**RHEL 7.4**_
 3. Are you using Newman as a library, or via the CLI? _**Downloaded Newman via npm**_ 
 3. Did you encounter this recently, or has this bug always been there: _**We are executing our postman collections through newman in Jenkins for the first time.**_
 4. Expected behaviour: `status 200`
 5. Command / script used to run Newman: `HTTP_PROXY=http://xx.xx.xx.xx:xx HTTPS_PROXY=http://xx.xx.xx.xx:xx newman run collections.json --reporters junit,html,xml`
 6. Sample collection, and auxiliary files (minus the sensitive details): _**Can't share as it is a confidential one (bank's property)**_
 7) Nodejs version: `10.14.2`

We are trying to automate the execution of API test collections using Newman in Jenkins. The collections are executing properly in postman, but we are getting 403 forbidden when we execute them in Jenkins. We are getting outputs like these:

`GET http://xx.xx.xxx.xx:xxxx/api/add-lead/ [403 Forbidden, 2.69KB, 133ms]`
`There was an error running your collection: tunneling socket couldn't be established, statusCode=403`

We have installed Jenkins and necessary capabilities to execute postman collections in a Jenkins agent. Jenkins, agent, the IPs mentioned in GET, PUT commands are in our bank's internal network. 

What could be the reason because we have scanned through similar issues, but found no satisfactory answers. 

Please help us. 

Regards
Aditya

Pinging @kunagpal

**Comment by rathodamol** [comment]
Try using insecure tag in cli. 
Eg: newman run postman_collection.json --insecure

**Comment by codenirvana** [comment]
@ackris Are you still facing this issue? Have you tried using `--insecure` flag?

**Comment by ackris** [comment]
@codenirvana  

Yes. It is still showing the same error.

**Comment by ackris** [comment]
@codenirvana  @rathodamol 

Now we are getting this error [1858](https://github.com/postmanlabs/newman/issues/1858). We are scratching our heads because it should work in a straightforward manner. 

Regards
Aditya

**Comment by davadora** [comment]
any update on this?  we've seen it secure and insecure, with requests staying inside our network and traversing out to the internet....does an upgrade to Jenkins and/or newman resolve it?

**Comment by codenirvana** [comment]
It looks like you are only setting the `HTTPS_PROXY` and trying to send `http:` requests.
I hope setting both `HTTPS_PROXY` and `HTTP_PROXY` will fix this issue.
