### ISSUE TITLE
How to catch before/after pm.test event

### ISSUE THREAD

**Issue by troe88** [postmanlabs/newman#1826]
Hello everyone,

I'm going to create my own reporter, so it is quite important for me to handle with before/after pm.test

![image](https://user-images.githubusercontent.com/8250210/50088296-a9ec9880-0213-11e9-961f-d5d17fe40006.png)

I've gone through available events that was mentioned in documentation, but solution hasn't been founded. 
Is this possible to handle with this events in the first place ?

Thank you in advance, 
Dmitry.

**Comment by codenirvana** [comment]
@troe88 No, There's no before & after `pm.test` event. But, for every new assertion in the test scripts `assertion` event will be triggered.

**Comment by troe88** [comment]
@codenirvana Thank you for the answer.
