### ISSUE TITLE
newman [4.2.3] doesn't pass qouta inside field

### ISSUE THREAD

**Issue by m3dbedb** [postmanlabs/newman#1831]
Version and environment information:

 1. Newman Version 4.2.3
 2. OS details Debian 9
 3. I use Newman via the CLI?
 3. I have encountered this recently
 4. Expected behaviour: as Runner do, pass "," as quota sign
 5. Command / script used to run Newman: newman run с1.json -d fiz.csv
 6. Sample collection, and auxiliary files (minus the sensitive details):
[c1.zip](https://github.com/postmanlabs/newman/files/2699272/c1.zip)

**Comment by m3dbedb** [comment]
Solutind for people who would face the issue: you may send comma and quotas using urlencoding for testing web pages: "Canada%2C Toronto" stands for  "Canada, Toronto"

**Comment by codenirvana** [comment]
@m3dbedb You can wrap the values in quotes like: `"value 1","value 2, 3"`
Also, we are working on both Newman & App to have parity in CSV parsing.
