### ISSUE TITLE
Multiple ssl key and cert in the same test

### ISSUE THREAD

**Issue by dtalex** [postmanlabs/newman#1839]
Hi,
I use newman latest verssion of newman via cli
I have the need to send https requests to different servers supporting mutual authentication in the same test simulating different users.
As of now in newman I can only set one couple key/cert.

I implemented it Q&D for my use here [https://github.com/dtalex/newman/tree/myMod](url)

Basically here 
```javascript
 certificates: options.sslClientCert && new sdk.CertificateList({}, [{
                name: 'client-cert',
                matches: [sdk.UrlMatchPattern.MATCH_ALL_URLS],
                key: { src: options.sslClientKey },
                cert: { src: options.sslClientCert },
                passphrase: options.sslClientPassphrase
            }])
```

I feed a configuration file done as follows
```json
[{
	"name": "identity1-cert",
	"matches": "https://server1.com/*",
	"key": {
		"src": "C:/a/b/identity1.key"
	},
	"cert": {
		"src": "C:/a/b/identity1.cer"
	}
},
{
	"name": "identity2-cert",
	"matches": "https://server2.com/*",
	"key": {
		"src": "C:/a/b/identity2.key"
	},
	"cert": {
		"src": "C:/a/b/identity2.cer"
	},
	"passphrase": "qwer1234"
}]
```

Is it possible to see it implemented in future releases?
(Probably I had to post it in Pull Requests but it is too "ugly" to be accepted)
Regards,
Ale

**Comment by sandeepkumar-aitha** [comment]
I too need this feature.

**Comment by sandeepkumar-aitha** [comment]
I too need this feature

**Comment by codenirvana** [comment]
`--ssl-client-cert-list` option is added in Newman v4.6.0 🎉

**Comment by s4ik4t** [comment]
Do not see any mention for pfx files, is that supported too?
