### ISSUE TITLE
Test Passes in Postman but fails in Newman for oAuth2.0

### ISSUE THREAD

**Issue by sergiybuch** [postmanlabs/newman#1859]
So I am using 2 requests, they both are ok in Postman Collection Runner, but somehow in Newman one of the requests is always  [401 Unauthorized]. I am using pre-request script to get a token and I was using it only in 1st request, then I switched requests, used script in both requests but 401 always in the same request.

 1. Newman Version 4.3.1:
 2. Windows 10:
 3. Are you using Newman as a library, or via the CLI? via CLI
 3. Did you encounter this recently, or has this bug always been there: Just started using it
 4. Expected behavior: Run tests same as Collection runner
 5. Command / script used to run Newman: newman run https://www.getpostman.com/collections/...
 6. Sample collection, and auxiliary files (minus the sensitive details):  
[Timesheet-GET.postman_collection.zip](https://github.com/postmanlabs/newman/files/2760857/Timesheet-GET.postman_collection.zip)

Steps to reproduce the problem:

1. Create Collection
2. Add pre-request script to get a token
3. Collection in Runner works fine but errors in Newman because token is missing

So I am using 2 requests, they both are ok in Postman Collection Runner, but somehow in Newman one the requests is always  [401 Unauthorized]. I am using pre-request script to get a token and I was using it only in 1st request, then I switched requests, used script in both requests but 401 always in the same request.

 Screenshots:
On screenshot you can see that request 1 is failing and request 3 is ok, they are exactly the same.

![newman](https://user-images.githubusercontent.com/28896994/51200056-6c3c6780-18c6-11e9-8bef-804c02c05ecf.png)
![image](https://user-images.githubusercontent.com/28896994/51200762-6b0c3a00-18c8-11e9-85ca-f7946710bbbf.png)

**Comment by sergiybuch** [comment]
Looks like I found what was the issue, to have it working in Newman you need to select OAuth 2.0 in Authentication. Postman works great when there selected No Auth because I am using pre-request script and Newman wants to have OAuth 2.0 selected.

**Comment by sravan449** [comment]
I am facing the similar issue,

**Following is my scenario**

I am generating an offline token from the server manually and in the Postman I have created an environment variable for token and passing this token variable in the requests by selecting OAuth 2.0 authentication

![image](https://user-images.githubusercontent.com/42779110/51443582-e2026200-1d10-11e9-94fa-9e2549b806ab.png)

I am able to run the requests from Postman Collection runner and I am getting 200 response code as expected but when I run the same collection runner from newman by passing the environment variable file as argument, I am getting 401 unauthorized error code 

I have tried to run the collection runner with the below syntax from cli

newman run "Runner.postman_collection.json" --environment "All Variables.postman_environment.json"

I expect this to return response code as 200 as I have Token variable in the environment variable but I am getting 401 error

Could someone please help me on how to resolve this issue in newman

**Comment by KristofVanKriekingen1337** [comment]
I am also facing the same results. We are validating not on "authentication" but on request headers.
When running tests in Postman Collection Runner, it works just fine. When running the tests by newman, I'm receiving 401 errors also. 

I'm also looking for a fix! :-)

**Comment by ruthraprakash** [comment]
me too facing this type of scenario. Actually in my scenario, Pre request scripts were not working on newman, but working on postman.

**Comment by Sha-123** [comment]
did anyone found solution? please share it.

**Comment by shamasis** [comment]
Yeah. We had slotted it a bit low on list. Bumping it up.

**Comment by saswatds** [comment]
It seems like all the issues reported here have custom auth flows and are not using the postman oauth2 helper provided in the app. (This helper can be accessed using the `Get New Access Token` button)

![Screenshot 2019-04-09 10 14 20](https://user-images.githubusercontent.com/8796447/55773851-43380700-5ab0-11e9-90d8-d13881120a3e.png)
To learn more about how to use the helper you can check out learning-centre https://learning.getpostman.com/docs/postman/sending_api_requests/authorization/#oauth-20

As per the current behaviour, selecting the `OAuth 2.0` in Authorization will enable the oauth2 helper.
During collection run the `Access Token` set will replace any existing `Authorization` headers that may have been set in the headers section.

Having clarified that we were **unable to reproduce** any of the above issues of inconsistency between app and newman using the oauth2 helper and _we would request anyone having issues with oauth2 helper or anyone other aspect of inconsistency to file separate issues with proper steps to reproduce._ 

On a side note, the helper generates and stores the access token and refresh token within the app and as such OAuth refresh cannot be done within newman.

**Comment by radhikanachiar** [comment]
Iam getting the same issue in Newman / VSTS pipeline. Iam setting a response of GET request to a global env. Variable and passing the same to another request ( as token ) , works locally. But when i run in Newman i get 401 error . My first GET request working fine in Newman but all my subsequent request does not pick my previous environment variable.

**Comment by shamasis** [comment]
Hey, this could be for various reasons. This thread is a closed issue around custom oAuth implementation. Can you file a separate issue with error output and —verbose Newman flag and a scaled down collection that we can run to reproduce this.

**Comment by tyomasson** [comment]
The same issue

**Comment by erpnedir** [comment]
I face the same problem. @radhikanachiar have you find a solution or open a new issue?

**Comment by rmnscb** [comment]
i have the same problem

**Comment by naderkhalil** [comment]
It seems that Newman cannot run thru Oauth2 flow and there isn't a plan to support it
Newman has "no way to prompt the user to login" and the "the app does not export the value of generated OAuth token to .json file"

https://github.com/postmanlabs/newman/issues/2615#issuecomment-776381139

**Comment by ongki** [comment]
Same issue.

**Comment by aladendorf** [comment]
Same here, I use oAuth2 with grant type credentials wich works without any poups except in newman, would be a great feature to support this.

**Comment by LTRichHouse** [comment]
Same for me. It's a pain.

**Comment by chancesmith** [comment]
Same issue for me as well.

**Comment by lindblb** [comment]
Same issue

**Comment by jdelpierre** [comment]
same issue :( 
How can I test oAuth02.0 authentication with Newman?

**Comment by deepakshenoyk** [comment]
I found a way to implement this. Implement Oauth2.0 as a new request and save the bearer token in the variables. Then.. even in Newman we can run Oauth2.0

**Comment by vinhkhangphung** [comment]
For future reader, solution suggested by `@deepakshenoyk` does work. But keep in mind that the pre-request script and the postman main request is not guarantee to be synchronous, therefore, there could be a case where the main request is sent before the access token is retrieved and stored.
