### ISSUE TITLE
Unable to post request with Path and Body parameters together in a post request.

### ISSUE THREAD

**Issue by adarshpandeyrinku** [postmanlabs/newman#1864]
Hi Team,

I am using visual studio code and node js terminal to generate postman collection using swagger2-postman-generator node package. while I am running the yaml it is not showing the body parameters in postman rather displaying a message provided for body parameter. Here are the snapshot of my code:

![image](https://user-images.githubusercontent.com/12835237/51480984-87244580-1db8-11e9-83f7-0888adc4a212.png)

![image](https://user-images.githubusercontent.com/12835237/51481106-eb470980-1db8-11e9-8eb2-eae020d2df09.png)

By running the command I can see the json file generated successfully but when I opened it in postman, it is not showing any parameters in body and just showing the description, as this snapshot...

![image](https://user-images.githubusercontent.com/12835237/51481286-850eb680-1db9-11e9-87d5-855eacc84d98.png)

Below is example of my Yaml file:
 
post:
    operationId: TestMe
    consumes:
        -   application/json
    produces:
        -   application/json
    parameters:
        -   name: GroupID
            in: path
            description: Unique identifier of the group.
            required: true
            type: integer
            format: int32
        -   name: myExtId
            in: path
            description: Unique identifier of my extension.
            required: true
            type: string
        -   name: Model
            in: body
            description: testing of body with string parameter.
            type: string
            required: true

**Comment by codenirvana** [comment]
I hope updating to the latest version of the Postman app fixes this issue.
If not, feel free to open a new issue in our issue tracker here: https://github.com/postmanlabs/postman-app-support
