### ISSUE TITLE
Better help on CLI

### ISSUE THREAD

**Issue by InFog** [postmanlabs/newman#1866]
Current output from `-h` on CLI is:

```
$ newman -h
Usage: newman [options] [command]

Options:
  -v, --version               output the version number
  -h, --help                  output usage information

Commands:
  run [options] <collection>  URL or path to a Postman Collection.
```

It would be better to have more documentation here, something like:

```
$ newman -h
Usage: newman [options] [command]

Options:
  -v, --version               output the version number
  -h, --help                  output usage information

Commands:
  run [options] <collection>  URL or path to a Postman Collection.

Options:
  -e <source>, --environment <source>           Specify an environment file path or URL
  -g <source>, --globals <source>               Specify the file path or URL for global variables
  -d <source>, --iteration-data <source>        Specify a data source file (CSV) to be used for iteration as a path to a file or as a URL
  -n <number>, --iteration-count <number>       Specifies the number of times the collection has to be run when used in conjunction with iteration data file.
```

And so on. So, what is available in https://github.com/postmanlabs/newman#command-line-options.

**Comment by deepakpathania** [comment]
Hey @InFog, what you're describing is exactly what we used to show in version 3.9.x. We decided to move away from that behavior to support better help text for multiple commands, in the near future, `run` being one of them.

So if you would like to see all the options for a particular command, you'll have to specify that command now. So in your case,
```js
newman run -h
```
should show all the supported options.

Hope this helps.

**Comment by InFog** [comment]
Thank you for the reply, @deepakpathania.

True, running `newman run -h` will show that. But this is not documented there. Since currently there is only one command, I think showing the options by default is nice. But I also understand the plans to have more commands.

What about documenting this behavior like:

```
$ newman -h
Usage: newman [options] [command]

Options:
  -v, --version               output the version number
  -h, --help                  output usage information

Commands:
  run [options] <collection>  URL or path to a Postman Collection.

To get available options for different commands:
  [command] -h
```

What do you think?

**Comment by deepakpathania** [comment]
Makes sense, would you be interested in sending a PR for the same? :)

**Comment by InFog** [comment]
Yes, I can do that. Can you point me where to look for on the source?

**Comment by InFog** [comment]
I found it. I'll send the PR.

Am Mo., 28. Jan. 2019, 06:17 hat Deepak Pathania <notifications@github.com>
geschrieben:

**Comment by codenirvana** [comment]
@InFog Thanks for contributing, this has been added in Newman v4.4.0.
