### ISSUE TITLE
Newman CLI ignores the "Body" section of a GET request

### ISSUE THREAD

**Issue by elijah-hawk** [postmanlabs/newman#1880]
**Describe the bug**
Newman CLI ignores the "Body" section of a GET request. In other words, Newman does not "process" the Body section (otherwise known as request.data) of a GET request but the Postman desktop app does.

**To Reproduce**
1. Install Postman desktop app 6.7.2 (macOS)
2. Install Newman 4.3.1 package via npm (macOS)
3. Create a GET request in Postman desktop app
4. Include a JSON in the Body of the request (I understand that the ability to do this for a GET request is new)
5. Ensure that the JSON is compatible with the GET request. This means that the Body of the GET request will need information that augments what is returned in the response.
6. Create a test to assert on the response body
7. Note that the assertion passes in the Postman desktop app
8. Run the collection in Newman
9. Notice that a TypeError or some other failure related to the passing assertion made in the Postman desktop app will return in Newman

**Expected behavior**
The assertion should pass in both Postman and Newman

**Screenshots**
![passes-in-postman](https://user-images.githubusercontent.com/20306765/52157785-cec39080-2646-11e9-8d07-10a739d091a0.png)
![fails-in-newman](https://user-images.githubusercontent.com/20306765/52157786-d08d5400-2646-11e9-8d0b-aaa9fb4d736e.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.7.2
 - Newman 4.3.1
 - macOS High Sierra 10.12.6

**Additional context**
Willing to set up a meeting with a Postman developer but will not share the endpoint that this was tested on here

**Comment by shamasis** [comment]
Yep, this could be a bug. Just putting down my thoughts here so that others may short circuit some reproduction work. 

- postman runtime uses protocolProfileBehaviour property in Item of SDK to let know that body should be sent
- as such, during export, postman app should include this configuration object in collection JSON (cc @numaanashraf, @kamalaknn)
- Newman should have latest runtime and should receive these properties (add integration tests if not already) @ankitsiam @codenirvana

**Comment by elijah-hawk** [comment]
Hello again, I tested this out using the Postman-Echo endpoints. here is a collection I can share:

[postman-echo-get.txt](https://github.com/postmanlabs/newman/files/2829674/postman-echo-get.txt)

Make sure to change the file extension to JSON. You will see that the tests made here pass in the Postman Desktop app but fail in Newman. The "protocolProfileBehavior" object exists in the collection. Thanks!

**Comment by codenirvana** [comment]
@elijah-hawk Here's the local server used for that test collection: [echo server](https://github.com/postmanlabs/newman/blob/develop/npm/server.js#L11)

Also, the postman-echo collection you shared is working fine for me.
<img width="541" alt="screenshot 2019-02-05 at 4 40 54 am" src="https://user-images.githubusercontent.com/4865836/52243626-3fe19d00-2900-11e9-99ac-a50ac1e3168e.png">

I see you shared your Newman version(4.3.1) above but can you confirm it using `newman -v` once.
Maybe try uninstalling and reinstalling Newman again. 😕

**Comment by elijah-hawk** [comment]
Interesting! You are correct, using the vanilla "newman run" command, I see success!

<img width="552" alt="vanilla-newman-run-is-successful" src="https://user-images.githubusercontent.com/20306765/52245055-f871f700-2894-11e9-8e2d-8aa530d784f2.png">

However, my Newman configuration uses a customer reporter. Here is an example command that I use in my terminal:
"JENKINS_BRANCH=local node newman-runner.js"

https://learning.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman/#custom-reporters

Where "local" is a configuration file that I use to specify the environment and collection. The newman-runner.js is a javascript file where I invoke the newman module.

With this information, does anything else pop up that I can do to troubleshoot? Thanks again, I should have cited that a custom reporter is leveraged in regressions earlier, my apologies.

**Comment by elijah-hawk** [comment]
Here is an image of the run, the fact that the custom reporter is simply a wrapper around Newman, shouldn't cause this problem should it? Maybe there is an update I need to make on the customer reporter? I did try to uninstall and re-install Newman to no avail:
![custom-reporter-results](https://user-images.githubusercontent.com/20306765/52247381-869eab00-289e-11e9-9ed1-91f29e9f35df.png)

**Comment by elijah-hawk** [comment]
Looking further into our own codebase for the custom reporter, here is a list of options that we have at time of running Newman:
```
currentOptions = {
      collection: collectionName,
      reporters: config.options.reporters,
      iterationCount: parseInt(program.number),
      delayRequest: parseInt(program.delayRequest) || 0,
      insecure: config.options.insecure,
      timeout: 2400000,
      ignoreRedirects: config.options.ignoreRedirects || false,
      globals: getGlobals(null)
    }
```
Is there an option that is enabled in vanilla newman that we aren't setting at runtime?

Possibly, something to do with?
```
"protocolProfileBehavior": {
    "disableBodyPruning": true
}
```
Thanks.

**Comment by codenirvana** [comment]
@elijah-hawk No, this looks fine.
Can you verify the Newman version used in your `newman-runner.js`?
Check its `package.json` or `node_modules/newman/package.json` or `npm list newman`.

**Comment by elijah-hawk** [comment]
@codenirvana, @shamasis, I figured it out! The package-lock.json needed updating, it was using Newman version 3.10.0).

I ran `npm install newman` which updated the package-lock.json and the package.json for the custom reporter.

On Friday, before I reported this issue I used `npm install -g newman` which for some reason did not update the package-lock.json.

Afterwards, I re-ran the collection and received passing assertions.

Thank you for all of your troubleshooting assistance!

**Comment by codenirvana** [comment]
@elijah-hawk Glad it worked for you!
`npm install -g` install's a package globally, it will not update your local package or package-lock.

**Comment by elijah-hawk** [comment]
Thanks, guys!

**Comment by petrisorionel** [comment]
It is a possibility to ignores the "Body" section for all type of request (POST / PUT / PATCH / DELETE ) ?
