### ISSUE TITLE
error: invalid command - after trying to run tests

### ISSUE THREAD

**Issue by 9av1n-j0hn50n** [postmanlabs/newman#1884]
Hi,

I've recently created a repo to run some tests against a CMS API.

I've added Newman via the following command in the projects directory on my machine:
`yarn add newman --dev`

It appears that everything installed correctly.

I've exported my collection via Postman and added the file (`publishApiTests.json`) to the project.

But when I run the following script in the project:
`yarn newman publishApiTests.json`

I get the this error:
```
yarn newman publishApiTests.json
yarn run v1.13.0
$ /PATH_GOES_HERE/node_modules/.bin/newman publishApiTests.json
error: invalid command `publishApiTests.json`

Usage: newman [options] [command]

Options:
  -v, --version               output the version number
  -h, --help                  output usage information

Commands:
  run [options] <collection>  URL or path to a Postman Collection.
✨  Done in 0.70s.
```

I'd be grateful for any help given, my Newman knowledge isn't that great.

Newman Version: **4.3.1**
OS details (type, version, and architecture): **node 8.9.4** 

Thanks!!!

**Comment by codenirvana** [comment]
@9av1n-j0hn50n You need to specify the `run` command:
`yarn newman run publishApiTests.json`

Usage documentation: https://github.com/postmanlabs/newman#usage

Also, for issues like this, we have an active user community forum that will help to solve further issues. Visit: https://community.getpostman.com/

**Comment by 9av1n-j0hn50n** [comment]
@codenirvana thanks for your help!
