### ISSUE TITLE
Question: Running A Single Operation From A Postman Collection Within A Folder

### ISSUE THREAD

**Issue by bhreinb** [postmanlabs/newman#1890]
1. Newman Version (can be found via `newman -v`): 4.3.1
 2. OS details (type, version, and architecture): macOS High Sierra
 3. Are you using Newman as a library, or via the CLI? Library
 3. Did you encounter this recently, or has this bug always been there: Encountered this recently
 4. Expected behaviour: Ability to target a single resource within a folder

Steps to reproduce the problem:

1. I have a postman collection something like the following:
    Sample Postman Collection
         Folder 1
            Operation 1 Folder 1
            Operation 2 Folder 1
        Folder 2
            Operation 1 Folder 2
            Operation 2 Folder 2

My use case is that I generate a postman collection from the swagger file. I use a library to do that which generates a postman collection and an environment file. I overwrite the autogenerated environment file with one that was handcrafted as part of a manual test effort. The collection & environment file (that I replace) I send them onto newman library to do some API testing

```
const response = await newman.run({
        environment: require('./Sample_Web_Services.postman_environment.json'),
        collection: require('./Sample_Web_Services.postman_collection.json'),
        reporters: 'json'
    }, function (err, summary) {
```
Unfortunately, I don't have control over the content of the swagger file hence I'd like to be able to execute `Operation 1 Folder 1`. In some cases I'd like to execute all operations within a folder or only just one from a folder. Would you have any suggestions on how to solve this? One solution would be to re-structure the swagger so that one operation is assigned to one folder but as mentioned above I don't have control of the content of the swagger document been sent to me. Many thanks in advance re any help with the above.

**Comment by codenirvana** [comment]
@bhreinb You can use the `folder` option to run a specific folder(s) instead of the entire collection.
For your use case, add `folder: 'Operation 1 Folder 1'` in your `newman.run` options.

**Comment by bhreinb** [comment]
Hi @codenirvana 

Thanks for the suggestion. However let's say

```
Operation 1 Folder 1 is a put request
Operation 2 Folder 1 is a get request
```

So I can target Folder 1 per your suggestion. But if I only wanted to target one of the requests in the folder that is where the issue lies does it not? Their is a use case for me to not target all APIs within a subfolder. Any ideas on how to solve that?

**Comment by codenirvana** [comment]
@bhreinb If your request name is unique(across the collection, otherwise all the duplicates will be executed), you can specify the request name in the folder option and that single request will be executed.

**Comment by bhreinb** [comment]
Oh I wasn't aware of that...I will investigate further on my end. Thanks for answering all my questions 🙂. Have a nice day.

**Comment by bhreinb** [comment]
Hi @codenirvana 

Apologies last question. So I tried out what you mentioned above.

I use the parameter folder and I'm able to target a request name per your suggestion as long as it's unique. Thanks for that.

Now where the issue lies is

1. if their is requests in the collection that have the same name regardless of folder structure (the first in the collection is picked...no duplicates are executed)
2. I'm unable to target a specific request belonging to a particular folder (this would seem to be the offending code)

```
// sets entrypoint to execute if options.folder is specified.
        if (options.folder) {
            entrypoint = { execute: options.folder };

            // uses `multipleIdOrName` lookupStrategy in case of multiple folders.
            _.isArray(entrypoint.execute) && (entrypoint.lookupStrategy = MULTIENTRY_LOOKUP_STRATEGY);
        }
```

I can't pass lookupStrategy as part of folder options. Thoughts?

**Comment by codenirvana** [comment]
@bhreinb You are right, that's not supported yet. We are tracking this feature request here: #1851
