### ISSUE TITLE
Deprecated warning for package circular-json 

### ISSUE THREAD

**Issue by vinodtelang** [postmanlabs/newman#1908]
1. Newman Version (can be found via `newman -v`):  **4.3.1**
 2. OS details (type, version, and architecture):   **window 7, 64-bit**
 3. Are you using Newman as a library, or via the CLI? : **Newman as a library**
 3. Did you encounter this recently, or has this bug always been there: **Always** 
 4. Expected behaviour: **Warning should be gone.**
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):
 8. **Node > 10.x** 

![newman_warning](https://user-images.githubusercontent.com/44158944/53071993-d7064180-3509-11e9-9c82-3aac8d2a88ec.png)

Deprecated package comes along with latest newman version. Kindly suggest the solution.

**Comment by shamasis** [comment]
This is will be handled by https://github.com/postmanlabs/uvm/pull/262

cc @codenirvana @kunagpal - can you review, release and upkeep?

**Comment by msbhalerao** [comment]
Facing the same issue.. Please suggest solution.

**Comment by shamasis** [comment]
This is not an issue. This message is not shown by Newman, but by underlying npm.
