### ISSUE TITLE
Newman not producing html reports

### ISSUE THREAD

**Issue by pkaramol** [postmanlabs/newman#1910]
```
    $ sudo newman run testing.postman_collection.json -k -e testing_environment.postman_environment.json -r htmlextra --reporter-htmlextra-report /home/pkara/Desktop
    /home/pkara/Desktop
    $ ls ~/Desktop/*.html
    ls: cannot access '/home/pkara/Desktop/*.html': No such file or directory
```

However the following command produces output in my terminal as expected

`    sudo newman run testing.postman_collection.json -k -e testing_environment.postman_environment.json -r cli
`
(have tried with and without `sudo`)

```
$ newman -version
4.4.0
/home/pkara/Desktop
$ npm -version
5.10.0
/home/pkara/Desktop
$ nodejs --version
v8.14.0
/home/pkara/Desktop
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

**Comment by codenirvana** [comment]
@pkaramol This is probably because `htmlextra` reporter is missing. Can you verify that?

You can install it using: `npm i -g newman-reporter-htmlextra`

**Comment by DannyDainton** [comment]
HEY @pkaramol, 

Not sure if you have solved this problem or not but `--reporter-htmlextra-report` isn't a flag option on the reporter, as mentioned in your example. 

It's either `--reporter-htmlextra-export` to specify an export location or `--reporter-htmlextra-template` to specify the path to a custom template.
