### ISSUE TITLE
403 error on test with 4.4.0, no problem on 4.3.1

### ISSUE THREAD

**Issue by gchablowski** [postmanlabs/newman#1912]
1. Newman Version (can be found via `newman -v`): 4.4.0
 3. Are you using Newman as a library, or via the CLI? install wiht npm and use cli
 3. Did you encounter this recently, or has this bug always been there: The bug is only present on 4.4.0
 4. Expected behaviour: The test should go as before
 5. Command / script used to run Newman: newman run ./test/e2e/test.json
 6. Sample collection, and auxiliary files (minus the sensitive details): https://github.com/Back9digital/b9-payment/blob/master/test/e2e/test.json

We use newman on our CI with Travis to test our api gateway. All was working since we pass to the last newman version (4.4.0), now all test return a 403 error. If we downgrade newman to 4.3.1 all work as intended. The test past to on postman. 
We try to reexport the test from postman, but it's continue to fail.
We try on local and we have the same issues.

Do the last version introduce a bug or something change ?

Thanks for all.

**Comment by codenirvana** [comment]
@gchablowski can you provide more information about this issue?
This is happening for a single request or for the entire collection?

The collection you shared looks fine but I can't test locally to reproduce this issue because it depends on environment variables. Is it possible for you to share the environment variables as well or a scaled-down collection with this behavior?

**Comment by gchablowski** [comment]
Hi @codenirvana,
This happening for all the request.
It's possible to share the environement variable, but you may understand that I am not very enthousiast to put them in the wild. 
May you give me your email and I send you that back?

Thanks.

**Comment by codenirvana** [comment]
@gchablowski As discussed over the email, this is happening because of request mutation i.e, the header was getting updated via pre-request script.
We are working on documenting this feature and the underlying sandbox APIs.
