### ISSUE TITLE
Output Response on Test Failure

### ISSUE THREAD

**Issue by wbrooks1981** [postmanlabs/newman#192]
I am looking to see if this would be a desirable feature request.   In POSTMAN (not in Collection Runner)  when you execute a request you will get all the desired information to help debug your JavaScript code.   Here is what I was thinking in newman.

On a request,   if you have a test created (tests["This is a test"] = false;)  and it fails,  it would be great for the console output to display the responseBody.  
This would display after all the tests of the request are displayed.  

Here would be an example of the output to console, since a test (in this case 2) failed it would display the responseBody at the bottom of the request. 

500 829ms Create Object Widget https://www.website.com/v1/object/12345
    x Status code is 400
    x Error is as expected
{"documentation":"https://www.website.com/rest/errors/500","errorcode":0,"message":"Error occurred"}

In addition you could drive this functionality with a command line parameter as well.

**Comment by jungle-boogie** [comment]
I'd also like the -t option to save the response to a file for BOTH pass and fail.

**Comment by digital-abyss** [comment]
I've made a PR that allows an optional file to be specified that would log all request and response bodies (not just failures): https://github.com/postmanlabs/newman/pull/218

Thoughts ?

**Comment by vishbin** [comment]
Is this feature  implemented  ?

**Comment by czardoz** [comment]
The PR is merged now. Closing this issue.

**Comment by rapidroamer** [comment]
-t is discontinued, anyone looking to log response, please use:
--reporters json and optionally
 --reporter-json-export <File>
