### ISSUE TITLE
While executing collection in node , not able to send my data file 

### ISSUE THREAD

**Issue by Subhashini-1** [postmanlabs/newman#1926]
While executing collection in node , not able to send my data file 
Version and environment information:
 1. Newman Version : 4.4.0
 2. OS details (type, version, and architecture): Windows 10 
 3. Are you using Newman as a library, or via the CLI - Command line options
 3. Did you encounter this recently, or has this bug always been there: Recently
 4. Expected behaviour: Should be able to run collection fetching the data file sent in js file 
 5. Command / script used to run Newman: node Sample.js
 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/44973580/53686064-b54a5d00-3d48-11e9-9be7-0bf95589558f.png)

Refered below 
1.https://github.com/postmanlabs/newman#command-line-options
![image](https://user-images.githubusercontent.com/44973580/53686073-d3b05880-3d48-11e9-8d2e-324870c9cb31.png)

2.https://learning.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman/
![image](https://user-images.githubusercontent.com/44973580/53686079-e1fe7480-3d48-11e9-933d-7022e9d2c1de.png)

1. How to send data for a collection file in node ?
2. As per above screenshots , at one file its mentioned as data and in other its mentioned iteration-data
3. Tried using both options in js file ,none of them is working  (while running in cmd prompt using -d its working )

Please help addressing what should be the option for data file .

JS File 👍 

const newman     = require('newman')
const nodemailer = require('nodemailer')
const MailComposer = require("nodemailer/lib/mail-composer");
const from_who = 'subhashiniarumugham@gmail';
var pdfcrowd = require("pdfcrowd");
newman.run({
    collection: 'Downloads/Smoke_Suite.postman_collection.json',
    environment: 'Downloads/Aircanada_Int.postman_environment.json',
	iteration-data: 'Downloads/Data.csv', (Also tried using data:'Downloads/Data.csv )
	iteration-count: '1',
    d: 'Downloads/Data.csv',
    reporters: 'htmlextra',
     reporter: {
        htmlextra: {
            template: 'Downloads/EIP_INT.hbs',
         	export:'Desktop/SmokeReport.html',

**Comment by DannyDainton** [comment]
Use `IterationData` within the script.

https://github.com/postmanlabs/newman/blob/develop/README.md#newmanrunoptions-object--callback-function--run-eventemitter

**Comment by Subhashini-1** [comment]
I have tried using IterationData in node script along with iterationCount in number value ,but still its not reading my csv file.

**Comment by DannyDainton** [comment]
Would you be able to elaborate more on _not reading_ your file. 

Those 2 changes would have solved the error that you were seeing. 

Is this now a question around the way the data from the file is used in your collection? Can you provide an example of the file and the way you have the data references in the requests.

**Comment by Subhashini-1** [comment]
Hi Danny

Yes.This is about using the data from file in collection.The data file is
in csv format with key value pairs .

I have referenced them in collection by {{key}} value.


Thanks,
Subhashin

**Comment by Subhashini-1** [comment]
Able to read and reference the data file after node reinstallation !
