### ISSUE TITLE
Allow Request body to be a usable variable

### ISSUE THREAD

**Issue by wbrooks1981** [postmanlabs/newman#193]
Not sure if this functionality exists, but looking to see a feature to have the ability to work with the requestBody.  

When a request is sent,  we are able to interact with responseCode and responseBody.    It would be great to have a parameter that was called requestBody.  This way I could either console.log the requestBody, or JSON.parse the requestBody and other similar things that can be done to responseBody to help debugging.

**Comment by abhijitkane** [comment]
You can use `request.data`.

The current properties are available for the request:
url, headers, data, dataMode

Our docs are a bit lacking, and we're working on revamping them.

**Comment by wbrooks1981** [comment]
Ah great!   That is what I am looking for thanks!

**Comment by wbrooks1981** [comment]
Ok I see that these are working great.  Only one thing I think may be wrong.   When utilizing the request object in the test section, the Headers don't have the tokens filled out.

Basically I am seeing if I attempt to use request.headers  and there is a header that is utilizing a token they token name and not the value is being returned.

{Authorization: "{{authToken}}", Content-Type: "application/json"}

I would expect 

{Authorization: "someauthTokenValue", Content-Type: "application/json"}

**Comment by abhijitkane** [comment]
Variables aren't resolved in the pre-request script, because the script itself can modify the variables.

In the tests section, we can include the resolved values. We'll add this in a future release.

**Comment by shamasis** [comment]
@czardoz - in upcoming postman api, we could have two request instances, the original one and the one post authorisation.

**Comment by kunagpal** [comment]
@czardoz @shamasis Are we good to close this issue?

**Comment by shamasis** [comment]
No. Will close when we have a solution.

**Comment by kunagpal** [comment]
This is not a part of our current roadmap, but has been marked as a feature request and added to our internal tracker. We'll update this thread when any progress occurs on this. :)

**Comment by czardoz** [comment]
This is fixed with the `pm.request` object. More details here: https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference
