### ISSUE TITLE
Postman global variables return variable name not variable content using POST form-data request

### ISSUE THREAD

**Issue by mpetusky** [postmanlabs/newman#1930]
Newman v 4.40
Windows 10 64-bit
Running Newman from command prompt

Newman test returns the global variable name, not the contents of the variable.  Test runs in Postman GUI.

Variable set in test pre-request script:

    pm.globals.set('Analyses_tmpAdHocUploadConfig', JSON.stringify(requestObj));

Test script source:
 
![image](https://user-images.githubusercontent.com/27212405/53983801-0ca05280-40e6-11e9-8abd-ccf4590a3125.png)

Postman GUI show data is being generated and set to global variable in the pre-reqeuest script
![image](https://user-images.githubusercontent.com/27212405/53984227-efb84f00-40e6-11e9-8524-93ac0f0f69ac.png)

**Comment by codenirvana** [comment]
Can you share a scaled-down collection which we can use to reproduce this issue?

**Comment by DannyDainton** [comment]
Hey @mpetusky,

I'm going to close out this issue, we can open it up again if you're able to reproduce the problem, with a scaled-down Collection, in the latest version.
