### ISSUE TITLE
Junit report doesn't pass validation against schema in xunit Jenkins plugin

### ISSUE THREAD

**Issue by donotello** [postmanlabs/newman#1931]
1. Newman Version (can be found via `newman -v`): `4.4.0`
 2. OS details (type, version, and architecture): `Ubuntu 18.04.2 LTS`
 3. Are you using Newman as a library, or via the CLI? `CLI`
 4. Did you encounter this recently, or has this bug always been there: introduced in 4.3.1 (#1828)
 5. Expected behaviour: junit report generated by newman is successfully validated against [Ant junit](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) and [Maven surefire](http://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd) schemas
 6. Command / script used to run Newman: `newman run single-request-failing.json -r junit --reporter-junit-export test.xml`
 7. Sample collection, and auxiliary files (minus the sensitive details): you can use any collection e.g. [single-request-failing.json](https://github.com/postmanlabs/newman/blob/develop/test/fixtures/run/single-request-failing.json)

This issue breaks our integration of newman with [Jenkins xUnit plugin](https://wiki.jenkins.io/display/JENKINS/xUnit+Plugin):

```
INFO: [JUnit] - 1 test report file(s) were found with the pattern 'newman-output/xml/Newman-Output.xml' relative to '/scm/Checkout/develop' for the testing framework 'JUnit'.
WARNING: The file '/scm/Checkout/develop/newman-output/xml/Newman-Output.xml' is an invalid file.
WARNING: At line 3 of file:/scm/Checkout/develop/newman-output/xml/Newman-Output.xml:cvc-complex-type.3.2.2: Attribute 'classname' is not allowed to appear in element 'testsuite'.
...
```

**Comment by codenirvana** [comment]
@donotello This is fixed in Newman v4.4.1. Thanks for contributing!
