### ISSUE TITLE
error: You are not authenticated by the server.

### ISSUE THREAD

**Issue by PresidentCamacho** [postmanlabs/newman#1943]
1. Newman Version (can be found via `newman -v`): 4.4.0
 2. OS details (type, version, and architecture): Windows 10
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Never got it to work
 4. Expected behaviour: Collection runs with environment variables
 5. Command / script used to run Newman: newman run https://www.getpostman.com/collections/[$id] -e https://[$team].postman.co/environments/[$environments]cd?workspace=[$workspace]/environments?apikey=[$apikey]

Hi,

I'm trying to run a collection though newman cli with the command above except for I've changed the real values to [$x]. When I run the command I get the message: `error: You are not authenticated by the server.`. When running the collection through newman without the environment url everything works. But not with the environment url. What am I doing wrong?

**Comment by kunagpal** [comment]
@PresidentCamacho Apologies for the delay, could you confirm that the environments used via the URL and local file are identical?
