### ISSUE TITLE
The request.header.referer value is not set properly

### ISSUE THREAD

**Issue by barnarock** [postmanlabs/newman#1946]
Version and environment information:
-->
 1. Newman Version (can be found via `newman -v`): **4.4.0**
 2. OS details (type, version, and architecture): **Windows 10 Pro v1803**
 3. Are you using Newman as a library, or via the CLI? **CLI**
 3. Did you encounter this recently, or has this bug always been there: **I've encountered it recently, but it seems that it was happening always (I downgraded newman to previous versions e.g. 3.6.1).**
 4. Expected behaviour: **When the call entails an http redirect, the redirect_uri is saved into the header.referer parameter. That happens using Postman (expected behaviour), but not using Newman.**
 5. Command / script used to run Newman: **newman run XXX.postman_collection.json -e XXX.postman_environment.json --reporters cli,htmlextra --folder "XXX"**
 6. Sample collection, and auxiliary files (minus the sensitive details): **I am using the google api oAuth in order to obtain the code and then the token.** 
 7. Screenshots (if applicable): See the red circles.

![postmanVSnewman](https://user-images.githubusercontent.com/48828621/54822052-4e172d00-4ca4-11e9-86ae-2a54ba3ba12d.jpg)

**Comment by codenirvana** [comment]
Can you check if this issue is still reproducible in the latest version of Newman?
If not, can you share a scaled-down collection which we can use to reproduce this issue?

**Comment by DannyDainton** [comment]
Hey @barnarock 

I'm going to close out this issue, we can open it up again if you're able to reproduce the problem on the latest version.
