### ISSUE TITLE
How Do I save a environmental variable from grunt-newman

### ISSUE THREAD

**Issue by sudazzle** [postmanlabs/newman#196]
I am using grunt-newman plugin to automate the test. Everything is working file but I am not able to push value into the environment variable like in postman. In postman we can just call postman.setEnvironmentVariable(“key”, “value”). Need help

**Comment by abhijitkane** [comment]
The syntax is correct.Just make sure you use the right quotes - 
`postman.setEnvironmentVariable("key", "value")` instead of `postman.setEnvironmentVariable(“key”, “value”)`

Also, this won't edit the environment file you're using. The variable will only be available during the duration of your run.

**Comment by StevenWatremez** [comment]
I have the same error when I send my auth request with Newman, it doesn't write the Token value into my environment value. So I can't use the auth Token for my others requests.

**Comment by StevenWatremez** [comment]
If the variable is only available during the duration of the run. If I want to run requests with folder's collection (-f option with Newman), how can I set my variable between two run ?

**Comment by abhijitkane** [comment]
You cannot, at the moment. Newman does not edit the environment file that you provide. You'll need to create a new collection which has all the requests, and run that with Newman. We'll be adding the persist environment variables feature soon, but I can't offer an ETA on that.

**Comment by bandtank** [comment]
I'm having this problem and my quotes look like they're correct. What else could it be? It's weird because one of my variables is being set correctly (or so it seems...) while none of the others are working. I exported everything directly from Postman.

**Comment by abhijitkane** [comment]
The -e switch is for environments, the -d is for data files (CSV/JSON files only)
Sample env file - https://gist.github.com/abhijitkane/3bee2334fcc234e43dc4
Sample data file - https://www.getpostman.com/docs/jetpacks_examples (towards the end)

If you still face issues, can you send the sample collection/env file to help@getpostman.com

**Comment by czardoz** [comment]
@bandtank I'm closing this issue, since your problem does not seem to be with grunt-newman. If you're still facing it, could you open a new issue?

**Comment by gpicazo** [comment]
> You cannot, at the moment. Newman does not edit the environment file that you provide. You'll need to create a new collection which has all the requests, and run that with Newman. We'll be adding the persist environment variables feature soon, but I can't offer an ETA on that.
**Aug 4, 2015**

@abhijitkane Is there an ETA/update on this feature yet?

**Comment by czardoz** [comment]
@gpicazo Newman now allows you to export the environment variables at the end of the run (with the --exportEnvironment option). Is that what you're looking for?

**Comment by gpicazo** [comment]
@czardoz Yes, that's what I was looking for. Thank you very much.

**Comment by Nudink** [comment]
@czardoz Is there a way in which I can persist new environment variables during a run. For example, with the first request i create an incremental value which I set as a variable and want to use in my second request in the same run.
