### ISSUE TITLE
Reading Response Header

### ISSUE THREAD

**Issue by sudazzle** [postmanlabs/newman#197]
I encountered a interesting issue while reading the response header. Our application responses with some custom headers. responseHeaders.hasOwnProperty works fine in postman no issues, but same thing doesn't work in grunt-newman automated test. And interesting thing is it does work with some others. Let me put it this way it works with some and doesn't work with others. But I found a method 'postman.getResponseHeader' inside the TestResponseHandler.js module that solved my problem. I couldn't work out what happened there. My question is why does it happen and which one is better to use. Thank you
----postman.getResponseHeader('S-custom-header')
----responseHeaders.hasOwnProperty('S-custom-header')

**Comment by abhijitkane** [comment]
Node and Chrome handle uppercase headers in XHR responses in different ways. 

According to the HTTP spec, Header names are case insensitive, and postman.getResponseHeader() handles this, and that's the one you should use.

We're in the process of updating our docs.
