### ISSUE TITLE
Newman error 401 while trying to pass Global variable from a Get Request and Pass as Header to another request

### ISSUE THREAD

**Issue by radhikanachiar** [postmanlabs/newman#1971]
1. Newman Version (can be found via `newman -v`):4.4.1
 2. OS details (type, version, and architecture): windows 10
 3. Are you using Newman as a library, or via the CLI? CLI ( VSTS pipeline )
 3. Did you encounter this recently, or has this bug always been there: bug always
 4. Expected behaviour: 
 5. Command / script used to run Newman:
run ./LocGET-V2-postman_collection.json -d ./apidata-1.csv -e ./MyWorkspace.postman_globals.json   -r html,cli,junit 
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by radhikanachiar** [comment]
Steps to reproduce the problem:

1. I created a GET request to get response of a authtoken. 
in my tests i stored my authtoken as below

**var authToken = responseBody;
postman.setGlobalVariable("authToken",authToken);**

2. Now i pass on my authtoken in all my subsequest test of GET request in header

3. I run my collection locally ( my first test is Get authtoken )  and this works

4. In newman i get 401 error for all my requests except for 1st on where 200 ok for Get authtoken.

I assume that in pipeline my previous Get response is not getting stored in authToken dynamically and subsequest request fails as no valid header data available.

Sample error in CI pipeline

Γûí APIGETValidation
Γöö APIGET-Withdata1
  GET https://mytestapi.net/apiname/v2/myid/?s={"sdata":["npm"]} [401 Unauthorized, 394B, 11ms]
 10. Error occured: AssertionError: expected response to have status code 200 but got 401


-

**Comment by DannyDainton** [comment]
Hey @radhikanachiar

Is the whole `response` body from your first request, the Auth token?

```
var authToken = responseBody;
postman.setGlobalVariable("authToken",authToken);
```

It suggests it is from the code you posted, is it not a `property` inside the response body?

What does `console.log(authToken)` give you?

**Comment by radhikanachiar** [comment]
Issue resolved

**Comment by akjain-mdsol** [comment]
Hi Danny,
I did some custom proxy in POSTMAN and manage a request where it is passing inside the POSTMAN like: 200 status code but same i export and ran into the NEWMAN so getting 401 unauthorized ...
why?

**Comment by LavanyaGolla** [comment]
> Issue resolved

I am having the same issue. Could you please tell me how it got resolved?

**Comment by LavanyaGolla** [comment]
@radhikanachiar
