### ISSUE TITLE
Test is failing when i run with newman, same test works fine in postman

### ISSUE THREAD

**Issue by arun290636** [postmanlabs/newman#1975]
Sample request :

POST : http://{{baseUrl}}/api/partners

Prescript 
 pm.globals.set("partnerId",'test'+Date.now());
var partnerId = pm.globals.get("partnerId");
var helpers = eval(pm.environment.get("loadHelpers"));
helpers.setUpPartnerData(partnerId, "test123");

Body
{{partner}}

Environment variables

partnerSchema = {"partnerId":"string","password":"string"}

loadHelper = function loadHelpers() {
    let helpers = {};
 
    helpers.setUpPartnerData = function verifyCount(partnerId, password) {
       var partner = JSON.parse(environment.partnerSchema);
       partner.partnerId = partnerId;
      partner.password = password;
      pm.globals.set("partner",JSON.stringify(partner));
    }
    return helpers;
} + '; loadHelpers();');

Above code works fine with postman but when i run with newman below error is thrown 
"SyntaxError in prerequest-script"

**Comment by arun290636** [comment]
eval is not supported by newman.

**Comment by arun290636** [comment]
@vikiCoder I did further investigation on this. Looks like eval() is not supported by newman. Let me know if you need more details on this.

**Comment by shamasis** [comment]
Newman and postman uses same code for scripts. Eval is supported alright. Can you try a simpler one liner stuff to double check?

Also, can you check if you’re using an older node version to run Newman. Can’t recall of the top of my head, but `let` isn’t supported below node v6 (I may be wrong about exact version)

**Comment by arun290636** [comment]
@shamasis thanks for your quick response. eval is working fine with simple code. Can you please try running below in preScript:

Steps:
Set environment variable manually 
testHelper = function loadHelpers() {
    let helpers = {};
    helpers.setUpPartnerData = function setUpPartner(partnerId, password) {
       var partner = {"partnerId":"string","password":"string"};
partner.partnerId=partnerId;
partner.password = password; 
pm.globals.set("partnerTest12",JSON.stringify(partner));
    }
return helpers;
}; loadHelpers();

in prescript add 
var testhelper = eval(pm.environment.get("testHelper"))
testhelper.setUpPartnerData("123we","tesrt123")

above script is working fine in postman but when i run with newman it fails with below error -
"TypeError in prerequest-script"

**Comment by DannyDainton** [comment]
Hey @arun290636 

I took a look at the code you posted and I did get an error in the console when running this with Newman but I made a small change to the function and then it seemed to work fine, with the global variable set with the data from the `testhelper.setUpPartnerData("123we","tesrt123")` statement.

I added this as an `environment` variable with the name `testHelper`:
```
function loadHelpers() {
    let helpers = {};
    helpers.setUpPartnerData = function setUpPartner(partnerId, password) {
        var partner = {"partnerId":"string","password":"string"};
        partner.partnerId = partnerId;
        partner.password  = password;
        pm.globals.set("partnerTest12", JSON.stringify(partner));
        
    }
    return helpers;
}; 
loadHelpers();
```

Added this to the `Pre-request Script`:

```
var testhelper = eval(pm.environment.get("testHelper"))

testhelper.setUpPartnerData("123we","tesrt123")
```

I exported the `globals` out to a file using the `--export-globals` flag
```
{
  "id": "8e51e4b7-04d9-4094-b5e6-cecdd218be1d",
  "values": [
    {
      "type": "any",
      "value": "{\"partnerId\":\"123we\",\"password\":\"tesrt123\"}",
      "key": "partnerTest12"
    }
  ],
  "name": "globals",
  "_postman_variable_scope": "globals",
  "_postman_exported_at": "2019-04-18T09:40:44.585Z",
  "_postman_exported_using": "Newman/4.4.1"
}
```

**Comment by arun290636** [comment]
@DannyDainton Thanks for your quick response. What did you change in the code?

**Comment by DannyDainton** [comment]
Basically just the `testHelper = ` part of the variable code. Have you tried it with the code I posted?

**Comment by arun290636** [comment]
@DannyDainton thanks for your response. above script worked fine but now i have another problem. I am unable to access global variable("partnerTest12") in next request when i run with newman , works fine with postman. your help will be appreciated.

**Comment by shamasis** [comment]
Closing issue.
