### ISSUE TITLE
How to write script for array

### ISSUE THREAD

**Issue by debjchak** [postmanlabs/newman#1976]
Newman Version:4.0.2,Postman Version:6.2.5
OS details (type, version, and architecture): Windows 10,64 bit production Imagev1.16.00.AO.B19
Newman via the CLI
Did you encounter this recently, or has this bug always been there: No bug,need suggestion
Expected behaviour: How to script for responses having arrays

I have a response which has an array(the Error bock). I want to provide validation for the "rejectionErrorCode": "MULTIPLE_UID". How do I do it?
For others my script works fine: 
//3-2_Happy Path_TC4_Status check
pm.test("Check Status", function () {
pm.expect(response.acknowledgement.status).to.eql("299");
});

Please find my response block below:
{
    "acknowledgement": {
        "messageHeader": {
        },
        "messageType": "x_x",
        "status": "299",
        "Errors": [
            [
                {
                    "rejectionErrorCode": "MULTIPLE_UID",
                }
            ]
        ]
    }

**Comment by shamasis** [comment]
Hey there. I suggest you post at community.getpostman.com to get this answered. There are great folks on the forum there who can point you to resources to read up on. 😊

**Comment by shamasis** [comment]
Oh and maybe this link would help. https://www.chaijs.com/plugins/chai-arrays/

Postman uses Chai assertion library. There are some cool syntaxes there. Plus postman sandbox documentation also has links to this.
