### ISSUE TITLE
no assertions reporter options not working

### ISSUE THREAD

**Issue by zekeoptimo** [postmanlabs/newman#1978]
1. Newman Version (can be found via `newman -v`): 4.4.1
 2. OS details (type, version, and architecture): Windows, but running under Ubuntu WSL
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: been around for a while I think ...
 4. Expected behaviour: assertions should not display
 5. Command / script used to run Newman: newman run test.postman_collection.json -e environment/postman_environment.json -g environment/local.postman_global.json --reporters cli --reporter-cli-no-assertions
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

We have an old Jenkins box that is using version 3.8.3 of newman and the --reporter-cli-no-assertions appears to be working fine there. However, locally I'm running the latest (4.4.1) and it does not work - assertions are still displayed. I also tried --reporter-cli-no-success-assertions and it did not work.

I tried to narrow it down to when the issue first started happening by installing different versions of newman and found that even version 3.9.4 does not work correctly, so this bug may have been around for a while. I did verify that locally version 3.8.3 works as expected, as I saw on the Jenkins box.

**Comment by DannyDainton** [comment]
Hey @zekeoptimo 

I'm running version 4.4.1 of the Newman on a Mac and it seems to the working for me:

*Using the `--reporter-cli-no-assertions` flag*:
<img width="1399" alt="Screenshot 2019-04-18 at 08 08 13" src="https://user-images.githubusercontent.com/17089546/56343022-83cf0900-61b1-11e9-984d-ff4664cbe4bb.png">

*Using the the cli reporter without any flags*:
<img width="1319" alt="Screenshot 2019-04-18 at 08 09 00" src="https://user-images.githubusercontent.com/17089546/56343004-774ab080-61b1-11e9-8eb7-af64aa33ae2d.png">

Do you have an image of the output that you're getting?

**Comment by zekeoptimo** [comment]
Ah I think I see now. It appears to me this behavior has changed then - in versions 3.8.3 it repressed the entire postman test display. To reproduce I did:

sudo npm uninstall -g newman
sudo npm install -g newman@3.8.3

Without the flag:
![image](https://user-images.githubusercontent.com/27833443/56382923-66a83380-61cd-11e9-9bbd-9b248bc25235.png)


With the flag:
![image](https://user-images.githubusercontent.com/27833443/56382969-85a6c580-61cd-11e9-841e-90ba0ee8e895.png)

Perhaps this was an intentional change - but it appears that previously this flag suppressed the entire test and instead just shows the summary and failures.

**Comment by codenirvana** [comment]
Closing as this is fixed in the latest version of Newman.
