### ISSUE TITLE
Iteration data not passing

### ISSUE THREAD

**Issue by kbryantkb** [postmanlabs/newman#1989]
1: Newman Version 4.4.1
2: OS Details Type Microsoft Windows 10 Pro, Version 10.0.17763, Build 17763
3: Using Newman as a library
4: encountered this issue yesterday
5: Expected Behavior
I wrote a command line collection runner. I am grabbing the collection and the environment using a URL and importing iteration data via CSV. and realized that I keep returning errors that I am not getting in postman. I decided to write the request and response data for each call into HTML report template and discovered that although the correct environment data is passing and the correct collection is being used, none of the iteration data is being passed into the sale request. If you look at the screenshots below, you will see in the html report that the amount value is 25.02, but the value of amount is passed in from a CSV with a variable name of {{amount}} and that none of the values from the are picked up, but the number of iterations do correlate with the number of rows in the CSV so I know I am sourcing the correct CSV. Whenever I run the same collection with the same data source in Postman Runner, I experience no problems. 

Here are some screenshots below. 

![ticket screenshot](https://user-images.githubusercontent.com/50109154/56985009-61e06980-6b55-11e9-9391-94d5fb97c9f6.PNG)

In the first screenshot you can see that the CSV is being used to pull data. The amount value is in the CSV and that the amount in the body of the request is set to {{amount}} 

![other ticket screenshot](https://user-images.githubusercontent.com/50109154/56985079-88060980-6b55-11e9-8760-0e962d272568.PNG)

In the second screenshot, you can see that the amount is actually 25.02. 

What can I do to get iteration data passed into the requests when I run the collection?

5: command script used to run newman: node command_line_runner

6: sample collection:

7: screenshots applied above

Steps to reproduce: 
1: created an API Key, 
2: created a get request to get the UID for the environment and collections
3: appended the Collection and environment UID to url as well as the apikey
4: sourced a csv file for data. 
5: add variables {{request.body}} and {{response.body}} to the reporter template
6: ran the command_line_runner.

**Comment by DannyDainton** [comment]
Hey, 

Not trying to steer you away from what you're doing but have you tried it with the `htmlextra` reporter? 

The standard reporter aggregates everything together, by design. I wanted to confirm that you are still having issues with an alternative reporter.

**Comment by kbryantkb** [comment]
I have not tried using an alternative reporter. Can you provide me some
more details about htmlextra?

**Comment by DannyDainton** [comment]
The full details can be found here:

https://www.npmjs.com/package/newman-reporter-htmlextra

**Comment by kbryantkb** [comment]
Hello @DannyDainton 

I ran the htmlextra report and although I have way more information about about each run. I was able to confirm that I am using the correct environment and the correct collection. I can tell that the iteration data is at least acknowledged in my request because the number of iterations correspond with the number of rows in the iteration data file, but I am still running into the issue of the iteration data not being passed into the request body. *(View Screenshot Below)*

![correct collection environment and iterations](https://user-images.githubusercontent.com/50109154/57018100-03b49480-6bf0-11e9-8641-866d3277e6ee.PNG)

Please observe the value amount which is set to {{amount}}. Amount is supposed to be pulled from the data file CSV and set as an environment variable. *(View Screenshot Below)*

![ticket screenshot r2](https://user-images.githubusercontent.com/50109154/57018012-a4ef1b00-6bef-11e9-9ca2-020b30e93906.PNG)

In the CSV the Amounts for each iteration is 35, 70, 57, and 85. This works perfectly fine in the Postman Collection Runner, but the amount consistently returns 25.02 for each iteration *(View Screenshot Below)*

![Amount still same](https://user-images.githubusercontent.com/50109154/57018074-eb447a00-6bef-11e9-9492-4ec7e7913402.PNG)

25.02 was a static amount that was set before I decided to replace the amount with variables. It is like it is cached some old version of the request. I have even tried setting the amount to different static amounts and 25.02 is still returned. This is the same for {{cvvNumb}} which is set in the prereq scripts to pull from the CSV file and save as an environment variable.

**Comment by DannyDainton** [comment]
Glad you got that reporter running and showing you something different. 

I did notice, from your image, that the POST body variables and the names in data file are slightly different from the CSV and JSON file heading/keys.

You have a mixture of upper and lowercase names in the 2 places. 

So `Amount` in the file and `amount` as the variable name.

**Comment by kbryantkb** [comment]
@DannyDainton 

That does not appear to be a problem and I did that on purpose as a way to differentiate between the name of the CSV headers and the environment variables pre-reqs below:

![prereqs](https://user-images.githubusercontent.com/50109154/57020544-9278df80-6bf7-11e9-88b7-7dc949606dc8.PNG)

**Comment by kbryantkb** [comment]
@DannyDainton 

Another thing to note is that for testing purposes, I changed the value of the Amount to 35 and still returned 25.02 when running the collection in newman. 

![35 25](https://user-images.githubusercontent.com/50109154/57020777-690c8380-6bf8-11e9-93ac-1413fb2e7a7d.PNG)

**Comment by DannyDainton** [comment]
That's good to know. 

That part of the setup information/image was missing from the original issue data so it was worth asking 😁

Another suggestion would be to use the `pm.*` API to get the Iteration data rather than using `.data`.

For example:

`pm.iterationData.get('Amount')`
pm.iterationData.get(variableName:String)

**Comment by DannyDainton** [comment]
You mentioned you're using a URL to get the data, are you updating that link after each time you've change something in the file?

This seems more like an environmental issue rather then a problem with Newman, in my opinion. 

I would be more than happy to discuss this over on our community site and get to the bottom of what's happening.

https://community.getpostman.com

**Comment by kbryantkb** [comment]
Im using a local path to get the data and using a url for the the collection and environments as you can see below: 

![collection runner ticket r2](https://user-images.githubusercontent.com/50109154/57021439-36fc2100-6bfa-11e9-8eba-34ab9c5d8121.PNG)

**Comment by kbryantkb** [comment]
the issue was not a newman issue but was more so a postman issue. This issue has been solved.

**Comment by Samuel-31** [comment]
Hi,

Can you give me details on how you solved the problem ? I am experiencing the same issues. The process works well with Collection runner but when I try with Newman I have the right number of iterations (=rows in csv files without the header) but the variables is not replaced by the row values

**Comment by kbryantkb** [comment]
@Samuel-31 

Please follow the link below. 

https://community.getpostman.com/t/iteration-data-not-passing/5238

The solution to my particular problem is there. Make sure that you are using the following API calls to get the Collection UID and the Enviroment UID

Environment: https://api.getpostman.com/environments
GET
Header: x-api-key: {{api_key}}

Collection: https://api.getpostman.com/collections
GET
Header: x-api-key: {{api_key}}

**Comment by Samuel-31** [comment]
Thanks for your fast answer but unfortunately I cannot solve my problem. I attach the copy of the collectionjson I exported from Postman (the id is the same as the one I got with the API call you told me)
and the csv file.
The line command I run is newman run maps.json -d city.csv

maps.json is the name of the collection json and city.csv the name of the csv
I can see the request is executed 5 times but with this URL : https://maps.googleapis.com/maps/api/geocode/json?address={{address}}&key=XXXXXXX which shows that the address variable is not changed.

I also tried by putting address as an environment variable and add -e env.json in the newman command line and the URL is executed 5 times with the initial value of address set in the the environment json.

![collectionjson](https://user-images.githubusercontent.com/51972690/59721906-a8337a00-9222-11e9-8ca3-6903a3d510e5.png)
![city](https://user-images.githubusercontent.com/51972690/59721921-b08bb500-9222-11e9-861a-266badb84ebc.PNG)

**Comment by kbryantkb** [comment]
I did not use an exported collection because I ran into the same problem. I
chose to link to my collection in postman and the environment in postman
and it worked for me. I'm out and about now, but as soon as I get back to
my computer, I can share my code with you that helped me solve the problem.

**Comment by Samuel-31** [comment]
That would be very nice because this problem is really making me mad^^

**Comment by Samuel-31** [comment]
Hi,

I finally could solve the problem, here is the solution that worked for me. I just had to save the .csv in another format (csv and not csv UTF-8 as it was by default) and the variable values were well replaced by newman :) But thanks again kbryantkb for you help

**Comment by svarshney2311** [comment]
> Im using a local path to get the data and using a url for the the collection and environments as you can see below:
> 
> ![collection runner ticket r2](https://user-images.githubusercontent.com/50109154/57021439-36fc2100-6bfa-11e9-8eba-34ab9c5d8121.PNG)
> 
> I'm also updating to pm.IterationData.get rather than data.

Hi, I just want to know what tool you are using to construct these folders. It looks awsome..like all in one folder.

**Comment by kbryantkb** [comment]
> > Im using a local path to get the data and using a url for the the collection and environments as you can see below:
> > ![collection runner ticket r2](https://user-images.githubusercontent.com/50109154/57021439-36fc2100-6bfa-11e9-8eba-34ab9c5d8121.PNG)
> > I'm also updating to pm.IterationData.get rather than data.
> 
> Hi, I just want to know what tool you are using to construct these folders. It looks awsome..like all in one folder.

No library, just being meticulous about organization. This is old code and I've since stored all of my environment and collection UIDs and paths to data on a json file and access my collections, environments, and data using json.

**Comment by svarshney2311** [comment]
> > > Im using a local path to get the data and using a url for the the collection and environments as you can see below:
> > > ![collection runner ticket r2](https://user-images.githubusercontent.com/50109154/57021439-36fc2100-6bfa-11e9-8eba-34ab9c5d8121.PNG)
> > > I'm also updating to pm.IterationData.get rather than data.
> > 
> > 
> > Hi, I just want to know what tool you are using to construct these folders. It looks awsome..like all in one folder.
> 
> No library, just being meticulous about organization. This is old code and I've since stored all of my environment and collection UIDs and paths to data on a module and access my collections, environments, and data by importing the module to my test scripts

What are you using for moduling. Can you run your scripts directly from your module set up?

**Comment by kbryantkb** [comment]
@sandermvanvliet 

![environements and keys](https://user-images.githubusercontent.com/50109154/87356413-04ed8b00-c530-11ea-8029-2deb0555b554.PNG)

**Comment by kbryantkb** [comment]
> > > > Im using a local path to get the data and using a url for the the collection and environments as you can see below:
> > > > ![collection runner ticket r2](https://user-images.githubusercontent.com/50109154/57021439-36fc2100-6bfa-11e9-8eba-34ab9c5d8121.PNG)
> > > > I'm also updating to pm.IterationData.get rather than data.
> > > 
> > > 
> > > Hi, I just want to know what tool you are using to construct these folders. It looks awsome..like all in one folder.
> > 
> > 
> > No library, just being meticulous about organization. This is old code and I've since stored all of my environment and collection UIDs and paths to data on a module and access my collections, environments, and data by importing the module to my test scripts
> 
> What are you using for moduling. Can you run your scripts directly from your module set up?

The modules are more or less used to pull in environments, collections, and test data, but I can run directly the above scripts.

I just use Node.js and Newman as the collection runner. 

I use the below endpoints to get the Collection and Environment UIDs

Environment: https://api.getpostman.com/environments
GET
Header: x-api-key: {{api_key}}

Collection: https://api.getpostman.com/collections
GET
Header: x-api-key: {{api_key}}

I store them in the module below as well as the reports and data paths. 

![image](https://user-images.githubusercontent.com/50109154/87358365-ab875b00-c533-11ea-886b-6d15367d4b47.png)

and one module is used to reference different collections, environments, data, and reports
