### ISSUE TITLE
Sugar Date utilities blowing up (again)?

### ISSUE THREAD

**Issue by sgilbane** [postmanlabs/newman#199]
I've got test code that looks like:
```javascript
var todaysDate = Date.create().format('{yyyy}-{MM}-{dd}');
tests["Todays date is " + todaysDate] = true;
```
and I get this error:
```
    EXCEPTION - TypeError: Object function Date() { [native code] } has no method 'create'
```

This may be a regression from https://github.com/a85/Newman/issues/176.

I am running Newman 1.2.14 on a MacOS.

**Comment by abhijitkane** [comment]
Doesn't seem like regression - #176 referred only to objects. Sugar doesn't add functions to Object.prototype.

This issue only seems to exist with the Date.create and Array.create methods. These are aliases for new Date() and [], and are not set up through Date.prototype and Array.prototype. We'll try to fix this soon.

Thanks for reporting this.

**Comment by sgilbane** [comment]
Great, thanks, Abhijit.  I can probably work around it for now by using "new Date()" and the "set" function.

**Comment by paulononaka** [comment]
+1! Thanks!

**Comment by czardoz** [comment]
This issue has been fixed in https://github.com/postmanlabs/newman/commit/24189b3b7f94242c8328cee3ba624fadb8b6df4d, and tests have been added in https://github.com/postmanlabs/newman/commit/1a5cde0908497757590448693b9c6c228e5fecd8 to ensure it does not recur.
