### ISSUE TITLE
Running test against individual requests instead of entire folder

### ISSUE THREAD

**Issue by arun-subramanian-1** [postmanlabs/newman#1990]
Posted the question in the postman forum but didn't get a response so far so asking the question here.

https://community.getpostman.com/t/run-test-on-a-particular-request-instead-of-all-requests-in-a-folder/5229

 1. Newman Version (4.4.1):
 2. OS details (OSX  10.13.6 ):
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: N/a
 4. Expected behaviour:
 5. Command / script used to run Newman: npx newman mycollection --data mydata --folder myfolder
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

Right now both postman test runner and newman CLI seems to run test on all requests in a folder. Is it possible to run tests against individual requests ? Or do I need to move these to its own subfolder (which works but additional level of access)

**Comment by shamasis** [comment]
It is currently not possible to select individual requests to run in a collection. Not sure if we would add that feature in short term for Newman. For Postman runner, there is some design level discussion going on around this. So, my best bet for you would be to ... as you suggested ... add sub folders.

**Comment by codenirvana** [comment]
You can use the `--folder` option to also specify the individual request name.
