### ISSUE TITLE
Newman return value is 134 when all tests pass

### ISSUE THREAD

**Issue by pavelsaman** [postmanlabs/newman#1992]
Hi,
I'm facing the following problem.

1. Newman Version (can be found via `newman -v`): 4.4.1
2. OS details (type, version, and architecture): Linux 4.19.0-parrot4-28t-amd64
3. Are you using Newman as a library, or via the CLI? CLI
3. Did you encounter this recently, or has this bug always been there: for me, always there, but haven't tried with a different Newman version. Tried only on Windows machine, where I don't encounter the same problem.

4. Expected behaviour: return value should be 0 if newman succeeds, that is when all tests pass, which is my example here

5. Command / script used to run Newman:
newman run test_collection

6. Sample collection, and auxiliary files (minus the sensitive details):
Sample test collection stripped down to minimum just to show the problem:
```
{
	"info": {
		"_postman_id": "45eecf8a-d15e-42f4-a226-c910ea30c91e",
		"name": "Test collection",
		"description": "Data entries length etc.",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "Simple request",
			"event": [
				{
					"listen": "test",
					"script": {
						"id": "757d142b-ce04-425d-925c-232325bae3b0",
						"exec": [
							""
						],
						"type": "text/javascript"
					}
				}
			],
			"request": {
				"auth": {
					"type": "noauth"
				},
				"method": "GET",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": ""
				},
				"url": {
					"raw": "https://holidayapi.pl/v1/holidays?country=CZ&year=2019&month=07",
					"protocol": "https",
					"host": [
						"holidayapi",
						"pl"
					],
					"path": [
						"v1",
						"holidays"
					],
					"query": [
						{
							"key": "country",
							"value": "CZ"
						},
						{
							"key": "year",
							"value": "2019"
						},
						{
							"key": "month",
							"value": "07"
						}
					]
				}
			},
			"response": []
		}
	],
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"id": "dc63b3e8-e0a3-4a89-a88f-f381f1415a52",
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		},
		{
			"listen": "test",
			"script": {
				"id": "8c51f085-6bb4-4705-adc5-d79a4cbcc8f2",
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		}
	],
	"variable": [
		{
			"id": "153148c5-69b5-4c4b-affc-17518df9b62a",
			"key": "category_name",
			"value": "\"1\"",
			"type": "string"
		},
		{
			"id": "56a942ca-a058-415a-93f0-fc0f05f0f401",
			"key": "is_shown",
			"value": "true",
			"type": "string"
		},
		{
			"id": "fbcb0e86-a3f2-463c-b447-ef8ba2c217b4",
			"key": "should_pass",
			"value": "false",
			"type": "string"
		},
		{
			"id": "54842344-89bc-42bc-9fb1-f6d680e1b501",
			"key": "expected_status",
			"value": "400",
			"type": "string"
		}
	]
}
```

I have no environment and no data in this simple example.

7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/24702416/57176719-960ca080-6e5b-11e9-9740-5bfc657cc695.png)

Steps to reproduce the problem:
1. save the collection and run it with this command:
newman run test_collection
2. run echo $?

Newman return value is 134 even though all tests have passed and newman itself haven't reported any other problems. Why is it not 0? When I try the same setting on Windows machine, command `echo %errorlevel%` returns 0.

**Comment by shamasis** [comment]
Yep. It should be 0. @postmanlabs/runtime

**Comment by arnitkun** [comment]
Hi! I tried to replicate the issue using the collection provided by you, but something didn't seem to work; I got a bad request.

Tried to replicate with a collection of my own: 
[Uploading demo.postman_collection.json.zip…](Sample Collection)
![Uploading Screenshot 2019-10-18 at 3.53.56 PM.png…](Run Result)

**Comment by arnitkun** [comment]
Hi!

I tried to replicate with the collection you provided but got a bad request, perhaps something is missing there.

Tried with my own simple collection.

<img width="822" alt="Screenshot 2019-10-18 at 4 47 13 PM" src="https://user-images.githubusercontent.com/15148735/67090134-f6ec2300-f1c6-11e9-8fb4-71e458f265c5.png">

[demo.postman_collection.json.zip](https://github.com/postmanlabs/newman/files/3743608/demo.postman_collection.json.zip)

**Comment by pavelsaman** [comment]
> I tried to replicate with the collection you provided but got a bad request, perhaps something is missing there.

I suppose you got 400 Bad Request.

And yes, you need a valid API key for the endpoint. It says so in the response:

```
"errors": {
        "api_key": [
            "The 'api_key' field is required!"
        ]
    }
```

**Comment by coditva** [comment]
@pavelsaman It seems that the newman command was aborted. I see "aborted" written just above the prompt. Error code `137` seems correct for this situation.

However, it's unclear why it was aborted. Is it still reproducible on your end or was it just a one-time?

**Comment by pavelsaman** [comment]
@coditva well, two things first:
- they actually changes the API a bit, I guess I didn't need any API key last time, otherwise I would've mentioned that
- I can't use the same machine with the same OS like I did before

So, on a x86_64 Manajro 18.1.5 with linux kernel 4.19.96-1 everything seems ok now:
![image](https://user-images.githubusercontent.com/24702416/72759195-3dda2200-3bd5-11ea-8bdb-a4bf8253b6ff.png)

**Comment by coditva** [comment]
Ok, so this seems like a one-time thing and it is not reproducible anymore, I'll go ahead and close this. We'll reopen this if you (or someone else) can reproduce this. :)
