### ISSUE TITLE
Any command to gracefully stop a collection run?

### ISSUE THREAD

**Issue by cainzhong** [postmanlabs/newman#1995]
We have a requirement to run a collection for a while, maybe 1 or 2 hours.
We have an idea that set '--iteration-count <number>' as a very big number, then the collection will not be stopped in 3 hours. So there is only one question, how to stop the collection gracefully.
Any command? or just 'Ctrl +C'. If we use 'Ctrl + C', does the report can be generated?

**Comment by codenirvana** [comment]
@cainzhong Report will not be generated if the execution is interrupted (`Ctrl + C`)
However, Newman run with large iteration count might end up cause this issue #935

For generating the report for an aborted execution depends on how the reporter is configured.
e.g, CLI reporter logs real time but JSON reporter writes to the file at the end of the run.

**Comment by shamasis** [comment]
Your best bet is to redirect output Newman CLI output to a file in command line. However, note that we are tracking an issue with Newman having very large iteration count. We do plan to address that some time on our mid-long term roadmap.
