### ISSUE TITLE
Newman-Issue reading data from response body and use them as variables

### ISSUE THREAD

**Issue by mverma-va** [postmanlabs/newman#200]
When I run the collection using newman, getting the error (see snapshot) that "Cannot read property 'xyz' of undefined'. The collection works fine from the Postman tool.
What I am trying to do in my collection that I read some data from the response body and use them as variables in further api calls. (Note that my api call takes nearly 30 seconds to return response)

var retData = JSON.parse(responseBody);
postman.setEnvironmentVariable("msid", retData.data.msid);

![screen shot 2015-03-27 at 2 28 48 pm](https://cloud.githubusercontent.com/assets/4573058/6876859/352035b0-d491-11e4-8704-609082d9a0b2.png)

**Comment by abhijitkane** [comment]
Can you put a `console.log(responseBody);` as the first line of your test script?

Since the request is returning a 400 response, the request isn't being sent correctly for some reason, and I doubt the response will contain the JSON you expect.

**Comment by mverma-va** [comment]
![screen shot 2015-03-30 at 10 09 37 am](https://cloud.githubusercontent.com/assets/4573058/6900624/0c408416-d6c5-11e4-837f-86b2f817a36b.png)

Thanks for replying, so I added the log and observed that it is asking for "pid" variable which I already have in my ENV file. And note that it is working fine from Postman UI.

Mverma-Mpro:postman-collections mverma$ less less PB_DEMO.postman_environment | grep -A 3 pid
less: No such file or directory
			"key": "pid",
			"value": "BAH",
			"type": "text",
			"name": "pid",
			"enabled": true
		},
		{
Mverma-Mpro:postman-collections mverma$ 
![screen shot 2015-03-30 at 10 15 09 am](https://cloud.githubusercontent.com/assets/4573058/6900724/b40ee44e-d6c5-11e4-9792-0dd25ea81911.png)

**Comment by mverma-va** [comment]
Also noticed with this other api endpoint, is it coz my form data is in raw format? See snapshot.
![screen shot 2015-03-30 at 11 23 32 am](https://cloud.githubusercontent.com/assets/4573058/6902169/5fef121c-d6cf-11e4-8369-6eb2e9123336.png)

Mverma-Mpro:postman-collections mverma$ newman -c Jetpacks_SM_Happy_Paths_V2.json.postman_collection -e SM_DEMO.postman_environment 

Iteration 1 of 1
{"message": "The following arguments are required: ['country', 'address', 'city', 'zip', 'companyName'].", "version": "2.0", "requestId": "5519860f00ff00ffebcb4a65a7520001737e736f636d6b74672d64656d6f0001617069733a3237312d6163636f756e742d67726f75702d766f626a65637400010103", "responseTime": 8, "statusCode": 400}
    EXCEPTION - TypeError: Cannot read property 'accountGroupId' of undefined
400 518ms V2 - External - CreateSite - Happy https://socmktg-demo.appspot.com/api/v2/account/create/?apiUser=

**Comment by abhijitkane** [comment]
Can you send the collection file to help@getpostman.com?

**Comment by mverma-va** [comment]
I have sent you an email with the collection file

**Comment by abhijitkane** [comment]
Can you try adding a "Content-Type: application/json" header in your Postman request? Chrome adds a content-type header, Node doesn't - which is why your server wasn't recognising your request data as JSON.

**Comment by mverma-va** [comment]
So instead of adding that line (I tried it did not work that way, maybe I added it at wrong place) I changed the "Text" to "JSON (application/json)" in postman UI it worked with newman. See snapshot.
![screen shot 2015-04-02 at 10 00 56 am](https://cloud.githubusercontent.com/assets/4573058/6967982/5447296a-d920-11e4-95c6-a0b0e7ffa1b5.png)

**Comment by mverma-va** [comment]
So if that is the only way, I will change all endpoints to select that and save them.

**Comment by mverma-va** [comment]
Thanks, you may close this issue now, as it is working after making that change you mentioned.

**Comment by dayerdl** [comment]
How can i solve this problem in the version 3.0? I cant the option application/json.

**Comment by abhijitkane** [comment]
If you have a POST or PUT request and select the raw mode in the Body tab, there's a dropdown to the right of the form/url-encoded/raw/binary selector. If you select JSON, a Content-Type: application/json header will be added.
![screen shot 2015-06-25 at 14 40 14](https://cloud.githubusercontent.com/assets/681190/8351072/23387ad0-1b48-11e5-8a7f-a3346e271830.png)
