### ISSUE TITLE
I am trying to hit download API through newman. The response of this API returns byte array. I want to write an excel file with this content. Response headers content-type is 'application/xlsx'. Is there any way in newman by which I can achieve this? 

### ISSUE THREAD

**Issue by nupur-ezops** [postmanlabs/newman#2010]
1. Newman Version (can be found via `newman -v`): 4.5.0
 2. OS details (type, version, and architecture): Windows
 3. Are you using Newman as a library, or via the CLI? : CLI
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman: 
 6. Sample collection, and auxiliary files (minus the sensitive details): 
 7. Screenshots (if applicable):

**Comment by codenirvana** [comment]
You can use Newman as a library to achieve this.
We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with issues like these.
