### ISSUE TITLE
Newman adds a question mark ("?") at the end of certain requests

### ISSUE THREAD

**Issue by xaviergm** [postmanlabs/newman#2012]
**General Information** 
1. Newman Version (can be found via `newman -v`):
 - 4.4.1

 2. OS details (type, version, and architecture):
 - Windows 10 Enterprise version 1809

 3. Are you using Newman as a library, or via the CLI?
 - CLI

 3. Did you encounter this recently, or has this bug always been there:
 - Unknown - Found it today (21st May 2019)

 4. Expected behaviour:
- The request URL is clean, without extra characters at the end, like when executed with Postman Collection Runner.

 5. Command / script used to run Newman:
 - newman run --insecure -d "PaginationTests - DEV - v1.0.csv" -e "DEV.postman_environment.json" "API - Pagination Tests.postman_collection.json"

 6. Sample collection, and auxiliary files (minus the sensitive details):
 - Collection    >>>   API - Pagination Tests.postman_collection.json
 - Environment   >>>   DEV.postman_environment.json
 - Data File   >>>   PaginationTests - DEV - v1.0.csv

 7. Screenshots (if applicable):
 - Screenshot 1   >>>   2019-05-21_17-59-39.jpg   >>>   CMD window showing added "?" at the end of the request, which makes the request successful (code 200) but results are empty as the server cannot interpret the parameter correctly.
 - Screenshots 2&3   >>>   2019-05-21_18-11-53.jpg & 2019-05-21_18-08-12.jpg   >>>   Same settings working perfectly in Postman Collection Runner

**Steps to reproduce the problem:**

1. Call Newman with the same data file, same environment and same collection as in postman collection runner. 

**Description of the issue:**
 - When exporting the above environment and collection from Postman and trying to run it in Newman, the latter adds a question mark at the end of the URL, making the server fail to understand the request:
> (base & resource paths omitted)/work_packages/?work_package_cd=4*?
     _as opposed to_
> (base & resource paths omitted)/work_packages/?work_package_cd=4*
 - This only happens with this collection.
 - I suspect two reasons: 
  -- The collection uses full URL replacement (the URL in the collection is just {{URL}} and it is passed on to Newman (and Postman) by the environment file and makes use of the data file.
  -- The parameter passed to the server includes an asterisk at the end ("*") for wildcarding.
 - The data file is, in essence, a collection of URLs with expected page size results to check against our pagination logic.
[Newman adds question mark 2019-05-21.zip](https://github.com/postmanlabs/newman/files/3203543/Newman.adds.question.mark.2019-05-21.zip)

**Comment by codenirvana** [comment]
Fixed in Newman v4.5.1
