### ISSUE TITLE
Need an option to set the timeout for requests

### ISSUE THREAD

**Issue by cluda** [postmanlabs/newman#202]
Need an option to set the timeout for requests. Perhaps a command-line option or an environment variable.

I am getting this error:
```
EXCEPTION - No response from URL
RequestError: ... terminated. Error: ETIMEDOUT
```

**Comment by mverma-va** [comment]
I am not sure if you are looking for these options:

https://github.com/postmanlabs/newman
Request options:
-y, --delay [number]            Specify a delay (in ms) between requests [number]
-r, --requestTimeout [number]   Specify a request timeout (in ms) for a request

**Comment by czardoz** [comment]
Closing this, as @mverma-va pointed out, there are command line flags for specifying the request timeout.
