### ISSUE TITLE
Collection level pre request scripts won't change the values of variables in newman

### ISSUE THREAD

**Issue by kobo98** [postmanlabs/newman#2021]
Hi,

I'm running my tests with postman and they pass fine, but when running them in newman I see that collection level pre-request scripts won't run as expected (they won't update variable values).
Then the test will fail because the variables that should have been populated by the collection level pre request script are still empty.

I use windows 10 with newman 3.6.0, here is my collection level pre request script:

```
pm.sendRequest({
    url: pm.variables.get("api_base") + "/sprint/active/" + pm.variables.get("project_id),
    }, function(err, res){
        pm.variables.set("sprint_id", res.json()[0].sprintId);
});

pm.sendRequest({
    url: pm.variables.get("api_base) + "/process/Sprints/" + pm.variables.get("sprint_id") + "/tasks",
    method: "GET",
},function(err, res){
    var tasks = res.json().map(task => task.taskid);
    pm.variables.set("tasks", tasks);
})
```

After a run with newman, I look at the list "variable" in the json exported and notice that all of the variables are still set on their defaults or empty.

I'm struggling with this problem for a few days already and would be happy to get your assistance.
Thanks.

**Comment by codenirvana** [comment]
Can you share a scaled-down collection which we can use to reproduce this issue?

**Comment by DannyDainton** [comment]
Hey @kobo98,

I'm going to close out this issue, we can open it back up if you're able to reproduce the issue using the latest version of Newman.
