### ISSUE TITLE
Add "files" to package.json

### ISSUE THREAD

**Issue by ZebraFlesh** [postmanlabs/newman#2026]
Using Newman 4.5.0, the eslint-plugin-node recommended ruleset flags `require('newman')` as an unpublished module because the package.json file lacks a [`files` attribute](https://docs.npmjs.com/files/package.json#files). This requires specific eslint configuration to allow newman to pass linting. This seems like unnecessary friction. Refer to the [node/no-unpublished-require rule](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unpublished-require.md) for additional information. This will also prevent future instances of #245.

**Comment by shamasis** [comment]
Feel free to send PR or use `allowModules` in that rule. We prevented #245 2 years back by creating test specs to check for the same. Note that Newman has a number of dependencies as well and it’s impossible to ask all dependencies do this. 

Additionally, postman-sandbox module uses dynamic require to facilitate loading modules within VM. And newman too has a dynamic require section to load reporters.

**Comment by Shivansh2407** [comment]
Please can you explain what needs to be done here @ZebraFlesh @kunagpal @shamasis ?

**Comment by ZebraFlesh** [comment]
Add a `files` key in package.json that lists the files which are included when the package is published.

**Comment by Shivansh2407** [comment]
What all files need to be added here @ZebraFlesh ??
{
  ...
  "files": [
    "bin",
    "lib",
    "index.js"
  ]
}
Like when I type this what all files should be there in the array?

**Comment by ZebraFlesh** [comment]
Any files that you want to include when the package is published need to go here. If it’s not listed, it won’t be published. See also [the npm docs](https://docs.npmjs.com/files/package.json#files).

**Comment by Shivansh2407** [comment]
I have tried to add all the files . Please have a look and Let me know @ZebraFlesh .

**Comment by IshaanDesai45** [comment]
I would like to work on the issue

**Comment by Shivansh2407** [comment]
@IshaanDesai45 Fixed it already 👍

**Comment by IshaanDesai45** [comment]
okay, is PR merged or are there any issues in the PR that I can Help with ??

**Comment by codenirvana** [comment]
This is fixed as part of Newman v5.
