### ISSUE TITLE
newman Invalid character

### ISSUE THREAD

**Issue by txrackack** [postmanlabs/newman#2029]
Version and environment information:

 1. Newman Version (4.5.0):
 2. OS details (Windows 10 Pro Version1903 Build 18362.175 64bit):
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Recently via TeamCity
 4. Expected behaviour: Using cmd with command newman -v or --version the version would be echoed to the screen
 5. Command / script used to run Newman: cmd 
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/34013498/59468056-c4848080-8df6-11e9-9fe5-c93ff0861fd0.png)

Steps to reproduce the problem:

1. Open command prompt (Administrative Mode or not)
2. Type newman -v and hit enter
3. Receive error from newman.js for Invalid character Line 1 Char 1 at the path designated in the environment path variable

**Comment by shamasis** [comment]
Can you try `npm i newman -g`? Install globally with node v6 and above installed. By the way, I’m not a 100% sure that this would fix your issue ... but windows scripting host should not be interpreting this in the first place.

**Comment by kannathasanE** [comment]
I am getting the same issue on my machine too. Could you please help me to resolve this

![Error new](https://user-images.githubusercontent.com/12726308/67741157-38d65e00-fa3e-11e9-99fb-1603294a652a.jpg)

**Comment by wt383** [comment]
did anyone find a solution? same error here.

**Comment by sowjanya547** [comment]
I can still see the error. Tried npm i newman -g and also installed older version and still not able to resolve.

**Comment by sowjanya547** [comment]
> I am getting the same issue on my machine too. Could you please help me to resolve this
> 
> ![Error new](https://user-images.githubusercontent.com/12726308/67741157-38d65e00-fa3e-11e9-99fb-1603294a652a.jpg)

were you able to fix this issue?

**Comment by wt383** [comment]
my version is 4.5.5

**Comment by codenirvana** [comment]
Is this issue still reproducible in Newman v5?

**Comment by wt383** [comment]
newman - v works on 5.1.0.

**Comment by shamasis** [comment]
Thanks for confirming that v5 and above solves this issue. Closing this issue.

**Comment by karnati1997** [comment]
> Version and environment information:
> 
> 1. Newman Version (4.5.0):
> 2. OS details (Windows 10 Pro Version1903 Build 18362.175 64bit):
> 3. Are you using Newman as a library, or via the CLI? CLI
> 4. Did you encounter this recently, or has this bug always been there: Recently via TeamCity
> 5. Expected behaviour: Using cmd with command newman -v or --version the version would be echoed to the screen
> 6. Command / script used to run Newman: cmd
> 7. Sample collection, and auxiliary files (minus the sensitive details):
> 8. Screenshots (if applicable):
>    ![image](https://user-images.githubusercontent.com/34013498/59468056-c4848080-8df6-11e9-9fe5-c93ff0861fd0.png)
> 
> Steps to reproduce the problem:
> 
> 1. Open command prompt (Administrative Mode or not)
> 2. Type newman -v and hit enter
> 3. Receive error from newman.js for Invalid character Line 1 Char 1 at the path designated in the environment path variable

i am also getting the same problem on how to resolve it.

**Comment by Gurparv** [comment]
I am getting the same issue on my windows machine. 
And I am using newman v5.3.0.

**Comment by shubhbhargav** [comment]
@karnati1997 Can you please let us know which newman version did you install? If you've installed an older version, we would recommend you to install the latest one i.e. v5.3.0

**Comment by shubhbhargav** [comment]
@Gurparv Did you install it globally? `npm i newman -g`

**Comment by Gurparv** [comment]
> @Gurparv Did you install it globally? `npm i newman -g`
@shubhbhargav  Yes, i tried both of the following commands. But the issue still persists.
1. `npm install -g newman`
2. `npm i newman -g`

**Comment by shubhbhargav** [comment]
Thanks for the info @Gurparv. Apologies for the delay here but can you please provide me with the following details as well?

- OS details
- Did the issue started happening with a fresh installation/update/upgrade? Was it working before?
- Node version

Trying to see if this is related to the underlying OS or node version in any way. I've a hypothesis that it might be related to the node version: https://stackoverflow.com/questions/28083379/running-sails-throwing-invalid-character-error

**Comment by Gurparv** [comment]
@shubhbhargav - This issue is resolved now. Please check the [issue](https://github.com/postmanlabs/newman/issues/2886)
Thanks.
