### ISSUE TITLE
Facing Issue with htmlextra report while generating Newman report Through Jenkins Pipeline 

### ISSUE THREAD

**Issue by bmakamsatyaprakash** [postmanlabs/newman#2037]
I am unable to get htmlextra report on jenkins pipeline.
I am trying to run collection on Jenkins using Newman with following commands and versions are given below. Please help get nice beautified HTML report which is getting generated when run through terminal and not on Jenkins Pipeline

Newman - 4.4.1
Node - v8.11.2
MAC os - Mojave - 10.14.5

jenkins file :

pipeline {
agent { label '' }
    parameters{
        string( name: "smokeTests", defaultValue: "", description: "to check the build" )
    }
    stages {
        stage ('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Test'){
            steps {
                sh 'npm install'
                sh 'npm install -S newman-reporter-htmlextra'
                sh 'newman run ComponentTests/Sprint1/PostmanDemo.postman_collection.json \
                -e ComponentTests/Sprint1/Postmandemo.postman_environment.json \
                -g globals/test.evn.json --reporters cli,htmlextra \
                --reporter-htmlextra-export "newman/HTML_report.html" --insecure'
                //archive (includes: '**.html')
      publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'newman', reportFiles: 'HTML_report.html', reportName: 'APIHTML Report', reportTitles: ''])

 
            }
        }
    }
}

**Comment by shamasis** [comment]
What’s not working and what errors do you see? Can you provide this information and also report the same at the issue tracker of the reporter?

**Comment by bmakamsatyaprakash** [comment]
This is how it is looking on Jenkins Pipeline
<img width="748" alt="Screen Shot 2019-06-20 at 3 54 52 pm" src="https://user-images.githubusercontent.com/36174879/59824303-15a2f000-9374-11e9-93ed-6eaf068b3dac.png">

**Comment by bmakamsatyaprakash** [comment]
on local this is how it should be shown 
<img width="1234" alt="Screen Shot 2019-06-20 at 3 56 11 pm" src="https://user-images.githubusercontent.com/36174879/59824348-31a69180-9374-11e9-9c0a-31f07a1a26a0.png">

**Comment by DannyDainton** [comment]
Similar question was asked and answered in a community post. 

You could try to use this method to resolve the problem? This is more of a Jenkins environment issue than an Newman/reporter one. 

https://community.getpostman.com/t/newman-htmlextra-reporter-not-displaying-correctly-when-viewed-from-jenkins/5735/2

**Comment by bmakamsatyaprakash** [comment]
Thanks for quick turnaround .
I really appreciate if you could look into this and help me.

I am not very clear on the approach you have mentioned . Please let me know more specific steps on what i should be doing to get proper HTML report on Jenkins Pipeline.
As per the link below , i tried running : System.setProperty( ‘hudson.model.DirectoryBrowserSupport.CSP’ ,’’ ) this command on console (MAC terminal) which throws error. I don’t see any console on Jenkins > CONFIGURATION

https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy

**Comment by bmakamsatyaprakash** [comment]
@petrrheckoHims,
Really appreciate your help.. It worked  :) !!!
Running this on terminal as per your details worked perfectly fine giving me nice reports.

java -Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-same-origin allow-scripts; default-src 'self'; script-src 'unsafe-eval' *; img-src *; style-src 'unsafe-inline' *; font-src *;" -jar jenkins.war --httpPort=8082

**Comment by zafaque** [comment]
Hey @bmakamsatyaprakash what you have run on the terminal which fix the html report

I tried running this `java -Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-same-origin allow-scripts; default-src 'self'; script-src 'unsafe-eval' *; img-src *; style-src 'unsafe-inline' *; font-src *;" -jar jenkins.war --httpPort=8082` but throwing error `Error: Unable to access jarfile jenkins.war`

**Comment by Ksingh22** [comment]
go to Jenkins console and run this System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "")

PS: It has potentially security risk
