### ISSUE TITLE
Just parse the postman script

### ISSUE THREAD

**Issue by sanxun0325** [postmanlabs/newman#2041]
If I want Newman to help me analyze the postman's script, I just want to analyze the result, can I do that

**Comment by shamasis** [comment]
You can. But it depends on your use case. I think if you elaborate your use case and post it at community.getpostman.com ... you’ll get a lot of eyeballs. This issue tracker is limited to only tracking bugs and features of Newman.

**Comment by shamasis** [comment]
Even I’m very interested to know more. So, once you post this in the community, do let me know the link to your post. ❤️❤️
