### ISSUE TITLE
getResponseHeader() not working with newman(v4)

### ISSUE THREAD

**Issue by kavithasub** [postmanlabs/newman#2047]
'postman.getResponseHeader("header_name")' not working with newman but working fine in postman native app.

 1. Newman Version : 
$ newman -v
4.5.1
$ npm -v
6.9.0
$ node -v
v12.4.0
 2. OS details (type, version, and architecture): Ubuntu 16.04
 3. Are you using Newman as a library, or via the CLI? CLI
 4. Command / script used to run Newman: newman run collection_name -e environment_name -r cli
 5. Sample collection, and auxiliary files (minus the sensitive details):

Sample collection has only one request(GET) which would return a Location header in the response headers with redirect uri value. In the 'test' I'm trying to set variable using the header value as below
```
pm.environment.set("location_header", postman.getResponseHeader("Location"));
var str =  pm.environment.get("location_header");
console.log(`location_header ==  ${str}`);
```
This actually working fine in postman native app(logged Location header value(uri)), but newman returns 'undefined' always.

I could see a related issue reported in : https://github.com/postmanlabs/newman/issues/398#issuecomment-221796658
but seems no proper solution given.

**Comment by DannyDainton** [comment]
Hey @kavithasub,

Can you see if `pm.response.headers.get('Location')` works please?

**Comment by kavithasub** [comment]
Hi @DannyDainton , Thank you for prompt response. Unfortunately still same issue when using like
```
var loc = pm.response.headers.get('Location');
console.log(`new location ==  ${loc}`);
```
![sam](https://user-images.githubusercontent.com/15671620/60257774-996b5800-98f1-11e9-82b1-6052ef71b331.jpeg)

**Comment by DannyDainton** [comment]
Have you tried to log all the headers to confirm that the `Location` header is actually part of that final response?

You could use this to list all the `keys`:
`console.log(_.keys(pm.response.headers.toObject()))` 

You could also confirm this by using a different reporter with Newman which displays all the information, including the headers, in the final output. 

I know that this one includes that :)

https://www.npmjs.com/package/newman-reporter-htmlextra

**Comment by kavithasub** [comment]
Seems logging response headers by postman native app and newman are different. Please see the below image, and there from newman missing location header and showing additional headers also.
newman-cli vs postman-console
![diff](https://user-images.githubusercontent.com/15671620/60316538-92435900-9988-11e9-8eb4-38e9c7a4dc89.jpeg)

**Comment by kavithasub** [comment]
I understand the issue now, as my request was redirecting always at newman runs, it was not giving Location header in the response but postman app did(according to settings).
Now, I'm able to log the Location header by runs with --ignore-redirects option. 
Hence closing the issue. Thanks :)
