### ISSUE TITLE
Using newman running Postman oAuth1 helper, returned ReferenceError

### ISSUE THREAD

**Issue by uscyaodi** [postmanlabs/newman#205]
After using the Postman oAuth 1.0 helper to create the request and running it successfully through Postman, I used the newman to run this collection. However, while newman dealing the Postman oAuth1 helper with the HelperProcessor.js, it returned the ReferenceError on line 453:
```
var index = _.indexOf(oauthParams, params[i].key);
```
I am not an expert of the JavaScript, but the "_" is definitely not defined through the code and maybe someone missing the name of this parameter?
Please review this issue and give me feedback at your earliest convenience.

**Comment by abhijitkane** [comment]
Thanks for pointing this out. We'll push a fix for this soon.
