### ISSUE TITLE
Improve the statistics counter of requests so that they count as an error those that return an error code http

### ISSUE THREAD

**Issue by alkep** [postmanlabs/newman#2051]
1. Newman Version (can be found via `newman -v`): **4.5.1**
 2. OS details (type, version, and architecture): **Windows 10**
 3. Are you using Newman as a library, or via the CLI? **Library**
 3. Did you encounter this recently, or has this bug always been there: **Recent**
 4. Expected behaviour:  **Request that return error code >=400 should be considered failed in counters stats.**
 

I have change the file lib/run/summary.js

![image](https://user-images.githubusercontent.com/52447698/60502733-a3f56b00-9cbe-11e9-911b-1deacd32de5d.png)

new code:

            emitter.on(name, function (err, o) {
                // check pending so that, it does not negate for items that do not have a `before` counterpart
                if (err || (name == 'request' && o.response && (o.response.code < 200 || o.response.code >= 400))) {
                    tracker.failed += 1;
                }
                tracker.pending && (tracker.pending -= 1);
                tracker.total += 1;
            });

**Comment by shamasis** [comment]
I'm afraid that this is not a generic use case and is subjective. I suggest you clone/copy the CLI reporter, add this logic and use as part of the custom reporter functionality. Perhaps, others will find that useful too.

**Comment by alkep** [comment]
Hi Shamasis, Thanks for your answer.
I think i didn’t explain correctly or there is another way to get the failed requests. 
When you are testing a project is necessary to know how many request return an error.
May be you can tell me if exist that counter.
Thank you.

**Comment by shamasis** [comment]
Ok. If I assumed correctly, you are trying to fail tests when any request return a non 2xx response code. For that you’d need to write tests. Maybe read this blog post https://blog.getpostman.com/2017/10/25/writing-tests-in-postman/ to know more. 

A non 2xx response code is not an error for all APIs. As such, Newman cannot assume that. If you write tests then Newman can show test failure results. I hope I could explain. Also, try posting your questions to community.getpostman.com to get more people to see and answer your questions.

**Comment by alkep** [comment]
Thank you. I will change all my test boxes. Until now i used test  boxes
only for saving environment variables.
Next time i will post questions on postman community.

Nice regards
