### ISSUE TITLE
How to Run multiple newman command in single Docker and single container

### ISSUE THREAD

**Issue by josephthanaraja** [postmanlabs/newman#2054]
Hello I have three different collections (GET and POST) and wanted to run multiple newman commands in Single Docker container but it is not working. If I create three container it is working fine. Is it possible to use one container and use three newman run command?.

Working one(two docker with two newman separately):-
docker run ---name uatpostman1 postman/newman:ubuntu run collection1.json -d collectionData1.json -r cli,junit,htmlextra --reporter-htmlextra-export /var/newman/collection2.html
docker run ---name uatpostman2 postman/newman:ubuntu run collection2.json -d collectionData2.json -r cli,junit,htmlextra --reporter-htmlextra-export /var/newman/collection2.html

Expected one(One Docker with 2 Newman run):-
docker run ---name uatpostman postman/newman:ubuntu run collection1.json -d collectionData1.json -r cli,junit,htmlextra --reporter-htmlextra-export /var/newman/collection1.html postman/newman:ubuntu run collection2.json -d collectionData1.json -r cli,junit,htmlextra --reporter-htmlextra-export /var/newman/collection2.html

Please help

**Comment by josephthanaraja** [comment]
Could you please check and update. I wanted to run multiple collections in single Docker container rather than creating an individual container for each collections. Appreciate your help

**Comment by jordanst3wart** [comment]
Maybe:
```
docker run ---name uatpostman postman/newman:ubuntu run collection1.json -d collectionData1.json -r cli,junit,htmlextra --reporter-htmlextra-export /var/newman/collection1.html && newman run collection2.json -d collectionData1.json -r cli,junit,htmlextra --reporter-htmlextra-export /var/newman/collection2.html
```

This is problem with your knowledge of docker, and not a problem with newman. Maybe ask on stackoverflow.

**Comment by codenirvana** [comment]
Closing as per https://github.com/postmanlabs/newman/issues/2054#issuecomment-532486958

**Comment by AmanKamboj12** [comment]
Hello all did we get any resolution for this ?
How we can update docker-compose file to run multiple collections ?
