### ISSUE TITLE
Export Environment Variable not exporting on('done')

### ISSUE THREAD

**Issue by jdm-hexagon** [postmanlabs/newman#2059]
1. Newman Version (can be found via `newman -v`): 4.4.0
 2. OS details (type, version, and architecture): mac OS 10.14.3
 3. Are you using Newman as a library, or via the CLI? Library, Node 10.16.0
 3. Did you encounter this recently, or has this bug always been there: always
 4. Expected behaviour: Variable should be written to file on done 
 
I've seen a [few issues here](https://github.com/postmanlabs/newman/issues/831#issuecomment-367339649) with variables not being exported. I'm using the solution suggested to write out a variable from a login post which set the variable. Once this is done I loop over an array of collections that read in the same variables.

The weird thing is, if I comment out the `collectionRunner()` call out of the `.on('done', (err, summary) => {}` the global and env variable get written out properly. When I add `collectionRunner()` back in, the files don't update. Here's my code:

	#!/usr/bin/env node
	const newman = require('newman');
	const { readdirSync, writeFile } = require('fs');
	
	// Read in all the *.collections.json files that newman will run
	const collectionsDir = readdirSync('./collections');
	const collections = collectionsDir.filter((json) => json.match(/.*collection\.json$/));
	
	function collectionRunner() {
		for (let collection of collections) {
			const collectionPath = require(`./collections/${collection}`);
			newman.run({
				collection: collectionPath.collection,
				iterationData: `./collections/${collection.replace(/\.collection\.json$/,'')}.data.json`,
				globals: require('./env/globals.json'),
				environment: require('./env/localhost.postman_environment.json'),
				reporters: 'cli',
			}).on('start', function (err, args) { // on start of run, log to console
				console.log('running a collection...')
			}).on('done', function (err, summary) {
				if (err || summary.error) {
					console.error('collection run encountered an error.')
				}
				else {
					console.log('collection run completed.')
				}
			})
		}
	}
	
	// Run the User Collection first to set *x-device-auth*
	// On success, run the rest of the collections
	newman.run({
		collection: require('./templates/users.postman_collection'),
		globals: require('./env/globals.json'),
		environment: require('./env/localhost.postman_environment.json'),
		exportGlobals: './env/globals.json',
		exportEnvironment: './env/localhost.postman_environment.json',
		reporters: 'cli',
	})
	.on('done', (err, summary) => {
		if (err || summary.error) {
			console.error('collection run encountered an error.');
			console.error(summary.error);
			console.error(err)
		}
		collectionRunner()
	});

**Comment by DannyDainton** [comment]
Hey @jdm-hexagon 

Is this an issue that you're still facing?

**Comment by jdm-hexagon** [comment]
@DannyDainton, thanks for the followup. It's no longer an issue, though I was never able to resolve it. Instead of running a seperate collection for the user auth, then running the rest of the collections. I injected the user auth method into every collection so they are all handled independently.
