### ISSUE TITLE
npm installation error: Could not load the Visual C++ component "VCBuild.exe"

### ISSUE THREAD

**Issue by crazy4groovy** [postmanlabs/newman#206]
on `npm install -g newman`

First I installed python, because it was required.

Now I get that error message... No way I'm installing: "To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005"

**Comment by josephyanks** [comment]
I too am getting this error, but it is telling me to install visual studio 2010 build tools. 

Once I did that, it's now telling me that I'm missing winsock.h

Any idea what actual dependencies a build server would need to install newman properly?

**Comment by NeilCross** [comment]
I've forked the repo to remove the dependency on domjs by rolling back to jsdom-nogyp.  I'd decided that, on my CI machines, running an older version of node (required for jsdom-nogyp) was less of an problem than requiring a VS install.

Repo is here: https://github.com/NeilCross/Newman-nogyp

I'm not currently planning on releasing it in npm (newman-nogyp anyone?) but will keep it up to date with Newman development while the tests keep passing. Installation instructions are at the top of the readme.

**Comment by czardoz** [comment]
We've released Newman v2.0 Beta, which does not require compilation of any packages. It only supports Node v4.0+ though. Checkout the [readme](https://github.com/postmanlabs/newman/) for details and installation instructions.
