### ISSUE TITLE
New Feature Request- Send Reporter result as REST, not write to file.

### ISSUE THREAD

**Issue by luddskunk** [postmanlabs/newman#2065]
Version and environment information:

 1. Newman Version (can be found via `newman -v`): ^4.5.1
 2. OS details (type, version, and architecture): Windows 10, v 1809
 3. Are you using Newman as a library, or via the CLI? Library
 3. Did you encounter this recently, or has this bug always been there: Recently
 4. Expected behaviour: Be able to send Reporter output as REST response.
 5. Command / script used to run Newman: - 

Hi,

I want to use Newman with Node.js and setup an API in the cloud (Azure Function) which will trigger newman with given URLs to Collection and Environments. Then send back the result (Preferably as JUnit) directly. I don’t want to write to file, then open file and send content. I would like to have this feature, as it seems that it is not possible at the moment.

This would enable me to have a “newman API” which will run collections in different regions in the world, which would help me test my different services which then would integrate smoothly in my CI / CD pipelines.

Thanks in advance for any help or feedback regarding this.

Reference: https://community.getpostman.com/t/newman-send-reporter-result-as-rest-not-write-to-file-possible/6655

**Comment by adityaofficial10** [comment]
@luddskunk 
You basically want the result to be returned in the callback rather than having to read the report.
Right?

**Comment by luddskunk** [comment]
@adityaofficial10 Yes, that would be adequate.

**Comment by adityaofficial10** [comment]
@luddskunk 
Ok I am moving ahead with this and I'll try to find a fix without disturbing the workflow.

**Comment by shamasis** [comment]
I see how you'll need this. 😊

This is not within the scope of Newman and will conflict with certain upcoming product features.

The ideal way is to build and release a separate reporter to achieve this - maybe `newman-reporter-upload`.

**Comment by adityaofficial10** [comment]
@shamasis 
Fully agreed.
I concluded the same after going through the codeflow.

**Comment by asdf23** [comment]
Sorry to somewhat hijack this thread.. I'd like to append to the report a bunch of unrelated things from other non-newman tests. I suppose I could grab the contents over http then add-to as desired. I was hoping that there would be a library way to append content to a html report.

**Comment by adityaofficial10** [comment]
@asdf23 
Can you just elaborate a little bit on that??

**Comment by asdf23** [comment]
I have an elaborate test script that includes things outside of postman's domain, What I want is a single report with the other stuff.  I'm not exactly sure if the two object would align well.

As a test in beforeDone I pushed a clone of the 2nd paramenter's args.summary.run.failures object.

`args.summary.run.failures.add(  args.summary.run.failures[0] ... )`

That worked, it's pretty hacky though

That seems to work, so now I can add a

**Comment by asdf23** [comment]
Actually I take that back, beforeDone seems to have a 1 second window of being able to inject test results
