### ISSUE TITLE
Vulnerabilities in your dependencies: Lodash - Prototype Pollution

### ISSUE THREAD

**Issue by Pixcell** [postmanlabs/newman#2066]
1. Newman Version (can be found via `newman -v`): 4.5.1
 2. OS details (type, version, and architecture): macOSX 64bit
 3. Are you using Newman as a library, or via the CLI?: library
 3. Did you encounter this recently, or has this bug always been there: recent npm audit
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

Steps to reproduce the problem:

1. npm install newman
2. npm audit

![image](https://user-images.githubusercontent.com/4005291/61671688-d550dc00-ad3c-11e9-86fc-6a0af83c3233.png)

**Comment by ipmsteven** [comment]
The change is merged in develop branch [here](https://github.com/postmanlabs/newman/commit/32e69ea335f2087c3698d62e4e3b327186f957d0) but just not released yet

**Comment by ZebraFlesh** [comment]
What is preventing this security fix from being released?

**Comment by codenirvana** [comment]
Fixed in Newman `v4.5.3`.
