### ISSUE TITLE
Document all events (and their args) emitted by the `newman` lib

### ISSUE THREAD

**Issue by kaustavdm** [postmanlabs/newman#2069]
Currently, there is only a list of events documented for newman in the [README.md](https://github.com/postmanlabs/newman#newmanrunevents). These events need to be documented as:

## event name

Event Description

args           |   description
-----------|--------------------
`opts`       | This is an option
`opts.foo` | A property of the `opts` object

**Comment by malvikach** [comment]
Documentation can be found [here](https://github.com/postmanlabs/newman/wiki/Newman-Run-Events)
