### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by sbutalia** [postmanlabs/newman#207]
Getting the following error:    EXCEPTION - SyntaxError: Unexpected token

console.log(responseBody) outputs this:
�_U�e�O
       �0��ʯ�Ö�Ԡ��Q�`�%B���T�軧����>��F,
���zh��Bx����z�`�,��`$�lJۆ���aQ�&V9���m\�6�m#
R�7����`�T�eDq���Me���JS.�
    EXCEPTION - SyntaxError: Unexpected token

![image](https://cloud.githubusercontent.com/assets/1808387/7778355/459a8ad4-007f-11e5-97e7-b04cb1d1342a.png)

I see a valid JSON output in postman
![image](https://cloud.githubusercontent.com/assets/1808387/7778369/632ba01a-007f-11e5-9d7b-b87f312c4e2b.png)

my Header:
![image](https://cloud.githubusercontent.com/assets/1808387/7778375/7601d1a0-007f-11e5-9f26-b8bb744b3d08.png)

**Comment by abhijitkane** [comment]
Can you try playing around with the -N option?

`'-N, --encoding [encoding-type]', 'Specify an encoding for the response. Supported values are ascii,utf8,utf16le,ucs2,base64,binary,hex'`

**Comment by sbutalia** [comment]
Tried all with no luck.. 

Think it has something to do with gzip?
        response = Response(r)
        response.headers['Access-Control-Allow-Origin'] = 'http://127.0.0.1:3000'
        response.headers['Content-Encoding'] = 'gzip'
        response.headers['Content-type'] = 'application/json; charset=utf-8'
        response.headers['Access-Control-Allow-Credentials'] = 'true'

**Comment by wbrooks1981** [comment]
I am seeing this as well.  If the content-encoding is present in the response and its gzip  then the encoded value is what is put into the responseBody.   This in turns runs into syntax errors when trying to do something with the responseBody ie.  JSON.parse(responseBody).    I also attempted to use the -N options with no success.     The question is,  is newman supposed to decode gzip or can it?

**Comment by gadelkareem** [comment]
also here ```EXCEPTION - SyntaxError: Unexpected token Y``` after last update

**Comment by gadelkareem** [comment]
I found out that it was wrong response on Vagrant machine caused by IP blocking on my code. I guess the exception was caused by the test script on the first call as it did not return proper JSON. 

I confirm it is not a bug but the error message could be improved I suppose by catching the response parse error.

Thanks for great work!

**Comment by czardoz** [comment]
@wbrooks1981 can you open a new issue with more details if you're still facing this problem?
