### ISSUE TITLE
Collecttions should be enable to move to another!

### ISSUE THREAD

**Issue by alonelyleaf** [postmanlabs/newman#2070]
I have built some collections before, now I want to organize them, but these collections are not enable to move, it is terrible！

**Comment by coditva** [comment]
@alonelyleaf Sorry to hear about that! Can you elaborate what you're trying to do and what is your expected behaviour?

**Comment by alonelyleaf** [comment]
I am sorry to answer you today. Because I didn't have a good plan, I built many collections. Now, I want to clean up them, but I can't move them to a collections. So, can you add this feature for the next version?

**Comment by coditva** [comment]
@alonelyleaf Do you want to have collections inside another collection? You can create `Folders` inside collections and put `Requests` inside these folders. Please correct me if I misunderstood?

**Comment by alonelyleaf** [comment]
Thanks! At the beginning, I want to move a collections to another. As you said, I can create a folder in another collection, and then I can move the requests to this folder. it really resolves my  problem.

It's a little bit of tedious for moving the requests one by one , but it works. Thank you very much!
