### ISSUE TITLE
jsdom 4.x onward only works on io.js, not Node.js

### ISSUE THREAD

**Issue by jojoblaze** [postmanlabs/newman#208]
After just calling newman I get this error: `jsdom 4.x onward only works on io.js, not Node.js`.

I'm working on a Windows machine. I installed "newman": "1.2.12" cause I got some trouble with the latest version. I know this is a known issue at the moment.
Before newman@1.2.12 I installed 1.2.9 version wich gave me another problem related with jsdom. Upgrading to 1.2.12 only shift the problem.
I have node 0.12.2 and npm 2.7.4.

**Comment by abhijitkane** [comment]
Newman 1.2.10 had the older version of jsdom. Can you try with that?

**Comment by jojoblaze** [comment]
Even with 1.2.10 I got the same error.

**Comment by czardoz** [comment]
@jojoblaze you can install Newman Beta (check the [readme](https://github.com/postmanlabs/newman/) for details). Newman Beta supports node v4.0+ and newer versions of jsdom.
