### ISSUE TITLE
Since 4.5.2 form data parameters are missing when using pm.sendrequest() (works in 4.5.1)

### ISSUE THREAD

**Issue by danshoubs** [postmanlabs/newman#2081]
1. 4.5.3
 2. [Windows 2019 with VS2019](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md)
 3. CLI - via Azure DevOps Task
 4. Since version 4.5.2 (exists in 4.5.3 as well) we get the following error: 'Token or expiry date are missing'

The token or expiry date error is from our SSO because it failed the login request:
```
{ error: 'invalid_request',
2019-08-07T11:32:43.9587594Z   │   error_description:
2019-08-07T11:32:43.9587734Z   │    'AADB2C90083: The request is missing required param
2019-08-07T11:32:43.9587892Z   │ eter: grant_type.\r\nCorrelation ID: a0befe50-8e68-451
2019-08-07T11:32:43.9588043Z   │ 0-991c-b63071847775\r\nTimestamp: 2019-08-07 11:32:43Z
2019-08-07T11:32:43.9588140Z   │ \r\n' }
```
It would seem the parameter isn't being sent correctly to the token endpoint.

 5. In version 4.5.1 we had no issues, since 4.5.2 our collection will no longer run 
we have work around this by explicitly using the version when installing: `npm.cmd install newman@4.5.1 -g`
 6. Command / script used to run Newman:
`newman.cmd run D:\a\r1\a\_projnamehere-CI\drop\postman\projnamehere.E2E-Test.postman_collection.json --reporter-junit-export D:\a\r1\a\_projnamehere-CI\drop\postman -r "cli,junit" -n 1 --global-var "username=***" --global-var "password=***" --global-var "clientid=removed" -e D:\a\r1\a\_projnamehere-CI\drop\postman\projnamehere.E2E-Test.postman_environment.json`

 7. Sample collection, and auxiliary files (minus the sensitive details): attached
[projName.E2E-Test.postman_collection.json.txt](https://github.com/postmanlabs/newman/files/3476868/projName.E2E-Test.postman_collection.json.txt)
[projName.E2E-Test.postman_environment.json.txt](https://github.com/postmanlabs/newman/files/3476869/projName.E2E-Test.postman_environment.json.txt)

 8. Screenshots (if applicable): Logs attached 
[newman_task.log.txt](https://github.com/postmanlabs/newman/files/3476852/newman_task.log.txt)

**Comment by codenirvana** [comment]
@danshoubs Can you check if removing `header: 'Content-Type:application/json',` key from the `sendRequest` payload fixes this issue.

@jdholbrook81 Can you share a scaled-down collection which we can you to reproduce the issue?

**Comment by gdekeuster** [comment]
I had the same issue. Since the upgrade to Newman 4.5.3 POST requests were failing.
In Postman there was no issue.
Removing the Content-Type header fixed the issue. The POST request is running fine again in Newman 4.5.3

**Comment by danshoubs** [comment]
@codenirvana I disabled the header in the collection, but the issue is still present.

```
				"header": [
					{
						"key": "Content-Type",
						"name": "Content-Type",
						"value": "application/json",
						"type": "text",
						"disabled": true
					},
```

**Comment by codenirvana** [comment]
@gdekeuster Thanks for the confirmation.
Since v4.5.2, we don't force override  `Content-Type` header for the form-data request body.

@danshoubs Looks like you disabled the request level headers only. Also remove/comment the `header` key in `echoPostRequest` object (sendRequest options).

**Comment by danshoubs** [comment]
@codenirvana can confirm that removing the `header` key in `echoPostRequest` object works.
To do this, I edited the collection file. What do I have to do so the change persists when I export the collection from postman?

**Comment by codenirvana** [comment]
@danshoubs You can remove/disable the `Content-Type` header and update (remove the header key) the Pre-request Script before exporting the collection.

Note: Save the updated request before exporting.
