### ISSUE TITLE
Tests fail when sending grant_type on v.4.5.3, despite they pass on other versions

### ISSUE THREAD

**Issue by kkliuiev** [postmanlabs/newman#2084]
1. Newman Version (can be found via `newman -v`): 4.5.3
 2. OS details (type, version, and architecture): macOS 10.14
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: reproduced only on 4.5.3
 4. Expected behaviour: tests pass just like on other Newman versions
 5. Command / script used to run Newman: Newman run ...json -e ....json
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

Steps:
1. run collection containing tests with grant_type in authorization request
2. observe tests log

**Comment by codenirvana** [comment]
@kkliuiev Can you share a scaled-down collection which we can use to reproduce this issue?

Possibly duplicate of #2081

**Comment by kkliuiev** [comment]
sorry, I cannot due to privacy, I'll try to make with some public

**Comment by virgesmith** [comment]
I have what I assume to be the same problem, all my tests fail on v4.5.2 and v.4.5.3, reverting back to 4.5.1 and they work fine again. The first test gets an Azure AD token, which fails, and all subsequent tests require the token so also fail

Excerpt from test:
```
"request": {
"auth": {
	"type": "noauth"
},
"method": "POST",
"header": [
	{
		"key": "Content-Type",
		"value": "application/x-www-form-urlencoded"
	}
],
"body": {
	"mode": "formdata",
	"formdata": [
		{
			"key": "grant_type",
			"value": "{{grant_type}}",
			"type": "text"
		},
		{
			"key": "client_id",
			"value": "{{client_id}}",
			"type": "text"
		},
		{
			"key": "client_secret",
			"value": "{{client_secret}}",
			"type": "text"
		},
		{
			"key": "resource",
			"value": "{{resource}}",
			"type": "text"
		}
	]
},
"url": {
	"raw": "https://login.microsoftonline.com/{{tenant_id}}/oauth2/token",
	"protocol": "https",
	"host": [
		"login",
		"microsoftonline",
		"com"
	],
	"path": [
		"{{tenant_id}}",
		"oauth2",
		"token"
	]
},

```

Response:
```
 │ { error: 'invalid_request',
  │   error_description:
  │    'AADSTS900144: The request body must contain the following parameter: \'grant_type\'.\r\nTrace ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\r\nCorrelation ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\
  │ r\nTimestamp: 2019-08-12 10:16:26Z',
  │   error_codes: [ 900144 ],
  │   timestamp: '2019-08-12 10:16:26Z',
  │   trace_id: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx,
  │   correlation_id: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx,
  │   error_uri: 'https://login.microsoftonline.com/error?code=900144' }```

So grant_type is getting lost somehow. This is blocking me from fixing high severity vulnerabilities in a newman dep (lodash)

**Comment by codenirvana** [comment]
@virgesmith This is duplicate of #2081, refer: https://github.com/postmanlabs/newman/issues/2081#issuecomment-519149629

Remove the `Content-Type` header and I hope that will fix your issue.

**Comment by virgesmith** [comment]
Yes that works for me thanks for the swift response.

**Comment by codenirvana** [comment]
Closing as Duplicate of #2081
