### ISSUE TITLE
Response times 3x-4x larger than in postman

### ISSUE THREAD

**Issue by dannycohn** [postmanlabs/newman#209]
I've written a suite of test cases for my API, including response times. Via postman, the response time reported is typically 65-130ms. In newman, it's rather consistently 400ms. My test cases have a max response time of 200ms, so they're failing.

**Comment by chrfritsch** [comment]
I have this issue to. Postman needs just 150ms for a request and newman needs about 5 secounds for every request

**Comment by cameronoxley** [comment]
Also having the same issue, however in my case the response times are about 5x-10x longer in newman.

**Comment by shamasis** [comment]
What would be a sure-shot way to reproduce this on OSX? Based on that, I can check whether the upcoming v3.x fixes this issue. Try it out if possible - https://github.com/postmanlabs/newman/tree/feature/v3

**Comment by shamasis** [comment]
Since v3.0, I couldn't spot much difference between Newman and postman response times. So closing this ticket. Please reopen if otherwise.
