### ISSUE TITLE
Collapse is misspelled in report

### ISSUE THREAD

**Issue by AlkamiChewie** [postmanlabs/newman#2091]
1. Newman Version (can be found via `newman -v`): 4.5.3
 2. OS details (type, version, and architecture): Windows 10
 3. Are you using Newman as a library, or via the CLI?CLI
 3. Did you encounter this recently, or has this bug always been there:Just noticed
 4. Expected behaviour: Collapse button should read collapse not collaspe
 5. Command / script used to run Newman: run
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/54043944/62899504-87b50700-bd1d-11e9-989c-3cdb6ce00884.png)

**Comment by DannyDainton** [comment]
Hey @AlkamiChewie, 

This is a community created report that is independent of Newman - That issue was fixed a few versions ago so I would suggest updating to the latest package.

**Comment by AlkamiChewie** [comment]
Awesome,  Thanks and Apologies.  I completely forgot that it was a separate project.  

Sent from Mail for Windows 10
