### ISSUE TITLE
Add node-uuid to globals so postman and newman requests can generate UUID strings

### ISSUE THREAD

**Issue by xiphiaz** [postmanlabs/newman#210]
`node-uuid` is already a dependency, can it be added to postman and newman so tests & pre-request scripts have access?

We have a need where our clients generate a uuid for entity creation so we are currently doing a clumsy hack ie 

```js
var uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
    var r = Math.random() * 16 | 0, v = c == 'x' ? r : r & 0x3 | 0x8;
    return v.toString(16);
});
postman.setGlobalVariable("newUuid", uuid);
```

Instead we would like to do 
```js
postman.setGlobalVariable("newUuid, uuid.v4()");
```

**Comment by xiphiaz** [comment]
Actually disregard, I found the functionality in https://github.com/postmanlabs/newman/blob/master/CHANGELOG.md#113-september-17-2014

**Comment by litch** [comment]
I'm actually getting invalid v4 UUIDs from that call.  Here's an example of the output:

`6d223574-36ac-f49c-de17-6f29cab38f15`

Note neither the 4 nor the y.  Pretty annoying.

**Comment by czardoz** [comment]
@litch can you open a new issue for this, and mention your Newman version? 

We are using v4 IDs (See https://github.com/postmanlabs/newman/blob/19c701b7e51c646a6d23f7219f9a2d4240c10c1b/src/utilities/VariableProcessor.js#L32) So I will need to check this out properly :)
