### ISSUE TITLE
"No Such File Or Directory" Newman via Ubuntu

### ISSUE THREAD

**Issue by TzviGK** [postmanlabs/newman#2100]
1. Newman Version (can be found via `newman -v`): 4.5.4
 2. OS details (type, version, and architecture): Windows 10 (64bit) Running Ubuntu Console V1804
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Always
 4. Expected behavior: Both commands to run as expected
 5. Command / script used to run Newman: 
`

#CartCollection as Logged in User

newman run https://www.getpostman.com/collections/COLLECTIONNUMBER -g /mnt/c/FOLDERNAME/automatedtesting/Configuration/LoggedUser.json

#CartCollection as SessionUser

newman run https://www.getpostman.com/collections/COLLECTIONNUMBER -g /mnt/c/FOLDERNAME/automatedtesting/Configuration/SessionUser.json`

The first file (LoggedUser) gets an error of "No Such File Or Directory". While the second file **runs as expected.**

Both files are in the same path with the only difference being that one has a global variable set (LoggedUser = true) while the other has (LoggedUser = false).
![image](https://user-images.githubusercontent.com/54317161/63535148-7340ed80-c519-11e9-817a-48dcaf8dd2d1.png)

For some unknown reason the LoggedUser.json can't be found.
![image](https://user-images.githubusercontent.com/54317161/63535111-5a383c80-c519-11e9-860e-22488e4e938d.png)

When directing directly to the json it displays in the console though.
![image](https://user-images.githubusercontent.com/54317161/63535032-2eb55200-c519-11e9-9995-ab9eb01ac127.png)

**Comment by sponeill** [comment]
@TzviGK Did you find a solution for this? I am experiencing the same issue. Thanks.
