### ISSUE TITLE
Not able to fetch request name with folders in newman event handlers through node run

### ISSUE THREAD

**Issue by shivam14g** [postmanlabs/newman#2102]
I have created a JS file in which I Imported newman library and then define newman.run() function and in the call back function I put **'on'** event handlers . In this event handlers I put different different events. I tried with request , item, done .. In all events I tried to fetch the API request name along with folder: 

**Like my collection file are in below form:**

**"item": [
		{
			"name": "Folder 1",
			"item": [
				{
					"name": "Folder 2",
					"item": [
						{
							"name": "API_to_Verify_Employee_Details",
							"event": [
								{
									"listen": "test",
									"script": { };
**
		
I used below method to get the request name:

newman.run({
    collection: './TestEmployeeDetails.json',
    reporters: "cli",
    reporter: {
        html: {
            export: './htmlResults.html' 
        },
        json: {
            export: './jsonResults.json' 
        }
    }
}, function (err,summary) {
    console.log('collection run complete!');
}).on('request', function (err, summary) { 
console.log(summary.request.name);	
};
	
**Actual**: with every event I am getting only "API_to_Verify_Employee_Details"
**Expected** : "Folder1.Folder2.API_to_Verify_Employee_Details"
 Newman Version : 4.5.3

Please let me know if there are other events to fetch request details with folder name or from which method of summary object.

**Comment by DannyDainton** [comment]
Hey,

You could give the `htmlextra` reporter a go and see if that shows the names and solves your problem?

https://www.npmjs.com/package/newman-reporter-htmlextra

**Comment by shivam14g** [comment]
Is it not possible through summary object in event handlers ?

**Comment by DannyDainton** [comment]
@shivam14g 

This is by no means a solution and I'm not sure of the structure of your Collection and how you plan to use the extracted information but you could get that from the `done` event.

My basic Collection structure:

<img width="300" alt="Screenshot 2019-08-28 at 10 34 38" src="https://user-images.githubusercontent.com/17089546/63844175-a521dc00-c97f-11e9-9b6e-4daa325e4e57.png">

Using the `done` event to log the names on the folders and request:

<img width="1086" alt="Screenshot 2019-08-28 at 10 34 08" src="https://user-images.githubusercontent.com/17089546/63844260-c682c800-c97f-11e9-8344-3098146ebbdc.png">

**Comment by codenirvana** [comment]
Closing as per https://github.com/postmanlabs/newman/issues/2102#issuecomment-525665791
