### ISSUE TITLE
[Feature Request] Generating collections from swagger/oai yml/json specs

### ISSUE THREAD

**Issue by RomainSimiand** [postmanlabs/newman#2104]
It's kind of mindblowing that what happens in the Postman desktop app, and the web version, isn't supported by Newman (via cli).
I'm trying to industrialize our Postman collections maintenance.
Our APIs evolve fast, and the bigger we get, the harder it is to ensure consistency between specs, implementation, and collections for our internal testers etc ...
I was hoping newman would cope with this issue a long time ago, but haven't had the chance to see this coming. 

Is this feature in the pipe ? And if not, I'd love to get your thoughts on this.
Thanks!

**Comment by adityaofficial10** [comment]
@RomainSimiand 
I am moving forward with this feature request.

**Comment by adityaofficial10** [comment]
@shamasis 
We can use swagger2-postman-generator npm package here.
It converts the Swagger spec to Postman Collection v1.
We'll have to convert it to v2 and we're done.

**Comment by shamasis** [comment]
2 years too late to reply!

I'm afraid this is beyond the scope of newman as a project. 

Similar constructs as discussed here is planned to be built in a more integrated fashion on Postman Platform and APIs. Meanwhile, individual separate components stay open sourced for all of us to combine and integrate as we please. 

Closing this.

**Comment by shamasis** [comment]
@adityaofficial10 you can talk to @postmanlabs/integrations-platform to check if swagger-2-postman's team is available to collaborate to add anything relevant on that project itself.
