### ISSUE TITLE
How can i exclude some folders in the collection?

### ISSUE THREAD

**Issue by stephenwang1011** [postmanlabs/newman#2115]
For example:
 I have  5 five folders: f1,f2,f3,f4,f5.  
 I want to exclude folder: f2, how can I do?

Please don't suggest me to use :
newman run collection.json  --folder f1 --folder f3 --folder f4 --folder f5

Thanks!

**Comment by stephenwang1011** [comment]
no one knows?

**Comment by ProBeta1** [comment]
One straightforward way is to copy the desired folders in a directory and just using that .

**Comment by DannyDainton** [comment]
Hey @stephenwang1011

I believe the only way to do that is by the way you mentioned which isn't ideal if you have many folders.

There is a recent feature request to include a flag to exclude certain folder so I'm going to close this one and track things on that issue.

https://github.com/postmanlabs/newman/issues/2465
