### ISSUE TITLE
Feature request: run with multiple files

### ISSUE THREAD

**Issue by Eomm** [postmanlabs/newman#2117]
Hello,
the `run` command could accept as input a regexp or a list of file in order to execute all the collection as a single one.

_Use case_

If you have a huge test suite you need to break up into multiple files.
Right now I have 140k request in 14 `.postman_collection` files.

You could use:

`for fn in `ls *.postman_collection`; do newman run $fn --env-var 'baseUrl=http://localhost:3000'; done`

But the bail logic is gone and I need bash scripting to manage the exit code and reports.

WDYT?

**Comment by shubhamjadon** [comment]
@codenirvana I would like to work on this.

**Comment by codenirvana** [comment]
@shubhamjadon Sure 👍

**Comment by shubhamjadon** [comment]
@codenirvana please review the pull request.

**Comment by sweetnoods** [comment]
That does seem incredibly useful for CI/CD.

**Comment by rufreakde** [comment]
Will we then be able to provide a list of pairs sharing the same global scope that might be changed during the run?
`run -g <global.json> --collectionEnvPair <colection.json1> <env.json1> --collectionEnvPair <colection.json2> <env.json2>`

Would I be able to have an authentication collection run first and all the other ones with its environment afterwards?

**Comment by rufreakde** [comment]
nvm can somulate this with, just "found --export-globals <path>" :)

**Comment by shamasis** [comment]
Newman will not support running multiple collections at one go in a foreseeable future. 

We can provide useful code snippets and examples to make this super easy in CI.
