### ISSUE TITLE
How to add WSS security credntials in Postman

### ISSUE THREAD

**Issue by kadianravi007** [postmanlabs/newman#2121]
I have been testing Webservice and trying to automate the SOAP UI request which contains WSS Outgoing security credentials. I have tried putting those credentials under Basic AUTH but it does not work for me. And it gives HTTP 400 Bad Request as response. 

In SOAP UI, Request works fine but while creating the same kind of request I am getting above mentioned error. Talked to developer and he mentioned I need to incorporate the WSS security credentials like user name/Password and Timestamp for successful response.

Please help me on this issue.

Thanks,
Ravinder Kadian

**Comment by codenirvana** [comment]
Can you share a scaled-down collection which we can use to reproduce this issue?

**Comment by DannyDainton** [comment]
Hey @kadianravi007 

I'm going to close this issue out for now but if you're still having problems, we can open it again.
