### ISSUE TITLE
Postman collection prerequest script not executing in newman

### ISSUE THREAD

**Issue by ppyoosuf** [postmanlabs/newman#2122]
1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):windows 10
 3. Are you using Newman as a library, or via the CLI? library
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:prerequest script not running, but working in postman
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):

**Comment by arnitkun** [comment]
Hi!

I was not able to reproduce this issue. 

Steps:

1. Created a collection with 2 requests. 
2. Placed a pre-request script in one of the request.

The script ran successfully. I also tried to change the order of requests but the script did not fail.
Can you please add more information?

[My collection](https://github.com/postmanlabs/newman/files/3632715/demo.postman_collection_1.json.zip)

**Comment by ppyoosuf** [comment]
Hi ,

we were added the pre-request script for the collection/folder not for each individual request. can u check with the same.

**Comment by ppyoosuf** [comment]
Hi ,
That fixed..,
 I was working with newman@3.5.2 version,I just updated to the latest version(4.5.4).I think the collection level pre-request is the new feature in postman.

**Comment by arnitkun** [comment]
I tried the same with a collection level request and it seems to work as well. 
[Collection used](https://github.com/postmanlabs/newman/files/3634772/demo.postman_collection_4.json.zip)

**Comment by jtj999** [comment]
hi, I use nodejs version 14.5.0 (includes npm 6.14.5) and the pre-requisite file is not executed when ran from CLI . I have window 10. can anyone please help ?

**Comment by momentumsubash** [comment]
did any one had sucess with this , i have a pre-request script in the top folder for creating session token and im passing this token for all the requests that i have in folders and sub folders, but when i try to run it using newman, it keeps giving me error with session token, but im pretty sure same script works by using postman tool , i even have returned the variables in console, and in postman it retruns the sessiontoken but not in newman ,

**Comment by ander-murane** [comment]
I have the same issue. Working with Newman version 5.3.1. Postman 9.14.8. I have a collection level pre-request script to set the headers. It runs in Postman as a collection or with individual tests. Newman fails every time. To prove it's a newman issue I manually selected the headers in the Postman app and that is the only test that passes. See Screenshots. 
<img width="1044" alt="Screen Shot 2022-03-02 at 3 02 55 PM" src="https://user-images.githubusercontent.com/97995234/156457435-ac2cc977-d206-417a-b23d-4d3814fac5ab.png">
<img width="896" alt="Screen Shot 2022-03-02 at 3 03 17 PM" src="https://user-images.githubusercontent.com/97995234/156457436-8848c743-e67b-42ea-81a1-206d40a39122.png">
<img width="723" alt="Screen Shot 2022-03-02 at 3 03 39 PM" src="https://user-images.githubusercontent.com/97995234/156457439-e807366b-f366-468a-8a58-fd3464064be2.png">
<img width="764" alt="Screen Shot 2022-03-02 at 3 04 27 PM" src="https://user-images.githubusercontent.com/97995234/156457440-304ea05a-4190-4584-9889-92b8ab6c44e8.png">
<img width="429" alt="Screen Shot 2022-03-02 at 3 04 42 PM" src="https://user-images.githubusercontent.com/97995234/156457443-c9cc5f7e-c38d-4c14-b641-dc9600f14e09.png">

**Comment by aladendorf** [comment]
Same here, I need to use newman with a collection with prerequest script for authentification.
is there a solution out there since this is thread is closed?

**Comment by malvikach** [comment]
@aladendorf Could you give an example/reference of your pre-request script. 

Are u using pm.environment.set() in the script for using the environment variables. If yes, it would help if you can post the newman command you are using to execute your collection (I want to validate if you are making use of environment in the command too) 

Sample newman command to run a collection along with an environment:
`newman run my_collection.json -e my_environment.json`

**Comment by aladendorf** [comment]
@malvikach, thanks for your reply, this is my prerequest script: 
`const echoPostRequest = {
  url: 'https://auth.xxxxxx.xxxxxx.de/auth/realms/xxxxxxxx/protocol/openid-connect/token',
  method: 'POST',
  header: 'Content-Type:application/x-www-form-urlencoded',
  body: {
    mode: 'urlencoded',
            urlencoded: [
            {key: "client_id", value: "xxxxxx"},
            {key: "client_secret", value: "xxxxx-xxxxx-xxxxx-xxxxx"},
            {key: "scope", value: "web-origins"},
            {key: "grant_type", value: "client_credentials"}
        ]
  }
};

var getToken = true;

if (!pm.environment.get('accessTokenExpiry') || 
    !pm.environment.get('currentAccessToken')) {
    console.log('Token or expiry date are missing')
} else if (pm.environment.get('accessTokenExpiry') <= (new Date()).getTime()) {
    console.log('Token is expired')
} else {
    getToken = false;
    console.log('Token and expiry date are all good');
}

if (getToken === true) {
    pm.sendRequest(echoPostRequest, function (err, res) {
    console.log(err ? err : res.json());
        if (err === null) {
            console.log('Saving the token and expiry date')
            var responseJson = res.json();
            console.log("response access_token " + responseJson.access_token)
            **pm.environment.set('currentAccessToken',** responseJson.access_token)
    
            var expiryDate = new Date();
            expiryDate.setSeconds(expiryDate.getSeconds() + responseJson.expires_in);
            **pm.environment.set('accessTokenExpiry',** expiryDate.getTime());
        }
    });
}`

there are 2 environment set but I have not setuped any environment and all even works like expected, except the newman run :)

**Comment by malvikach** [comment]
@aladendorf could you also share your newman command (please hide any sensitive data like keys).

Please Note: You will need to use the environment file in your Newman command as well so that Newman is aware of the environment file that it needs to set and get variables to.

**Comment by aladendorf** [comment]
@malvikach my command for run the collection: `newman run dev_collection.json -e dev_environment.json`
The environment.json

`{
	"id": "b8da459b-c2f3-4a4c-b342-7c9c226185da",
	"name": "dev",
	"values": [
		{
			"key": "accessTokenExpiry",
			"value": "",
			"type": "default",
			"enabled": true
		},
		{
			"key": "currentAccessToken",
			"value": "",
			"type": "default",
			"enabled": true
		}
	],
	"_postman_variable_scope": "environment",
	"_postman_exported_at": "2022-05-09T12:09:35.175Z",
	"_postman_exported_using": "Postman/9.17.1"
}`

**Comment by malvikach** [comment]
@aladendorf The above command looks fine.

Unfortunately, I am unable to reproduce the above issue when I tried a similar scenario. 

Would it be possible for you to additionally share your console logs and a screen recording of your newman run. Please do share your dev_collection.json and dev_environment.json files (remove sensitive values).

This will help me understand the issue better.

**Comment by aladendorf** [comment]
@malvikach I setup a new collection and a new environment with just one test, this works well, even without the environment. So I think I need to go over each test and test it seperatlyto find the one that cant run in newman. Thank you for your support!

**Comment by malvikach** [comment]
@aladendorf I see! 

hope u find the issue following the above approach. The pre-request scripts should execute fine in newman. 
Do let us know if you need any further info from our end.

**Comment by aladendorf** [comment]
If I found the test wich not run in newman I will write you, best regards

**Comment by aladendorf** [comment]
@malvikach Ive created a new collection and finally added all tests again, now it works, maybe newman only work without problems for created Collections after install newman? Dont know, works, best reagrds

**Comment by malvikach** [comment]
@aladendorf that shouldn't have been the case. I will validate this on my end though. 

I am glad that it worked for you now. 

Happy testing :)

**Comment by aladendorf** [comment]
@malvikach Ive testetd it again with another Collection wich always fails with 401 in newman but not in postman. Ive duplicated it and then it runs, strange.

best regards

**Comment by malvikach** [comment]
@aladendorf please share a screen recording or a sample collection JSON. Thanks again for writing about this.

**Comment by TLYoz** [comment]
I have a similar issue. 

I have a collection in postman that as a pre request does this 

```
function S4() {
    return (((1+Math.random())*0x10000)|0).toString(16).substring(1); 
}
 
guid = (S4() + S4() + "-" + S4() + "-4" + S4().substr(0,3) + "-" + S4() + "-" + S4() + S4() + S4()).toLowerCase();


pm.request.headers.add({
    key: "ConversationId",
    value: guid
});
```
It sets a random header per request. It works fine in Postman but in  Newman it does not add the header.

`npm run newman -- "my_collection.json" -e "${ENV_FILE}" -k -r cli,teamcity`

How the build is executed in teamcity. Not very familiar with npm but I assume this would always be running a latest stable Newman.

**Comment by LamriL** [comment]
@malvikach @aladendorf : I encountered the same problem.

Pre-request script
`pm.sendRequest({
    url: 'https://xxxx/xxxxx/protocol/openid-connect/token',
    method: 'POST',
    header: {
        'Content-Type': 'application/json',
    },
    body: {
        mode: 'urlencoded',
        urlencoded: [
            {key: "grant_type", value: "xxxxx"},
            {key:"username", value: "xxxx"},
            {key:"client_id", value: "xxx"},
        ]
    }
}, 
(err, res) => pm.environment.set("MyToken", res.json().access_token));`
