### ISSUE TITLE
Website: Documentation error on File Uploads

### ISSUE THREAD

**Issue by jcald1** [postmanlabs/newman#2131]
The page `https://learning.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman/` in the 'File Uploads' section says that 'The file sample-file.txt must be present in the same directory as the collection.'  This should say 'In this collection, sample-file.txt should be present in the current working directory.' instead, just like the README.md in the root directory of the repo. The website documentation and README.md are not in sync.

**Comment by Suhasnama** [comment]
Hello @codenirvana  , I would like to fix this issue, shall I update the file at `https://github.com/postmanlabs/postman-docs/blob/develop/src/pages/docs/postman/collection-runs/command-line-integration-with-newman.md` and submit a PR at `postmanlabs/postman-docs`

**Comment by Suhasnama** [comment]
Hi @jcald1 , @codenirvana ,
Fixed this issue and opened a PR at postman-docs , find the PR [here](https://github.com/postmanlabs/postman-docs/pull/2216#issue-383696890) , please review it and merge it accordingly.

**Comment by codenirvana** [comment]
@Suhasnama Thanks for the contribution 👍

**Comment by codenirvana** [comment]
Closing as the mentioned PR is merged.
