### ISSUE TITLE
Have a dedicated command to show up local env-info

### ISSUE THREAD

**Issue by jamesgeorge007** [postmanlabs/newman#2134]
As of now, the users are required to provide information concerning their local environment while submitting bug reports. It would be nice to have a dedicated command that would ease the respective workflow. 

## Proposed API

`newman info`

```sh
Environment Info:

  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.8.1 - /usr/local/bin/node
    Yarn: 1.17.0-0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.75
    Firefox: 69.0
  npmGlobalPackages:
    newman: 4.5.4
```

**Comment by jamesgeorge007** [comment]
I would happily submit a PR :+1:

**Comment by jamesgeorge007** [comment]
@codenirvana thoughts :thinking:

**Comment by adrijshikhar** [comment]
@shamasis if this feature is not in the pipeline, i would like to work on this. Thanks.

**Comment by DannyDainton** [comment]
Hey @adrijshikhar

Did you start working on this? 😁

**Comment by adrijshikhar** [comment]
Not yet, but if this feature is required then I would really like to work on this.

**Comment by DannyDainton** [comment]
All contributions to the project are welcome 😁

**Comment by jamesgeorge007** [comment]
I think a better idea would be to add a line about `please paste the output of npx envinfo --system --npmGlobalPackages newman  -binaries --browsers` to the issue template rather than adding it to the CLI.

**Comment by adrijshikhar** [comment]
I think `newman info` is more intuitive for a user. Easy to remember and easy to communicate. Under the hood, the working might be the same but if we look through the perspective of engaging the user in the product then giving him short simple command would be nice. The user would feel that using this is handy because not everyone is very fond of big command lines. What say?

**Comment by adrijshikhar** [comment]
@DannyDainton what are your views about the feature? I am planning to work on this.

**Comment by DannyDainton** [comment]
Sounds good. 

Looking forward to seeing what you come up with 🏆

**Comment by adrijshikhar** [comment]
Sounds nice.
I will get right on it.

**Comment by adrijshikhar** [comment]
What would a better option?
1. use the npm module to print system information
2. use inbuild function such as `inxi` to print system information
@DannyDainton Please give some insights on this one

**Comment by codenirvana** [comment]
This is a great idea but a simple CLI tool like Newman doesn't have a lot of OS/environment-specific dependencies.

Currently (+historically), the only thing we need to debug an issue is `newman -v`. 😅
