### ISSUE TITLE
Multipart/form-data boundary

### ISSUE THREAD

**Issue by kgacova** [postmanlabs/newman#2143]
1. Newman Version: 4.5.4
 2. OS: Windows 10 x64
 
In postman I have a request with headers:
![image](https://user-images.githubusercontent.com/15667465/66048232-76bc9100-e529-11e9-9789-518ef779a97d.png)
Postman produces a request with 
Content-type: multipart/form-data; boundary=--------------------------096616827613277107889682
Export to json and run it with newman, I get "Content-type:multipart/form-data" without specified boundary. Can something be done about this?

**Comment by codenirvana** [comment]
This has been fixed in Newman v4.5.5.
