### ISSUE TITLE
Powershell can't seem to handle output from Newman reporters 

### ISSUE THREAD

**Issue by ptletski** [postmanlabs/newman#2144]
This is in regards to closed issue 1116. It doesn't really state a solution.

I'm using newman 4.5.4 on Windows 10 with Powershell.

I copied the PS script in issue 116 to run my Postman requests.

I applied the no-color and diasable-unicode options.

The appearance is as shown in the last image in the referenced issue.

![image](https://user-images.githubusercontent.com/44261878/66270699-79b6ca80-e824-11e9-9ff3-96fda2f9084b.png)

Is there a solution to clean up the appearance of output?

**Comment by shamasis** [comment]
Perhaps power shell CLI width detection needs some more research. As a short term, maybe we can allow setting CLI width via options forcefully? @codenirvana

**Comment by ptletski** [comment]
That would be OK, I hope.

**Comment by sparksterz** [comment]
As an update I've been using PowerShell Core 7.1.2 in Windows Terminal and the Newman CLI reporter output is working as expected.

**Comment by shamasis** [comment]
> As an update I've been using PowerShell Core 7.1.2 in Windows Terminal and the Newman CLI reporter output is working as expected.

True that. I've tried reproducing it earlier even when this was first reported - but couldn't. Back then the only solution I could think of is open up an undocumented api to use some environment variable to force set CLI width. As I type, even now it works on PowerShell just like you said.

**Comment by DannyDainton** [comment]
Closing for now, can look at reopening again.
