### ISSUE TITLE
[chore]: onboarding an ASCII flavoured banner

### ISSUE THREAD

**Issue by jamesgeorge007** [postmanlabs/newman#2145]
![Screenshot from 2019-10-07 20-33-25](https://user-images.githubusercontent.com/25279263/66324093-7ade1980-e942-11e9-98fa-36b7a9a9435a.png)

**Comment by jamesgeorge007** [comment]
I've put together [node-banner](https://github.com/jamesgeorge007/node-banner) for the purpose.

**Comment by jamesgeorge007** [comment]
@codenirvana thoughts :thinking:

**Comment by codenirvana** [comment]
Looks good!
However, adding such ASCII arts needs to be tested and managed across multiple OS, shells and CI environments.

I would love to see this in a custom CLI reporter (maybe inbuilt reporters fork) but no plan to add this right now.

Thanks for sharing this module. 👍

**Comment by shamasis** [comment]
@jamesgeorge007 ... just to add context, have a look at issues like this: https://github.com/postmanlabs/newman/issues/2144 - they are hard to fix and test for across multiple platforms and TTY / REPLs. Hence, we would ideally like to avoid adding ASCII art as a default feature.
