### ISSUE TITLE
Newman not able to send csv file via POST request

### ISSUE THREAD

**Issue by cguedez** [postmanlabs/newman#2149]
Hi I having problems when using newman.

What is happening is: I have a postman collection where I upload a CSV file and sent to the API server and everything works fine, I get status code 200.

However, when I save this collection into JSON and try to run it with newman I get a code 422 with a message that indicates that the file has not been sent since the property is empty.

I have attached a snippet of my JSON collection, and the report I get back after the Post request call.

I hope you can help with this as I have read everything about it and couldn't find anything about this specific one.

![Capture](https://user-images.githubusercontent.com/56342803/66467335-35256c00-ea7c-11e9-86dc-fb1a0623fed1.PNG)
![Capture1](https://user-images.githubusercontent.com/56342803/66467336-35256c00-ea7c-11e9-9d1f-2a64bc70559c.PNG)

**Comment by vdespa** [comment]
Try getting the csv file from the same directory from where you are executing newman. 

I suspect that maybe newman is not allowing you to read this file because you did not specify a working directory using --working-dir <path>

**Comment by cguedez** [comment]
The issue is now fixed. 

The file is in the same directory.

The problem was that the code generated by postman had a content type of x-www-form-urlencoded.
This should be form-data instead.

I've fixed it by removing the whole block (as attached)

Thank you so much for you help.

![Capture](https://user-images.githubusercontent.com/56342803/66477731-a5d68380-ea90-11e9-894a-1a88c2ca8c32.PNG)
