### ISSUE TITLE
-x returning code 0 even though tests failed

### ISSUE THREAD

**Issue by riyunoa** [postmanlabs/newman#215]
Hey everyone, we've been having issues with newman 1.2.16. For some reason, -x returns code 0 even though some tests failed. -s returns an error as expected.

Any ideas how we can fix this? Thanks in advance!

**Comment by abhijitkane** [comment]
Thanks for reporting this. We'll fix this in the next release.

**Comment by riyunoa** [comment]
Thank you abhijitkane, looking forward to that! We'll just use -s in the meantime.

**Comment by Crispy1975** [comment]
We are potentially seeing this within a Node.js app. On any error we expect the error code 1 to be returned in the callback, however the response is undefined. Here's our options...

	// Rig production environment options
	var prodOpts = {
		envJson: prodEnv,
		iterationCount: 1,
		outputFile: resDir + 'outfile.json',
		responseHandler: 'TestResponseHandler',
		asLibrary: true,
		stopOnError: false
	};

...and here is the execute with callback.

	// Run the test(s)
	Newman.execute(basicApiCollection, prodOpts, function(code) {
		console.log('Test cycle complete', code);
	});

Test output displays perfectly on the command line and writes to the defined output file. However we never get an exit code through the callback. We have also confirmed the -x from a bash script does not return 1 either.

Any updates on when the next release will be to fix this?

**Comment by abhijitkane** [comment]
Newman v1.2.17 is out. You should be getting the callback correctly. Can you confirm?

**Comment by Crispy1975** [comment]
@abhijitkane cool, will test that and post result here. Thanks!

**Comment by Crispy1975** [comment]
@abhijitkane tested the new version (v1.2.17) and we not do get a code back from the callback, however we are seeing a code of `0` when we expect a code of `1`. We have a speed test failing on an API endpoint. My understanding is that Newman should report a `1` when the `asLibrary` option is set?

**Comment by abhijitkane** [comment]
Here's what I tried:
A collection `collection.json` had 3 requests with one test each. (The tests for request 2 was failing, the other 2 were passing)
Using as a standalone program - 
`newman -c collection.json -x`   gave an exit code of 1 (but ran all 3 tests)
`newman -c collection.json`   gave an exit code of 0 (but ran all 3 tests)
`newman -c collection.json -s`   gave an exit code of 1 (but ran only the first 2 tests)

Using as a library:
```
newmanOptions = {
    iterationCount: 1,     
    responseHandler: "TestResponseHandler",
    asLibrary: true,             
    exitCode: true
}
Newman.execute(collectionJson, newmanOptions, function(code) {
	console.log("Exit code: " + code);
});
```
printed 'Exit code: 1'

Are you following a similar procedure and getting different results?

**Comment by Crispy1975** [comment]
Being honest I didn't try it as a command line this time, just within a Node.js app. However even with an error we got an exit code of `0`. I will test again to make sure nothing is missing.

**Comment by Tom5om** [comment]
Tested it just now, appears to be working on this new version (2.18) Had the same problem a while ago.
