### ISSUE TITLE
CSV File with Quotes Parsed Correctly in Collection Runner, but not in Newman

### ISSUE THREAD

**Issue by JDiazZenergy** [postmanlabs/newman#2150]
1. Newman Version (can be found via `newman -v`): 4.5.5
 2. OS details (type, version, and architecture): Windows 10 x64
 3. Are you using Newman as a library, or via the CLI? CLI
 4. Expected behaviour: CSV file be parsed correctly, as it is in the postman collection runner
 5. Command / script used to run Newman: newman run "$collection" -e "$environment" --folder "Default" -d $pathToTestData + "Default.csv" -r $reportType

I can do a collection run with no issues in the collection runner, however when doing the same collection run in newman, an error message will be thrown. The issue appears to be a difference in the way the csv file is parsed in newman vs in the collection runner. The csv file contains multi line values, as well as values that contain double quote characters. 

It seems that the collection runner correctly escapes the commas before running while newman does not. Here is an example showing the preview data window in the collection runner:
![image](https://user-images.githubusercontent.com/47532760/66519020-720d5500-eab4-11e9-9232-8e139519b413.png)

Here is a look at the raw text of the same csv file:
![image](https://user-images.githubusercontent.com/47532760/66519103-9ff29980-eab4-11e9-9386-4541752f1bcf.png)

Steps to reproduce 
1. Create a csv file that includes double quotes
2. Pass in the csv file to newman via the -d option
3.  Attempt to run this newman command
4. Get the following error message: error: Invalid Closing Quote: got """ at line 2 instead of delimiter, row delimiter, trimable character (if activated) or comment

**Comment by codenirvana** [comment]
@JDiazZenergy We are aware of this disparity in Newman's CSV parser and it's planned to be fixed in Newman v5 (no ETA just yet).

For now, you can replace `"""` with `\"` to unblock this issue.

**Comment by SimonVHB** [comment]
@codenirvana I'm getting a similar error: `error: Invalid opening quote at line 2`

The csv datafile that I'm using looks like this:
![image](https://user-images.githubusercontent.com/16856776/69567670-3245f280-0fba-11ea-8d2a-a9d50d48ae92.png)
It only has one double quote (in comparison to `"""` like the problem above)

I can't figure out how to work around this problem (untill v5 is released).
How do I escape the quotes for it to work?

**Comment by iheartdaikaiju** [comment]
> @JDiazZenergy We are aware of this disparity in Newman's CSV parser and it's planned to be fixed in Newman v5 (no ETA just yet).
> 
> For now, you can replace `"""` with `\"` to unblock this issue.

I have verified "for now" solution doesn't work with Newman 4.5.5 . My newman runner is located here,
https://github.com/iheartdaikaiju/postman_tools/blob/master/Runner.js

although I am happy to prepare a bare newman call with nothing else in the nodejs file as well.

Try using this test document
Blank,\"Field 1\",\"Field 2\",
,{\"ExampleArgument\": \"hello\", \"Another\":\"world\"},3,

**Comment by iheartdaikaiju** [comment]
The collection runner also fails on escaped double quotes. If this is a field,
"""2396903200"""
This is the result
""2396903200""
Per CSV standard RFC 4180 this should instead be
"2396903200"

**Comment by iheartdaikaiju** [comment]
@SimonVHB  I was able to verify if you do
"[""5dd...427""]"
That will work in the Collection Runner in Postman, which I feel should be the recommended alternative, rather than \" which is not part of RFC 4180

**Comment by harishshet222** [comment]
Hi, Can anyone help me on how to pass the csv file containing the testcase to newman run, 
I have created a collection in postman , there I have only one request, and I am passing the csv file in the collection runner and it gets executed successfully , I want to do the same in newman , So I installled newman, and when I tried to run , using newman run <collection-link> -d <path to csv file > I am getting error error: Invalid opening quote at line 3, how to pass the csv file to the newman?

**Comment by iheartdaikaiju** [comment]
Hello @harishshet222 

As per the above discussion you have two options

1, you can avoid using quotes in your data. Note that Postman as of now treats One Two,Three, Four Five as "One Two","Three"," Four Five"
2, you can use the collection runner as follows :

- Runner button, 3rd from the left on the top
- Data : Select File : browse to your .csv file
- Press Start Run

All the other options you can send to Newman, can be sent to the Collection Runner.

For now, Newman is best suited for CSV files that do not contain quotes within records, and the Collection Runner for CSV files that contain quotes.

As a personal work-around, I have added Pre-Request scripts that turn unused symbols (I like using á or ¿) into quotation marks, to my collection, whenever I need command line automation.

**Comment by adrijshikhar** [comment]
i would like to work on this feature.

cc @codenirvana and @shamasis

**Comment by codenirvana** [comment]
This is fixed in Newman v5.
