### ISSUE TITLE
How not to store cookies for each iterations?

### ISSUE THREAD

**Issue by simmosoonsein** [postmanlabs/newman#2151]
I have Postman collection which requires to clear cookies during each iteration.
I have included cookieJar.clear(URL, callback (error)); in the very first step.
With Postman, in collection runner there is possibility not to store cookies during each iteration execution. Using this method all my test iterations runs fine.
Using the same collection in Newman iterations 2...n will fail cause cookies are not cleared and old cookies are used.
How to clear cookies with Newman?

**Comment by coditva** [comment]
Hey @simmosoonsein, thanks for writing in.

Currently, there's no way to clear all cookies between iterations in Newman. But as you mention you're using `cookieJar.clear`, you should be able to use it as a workaround.

Please note that to clear all cookies, you must call `cookieJar.clear` for each `domain+path` that as cookies set.

E.g. if you have cookies set on `mycoolsite.com/foo`, `mycoolsite.com/bar` and `someothersite.com/bar`, you must call `cookieJar.clear` for each for these.
```javascript
let cookieJar = pm.cookies.jar();

cookieJar.clear('mycoolsite.com/foo');
cookieJar.clear('mycoolsite.com/bar');
cookieJar.clear('mycoolsite.com/bar');
```

You can read more about cookies here: [Programmatic Access of Cookies](https://learning.getpostman.com/docs/postman/sending_api_requests/cookies/#programmatic-accees-of-cookies).
Hope this helps! :)

**Comment by simmosoonsein** [comment]
Thank you for the reply.
Unfortunately it seems the solution does not work or I am doing something wrong.
To check it with very simple case, I made google.com request with cookies reset. 
Using Postman works fine, with Newman I saw that cookie was reset for 2nd iteration but after that it remained unchanged.

`Iteration 1/5

→ google
  ┌
  │ 'Old cookies: '
  └
  GET http://www.google.com [200 OK, 6.02KB, 102ms]
  ┌
  │ 'New cookies: 1P_JAR=2019-10-11-12; NID=189%3DfsKSCCXPIq8vc9DwvSOWagh8S3vM2S6eYQ-s91gDxQZLwMJHdduiu4HHyPioPphYg4w_Gt2EX1uOQb9
  │ vVBPksBPqGaXthPfX0HX2x_B_iu5LW7smI27NOFrAkTjqmhgKNPHOfOj4qLm24q8vD9vnC0OGxgEZTV4OFsVx-YZddhw'
  └

Iteration 2/5

→ google
  ┌
  │ 'Old cookies: 1P_JAR=2019-10-11-12; NID=189%3DfsKSCCXPIq8vc9DwvSOWagh8S3vM2S6eYQ-s91gDxQZLwMJHdduiu4HHyPioPphYg4w_Gt2EX1uOQb9
  │ vVBPksBPqGaXthPfX0HX2x_B_iu5LW7smI27NOFrAkTjqmhgKNPHOfOj4qLm24q8vD9vnC0OGxgEZTV4OFsVx-YZddhw'
  └
  GET http://www.google.com [200 OK, 6.02KB, 59ms]
  ┌
  │ 'New cookies: 1P_JAR=2019-10-11-12; NID=189%3DpKRwm2eKoi0C2fsOfm2jjllgWXOdxa5o2QeqT6lkihafOTqexySkl21cKpnBrivq_ya_GTg84z5A4QP
  │ VUDwQPfUlm3f8GX3N7WDZShXCE_rCTG9xARmH4UuIE87vpU-A7aJY2jpGjIC9DqAORHyGS0UEDnNktUFTlGmwuatsdyw'
  └

Iteration 3/5

→ google
  ┌
  │ 'Old cookies: 1P_JAR=2019-10-11-12; NID=189%3DpKRwm2eKoi0C2fsOfm2jjllgWXOdxa5o2QeqT6lkihafOTqexySkl21cKpnBrivq_ya_GTg84z5A4QP
  │ VUDwQPfUlm3f8GX3N7WDZShXCE_rCTG9xARmH4UuIE87vpU-A7aJY2jpGjIC9DqAORHyGS0UEDnNktUFTlGmwuatsdyw'
  └
  GET http://www.google.com [200 OK, 5.69KB, 55ms]
  ┌
  │ 'New cookies: 1P_JAR=2019-10-11-12; NID=189%3DpKRwm2eKoi0C2fsOfm2jjllgWXOdxa5o2QeqT6lkihafOTqexySkl21cKpnBrivq_ya_GTg84z5A4QP
  │ VUDwQPfUlm3f8GX3N7WDZShXCE_rCTG9xARmH4UuIE87vpU-A7aJY2jpGjIC9DqAORHyGS0UEDnNktUFTlGmwuatsdyw'
  └

Iteration 4/5

→ google
  ┌
  │ 'Old cookies: 1P_JAR=2019-10-11-12; NID=189%3DpKRwm2eKoi0C2fsOfm2jjllgWXOdxa5o2QeqT6lkihafOTqexySkl21cKpnBrivq_ya_GTg84z5A4QP
  │ VUDwQPfUlm3f8GX3N7WDZShXCE_rCTG9xARmH4UuIE87vpU-A7aJY2jpGjIC9DqAORHyGS0UEDnNktUFTlGmwuatsdyw'
  └
  GET http://www.google.com [200 OK, 5.69KB, 56ms]
  ┌
  │ 'New cookies: 1P_JAR=2019-10-11-12; NID=189%3DpKRwm2eKoi0C2fsOfm2jjllgWXOdxa5o2QeqT6lkihafOTqexySkl21cKpnBrivq_ya_GTg84z5A4QP
  │ VUDwQPfUlm3f8GX3N7WDZShXCE_rCTG9xARmH4UuIE87vpU-A7aJY2jpGjIC9DqAORHyGS0UEDnNktUFTlGmwuatsdyw'
  └
`

Attaching .json file as well.
[test.json.zip](https://github.com/postmanlabs/newman/files/3717677/test.json.zip)

**Comment by coditva** [comment]
@simmosoonsein,
I noticed that in your pre-request script, you're clearing the cookies after you're checking the value of the "old cookies". I think you might want to do this instead:

```javascript
const jar = pm.cookies.jar();

jar.clear("google.com", function (error) {
  // error - <Error>
    jar.getAll('google.com', function (error, cookies) {
       console.log("Old cookies: " + cookies);
      // error - <Error>
    });
});
```

With the above change, I was able to verify that Newman is clearing the cookies. Can you try and confirm this?


The collection with change: [test2.zip](https://github.com/postmanlabs/newman/files/3722960/test2.postman_collection.json.zip)

**Comment by simmosoonsein** [comment]
Yes, works now, also I was able to clear cookies when full path was given: cookieJar.clear('mycoolsite.com/foo');
