### ISSUE TITLE
how to pass --insecure option in the newman run options

### ISSUE THREAD

**Issue by kthulsidoss** [postmanlabs/newman#2153]
Hi All of a sudden the code that generates a files responses from newman stopped working.
From the web i found that i need to add --insecure flag. Can you show how to add this to option
newman.run({
  // run options go here
  	collection: 'SIA_MTM_FUNCTIONAL_TEST_SCRIPTS_Chuncks1_NewDB_Dev_Mzr.postman_collection.json',
    environment:'SIA_NewDB_Dev_Mzr.postman_environment.json',	
	 "reporters": "htmlextra",
    "reporter": { "htmlextra": {"export": "SIA_Testcases_Report.html"} }
}, function (err, summary) {
  // handle collection run err, process the run summary here
}).on('request', function (err, execution) { // This is triggered when a response has been recieved
   if (err) { return console.error(err); }
    const fileName = testCaseArray[i]+'-foo.bl';
   fs.writeFile(fileName, execution.response.stream, function (error) {
      if (error) { console.error(error); }
      i++;
   });
});

**Comment by shamasis** [comment]
Hey 😊. community.getpostman.com should answer your question much faster than the issue tracker here.
