### ISSUE TITLE
Add wait-for-it (or something like it) to the docker image

### ISSUE THREAD

**Issue by sergiopacezup** [postmanlabs/newman#2154]
This would allow Newman to wait until the rest of the containers are up before starting the tests on CI/CD environments

**Comment by rhythmicdevil** [comment]
You should look into the NodeJS wait-on module. I had a similar problem waiting for servers to come up when using Cypress.io in a container to test web applications. I added wait-on to the Docker image and provided a condition. I do this in a Jenkins pipeline. Its probably not 100% applicable, but might get you were are going. 

```
sh 'docker run --name uiTestingWaitForServer ${CYPRESS_IMAGE} /bin/bash -c "/node_modules/.bin/wait-on http://${UI_TESTING_TARGET}:80/LaunchPad"'
```

**Comment by codenirvana** [comment]
Closing as this issue is not related to Newman and a workaround https://github.com/postmanlabs/newman/issues/2154#issuecomment-615393096 exists.

**Comment by 9Rune5** [comment]
It would make a lot of sense to have this in newman so that we don't all have to roll our own docker image containing wait-on or whatnot.

`newman -waitforOK <url>`

That way we can easily pass this parameter when incorporating postman/newman into our docker-compose files.
