### ISSUE TITLE
getting the number of failed tests

### ISSUE THREAD

**Issue by sudazzle** [postmanlabs/newman#216]
I found my solution from this commit "Added a feature to count the total amount of tests that failed #165" URL "https://github.com/dog94/Newman/commit/cc9be29b4d1c18b116a7debe950a075a1c47d5ab". But I also found some functions "_extractPassFailCountFromTests" and "_getPassFailCount", but I couldn't workout how to make use of it. I am working on GRUNT-Newman. Any suggestions pls

**Comment by shamasis** [comment]
This is being addressed in upcoming newman v3.x. In fact it is already fixed there. Try it out if possible - https://github.com/postmanlabs/newman/tree/feature/v3

**Comment by shamasis** [comment]
newman v3 now has

- failure summary referred using numbers
- programatic use has a failure array sent to callback
