### ISSUE TITLE
Docker Image - How to calculate total runtime 

### ISSUE THREAD

**Issue by josephthanaraja** [postmanlabs/newman#2163]
I am using Docker Image for the newman and running multiple test cases using that and all works fine. Since I am generating the HTML reports, I need to wait and manually I am giving the sleep(secs) in my jenkins pipline. Is there any other way to get/calculate the total execution time including the HTML reporting generation time.

**Comment by shamasis** [comment]
I’m no expert on Jenkins, but isn’t there a way to wait the image to finish executing and not put a sleep command? Also, total time taken to execute any command can be extracted using the `time` command - `time docker run ...`; there’s nothing built in Newman to be able to do so.

**Comment by shamasis** [comment]
The HTML report generation time is included in the total time newman binary takes to execute. If you do `time newman ...` you should get total time. 

There’s no separate way to get breakup of time taken by the reporter. Closing this thread.
