### ISSUE TITLE
newman does not work with pfx file

### ISSUE THREAD

**Issue by raghavendraavinay** [postmanlabs/newman#2165]
Hi,

Please help me out here , am getting error **error:0906D06C:PEM routines:PEM_read_bio:no start line** when pfx file is used with passphrase in newman. Same pfx file works fine in postman.

commandline used as below: 
**node newman.js run "collectionfile" -e "environmentfile" --insecure --ssl-client-cert "abc.pfx" --ssl-client-passphrase "abc" --reporters cli,html --reporter-html-export**

 1. Newman Version: 4.5.5
 2. OS details: Windows 7
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Tried this option recently
 4. Expected behaviour: PFX with passphare should work

Steps to reproduce the problem:

1. extracted pfx file from jks keystore using keytool
2. Used --ssl-client-cert option to point to pfx and no key file option was given
3. Executing this in CLI throws error **error:0906D06C:PEM routines:PEM_read_bio:no start line**

**Comment by aquibbaig** [comment]
@codenirvana Can I work on this?

**Comment by codenirvana** [comment]
@aquibbaig Yes, sure! 👍

**Comment by aquibbaig** [comment]
@codenirvana Hello. Sorry for the late reply, I had been travelling. So, I have been digging around a bit around this issue here. All I would like to know it how do you test sample routes to see if stuff is working properly in newman? I mean you can always run newman locally. However, If I wanted to check if newman accepts pfx files as client certificates, do I need to have an actual route plus a pfx certificate in postman to actually check it?

**Comment by codenirvana** [comment]
@aquibbaig  You need a local server that requires the PFX client certificates.
Refer [PFX tests in postman-runtime](https://github.com/postmanlabs/postman-runtime/blob/develop/test/integration/sanity/certificate.test.js#L179) for more details.

**Comment by codenirvana** [comment]
PFX client certificates can be setup using the new `--ssl-client-cert-list` option.
Here's an example config file that this option accepts:
```json
[
    {
        "name": "localhost certificates",
        "matches": ["https://localhost:9090/*"],
        "pfx": {"src": "/path/to/certificate.pfx"},
        "passphrase": "supersecret"
    }
]
```

**Comment by hungtdao** [comment]
Has this been implemented or resolved?  I got a same error when running newman for a Postman collection
> newman run test.postman_collection.json -e qa_env.postman_environment.json --ssl-client-cert c:\abc.pfx --ssl-client-passphrase passw0rd --reporter-junit-export "c:\report.xml"

Error:
_tls_common.js:135
      c.context.setCert(cert);
                ^

Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext [as __createSecureContext] (_tls_common.js:135:17)
    at Object.tls.createSecureContext (C:\Users\DaoH02\AppData\Roaming\npm\node_modules\newman\node_modules\postman-request\index.js:187:51)
    at Object.connect (_tls_wrap.js:1160:48)
    at C:\Users\DaoH02\AppData\Roaming\npm\node_modules\newman\node_modules\tunnel-agent\index.js:202:28
    at ClientRequest.onConnect (C:\Users\DaoH02\AppData\Roaming\npm\node_modules\newman\node_modules\tunnel-agent\index.js:163:7)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketOnData (_http_client.js:484:11)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
