### ISSUE TITLE
Specify Output Directory

### ISSUE THREAD

**Issue by CodeObsessed** [postmanlabs/newman#217]
A extremely useful feature would be the ability to specify an output directory for each collection's json file. Then upon every save, this is exported to that location.

The reason for this, is because we want to integrated Postman with our source control for CI testing. This will allow us to always have the latest tests in source control upon check-in.

**Comment by shamasis** [comment]
@CodeObsessed - can you file this in https://github.com/postmanlabs/postman-app-support?
