### ISSUE TITLE
Embedded Chrome v66 browser - security issue

### ISSUE THREAD

**Issue by alexwaddelluk** [postmanlabs/newman#2177]
The embedded Chrome browser that is used to signing to Postman.co is using Chrome v66 - as this has significant security issues, this version and all others up to v77 are blocked at one of our clients, which means we cannot sign into Postman.co

Could someone please advise if/when the embedded browser will be updated to Chroms v78 or newer?

**Comment by shamasis** [comment]
Umm ... what happened here? 🤔😂

Do you mean Postman native app’s embedded chrome version?
