### ISSUE TITLE
Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by ggpai** [postmanlabs/newman#2185]
1. Newman Version (can be found via `newman -v`): 4.5.4
npm version: 6.13.2
Node version: V11.11.0
 2. OS details (type, version, and architecture): Windows 2012 Server
 3. Are you using Newman as a library, or via the CLI? Newman CLI
 3. Did you encounter this recently, or has this bug always been there: Recently 
 4. Expected behaviour:
 5. Command / script used to run Newman:
newman run GeneralSettings_WFIM_VMPS.postman_collection.json -e Env_Dev_VMPS.postman_environment.json -k --reporter-htmlextra-browserTitle "DevVMPSSettings" -r htmlextra --reporter-htmlextra-showOnlyFails --reporter-htmlextra-export C:\03_Nimbus\Dev\Nimbus2.0_API\TestResult_Settings\. 
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

Steps to reproduce the problem:
 I am running below newman command:
newman run GeneralSettings_WFIM_VMPS.postman_collection.json -e Env_Dev_VMPS.postman_environment.json -k --reporter-htmlextra-browserTitle "DevVMPSSettings" -r htmlextra --reporter-htmlextra-showOnlyFails --reporter-htmlextra-export C:\03_Nimbus\Dev\Nimbus2.0_API\TestResult_Settings\. 

Getting below warnings/errors while running newman collection
(node:5040) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:5040) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:5040) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:5040) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:5040) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:5040) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by shamasis** [comment]
This is a standard node warning. We’ve run newman through our memory leak detection scripts and I don’t think we have identified a leak. If you have identified a leak, please post the collection and config that’s causing the leak along with the conditions under which the leak was discovered. It will help us a lot. 

On a separate note, @codenirvana is it a good idea to simply suppress this message so that it doesn’t freak people out? Maybe keep this enabled only under a `—debug` flag and use in tests?
