### ISSUE TITLE
I should be able to run single collection in multiple environments, like, Test, Staging and Prod. But, if I do so it runs all the APIs every time whereas I want to run some of them in Prod ans some of them in Stating and Prod both but all of them in Test. Can I do that by any way? 

### ISSUE THREAD

**Issue by testerncoder** [postmanlabs/newman#2186]
1. Newman Version (can be found via `newman -v`): 4.5.6
 2. OS details (type, version, and architecture): Windows 10, 64 bit
 3. Are you using Newman as a library, or via the CLI? : Yes
 3. Did you encounter this recently, or has this bug always been there: 
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable): NA

**Comment by codenirvana** [comment]
You can set up an environment or global variable and run your tests accordingly.

Also, we recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with issues like these.
