### ISSUE TITLE
In tests, get remote schema by $.getJSON for tv4 is impossible

### ISSUE THREAD

**Issue by webda2l** [postmanlabs/newman#219]
Current way in tests, to validate remote schema (https://github.com/geraintluff/tv4/issues/98) with $.getJSON or other Ajax methods is impossible.

I get similar problem to http://stackoverflow.com/questions/8638820/jquery-ajax-in-node-js, a ````statusText: 'No Transport'````

Maybe, like suggested in SO, can we have access to full request module in tests or fill a xhr to jquery?

**Comment by abhijitkane** [comment]
In the current version of Postman, tests run synchronously, so there's no way of getting remote scripts into the test environment. This is a restriction of the Chrome app platform.

We're working on ways to allow you to import custom JS files into the sandbox, but I can't offer an approximate date for that yet.

**Comment by webda2l** [comment]
Ok, thanks. So, feel free to close this issue if you want or wait.

**Comment by czardoz** [comment]
I'm closing this issue, we'll track the remote import feature in a separate place :)
