### ISSUE TITLE
Newman only fails a request if there is a test assertion in the collection.

### ISSUE THREAD

**Issue by avvi00** [postmanlabs/newman#2191]
1. Newman Version: 4.5.7
 2. OS details: Windows Server 2012
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Recently
 4. Expected behaviour:

A request that fails with 4xx, 5xx error should result in a failure. I can only get a failure if I set a test with expected response status of 200

 5. Command / script used to run Newman:
newman run https://api.getpostman.com/collections/xyz/?a
pikey=**** -e https://api.getpostman.com/environments/eeee/?apikey=**** --folder abc

 6. Sample collection, and auxiliary files (minus the sensitive details):

[newman.postman_collection.txt](https://github.com/postmanlabs/newman/files/3942892/newman.postman_collection.txt)

 7. Screenshots
![image](https://user-images.githubusercontent.com/3652531/70493282-30a03100-1b5b-11ea-8ef2-b2339c87f48c.png)

**Comment by matt-ball** [comment]
If you created a Newman run to test 400/500 conditions, a success (to you) would be seeing those status codes. As such, Newman doesn't make any assumptions as to what code it should receive. You need to explicitly define the expected behavior in your test scripts.

**Comment by avvi00** [comment]
Certainly agree that should be the case when there is a test assertion. My view is that when no explicit assertion is made, they should be treated as failures and thus indicated. Postman itself has this behaviour.

**Comment by pavellishin** [comment]
> My view is that when no explicit assertion is made, they should be treated as failures and thus indicated. Postman itself has this behaviour.

Does it? I don't see that happening on my end. The collection runner also doesn't show this as a failure.

![image](https://user-images.githubusercontent.com/296084/70731045-12aa0c00-1cd4-11ea-83ed-d0b8c60f7940.png)


![image](https://user-images.githubusercontent.com/296084/70731081-2190be80-1cd4-11ea-96b9-d3f5e6bdb04b.png)

**Comment by avvi00** [comment]
Ok my mistake - seem to recall seeing a response return red text in postman at some point. So its good that it's consistent in that regard. 

Still seems weird to me that a 4xx client error or 5xx server error is successful in the eyes of this framework.

**Comment by pavellishin** [comment]
> Still seems weird to me that a 4xx client error or 5xx server error is successful in the eyes of this framework.

I hear where you're coming from, but I disagree. Treating 4xx/5xx responses as errors is a habit from testing happy paths only. Tests should validate and verify the unhappy path responses, and I'd be pretty annoyed if I had to toggle some switch somewhere to say, "hey, this will return a non-200 response, please don't shit yourself about it." (Personal grumble grumble, we have something at work that requires this, and I am annoyed about it, and I'm itching to modify it.)

**Comment by shamasis** [comment]
Closing this issue. I too strongly believe that we cannot assume what response codes are used for. Having said that, we could think of ways to add simple no-code tests in Postman app at one point and make command line parameters reflect the same in newman.
