### ISSUE TITLE
Passing multiple folders to Newman CLI runs asynchronous but not sequentially

### ISSUE THREAD

**Issue by SarathkumarRajendran** [postmanlabs/newman#2196]
1. Newman Version 4.5.7:
 2. OS details MAC 10.14.3:
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Always
 4. Expected behaviour: All Folders should be executed sequentially in the order given
 5. Command / script used to run Newman: 
 newman.run({
      collection: require('../test/TestRequestsList.postman_collection.json'),
      environment: require('../test/TestENV.postman_environment.json'),
      folder: ['GetIDToken', 'IDLiteAuth', 'CAT_MasterTokenGrant_IDLiteClient', 'RID_GET_IDLITE_Member']
    })

Expecting the folders to be executed as per the order given. Please let me know how to run folders sequentially - OR - please let me know if this can added as a feature.

**Comment by rohit-smpx** [comment]
You can use [bluebird](http://bluebirdjs.com/docs/getting-started.html).[each](http://bluebirdjs.com/docs/api/each.html)/[mapSeries](http://bluebirdjs.com/docs/api/promise.mapseries.html)

```js
const fs = require('fs');
const newman = require('newman');
const bluebird = require('bluebird');


const folders =  ['GetIDToken', 'IDLiteAuth', 'CAT_MasterTokenGrant_IDLiteClient', 'RID_GET_IDLITE_Member'];

bluebird.mapSeries(folders,(folder) => new Promise((resolve, reject) => {
  newman.run({
    collection: require('../test/TestRequestsList.postman_collection.json'),
    environment: require('../test/TestENV.postman_environment.json'),
    folder,
  }, (err, summary) => {
    if (err) {
      reject(err);
    } else {
      resolve(summary);
    }
  });
})))
  .then((results) =>{
    console.log(results);
  })
  .catch(console.err);
```

**Comment by SarathkumarRajendran** [comment]
Thank you very much Rohit. Can you please let me know if there's any way to run the folder multiple times, consider the scenario below
POSTMAN COLLECTION
 - Folder 1
 - Folder 2
 - Folder 3
 - Folder 4
 - Folder 5

so, for a single test, i would like run the folders in the given order 
const folders =  ['Folder 1', 'Folder 3', 'Folder 2', 'Folder 1', 'Folder 2'];

But it lloks postman applies folder name as filter and runs repeated folder only once, say here it runs only once 'Folder 1' and 'Folder 3'

Can you please let me know if there's way to use repeated folder names and make it to run successfully?

**Comment by SarathkumarRajendran** [comment]
Also I have tried with the approach you said and having some issues, it runs only one folder , all the folders are not executing. 

const folders = ['Folder 1', 'Folder 2']; 
    
    bluebird.mapSeries(folders,(folder) => new Promise((resolve, reject) => {
          newman.run({
            collection: require('../test/archive/TestRequestsListCopy.postman_collection.json'),
            environment: require('../test/archive/Tets.postman_environment.json'),
            folder
          }).on('request', function (err, args) {
            if (err) { reject(err) } else {
              console.log('\n');
              console.log('request executed is : ' + args.item.name)
              //console.log('env value is : ' + args.environment.values.members[0].value)
              console.log('response of ' + args.item.name + 'is: ' + args.response.stream.toString())
            }
          });
    }))

Above script runs the requests available in Folder 1 only. Folder 2 is not at all being executed. Can you please check and let me know if i did anything wrong here.

**Comment by rohit-smpx** [comment]
> Above script runs the requests available in Folder 1 only. Folder 2 is not at all being executed. Can you please check and let me know if i did anything wrong here.

You forgot to resolve the promise from the newman `callback` (like in my original comment) or `done` event (shown below).

```js
const folders = ['Folder 1', 'Folder 2'];

bluebird.mapSeries(folders,(folder) => new Promise((resolve, reject) => {
      newman.run({
        collection: require('../test/archive/TestRequestsListCopy.postman_collection.json'),
        environment: require('../test/archive/Tets.postman_environment.json'),
        folder
      }).on('request', function (err, args) {
        if (err) { reject(err) } else {
          console.log('\n');
          console.log('request executed is : ' + args.item.name)
          //console.log('env value is : ' + args.environment.values.members[0].value)
          console.log('response of ' + args.item.name + 'is: ' + args.response.stream.toString())
        }
      }).on('done', function (err, summary) {
	    if (err) {
	        reject(err);
	    }
	    else {
	        console.log('collection run completed.');
			resolve();
	    }
	  });
}))
```

**Comment by SarathkumarRajendran** [comment]
Thank you, but it looks when we use bluebird.mapSeries(folders,(folder), newman runner instance is called newly for each folder. But i'm expecting all the folders to be executed in a single newman run instance as requests from multiple folder forms the single test case and have inter dependency between folders.

**Comment by rohit-smpx** [comment]
> Thank you, but it looks when we use bluebird.mapSeries(folders,(folder), newman runner instance is called newly for each folder. 

Yup, that is the case with this workaround. 

> But i'm expecting all the folders to be executed in a single newman run instance as requests from multiple folder forms the single test case and have inter dependency between folders.

Hopefully some alternative is suggested by the folks at Postman.

**Comment by rohit-smpx** [comment]
From what I understand from reading https://github.com/postmanlabs/newman/issues/2199, you want env values to persist between runs. This is possible because the summary object returns the environment modified by the run in [summary.environment](https://github.com/postmanlabs/newman#newmanruncallbackerror-object--summary-object)

So you could do:

```js
const folders = ['Folder 1', 'Folder 2'];

let env = require('../test/archive/Tets.postman_environment.json');

bluebird.mapSeries(folders,(folder) => new Promise((resolve, reject) => {
      newman.run({
        collection: require('../test/archive/TestRequestsListCopy.postman_collection.json'),
        environment: env,
        folder
      }).on('done', function (err, summary) {
	    if (err) {
	        reject(err);
	    }
	    else {
	        console.log(`Collection run completed for folder ${folder}.`);

			/** ********* Setting env for next run ******* */
			env = summary.environment.toJSON();
			resolve(summary);
	    }
	  });
}))

```

**Comment by SarathkumarRajendran** [comment]
Thank you for the reply. But if we pass the environment values from summary to next run instance, it will contain the environment values updated by the previous run only. 

But my test case doesn't look for environment values from previous run, instead update the environment file which is available in the directory with new values by using nodejs script and then wants newman run 2nd instance to use env file from directory with updated values.  

Sceanrio:
1. Update env file from directory with some value, say
 Key: uuid
value: uuid 1
 Key: Phone
value: phone 1

2. Call newman runner and execute some requests

3. Now, again update environment variables using nodejs script which is available in the directory, say different value of uuid and phone
Key: uuid
value: uuid 2
 Key: Phone
value: phone 2

4. Call Newman runner with the same env file directory path

Actual: Newman runs with previous value of env file (NOT TAKING NEWLY UPDATED VALUES) , but when i open the env file, new values are updated

Note: This is not Iteration flow to use iteration data.

**Comment by rohit-smpx** [comment]
Is this all being done in the same script executed once? Because if that's the case then nodejs will cache the value of the json when you require it the first time and use it again. It has no way of knowing that the file has been modified.
You will have to delete it from the `require.cache` after modifying it so that it gets read again, like:
`delete require.cache[require.resolve('../test/archive/Tets.postman_environment.json')]`

**Comment by SarathkumarRajendran** [comment]
Thank you very much. It's working now after deleting cache.
