### ISSUE TITLE
RequestError while using HTTPS urls in newman

### ISSUE THREAD

**Issue by vishbin** [postmanlabs/newman#220]
newman does not work with collections with https apis urls .

**Comment by NeilCross** [comment]
It's working for me.  Is your security certificate & certification path valid?  

You can disable strict ssl with the -k swtch

**Comment by vishbin** [comment]
Its works when I run it through postman directly

**Comment by shamasis** [comment]
Seems like it has been quite a while. Was unable to reproduce this issue without further information. Is this issue relevant any longer? If not, will close it in near future.

**Comment by darshil09** [comment]
I am facing similar issue
i can run tests on postman, but failing on newman.
its https://url.. tried -k/--insecure switch.

here is the error:
Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 8080 8080:80
    at ClientRequest.onError (C:\Users\darshil\AppData\Roaming\npm\node_modules\newman\node_modules\tunnel-agent\index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1015:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by gleuck** [comment]
I'm getting the same error. I've already tried setting the HTTP_PROXY and HTTPS_PROXY env vars in the same command when running newman. No success.
It works fine in Postman.

**Comment by shamasis** [comment]
We're working on adding proxy support - both as file and per domain as well as global.

**Comment by gleuck** [comment]
It is now working for me. It seems that http_proxy and HTTP_PROXY are completely different things. :-)
Set the correct (uppercase) environment variable and everything works fine.
Nevertheless, Postman seems to consider uppercase and lowercase env vars.

**Comment by shamasis** [comment]
Interesting find. @czardoz - possibly a bug in request module?

**Comment by kunagpal** [comment]
@gleuck A quick update: Proxy settings can be configured as shown here: https://github.com/postmanlabs/newman/tree/feature/proxy-readme-docs#proxy

**Comment by kunagpal** [comment]
Closing request due to inactivity, feel free to let us know about any other suggestions, bug reports, that you might have in mind.

**Comment by matheusro** [comment]
@gleuck I was strugling with proxy variables until your feedback about uppercase saved my life 😄
