### ISSUE TITLE
Flush/Clear newman library run instance memory

### ISSUE THREAD

**Issue by SarathkumarRajendran** [postmanlabs/newman#2200]
Please let me know how to clear the newman runner instance memory once the run is completed. Currently, i'm updating the environment variables from nodejs script to environment file and then passing it to newman runner. This is working for the first newman run instance.

But when again update environment file with new values and then calling newman run 2nd time, it's still running with old environment values (NOT taking newly updated values) , whereas when we open the environment file, could see that values are really updated inside it.

Can anyone please let me know the solution for this - or how to clear the neman run instance memory whenever the run is completed, such that it read the environment file with same name again but with updated values.

**Comment by jordanst3wart** [comment]
Appears to duplicate #2199
