### ISSUE TITLE
Parse Error: header overflow [errored]

### ISSUE THREAD

**Issue by hvitis** [postmanlabs/newman#2210]
![image](https://user-images.githubusercontent.com/17104239/72709767-dfc22600-3b65-11ea-9d2b-5eabbcb45b64.png)

When I’m running my collection against Identity Server using POSTMAN they are running smooth and perfect but after exporting and running from NEWMAN I’m getting this error visible on the screen.
```
**Parse Error: header overflow [errored]**
```

The request causing error is POST request with application/x-www-form-urlencoded and in form data I have state and id_token (first 859 char, second 1644 char). The NEWMAN fails on making the request itself (I think). I know it cause the server works against the browser, against POSTMAN and the request works in NEWMAN when I put shorter, fixed strings of data (but obviously server gives response about unauthorized call)

Anybody has any idea how it may be solved or how to find out if it’s a bug? In the source code I didn’t see much about logger.

I tried:

- Running via API, via Powershell, via POSTMAN API
- Tried putting fixed strings into those variables (same variables but put manually cause this error, shorter work)
- Increasing header size
- Cleaning cookies before runs

It seems like NEWMAN fails to make the request because of the size of the header? Or maybe it’s something with encoding/exporting to collection? Any ideas? If so, maybe clues on how can I fix it?  

> 
> Newman Version 4.5.7
> OS details Win10
> Are you using Newman as a library, or via the CLI:  **Tried both**  
> Did you encounter this recently, or has this bug always been there: No info about the bug anywhere.
> Expected behaviour: **It should make a request at least. Looks like it fails before sending it**
> Command / script used to run Newman: newman run .\NEWMAN.postman_collection.json --ignore-redirects
> 

I can't provide the collection as it's data that can't be compromised. Tried to be specific as per what am I passing to the request.

### Issue that may be similar / relevant
#2182
#1224

**Comment by coditva** [comment]
@hvitis this appears to be node specific problem at first glance. Can you try running this collection with Newman on a version of node < 10.15? (node `v8` to be on the safe side).

You can switch versions using:
- https://github.com/nullivex/nodist
- https://github.com/coreybutler/nvm-windows

whichever works for you.

**Comment by hvitis** [comment]
@coditva You have saved my life. 

**SOLUTION**: Works with Node v.10.12.0 // npm v6.4.1 // newman v4.5.7

**Comment by farouk60** [comment]
nvm install 10.12.0

**Comment by fangjiantan** [comment]
@hvitis Hi, I reported this error when executing with Newman command：
error: Invalid Record Length: header length is 9, got 1 on line 5

**Comment by Sviatoy** [comment]
you also can specify 
node --max-http-header-size=40960 
It should work for latest node
