### ISSUE TITLE
Global variable are not being accessed in Newman CLI

### ISSUE THREAD

**Issue by gshakir125** [postmanlabs/newman#2211]
I am running a collection whose  requests contain some global variable, when i run this collection in Postman Native app its working fine, but when i get the shared link of same collection and run it in the Newman CLI i am getting error. snapshot is given below.

![image](https://user-images.githubusercontent.com/46843605/72900233-553a1c00-3d49-11ea-9c9e-70df62fef178.png)

**Comment by coditva** [comment]
@gshakir125 Did you export the global variables from Postman App and use them with the command?

```bash
# use this option:
-g, --globals <path>            Specify a URL or Path to a file containing Postman Globals.
```

**Comment by gshakir125** [comment]
> @gshakir125 Did you export the global variables from Postman App and use them with the command?
> 
> ```shell
> # use this option:
> -g, --globals <path>            Specify a URL or Path to a file containing Postman Globals.
> ```
