### ISSUE TITLE
Request debug info

### ISSUE THREAD

**Issue by gadelkareem** [postmanlabs/newman#222]
newman is installed globally and I need to see the full info for the failed request. I tried to modify the responseHandler but it is not clear what dependencies are need, or maybe I need a working example of extending it.

**Comment by czardoz** [comment]
The fix has been commited: https://github.com/postmanlabs/newman/blob/develop/bin/newman#L48

You can now use ``-O <filename>`` to enable verbose logging, this will dump the request/responses to the file.

**Comment by vikt0rs** [comment]
please, suggest, if this feature still available?

**Comment by vikt0rs** [comment]
@czardoz ping?
