### ISSUE TITLE
Getting the below error while installing newman , npm ERR! code EINTEGRITY npm ERR! sha512-

### ISSUE THREAD

**Issue by praveen-centrico** [postmanlabs/newman#2220]
1. Newman Version (can be found via `newman -v`):
could not install , npm version 6.13.4 , node v12.14.1
 2. OS details (type, version, and architecture): 
Windows10
 3. Are you using Newman as a library, or via the CLI? 
CLI
 3. Did you encounter this recently, or has this bug always been there:
new
 4. Expected behaviour:
Newman installed successfully  
 5. Command / script used to run Newman:
npm install -g newman
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

[2020-02-05T07_08_12_952Z-debug.log](https://github.com/postmanlabs/newman/files/4158021/2020-02-05T07_08_12_952Z-debug.log)

**Steps to reproduce the problem:**

1. npm install newman -g

**Getting the below error:
**npm ERR! code EINTEGRITY
npm ERR! sha512-VhzHxkEG4zpLzLP8QA5NYf1eeI6X+d5cybpYcduQvQFsvVu6aUoGnRhfWJhxVOKJ8a2bEvwh1ZLfzTo6SzI3CA== integrity checksum failed when using sha512: wanted sha512-VhzHxkEG4zpLzLP8QA5NYf1eeI6X+d5cybpYcduQvQFsvVu6aUoGnRhfWJhxVOKJ8a2bEvwh1ZLfzTo6SzI3CA== but got sha512-OHtgagGK8FQEqCau0sPc8YPNbwxuBO+0la6/27b8lQ67JwsBET97pSTsp3qS/o+fzRh6C8UmeU8iljZ8QYPvcQ==. (4071 bytes)
npm WARN tar invalid entry}}

**2. Tried the below options**

npm cache clean --force
deleted node folders

**Comment by im-Amitto** [comment]
@praveen-centrico  As a workaround, follow the below steps:
• Go to the project directory
• Remove the node_modules directory: rm -rf node_modules.
• Remove package-lock.json file: rm package-lock.json
• Clear the cache: npm cache clean --force
• Run npm install --verbose
If after following the above steps still the issue exists then please provide us the output of installation command with --verbose.

**Comment by jimc404** [comment]
Your log shows  `304 Not Modified` responses on fetching the modules. 

This should be a fault with the cached content where integrity check does not match with the `package.lock.json`. You can fix this by running ```npm cache verify``` and reinstalling the modules.

As @im-Amitto mentioned you can clear your cache and reinstall, that too should fix the issue albeit by using more bandwidth. 

Most of the times, the underlying cause for this is the network or some fault in the system. If this does not go away then open an issue in the NPM repo.

**Comment by shamasis** [comment]
@praveen-centrico were you able to solve your issue? Closing this issue for now since most of the possible solutions we could employ has been discussed on the thread. If the problem persists, we would reopen. But we should then also reach out to npm team if there’s no new reason discovered.
