### ISSUE TITLE
Running collection with POSTMAN,but not with NEWMAN(With Environment.json).

### ISSUE THREAD

**Issue by arkadiyala** [postmanlabs/newman#2225]
Issue : 
Running collection with POSTMAN,but not running with NEWMAN(With Environment.json).

 1. Newman Version (can be found via `newman -v`): 4.5.7
 2. OS details (type, version, and architecture): Windows 7 enterprise
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Always
 4. Expected behaviour: whatever running from POSTMAN, should run from NEWMAN
 5. Command / script used to run Newman: Newman run <Pioneer.json> -e <environment.json> 

Steps to reproduce the problem:

1. Run Pioneer.json collection from POSTMAN (Working fine - Save extracted token into environment file and getting tokens from environment file into subsequent POST request)  
2. Run Pioneer.json collection from NEWMAN (NOT WORKING - Not Saving extracted token into environment file and NOT getting tokens from environment file into subsequent POST request)

My code under 'Tests' in 1st POSTMAN GET request:
![Capture](https://user-images.githubusercontent.com/21693119/74393898-f3f9eb80-4dd0-11ea-9113-1a02c38aa63c.PNG)

Note:
pm.environment.set("TS01a20dbe", headerValue1) - Updating 'TS01a20dbe' value in environment variable when I run above GET request from POSTMAN, but not updating when I run the same from NEWMAN.
 So 'TS01a20dbe' value is not passed on to next POST request.

**Comment by SarathkumarRajendran** [comment]
Can you try passing the variable storing steps (below 3 lines of code) **out of test method** and check whether it works?
let headerValue
var headervalue1
pm.environment.set

Please let me know the outcome of this.

**Comment by AugustDev** [comment]
Could you please elaborate on the solution, I am having same issue - tests work on Postman runner, but not on newman
