### ISSUE TITLE
ssl-extra-ca-certs not recognized as an option

### ISSUE THREAD

**Issue by ZebraFlesh** [postmanlabs/newman#2227]
1. Newman Version (can be found via `newman -v`): 4.5.7
 2. OS details (type, version, and architecture): macOS 10.14.6
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: recent
 4. Expected behaviour: Able to specify `--ssl-extra-ca-certs` CLI flag
 5. Command / script used to run Newman: `npx newman run ./test/e2e/newman/postman_collection.json --global-var "baseUrl=https://localhost:3000" --ssl-extra-ca-certs "./config/dev-certs/rootCA.pem"`
 6. Sample collection, and auxiliary files (minus the sensitive details):
```json
{
  "info": {
    "name": "My Project",
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
  },
  "item": [
    {
      "name": "Smoke Test",
      "event": [
        {
          "listen": "test",
          "script": {
            "id": "993811a6-169b-4d7a-b97b-896aa4f2fbb5",
            "exec": [
              "pm.test(\"Status code is 200\", function () {",
              "    pm.response.to.have.status(200);",
              "});",
            ],
            "type": "text/javascript"
          }
        }
      ],
      "request": {
        "method": "GET",
        "header": [],
        "body": {
          "mode": "raw",
          "raw": ""
        },
        "url": {
          "raw": "{{baseUrl}}",
          "host": [
            "{{baseUrl}}"
          ]
        }
      },
      "response": []
    }
  ]
}
```
 7. Screenshots (if applicable): N/A

Steps to reproduce the problem:
1. execute command `npx newman run ./test/e2e/newman/postman_collection.json --global-var "baseUrl=https://localhost:3000" --ssl-extra-ca-certs "./config/dev-certs/rootCA.pem"`
2. receive error `error: unknown option '--ssl-extra-ca-certs'`

**Comment by codenirvana** [comment]
@ZebraFlesh This option is recently added in #2208 and will be available from the next Newman release (early next week).

**Comment by ZebraFlesh** [comment]
Ah I see: the repo defaults to the `develop` branch instead of `master`. I thought the feature was available since it was in the readme.

**Comment by ZebraFlesh** [comment]
@codenirvana Any update on that release? I think we're now into "late next week" territory. Would a PR with [semantic-release](https://semantic-release.gitbook.io/semantic-release/) be helpful?

**Comment by codenirvana** [comment]
@ZebraFlesh This is getting delayed because of the other items which are scheduled in Newman v4.6.0 release. 😞
For sure this will be released before 25th Feb either as part of Newman v4.6.0 or v4.5.8.

Thanks for sharing the semantic-release link, I will have a look 👍

**Comment by codenirvana** [comment]
@ZebraFlesh Added in Newman v4.6.0 🎉
