### ISSUE TITLE
Custom HTML Reporting template

### ISSUE THREAD

**Issue by pradeepmurugesan** [postmanlabs/newman#223]
We need to override the newman functionality to accept custom templates for HTML reports. Do you guys have it as part of your roadmap? or you guys accept pull requests if we implement the same ?

somthing like 

>newman -c collection.json -e QA.json -H report.html --template=custom.ejs

**Comment by baldemarch** [comment]
We definitely need this, urgently.

**Comment by shamasis** [comment]
newman v3 has the base for doing this. we will soon expose this - perhaps in 3.1

+ @czardoz @kunagpal

**Comment by kunagpal** [comment]
@pradeepmurugesan @baldemarch 

Newman `v3.1.0-beta.1` is now available, and comes with an improved HTML reporter, default template overriding options, and other bug fixes. You can install it with: `npm install -g newman@beta`.

An option to specify custom templates for the HTML report is provided via the `--reporter-html-template <path-to-handlebars-template-file.hbs>` CLI flag. A sample template can be found at: https://github.com/postmanlabs/newman/blob/feature/styled-html-report/lib/reporters/html/template-default.hbs.

**Comment by baldemarch** [comment]
@kunagpal awesome! Will try asap. Thanks for the update!

**Comment by kunagpal** [comment]
@baldemarch The link has been fixed.

**Comment by baldemarch** [comment]
@kunagpal thanks :)

**Comment by felixdjost** [comment]
see also here https://github.com/felixdjost/newman-html-report-template-verbose for usage of a custom templates which dumpes http headers and body (which we found to be useful for debugging)
