### ISSUE TITLE
The CLI output should show the json data, the request is generating if any.

### ISSUE THREAD

**Issue by RishabhKodes** [postmanlabs/newman#2233]
1. Newman Version (can be found via `newman -v`):4.5.7
 2. OS details (type, version, and architecture):Ubuntu 16.0.7
 3. Are you using Newman as a library, or via the CLI?CLI
 3. Did you encounter this recently, or has this bug always been there: Not a bug, but a missing feature.
 4. Expected behaviour: Should show json if present there in the request.
 5. Command / script used to run Newman: newman run https://www.getpostman.com/collections/e32ba78064bd59f9daf8D

**Comment by Shivansh2407** [comment]
Can You please explain the issue more elaborately so that I can help you in fixing this.

**Comment by RishabhKodes** [comment]
> Can You please explain the issue more elaborately so that I can help you in fixing this.

When we execute the command to run collection in CLI, it should display the json data the REST API is sending (if the json is present). It's not an issue as of now, but an additional feature that can be added, so closing this issue.
