### ISSUE TITLE
Contributing guidelines not clear about how to debug your changes locally

### ISSUE THREAD

**Issue by aquibbaig** [postmanlabs/newman#2238]
Version and environment information:
 1. Newman Version (can be found via `newman -v`): 4.5.7
 2. OS details (type, version, and architecture): GNU/Linux - Fedora 29
 3. Are you using Newman as a library, or via the CLI? N/A
 3. Did you encounter this recently, or has this bug always been there: N/A
 4. Expected behaviour: N/A
 5. Command / script used to run Newman: newman run
 6. Sample collection, and auxiliary files (minus the sensitive details): N/A
 7. Screenshots (if applicable): N/A

The contributing documentation is not clear about how to run newman locally and debug your changes(after step 6 from below), which makes it tricky for developers getting started. I'd like to add that information to the contributing docs. 
```
1. Clone this repository / your fork of this repository using `git`
2. If not on `develop`, switch to the `develop` branch with `git checkout develop`
3. Run `npm install` in the project directory
4. Make sure everything is working by running `npm test`.
5. Create a new feature branch from `develop` with `feature/your-feature-name`.
6. Make the necessary changes in line with the objective(s) of the pull request
7. Ensure that you have added unit and integration tests for any new features added / bugs fixed
8. Run `npm test`. If any tests fail, resolve the issue with the code, and re-try
9. Once the tests pass, commit and push. **Do not** alter the `version` in `package.json`
10. Create a pull request to `develop`
```

**Comment by shamasis** [comment]
@aquibbaig ... I also think that the contributing guide should add a point or two around:

1. How to pick a feature to build. We shouldn’t just build any feature and build the ones that make a valuable product. How to judge that and how to think of product stories before jumping to code.

2. How to fix a bug. Try to find if a bug is a one off fix or it needs an architectural or bigger change. How to write tests better for bugs to avoid regression.

**Comment by aquibbaig** [comment]
@shamasis Exactly. Anything specific you'd like me to add?

**Comment by jimc404** [comment]
Maybe I'm missing the point here but isn't running `npm link` enough to locally debug nodejs packages. It'll create the needed symlinks to `usr/lib/node_modules/` so we can then use it as a regular package.

Although the other mentioned points can definitely help beginners with starting their contributions.

**Comment by shamasis** [comment]
Another thing around contribution is to think about including around how to think of adding a new feature. Concerns, as discussed in this issue wastes a lot of contributor’s time - https://github.com/postmanlabs/newman/issues/2275#issuecomment-599704875

We need to strictly say that before sending PR for features, it is better to get a green from @codenirvana (to double check its alignment with the ecosystem.)

**Comment by aquibbaig** [comment]
@shamasis Yes, the contributing guidelines can be updated to reflect this too. It's hard to implement those things in Newman which are not clearly thought of in Postman itself.
