### ISSUE TITLE
Running folder by its path

### ISSUE THREAD

**Issue by faressoft** [postmanlabs/newman#2241]
Is it possible to run a specific folder by specifying its path if it is under a parent folder and the subfolders don't have unique names across the entire collection.

**Comment by csk1827** [comment]
@faressoft As far as I know, newman runs the first occurred subfolder when a folder name is specified by `--folder` tag. It is not possible to run a specific subfolder if the subfolders don't have unique names across the entire collection.

**Comment by codenirvana** [comment]
It's essential to have a unique folder/request name.
