### ISSUE TITLE
Npm Test Fails

### ISSUE THREAD

**Issue by TheDhejavu** [postmanlabs/newman#2243]
Version and environment information:
 1. Newman Version (can be found via `newman -v`):
  4.6.0
 2. OS details (type, version, and architecture):
Windows 10
 3. Are you using Newman as a library, or via the CLI?
Via the CLI
 3. Did you encounter this recently, or has this bug always been there:
I was trying to setup CLI on my local computer
 5. Command / script used to run Newman:
npm test
 7. Screenshots (if applicable):
![newman](https://user-images.githubusercontent.com/19678915/75592016-7c3ee880-5a81-11ea-84be-826f8fafdd39.PNG)

#### Steps to reproduce the problem:
1. STEP 1
Clone  https://github.com/postmanlabs/newman
2. STEP 2
cd newman & npm install
3. STEP 3
npm test

**Comment by jimc404** [comment]
There should be more info on this above the coverage table. The screenshot you've shared is a generic error message so it's not possible to infer anything.

**Comment by TheDhejavu** [comment]
@jimc404 the erros above this screenshot i my previous comments can be found in the screenshots
 below

![newman-1](https://user-images.githubusercontent.com/19678915/75614660-67269000-5b3b-11ea-9c32-04673f12ff43.PNG)



![newman-2](https://user-images.githubusercontent.com/19678915/75614668-71e12500-5b3b-11ea-9cd7-c99035d38665.PNG)

**Comment by jimc404** [comment]
Is there any other error message above this?  From this it looks like the CLI can't be loaded properly. Since the failure happens in integration test the core newman should be working properly. You can run the ```test-cli``` script to see if the error only appears here or with the other uses of CLI as well. It won't fix the error, but may give a better idea at what the problem may be

**Comment by TheDhejavu** [comment]
I just finished running `test-cli` and I got a new set of errors.  Could this be an issue with my OS or the test cases

**Comment by jimc404** [comment]
I'd say that there's a fair chance that you're missing out on some step in your computer. Although there's always the chance that it's a software bug, but if that were the case here a sizeable amount of people would have been affected and reported it when this release came out.

**Comment by TheDhejavu** [comment]
Well, I followed the setup process properly. Since no one has reported this issue yet then this could be an issue with my PC or maybe there is something that I'm doing wrongly

**Comment by codenirvana** [comment]
@TheDhejavu Looks like tests are failing because of the reduced test coverage, have you made any changes to the code base or is it failing right after the git clone?

**Comment by TheDhejavu** [comment]
@codenirvana it failed immediately after the git clone, I didn't alter anything. Running `npm test` is part of the setup process. it indicates that the cli is working as expected

**Comment by TheDhejavu** [comment]
I have fixed this issue. I'm just going to close it now. If there is anyone facing this same challenge. I fixed this issue by deleting the forked repo and fork again before cloning to local. thanks
