### ISSUE TITLE
[FEATURE REQUEST] Auto-suggest for newman commands 

### ISSUE THREAD

**Issue by TheDhejavu** [postmanlabs/newman#2244]
### This is a feature Request
What if Newman CLI could have auto-suggest for CLI commands like git commands 
E.G user could mistype help as hlp  

#### Current behavior
The current behavior currently display the below information in the screenshot to the user when a command is mistyped with a missing character 

![newman-auto](https://user-images.githubusercontent.com/19678915/75592349-5cf48b00-5a82-11ea-9909-de04f20182c5.PNG)

#### Proposed behavior using git as a case study 
![auo-newman](https://user-images.githubusercontent.com/19678915/75592480-b8bf1400-5a82-11ea-9df0-e595d53a2d3d.PNG)

**Comment by gittysachin** [comment]
I would like to work on this issue.

**Comment by shamasis** [comment]
Sure. But do note that newman has a very few commands to do autocomplete. There are far higher user impact features and issues that can be tackled instead😊.

If you do work on this, please do read https://github.com/postmanlabs/newman/blob/develop/.github/CONTRIBUTING.md

Post an expected behaviour and also post how someone else will maintain this feature going forward. Which terminals will this work in and what would be the limitations, if any.

**Comment by gittysachin** [comment]
@shamasis Thanks. I'll post all the details about this new feature.

**Comment by TheDhejavu** [comment]
@gittysachin oh well, I waited patiently for a review of this feature before suggesting an implementation but I guess you talked about implementing it first. I hope to see what you create ❤️

**Comment by gittysachin** [comment]
@TheDhejavu I tried to make changes. I think that I coded correctly. But how can I build this and test on my new changes? Cause it's just working on the last version as I cloned the repo.

**Comment by TheDhejavu** [comment]
@gittysachin correct me if I'm wrong, you mean you have been working on a few changes before this and now you trying to implement this new feature on top of these changes? Or you are just starting out and trying to figure out how to build and test it on the new changes made to the repo ?

**Comment by gittysachin** [comment]
@TheDhejavu I tried changing the code and I think I wrote it correctly. But now it's not doing anything new when I'm trying `node ./bin/newman.js v`. So is there any way I can try with my new changes? It's just reacting as the old.

**Comment by TheDhejavu** [comment]
Oh, i get it now. try using a different command like `node ./bin/newman.js --hlp` , it should give a list of defined suggestion like
`do you mean help `

**Comment by gittysachin** [comment]
@TheDhejavu thank you. I tried testing that command. But something was going wrong. It was just saying ```error: invalid command `--hlp` ```. No worries, I'll try to make it again and will look into the problem.

**Comment by TheDhejavu** [comment]
Exactly instead of throwing this kind of error, it should give you a list of related commands to `--hlp`

**Comment by ProBeta1** [comment]
Any updates @gittysachin ?

**Comment by codenirvana** [comment]
Great idea but as mentioned in https://github.com/postmanlabs/newman/issues/2244#issuecomment-595059566, Newman at the moment has only `run` command and on error, it already shows the help text with all the commands and options listed.

Closing this right now, maybe we need something like this once we have 100s of commands like `git` 😅
