### ISSUE TITLE
allure reports fail with error: c.charCodeAt(...).toString(...).padStart 

### ISSUE THREAD

**Issue by izlatkin** [postmanlabs/newman#2252]
newman run xxxx.json -e yyyy.json -r "cli,allure"

#### Finished Execution ####
error: c.charCodeAt(...).toString(...).padStart is not a function

xxxx.json:

{
	"info": {
		"_postman_id": "00df9343-575b-484c-b8c7-18bff04bb41f",
		"name": "PILOT 2",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "4. xxxx [7]",
			"event": [
				{
					"listen": "test",
					"script": {
						"id": "aec4029e-a6ed-49e5-b2da-dcb1825a4df4",
						"exec": [
							"pm.test(\"Status code is 200\", function () {",
							"    pm.response.to.have.status(200);",
							"});",
							"",
							"var jsonData = pm.response.json();",
							"pm.environment.set(\"accountId\", jsonData.accountId);",
							"pm.environment.set(\"subscriberId\", jsonData.subscriptionId);",
							"pm.environment.set(\"baseProductId\", jsonData.baseProductId);"
						],
						"type": "text/javascript"
					}
				}
			],
			"request": {
				"auth": {
					"type": "noauth"
				},
				"method": "POST",
				"header": [
					{
						"key": "Accept",
						"type": "text",
						"value": "application/json",
						"disabled": true
					},
					{
						"key": "Content-Type",
						"type": "text",
						"value": "application/json"
					},
					{
						"key": "x-correlationid",
						"type": "text",
						"value": "{{correlationId1}}"
					},
					{
						"key": "X-Login-Id",
						"value": "YotaSystem",
						"type": "text"
					},
					{
						"key": "X-App-Code",
						"value": "Yota-Core",
						"type": "text"
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\r\n   \"accountProfileId\": \"10004\",\r\n   \"billingProfileId\": \"10002\",\r\n   \"subscription\":{\r\n      \"msisdn\": \"{{msisdn}}\",\r\n      \"imsi\":\"{{imsi}}\",\r\n      \"baseProductId\": \"500000\",\r\n      \"regionOfBuying\": \"{{regionOfBuying}}\"\r\n   },\r\n   \"accountParameters\":[\r\n      {\r\n         \"name\": \"accountExternalId\",\r\n         \"value\": \"{{correlationId1}}\"\r\n      }\r\n   ]\r\n}"
				},
				"url": {
					"raw": "http://{{dapi_host}}/bill/v1/accounts",
					"protocol": "http",
					"host": [
						"{{dapi_host}}"
					],
					"path": [
						"bill",
						"v1",
						"accounts"
					]
				}
			},
			"response": []
		}
	],
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"id": "3e9507ce-f7c9-4656-8869-8ceb5fcdf0e0",
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		},
		{
			"listen": "test",
			"script": {
				"id": "00b2138b-20d7-49de-bf00-ec32445d7410",
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		}
	],
	"protocolProfileBehavior": {}
}

**Comment by codenirvana** [comment]
@izlatkin You can report this issue on the allure reporter issue tracker: https://github.com/ervirendersingh/newman-reporter-allure/issues
