### ISSUE TITLE
(Feature request) Add cli reporter option to print plain unwrapped console logging

### ISSUE THREAD

**Issue by filfreire** [postmanlabs/newman#2255]
## TL;DR:
Let's add a `cli` reporter option that prints plain and unwrapped console logging.

## Purpose
Right now it looks like this:
```
GET http://somerequest
┌
│  <something i console.log'd out>
└
```

I’d like to have the option to just plainly print the output:
```
GET http://somerequest
<something i console.log'd out>
```

Related community discussion [here](https://community.postman.com/t/remove-from-newman-cli-output/11229).

## Proposed solution

A reporter option `cleanConsole` that can be added to as flag to the `newman run` cli command like `--reporter-cli-clean-console` and `--reporter-clean-console`.

**Comment by shamasis** [comment]
One cool thing to do would be to create a new reporter called `newman-reporter-console` and use that in conjunction with console turned off in CLI reporter. 😊

Best part of that would be that there had been a a few requests here and there for being able to log Console to file or pipe it somewhere ... all such console specific features could be packed in that reporter.

Thoughts?

**Comment by SLakhani1** [comment]
@shamasis I think that would be great. Also I want to add one more thing lets pipe all that output on a file and then always keep updating that file and adding the new activities at the end( We can go 2 ways- like whenever we use CLI reporter **always** do saving the logs in the background or we can go with the more flexible flag options as well, In both the options file will be updated in such a way that logs will be entered in the end).
In this way can have the history of collection's as well.
Suggestions?

**Comment by SLakhani1** [comment]
And I would like to work on it.

**Comment by shamasis** [comment]
Haha! That’s a great idea too. Let’s first attempt making separate reporters. It keeps the primary reporter light and purposeful. Also makes it easy to code.

**Comment by SLakhani1** [comment]
Okay great! Then I'll start working on it.

**Comment by VibhorCodecianGupta** [comment]
@shamasis #2270 attempts the use case

**Comment by codenirvana** [comment]
This should be a separate CLI reporter.

Adding this feature will require additional effort to port every new feature in these two modes in the future which will add a lot of complexity to the inbuilt reporter.
