### ISSUE TITLE
Run multiple collections sequentially sharing a common environment.

### ISSUE THREAD

**Issue by lusoalex** [postmanlabs/newman#2262]
Dear,

I was wondering if it is possible (did not find how) to run sequentially two or more collections, but sharing the same environment.

Something like 
```bash
newman run authenticate_collection.json api_collection.json -e environment.json
```

I have a collection that basically login a user and retrieve an access_token.
Then I have multiple collection for several APIs.
I would not to have to copy/paste each time the authentication folder but share it instead.
So the result (access_token) of the authenticate_collection.json would be into the environment, only for the run execution context.

I guess it require to be handle first by postman before newman?
Is this something possible?
Thanks a lot for your help!

**Comment by shubhamjadon** [comment]
@lusoalex  i do not think that running multiple collections sequentially is possible in newman. This feature needs to be added to newman.(something similar was requested in issue #2117 ).

**Comment by lusoalex** [comment]
Hello, thanks for your quick answer. I really appreciate!

It is not totally similar to issue [#2117 ](https://github.com/postmanlabs/newman/issues/2117) as it is not just run collection one by one in a loop, but keep track of new values into the environment (only during the newman execution lifetime)

Regarding the example I gave on the issue, the authentication_collection.json will add an access_token into the environment, that would be used by the api_collection.json.
But in the end, I do not expect the environment to keep this value once newman has finished.

To be transparent, this is because I am developing +10 different APIs and It's annoying to copy/paste the folder containing the request to obtain the access_token. Plus when there's an update on these requests, I have to apply them everywhere.

Please could you tell me if this feature seems "strange/useless" or if you have some workaround?
By the way, I guess it should be implemented first in postman before newman right?

Thanks a lot for you time and expertise!
Alexandre.

**Comment by shubhamjadon** [comment]
@lusoalex there is no feature like the one you asked currently in postman.
But there is a workaround i discovered maybe that could help you. It is as follows:
1. You can change environment variable using Test Scripts(go through this [link](https://learning.postman.com/docs/postman/collection-runs/using-environments-in-collection-runs/) for tutorial). The environment variable will get changed after getting a response from collection run.
2. Then you can use that value in other collection run. As you mentioned it is a access token so you can either add it to url or header of requests.([more info](https://www.youtube.com/watch?time_continue=432&v=HiIJbmjeTPU&feature=emb_title))
3. Now, above is possible if you can run multiple collections sequentially which is currently not possible in postman. Hence, to run them sequentially you will need to add some lines of code(if you want to do this i suggest that you locally install newman library in a folder and do following changes directly in it)
Steps are as follows:

-  Add following code at line 98 (after "var emitter = new EventEmitter(),runner = new runtime.Runner(),stopOnFailure,entrypoint;") (inside node_modules/newman/lib/run/index.js):

```
if(_.isArray(options.collection)){
        let obj = {};
        obj.info = options.collection[0].info;
        obj.info.name = "combined";
        obj.item = [];
        for(let i=0; i<options.collection.length; i++){
            obj.item.push({name:"file"+(i+1),item:options.collection[i].item});
        }
        options.collection = obj;
}
```

-  After adding following changes use newman nodejs module to run your collection. Provide a array of collections like this:
(sample app.js)
```
const newman = require('newman'); // require newman in your project

// call newman.run to pass `options` object and wait for callback
newman.run({
    collection: [require('./authentication_collection.json'),require('./api_collection.json')], 
    reporters: 'cli',
    environment: require('./testEnv.postman_environment.json')
}, function (err) {
	if (err) { throw err; }
    console.log('collection run complete!');
});
```
(The above only works for newman nodejs module)
(Also, if you want info on how to run collection using newman library then see [docs](https://github.com/postmanlabs/newman#using-newman-as-a-library))

(The above implementation will combine all the collections into a single collection and then run it. That's the only way i can think of achieving desired functionality)

I hope this helps.

**Comment by lusoalex** [comment]
Thanks for your help, I'll try them asap.
👍

**Comment by ahghatol** [comment]
@shubhamjadon

I tried the solution you have given to run multiple collections.

I observed that with the solution you have provided, the pre-request script does not work. I was trying to set variables (e.g token) in per request script at the collection level.
