### ISSUE TITLE
stream.js error

### ISSUE THREAD

**Issue by DR-BoneZ** [postmanlabs/newman#227]
While running a collection that works within the postman client, throws following error:
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: EISDIR, read
    at Error (native)

**Comment by abhijitkane** [comment]
Is this happening with only one collection file, or any collection that you try? If it's only with one collection, can you send the collection file to help@getpostman.com?

Also, is there any other line in the stack trace?

**Comment by DR-BoneZ** [comment]
This error seems to be correlated to any request that includes a file to upload. I worked around this by using a different submission method with the rest API I was using, but if there is a way to still do it with the file upload that would be helpful.

That was the entire printout from stderr.

**Comment by abhijitkane** [comment]
Requests with file uploads can be run in Newman - http://blog.getpostman.com/2014/11/15/using-newman-to-run-collections-with-file-post-requests/

**Comment by digital-abyss** [comment]
@Dr-BoneZ , @abhijitkane -- I've seen this too when a request with a file upload is cloned, even if you change the request type (say to a GET), the emitted JSON collection still has the following fields, which I think may cause issues for newman.:

```
			"data": [
				{
					"key": "data",
					"value": "",
					"type": "file",
					"enabled": true
				}
			],
			"dataMode": "params",
```

I've fixed my collection by removing those fields, or removing the data field and switching the dataMode to an appropriate type for other request types (e,g, "raw").  I don't know whether newman should handle this better, or if postman should remove these fields a bit more proactively.

**Comment by kunagpal** [comment]
@DR-BoneZ  @digital-abyss Newman now supports file uploads correctly, do go ahead and try it out.
