### ISSUE TITLE
What happened to the -r option ?

### ISSUE THREAD

**Issue by dhoyt** [postmanlabs/newman#228]
I would like to specify the maximum amount of milliseconds that each request can take using this option 

-r, --requestTimeout [number]   Specify a request timeout (in ms) for a request

but it tells me ... error unknown option '-r'

It this option still available ? ... I hope so.

Thanks

**Comment by abhijitkane** [comment]
I'm able to use it in v1.2.17 of Newman - 
![screen shot 2015-07-16 at 08 59 51](https://cloud.githubusercontent.com/assets/681190/8714989/1baa76e0-2b99-11e5-854d-b7291c092e86.png)

**Comment by dhoyt** [comment]
I'm running 1.2.15

![image](https://cloud.githubusercontent.com/assets/10944880/8722789/2ad099fe-2b96-11e5-8320-6c924b3c33ea.png)

**Comment by abhijitkane** [comment]
The option was only added in 1.2.16.

**Comment by dhoyt** [comment]
Ok ... thanks !!
