### ISSUE TITLE
How do I add new commands?

### ISSUE THREAD

**Issue by KIRA009** [postmanlabs/newman#2282]
I am looking to contribute to the project. I was looking for a way to add new commands. Which file or directory should I look into for that? Could you please guide me as to how a command is executed from the time it is entered, to the time the response is generated.

**Comment by jimc404** [comment]
Look into `bin/newman.js` and from there just follow the imports. You can also take a look at `commander.js` docs as it's used to implement the input part.

**Comment by codenirvana** [comment]
Closing as per https://github.com/postmanlabs/newman/issues/2282#issuecomment-602448204
