### ISSUE TITLE
Request about patch with higher version of postman-runtime to 4.6 tag

### ISSUE THREAD

**Issue by jwasek** [postmanlabs/newman#2283]
Hi,
Could you create a new tag (ex 4.6.1) with a higher and not vulnerable version of postman-runtime? I saw that you have proper version on the dev branch.

I use 4.6 tag, but snyk throw security issue related to postman-runtime and hardcoded version of crypto-js.

Regards

**Comment by codenirvana** [comment]
Fixed in Newman v5.
