### ISSUE TITLE
CLI issue with package.json scripts

### ISSUE THREAD

**Issue by alexkaufman06** [postmanlabs/newman#2284]
1. Newman Version (can be found via `newman -v`): 4.6.0

 2. OS details (type, version, and architecture): macOS Mojave: Version 10.14.6

 3. Are you using Newman as a library, or via the CLI? CLI

 3. Did you encounter this recently, or has this bug always been there: Recently

 4. Expected behaviour:
 When I run newman as a script in my package.json with a collection that contains a failing test. I expect the script to run without failure.

 5. Command / script used to run Newman: 
**I have this script in package.json:**
    "newman:reports": "newman run postman-collections/tests.json -e postman-collections/test.json -r htmlextra,json --reporter-json-export newman/test-run.json --reporter-htmlextra-export newman/test-run.html",
**I run this in terminal:**
npm run newman:reports
**I get this:**
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! automation@0.0.0 newman:reports: `newman run postman-collections/nerp.json -e postman-collections/test.json -r htmlextra,json --reporter-json-export newman/test-run.json --reporter-htmlextra-export newman/test-run.html`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nerp@0.0.0 newman:reports script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexk/.npm/_logs/2020-03-23T19_57_57_550Z-debug.log
**Here is the debug.log**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'newman:reports' ]
2 info using npm@6.11.3
3 info using node@v10.15.3
4 verbose run-script [ 'prenewman:reports', 'newman:reports', 'postnewman:reports' ]
5 info lifecycle automation@0.0.0~prenewman:reports: automation@0.0.0
6 info lifecycle automation@0.0.0~newman:reports: automation@0.0.0
7 verbose lifecycle automation@0.0.0~newman:reports: unsafe-perm in lifecycle true
8 verbose lifecycle automation@0.0.0~newman:reports: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/alexk/Desktop/Repositories/nerp/node_modules/.bin:/Users/alexk/.rvm/gems/ruby-2.6.3/bin:/Users/alexk/.rvm/gems/ruby-2.6.3@global/bin:/Users/alexk/.rvm/rubies/ruby-2.6.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alexk/.okta/bin:/Users/alexk/.rvm/gems/ruby-2.6.3/bin:/Users/alexk/.rvm/gems/ruby-2.6.3@global/bin:/Users/alexk/.rvm/rubies/ruby-2.6.3/bin:/Users/alexk/.rvm/bin:/Users/alexk/Desktop/Repositories/jMeter/apache-jmeter-5.1.1/bin/:/Users/alexk/.rvm/bin:/Users/alexk/Desktop/Repositories/jMeter/apache-jmeter-5.1.1/bin/
9 verbose lifecycle automation@0.0.0~newman:reports: CWD: /Users/alexk/Desktop/Repositories/system-tests
10 silly lifecycle  automation@0.0.0~newman:reports: Args: [ '-c',
10 silly lifecycle   'newman run postman-collections/asdfs.json -e postman-collections/test.json -r htmlextra,json --reporter-json-export newman/test-run.json --reporter-htmlextra-export newman/test-run.html' ]
11 silly lifecycle automation@0.0.0~newman:reports: Returned: code: 1  signal: null
12 info lifecycle automation@0.0.0~newman:reports: Failed to exec newman:reports script
13 verbose stack Error: automation@0.0.0 newman:reports: `newman run postman-collections/asdf.json -e postman-collections/test.json -r htmlextra,json --reporter-json-export newman/test-run.json --reporter-htmlextra-export newman/test-run.html`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid automation@0.0.0
15 verbose cwd /Users/alexk/Desktop/Repositories/system-tests
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "newman:reports"
18 verbose node v10.15.3
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 1
22 error automation@0.0.0 newman:reports: `newman run postman-collections/service-tests.json -e postman-collections/test.json -r htmlextra,json --reporter-json-export newman/test-run.json --reporter-htmlextra-export newman/test-run.html`
22 error Exit status 1
23 error Failed at the automation@0.0.0 newman:reports script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

 6. Sample collection, and auxiliary files (minus the sensitive details):
{
	"info": {
		"_postman_id": "nerp",
		"name": "nerp",
		"description": "nerp",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "nerp",
			"event": [
				{
					"listen": "test",
					"script": {
						"id": "nerp",
						"exec": [
							"const json = JSON.parse(responseBody);",
							"const access_token = json.access_token;",
							"",
							"pm.environment.set('userJwt', access_token);",
							"",
							"pm.test(\"Get JWT\", function () {",
							"    pm.response.to.have.status(200);",
							"    console.log(responseBody);",
							"});",
							""
						],
						"type": "text/javascript"
					}
				}
			],
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "urlencoded",
					"urlencoded": [
						{
							"key": "grant_type",
							"value": "http://auth0.com/oauth/grant-type/password-realm",
							"type": "text"
						},
						{
							"key": "client_id",
							"value": "nerp",
							"type": "text"
						},
						{
							"key": "client_secret",
							"value": "nerp",
							"description": "Required for confidential clients.",
							"type": "text"
						},
						{
							"key": "audience",
							"value": "nerp",
							"type": "text"
						},
						{
							"key": "nerp",
							"value": "nerp",
							"type": "nerp"
						},
						{
							"key": "nerp",
							"value": "nerp",
							"type": "text"
						},
						{
							"key": "nerp",
							"value": "nerp",
							"description": ".",
							"type": "text"
						},
						{
							"key": "scope",
							"value": "",
							"type": "text",
							"disabled": true
						}
					]
				},
				"url": {
					"raw": "nerp",
					"protocol": "https",
					"host": [
						"login",
						"test",
						"dat",
						"com"
					],
					"path": [
						"nerp",
						"nerp2"
					]
				},
				"description": "nerp"
			},
			"response": []
		},
		{
			"name": "nerp",
			"event": [
				{
					"listen": "test",
					"script": {
						"id": "nerp",
						"exec": [
							"let rateLimitingLoops = parseInt(pm.environment.get('rateLimitingLoops'));",
							"console.log('start: ', rateLimitingLoops);",
							"",
							"if (rateLimitingLoops < 12) {",
							"    rateLimitingLoops++;",
							"    pm.environment.set('rateLimitingLoops', rateLimitingLoops);",
							"    pm.test(\"asdf\", function () {",
							"        pm.response.to.have.status(422);",
							"        console.log(responseBody);",
							"        console.log('test run: ', rateLimitingLoops);",
							"    });",
							"    setTimeout(function(){}, [100]);",
							"    postman.setNextRequest(\"asdf\");",
							"} else {",
							"    pm.test(\"asdf\", function () {",
							"        pm.response.to.have.status(429);",
							"        console.log(responseBody);",
							"    });",
							"    pm.environment.set('rateLimitingLoops', 1);",
							"}"
						],
						"type": "text/javascript"
					}
				}
			],
			"request": {
				"method": "POST",
				"header": [
					{
						"key": "Content-Type",
						"name": "Content-Type",
						"type": "text",
						"value": "application/json"
					},
					{
						"key": "asdf",
						"value": "asdf",
						"type": "text"
					},
					{
						"key": "asdf",
						"value": "Bearer {{userJwt}}",
						"type": "text"
					},
					{
						"key": "Content-Length",
						"value": "79",
						"type": "text",
						"disabled": true
					},
					{
						"key": "origin",
						"value": "http://localhost:3100",
						"type": "text"
					},
					{
						"key": "referer",
						"value": "http://localhost:3100/asdf",
						"type": "text"
					},
					{
						"key": "sec-fetch-mode",
						"value": "cors",
						"type": "text"
					},
					{
						"key": "sec-fetch-site",
						"value": "cross-site",
						"type": "text"
					},
					{
						"key": "User-Agent",
						"value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36",
						"type": "text"
					},
					{
						"key": "asdf",
						"value": "asdf",
						"type": "text",
						"disabled": true
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\n\t\"asdf\": \"nerp\",\n\t\"fff\": 12345678,\n\t\"emailAddress\": \"nerp@nerp.com\"\n}",
					"options": {
						"raw": {}
					}
				},
				"url": {
					"raw": "{{nerp}}/nerp",
					"host": [
						"asdf"
					],
					"path": [
						"ad",
						"asdf",
						"nerp",
						"adsfff"
					]
				}
			},
			"response": []
		}
	],
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"id": "nerp",
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		},
		{
			"listen": "test",
			"script": {
				"id": "nerp",
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		}
	],
	"protocolProfileBehavior": {}
}

**Comment by codenirvana** [comment]
I don't feel this issue is related to Newman.

Can you share a sample package that we can use to reproduce this issue locally?

**Comment by alexkaufman06** [comment]
We ended up going a different route for this project. Since no one else is reporting this I'll close it.
