### ISSUE TITLE
Access variables from a callback

### ISSUE THREAD

**Issue by bobotzzz** [postmanlabs/newman#2294]
1. Newman Version (can be found via `newman -v`): 4.6.0
 2. OS details (type, version, and architecture): macos
 3. Are you using Newman as a library, or via the CLI: Library
 3. Did you encounter this recently, or has this bug always been there: recently
 4. Expected behaviour: access variable from newman.run .on() callback
 5. Command / script used to run Newman: 
for example:

newman.run({
        collection: require(collection),
        environment: require(environment),
        globals: require(globals),
        delayRequest: timeout*100,
        reporters: 'cli'
    }, function (err) {
        if (err) { throw err; }
        console.log('collection run complete!');
    }).on('start', function (err, args) { // on start of run, log to console
        console.log('running a collection...');
        console.log('global variables...', pm.globals);

 6. Sample collection, and auxiliary files (minus the sensitive details): n/a
 7. Screenshots (if applicable): n/a

**Comment by narayanpai1** [comment]
The second argument is actually the RunSummary object. You can find out more about this object [here](https://github.com/postmanlabs/newman#newmanruncallbackerror-object--summary-object).

You can access globals from your function by ``args.globals``.

**Comment by codenirvana** [comment]
Closing as per https://github.com/postmanlabs/newman/issues/2294#issuecomment-629609758

**Comment by bobotzzz** [comment]
> The second argument is actually the RunSummary object. You can find out more about this object [here](https://github.com/postmanlabs/newman#newmanruncallbackerror-object--summary-object).
> 
> You can access globals from your function by `args.globals`.

Hi, While that is true for the newman.run callback, it is not true for the callback inside a newman event. For these events, the callbacks are not even documented.
A use case I see this fit for exposing variables in events callback, is when a certain libs are used for email or websockets handling. This way, for example, after a response is received, in that event, certain checks can be validated using collection variables.
@codenirvana please review what I said and reopen this issue.
