### ISSUE TITLE
What am I missing or doing wrong ?

### ISSUE THREAD

**Issue by dhoyt** [postmanlabs/newman#230]
Here is my console ...

![image](https://cloud.githubusercontent.com/assets/10944880/8747272/4cbe82f0-2c5f-11e5-8c9c-8df2404ab3ae.png)

I installed 'unirest' globally and in my javaScript I have ...

var unirest = require("unirest");

**Comment by czardoz** [comment]
@dhoyt Have you set your ``NODE_PATH`` environment variable? Check out this question if you have not: http://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows

Basically, installing a module globally does not make it available for inclusion automatically. The ``-g`` option only places executables (if any) on your system ``PATH``.

**Comment by dhoyt** [comment]
@czardoz ... thank you very much ... that was it !
