### ISSUE TITLE
Newman does not replace variable in URL when using first variable from data source file

### ISSUE THREAD

**Issue by marcomaespolteq** [postmanlabs/newman#2311]
Hi all,

I have a collection with 1 request which look like this:
GET https://www.example.com/price_read?Phase={{PhaseCode}}&CaseType={{CaseTypeCode}}&Date=2020-12-31
When I run this in Postman with a simple CSV as input where the name of the variables are coming from, everything works great.
When I run this in newman with the same data, the first variable is replaced by the value from the CSV, but the second value stays a variable name.
With the example as provided under this message the response lookse like:
GET https://www.example.com/price_read?Phase=84&CaseType={{CaseTypeCode}}&Date=2020-12-31
GET https://www.example.com/price_read?Phase=85&CaseType={{CaseTypeCode}}&Date=2020-12-31

And because of that, my tests fail.
The strange thing is that PhaseCode is the third field in the CSV and CaseTypeCode is the first field. And PhaseCode works.

I changed the position of the variable in the url and that doesn't change the be behaviour. Still PhaseCode is replaced. So it looks like this:
GET https://www.example.com/price_read?CaseType={{CaseTypeCode}}&Phase=84&Date=2020-12-31
GET https://www.example.com/price_read?CaseType={{CaseTypeCode}}&Phase=85&Date=2020-12-31

When I add an extra column in the CSV on the first position, the variable is replaced!
So looking at this finding, it seems that newman has problems with the first variable in the header of a CSV. Postman does not have this problem.

I wanted to create an example, which I added.
[example.zip](https://github.com/postmanlabs/newman/files/4456039/example.zip)
newman run price.postman_collection.json -d prices.csv
Results in:
Iteration 1/2

→ price
  GET https://www.example.com/?param1={{param1}}&param2=2 [200 OK, 1005B, 579ms]

Iteration 2/2

→ price
  GET https://www.example.com/?param1={{param1}}&param2=4 [200 OK, 1005B, 126ms]

newman run price.postman_collection.json -d prices_extra_colomn.csv
Results in:
Iteration 1/2

→ price
  GET https://www.example.com/?param1=1&param2=2 [200 OK, 1005B, 581ms]

Iteration 2/2

→ price
  GET https://www.example.com/?param1=3&param2=4 [200 OK, 1005B, 140ms]

**But during the creation of that example I found out that it only seems to occur when the CSV has a UTF-8 with BOM (which Excel seems to add to the file)
When the example data has no BOM, so just UTF-8 the problem doesn't occur.**

So this is still a different behaviour between Postman and Newman. And in my opinion newman should also work if the file has a BOM. 

 1. Newman Version (can be found via `newman -v`):
4.5.4
 2. OS details (type, version, and architecture):
MacOS 10.15.4
 3. Are you using Newman as a library, or via the CLI?
CLI
 3. Did you encounter this recently, or has this bug always been there:
recently (but never used it like this before)
 4. Expected behaviour:
All variables should be replaced in url
 5. Command / script used to run Newman:
newman run price.postman_collection.json -e price.postman_environment.json -d prices.csv -n 2
 6. Sample collection, and auxiliary files (minus the sensitive details):
CaseTypeCode,CaseType,PhaseCode,Phase
30101,Case 1,84,Phase 1
30101,Case 2,85,Phase 2
 7. Screenshots (if applicable):
<img width="694" alt="Screenshot 2020-04-09 at 11 59 14" src="https://user-images.githubusercontent.com/49234445/78883284-993fe180-7a59-11ea-9aec-11b0755c3754.png">

**Comment by codenirvana** [comment]
@marcomaespolteq Thanks for sharing the example collection and data files, I can reproduce this issue locally with Newman v4 and this behavior is because of the BOM character in the input CSV.

We recently fixed this issue with #2303 and the fix is available in Newman v5.

Also, check the [v4 to v5 migration guide](https://github.com/postmanlabs/newman/blob/develop/MIGRATION.md#migrating-from-v4-to-v5) and [changelog](https://github.com/postmanlabs/newman/blob/v5.0.0/CHANGELOG.yaml#L1) for more details.
