### ISSUE TITLE
--env-var is unknown option in v5

### ISSUE THREAD

**Issue by rparsonsbb** [postmanlabs/newman#2313]
1. Newman Version (can be found via `newman -v`): 5.0.0
 2. OS details (type, version, and architecture): linux, windows
 3. Are you using Newman as a library, or via the CLI? cli
 3. Did you encounter this recently, or has this bug always been there: recently, 5.0 release
 4. Expected behaviour: --env-var is an accepted option
 5. Command / script used to run Newman: newman --env-var key=value run test.json
 6. Sample collection, and auxiliary files (minus the sensitive details): not needed
 7. Screenshots (if applicable): not needed

**Comment by codenirvana** [comment]
@rparsonsbb With Newman v5, `--env-var` option is acceptable by the `run` command and not as a free-form option.

So, changing the order of `--env-var` option from `newman --env-var key=value run test.json` to `newman run --env-var key=value test.json` will fix your issue.
