### ISSUE TITLE
RunSummary does'nt return timings -> completed if use bail

### ISSUE THREAD

**Issue by liberstein** [postmanlabs/newman#2316]
1. Newman Version: 5.0.0
 2. OS details : Ubuntu 18.04.1 x64
 3. Newman as a library
 3. this bug always been there: RunSummary -> run -> timings doesnt has **completed**
 4. Expected behaviour: RunSummary -> run -> timings  has **completed**
 5. Command / script used to run Newman: newman run
 6. Sample collection, and auxiliary files : any collection with error 
 7. Screenshots : http://i.imgur.com/AhzX8Uz.png http://i.imgur.com/iMnhahg.png

Steps to reproduce the problem:
1.  options.bail: ['folder']
2.  newman run

**Comment by DannyDainton** [comment]
Hey @liberstein 

I'm going to close this issue out for now but if you're still having problems, we can open it again.
