### ISSUE TITLE
Error while installing newman on windows 7 64 bit

### ISSUE THREAD

**Issue by mverma-va** [postmanlabs/newman#232]
I am getting error while installing newman on windows 7 Pro (64 bit OS)
Steps: 
1. Install node.js package from link https://nodejs.org/download/ (Windows 64 bit msi file)
2. Now running the command in cmd prompt "npm install -g newman" gives error.
See attachment.

Kindly look into this asap, also note that I cannot install Visual Studio because of company policy. So will newman work without that or any workaround.
![2015-07-20 12_25_26-administrator_ command prompt](https://cloud.githubusercontent.com/assets/4573058/8784292/7178568a-2ede-11e5-98af-24d26e55d368.png)

**Comment by mverma-va** [comment]
Also note that I tried this from one of the blog post.
http://blog.getpostman.com/2015/04/09/installing-newman-on-windows/
"As a workaround, you can install version 1.2.10 of Newman (npm install newman@1.2.10), and downgrade your Node installation to an older version (v0.10.33 is confirmed to be working)"

So the install worked but now I get error that "'newman' is not recognized as an internal or external command, operable program or batch file."
I tried adding the path "C:\node_modules\newman\" to system env. variable "PATH" but it is not working.

**Comment by czardoz** [comment]
Hey @mverma-va, adding the ``node_modules`` folder to your ``PATH`` won't work, since the newman executable is not present in your ``node_modules`` folder. You need to add the newman "bin" folder to your path. It should be ``<whatever>\node_modules\newman\bin\``.

**Comment by mverma-va** [comment]
I should have mentioned that already, that I did added bin path as well "C:\node_modules\newman\bin"
So adding both or any of the two path did not work for me, after opening the cmd prompt again.

**Comment by czardoz** [comment]
If I understand correctly, you want to persistently change your ``PATH`` variable. While I don't have a windows box immediately at hand, could you try the steps outlined [here](http://stackoverflow.com/questions/23400030/windows-7-add-path)? 

This will ensure that the changes to your ``PATH`` persist across different ``cmd`` sessions.

**Comment by mverma-va** [comment]
Yes, I did set the path in system variable under advance system setting dash dash :)
I guess that's what you mean, right?

Also my original problem is I want to install the latest newman version, so I need solution for the issue mentioned in comment#1 :(

**Comment by mverma-va** [comment]
Hello,
Can someone please help here, I am still getting the issue where windows command prompt does not recognize newman. I have installed version 1.2.10 of Newman (npm install newman@1.2.10)
![2015-07-23 11_36_53-administrator_ command prompt](https://cloud.githubusercontent.com/assets/4573058/8857524/7898bd12-312f-11e5-81b0-daec39190d49.png)

**Comment by mverma-va** [comment]
Hello,
Can someone please help here, I am still getting the issue where windows command prompt does not recognize newman. I have installed version 1.2.10 of Newman (npm install newman@1.2.10)

![2015-07-23 11_40_05-administrator_ command prompt](https://cloud.githubusercontent.com/assets/4573058/8857555/9f3052aa-312f-11e5-8e63-6cbca50ca09d.png)

**Comment by wbrooks1981** [comment]
Depends on what you are trying to accomplish.  
1) Do you mean for newman to be usable globally no matter what directory the cmd prompt is in.  If so you need to install it globally.  npm install newman -g.  In addition whatever your global install directory, a lot of the time the default would be: c:\users\USERNAME\appData\roaming\npm,  make sure that is included in the Environment PATH variable. 

2) If you mean to run newman locally  from that specific directory above,   utilize node first.   
node newman -c 'mycollection.json' -e 'myenv.json'

**Comment by mverma-va** [comment]
@wbrooks1981 thank you so much it worked.....damm me for not knowing -g is for global :dart:

BTW can anyone tell me if I can install latest version of node.js and newman without installing VS and .NET FW on windows 7.

**Comment by jojoblaze** [comment]
I opened an issue about this problem some month ago 
https://github.com/postmanlabs/newman/issues/208

**Comment by mverma-va** [comment]
thanks @jojoblaze , I hope there is a solution for this and I could use the latest version of newman with all the bug fixes and any new features added to it.

**Comment by mverma-va** [comment]
@jojoblaze BTW for me node-v0.10.33-x64 and newman 1.2.10 works fine on windows so far, in case u wanna giv it a try.

**Comment by jojoblaze** [comment]
I have other tools in my CI pipeline that use node-v0.12. at the moment switch to an older version could be painful. it's a shame cause I'd really like to integrate newman.

**Comment by czardoz** [comment]
We've released Newman v2.0 Beta, which has a much more painless installation process on Windows. The caveat is that you need Node v4.0+ for it to work. 

The details on how to install the Beta are in the [readme](https://github.com/postmanlabs/newman/). In the future, Newman will be dropping support for Node v0.12 altogether, to simplify the installation issues. 

I'm closing this issue since there are no concrete actionable items here. Newman v2.0 (Beta) will definitely solve most of these installation issues, so do try it out. :)

**Comment by ram2705** [comment]
npm ERR! EINVAL: invalid argument, mkdir 'C:\Users\ac\'C:\Program\_cacache\tmp'

getting this error while installing on Win 10
