### ISSUE TITLE
--environment option fails to find file

### ISSUE THREAD

**Issue by rhythmicdevil** [postmanlabs/newman#2320]
1. Newman Version (can be found via `newman -v`): 5.0.0
 2. OS details (type, version, and architecture): CentOS Linux release 7.7.1908 (Core) 
 3. Are you using Newman as a library, or via the CLI? Docker
 3. Did you encounter this recently, or has this bug always been there: Just found it
 4. Expected behaviour: That the command executes and uses the arguments provided.
 5. Command / script used to run Newman: 
```
docker run -v ~/collections:/etc/postman -t postman/newman     https://www.getpostman.com/collections/df0a40ef41d570c48154     --environment="HTTPBinNewmanTest.json.postman_environment"     --reporters junit --reporter-junit-export="newman-report.xml"
```
 6. Sample collection, and auxiliary files (minus the sensitive details):
This command was taking from the docker hub [repository](https://hub.docker.com/r/postman/newman/) so I dont have access to the collection. 

Steps to reproduce the problem:
1. Copy the command from the Docker Hub Repository and execute it on the CLI. 

This is the result:
```
$ docker run -v ~/collections:/etc/postman -t postman/newman     https://www.getpostman.com/collections/df0a40ef41d570c48154     --environment="HTTPBinNewmanTest.json.postman_environment"     --reporters junit --reporter-junit-export="newman-report.xml"
error: unknown option '--environment=HTTPBinNewmanTest.json.postman_environment'
```

**Comment by codenirvana** [comment]
@rhythmicdevil Looks like you are missing the [run command](https://github.com/postmanlabs/newman#newman-run-collection-file-source-options), e.g:

```console
$ docker run -t postman/newman run <collection-file-source>
```

In your case, this will fix your issue:

```console
$ docker run -v ~/collections:/etc/postman -t postman/newman run https://www.getpostman.com/collections/df0a40ef41d570c48154     --environment="HTTPBinNewmanTest.json.postman_environment"
```

**Comment by rhythmicdevil** [comment]
For reference I copied that command directly from the [Docker Hub page](https://hub.docker.com/r/postman/newman/). And its not missing the run command. Look at the example I posted please.

**Comment by codenirvana** [comment]
@rhythmicdevil Thanks for reporting this issue, looks like the docker hub documentation is not updated after the Newman v4 release. Few of the examples are still using the discontinued v3 CLI options.

The correct usage should be:
```
docker run -v ~/collections:/etc/postman -t postman/newman run\
    https://www.getpostman.com/collections/df0a40ef41d570c48154 \
    --environment="HTTPBinNewmanTest.json.postman_environment" \
    --reporters junit --reporter-junit-export="newman-report.xml"
```

**Comment by rhythmicdevil** [comment]
Why does the 'run' command appear twice?

**Comment by rhythmicdevil** [comment]
Please explain why this is not working. 

`[swright@swright-dev-05 collections]$ ll
total 12
-rw-rw-r--. 1 swright swright 2737 Apr 17 14:01 environment.json
-rw-rw-r--. 1 swright swright 7154 Apr 17 14:01 globals.json
[swright@swright-dev-05 collections]$ 
[swright@swright-dev-05 collections]$ 
[swright@swright-dev-05 collections]$ 
[swright@swright-dev-05 collections]$ docker run -v ~/collections:/etc/postman -t postman/newman run    https://www.getpostman.com/collections/8a0c9bc08f062d12dcda     --environment="environment.json"     --globals="globals.json"     --reporters junit --reporter-junit-export="newman-report.xml"
error: ENOENT: no such file or directory, open 'environment.json'

[swright@swright-dev-05 collections]$ `

**Comment by codenirvana** [comment]
@rhythmicdevil as mentioned in the error message `error: ENOENT: no such file or directory, open 'environment.json'`.

There's no `environment.json` file in the current working directory.

**Comment by mbhassan** [comment]
I get the same error

```
error: ENOENT: no such file or directory, open 'environment.json'
```

whats the cwd for postman? Because in @rhythmicdevil example they are in the collections folder which is mounted to /etc/postman ...

**Comment by mbhassan** [comment]
Nvm the documentation is grossly wrong. Here's the correct way to run it
```
docker run -v ~/postman_collections:/etc/newman -t postman/newman run "postman_collection.json" --environment="postman_environment.json"
```

Notice that 

```
/etc/newman
```
is the WORKDIR for the docker container.

**Comment by rhythmicdevil** [comment]
Thank you.
