### ISSUE TITLE
Newman scenario?

### ISSUE THREAD

**Issue by huguesbr** [postmanlabs/newman#2321]
Hey,

I love postman / newman. We use it extensively to test our API. 

We’ve created basic scenario ( requests in folder ): signup, signin, add product to cart, checkout. 
Unfortunately this requests can’t be shared with other scenario and need to be duplicated ( and later maintain ). 

So I’ve build a gem ( sorry ruby is my language ^^ ) to do so:

https://github.com/huguesbr/newman_scenario

Launch it, set your postman API token, pick a collection and env ( supporting workspace ) and cherry pick some requests to be chain. The list of requests ( name ) is store in a local JSON file and uses to be a new collection extracting this requests from the main collection and running this collection using postman. 

Let me know what you think and if you like it will add a PR to mention in README

Thanks you anyway for this really great tooling ^^

**Comment by DannyDainton** [comment]
Hey @huguesbr, 

I'm going to close out this issue but this seems like something that could be shared with other Postman/Newman users over on our community site.

https://community.postman.com/
