### ISSUE TITLE
Exporting Global Variables for Every Entry in Data File

### ISSUE THREAD

**Issue by RuchiTrehan2** [postmanlabs/newman#2324]
Version and environment information:

 1. Newman Version (can be found via `newman -v`): 5.0.0
 2. OS details (type, version, and architecture): Windows 10, 64-bit
 3. Are you using Newman as a library, or via the CLI? CLI

I am using a data File (csv) having 3 rows. I need to export global variables json.
I know there is an option --export-globals to export final global variables into a json file. But i need to export separate global variables files for each data row of the data file (i.e. in my case 3 global variables json file)
Is it possible in newman ?

**Comment by codenirvana** [comment]
This is not possible out of the box. But maybe you can use Newman as a library to do so.

I recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with issues like these.
