### ISSUE TITLE
next newman.run() is triggered before the previous one ends.

### ISSUE THREAD

**Issue by rajatpuneak** [postmanlabs/newman#2325]
I have Single api call in the opts1 collection,
and multiple calls in opts2,

> "RAMP UP DATA DONE -------------" is printed in cli at 2nd call from 2nd newman run, 
> not before initiation of 2nd block.

```
const newman = require('newman');

    newman.run( opts1, function (err, summary) {
        if (err) {
            throw err;
        }
        else {
            console.log('RAMP UP DATA DONE -------------');
        }
    });

    newman.run( opts2, function (err, summary) {
        if (err) {
            throw err;
        }
        else {
            console.log('Execution Completed -------------');
        }
    });

```

**Comment by atulbi** [comment]
Each collection run is an [asynchronous](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous) operation and callback get called once collection run finishes. So, `RAMP UP DATA DONE -------------` is not printed from 2nd run, but after 1st run got finished.

Learn more about run [here](https://github.com/postmanlabs/newman#api-reference).

**Comment by rajatpuneak** [comment]
@atulbi : Thanks, Above Works

But I have the Run1 and Run2 in 2 different Functions which are Conditional on a Flag,

if (Flag = True)
Run1 then Run2

is what i want to achieve as i want to pass some values generated in Run1 to Run2,

any suggestion to achieve this ?

**Comment by codenirvana** [comment]
@rajatpuneak we recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with issues like these.
