### ISSUE TITLE
How to hide sensitve information like API Keys from report

### ISSUE THREAD

**Issue by praveendvd** [postmanlabs/newman#2326]
The newman report currently has sensitive informations  like API keys and authentication information. Is there a way to hide this ?

Version and environment information:

 1. Newman Version (can be found via `newman -v`):5.0.0
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Always

 4. Expected behaviour:

Option to hide sensitive information

Steps to reproduce the problem:

1. Add authentication method as api key and give details, create report

**Comment by DannyDainton** [comment]
Hey @praveendvd 

Are you still using the CLI for this as this was something that was added to the htmlextra reporter if you use that as your reporter?

**Comment by praveendvd** [comment]
> Hey @praveendvd
> 
> Are you still using the CLI for this as this was something that was added to the htmlextra reporter if you use that as your reporter?

Yes Danny you can close this , thank you so much

**Comment by praveendvd** [comment]
Thanks @DannyDainton  for implementating this in htmlextrareport

**Comment by anandvarkeyphilips** [comment]
@praveendvd @DannyDainton  how to hide this?
