### ISSUE TITLE
URI malformed error coming while executing from Newman works fine in postman

### ISSUE THREAD

**Issue by mr097065** [postmanlabs/newman#2328]
1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by codenirvana** [comment]
@mr097065 Can you share a scaled-down collection (or API endpoint) which we can use to reproduce this issue?

**Comment by mr097065** [comment]
1. newman

**Comment by mr097065** [comment]
URL: You can create a mock server in postman to utilize this as I have utilized my limit. 

/addresses?country=AUS&id=AUG|5f246f9b-7c97-4233-8de7-2d57f74cd86b|7.7305OAUGGwvjBwAAAAAIAgEAAAAAB7zTAAAAAAAAADEAAP..ZAAAAAD.....AAAAAAAAAAAAAAAAAAAAMTc3IHBhY2lmaWMgaHd5AAAAAAA-$15&dataset=GNAF

Response: 200 ok

{
  "addressLine1": "Level 2 111 Pacific Highway",
  "suburb": "SYDNEY",
  "postcode": "2000",
  "country": "Australia",
  "unitNumber": "Level",
  "level": “2”,
  "streetNumber": “111”,
  "streetName": "Pacific",
  "streetType": "Highway",
  "state": "NSW",
  "countryCode": "AUS"
}

I am using Newman Version = 4.5.3
**Error I am getting:** 
Unexpected token 'H' at 1:1
HTTP request parsing failed with error: "Malformed URI: /v1/addresses?country=A
^

This error comes in Newman only while in postman it works fine

**Comment by codenirvana** [comment]
@mr097065 Created a mock server as you suggested but still can't reproduces the issue locally.

<img width="1437" alt="Screenshot 2020-04-26 at 4 54 01 PM" src="https://user-images.githubusercontent.com/4865836/80306081-ab9e7700-87de-11ea-9609-d61f1f3fc730.png">

**Comment by mr097065** [comment]
I suspect it's something that MuleSoft might've patched in CloudHub (for security reasons) and now forcing consumers to encode the URI. Is it possible to encode URI in newman?

**Comment by codenirvana** [comment]
@mr097065 you can either manually encode the additional/unsafe characters which are not encoded automatically or add the following script as part of your Pre-request Script:

```js
pm.request.url.query.each((q) => {
     q.update(encodeURI(q.toString()))
});
```

This script mutates (encodes the additional characters) the request URL before sending it.

Also, can you verify that your request works fine in Postman after enabling the `"Use next generation URL processing"` setting?
<img width="1552" alt="76343092-99977080-6325-11ea-9b37-0e824726847f" src="https://user-images.githubusercontent.com/4865836/80306299-1bf9c800-87e0-11ea-89a8-740bfdd3294a.png">

**Comment by mr097065** [comment]
Thanks. Let me try that and also after enabling setting in postman to "Use next generation URL processing" it doesn't work in postman too.
![image](https://user-images.githubusercontent.com/54430859/80306370-3d6daa80-8806-11ea-84b3-17a46b435e55.png)

**Comment by codenirvana** [comment]
@mr097065 Thanks for the verification.

With this new setting Postman encodes the URL based on the WHATWG URL standard ([know more](https://github.com/postmanlabs/postman-app-support/issues/8154) about this change) which is similar to most of the web browsers.

Are you facing a similar issue when you send this request from Chrome or any other browser?

**Comment by codenirvana** [comment]
@mr097065 The only character which is causing (because it's not encoded) this issue is `|` which needs to be encoded as `%7C` according to your request middleware.

**Comment by mr097065** [comment]
Yes, I get same error in chrome when I hit the URL there.

Below is the error in chrome. 
HTTP request parsing failed with error: "Malformed URI: /v1/addresses?country=AUS&amp;id=AUG|5f246f9b-7c97-4233-8de7-2d57f74cd86b|7.7305OAUGGwvjBwAAAAAIAgEAAAAAB7zTAAAAAAAAADEAAP..ZAAAAAD.....AAAAAAAAAAAAAAAAAAAAMTc3IHBhY2lmaWMgaHd5AAAAAAA-$15&amp;dataset=GNAF"

I just added the provided code in Pre-request Script and it started working fine in postman even after enabling the in "Use next generation URL processing" setting, but as soon as I executed the same request in my local Newman it again failed.

![image](https://user-images.githubusercontent.com/54430859/80306747-727afc80-8808-11ea-90af-d18deb65147b.png)

**Comment by mr097065** [comment]
Yes you are correct only the pipe sign is not getting decoded properly. I will try to decode manually and then run in Newman

**Comment by codenirvana** [comment]
@mr097065 This is probably because of parsing invalid/non-JSON string (maybe the response is different).

Also, This change in the URL processor is enabled by default since Newman v5. I think you are using an older version of Newman locally and v5 on Jenkins.

**Comment by mr097065** [comment]
Yes I am using old version just updated Newman to V 5 and voilà it worked. Closing this issue. Thanks alot for your help.
