### ISSUE TITLE
A very strange behavior (defect??)

### ISSUE THREAD

**Issue by jetpacksfan** [postmanlabs/newman#233]
Hi there,

I'm testing with newman, failed with strange mistake:
![image](https://cloud.githubusercontent.com/assets/13167092/8826440/e8dc0630-30c9-11e5-947a-f8a7d244f238.png)
sometimes failed with other mistakes:
![image](https://cloud.githubusercontent.com/assets/13167092/8826590/f835cd86-30ca-11e5-8751-35bc9b8cc201.png)

It takes me hours to find the way to reproduce it:
1) Use an env in the link
2) If the env contains certain keywords. (I found that 'test', 'tests', 'apps' will triger it)
Try below:
Env is nothing but a url:
```
{
	"id": "672e271e-1f47-e545-6a40-66936265019e",
	"name": "DEMO",
	"values": [
		{
			"key": "serverloc",
			"value": "google.com", // change it to apps.google.com, gootestsgle.com, etc will reproduce
			"type": "text",
			"name": "serverloc",
			"enabled": true
		}
	],
	"timestamp": 1437566898959,
	"synced": false,
	"syncedFilename": ""
}
```
And collection is the simplest one - just navigate to www.google.com/maps
```
{
	"owner": "65578",
	"lastUpdatedBy": "65578",
	"lastRevision": 25853332,
	"team": null,
	"id": "8183b082-877d-9645-94ec-aebf790aee5f",
	"name": "Demo_Collection",
	"description": "",
	"remoteLink": "",
	"order": [
		"e8cce480-6f0b-f797-cb6e-c161d5a52019"
	],
	"requests": [
		{
			"id": "e8cce480-6f0b-f797-cb6e-c161d5a52019",
			"headers": "",
			"url": "www.{{serverloc}}/maps",
			"preRequestScript": "",
			"pathVariables": {},
			"method": "GET",
			"data": [],
			"dataMode": "params",
			"version": 2,
			"tests": "",
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1437572115770,
			"name": "go google",
			"description": "",
			"collectionId": "8183b082-877d-9645-94ec-aebf790aee5f"
		}
	]
}
```

**Comment by jetpacksfan** [comment]
@abhijitkane mate you gonna take a look
I almost decided not to use newman any more
Nearly frustrated by it and totally exhausted

**Comment by czardoz** [comment]
@jetpacksfan This does not look like erroneous behaviour. If you set the variable to ``apps.google.com``, then while running, the URL becomes "www.apps.google.com/maps". If you try to visit "http://www.apps.google.com/maps", it'll throw an error, because the DNS name does not exist. Same with ``gootestsgle.com``. The error you see: ``ENOTFOUND`` means that newman was unable to find the remote address. 

I'm keeping this issue open, so we'll put a better error message in place of just ``ENOTFOUND``.

**Comment by jetpacksfan** [comment]
@czardoz Thanks. But please take a look at the 1st picture.
The url I was visiting in my collection happen to begin with apps.test.xxxx, which is valid url because it's the server our apis rest on.
All test cases failed due to that mistake.

**Comment by czardoz** [comment]
If you were using the same collection, and setting "serverloc" to "apps.test.xxxx", the URL would become "www.apps.test.xxxx", which would throw the error if no CNAME is configured in your DNS settings for "www.apps.test.xxxx". 

I'm trying to reproduce the error in the first picture.

**Comment by jetpacksfan** [comment]
Thank you czardoz. Then my description may not be precise.
when I'm saying "www.apps.test.xxxx" xxxx is just omitted here, when doing the testing of course they're replaced by actual strings. 
Because I just download the collections and env from POSTMAN and run them in newman.
I'll let you know if I find something tomorrow.

**Comment by jetpacksfan** [comment]
To make life easier and also to accelerate your debugging I've sent you an email contact@aniketpanse.in including the collection and env so you can reproduce yourself.

I know invalid urls lead to some errors but should not be that error otherwise I've solved it myself.

![image](https://cloud.githubusercontent.com/assets/13167092/8829769/d281f478-30db-11e5-9580-e24f3aaf1d25.png)

**Comment by czardoz** [comment]
Thanks for sharing the files, @jetpacksfan!

Here is what I was able to find out: 

1) Newman throws a ENOTFOUND error if the DNS record does not exist. This is the reason why "www.apps.google.com", and "gootestsgle.com" etc show that error. 

2) If the response body is empty, the value of ``responseBody`` is ``undefined``. This is the reason for the "Cannot read property 'has' of undefined" errors. 

3) The errors definitely have nothing to do with the "apps" or "test" strings in the URLs. Here's a simple collection (it has only one request) that works with "serverloc" set to "apps.google.com":

```
{
	"id": "4aaffd8a-c1d7-5a22-3bf0-79ecfbe5fbf0",
	"name": "test issue #233",
	"description": "Trying to reproduce https://github.com/postmanlabs/newman/issues/233",
	"order": [
		"f53d5219-6036-31ca-bb44-1cea9c11bd42"
	],
	"folders": [],
	"timestamp": 1437633900852,
	"owner": "61671",
	"remoteLink": "",
	"public": false,
	"requests": [
		{
			"id": "f53d5219-6036-31ca-bb44-1cea9c11bd42",
			"headers": "",
			"url": "http://{{serverloc}}",
			"pathVariables": {},
			"preRequestScript": "",
			"method": "GET",
			"collectionId": "4aaffd8a-c1d7-5a22-3bf0-79ecfbe5fbf0",
			"data": [],
			"dataMode": "params",
			"name": "http://{{serverloc}}",
			"description": "",
			"descriptionFormat": "html",
			"time": 1437635444925,
			"version": 2,
			"responses": [],
			"tests": "",
			"currentHelper": "normal",
			"helperAttributes": {}
		}
	]
}
```

Associated Environment:
```
{
	"id": "25c52d73-03ce-0305-ab32-3c50f9795895",
	"name": "test_233",
	"values": [
		{
			"key": "serverloc",
			"value": "apps.google.com",
			"type": "text",
			"name": "serverloc",
			"enabled": true
		}
	],
	"timestamp": 1437635065317,
	"synced": false,
	"syncedFilename": ""
}
```

I ran the above using newman:

```
aniket [~/tmp/workdir] -> newman -c ./issue_233_collection.json -e ./issue_233_env.json 

Iteration 1 of 1
200 9316ms http://{{serverloc}} http://apps.google.com

Summary:

Parent                   	Pass Count	 FailCount
-------------------------------------------------------------
Collection test issue ...	         0	         0

Total                    	         0	         0

```

**Comment by jetpacksfan** [comment]
@czardoz Thank you. I agree with your findings. For this issue I think you'd better add a mechanism to make the reason clearer so the users can have a correct way to do something. For example add a -debug option so newman can optionally generate a log file, and users can at least paste the contents here, saving your time of debugging. 

And also, however, I believe there might be some other scenarios to reproduce this issue. 
When I first met the issue, I just downloaded the collection and environment from the postman and run them in newman. I'll do more tests tomorrow.

I've tried your example, which works fine on my private computer. I'll try it again on another computer and let you know the result tomorrow.

**Comment by jetpacksfan** [comment]
Even your sample failed on my win8 computer. I saved your contents to env1 and coll1:
![image](https://cloud.githubusercontent.com/assets/13167092/8865376/d04e63be-31f1-11e5-9ec7-5b1ebe06e315.png)

It seems that if I don't use environments then it'll pass.
I think this is an environmental problem and I'll try to rebuild the newman.

I hope you can build the newman into a binary file and release it in a installation package, because the end users can't control the software environment. Different windows version, python version, VS, node.js may bring bugs here and there for newman. And successful build of newman can't guarantee all the function work.

**Comment by jetpacksfan** [comment]
Just tried rebuilding the newman and no luck.
A bit frustrated.
Maybe I can try some different combination of VS/python/node in the future.
my env is:

Windows 8.1 - 64 bit
Python 2.7.10
node-v0.12.7-x64
VS 2012



![image](https://cloud.githubusercontent.com/assets/13167092/8865648/c32c3fea-31f5-11e5-9ea1-d939deb08154.png)

**Comment by czardoz** [comment]
There are actually some known issues with Newman on windows. Here's a small write up that might help you, @jetpacksfan: http://blog.getpostman.com/2015/04/09/installing-newman-on-windows/

In the meantime, I'm doing some digging around in windows myself.

**Comment by jetpacksfan** [comment]
Thank you. Now the issue is that a seemingly successful build can't guarantee a correct newman. 
Anyway, releasing newman in a more formal way (e.g in a .zip package, a installation package) is more preferable. I know it takes time. Can't wait to see it happen!

**Comment by czardoz** [comment]
@jetpacksfan , we've released a Beta version of Newman, which is compatible with Node v4.0+ on windows, and does not require the compilation of any extensions. This was possible because the newer releases of jsdom (which do not depend on contextify) are compatible with Node v4.0+. 

You can check the [readme](https://github.com/postmanlabs/newman/) for details on how to install Beta.
