### ISSUE TITLE
Ability to execute individual requests

### ISSUE THREAD

**Issue by shubhamjadon** [postmanlabs/newman#2339]
Currently, you can run entire Postman collections. Add the capability the run a single request - not the whole collection.
This feature was meant to be part of GSOC 2020 but as this has not been assigned to anyone. I would love to add this feature to newman.
@shamasis @codenirvana can you assign this to me?

**Comment by codenirvana** [comment]
Sure, the original idea was to add a new `newman request` command which takes curl like arguments to execute that request.

However, a single request can be sent using the `--folder` option as well.

**Comment by rohit-gohri** [comment]
I think we could still keep this open, as in the case of duplicate request names the folder option fails. 

@shubhamjadon does https://github.com/postmanlabs/postman-runtime/pull/1010 allow filtering requests with nested paths and with ids if the duplicate name requests in the same folder?

**Comment by molteninjabob** [comment]
I'd love to see this re-opened and allow for the separation of execution from organization. We are working on a service mapper that will build a collection of requests based on the endpoint path, but we still want to group related endpoints together in a folder for easy organization. In addition to @rohit-gohri 's point about duplicate requests, running a single request requires creating another sub-folder for each individual request, which is a lot of overhead.

**Comment by rohit-gohri** [comment]
@molteninjabob You don't need to actually make sub folders if the request name is unique. The `--folder` option actually works more like a filter, more info in #2195
