### ISSUE TITLE
Tests in Postman Collection pass, In Newman some of them fail

### ISSUE THREAD

**Issue by kristijanjakimovski** [postmanlabs/newman#2347]
1. Newman Version (can be found via `newman -v`):5.0.0
 2. OS details (type, version, and architecture): Centos7
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Bug has been there since I started using newman
 4. Expected behaviour: Postman Collection works, newman doesnt
 5. Command / script used to run Newman: newman run test_newman_centos_Copy.postman_collection.json -e TEST-NEWMAN-Copy.postman_environment.json
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/43315720/81799344-84031a80-9511-11ea-80e9-aed43f4ca310.png)

![image](https://user-images.githubusercontent.com/43315720/81799265-60d86b00-9511-11ea-9ef3-3d27d94ecdb9.png)

**Comment by codenirvana** [comment]
@kristijanjakimovski Can you share a scaled-down collection which we can use to reproduce this issue?

**Comment by kirill-bulyshkin** [comment]
Faced with the same problem when running collections through Newman 5.0.0 - 5.0.1 versions

**Comment by codenirvana** [comment]
@kirill-bulyshkin what's the exact problem? Can you share a scaled-down collection which we can use to reproduce this issue locally?

**Comment by kristijanjakimovski** [comment]
Found the problem, newman v5.0.0 uses next generation URL processing, and when you install postman by default in Setting "Use next generation URL processing" is turned off and I couldn't see the errors in postman console. The errors were blank space after the URI request... Now is working fine :)

**Comment by codenirvana** [comment]
@kristijanjakimovski Thanks for the confirmation! 😄 
We are soon going to enable the next-generation URL processor ON by default in Postman as well.
