### ISSUE TITLE
Proxy Settings

### ISSUE THREAD

**Issue by blowsie** [postmanlabs/newman#235]
In newman, my tests wont run when within the corporate firewall,
They work perfectly fine from chrome, or when outside the network.

Is newman proxy aware? If so how can i configure it ?

Thanks.

**Comment by abhijitkane** [comment]
Newman will rely on your system proxy to make calls. You can try playing around with the -k and -l options (https://www.npmjs.com/package/newman).

**Comment by wendyyy** [comment]
Could you please explain this more details?
I run my test successfully with postman plugin. But when I try to execute with command line (newman). It fail: "
RequestError: [cd00d2ed-75e1-c8bc-0e9b-d0ebc094e41e] 'get_auth_rmaxx_HANA copy' terminated. Complete error: 
Error: tunneling socket could not be established, cause=write EPROTO
    at ClientRequest.onError (/usr/local/lib/node_modules/newman/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at onwriteError (_stream_writable.js:304:10)
    at onwrite (_stream_writable.js:322:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
"
I tried to add -k -l, but still fail.
How can I add proxy for new man?

**Comment by blowsie** [comment]
@wendyyy 
> How can I add proxy for new man?

In windows you can configure your proxy in the internet options
![image](https://cloud.githubusercontent.com/assets/308572/14527484/452bfafe-0242-11e6-8d18-9dfea1074c64.png)

Advanced:
If this conflicts with your existing settings, you can run a local proxy using something like CNTLM.

**Comment by czardoz** [comment]
Yep that should do it! :)

@wendyyy If you're using Mac/Linux, you can run Newman like this:

```
HTTP_PROXY=http://your-proxy-ip:port/ HTTPS_PROXY=http://your-proxy-ip:port/ newman -c collection_file 
```

**Comment by wendyyy** [comment]
Thanks @czardoz and @blowsie. I use mac. The socket error is gone after I add HTTP_Proxy...
But now it is ETIMEOUT error ...

**Comment by czardoz** [comment]
@wendyyy Please open a new issue for that :-)
