### ISSUE TITLE
[Feature request] Using newman in drone - Read secrets from environment

### ISSUE THREAD

**Issue by limayekaiwalya** [postmanlabs/newman#2353]
I am looking to run a test collection in drone, as a part of my CI/CD pipeline. I can use the newman CLI straightaway similar to other CI tools like Jenkins/Travis etc. However, it seems like this requires me to commit my `environment.json` which contains sensitive data, along with the rest of my code for the CI to use. I would prefer not to commit any secrets in plain text. How can I achieve this?

**Comment by narayanpai1** [comment]
Apart from using a JSON file as an environment, newman also allows you to use remote environments and collections via its URL as follows:
```console
newman run https://www.getpostman.com/collections/<collection_id>?apikey=$API_KEY -e https://www.getpostman.com/environments/<environment_id>?apikey=$API_KEY
```

Here ``API_KEY`` can be stored as an ENV variable in your CI/CD provider.

Check out [this](https://documenter.getpostman.com/view/631643/JsLs/?version=latest) to know more about APIs provided by Postman.

**Comment by codenirvana** [comment]
Closing as per https://github.com/postmanlabs/newman/issues/2353#issuecomment-629596637
