### ISSUE TITLE
Newman test report customize display in Testrail

### ISSUE THREAD

**Issue by sourav044** [postmanlabs/newman#2356]
1. Newman Version 4.5.7
 2. OS details Windows 10
 3. Are you using Newman as a library?  Yes, I am using it as a library. 
 3. Did you encounter this recently, or has this bug always been there: ->  Recently
 4. Expected behaviour: -> Newman test report customize display in Testrail
 5. Command / script used to run Newman: 
`newman run Scripts.postman_collection.json -e Auto.postman_environment.json --reporters cli,testrail`
 6. Sample collection, and auxiliary files (minus the sensitive details):

```
Request: GET http://----/api/hello
Headers: [{"key":"User-Agent","value":"PostmanRuntime/7.21.0","system":true},{"key":"Accept","value":"*/*","system":true},{"key":"Cache-Control","value":"no-cache","system":true},{"key":"Postman-Token","value":"xxx","system":true},{"key":"Host","value":"10.1.4.157:11003","system":true},{"key":"Accept-Encoding","value":"gzip, deflate","system":true},{"key":"Connection","value":"keep-alive","system":true}]

Response: 200 OK
Headers: [{"key":"Content-Length","value":"2"},{"key":"Content-Type","value":"application/json; charset=utf-8"},{"key":"Server","value":"Microsoft-HTTPAPI/2.0"},{"key":"Date","value":"Sat, 25 Apr 2020 11:49:31 GMT"}]
Body: []
```

 7. Screenshots (if applicable):
![mageofpostman](https://user-images.githubusercontent.com/22783872/82198845-8652e380-991a-11ea-87cf-fe1b42ecf3e4.png)

Steps to reproduce the problem:
1. Install newman and Testrail. 
2. Configure Testrail in the system. 
3. Using API credentials from Testrail, Newman execute report and pass the generated report to testrail. 

Command to execute it : 
`newman run Scripts.postman_collection.json -e Auto.postman_environment.json --reporters cli,testrail`

4. Go to the particular project and test case of the Testrail and browse the report. 

Expectation: 
I would like to show the report in a meaningful way rather than simply displaying it in a json format. 
This will allow the user to read it and find the easily issue that has been reported by the newman for the test cases.

**Comment by narayanpai1** [comment]
Hi @sourav044, since testrail is a custom reporter and this repo doesn't deal with it, you would have to raise the issue in [this](https://github.com/billylam/newman-reporter-testrail) repo.
