### ISSUE TITLE
xml output gives passed even for failures

### ISSUE THREAD

**Issue by smrutikore** [postmanlabs/newman#236]
-t, --testReportFile [file] Path to file where results should be written as JUnit XML [file]

With the above param even failure case is coming as passed. Henceforth when jenkins integrated with xml parser plugin doesnt give failed results at all

**Comment by smrutikore** [comment]
any update on this?

**Comment by shamasis** [comment]
Did you try the `--exitCode` parameter? This causes newman to bubble up the failure code to the terminal.

**Comment by smrutikore** [comment]
So along with -t --exitCode ?

**Comment by shamasis** [comment]
Yes. `--exitCode` or `-x`.

```
newman --url="blah" --testReportFile="blahblah" --exitCode;
```

**Comment by shamasis** [comment]
I may have spoken too soon... Is it that your XML file is marking the failed tests as passed?

**Comment by smrutikore** [comment]
Yes. As i am using xml parsing plugin for jenkins . and the actual result is failed but its giving as passed

**Comment by smrutikore** [comment]
Some thing like below.

Send expiry message in existing thread- thread2.Status code is 400 Bad Request	Passed
Send message in existing thread- thread1.Status code is 200 OK	Passed

The first one is bad request where as its giving as Passed

**Comment by abhijitkane** [comment]
@smrutikore What's the exact test script? 'Status code is 400' sounds like you're testing for the status code being 400. A malformed request will return a 400 status code, and the test will pass.

**Comment by smrutikore** [comment]
My test is just to expect a 200 status code and I am expecting it to fail if other than 200

**Comment by abhijitkane** [comment]
I created a collection (https://beta.getpostman.com/collections/12ba3edfb39057e6a7c6) that has one passing test and one failing test, and ran:
` newman -u http://beta.getpostman.com/collections/12ba3edfb39057e6a7c6 -t test.xml`
test.xml shows one pass and one failure.
Are you getting a different output for this command?

**Comment by shamasis** [comment]
@smrutikore - even I did the same checks and seems that I am getting correct result in XML.

For example, if I run the collection [http://beta.getpostman.com/collections/000019266d44f95c2320](http://beta.getpostman.com/collections/000019266d44f95c2320)

```terminal
newman -u http://beta.getpostman.com/collections/000019266d44f95c2320 -t test.xml
```

My XML output is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite name="Expect 200 and Server Returns 200" id="0ddbf59d-7b45-1938-47fa-505cc35542a1" timestamp="2015-07-31T18:50:17.539Z" time="3725.00 ms" tests="1" failures="0">
		<testcase name="Status code must be 200" />
	</testsuite>
	<testsuite name="Expect 200 but Server Returns 400" id="c9fd0765-02f8-1899-688f-0e36fbf81878" timestamp="2015-07-31T18:50:17.540Z" time="452.00 ms" tests="1" failures="1">
		<testcase name="Status code must be 200" >
			<failure><![CDATA[Status code must be 200]]></failure>
		</testcase>
	</testsuite>
</testsuites>
```

The collection I created, has one URL that returns 200 and another that returns 400. In both the requests, I wrote test case that expects status to be 200. As such, the request where response is 400, fails in newman and the XML report reflects that.

Can you check in your collection whether the test script has been written to expect status 200?

**Comment by smrutikore** [comment]
yeah . You are right. I got the output with failure and pass .

<testsuite name="Getting Users Unread Messages Count after reading message" id="8f0fbe52-5a97-6b3e-2190-e961d6e94e52" timestamp="2015-07-31T18:51:19.267Z" time="1869.00 ms" totalTime="1869 ms" tests="2" iterations="1" failures="1" successes="1">
<testcase name="Status code is 200 OK" successes="1" failures="0"/>
<testcase name="Message unread count decremented on reading the message" successes="0" failures="1"/>
</testsuite>

I think the problem is with junit xml report plugin using for jenkins which is picking the Failure as Passed.

Any idea about this?

**Comment by shamasis** [comment]
Just to clarify... even with the collections we posted, your jUnit XML report plugin is reporting all pass?

**Comment by smrutikore** [comment]
Yes. When I get the mail after passing of the xml junit report . Seems like this report doesn't support with jenkins plugin. i.e the genrated report has failures but when its it is parsed and being sent to email via jenkins it gives passed status

**Comment by abhijitkane** [comment]
We merged a pull request in May that corrected the jUnit output format - https://github.com/postmanlabs/newman/pull/184/files. Not sure why there's still an issue. Can you compare this output with output from other tools?

**Comment by smrutikore** [comment]
Thanks for the help here. Verified with the latest update and it works fine now in jenkins.
