### ISSUE TITLE
error: Invalid Record Length: header length is 9, got 1 on line 5

### ISSUE THREAD

**Issue by fangjiantan** [postmanlabs/newman#2362]
1. Newman Version (can be found via `newman -v`): 》4.5.4
 2. OS details (type, version, and architecture):》OS-10.14.5
 3. Are you using Newman as a library, or via the CLI?》CLI
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

I reformated the csv file to have all strings enclosed with double quotes and it works now

Run:
$ newman run /Users/hhht/Postman/files/login/Test_api_login.postman_collection.json --environment /Users/hhht/Postman/files/login/Test_api_path.postman_environment.json --iteration-data /Users/hhht/Postman/files/login/TestsCase_login.csv -r html --reporter-html-export /Users/hhht/Postman/files/reporter/login.html

Output:

error: Invalid Record Length: header length is 9, got 1 on line 5

**Comment by codenirvana** [comment]
@fangjiantan can you try updating to Newman v5 and check if that fixes your issue?

**Comment by fangjiantan** [comment]
> @fangjiantan您可以尝试更新到Newman v5并检查是否解决了您的问题吗？

Thank you. It will be solved after updating to the latest version
