### ISSUE TITLE
nested folder is not included in the runner

### ISSUE THREAD

**Issue by junghanChoi** [postmanlabs/newman#2363]
1. Newman Version (can be found via `newman -v`): 5.0.1
 2. OS details (type, version, and architecture): win10 64bit
 3. Are you using Newman as a library, or via the CLI? cli
 3. Did you encounter this recently, or has this bug always been there: recently. 
 4. Expected behaviour: include all requests in the collection
 5. Command / script used to run Newman: newman run "LBE 0.1.postman_collection.json" -e "LBE alpha.postman_environment.json"
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/11530184/82790483-1955c580-9ea7-11ea-90d6-9b1dcabd98e9.png)
![image](https://user-images.githubusercontent.com/11530184/82790512-207cd380-9ea7-11ea-8cf8-c74881b6734a.png)

There are explicitly all of requests in the exported json file. But some requests are not included in the newman run. Is this becuase of complex folder structure?

**Comment by junghanChoi** [comment]
I pulled nested folders out, then the runner include them.

**Comment by codenirvana** [comment]
@junghanChoi That's odd... can you share a scaled-down collection (without sensitive details) which we can use to reproduce this issue locally?

**Comment by rwilliams3** [comment]
I had this same issue as well. I had to resort to not using the nested folder name and only using the outermost folder name instead (which gave me less control over the test as it would run all of the nested folders by default). This used to work.

**Comment by codenirvana** [comment]
@rwilliams3 Please share the steps which we can follow or a collection (using [echo endpoint](http://postman-echo.com/)) which we can use to reproduce this issue locally.

**Comment by junghanChoi** [comment]
It'll be violation of COC when I share the code. I would try to create an example collection.

**Comment by junghanChoi** [comment]
It seems that I was using postman in a wrong way.
Maybe the folder structure was problem. **But also my script had fault.**
I've wanted to run the same request again with different parameter value.
The problem was that I made duplicated request name. 

`
let sizes;

try {
    sizes = pm.globals.get("sizes")
}
catch (e) {

}
if (!sizes) {
    sizes = [0, 501, 1000, "aaa", -1]
}
let currentSize = sizes.shift()
console.log(currentSize)
if (currentSize === undefined) {
    postman.setNextRequest()
    pm.globals.unset("sizes");
    pm.globals.unset("size");
}
else {
    console.log("Current size: " + currentSize)
    pm.globals.set("sizes", sizes)
    pm.globals.set("size", currentSize)
    postman.setNextRequest("**blocks_**Get transactions_invalid size")// << add explicitly different name.
}
`
There are no excluded requests now.

**Comment by codenirvana** [comment]
@junghanChoi Thanks for the clarification.
It's better to give a unique folder/request name while using `postman.setNextRequest` to avoid confusion.

I am closing this issue now. Feel free to reopen if the folders issue persists or you can help us with the steps to reproduce this issue.
