### ISSUE TITLE
Not able to access https url from newman even when using -k option (works in postman)

### ISSUE THREAD

**Issue by mverma-va** [postmanlabs/newman#237]
Hi,
I am trying to call a https request with username and password in url, so this works in postman(gave 200), but does not work in newman. 
I am new with authentication headers, I tried selecting "Basic Auth" and giving username/password there (this did not work in postman itself) and gave me 401

manishve@PC2359VM ~/Documents $ newman -c Dummy.json.postman_collection -e Dummy_Env.postman_environment -k

Iteration 1 of 1
Auth header: null
401 350ms tq2 https://user:password@xx.xx.xx.xx/views/Alarms_Current
undefined
401 250ms tq2 copy https://user:password@xx.xx.xx.xx/views/Alarms_Current

Summary:

Parent                   	Pass Count	 FailCount
-------------------------------------------------------------
Collection Dummy         	         0	         0

Total                    	         0	         0
manishve@PC2359VM ~/Documents $

**Comment by mverma-va** [comment]
Can someone please help with the workaround or maybe a video tutorial link that would be great.

**Comment by abhijitkane** [comment]
Are you able to make curl requests to https://user:password@xx.xx.xx.xx/views/Alarms_Current successfully?

**Comment by mverma-va** [comment]
hi Abhijit,
the curl did not work as u mentioned, but when i added the option --digest it worked see below. 
So does that mean I have to add Authorization as Digest Auth in each call in postman collection so that it works in newman. What is the best n easiest way to do that.

manishve@PC2359VM ~/Documents/projects/hitntrial/postman $ curl -u user:password http://X.X.X.X/views/Alarms_Current/ -v
* Hostname was NOT found in DNS cache
*   Trying X.X.X.X...
* Connected to X.X.X.X (X.X.X.X) port 80 (#0)
* Server auth using Basic with user 'user'
> GET /views/Alarms_Current/ HTTP/1.1
> Authorization: Basic aaaaaaaa==
> User-Agent: curl/7.35.0
> Host: X.X.X.X
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< WWW-Authenticate: Digest qop="auth", realm="aaaaaaaa", nonce="1111111"
* no chunk, no close, no size. Assume close to signal end
< 
* Closing connection 0
manishve@PC2359VM ~/Documents/projects/hitntrial/postman $ curl -u user:password http://X.X.X.X/views/Alarms_Current/ --digest
{ "widgets": [{

**Comment by mverma-va** [comment]
Also it would be great if you guys add a blog, since I see lot of similar bugs raised. or maybe provide me a link or a video tutorial which is good. Thanks :)

**Comment by abhijitkane** [comment]
If digest auth worked in curl, you'll need to use Digest Auth in Postman, export the collection, and run it in Newman. I'm not sure of the exact params you need to use - Digest Auth takes a lot more that username and password.

We have a blog setup at http://blog.getpostman.com/, and regularly add articles.

**Comment by mverma-va** [comment]
This issue is good to be closed.
