### ISSUE TITLE
Async Callback

### ISSUE THREAD

**Issue by FCesar** [postmanlabs/newman#2370]
Hello everybody, I not understand, how to `.pause()` works . 
_Originally posted by @FCesar in https://github.com/postmanlabs/newman/issues/612#issuecomment-633650858_

In my case, I wish get data in my db on event "beforeItem" . But interaction not await query result and execute request. I wish that newman awaiting, before execute request

I use async/await in callback.

**Comment by DannyDainton** [comment]
Hey @FCesar 

I'm going to close this issue out for now but if you're still having problems, we can open it again.
