### ISSUE TITLE
JSON reporter sometimes stores one execution twice

### ISSUE THREAD

**Issue by D43M0NT00L5** [postmanlabs/newman#2376]
I encounterd an issue while i merged pairs of executions and failures via their httpRequestId. 
The aim is to have a failure without an empty response.
So i normally let my script run over the json-reporter-export-file and create a summary from scratch.
The summary contains a small overview and all failures with detailed response and httpRequestId only.
In order to add the response to a failure, i used the httpRequestId to identify the response within the executions of the json-reporter-export-file.
When i checked my merges, some of them didnt contain any request or response.
The reason why the request is also empty, is caused by taking the requests from the executions and not using the requests of the failures.
I checked the occurance of the httpRequestId of the failure, and the count was one.
Normally their should be two, the execution and the failure.

So i would like to ask if this should be an expected behavior of the newman features?

 1. Newman Version (can be found via `newman -v`): 
=> 5.0.1
 2. OS details (type, version, and architecture): 
=> Ubuntu Server 18.0.4 LTS
 3. Are you using Newman as a library, or via the CLI? 
=> CLI
 3. Did you encounter this recently, or has this bug always been there: 
=> uncertain(im new in postman/newman)
 4. Expected behaviour: 
=> json reporter should create a json after newman has executed the given requests in a collection
- a pair of execution and failure can be identified via httpRequestId or ref 
 5. Command / script used to run Newman:
=> newman run collection.json -n 6 --reporters json --reporter-json-export result.json --silent
 6. Sample collection, and auxiliary files (minus the sensitive details):
=> im that i cant create a sample, ill give you an explanation:
- it's a collection with 300 requests
- Structured in PreRun,POST,GET,POSTbyID,GETbyID,PUT,DEL and PostRun
 7. Screenshots (if applicable):
![grafik](https://user-images.githubusercontent.com/46996491/83330228-f7d15100-a28d-11ea-90a7-c1ea46eb73fb.png)
The screenshot is showing executions of the json-reporter-export-file.

Hopefully a normal collection with roundabout 300 request and multiple iteration should recreate the issue.

**Comment by DannyDainton** [comment]
Hey @D43M0NT00L5,

I'm going to close this issue out for now but if you're still having problems, we can open it again.

**Comment by shwetasarpal** [comment]
Hi ,
I am facing the same issue where the tests are reported twice. My collection has a pre request script to generate authorization token and it uses sendRequest().
