### ISSUE TITLE
Postman collection fails in postman ... no cookie/session

### ISSUE THREAD

**Issue by georgepcelvi** [postmanlabs/newman#238]
I have a postman collection which relies on cookies for 1 test chained to the next test to run.
postman test runner works perfectly.
newman test runner fails on the subsequent test needing the session.
I have installed the interceptor plugin in postman/jetpacks.
Is their a way to make newman cookie/session aware?
Thanks

**Comment by abhijitkane** [comment]
To send cookies via Newman, you'll explicitly need to set the Cookie header in the request. There's currently no way of getting Chrome's cookies into Newman.

**Comment by nishantkyal** [comment]
How can I set Cookie header in newman request?
