### ISSUE TITLE
How to Access Updated Global Variable's Value after each Iteration

### ISSUE THREAD

**Issue by RuchiTrehan2** [postmanlabs/newman#2384]
1. Newman Version (can be found via `newman -v`): 5.0.0
 2. OS details (type, version, and architecture): windows 10 64-bit
 3. Are you using Newman as a library, or via the CLI? Library
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

I have 3 requests and I am using a csv data file to iterate through 5 different iterations. Now, I want to fetch the updated global variables' values after each iteration. 

I am aware of exporting the global variable option in Newman, but it returns only the final values.

Is their any option for it ? Or any other way that i can fetch and store the global variable's value in a file or something after each iteration ?

**Comment by DannyDainton** [comment]
Hey @RuchiTrehan2 

Is this still an issue for you?

**Comment by DannyDainton** [comment]
Hey @RuchiTrehan2

I'm going close this issue out due to inactivity, if you're still facing this issue we can open it back up and take a look at what's happening.
