### ISSUE TITLE
Newman throws exception when calling js function from sandbox

### ISSUE THREAD

**Issue by PaulRF** [postmanlabs/newman#239]
Hi!
1) I defined the body request as
*["User::logon",null,"username", "{{encoded_pwd}}", "127.0.0.1", "test"]*
2)I defined pre-request as:
```javascript
var sha = CryptoJS.SHA256('123456').toString();
postman.setGlobalVariable('encoded_pwd', sha); 
```
3) I added the following line  to the *tester_sandbox.html*:
```javascript
<script type="text/javascript" src="js/libs/sha256.js"></script>
```
4) I copied sha256.js to the corresponding location
But when I run my test via newman it throws the exception: 
*Iteration 1 of 1 EXCEPTION - ReferenceError: CryptoJS is not defined*
Any ideas?

**Comment by abhijitkane** [comment]
Closing this. I've replied on the ticket in Postman's issue tracker. Tester_sandbox is part of Postman, not Newman.
