### ISSUE TITLE
Differences in Access-Control-Expose-Headers in Response Header

### ISSUE THREAD

**Issue by sudazzle** [postmanlabs/newman#240]
I am not getting the same Expose Header in Response while testing from grunt-newman and postman. 

**In postman** 

     Access-Control-Expose-Headers → My-Custom-Header, My-Custom-Header, X-Chopped, api-version, content-length, content-md5, content-type, date, request-id, response-time

**In grunt-newman**

    Access-Control-Expose_Headers -- Api-Version, Request-Id, Response-Time

What is the reason behind it? How do I get the same response?

**Comment by abhijitkane** [comment]
@sudazzle Are you sending the exact same request payload? You'll need to use a web debugging tool like http://www.charlesproxy.com/download/ to see any difference in the requests you're sending.

**Comment by sudazzle** [comment]
I included this: 

       Origin:chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop 

in the request header and it worked. Thanks @abhijitkane. By the way I couldn't install charlesproxy because I use ubuntu. Anyway my problem is solved. Thanks a lot.
