### ISSUE TITLE
SSL-client-cert-list not working

### ISSUE THREAD

**Issue by irfaansb** [postmanlabs/newman#2404]
Version and environment information:

 1. Newman Version - 4.5.6
 2. OS details : mac os
 3. Using newman as CLI
 5. Command / script used to run Newman: cmd used: newman run Automation.postman_collection.json --ssl-client-cert-list sslclientcertlist.json
5. Error message: error: unknown option '--ssl-client-cert-list'

Steps to reproduce the problem:

1. Create a postman collection
2. Create a ssl_list.json
3. run the command

**Comment by codenirvana** [comment]
Support for `--ssl-client-cert-list` option was added in Newman v4.6.0. Refer: https://github.com/postmanlabs/newman/blob/v5.1.0/CHANGELOG.yaml#L38

I hope updating Newman to the latest version will fix your issue.
