### ISSUE TITLE
if 

### ISSUE THREAD

**Issue by snv0** [postmanlabs/newman#2406]
1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by codenirvana** [comment]
Looks like this is created by mistake.
Feel free to reopen if you can provide more detail about this issue.
