### ISSUE TITLE
Proxy Request through Request Agent 

### ISSUE THREAD

**Issue by RajatGupta16197** [postmanlabs/newman#2413]
I am using newman as a library.I am specifying the request agent but newman is not accepting it. I tried socks-proxy-agent as well as http-proxy-agent. I am also using reporters options too which is generating the report properly.

const requestAgent = new SocksProxyAgent({ host: 'localhost', port: '1080' });
 
newman.run({
    collection: require('./sample-collection.json'),
    requestAgents: {
        http: requestAgent, 
        https: requestAgent,
    }
}, function (err) {
    if (err) { throw err; }
    console.log('collection run complete!');
});

**Comment by DannyDainton** [comment]
Hey @RajatGupta16197,

I'm going to close out this issue due to inactivity, we can open this up again if you're still facing this issue.
