### ISSUE TITLE
Global variables for header is not accepted in newman 

### ISSUE THREAD

**Issue by manju0906** [postmanlabs/newman#2417]
I have defined global variables for header and URL in postman collection and its working fine but when i try to run using newman command by passing the global variables, URL is accepted but somehow headers are not read.

is there anything wrong in newman command or is there any way to pass the global variables to headers using newman.

please refer the below screenshots.

1. Defined variables in postman and its working

![image](https://user-images.githubusercontent.com/5094716/86006388-8246d500-ba33-11ea-8fd2-ba6c262c2036.png)

2. when running from newman its not working.

![image](https://user-images.githubusercontent.com/5094716/86111577-8b43af00-bae4-11ea-9af4-fac88e4443ac.png)

**Comment by manju0906** [comment]
looks like there was some error in script, i completely redesigned the script. it worked fine. but i still couldn't find a solution if there was an error in script how postman runner was working fine.

**Comment by shridharb78** [comment]
hi @MLINGAD  I am also facing the same issue. I dont see any error in my POSTMAN test script.  Is there any solutions you found for this?
