### ISSUE TITLE
while executing Newman as Library, getting error.

### ISSUE THREAD

**Issue by svarshney2311** [postmanlabs/newman#2421]
Hi,

Iam trying to execute below  Node library, but getting error.

const newman = require('newman')

Below is my app.js:

newman.run({
collection: './Digital_API.postman_collection.json',
IterationData : '/TestData_SIT.json', 
IterationCount : 1,
d: '/TestData_SIT.json',
reporters: 'htmlextra',
reporter: {
htmlextra: {
template: '/Report.hbs',
export:'Desktop/SmokeReport.html'

}
}
})

**Getting below error:**

C:\Users\SVarshney\OneDrive - Shaw Communications Inc\Project\Postman\Collection>node app.js
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'newman'
Require stack:
- C:\Users\SVarshney\OneDrive - Shaw Communications Inc\Project\Postman\Collection\app.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1026:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (C:\Users\SVarshney\OneDrive - Shaw Communications Inc\Project\Postman\Collection\app.js:1:16)
[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\SVarshney\\OneDrive - Shaw Communications Inc\\Project\\Postman\\Collection\\app.js'[39m
  ]
}
Note:
My Postman collection and Json Data file and temorary report are stored in  C:\\Users\\SVarshney\\OneDrive - Shaw Communications Inc\\Project\\Postman\\Collection\  path.
Nwman version 5.1.0
Node version: v12.18.0

**Comment by DannyDainton** [comment]
@svarshney2311 can this be closed, you raised this on the htmlextra repo and followed it up with something after you had it working, so I can only assume this isn't an issue anymore. 😁

**Comment by DannyDainton** [comment]
Duplicate issue.
