### ISSUE TITLE
'newman' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by VeerannaKonda** [postmanlabs/newman#2428]
Steps to reproduce the problem:

1. Installed NPM successfully
2. Installed neman also successfully
3. while trying to install newman html report getting below error.
'newman' is not recognized as an internal or external command,
operable program or batch file.

**Comment by VeerannaKonda** [comment]
![image](https://user-images.githubusercontent.com/47398885/86909436-b27a2c00-c135-11ea-8d1f-f8fc4930d984.png)

**Comment by DannyDainton** [comment]
Hey @VeerannaKonda

Has this now been resolved following the conversation on the Postman community fourm?


https://community.postman.com/t/newman-not-recognized-as-an-internal-or-external-command/13980

**Comment by pawanakhil** [comment]
@VeerannaKonda  Add Newman to System Environmental Variables in Windows.

**Comment by DannyDainton** [comment]
Hey @VeerannaKonda,

Not heard anything back about this issue, I'm going to close this issue for now but can reopen and take a look if the problem persists.

**Comment by anilyadav106** [comment]
Its still not working.

C:\Users\anilkumar06>npm install -g newman
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
C:\Users\anilkumar06\AppData\Roaming\npm\newman -> C:\Users\anilkumar06\AppData\Roaming\npm\node_modules\newman\bin\newman.js
+ newman@5.2.0
updated 1 package in 10.717s

C:\Users\anilkumar06>newman -v
'newman' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\anilkumar06>node -v
v12.18.4

C:\Users\anilkumar06>npm -v
6.14.6

**Comment by DannyDainton** [comment]
Hey @anilyadav106 

Did you check/add the system environment variable mentioned in the community posts?

**Comment by repl-balaji** [comment]
Go to Command prompt.
**type npm config set bin-links true**
Enter
Install your newman packages again.

"All Opinions express here are my own"

**Comment by eslamlotfy213** [comment]
issue still happen to me

**Comment by repl-balaji** [comment]
Newman was installed in our case as per npm install -g newman but it was coming as not recognized in command prompt.

The approach we took is, 
1) Compare all the node folders on non working and working computer. (C:\Program Files\Node... & C:\Users\<Name>\AppData\Roaming\npm

In our case some of these files were missing - 
![image](https://github.com/postmanlabs/newman/assets/19770664/dcbb224e-615b-4eea-90a6-ac9319adbaef)
Depending on what is missed, you can search more cli options [here](https://docs.npmjs.com/cli/v9/using-npm/config) on npm and install those specific ones. (in our case it was bin-links)
Then Re-install the newman.

It finally worked for us.

Good luck!

"All Opinions expressed here are my own"

**Comment by eslamlotfy213** [comment]
Fixed now i fixed the environment path
