### ISSUE TITLE
Newman run is failing with 401 error when run from Linux

### ISSUE THREAD

**Issue by ssunderk** [postmanlabs/newman#2444]
We are exploring newman to automate some api tests. We are testing a WebAPI which is SSL & Windows authentication enabled and hosted on a windows server. Newman is installed on client VM. When we run the postman collection from a windows VM the requests go through. However when we run same collection from a Linux VM the run fails with 401 error as shown below.

Response Message:
POST https://app.company.int:6002/api/Event [401 Unauthorized, 1.47KB, 395ms]
POST https://app.company.int:6002/api/Event [401 Unauthorized, 831B, 316ms]
POST https://app.company.int:6002/api/Event [401 Unauthorized, 1.47KB, 308ms]

More info:
-NewMan Versions
 -Newman installed on Linux VM: 5.1.2
 -Newman installed on Linux VM: 5.1.0
- Windows OS: Windows 10
- Linux OS- Ubuntu 18.04
- AuthType used in collection: NTLM [User name , password & domain provided - all verified]
- Same collection runs fine when run via newman from Windows laptop.
- curl to same url works from linux with same credentials .
- newman command used: newman run collection-file.json -e envt-file.json --insecure 
- exact same collection and environment files are used in both windows and linux

**Comment by xk0der** [comment]
Hey @ssunderk is it possible for you to install the Postman app on the Linux VM and test using the app to see if the requests fail? If yes, try to reproduce the issue from the Postman app and check the error in the Postman Console (View > Show Postman Console). Provide the raw-logs/screenshots here, if you are unable to share the screenshot here you may share it with us internally at the support-ticket that you have open with us.

If that's not possible, try running `newman` with the `--verbose

    newman run --verbose "CollectioName.json"

Packet capture from the VM while executing your collections would help as well.

Start capture as follows

    tcpdump -i any  -w newman-test.pcap

In a new terminal window, start the `newman run` - once the run completes, switch back to tcpdump terminal window to press `CTRL+C` to stop the capture. Share the `.pcap` file, also let us know the IP address of the VM and `app.company.int` to make it easy to filter the packets.

Again assuming these may have sensitive info, feel free to provide these internally.

**Comment by DannyDainton** [comment]
Hey @ssunderk,

I'm going to close this out for now, if this is still an issue, could you follow the steps provided by @xk0der and respond with any relevant information please.
