### ISSUE TITLE
https://learning.postman.com/docs/running-collections/using-newman-cli

### ISSUE THREAD

**Issue by hongthong2** [postmanlabs/newman#2463]
[https://github.com/postmanlabs/newman/issues/2437#issue-658936198]() @
 1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by DannyDainton** [comment]
Hey @hongthong2 

Going to close this issue as it looks like it was created by mistake 🤷‍♂️ 

If it wasn't a mistake, we can reopen this up again if you're able to provide some more details/context 😄
