### ISSUE TITLE
JSON data source file containing UTF-8 encoded data not read correctly

### ISSUE THREAD

**Issue by mryangza** [postmanlabs/newman#2466]
Hi,

I'm running Newman 5.1.2 CLI via postman/newman docker container on Ubuntu 18.04. I'm using a JSON data source file to iterate POSTs to my service. The JSON data source file contains the following sort of data:

  ```
{
    "name":"Paris"
  },
  {
    "name":"Mauregard"
  },
  {
    "name":"Provence-Alpes-Côte d'Azur"
  },
```
When the POST hits my service, the "name" received on the **Provence-Alpes-Côte d'Azur** iteration is actually "Provence-Alpes-CÃ´te d'Azur". This suggests that the JSON data source file is not being considered to be UTF-8 encoded when it is read.

I have tried saving the JSON file as UTF-8 with BOM and without BOM. I have also done the same for the collection and environment files. I have not tried converting the JSON to CSV file - I'd rather use JSON here (I've snipped out irrelevant fields so each iteration does contain more than just the "name" field). This happens for any non-ASCII name.

Any ideas?

**Comment by kevinswiber** [comment]
Hey @mryangza,

I can't reproduce this issue.  Is it possible that it's your server interpreting the encoding as ASCII?  If this is coming through the request body, you might want to try adding `;charset=UTF-8` to your Content-Type header value.  Additionally, you can try to isolate this by pulling up the request in Postman, hitting the Code link under the Send/Save buttons, copying the `curl` command, and running that in a terminal with the right values.  If the server still interprets this as ASCII, it can help narrow down where the encoding issue is originating.

**Comment by mryangza** [comment]
Ah yeah, you nailed it @kevinswiber - it's a missing charset indicator in the Content-Type header. Thanks so much! Sometimes an extra pair of eyes helps!
