### ISSUE TITLE
responseBody is undefined in errorResponse

### ISSUE THREAD

**Issue by jefferyyuan** [postmanlabs/newman#247]
Thanks for this great tool.

I am using newman, and found out that responseBody is undefined in tests
"tests": "console.log(responseBody);\n tests[\"check status code\"] = responseCode.code === 200;",
The output is: 
undefined

Could you please tell me what's wrong?

Also when we use newman, is there any flag to tell newman to print response?

Thanks a lot for your help.

**Comment by abhijitkane** [comment]
I'm not able to reproduce this. Can you run `newman -u https://www.getpostman.com/collections/a40fc19ba6c8edd01397` and check if the response body is printed?

What version of Newman are you on?

There's no option to print the response - you'll need to add `console.log(responseBody);` in the test script.

**Comment by jefferyyuan** [comment]
Hi, Abhijit:
Thanks so much for your help.

I found out that if the request succeeds(returns 200), responseBody is set and we can print it.

Otherwise(return 4xx or 5xx), responseBody is undefined even the server does return json data.

Is there a way to get the responseBody in the error? We want to check whether the returned error message is expected(error code).

Thanks a lot.

**Comment by abhijitkane** [comment]
To check the HTTP response code, use `responseCode.code`. If the response body is not set in the response, Newman cannot provide one in the sandbox.

Docs - https://www.getpostman.com/docs/jetpacks_sandbox
