### ISSUE TITLE
Newman (as a library) doesn't run any test

### ISSUE THREAD

**Issue by mankinchi** [postmanlabs/newman#2473]
1. Newman Version (can be found via `newman -v`): 5.1.2 (install as dependency)
 2. OS details (type, version, and architecture): Node - Typescript
 3. Are you using Newman as a library, or via the CLI? library
 3. Did you encounter this recently, or has this bug always been there: first time using
 4. Expected behaviour: Run all the test
 5. Command / script used to run Newman:
```
import Axios from 'axios';

const newman = require('newman');
require('dotenv').config();

const execute = async (): Promise<void> => {
	const response = await Axios.get<string>(
		`https://api.getpostman.com/collections/${process.env.POSTMAN_COLLECTION_ID}`,
		{
			headers: {
				'X-Api-Key': process.env.POSTMAN_API_KEY,
			},
		},
	);

	console.log(response.data);

	newman.run({
		collection: response.data,
		// collection: ,
		reporters: 'cli',
	}, (err): void => {
		if (err) { throw err; }

		console.log('collection run complete!');
	});
};

execute();
```
 6. Sample collection, and auxiliary files (minus the sensitive details):
```{
    "collection": {
        "info": {
            "_postman_id": "xxx",
            "name": "Hubs Games",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
        },
        "item": [
            {
                "name": "Categories",
                "item": [
                    {
                        "name": "Get All Categories",
                        "event": [
                            {
                                "listen": "test",
                                "script": {
                                    "id": "xxx",
                                    "exec": [
                                        "pm.test(\"Status code is 200\", function () {\r",
                                        "    pm.response.to.have.status(200);\r",
                                        "});"
                                    ],
                                    "type": "text/javascript"
                                }
                            }
                        ],
                        "_postman_id": "xxx",
                        "protocolProfileBehavior": {
                            "disableBodyPruning": true
                        },
                        "request": {
                            "method": "GET",
                            "header": [],
                            "url": {
                                "raw": "https://localhost:8080/api/game/categories/all",
                                "protocol": "https",
                                "host": [
                                    "localhost"
                                ],
                                "port": "8080",
                                "path": [
                                    "api",
                                    "game",
                                    "categories",
                                    "all"
                                ]
                            }
                        },
                        "response": []
                    }
                ],
                "_postman_id": "xxx"
            },
```
 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/8164063/90255996-65058300-de88-11ea-8f51-27279ad3fd0f.png)

I have tried and copy the result from the API, put it in a `.json` and run the test from cli by this
```
npx newman run .\apiCollection.json
```

and the test is running correctly

![image](https://user-images.githubusercontent.com/8164063/90256436-15738700-de89-11ea-983c-03619daf5c02.png)

**Comment by DannyDainton** [comment]
Hey @mankinchi

The output of `response.data` looks like it's just a the Id right, from what I can see in the console statement. Might be reading that wrong. 🤔

It would need to be the full URL to run the Collection.

**Comment by mankinchi** [comment]
@DannyDainton the `response.data` is the block of JSON in 6 (I only copy part of it since it's too big). I can't find any option to pass in an URL to `newman.run` for API route, maybe it's only for Cloud Subscriber,

**Comment by DannyDainton** [comment]
You can just add it as the string in the `collection` property.

```
const newman = require('newman'); 
newman.run({
    collection: `https://api.getpostman.com/collections/${uid}?apikey=${apiKey}`,
    reporters: 'cli'
}, function (err) {
	if (err) { throw err; }
    console.log('collection run complete!');
});

```

**Comment by mankinchi** [comment]
yay >v<. Working now. I'm not quite sure what happens. Your code helps. Tks :D

**Comment by DannyDainton** [comment]
Yay!

If you were to just try the hardcoded version of the URL in a browser, it should return the raw JSON.

I'm not sure if the why you had it originally was doing that, seemed like it was just passing an Id into that property, rather than the collection data.

I'm going to close this issue as it seems you're all good and running collections now!! 🏆

There's also a beautiful html reporter that some dude made, that would give you a different view of that Newman data 😂

https://github.com/DannyDainton/newman-reporter-htmlextra
