### ISSUE TITLE
No response in newman - Fine in postman

### ISSUE THREAD

**Issue by RyanW89** [postmanlabs/newman#248]
Hello, 

I'm using newman Version 1.2.17 and 1.2.16 (The first in Docker and the second locally as my VS is buggered).

When I'm running the tests though postman, all is fine, when i try through newman, I seem to be getting no responseBody.

Here is my Test:

tests["Response time is less than 2000ms"] = responseTime < 2000;
tests["Status code is 200"] = responseCode.code === 200;
tests["Content-Type is present"] = responseHeaders.hasOwnProperty("Content-Type");
console.log('Response',responseBody);
var jsonObject = xmlToJson(responseBody);
console.log('JSON',jsonObject);
tests["Status"] = jsonObject.pingdom_http_custom_check.Status=== "OK";

which all pass though postman, newman spurts out.

Iteration 1 of 1
Response
JSON
    EXCEPTION - TypeError: Cannot read property 'pingdom_http_custom_check' of null
200 9244ms {{Url}}/test/page.aspx?output=xml <My URL>/page.aspx?output=xml
    ? Response time is less than 2000ms - Fail
    ? Status code is 200 - Pass
    ? Content-Type is present - Pass
    ? Body matches string - Fail

Summary:

Parent                          Pass Count       FailCount
-------------------------------------------------------------
Collection 1                             2               2

Total                                    2               2

any thoughts or suggestions as I have no more ideas. I can only think that im missing a library or something in newman, but I dont know what.

Thanks.

PS im new to github, and newman, so apologies if anything is wrong.

**Comment by abhijitkane** [comment]
@RyanW89 Can you install http://www.telerik.com/fiddler or http://www.charlesproxy.com/ and check what the server is returning when you run the collection in Newman?

Alternatively, if you can create a small collection file that reproduces this problem, you can send it to help@getpostman.com, and we'll see if we can see this issue on our end.

**Comment by RyanW89** [comment]
Hello, 
We white list the URLs so sadly I cannot send the collection. I tried running a fiddler trace but could not get it to capture the newman requests, looks like i need to change the node.js / npm proxy settings. Will take a look tomorrow.

Cheers

**Comment by RyanW89** [comment]
Hello, 

Cannot seem to get it to run through fiddler, any thoughts?

**Comment by RyanW89** [comment]
I have managed to get my requests to go through fiddler, but im now getting: 

TypeError: Cannot call method 'toString' of undefined

if i remove the proxy settings, it goes back to how it was in my initial post.

**Comment by abhijitkane** [comment]
Can you create a small collection file that reproduces this problem, you can send it to help@getpostman.com, and we'll see if we can see this issue on our end.

**Comment by igladun** [comment]
Hello @abhijitkane ,
I have the same issue,
Tested on two environments: The firts is Windows with 2.0.0-beta.1, the second is Ubuntu 14 with 1.2.21
Steps to reproduce:
1) Download example collection
https://www.dropbox.com/s/a4oh68f63i6ilsp/example.postman_collection?dl=0
2) Run via cmd 
`newman -c example.postman_collection -o output.txt`
3) Verify that output.txt contain the response body
![response_body](https://cloud.githubusercontent.com/assets/4245201/10387145/85ba64bc-6e67-11e5-8710-731520cd7eed.png)

Actual result: missing response body in output.txt

**Comment by igladun** [comment]
I can't see requests from Newman either through Charles or Fiddler. Does Newman supports proxy?

**Comment by RyanW89** [comment]
Hello, 

Sorry I didnt get round to replying been flat out. The set HTTP and HTTPS did the job.

Thanks!

**Comment by czardoz** [comment]
@igladun 

By default, Newman does not store the response body in the output file. Newman is actually able to retrieve the response. If you use the ``--outputFileVerbose`` option, you'll see the response saved in the verbose output.

**Comment by igladun** [comment]
@czardoz 
Thank you!

**Comment by czardoz** [comment]
Welcome!
