### ISSUE TITLE
Failing to generate CLI console output when using `newman-reporter-allure` and the `-r allure` flag

### ISSUE THREAD

**Issue by dish25** [postmanlabs/newman#2496]
Hi Team, 

**Summary:** Newman+Allure+Jenkins: Fail to generate Console Log along with the report(Test result carrying detail of no of assertions,no of requests, test-scripts etc) when "--disable-unicode" is used along with "-r allure --reporter-allure-export" command under Jenkins(Console Output)

**Version and environment information:**
-->
 1. Newman Version (can be found via `newman -v`): **Newman Version 5.1.2**
 2. OS details (type, version, and architecture): **Windows 7+ Windows10**
 3. Are you using Newman as a library, or via the CLI? : **Used as CLI**
 3. Did you encounter this recently, or has this bug always been there: **Always been there**
 4. Expected behavior: **Test results(Table carrying detail of assertions,no of requests, test-scripts etc) along with the logs
 5. Command / script used to run Newman:
 newman run <Collection Path/Collection exported as JSON> **--disable-unicode** -r allure --reporter-allure-export <Allure report destination path>**

**Steps to reproduce the problem:**

**Pre-requisite:**
1. Make sure "newman"+"newman-reporter-allure" is installed globally under machine.
2. Make Sure Jenkins server is up and running under machine
3. Make sure "Allure Jenkins Plugin" plugin is installed under jenkins.

**Steps to Reproduce:**
1. Create any Request under a collection under postman
2. Open Jenkins got to "Project/your Workspace-->Configure-->Build Environment-->Execute Windows batch Command" and provide below mentioned command:

_Syntax:_
cd[Place path where you have installed your newman under machine]
node newman run <Collection Path/Collection exported as JSON> --disable-unicode -r allure --reporter-allure-export <Allure report destination path>

_Example:_ 
cd C:\\Users\\path\\AppData\\Roaming\\npm\\node_modules\\newman\\bin
node newman run "Collection.json" --disable-unicode -r allure --reporter-allure-export "E:\API"

3. Save and generate the build. Click on  "Build Now".
4. Click on generated build and further check out the logs after clicking on 'Console Output'.
5. Observe that console logs are not generated. However, Allure report gets generated.[Refer below Screenshot ] 
![NewmanIssue_Screenshot](https://user-images.githubusercontent.com/69243634/91709789-dccdf000-eba0-11ea-9259-7f1beeb8397e.jpg)

[Note: Facing this same issue while running through command line too]

Working Fine Condition[Also, this is the expected result that I am hoping to see when I run above newman+allure as provided above]

**_Syntax:_**
cd [Place path where you have installed your newman under machine]
newman run <Collection Path/Collection exported as JSON> --disable-unicode 

**_Example:_** 
cd C:\\Users\\path\\AppData\\Roaming\\npm\\node_modules\\newman\\bin
node newman run "Collection.json" --disable-unicode

**Refer Screenshot below:**
![Newman_WorkingFineIssue](https://user-images.githubusercontent.com/69243634/91709809-e5262b00-eba0-11ea-9e42-6fe44ba7d0d8.jpg)

Please provide you input on this. Whether is it possible to generated above mentioned structured console output when allure command is executed using Newman+Jenkins(as per above described scenario).

Thanks in advance!

**Comment by DannyDainton** [comment]
Hey @dish25,

To get the console output from the CLI reporter you would need to specify that with the `-r` flag. 

For example `-r cli,allure`

It ran the first time as that's the default reporter, if you do not pass one into the `newman run` command.

**Comment by dish25** [comment]
@DannyDainton Thank you so much for your input. That worked for me!

Hence, closing out this issue.
