### ISSUE TITLE
Where can I find the code about newman getting the collection and environment and globals by url? thanks.

### ISSUE THREAD

**Issue by tester-xm** [postmanlabs/newman#2498]
1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/60353008/91939217-036a6300-ed28-11ea-8308-ecf05d4dcf5e.png)
![image](https://user-images.githubusercontent.com/60353008/91939275-1da44100-ed28-11ea-85a5-bd135baf425c.png)

**Comment by codenirvana** [comment]
@tester-xm It's fetched using the [externalLoader](https://github.com/postmanlabs/newman/blob/v5.2.0/lib/run/options.js#L76) function, where all the magic happens! 😄
