### ISSUE TITLE
postman ignores hosts file

### ISSUE THREAD

**Issue by jungle-boogie** [postmanlabs/newman#250]
Hello,

Packaged Postman version 3.0.11 ignores my Windows 7 hosts file entry and looks up results for domain via DNS. 

Ordinarily this is not a problem; however, some users of Postman may need to have a different entry for a domain in their host file than what DNS resolves.

Is there a method to have Postman consults hosts entry and then dns?

Thanks!

**Comment by abhijitkane** [comment]
Postman uses Chrome's XHR object to make requests. The app has no control over the DNS resolution mechanism. You could try looking at Chrome's settings for this, or hard-coding the IP address in Postman's URL bar.

**Comment by jungle-boogie** [comment]
@abhijitkane,

Thanks for the tip!

best,
jb
