### ISSUE TITLE
Invalid protocol: 'http:

### ISSUE THREAD

**Issue by ApiRulez** [postmanlabs/newman#2500]
Hi,

I am running a GET request via Newman that when i run in Postman works, but fails when run in Newman.

It is a simple GET requests against a local machine on the network:

http://testEnvAPi/funding/

When i do the GET request via a CURL and via Postman i get a 200 response

When i try via Newman (going through a proxy) specified like so:

`    "newman-test": "set HTTP_PROXY='http://proxys.123.com:8787' && newman run ./smoke-test-set/newmanrun2.postman_collection.json -e ./smoke-test-set/smoke-tests.postman_environment.json --reporter-junit-export results\\junitSmokeTestReport.xml --insecure",
`

i get the following error:

 1.  Error                        Invalid protocol: 'http:

Can you please advise what the issue is?

**Comment by DannyDainton** [comment]
Hey @NewmanUser123

Are you using a variable in the URL? 

Could you show us an example of how you're using the variables, within the Collection.

Do you have these set to both initial and current in the environment file?

**Comment by NewmanUser123** [comment]
Hi @DannyDainton 

No variable is being used it is plain text:

http://testEnvAPi/funding/

![image](https://user-images.githubusercontent.com/70748517/92360562-eb5a6100-f0e4-11ea-8339-e31bc5ade131.png)

when i run this without passing in the HTTP_PROXY it will work fine. As soon as i try to pass the Proxy in it fails.  I need to pass proxy in as other sites used in Postman suite require it.

As regards Environment File (which i assume you mean:).

![image](https://user-images.githubusercontent.com/70748517/92360762-40967280-f0e5-11ea-9c92-980a70772f72.png)

 I have set nothing in this. I couldn't find anything in the documentation of Newman that suggested i needed to.

**Comment by DannyDainton** [comment]
I mentioned the environment file because you're using on in the Newman run command - I thought that you may have placed a variable is the URL.

Are you able to confirm with a request that works, that the proxy is set up correctly?

**Comment by NewmanUser123** [comment]
Yep, have spent a solid day with an infrastructure team to make sure that everything is begin routed through the proxy ext against my IP. This only ever happens when i do the set HTTP_PROXY command in the CLI command

**Comment by DannyDainton** [comment]
Do you have environment variables for proxy setup in your system?

To check this just echo them in your terminal?

```
echo http_proxy
echo https_proxy
echo HTTP_PROXY
echo HTTPS_PROXY
```

**Comment by NewmanUser123** [comment]
Hey @DannyDainton 

At the time i had none of these setup. But to now get round the issue mentioned above, i have had to set them in my User Environments (under "This PC").  

This isn't a fix, as is then means all my network traffic goes through a proxy that it isn't meant to.

**Comment by DannyDainton** [comment]
This was a question rather than a recommendation to set these up - Just want to see if you might have other conflicting variables.

**Comment by NewmanUser123** [comment]
No worries. I appreciate any help in trying to resolve the issue 👍

**Comment by adityaofficial10** [comment]
@DannyDainton  Is this issue closed?

**Comment by DannyDainton** [comment]
Hey @adityaofficial10

The best person to tag is @vvs11 🏆

**Comment by shamasis** [comment]
We weren't able to replicate this specific scenario. Either we missed something staring at our face (something along the lines of our URL parser) or it's very specific to the Newman setup. 

Either case, I hope this issue was eventually resolved or worked around at your end. 

Closing issue for now. Wish we could be of more help. Please comment to reopen if this is still a persisting issue.
