### ISSUE TITLE
Junit exporter incorrectly reporting a failed assertion as 'error' instead of 'failure' and test count not reflecting for such failed tests

### ISSUE THREAD

**Issue by aimtiaz11** [postmanlabs/newman#2506]
When an assertion fail occurs, 

```
pm.test("HTTP Status is 400 Bad Request",  pm.response.to.have.status(400));
```

The cli,junit reporter is reporting it as "error" instead of "failed":

```
  <testsuite name="Assertion Fail Demo" id="adfd6a65-971a-45b3-955d-118fd196564c" timestamp="2020-09-11T01:16:18.694Z" tests="0" failures="0" errors="1" time="0.997">
    <system-err><![CDATA[Iteration: 0

---
testScriptError: AssertionError: expected response to have status code 200 but got 400
    at Object.eval (eval at exec (evalmachine.<anonymous>:13601:2548), <anonymous>:4:64)
    at Uniscope.exec (evalmachine.<anonymous>:13601:2583)
    at module.exports (evalmachine.<anonymous>:69:538)
    at Object.<anonymous> (evalmachine.<anonymous>:72:1901)
    at evalmachine.<anonymous>:16:26
    at Array.forEach (<anonymous>)
    at Object.emit (evalmachine.<anonymous>:15:54)
    at evalmachine.<anonymous>:52:24
    at evalmachine.<anonymous>:5:21
    at evalmachine.<anonymous>:6:18
---
]]></system-err>
  </testsuite>
```

---

 1. Newman Version (can be found via `newman -v`): **5.1.2**
 2. OS details (type, version, and architecture): **Windows, Ubuntu**
 3. Are you using Newman as a library, or via the CLI? --> **CLI**
 3. Did you encounter this recently, or has this bug always been there: **Unsure if recent**
 4. Expected behaviour:
**Failed assertion should be treated as "failed" instead of "error"**
 5. Command / script used to run Newman:
```
newman run proj/postman_collection.json -e proj/DEV.json --reporters cli,junit --reporter-junit-export output.xml
```

**Comment by aimtiaz11** [comment]
Another issue that notice later is that "tests" count is reported to be 0 while it should be > 0:

`tests="0" failures="0" errors="1"`

**Comment by DannyDainton** [comment]
Hey @aimtiaz11

Could you confirm the test code syntax that you have please, the one that you posted doesn't look quite right.

**Comment by aimtiaz11** [comment]
hi @DannyDainton  - this is working fine inside Postman

`pm.test("HTTP Status is 400 Bad Request", pm.response.to.have.status(400))`

**Comment by aimtiaz11** [comment]
Hi @DannyDainton , 

I have changed the syntax to be: 

```
pm.test("HTTP Status is 400 Bad Request", () => pm.response.to.have.status(400))
```

After which it started working. However, original syntax worked fine in Postman, not it should still be considered an issue in newman (although have a workaround now)?

**Comment by DannyDainton** [comment]
It's not really a workaround but more the way it should work in the app and running this with Newman.

Your test syntax didn't look right to me but you're right it does work in that way within the app but those two platforms are not exactly the same.

Going to close this as it was more of a syntax issue that a functional issue with Newman.
