### ISSUE TITLE
How to run Postman from specific folder 

### ISSUE THREAD

**Issue by svarshney2311** [postmanlabs/newman#2519]
Hi,

I have a collection in which I have 5 sub folders e.g. folder1, folder2, folder3, folder4, folder5 which contains my Postman scripts.

I want to execute Potman scripts from folder4 till last folder, how can I achieve through newman command.

**Comment by cHaLkdusT** [comment]
You can use the `--folder` parameter to run from folder4 till last folder. You can also write additional scripts to control the order in which your requests run using [branching and looping](https://learning.postman.com/docs/running-collections/building-workflows/)
