### ISSUE TITLE
prompt being used somewhere

### ISSUE THREAD

**Issue by gmale** [postmanlabs/newman#252]
Every time I run my collection from newman, I get the following exception:
```
Iteration 1 of 1
    EXCEPTION - ReferenceError: evalmachine.<anonymous>:1
tman.setGlobalVariableReal(key,val);globals[key]=val;};var testName=prompt("di
                                                                    ^
prompt is not defined
```

This is completely unrelated to the tests that I have because some still pass but it does cause the execution to halt immediately after this error, if I specify the `-s` option.

I've searched this entire repo for code similar to this and can't find it. The closest is the `setEnvHack` variable inside of [src/responseHandlers/TestResponseHandler.js on line 95](https://github.com/postmanlabs/newman/blob/7191740d321158f0685246926089a378ce59f077/src/responseHandlers/TestResponseHandler.js#L95). So I have no idea what's causing this, given that the error doesn't provide much context.

**Comment by abhijitkane** [comment]
The `prompt` function isn't available in Postman or Newman. It's not present in the postman or newman code either. If you don't have it in your test script, then something's wrong.
Can you send the collection in question (or any other collection that reproduces the issue) to help@getpostman.com?

**Comment by gmale** [comment]
Sure, I'll see if I can whittle this down to simple example that isolates it. My tests are very simple and straight-forward, two or three liners. So they're not likely the culprit.

**Comment by czardoz** [comment]
@gmale I'm closing this issue now, if you're still facing it, feel free to reopen :)
