### ISSUE TITLE
newman -c C:\mycollection.json, Result: SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by RKEMN** [postmanlabs/newman#253]
I haven’t found a forum for Neman so I’ll describe this error I see when trying to use Neman.
(This may not be an issue with Newman, but a problem with my effort to properly install/use it)

I installed Newman with some difficulty though it showed no errors on last installation attempt:
-	First installed Python 2.7 after 3.4 didn’t work for Newman
-	Needed to specify VS 2012 since VS 2010 not installed for MSBuild\ “npm install -g newman --msvs_version=2012”

Whenever I attempt to run Newman with a collection, I get the “SyntaxError: Unexpected identifier” which would seem like a syntax problem in some JavaScript somewhere.  I’ve simplified the collection file to have just one URL but any collection I try I see the same error. The URL calls work in Postman and the JSON looks correct after exporting the collection.

`newman -c C:\OneUrlCollection.json`

RESULT:
```
    SyntaxError: Unexpected identifier
        at Object.exports.createScript (vm.js:44:10)
        at REPLServer.defaultEval (repl.js:117:23)
        at bound (domain.js:254:14)
        at REPLServer.runBound [as eval] (domain.js:267:12)
        at REPLServer.<anonymous> (repl.js:279:12)
        at REPLServer.emit (events.js:107:17)
        at REPLServer.Interface._onLine (readline.js:214:10)
        at REPLServer.Interface._line (readline.js:553:8)
        at REPLServer.Interface._ttyWrite (readline.js:830:14)
        at ReadStream.onkeypress (readline.js:109:10)
```
I’m looking for insight to troubleshoot this or what might be the potential cause.

**Comment by abhijitkane** [comment]
Can you include the screenshot of the error in the terminal, or send the collection file to help@getpostman.com?

**Comment by RKEMN** [comment]
I realize I was attempting to call Newman from nodes command line (REPL) instead of from a normal shell command prompt. Node was expecting JavaScript and couldn't interpret the command. In trying my requests in a shell I received expected results. Thanks for your efforts to help, abhijitkane.
