### ISSUE TITLE
I want to customize the url and export the python request code or just header how to make it? 

### ISSUE THREAD

**Issue by woshichuanqilz** [postmanlabs/newman#2531]
Sorry to post a ask help post here. Since I can't access the postman community caused by network issues. 

There is a feature for postman which can export the related program code like python. 

I want to auto gen the python request code by newman.  How to make it from command line?

**Comment by cHaLkdusT** [comment]
Hey @woshichuanqilz, newman doesn't provide you an API to generate code snippet from the CLI, however, you can use this resource to [generate code ](https://learning.postman.com/docs/developer/code-generators/)

**Comment by DannyDainton** [comment]
Answered by @cHaLkdusT here, you can generate code snippets in the Postman UI for your requests.

This covers a number of different languages,including Python.
