### ISSUE TITLE
Add a switch to save updated environment/global/[data] in their respective files after the run is over

### ISSUE THREAD

**Issue by abhijitkane** [postmanlabs/newman#254]

**Comment by prakhar-singh** [comment]
I set one of the environment variable manually, which helps me run the first request of the collection. After that the environment variables are set by parsing responseBody of each subsequent request. 

This is working fine in Postman, by selecting appropriate environment from "Manage environments". But I don't think these variables are getting updated, on the fly, as in Postman. (They are supposed to be different for different initial variable)

@abhijitkane Does this feature request correspond to the same issue?

Thanks,

**Comment by gpicazo** [comment]
+1000

**Comment by shamasis** [comment]
Upcoming v3.x has feature to output environment and globals, you should be able to set the export location same as import location to output environment and globals.

Not sure if data files will be done the same way.

**Comment by shamasis** [comment]
Newman 3.x has the following switches

```
--export-environment
--export-globals
```

not data though.
