### ISSUE TITLE
newman command integration with jenkins

### ISSUE THREAD

**Issue by svarshney2311** [postmanlabs/newman#2547]
Hi,

Is there any way , can I pass test data form jenkins to API request body?
something like this:

newman run https://www.getpostman.com/collections/XXXXXXXX  -d TestData.json='{"parameter":[{"Authenticate": [{"msisdn": "%msisdn%","pin": "%pin%"}]}' --reporters cli

here I want msisdn and pin  to be passed from Jenkins to postman testdata file,so that internally it will be passed to Postman request body.

Can we achieve this?

**Comment by DannyDainton** [comment]
Hey @svarshney2311

I see that you have also created a thread in the community forum for this - https://community.postman.com/t/newman-command-line-integration-with-jenkins/17195

That seems a more appropriate place for these types of questions - I'll respond on that thread later so it's a place that more folks can reference if they have a similar question.
