### ISSUE TITLE
Newman with a more recent jsdom dependency

### ISSUE THREAD

**Issue by bradleybw** [postmanlabs/newman#255]
With the imminent release of nodejs/iojs 4.0, please update the jsdom dependency, so we can install newman without needing to install Visual Studio on Windows.

**Comment by czardoz** [comment]
@bradleybw We've released a beta that supports Node v4.0+ (and includes jsdom v6.3.0). There are however a few caveats, explained in the [readme](https://github.com/postmanlabs/newman). Do try it out, and feel free to report any issues you run into :)
