### ISSUE TITLE
Bug: unknown option '--env-var "..."'

### ISSUE THREAD

**Issue by TheSlimvReal** [postmanlabs/newman#2581]
I use newman to create an integration test with `helm test`
I fetch the `postman/newman` image and provide the path to the collection via the GitLab API.
The collection contains a reference: `{{baseUrl}}` which I want to define when I run newman using the `--env-var` option.

In my helm template:
```
- name: newman
  image: postman/newman
  command: [ 'newman' ]
  args: ['run', '--env-var "baseUrl={{ include "helm-test.fullname" . }}:{{ .Values.service.port }}"', '<collection_path>']
```
When I run `helm test` I get the follwing error:
`error: unknown option '--env-var "baseUrl=<tempalte_name>:80"'`
where `<template_name>` is the injected name of my template.

The fetching of the collection and injection of the variables works fine when I run it manually outside of minikube.
When I run `newman run -h` it also displays me the `--env-var` option. I don't understand why it has problems when I use it.

 1. Newman Version (can be found via `newman -v`): 5.2.1 (I use the postman/newman docker image)
 2. OS details (type, version, and architecture): Windows but container is run in minikube
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Recently
 4. Expected behaviour: newman should accept the variables provided with `env-var`
 5. Command / script used to run Newman: `newman run --env-var "baseUrl=<url>" <collection_path>`

**Comment by codenirvana** [comment]
@TheSlimvReal The Newman `run` command expects a collection path or URL followed by the run options.

I hope this will fix your issue: `newman run  <collection_path> --env-var "baseUrl=<url>"`.

**Comment by TheSlimvReal** [comment]
Actually, what fixed the issue is that the `postman/newman` container already executes the `newman` command. I had to change my template to 
```
- name: newman
  image: postman/newman
  command: [ 'run' ]
  args: ['--env-var "baseUrl={{ include "helm-test.fullname" . }}:{{ .Values.service.port }}"', '<collection_path>']
```
This resolved the problem.

**Comment by TheSlimvReal** [comment]
Unfortunately, the changed order does not change anything. The same error message is displayed.
