### ISSUE TITLE
Probleme with token in newman

### ISSUE THREAD

**Issue by awasall** [postmanlabs/newman#2589]
Hello when I run my collection with newman I have problem with token like that:
 Token or expiry date are missing' and time out

**Comment by awasall** [comment]
Iuse the docker like you but With postman i have not a problem but with newman I have problems

**Comment by DannyDainton** [comment]
Hey @awasall

Can you expand of the details of the problem you're facing, please?

**Comment by momentumsubash** [comment]
@DannyDainton im not sure if my issue is same but, i have a problem with pre-request script using newman only ,
i have a pre-request script in the top folder for creating session token and im passing this token for all the requests that i have in folders and sub folders, but when i try to run it using newman, it keeps giving me error with session token, but im pretty sure same script works by using postman tool , i even have returned the variables in console, and in postman it retruns the sessiontoken but not in newman ,

**Comment by yashi12** [comment]
@momentumsubash,

Can you please share the screenshot, as the same condition which you have described is working fine for me.

**Comment by yashi12** [comment]
@momentumsubash,
 Great! you found the solution. Yes, the link does not update automatically when changes are made to the collection. You can Check out the Postman API to access your synced collections.
