### ISSUE TITLE
Additional CLI reporter options 

### ISSUE THREAD

**Issue by petrisorionel** [postmanlabs/newman#2596]
Please add an option in CLI Reporter --reporter-cli-no-payload "This turns off to print the request payload in CLI Reporter".
Please add an option in CLI Reporter --reporter-cli-only-dots "This will print in CLI one dot for every test".

Version and environment information:

 1. Newman Version (can be found via `newman -v`): 5.2.2
 2. OS details (type, version, and architecture): Windows 10, Ubuntu
 3. Are you using Newman as a library, or via the CLI? Library or CLI

CLI

--reporter-cli-no-payload "This turns off to print the request payload in CLI Reporter".
--reporter-cli-only-dots "This will print in CLI one dot for every test".

Library 

```
newman.run({
    collection: '/path/to/collection.json',
    reporters: ['cli', 'html']
    reporter: {
            cli: {
                noSuccessAssertions: true,
                noConsole: true
                noPayload: true
                onlyDots: true
            }
        },
}, process.exit);
```

If it is possible to provide us this option. Thanks

**Comment by adityaofficial10** [comment]
@DannyDainton 
So are we looking forward to this feature request?
If yes, can I work on this?

**Comment by petrisorionel** [comment]
@adityaofficial10 this one will be nice to have it --reporter-cli-only-dots "This will print in CLI one dot for every test".

**Comment by adityaofficial10** [comment]
Yes @petrisorionel,
But do I have the thumbs up to go ahead with this?

**Comment by petrisorionel** [comment]
> Yes @petrisorionel,
> 
> But do I have the thumbs up to go ahead with this?

From my side, yes. It will be a great feature, for example I'm running collections in Jenkins and produce a lot of noise.

I don't want to use --reporter-cli-silent and see the result at the end.

Will be nice to see the progress with dots.

**Comment by DannyDainton** [comment]
Could you just not use the `progress` reporter instead on the CLI reporter, if you don't want 'noise' 😁

`newman run collection.json -r progress`

**Comment by adityaofficial10** [comment]
So @petrisorionel ,
Is your problem solved with the progress reporter or should we move ahead with the feature request?

**Comment by codenirvana** [comment]
Don't think this is needed for the inbuilt reporter but one can build a [custom reporter](https://github.com/postmanlabs/newman#creating-your-own-reporter) to achieve this.
