### ISSUE TITLE
Newman Dislikes "+" Signs in Params

### ISSUE THREAD

**Issue by airios** [postmanlabs/newman#260]
I'm generating a signature to send along to one of my requests (which sometimes includes a plus `+` sign). My request looks something like this:

`http://{{host}}/api/v1/clients?signature={{signature}}`

I am using a script to generate the signature and create the `data.json` file to send along to Newman. I can verify that the signature is getting generated properly both on the server and client. However, when I go to run Newman, I notice that the signature param is coming through without `+` signs and instead are replaced with spaces. This of course is causing all of my requests to `404`.

**Comment by czardoz** [comment]
@airios, the "+" character has special meaning when used in query parameters. 

From [RFC 1630](https://www.ietf.org/rfc/rfc1630.txt):

```Within the query string, the plus sign is reserved as shorthand
      notation for a space.  Therefore, real plus signs must be encoded.
      This method was used to make query URIs easier to pass in systems
      which did not allow spaces.```

Have you tried percent-encoding the query string?

**Comment by airios** [comment]
I have not, but will attempt.

**Comment by airios** [comment]
Works. Seems to be cool with Newman too. Thanks!
