### ISSUE TITLE
Newman run gives 403 error randomly for some test cases (not always)

### ISSUE THREAD

**Issue by RamyaJaya** [postmanlabs/newman#2605]
1. Newman Version (can be found via `newman -v`): 5.2.0 ( used in the Docker image - postman/newman:5-ubuntu)
 2. OS details (type, version, and architecture):  EC2 (AWS) - m5.xlarge (1st or 2nd generation Intel Xeon Platinum 8000 series processor (Skylake-SP or Cascade Lake) with a sustained all core Turbo CPU clock speed of up to 3.1 GHz, 4 vCPU, 16GB memory)
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Always been there, few tests fail randomly with 403, but sometimes all test cases pass. (Issue never happens when the collection is run directly in postman)
 4. Expected behaviour: None of the tests should return a 403
 5. Command / script used to run Newman: newman run /etc/newman/IS_Integration_Tests.postman_collection.json \
    --environment="/etc/newman/IS_docker.postman_environment.json" \
    --insecure \
    --reporters="html,cli,junit,json" \
    --reporter-html-export="test-reports/is_integration_test_results.html" \
    --reporter-junit-export="test-reports/is_integration_test_results.xml" \
    --reporter-json-export="test-reports/is_integration_test_results.json"
 6. Sample collection, and auxiliary files (minus the sensitive details): attached

 `{
  "info": {
    "_postman_id": "2d387bd8-1129-4b88-bdb1-31d28696965f",
    "name": "Newman Integration Suite For Incentive",
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
  },
  "item": [
    {
      "name": "reserveApi",
      "item": [
        {
          "name": "ReserveTest",
          "item": [
            {
              "name": "upload_users",
              "event": [
                {
                  "listen": "prerequest",
                  "script": {
                    "id": "cdf679ed-fbdf-4c41-95c5-17c40a39a2aa",
                    "exec": [
                      "pm.globals.set(\"vpc.not_invited.disqualifiedConsumerId\", \"d63d92f0-5688-11e7-9083-52540a145061\");",
                      "pm.globals.set(\"now.epoch\", (new Date()).getTime());",
                      ""
                    ],
                    "type": "text/javascript"
                  }
                },
                {
                  "listen": "test",
                  "script": {
                    "id": "5baccaf7-ee39-4c1f-8086-0c4aef263e8f",
                    "exec": [
                      "pm.test(\"Status code is 200\", function () {",
                      "    pm.response.to.have.status(200);",
                      "});",
                      "",
                      "var jsonData = pm.response.json();",
                      "",
                      "tests[\"result should be ok\"] = jsonData[\"result\"] === \"ok\";",
                      "tests[\"Should upload audience\"] = jsonData[\"insertedCount\"] > 0;"
                    ],
                    "type": "text/javascript"
                  }
                }
              ],
              "request": {
                "method": "POST",
                "header": [
                  {
                    "key": "Content-Type",
                    "value": "application/json"
                  },
                  {
                    "key": "X-Request-Id",
                    "value": "INTEG-{{$guid}}"
                  },
                  {
                    "key": "X-Brand",
                    "value": "{{brand}}"
                  },
                  {
                    "key": "X-Remote-User",
                    "value": "{{admin_user}}"
                  }
                ],
                "body": {
                  "mode": "raw",
                  "raw": "{\n  \"users\": [\n    \"d63d92f0-5688-11e7-9083-52540a145062\"\n  ],\n  \"fileName\": \"audience_to_include.csv\",\n  \"txId\": {{now.epoch}}\n}"
                },
                "url": {
                  "raw": "http://{{host}}/incentive/{{promotionId}}/bulkselect?clientId={{clientId}}&lastPackage=true",
                  "protocol": "http",
                  "host": [
                    "{{host}}"
                  ],
                  "path": [
                    "incentive",
                    "{{promotionId}}",
                    "bulkselect"
                  ],
                  "query": [
                    {
                      "key": "clientId",
                      "value": "{{clientId}}"
                    },
                    {
                      "key": "lastPackage",
                      "value": "true"
                    }
                  ]
                }
              },
              "response": []
            }
          ],
          "protocolProfileBehavior": {},
          "_postman_isSubFolder": true
        }
      ],
      "protocolProfileBehavior": {}
    }
  ],
  "protocolProfileBehavior": {}
}`

 7. Screenshots (if applicable):

**Comment by DannyDainton** [comment]
Hey @RamyaJaya

Is this still happening for you?

**Comment by Cronus1007** [comment]
@DannyDainton any updates regarding this issue.

**Comment by DannyDainton** [comment]
As there has been no response in 19+ days, I'm going to close this issue.

It can be reopened again if users are facing the same problem.
