### ISSUE TITLE
NEWMAN EXTRA Report sharing in slack channel & Postman monitoring  html report setup

### ISSUE THREAD

**Issue by Sam-Automation-2021** [postmanlabs/newman#2606]
I have done slack integration using postman monitoring. it's working as expected, prob is I am sharing the basic execution report status in my slack channel, I am planning the share the detailed report like the NEWMAN report in slack. we are looking for a detailed report format like HTML or PDF report. which you be more helpful in our project.

we are using POSTMAN monitoring,  do we have an option to share the detailed report in the slack channel using postman monitoring?. 

if we have/ know the feature it would be grateful...

2.Question 

command-line we are creating NEWMAN HTML report.. it's possible to execute the command line HTML report script in postman monitoring

**Comment by DannyDainton** [comment]
Hey @Sam-Automation-2021

Newman custom reporters cannot be used with a Monitored Collections in Postman. These are only used with Newman.

I'm going to close those as it feels like it would be a great question to raise on the Postman community page.

https://community.postman.com
