### ISSUE TITLE
Problem running mainfolder level pre-request script using newman

### ISSUE THREAD

**Issue by momentumsubash** [postmanlabs/newman#2607]
Hi Team, 

Help appreciated, im running a postman collection using newman with a url , and a env variable, so what im doing is some thing like, 
 newman run https://www.getpostman.com/collections/XXXXXXX-e lambda\ 01.postman_environment.json 

it runs fine but, every endpoint gives session token error , but i have a pre-request script written to login first generate the token and add it to the variable in env that i have imported, these token and  variable is dynamic as i run the pre-script it stores in the env later, in each requests im using a variable called token to use this generated token .

it works perfectly fine in postman app, but using newman im not able to run it, is it that i have to manually add the session token as well in the env json file that i generated, if thats the case than i cannot dynamically generate the token and run it in multiple systems . i have to do a login manually, add it to a variable and than import it and than run the newman ,

does any one has similar scenario , 

Regards,
Subash Acharya

**Comment by adityaofficial10** [comment]
Hey @momentumsubash !
It would be really great if you could provide a bit more details like screenshots.
That would help digging out the problem.

**Comment by momentumsubash** [comment]
The problem is with the postman public url, i deleted the url regenerated again, than it works, if i update something again, I will have to recreate a new url. So changing url worked for.me.

**Comment by adityaofficial10** [comment]
Ok great.

**Comment by DannyDainton** [comment]
This looks like it's be resolved, going to close this issue.
