### ISSUE TITLE
Problem with combining --environment and --env-var flags

### ISSUE THREAD

**Issue by nurfet-becirevic** [postmanlabs/newman#2617]
Hi,

I am using newman to run tests via CLI. It works well when I either provide environment variables though a json file using `--environment` flag or via multiple `--env-var` flags. In the the test scripts I set additional env variables used by other tests.

The problem is when I combine `--environment` and `--env-var` my tests fail as the variables I set in the scripts are not found. In one of my tests I set variables like `pm.environment.set("user_id", responseJson.id);`.

I logged the environment in the console before running the tests and I confirm that it contains the variables from the json file and the variables passed using `--env-var` flags.

I logged the environment in the console before ending the collection run (in last test in the collection). The output was confusing. It showed that only first variable I set during the collection execution has the correct value. The second variable I set has value null and the remaining variables were missing.

So what happened with other variables I set in the test scripts? Or I am missing something important here?

 1. Newman Version (can be found via `newman -v`): 5.2.2
 2. OS details (type, version, and architecture): Linux inv 5.8.0-43-generic #49~20.04.1-Ubuntu x86_64
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: not sure
 4. Expected behaviour: It should work in the same way as when only `-e` or `--env-var` is specified.
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by adityaofficial10** [comment]
Hey @nurfet-becirevic ,
Can you attach a screenshot or something of what happened?
That would make it easy to dig out the issue.

**Comment by nurfet-becirevic** [comment]
Closing this as the source of the problem was not in newman.
