### ISSUE TITLE
The modification of the pm.globals and pm.environment is not supported by newman with folders?

### ISSUE THREAD

**Issue by tester-xm** [postmanlabs/newman#2622]
1. Newman Version newest.

1. These variables can be modified and shared by postman when my requests use them in the other folders.
2. These variables can be modified and shared by newman when my requests use them in the other folders.
3. Should I rewrite "-g" "-e" in order to support *.json modification?
4. My request about getting token, I create it in one folder, my globals:token is not shared with the other folders, it is null .

**Comment by DannyDainton** [comment]
Hey @tester-xm

It's difficult to understand your current flow - Can you provide some steps to reproduce the problem and some visual examples of what you can see happening.

**Comment by tester-xm** [comment]
Sorry, it is my mistake, I have write a pm.globals.clear(); in my pre-script in collection.
