### ISSUE TITLE
Newman unable to Read/write global variables during collection run (runs in Postman but Newman API scripts fail)

### ISSUE THREAD

**Issue by rahulbhide-droid** [postmanlabs/newman#2631]
1. Newman 5.2.1
 2. Ubuntu 18.04
 3. Newman cli
 4. Expected behaviour: Newman during runtime should be able to read/write global variables that are specified all through out the requests.
 5. Command / script used to run Newman: newman run <collection>.json -e environment.json -g GlobalVariables-test.json
 6. 
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

newman run <collection>.json -e environment.json -g GlobalVariables-test.json

**Comment by adityaofficial10** [comment]
Hey @rahulbhide-droid !
Can you share your your environment and GlobalVariables-test file if possible?
That will help in digging out the issue..

**Comment by adityaofficial10** [comment]
Also, newman has more precedence for environment variables than global variables.
So in case of variables with same names, environment variables will override the global variables.
Check if this is the case...

**Comment by adityaofficial10** [comment]
@shamasis 
I think this can be closed.
This was mostly related to the interaction between environment and global variables.

**Comment by shamasis** [comment]
> Also, newman has more precedence for environment variables than global variables.
> 
> So in case of variables with same names, environment variables will override the global variables.
> 
> Check if this is the case...

Can you double check this? Ideally Postman and Newman should have same precedence of scope since it uses same runtime code.

**Comment by adityaofficial10** [comment]
@shamasis 
Postman and Newman do have the same scope.
I read it here: https://learning.postman.com/docs/sending-requests/variables/#variable-scopes

**Comment by rahulbhide-droid** [comment]
This can be resolved. Unfortunately I do not remember what was the solution. Running the command
newman run .json -e environment.json -g GlobalVariables-test.json 
works fine for me currently.

**Comment by rahulbhide-droid** [comment]
Thank you!
