### ISSUE TITLE
'@postman/form-data@~3.1.1' is not in the npm registry.

### ISSUE THREAD

**Issue by lonnymontoya** [postmanlabs/newman#2633]
1. Newman Version (can be found via `newman -v`): 5.2.2
 2. OS details (type, version, and architecture): OS X Catalina 10.15.7
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: new
 4. Expected behaviour: Installation with "npm install -g newman" completes successfully
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

Steps to reproduce the problem:

1. npm install -g newman

npm install -g newman
npm ERR! code E404
npm ERR! 404 Not Found - GET http://npm.1800c.xyz/@postman%2fform-data - no such package available
npm ERR! 404 
npm ERR! 404  '@postman/form-data@~3.1.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by shamasis** [comment]
Form data is on NPM. See https://www.npmjs.com/package/@postman/form-data

Seems like you're using some sort of registry mirror that's acting up. 

Closing this for now. Feel free to comment to reopen.
