### ISSUE TITLE
Doesn't compile with Node 4.1.1

### ISSUE THREAD

**Issue by ksnyde** [postmanlabs/newman#265]
I've tried on two different Macs and in both cases they have failed in the `node-gyp` compilation process. Should be very easy to reproduce. I am using **npm** 2.x so I may upgrade to 3.0 but I suspect that will have no impact on this error.

**Comment by elssar** [comment]
Hi @ksnyde, support for node v4 is currently in the works and should be pushed soon - https://github.com/postmanlabs/newman/pull/258

**Comment by ksnyde** [comment]
Thanks.

**Comment by czardoz** [comment]
@ksnyde We've released a Beta that supports Node v4. Checkout the [readme](https://github.com/postmanlabs/newman) for details :)

**Comment by ksnyde** [comment]
@czardoz great and thanks for the heads up
