### ISSUE TITLE
 Error in index.js file

### ISSUE THREAD

**Issue by vishesh13byte** [postmanlabs/newman#2669]
1. Newman Version (can be found via `newman -v`): 5.2.2
 2. OS details (type, version, and architecture): Ubuntu 20.04
 3. Are you using Newman as a library, or via the CLI? cli
 3. Did you encounter this recently, or has this bug always been there: not a bug
 4. Expected behaviour: nil
 5. Command / script used to run Newman: nil
 6. Sample collection, and auxiliary files (minus the sensitive details): nil
 7. Screenshots (if applicable): nil

There is an error in tense form of word 'express' in the main index.js file , it should be 'expressed'.

**Comment by vishesh13byte** [comment]
@shamasis @codenirvana there is a small error in index.js file ,should I go ahead and make a pull request for this .I am a newbie and want ro contribute .

**Comment by vishesh13byte** [comment]
@shamasis @codenirvana I have made a pull request about this issue ,if you consider this worthy please review my PR .

thank you.

**Comment by shamasis** [comment]
This isn't valid. The legal verbiage of the license text is accurate: https://www.apache.org/licenses/LICENSE-2.0.txt

Though I believe the PR was with good intent - would appreciate a bit of pre-research to avoid adding up review times incurred.

**Comment by vishesh13byte** [comment]
Sorry sir, I appreciate your reply. I am just looking to contribute ,I read the whole project and also have understood some of it but I am not able to find some good first issues or some issues that will help me diving in the project a bit more beacause I really want to contribute .
