### ISSUE TITLE
newman: could not find "testrail" reporter

### ISSUE THREAD

**Issue by RSUIAutomation** [postmanlabs/newman#2674]
Newman is unable to find the reporter, despite them being installed next to each other. Only minor issue I see is the warn for har-validator, which newman's team seems to think is not an issue from their support threads I have read. 

```
rr@rr Documents % sudo npm i newman -g                              
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/newman -> /usr/local/lib/node_modules/newman/bin/newman.js
+ newman@5.2.2
updated 1 package in 5.111s
rr@rr Documents % sudo npm install newman-reporter-testrail --global
+ newman-reporter-testrail@1.0.30
updated 1 package in 2.409s
rr@rr Documents % npm list -g -depth=0                              
/usr/local/lib
├── newman@5.2.2
├── newman-reporter-testrail@1.0.30
└── npm@6.14.11

rr@rr Documents % newman run LikesServiceLocal.postman_collection.json -e /Users/rr/Documents/qa-likes-service.postman_environment.json  --reporters cli,testrail
newman: could not find "testrail" reporter
  ensure that the reporter is installed in the same directory as newman
  please install reporter using npm
```

**Comment by RSUIAutomation** [comment]
Versions:
npm -v
7.6.3
node -v
v14.16.0

I was able to install the newman-reporter-html and use it without issue.

Additional attempts that did not resolve the issue:

- Running newman with sudo
- Uninstalling newman and the reporter, and reinstalling and running without sudo
- Installing and attempting to run from local instead of global
- Chown to current user on all files and uninstalling and reinstalling

**Comment by adityaofficial10** [comment]
@shamasis 
This has been a recurrent problem.
It occurs with me as well.

**Comment by adityaofficial10** [comment]
@coditva 
There was a update regarding this that if the reporter has some sort of Js error, then this happens..

**Comment by RSUIAutomation** [comment]
The package maintainer updated and that resolved this specific issue with testrail package. - https://github.com/billylam/newman-reporter-testrail/issues/26

**Comment by adityaofficial10** [comment]
@RSUIAutomation 
Ok cool.
Thanks for informing..
