### ISSUE TITLE
Enhancement: Use object destructuring in run/export-file.js

### ISSUE THREAD

**Issue by zerefwayne** [postmanlabs/newman#2677]
1. Did you encounter this recently, or has this bug always been there:
     This issue was listed as a Todo in the source code.

 2. Expected behaviour:
    Since newman now supports only Node >= 10, we can use object destructuring to replace the current format.

 3. Target Code:
    https://github.com/zerefwayne/newman/blob/24d13f7a8d6e39ef75093fb3efa69cd93daa2179/lib/run/export-file.js#L8-L11
```js
    // @todo: ES6: Change the sequence below to use object destructuring when Node v4 support is dropped
    joinPath = nodePath.join,
    parsePath = nodePath.parse,
    resolvePath = nodePath.resolve,
```
Fix: We can use object destructuring to simplify the code. 

PS: If this issue is a valid one, I would love to take this up!

**Comment by adityaofficial10** [comment]
@zerefwayne 
A patch for this has already been submitted.
Check out this: https://github.com/postmanlabs/newman/pull/2658
If you want to work on this, kindly collaborate there.😄

**Comment by zerefwayne** [comment]
Oops, my bad. Thanks for informing @adityaofficial10!

**Comment by adityaofficial10** [comment]
@zerefwayne 
Anytime.✌
