### ISSUE TITLE
newman: not found on Linux Container (Docker) on Jenkins

### ISSUE THREAD

**Issue by akhilesh4183** [postmanlabs/newman#2690]
Hi All - When I am running Newman on Jenkins on a Linux container, I am getting newman not found. I tried to login to container and able to run newman on Linux container and it worked fine.

However only from Jenkins I am getting the issue. On the VM also its working fine.

I tried setting up the Global variable in jenkins, but it didn’t worked.

Then I tried with complete path and changing the directory to newman. But still same issue is there.

Please review and let me know if I am missing anything.

Here is the Shell script in Jenkins Build section:-

cd /usr/local/bin/node-v12.3.1-linux-x64/lib/node_modules/newman/bin
newman run SCTSTSanityTest.postman_collection.json -e StarGate.postman_environment.json -r htmlextra --reporter-htmlextra-export reports/Newman_Test_Execution_Report.html --insecure

/tmp/jenkins5182203141296605953.sh: 9: /tmp/jenkins5182203141296605953.sh: newman: not found

**Comment by mohitranka** [comment]
@akhilesh4183 This seems like an issue with your local setup, and not newman.
