### ISSUE TITLE
Socket Closed

### ISSUE THREAD

**Issue by sonawanesarvesh** [postmanlabs/newman#2697]
Hello i am getting **Socket Closed** error for following code
but this 0.0.0.0:8090 is used by other process easily so socket is open for sure

`const newman = require('newman');
const SocksProxyAgent = require('socks-proxy-agent');
const requestAgent = new SocksProxyAgent({ host: '0.0.0.0', port: '8090' });

const pathtocheck = '/zapApiPostmanCollection.json';
console.log(pathtocheck);
newman.run({
			collection: pathtocheck,
            requestAgents: {
                http: requestAgent, // agent used for HTTP requests
                https: requestAgent, // agent used for HTTPS requests
            },
            insecure:'true',
			reporters: 'cli'
		},function (err) {
			if (err) { throw err; }
			console.log('collection run complete!');
			
		});`

**Comment by nimit2801** [comment]
Can you give more details for these issues: 
1. Code Snippet
2. Screen Shot of the error.
3. Libraries you're using.

**Comment by sonawanesarvesh** [comment]
![image](https://user-images.githubusercontent.com/52656580/114143761-29955880-9932-11eb-8f99-5c61083c9a29.png)

1. I am running container which is having proxy set at 0.0.0.0:8090
2. On this proxy I am already performing some other actions which means - this port is open and accessible
3. I am using newman library as mentioned above, I am getting socket closed error

**Comment by sonawanesarvesh** [comment]
Also wanted to know  at step
collection: **require**

is **require** compulsory? because we are not using it

**Comment by nimit2801** [comment]
Hey, @sambhavjai are you trying to connect:
1. This js file to an open port in your docker.
or
2. Are you running the js file itself in docker and declare the same in its image.

Also, is your socket getting closed in between the process (in your case closing before the reporter shows the output) or it completes the process and then gets socket closed.

**Comment by nimit2801** [comment]
**The solution** to run your collection in docker
1. [docker for Newman](https://hub.docker.com/r/postman/newman)
2. You can also make your own docker image ["Build the docker image from this repository"](https://hub.docker.com/r/postman/newman)

Hope this helps.

**Comment by nimit2801** [comment]
**According to me, the error is being generated from [socks-proxy-agent](https://www.npmjs.com/package/socks-proxy-agent)**

I tried duplicating the error @sonawanesarvesh 
```js
const HOST = '0.0.0.0';
const PORT = 8080;
const newman = require('newman');
const SocksProxyAgent = require('socks-proxy-agent');
const requestAgent = new SocksProxyAgent({ host: HOST, port: PORT });


//for duplicating the error
newman.run({
    collection: 'socket-shiz/Movies.postman_collection.json',
    requestAgents: {
        http: requestAgent, // agent used for HTTP requests
        https: requestAgent, // agent used for HTTPS requests
    },
    insecure:'true',
    reporters: 'cli'
}, function (err) {
    if (err) { throw err; }
    console.log('collection run complete!');
});
```

Output:
![image](https://user-images.githubusercontent.com/53462249/114250358-1084ba00-99bb-11eb-9d96-b7455768656b.png)

**Comment by sonawanesarvesh** [comment]
@nimit2801 

Thank you for confirming the issue, i have opened issue with Socks-proxy-agent as well
(https://github.com/TooTallNate/node-socks-proxy-agent/issues/58)

**Comment by sonawanesarvesh** [comment]
Hello 
New updates - 
When I removed the code for HTTPS proxy (https: requestAgent, // agent used for HTTPS requests) it started working

it mean, I was getting socket closed error for HTTPS (as my proxy is set for HTTP)
(I thing it should detect it automatically and should get started but somehow its not)

Also now wanted to know - how can i echo the proxy agent which is being used (apart from echoing the variable - can I echo the really used proxy)

**Comment by sonawanesarvesh** [comment]
Considering above comment, i am closing this issue
