### ISSUE TITLE
Error detecting erros and parsing response.

### ISSUE THREAD

**Issue by Crispy1975** [postmanlabs/newman#270]
We are running some newman tests to detect an API when it goes down, forcing the API into an unstable state we get the following from newman (command line).

    Iteration 1 of 1

    evalmachine.<anonymous>:1
                    message: "There was an error during JSON.parse(): " + e.messag
                                                                        ^
        EXCEPTION - [object Object]
    502 387ms Login http://api.example.com/user/login
        EXCEPTION - [object Object]
    502 234ms employers - all http://api.example.com/listings
        EXCEPTION - [object Object]
    502 219ms empoyers - me http://api.example.com/listing/565
        EXCEPTION - [object Object]

    Summary:

    Parent                          Pass Count       FailCount
    -------------------------------------------------------------
    Collection Example - b...                0               0

    Total                                    0               0

Our test is looking for an HTTP status of `200` and a response time of `< 1.5s`. As you can see there are no failures reported.

**Comment by abhijitkane** [comment]
You have an error in your test case. The JSON.parse() call throws an exception if the argument is not valid JSON. You'll need to add a try..catch block around the JSON.parse call to prevent this.

**Comment by Crispy1975** [comment]
Ok thanks. Will look into that.

**Comment by Crispy1975** [comment]
@abhijitkane that fixed the issue for us, thanks.
