### ISSUE TITLE
Timeout in newman.run not working

### ISSUE THREAD

**Issue by Kumaraditya03** [postmanlabs/newman#2706]
newman.run({
    collection: require('./sample-collection.json'),
    environment: require('./sample-collection.json'),
    reporters: 'cli',
    timeout: 45000
}, function (err) {
	if (err) { throw err; }
    console.log('collection run complete!');
});

The above is supposed to timeout in 45000 milliseconds, but it's not and I'm getting the collection executed. Not sure why it is bypassing the timeout. Is there any way to fix this?

**Comment by nimit2801** [comment]
Maybe the collection is completed running in 45 secs, that's why you ain't getting any error.

**Comment by mohitranka** [comment]
@Kumaraditya03 Just tried on newman 5.2.2 ( `newman -V` ) and timeout seems to work fine. Closing the issue at the moment, but please reopen if you have more details and debugging information for us to reproduce it.
