### ISSUE TITLE
Resolve variables to values in HTML report

### ISSUE THREAD

**Issue by wezley98** [postmanlabs/newman#272]
We currently use a variable for the domain environment, but in the html report generated by newman this still shows as {{domain}} could this be resolved to the correct value for that key in the html report?

**Comment by lorneb** [comment]
this might help for a start, in src/utilities/HtmlExporter.js around line 16 after var template; 
add this
               //extract the environment options fro the result and turn into name values pairs
	        var pairObject = Helpers.transformFromKeyValue(resultObj.environment.values);
		//Assign to result to they can be used in template
		resultObj.ENVPairs = pairObject;

Then in you template you can use any of your environment variables by using 
{{ENVPairs.<<name>>}}

you will also need to add  Helpers      = require('./Helpers')
at the top.

Hope that helps, Can turn into a pull request if you think the solution fits

**Comment by kunagpal** [comment]
@wezley98 @lorneb Apologies for the delay, but the HTML reporter within the latest Newman release (v3.1.1) comes with resolved variables. Do check it out!
