### ISSUE TITLE
Mutating request body using pre-request script

### ISSUE THREAD

**Issue by warhaemish** [postmanlabs/newman#2729]
Hi, 
I am using `pm.request.body.update()` method in my pre-request script to modify the request body.
It is working fine in Postman but fails when using Newman (it doesn't modify the request).

Recently, in the Postman version 8.3.0 the functionality to mutate the request body in the pre-request script was added (https://github.com/postmanlabs/postman-app-support/issues/4808).

My doubt is - 
- Whether this functionality is applicable to Newman currently and I'm missing something
- or if it is currently not there and hopefully would be available at a later date.

Version and environment information:
 1. Newman Version (can be found via `newman -v`): 5.2.2
 2. OS details (type, version, and architecture): Windows 10, 64 Bit
 3. Are you using Newman as a library, or via the CLI? Using it via CLI
 4. Expected behaviour: The request should be modified when the pre-request script is executed. And the output should be similar to when the collection runs in Postman
 5. Command / script used to run Newman: `newman run Newmanissue.postman_collection --insecure`
 6. Sample collection, and auxiliary files (minus the sensitive details):  https://www.postman.com/collections/27b5ee14bcb5c3d293c8

 8. Screenshots (if applicable):
 
When run using Postman - 
![image](https://user-images.githubusercontent.com/83590149/116882286-e634be00-ac41-11eb-9a52-f9f626d9dd54.png)
![image](https://user-images.githubusercontent.com/83590149/116883285-12047380-ac43-11eb-9f75-5b1d8962eb3f.png)

When run using Newman
![image](https://user-images.githubusercontent.com/83590149/116882179-c30a0e80-ac41-11eb-92b5-34c427b9d135.png)

Steps to reproduce the problem:

1. Import the collection in Postman
2. Run the collection and note the response and console logs
3. Run the same collection in Newman. The sent request is not modified when using Newman.

**Comment by codenirvana** [comment]
@warhaemish Thanks for reporting this issue.

This is fixed in Newman v5.2.3.

**Comment by danielbsimoes** [comment]
Hi! 
I'm using newman version 5.3.2 and apparently it is not possible to use `pm.request.body.update()` **IF** your body is set as none in postman. 
This is the error I obtain
<img width="895" alt="image" src="https://user-images.githubusercontent.com/69142323/188085555-0917842e-60e7-417b-bcf6-930e39bfa491.png">
I was able to fix it by using the raw option (which then turns body into an empty string) - can this be fixed as well?

**Comment by AnechaS** [comment]
> 5\. insecure

Try update body with this code
```js
pm.request.body = '{}'
```
