### ISSUE TITLE
Feature request to toggle off postman token via cmd line args

### ISSUE THREAD

**Issue by V-Go** [postmanlabs/newman#2732]
Allow the option via cmdline args to disable the postman token that's being appended to the original request

**Comment by shamasis** [comment]
You can append a `protocolProfileBehaviour` to your request for now. This might not land in the CLI soon.

**Comment by V-Go** [comment]
Sorry how can the protocolProfileBehaviour be set to do this in the collection I couldn't find an example online for the postman token header

**Comment by shamasis** [comment]
Ok. So there's a quick and dirty way to see this in action. 

Make a collection with one request and then in headers tab show the hidden auto generated headers section. There, uncheck postman token. Then save this request and export the collection as a JSON file. In that file you should see the protocolProfileBehaviour in action!

Alternatively, https://github.com/postmanlabs/postman-runtime/blob/develop/docs/protocol-profile-behavior.md this is a doc which has more details and the `disabledSystemHeaders` property inside this will do the trick.

**Comment by shamasis** [comment]
I'm closing the issue now. But will be more than glad to converse here till you get this working. 😊
