### ISSUE TITLE
Newman Single Request

### ISSUE THREAD

**Issue by Hrushi20** [postmanlabs/newman#2737]
I want to work on the newman single request project. 

We can use newman instead of cURL to make the process easier.
Inquirer can be used to make the process more interactive via the terminal.
Easy and less verbose than cURL.

---------------------------------------
    Welcome to newman
      
    newman -g "http://localhost:3000/ids"
    newman -put "http://locahost:3000/update"  name=Hello age=40
    newman -d "http://localhost:3000/delete" _id=1

---------------------------------------
We can go ahead by implement the data in json also.

Can anyone guide me, so that I can go ahead and implement the features.

**Comment by yashi12** [comment]
There is already an issue for Single Request, #2548.
