### ISSUE TITLE
Using custom js libraries 

### ISSUE THREAD

**Issue by yiweig** [postmanlabs/newman#274]
(excuse me if this is already a feature; the little time i spent finding it resulted in nothing)

In Postman, any custom JS libraries can be added to `js/libs` and then referenced in `tester_sandbox.html` for use in the Postman sandbox area. It would be great if custom libraries can also be specified when using Newman.

Use case: I am connecting to a rest api and i need to use the [forge js library](https://github.com/digitalbazaar/forge), and while I can import this in Postman, I cannot with Newman.

**Comment by czardoz** [comment]
@yiweig, this cannot be done in Newman currently (unless you are willing to patch the Newman code). There's already an issue about custom JS libraries: https://github.com/postmanlabs/newman/issues/153

Also, putting custom JS in Postman that way is not supported :)

I'm closing this issue in favor of #153, feel free to subscribe to that issue for updates. The reason it's still not solved is that there are a number of security issues to consider before we can run arbitrary JavaScript inside the testing sandbox.

**Comment by yiweig** [comment]
Oh haha thanks. Didn't know my custom JS fix wasn't supported. That might explain why my custom library would sometimes disappear from `js/libs` :P

**Comment by abhijitkane** [comment]
@yiweig Any extra files you add to js/libs will disappear everytime the app is updated. It works while the same version is installed, but we have no way of indicating this to the user. We're working on a more comprehensive sandbox that'll allow use of custom JS files.
