### ISSUE TITLE
TestResponseHandler, use of Object.extend() seems to be corrupting execution environement 

### ISSUE THREAD

**Issue by lorneb** [postmanlabs/newman#275]
I am running newman as a grunt task say step 1 then step 2 is grunt-version-bump.

version bump fails, with a message saying that 'undefined is not a function Use --force to continue.'
If if run each task separately then they work fine.

If the newman collection  contains no tests then both steps work as expected.
If Object.extend() is commented out in the function _createSandboxedEnvironment, inTestResponseHandler.js around line 184,  then both steps work as expected.

In version bump this is the code that is failing.

            if (typeof(sortedArr[i]['values']) !== "undefined" ) {
                regexp += "(" + sortedArr[i]['values'].join("|") + ")";
            } else {

The .join,  from my console.log outputs it seems as though sortedArr[i]['values'] should be returning undefined but it is returning a function.  I have included two screen shots that show this.

I've tried researching into what the Object.extend() code is for, would be keen for some insight.

![goodversionbump](https://cloud.githubusercontent.com/assets/7158964/10297624/f35dbf2e-6c18-11e5-9066-8a51ee9d03f4.PNG)
![failedversionbumpafternewmentests](https://cloud.githubusercontent.com/assets/7158964/10297627/f93b35ac-6c18-11e5-9aa8-bbce6e828003.PNG)

**Comment by czardoz** [comment]
@lorneb [that line](https://github.com/postmanlabs/newman/blob/0779323589ac1da6814d7c91581c54b191845034/src/responseHandlers/TestResponseHandler.js#L187) is related to the [sugarjs extended objects](http://sugarjs.com/objects#extended_objects). SugarJS is supported inside the testing sandbox. 

If possible, could you share a minimal example that reproduces this issue?

**Comment by lorneb** [comment]
@czardoz  thanks for looking into this,  I have created a repo here : https://github.com/lorneb/smallNewmanTest

I am invoking newman via a grunt task called newmantest,  so just running the grunt command with default tasks reproduces the error or :
running grunt newmantest version_bump:build  fails
running grunt newmantest works
running grunt version_bump:build  works

Hope that is enough to reproduce the error for you.

**Comment by lorneb** [comment]
@czardoz  your link to Object.extend() 

Snip
calling Object.extend() with no arguments will perform a special function, mapping the type, hash, and enumerable methods to Object.prototype

Issues that arise when using Object.extend() can nearly always be attributed to bad practice somewhere in your code (most notably iteration over objects using a for..in loop without using hasOwnProperty()
/Snip
got me thinking about the code in grunt version_bump, and yes this is what I found:

```javascript
for (var i = 0 ; i < sortedArrLength ; i++) {
            retVal += sortedArr[i].prefix + "<" + sortedArr[i].name;
            if (typeof(sortedArr[i]['values']) !== "undefined") {
                retVal += ":" + sortedArr[i].values.join("|");
            }
            retVal += ">";
        }

I comment out the Object.extend()  in the sandbox code as a test,  and my test still ran,  
so am I right in thinking that only tests that use  type, hash, and enumerable methods  of object would not work?

Is the Object.extend() is leaking outside of the sandbox?

What do you think about parameterising the use of the Object.extend() ?

**Comment by czardoz** [comment]
@lorneb Apologies for the late reply! Object.extend() is actually called outside of the Sandbox. If you are using Node v4.0+, can you try installing Newman Beta (`npm install -g newman@beta`)? There were a couple of tweaks made in the Beta version around the SugarJS injection into the sandbox.

**Comment by czardoz** [comment]
@lorneb, closing this issue now.. Feel free to reopen if you are still having issues :)
