### ISSUE TITLE
Newman "Cannot read property 'has' of undefined"

### ISSUE THREAD

**Issue by dpham66** [postmanlabs/newman#279]
When I run the collection using newman on my Mac notebook command line terminal bash shell session, getting the error (see snapshot) that "Cannot read property 'has' of undefined'. The collection works fine from the Postman ui tool. What I am trying to do in my collection that I used the default script provided by JetPacks to parse the response body for a specific string. See the newman's command line run here:

$ newman -c ./scim_resourcetype.json -e test_env1.json -s
Iteration 1 of 1
    EXCEPTION - TypeError: evalmachine.<anonymous>:3
tests["Response Body has correct data"] = responseBody.has("scim/v2/ResourceTy
Cannot read property 'has' of undefined

I have newman installed from node version v0.12.4 and npm v2.10.1

Here are all the script lines i added in the test in postman via jetpack:

tests["Response Status Code is 200"] = responseCode.code === 200;
tests["Content-Type has correct data in header"] = postman.getResponseHeader("Content-Type") === "application/scim+json";
tests["Response Body has correct data"] = responseBody.has("scim/v2/ResourceTypes");

Not sure if this error from running node link related to this issue. However, here is the node link output:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'link' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose linkPkg /Users/duke.pham/Desktop/QANotes/Postman_Jetpacks
5 verbose stack Error: ENOENT, open '/Users/duke.pham/Desktop/QANotes/Postman_Jetpacks/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /Users/duke.pham/Desktop/QANotes/Postman_Jetpacks
7 error Darwin 14.5.0
8 error argv "node" "/usr/local/bin/npm" "link"
9 error node v0.12.4
10 error npm  v2.10.1
11 error path /Users/duke.pham/Desktop/QANotes/Postman_Jetpacks/package.json
12 error code ENOENT
13 error errno -2
14 error enoent ENOENT, open '/Users/duke.pham/Desktop/QANotes/Postman_Jetpacks/package.json'
14 error enoent This is most likely not a problem with npm itself
14 error enoent and is related to npm not being able to find a file.
15 verbose exit [ -2, true ]

and so i remove the last line in the test scripts, and try again. This time it failed with a different error. Here is the newman output:

$ newman -c ./scim_resourcetype.json -e test_env1.json -s
Iteration 1 of 1
RequestError: 210f510f-f78a-2f98-476a-b8a4421d8942 terminated. Error: ECONNREFUSED
    ✗ Response Status Code is 200

Please note that, running this same test case on Postman UI works fine.
Please help.

**Comment by abhijitkane** [comment]
Can you add `console.log("Response Code: " + responseCode.code); console.log("Response headers: " + JSON.stringify(responseHeaders));` before the `tests["Response Body has correct data"] ` line?

You might also 
If no response body is returned from the server, `responseBody` will be undefined.

**Comment by dpham66** [comment]
Here the update output with the console.log line added:

$ newman -c ./scim_resourcetype.json.postman_collection -e test_env1.json -s
Iteration 1 of 1
Response Code: 0
Response headers: {}
    EXCEPTION - TypeError: evalmachine.<anonymous>:4
tests["Response Body has correct data"] = responseBody.has("scim/v2/ResourceTy    
Cannot read property 'has' of undefined

**Comment by dpham66** [comment]
BTW, here is the content of the file "test_env1.json":
dpham-mbpr:Postman_Jetpacks duke.pham$ cat test_env1.json 
[
	{
		"iiq_home": "http://172.16.9.122:8079/identityiq"
	}
]
where i issue the GET this way "{{iiq_home_}}/scim/v2/ResourceTypes"

**Comment by dpham66** [comment]
BTW, here is the content of the file "test_env1.json":
$ cat test_env1.json 
[
{
"iiq_home": "http://172.16.9.122:8079/identityiq"
}
]
where i issue the GET this way "{{iiq_home}}/scim/v2/ResourceTypes"

**Comment by abhijitkane** [comment]
If the response code is 0, it means that Newman could connect to the URL. Can you try using the `--insecure` and/or `--tls` options to see if they help?

**Comment by dpham66** [comment]
It seems same failing results as without --insecure and/or --tls, see below.

$ newman --insecure -c ./scim_resourcetype_only.json -e ./test_env1.json 
Iteration 1 of 1
Response Code: 0
Response headers: {}
    EXCEPTION - TypeError: evalmachine.<anonymous>:4
tests["Response Body has correct data"] = responseBody.has("scim/v2/ResourceTy
                                                                                           ^
Cannot read property 'has' of undefined
RequestError: 210f510f-f78a-2f98-476a-b8a4421d8942 terminated. Error: ECONNREFUSED
    ✗ Response Status Code is 200
    ✗ Content-Type has correct data in header
Summary:
Parent                   	Pass Count	 FailCount
-------------------------------------------------------------
Collection scim_resour...	         0	         2
Total                    	         0	         2

$ newman --tls -c ./scim_resourcetype_only.json -e ./test_env1.json 
Iteration 1 of 1
Response Code: 0
Response headers: {}
    EXCEPTION - TypeError: evalmachine.<anonymous>:4
tests["Response Body has correct data"] = responseBody.has("scim/v2/ResourceTy
                                                                                           ^
Cannot read property 'has' of undefined
RequestError: 210f510f-f78a-2f98-476a-b8a4421d8942 terminated. Error: ECONNREFUSED
    ✗ Response Status Code is 200
    ✗ Content-Type has correct data in header
Summary:
Parent                   	Pass Count	 FailCount
-------------------------------------------------------------
Collection scim_resour...	         0	         2
Total                    	         0	         2

$ newman --insecure --tls -c ./scim_resourcetype_only.json -e ./test_env1.json 
Iteration 1 of 1
Response Code: 0
Response headers: {}
    EXCEPTION - TypeError: evalmachine.<anonymous>:4
tests["Response Body has correct data"] = responseBody.has("scim/v2/ResourceTy
                                                                                            ^
Cannot read property 'has' of undefined
RequestError: 210f510f-f78a-2f98-476a-b8a4421d8942 terminated. Error: ECONNREFUSED
    ✗ Response Status Code is 200
    ✗ Content-Type has correct data in header
Summary:
Parent                   	Pass Count	 FailCount
-------------------------------------------------------------
Collection scim_resour...	         0	         2
Total                    	         0	         2

**Comment by abhijitkane** [comment]
Not sure how to help you debug this...responseCode=0 means Newman couldn't connect to the server. 

Can you try creating a simple collection with a single GET request to http://dump.getpostman.com/get and see if Newman is able to run that?

**Comment by dpham66** [comment]
That worked fine:

$ newman -c  ./SimpleTests.json.postman_collection
Iteration 1 of 1
Response Code: 200
Response headers: {"Server":"nginx/1.1.19","Date":"Mon, 19 Oct 2015 19:01:48 GMT","Content-Type":"application/json","Content-Length":"159","Connection":"close"}
200 140ms http://dump.getpostman.com/get http://dump.getpostman.com/get
    ✔ Response Status Code is 200
    ✔ Response Body has correct data
Parent                                   Pass Count/Fail Count
---------------------------------------------------------------------
Collection SimpleTests   	         2	         0
Total                    	         2	         0

Here is the content of the file "SimpleTests.json.postman_collection":
{
	"id": "d89ceb44-eacf-bfab-5e13-d2e55647b687",
	"name": "SimpleTests",
	"description": "",
	"order": [
		"04341577-c44a-99b3-32ea-06d53b88c651"
	],
	"folders": [],
	"timestamp": 1445279191898,
	"owner": 0,
	"remoteLink": "",
	"public": false,
	"requests": [
		{
			"id": "04341577-c44a-99b3-32ea-06d53b88c651",
			"headers": "//Authorization: Basic amFtZXMuc21pdGg6eHl6enk=\n",
			"url": "http://dump.getpostman.com/get",
			"preRequestScript": "",
			"pathVariables": {},
			"method": "GET",
			"data": [],
			"dataMode": "params",
			"version": 2,
			"tests": "console.log(\"Response Code: \" + responseCode.code); console.log(\"Response headers: \" + JSON.stringify(responseHeaders));\ntests[\"Response Status Code is 200\"] = responseCode.code === 200;\ntests[\"Response Body has correct data\"] = responseBody.has(\"http://127.0.0.1:8000/get\");",
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1445281244301,
			"name": "http://dump.getpostman.com/get",
			"description": "",
			"collectionId": "d89ceb44-eacf-bfab-5e13-d2e55647b687"
		}
	]
}

**Comment by dpham66** [comment]
I think the issue is with -e. Here is the new result with change in my test to variable the http://dump.getpostman.com

$ newman -c  ./SimpleTests.json.postman_collection_v2 -e ./getpostman_env.json
Iteration 1 of 1
Response Code: 0
Response headers: {}
    EXCEPTION - TypeError: evalmachine.<anonymous>:3
tests["Response Body has correct data"] = responseBody.has("http://127.0.0.1:8
                                                      ^
Cannot read property 'has' of undefined
RequestError: 04341577-c44a-99b3-32ea-06d53b88c651 terminated. Error: ECONNREFUSED
    ✗ Response Status Code is 200

and the content of the file "SimpleTests.json.postman_collection_v2" is these:

{
	"id": "d89ceb44-eacf-bfab-5e13-d2e55647b687",
	"name": "SimpleTests",
	"description": "",
	"order": [
		"04341577-c44a-99b3-32ea-06d53b88c651"
	],
	"folders": [],
	"timestamp": 1445279191898,
	"owner": 0,
	"remoteLink": "",
	"public": false,
	"requests": [
		{
			"id": "04341577-c44a-99b3-32ea-06d53b88c651",
			"headers": "//Authorization: Basic amFtZXMuc21pdGg6eHl6enk=\n",
			"url": "{{getpostman}}/get",
			"preRequestScript": "",
			"pathVariables": {},
			"method": "GET",
			"data": [],
			"dataMode": "params",
			"version": 2,
			"tests": "console.log(\"Response Code: \" + responseCode.code); console.log(\"Response headers: \" + JSON.stringify(responseHeaders));\ntests[\"Response Status Code is 200\"] = responseCode.code === 200;\ntests[\"Response Body has correct data\"] = responseBody.has(\"http://127.0.0.1:8000/get\");",
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1445281557737,
			"name": "http://dump.getpostman.com/get",
			"description": "",
			"collectionId": "d89ceb44-eacf-bfab-5e13-d2e55647b687"
		}
	]
}

For the content of the file "getpostman_env.json"

[
	{
		"getpostman": "http://dump.getpostman.com"
	}
]

**Comment by abhijitkane** [comment]
The environment file doesn't need to be an array. Only data files need to be arrays.

Use 
```
  {
      "getpostman": "http://dump.getpostman.com"
  }
```

**Comment by dpham66** [comment]
Hmm, still same error. Here is the new env file content:

{
	"getpostman": "http://dump.getpostman.com"
}

**Comment by abhijitkane** [comment]
Ah..sorry
The correct format is:
```
{
	"id": "2a6cebe4-bfa3-2aef-016b-e9cab12f3c83",
	"name": "E1",
	"values": [
		{
			"key": "getpostman",
			"value": "http://dump.getpostman.com",
			"type": "text",
			"name": "getpostman",
			"enabled": true
		}
	],
	"timestamp": 1445284222282,
	"synced": false,
	"syncedFilename": ""
}
```
You can get this by exporting an environment file from Postman

**Comment by dpham66** [comment]
It works. Thank you very much.
