### ISSUE TITLE
Access the time of postman "pm.response.responseTime" requests from newman using node.js.

### ISSUE THREAD

**Issue by PauSanch** [postmanlabs/newman#2797]
hello, I need to access the time of postman "pm.response.responseTime" requests from newman using node.js.
In node I have the run.js file in which I run a collection, but I don't know how to access from here the time each collection request is taking, can anyone help me?

```
const newman = require('newman');
newman.run({
  collection: ("./PostmanCollections/CollectionName.json"),
  environment: ("./postmanVariables/A1Env.postman_environment.json"),
  reporters: "cli",
})
```
how do I access the time of the requests to put a console.log(??)

Thanks!

**Comment by DannyDainton** [comment]
Hey @PauSanch,

This should give you the response times for each of the requests:

```javascript
const newman = require('newman');
newman.run({
  collection: ("./PostmanCollections/CollectionName.json"),
  environment: ("./postmanVariables/A1Env.postman_environment.json"),
  reporters: "cli",
}).on('request', (err, args) => {
  console.log(`Response Time for the Request: ${args.response.responseTime}`)
})
```

More about the different `on` events can be found here:

https://github.com/postmanlabs/newman#newmanrunevents

**Comment by PauSanch** [comment]
Eureka! I didn't fall for 'args', it works! thanks a lot for the help!
