### ISSUE TITLE
Support request: equivalent of command-line flag "--disable-unicode" in the options of newman.run()

### ISSUE THREAD

**Issue by EricSt-Amand-opalrt** [postmanlabs/newman#2798]
1. Newman Version (can be found via `newman -v`): **5.2.4**
 2. OS details (type, version, and architecture): **Windows 10 x64**
 3. Are you using Newman as a library, or via the CLI? **as a library**
 3. Did you encounter this recently, or has this bug always been there: **I'm fairly new to newman so I have always had this issue**
 4. Expected behaviour: **I should have the same between `--disable-unicode` and the `options` object passed to `newman.run()` method.**
 5. Command / script used to run Newman: `node myNewmanScript.js`
 6. Sample collection, and auxiliary files (minus the sensitive details): Not relevant

Looking at the newman documentation, it looks like there is actually no equivalent for this option, like there is for `--bail` and `--color`.  Is it possible to have the equivalent of `--disable-unicode` in the options passed to newman.run() ??

**Comment by amar212b** [comment]
Use disableUnicode: true and it will work in Newman.run({ command when using Newman as library

**Comment by erstam** [comment]
I do use `"disableUnicode": "on"` in options and it works fine, thank you.
