### ISSUE TITLE
Error 403 - Forbidden: Client Certificate Required. - Postman call

### ISSUE THREAD

**Issue by Munira-Panjwani** [postmanlabs/newman#2817]
Hi,

Trying to call the api endpoint hosted on azure gives the error of Error 403 - "Forbidden: Client Certificate Required." 
I have uploaded the client certificate that is issued for website which also calls the same endpoint but it didn't work. 
Also, tried with "Enable SSL certificate verification" as OFF

![image](https://user-images.githubusercontent.com/88992466/129497561-e4522a28-b4bf-4062-aed0-3bd711d1cd24.png)

**Comment by shamasis** [comment]
If I am reading this right, you are not sending the client certificate. Newman is the "client" and it should send the certificate as per what the error says. You'd need to configure the same for this API.

Have a look at https://stackoverflow.com/questions/53233044/newman-how-to-send-ssl-cert-in-newman-request

https://en.wikipedia.org/wiki/Client_certificate
