### ISSUE TITLE
Feature Request - Ability to add Tests at folder or collection level

### ISSUE THREAD

**Issue by akapoor47** [postmanlabs/newman#283]
Example - I have a collection with 2 folders
In each folder I have 10 request and for each request under tests I have  

```
["Response time is less than 750ms"] = responseTime < 750;
```

If there is a way to add this test at folder or collection level, it will be much easier to manage if one has to change response time from 750 to a different value. 

If this feature already exist please point me to it.

@abhijitkane

**Comment by abhijitkane** [comment]
Not yet. We're working on a new collection format which will make this use-case much easier to implement, but have no concrete timeline yet.

If all you want to do is change the "750" to something else quickly, I'd suggest using a global variable.

In your test, you can use this - 
```
["Response time is less than "+globals.timeoutTestThreshold+"ms"] = responseTime < parseInt(globals.timeoutTestThreshold);

**Comment by kunagpal** [comment]
This is not a part of our current roadmap, but has been marked as a feature request and added to our internal tracker. We'll update this thread when any progress occurs on this. :)

**Comment by kunagpal** [comment]
@akapoor47 Newman v3.9.0 supports collection and folder level auth and scripts. These can be set within v5.4.1 of the Postman app and above 😄
