### ISSUE TITLE
Newman Data File Option [Question] (Newman 1.2.23)

### ISSUE THREAD

**Issue by Evesy** [postmanlabs/newman#284]
This is a quick question as I'm most likely misusing or misunderstanding the functionality with the '-d' flag to allow multiple iterations of a test with different data in each run. For example if I have basic test such as the below:

    {
        "id": "6096b178-2c22-736f-ffd6-91b560286946",
        "name": "Misc",
        "description": "",
        "order": [
                "7e213da6-0407-b5f8-01ab-ab8a71c1d61f"
        ],
        "folders": [],
        "timestamp": 1445799811035,
        "owner": "75020",
        "remoteLink": "",
        "public": false,
        "requests": [
                {
                        "id": "7e213da6-0407-b5f8-01ab-ab8a71c1d61f",
                        "headers": "",
                        "url": "amazon.co.uk",
                        "pathVariables": {},
                        "preRequestScript": "",
                        "method": "GET",
                        "collectionId": "6096b178-2c22-736f-ffd6-91b560286946",
                        "data": [],
                        "dataMode": "raw",
                        "name": "Amazon",
                        "description": "",
                        "descriptionFormat": "html",
                        "time": 1445799802097,
                        "version": 2,
                        "responses": [],
                        "tests": "tests[\"Response time is less than 5000ms\"] = responseTime < 5000;",
                        "currentHelper": "normal",
                        "helperAttributes": {},
                        "rawModeData": ""
                }
        ]
    }

If I want to run this test to run twice, first against http://amazon.co.uk & then secondly against http://wwwbbc.co.uk I can have a data file such as the below:

    [{
    "url": "http://amazon.co.uk",
    },
    {
    "url": "http://www.bbc.co.uk",
    }]

However if I were now to run the newman command:

    newman -c test.json -d data.json

I would get the below output. The test has simply ran twice against the same URL (the one provided in the original test file):

    Iteration 1 of 2
    200 1522ms Amazon [GET] http://amazon.co.uk
         ✔ Response time is less than 5000ms
    
     Summary:
    
    Parent                          Pass Count       FailCount
    -------------------------------------------------------------
    Collection Misc                          1               0
    
    Total                                    1               0
     
    Iteration 2 of 2
    200 1160ms Amazon [GET] http://amazon.co.uk
         ✔ Response time is less than 5000ms
    
    Summary:
    
    Parent                          Pass Count       FailCount
    -------------------------------------------------------------
    Collection Misc                          1               0
    
    Total                                    1               0

Am I using this feature wrong or is this not working as expected?

Thanks

**Comment by abhijitkane** [comment]
You'll need to change ` "url": "amazon.co.uk",` in your collection file to ` "url": "{{url}}",`

{{url}} refers to the variable (which can be provided through a global variable, an environment variable, or in your case, a data file)
