### ISSUE TITLE
substitute 'intel' package in postman-collection-transformer

### ISSUE THREAD

**Issue by ruowan** [postmanlabs/newman#2848]
Hi, newman team.

Newman is a great libray and very easy to use. But recently our component and governence pipeline detect legal issue when using newman package. 

The license of dependency package 'intel' package is MPL2.0.  Maybe there are some risks here. How about subsitute this `intel` package with others. and this `intel` package has no update since 2017. I think it's a good opportunity to make this change. 

How do you think about this?

Thanks in advance.

https://github.com/postmanlabs/postman-collection-transformer/issues/444

**Comment by codenirvana** [comment]
@ruowan Thanks for bringing this to our attention. We'll update the package and let you know.

**Comment by ruowan** [comment]
Great! Thanks~
