### ISSUE TITLE
Feature Request - include responses in output file

### ISSUE THREAD

**Issue by ihti** [postmanlabs/newman#285]
I use output file to build HTML report and now looking how to include response in my report. I don't see way how to get responses in output file or some other way. Maybe I miss something?

**Comment by czardoz** [comment]
You can  use the output verbose option, ``-O`` or ``--outputFileVerbose``. Since responses can be arbitrtraily large, they're not a part of the regular output file.

**Comment by ihti** [comment]
I know about `--outputFileVerbose` but from that file structure I can't pair certain response with test results.

Would you accept PR if I make changes which will allow to include response body in results, that would be optional and by default off?

**Comment by czardoz** [comment]
Sure, pull requests are always welcome! :)

When you say "by default", does that mean you'll require an extra command line flag to be added?

**Comment by ihti** [comment]
Yes Im thinking about extra command, what you think?

**Comment by czardoz** [comment]
I'm not sure actually.. Yours is a very valid use case, but I also want to avoid adding new flags every time we add some functionality. We could modify the ``--outputFileVerbose`` option to output in a machine readable format, but that'll be a breaking change for people who already use it. What do you think, @abhijitkane?

**Comment by abhijitkane** [comment]
@ihti For the short term, you can use `console.log(responseBody);` in your test script, and pipe Newman's output to a file. Use the `--noColor` flag while running.

@czardoz True..we're already running out of flags. There are already cases where one flag acts as a modifier for another. The outputFileVerbose thing was a pull request, but you're right - don't want to break existing behaviour.

**Comment by ihti** [comment]
@abhijitkane I achieve nothing with that solution.

I run newman as lib with cron and show results in HTML for analyze, if some test case fail it's useful to have response and see where's problem. 

outputFileVerbose is ok but just need machine readable format and reference to request ID, right now it's not much of use.

**Comment by ihti** [comment]
@czardoz @abhijitkane Any conclusion? 
How about introduce sub flags? I think having requests and responses in machine readable format is more important than html or verbose outputs, it's more or less same what we see in console output.

**Comment by kunagpal** [comment]
This is not a part of our current roadmap, but has been marked as a feature request and added to our internal tracker. We'll update this thread when any progress occurs on this. :)

**Comment by bibhuti12** [comment]
@kunagpal  i want a consolidated html reports with the information name of all the collections run and their status once all the collections has run and individual report has been published

**Comment by kunagpal** [comment]
@bibhuti12 I'm not quite sure about what you're looking for, could you create a fresh issue with more details here: https://github.com/postmanlabs/newman/issues/new? Thanks!
