### ISSUE TITLE
APIs run on Postman but not on Newman.

### ISSUE THREAD

**Issue by Navair2** [postmanlabs/newman#2854]
All APIs run on Newman except three, though they all are running on Postman.
![image](https://user-images.githubusercontent.com/92309193/136789201-7a85242b-1170-435b-b86c-afd46f37ecfa.png)

**Comment by malvikach** [comment]
Hi @Navair2 It seems that the 3 requests that are failing are referencing {{orderID}} in the path. Could you check if this variable value is available in the environment you are using while running the Newman command.
Sample newman command to run a collection along with an environment:
newman run my_collection.json -e my_environment.json
Read more about newman [here](https://learning.postman.com/docs/running-collections/using-newman-cli/command-line-integration-with-newman/).

**Comment by malvikach** [comment]
I will be closing this issue, please feel free to re-open it if you are still facing the problem.
