### ISSUE TITLE
Is there a way to delcare Env Vars in CircleCI Accessible by postman collection header? 

### ISSUE THREAD

**Issue by ErikBurdett** [postmanlabs/newman#2865]
Hi, I'm trying to set env variables for a postman/newman orb - I have a secret that needs to be accessed by and applied to the header in my postman collection but I can't find anything on setting the env var in circleci to where it's accessible to the postman collection. Can this be done in circleci or is it just postman? I've watched through https://www.youtube.com/watch?v=DsLa4SSF37o&ab_channel=CircleCI but it doesn't seem to cover setting these env variables in circleci. Right now the postman/newman orb is working but our secretes are contained in the postman collection which is not ideal for security reasons. Any ideas?
Thank you in advance,

**Comment by shamasis** [comment]
Hmm. At first glance it seems doable using combination of environment variables and CLI options / provided you know what exact environment variables are needed.

1. Define environment variable in Circle CI
2. While running Newman pass the environment variables using the `--env-var` options. (You can use globals too. Check CLI documentation of Newman)
3. In request header, use these variables using `{{}}` syntax.
