### ISSUE TITLE
Unable to Set --ignore-redirects

### ISSUE THREAD

**Issue by hvincent4470** [postmanlabs/newman#2876]
I am attempting to run a nodeJS application that calls newman to run some tests, newman v. 5.3.0, on Windows 10.  Inside my index.js script, I have my parameters for the run set out as:

const parametersForOne = {
    collection: path.join(__dirname, 'Sign_In-Change_Password-Smoke_Test.postman_collection.json'), 
	globalVar: [
		{"key": "URL", "value": "XXXXXX"},
		{"key": "State", "value": "XXXXX"},
		{"key": "STAFF_USERNAME", "value": "XXXXXX"},
		{"key": "STAFF_PASSWORD", "value": "XXXX"}
		],
    reporters: 'htmlextra',
    options: '--ignore-redirects'
};

When I execute my code, the test executes, successfully, except for all the tests where I am expecting a redirect to not be followed.  I am sure that I'm just failing to properly set the options parameter, but after, at this point, dozens of tries and looking through the documentation, I'm afraid I am stuck.  Can someone please help me out?

**Comment by DannyDainton** [comment]
When using that option within a script, you would need to use the `ignoreRedirects` flag.

You've added the flag for the CLI usage in your script.

Closing this out for now, if this doesn't address the problem it can be reopened.
