### ISSUE TITLE
ECMAScript 2020 operators not working in newman but working in Postman

### ISSUE THREAD

**Issue by maharshi-me** [postmanlabs/newman#2884]
1. Newman Version (can be found via `newman -v`): 5.3.0
 2. OS details (type, version, and architecture): Mac OS Big sur v11.4
 3. Are you using Newman as a library, or via the CLI? CLI
 4. Postman Version: v9.3.1
 4. Screenshots:
 
<img width="878" alt="Screenshot 2021-12-11 at 2 49 21 AM" src="https://user-images.githubusercontent.com/73870493/145643983-8a380e8c-cb05-4b54-9abe-13b3b1f6e773.png">
<img width="1440" alt="Screenshot 2021-12-11 at 2 48 21 AM" src="https://user-images.githubusercontent.com/73870493/145643988-bcbb3435-fb8f-4d00-9bb8-6f84d91a6c8a.png">

 
Steps to reproduce the problem:

1. Import this collection which contains a test api in Postman `https://www.getpostman.com/collections/7c68dcc0555eb360a29a`
2. Ensure it runs fine in Postman and logs "success" in the console.
3. Run this in terminal `newman run https://www.getpostman.com/collections/7c68dcc0555eb360a29a`
4. At step 3, gives Syntax Error. Doesn't log "success"

If we replace the optional chaining operator (?.) it works fine. I think the error happens with new operators in ECMAScript 2020. But they work fine in Postman

**Comment by shubhbhargav** [comment]
Hey @maharshi-me, can you please let us know the node.js version you are using? newman uses the system's node.js to execute, hence the underlying node.js version needs to be compatible with ECMAScript 2020 operator for newman to work.

**Comment by maharshi-me** [comment]
I am using node v10.24.1. It is not the latest version.

**Comment by shubhbhargav** [comment]
Thanks for the info @maharshi-me. I am able to verify that the corresponding error doesn't show up if we bump up the version to latest ones (17.0.1 for me).

Digging further (ref: https://node.green/#ES2020-features-optional-chaining-operator-----), any node version above v14.5.0 should work. Can you please try bumping up the version and let me know if it works?

**Comment by shubhbhargav** [comment]
@maharshi-me I am closing this issue given the above recommendation. Please feel free to let me know in-case it doesn't work.
