### ISSUE TITLE
Running exported collection from postman fails authentication (OAuth 1.0)

### ISSUE THREAD

**Issue by Fr4ncis** [postmanlabs/newman#289]
https://www.getpostman.com/collections/fc13d501598107a36184

It works fine in postman.
/healthcheck (unauthenticated) works
It seems that /token/generate works (oauth, using consumer key/secret but no oauthtoken/secret)
/token/authorize fails (oauth, using consumer key/secret but NO oauthtoken/secret) 
/offer/getlist.. both fail (oauth, using consumer key/secret AND oauthtoken/secret)

**Comment by Fr4ncis** [comment]
The interesting bit is that /token/generate works (I'll check that it is actually checking the signature!), /token/authorize and /token/authorize always fails instead. Postman with the same environments works.

**Comment by Fr4ncis** [comment]
If it helps I can send you the keys to try it yourselves. Let me know how I can help.

**Comment by Fr4ncis** [comment]
@czardoz anyone can help? it came down to oauth signature being invalid (works fine in postman!)

here is the collection:
```{
	"id": "39dd8929-3589-9c9a-74e6-49e99847ecd7",
	"name": "MAPI v3.x All",
	"description": "",
	"order": [
		"c36de517-efa5-55ec-b556-869750c5b7ad"
	],
	"folders": [],
	"timestamp": 0,
	"owner": "104499",
	"remoteLink": "https://www.getpostman.com/collections/fc13d501598107a36184",
	"public": false,
	"requests": [
		{
			"folder": null,
			"id": "c36de517-efa5-55ec-b556-869750c5b7ad",
			"name": "/token/authorize",
			"dataMode": "urlencoded",
			"data": [
				{
					"key": "token",
					"value": "{{token}}",
					"type": "text",
					"enabled": true
				}
			],
			"rawModeData": "",
			"descriptionFormat": null,
			"description": "",
			"headers": "User-Agent: iPhone OS 8.1, VoucherCodes.co.uk (V3.3.0)\nAuthorization: OAuth oauth_consumer_key=\"38ab9806bdbdb9153e6b607319c18403\",oauth_signature_method=\"HMAC-SHA1\",oauth_timestamp=\"1452012107\",oauth_nonce=\"HOCRk9\",oauth_version=\"1.0\",oauth_signature=\"ynUNcJLjRtU7Y2YyKXviuJZD1RA%3D\"\n",
			"method": "POST",
			"pathVariables": {},
			"url": "http://{{apiServer}}/{{apiVersion}}/token/authorize",
			"preRequestScript": "",
			"tests": "",
			"currentHelper": "oAuth1",
			"helperAttributes": {
				"id": "oAuth1",
				"time": 1452012107000,
				"consumerKey": "{{consumerKey}}",
				"consumerSecret": "{{consumerSecret}}",
				"token": "",
				"tokenSecret": "",
				"signatureMethod": "HMAC-SHA1",
				"timestamp": "1452012107",
				"nonce": "213123132",
				"version": "1.0",
				"realm": "",
				"header": true,
				"auto": true,
				"encodeSignature": false,
				"includeEmpty": false,
				"saveToRequest": true
			},
			"collectionId": "39dd8929-3589-9c9a-74e6-49e99847ecd7"
		}
	]
}```

and the environment file:
```{
	"id": "aed97b0e-e41e-5abe-3066-c8cbd68a2289",
	"name": "MAPI Test v3.4",
	"values": [
		{
			"key": "apiServer",
			"value": "mapi.mapi.test.vc.rmn.io",
			"type": "text",
			"name": "apiServer",
			"enabled": true
		},
		{
			"key": "apiVersion",
			"value": "v3.4",
			"type": "text",
			"name": "apiVersion",
			"enabled": true
		},
		{
			"key": "consumerKey",
			"value": "xxx",
			"type": "text",
			"name": "consumerKey",
			"enabled": true
		},
		{
			"key": "consumerSecret",
			"value": "xxx",
			"type": "text",
			"name": "consumerSecret",
			"enabled": true
		},
		{
			"key": "token",
			"value": "c0bc5cc9facce84ff34c4f3057513f35",
			"type": "text",
			"name": "token",
			"enabled": true
		},
		{
			"key": "oauthToken",
			"value": "1cee36eabd523238b12f3b1232fa16cd",
			"type": "text",
			"name": "oauthToken",
			"enabled": true
		},
		{
			"key": "oauthTokenSecret",
			"value": "badf19d19a8e54dcdbebf37a54bacc9de360e9690056b1dc336c2efccc3ab408",
			"type": "text",
			"name": "oauthTokenSecret",
			"enabled": true
		},
		{
			"key": "randomValue",
			"type": "text",
			"value": "945"
		}
	],
	"timestamp": 1450791891312,
	"synced": false,
	"syncedFilename": ""
}```

I removed the parameters for safety.

**Comment by czardoz** [comment]
@Fr4ncis can you drop a mail to help@getpostman.com with the consumerKey and consumerSecret?

**Comment by contactprad** [comment]
@czardoz  This option is still not working for me with your latest changes.

Below is my request data. please note that there are 3 param passed as data in request body, Oauth header are passed with Authorization

Request headers:
{
 "authorization": "OAuth oauth_consumer_key={{consumerKey}},oauth_signature_method=\"HMAC-SHA1\",oauth_timestamp=\"1458097765\",oauth_nonce=\"IhQt1T\",oauth_version=\"1.0\",oauth_signature=\"Ox7vao73urVUe%2FNsbLxWRG3xHNQ%3D\"",
 "host": "accounts-staging.autodesk.com",
 "accept-encoding": "gzip",
 "content-type": "multipart/form-data; boundary=--------------------------705401656511266169576552",
 "content-length": 436
}
Request data:
{
  "x_auth_username": "{{userName}}",
  "x_auth_password": "{{password}}",
  "x_auth_mode": "client_auth"
}
------------------------------------------------------------
Response headers:
{
 "cache-control": "private",
 "content-type": "text/html; charset=utf-8",
 "server": "Microsoft-IIS/7.5",
 "x-aspnetmvc-version": "5.0",
 "xoauth_problem": "signature_invalid",
 "x-aspnet-version": "4.0.30319",
 "x-powered-by": "ASP.NET",
 "p3p": "CP=\"NON DSP CURa OUR IND UNI\"",
 "content-length": "91",
 "date": "Wed, 16 Mar 2016 03:09:25 GMT",
 "connection": "close",
 "set-cookie": [
  ".ASPXAUTH=; domain=accounts-staging.autodesk.com; expires=Tue, 15-Mar-2016 03:09:25 GMT; path=/; HttpOnly",
  ".ASPXAUTH=; domain=accounts-staging.autodesk.com; expires=Tue, 15-Mar-2016 03:09:25 GMT; path=/; HttpOnly",
  ".ASPXAUTH=CAA091441CAD090EE1326F7FB8BE4536C29306FF9F0D6907BE3B94548A62DA67965F9EC016EF707791301DAB837A31C977D3543BC572798F312DDE6FCEB22F7E91FA503C611923601D5530FE877911C113AA392E7DC4AE738F2471D35618C6FD25FDE5EFC48DDCF74F854702D8F3808EAFCBF7B3CAEDAFFECFFB5F5B4BF44E958B566917; domain=accounts-staging.autodesk.com; path=/; HttpOnly",
  "cl-token=Ty8UVEOYb7dGWIEd0v8ar1YwCspxxQ7nJs1QepoYaOkdwfWcCLgIMQEqNN2gkNmVwsOtcLdjT3DIEydm0FkmBA==; domain=.autodesk.com; path=/; secure",
  "cl-flags=cl-kmsi-enabled:1|cl-token-enabled:1; domain=.autodesk.com; expires=Wed, 30-Mar-2016 03:09:25 GMT; path=/",
  "out=RBJYQCSFLBJ6; expires=Thu, 16-Mar-2017 03:09:25 GMT; path=/"
 ]
}
Response body:
xoauth_problem=signature_invalid&oauth_error_message=Message%20signature%20was%20incorrect.

**Comment by czardoz** [comment]
@contactprad what Newman version are you using?

**Comment by contactprad** [comment]
2.0.5 it is.

**Comment by czardoz** [comment]
@contactprad are you providing an environment to Newman, using the `-e` option? None of the variables in your request have been resolved to their values.

**Comment by tranhungt** [comment]
+1
Can confirm, I'm also having issues with exported collections using OAuth 1, signing with consumer key/secret with no token.
I see the PR with a chained reference here. Hope it works.
https://github.com/postmanlabs/newman/pull/579
