### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by ttyrone** [postmanlabs/newman#2891]
1. Newman Version (can be found via `newman -v`): 5.3.0
 2. OS details (type, version, and architecture): win10 x64
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: 
   i export a collection as episode2.json from postman, the request doing well in postman, then i try to use the episode2.json in newman to write the response to disk, but it's failed with **403 Forbidden** 
 4. Expected behaviour: do not trigger 403 Forbidden
 5. Command / script used to run Newman:
 `
const newman = require('newman'),
      fs = require('fs');
newman.run({
    collection: require('./episode2.json'),
    reporters: 'cli'
}).on('request', function (error, args) {
    if (error) {
        console.error(error);
    }
    else {
        fs.writeFile(`**002.ts**`, args.response.stream, function (error) {
            if (error) { 
                console.error(error); 
            }
        });        
    }
});
`
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):
 postman
![postman](https://user-images.githubusercontent.com/7576557/147063708-0400d04a-2c71-4be6-9a1c-7cddfe20b516.png)

newman
![newman](https://user-images.githubusercontent.com/7576557/147063723-2f525dd3-1734-4008-a835-cbc1353e23a0.png)

**episode2.json and newman.js**
you can import episode2.json to postman
[episode2.zip](https://github.com/postmanlabs/newman/files/7761301/episode2.zip)

pls help me with that, thanks.

**Comment by shubhbhargav** [comment]
@ttyrone I tried reproducing the issue with the steps mentioned but unfortunately I wasn't able to. The `newman.js` worked fine for me and ended up creating the `002.ts` file.

Can you please share more details around the error within the response? I can see some error string in the screenshot but a full error text would be much more helpful here.

**Comment by shubhbhargav** [comment]
@ttyrone I am closing this ticket as of now. Please feel free to let us know if you are still facing the issue. We will re-open the ticket and debug / resolve accordingly.
