### ISSUE TITLE
Docker images have changed architecture, and fail to run

### ISSUE THREAD

**Issue by chrishunter-konsentus** [postmanlabs/newman#2900]
https://hub.docker.com/r/postman/newman/tags

 1. Newman Version (can be found via `newman -v`): 5.3.1
 2. OS details (type, version, and architecture): Alpine AMD64/ARM64
 3. Are you using Newman as a library, or via the CLI? CLI - Docker image
 3. Did you encounter this recently, or has this bug always been there: This started an hour ago
 4. Expected behaviour: Newman to run
 5. Command / script used to run Newman: N/A
 6. Sample collection, and auxiliary files (minus the sensitive details): You can view tags here - https://hub.docker.com/r/postman/newman/tags
 7. Screenshots (if applicable): Please see URL in question 6.

Steps to reproduce the problem:

1. Run Newman Docker on x86/64 hardware
2. Error is produced
  - WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
  - standard_init_linux.go:228: exec user process caused: exec format error

The last release (5.3.0) was built as only AMD64. 5.3.1 which was released 2 hours ago is built as only an ARM64 container.

**Comment by codenirvana** [comment]
@chrishunter-konsentus Thanks for reporting this issue.

This is failed during the last release, we are working on the fix.

**Comment by codenirvana** [comment]
@chrishunter-konsentus Yes, we are planning to support multi-platform Docker images.

Also, can you verify if the issue is fixed now?

**Comment by chrishunter-konsentus** [comment]
@codenirvana I can confirm it working for me now. Thank you for your prompt response!
