### ISSUE TITLE
Test working with postman is failing with newman

### ISSUE THREAD

**Issue by cyrildubus** [postmanlabs/newman#297]
Hi, 

We are willing to use postman and newman to automate our API testing but I encounter a problem with newman that I cannot solve myself.

I'm using postman and newman on two computers with two different environments. 
The test is very basic : it's a POST on an URL with two form-data variables, no https, no auth, nothing weird.

On the first environment, postman and newman are working fine. On the other environment, postman is working and newman is failing with the following error : 

RequestError: [2d0589a7-85d4-a7b5-e3e5-0b870eb2f2a9] 'test request' terminated. Complete error: 
Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)    ✗ [object Object]

We do not manage to have more information since the --outputVerboseFile (or -O) option of newman is not working.

There is almost no difference between the two environments. One is on debian 7 the other is on debian 8 and that's it. The locale is the same, the encoding is the same, everything seems to be identical.

We are totally stuck on this one. We are going to print some debug in our API to see if we can get something from there but since it's working in almost every configuration we think it's more like an encoding problem or routing problem something like that. 

That would be nice to have more information about the error, any way to do so ?

Thank you

**Comment by cyrildubus** [comment]
Okay we found it. 

It was the EventEmitter library that disagree with one of the header transmitted by the webserver of the non working environment.

We force the header to "HTTP/1.1 200 OK" instead of "200 OK".

Postman (and everything else actually) has no problem with just "200 OK" but this lib was a bit more reluctant.

Problem solved

**Comment by czardoz** [comment]
Apologies about the bad error message. We'll fix it with the next release.
