### ISSUE TITLE
Updating environment varibale with each request during collection run as dun in postman app

### ISSUE THREAD

**Issue by rest17** [postmanlabs/newman#2976]
1. Newman Version -5.3.1
 2. OS details (type, version, and architecture): Mac Os Monterey
 3. Are you using Newman as a library, or via the CLI- CLI
 3. Did you encounter this recently, or has this bug always been there: feature request
 4. Expected behaviour: Environment variable in environment json not getting updated with earch for subsequent request.
 5. Command / script used to run Newman:  newman run SonetAPITest.postman_collection.json -e SonetDev.postman_environment.json --folder PolicyBuilderTestSuit -r htmlextra --reporter-htmlextra-export sonet_api_policy_builder_test_report.html --reporter-htmlextra-browserTitle "Sonet Policy Builder API Tests Dasboard" --reporter-htmlextra-title "Sonet Policy Builder API Tests Dasboard" --reporter-htmlextra-titleSize 6
<!--

Create API's collection in postman app .Create environment varibales. Export the collection and environment varibales and run through new this collection. Few test fails because the environment variable doesn't get updated with each request run and failing the subsequent request. 

I understand there is no feature to update the environment json file , but how to do request chaining through newman cli's option to run the collection with each new change.

**Comment by malvikach** [comment]
Related issue: https://github.com/postmanlabs/newman/issues/1679
