### ISSUE TITLE
Can't test using Newman

### ISSUE THREAD

**Issue by MeoBeoI** [postmanlabs/newman#298]
Hi
**PostMan** is really great, but when using **Newman** I have the same issue [here](http://stackoverflow.com/questions/33501908/testing-api-via-newman)
It's Ok when running in PostMan
![Image](http://s9.postimg.org/fr7rbcu0v/Screenshot_2015_11_25_15_39_50.png)

Using Newman.
![image](http://s7.postimg.org/z3on4j2x7/Screenshot_2015_11_25_15_45_21.png)

Can anyone help me with this.
Thank you so much

**Comment by czardoz** [comment]
Are you sure you've updated the collection from the Postman UI? In the collection menu, you'll need to click on "Share" and then "Update".

**Comment by MeoBeoI** [comment]
Thank @czardoz , it works !
I remember I've updated it multiple times before testing, but It works now.

Thank you so much.

**Comment by czardoz** [comment]
Great, glad it worked!
