### ISSUE TITLE
TypeError: Cannot read property '_visited' of null 

### ISSUE THREAD

**Issue by noelcommaj** [postmanlabs/newman#301]
Hello,
When running Newman on a collection file, I receive the above error. I saw that someone else had posted this previously, but resolved their's by recreating their collection. I attempted the same thing without resolution. Below is the output of the error:

TypeError: Cannot read property '_visited' of null at Object.jsface.Class._traverseJson (C:\%appdata%\npm\node_modules\newman\src\utilities\VariableProcessor.js:146:14)

I am working around the issue through a check for null in the _traverseJson funciton, however I wanted to reach out for a cleaner solution?

Thanks,
Jeremy

**Comment by czardoz** [comment]
@noelcommaj this has been fixed in the latest release :)
