### ISSUE TITLE
I am just running sample jenkins job with "date" command written in "Execute Shell" section. After I build the job, its getting successfully build but I can't see output of "date" command in console output. 

### ISSUE THREAD

**Issue by coolkarni-git** [postmanlabs/newman#3015]
1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by DannyDainton** [comment]
Closing this issue due to lack of information.
