### ISSUE TITLE
Newman function meets error in Nodejs 4.2

### ISSUE THREAD

**Issue by codingfishman** [postmanlabs/newman#302]
When run the newman in Nodejs 4.2, I got the error: **'caller' and 'arguments' are restricted function properties and cannot be accessed in this context**, I forgot the filename, but it like to be the `TestResponseHandler.js` which contains: 
```
AbstractResponseHandler._onRequestExecuted.call(this, error, response, body, request, results);
```
I downgrade the Nodejs to 0.10.33 and the issue disappeared.
It seems the Nodejs 4 has integrated new features of ES6 and is in strict mode by default, is this the root cause of my case? :)

**Comment by czardoz** [comment]
You need to install Newman Beta, check the readme for instructions. 

(Excuse the brevity, typing on my phone right now)

**Comment by codingfishman** [comment]
Thanks a lot!:)
