### ISSUE TITLE
newman + Behaviour test script  shows setTimeout is not defined

### ISSUE THREAD

**Issue by yyppaag** [postmanlabs/newman#304]
I'm using newman + http://blog.getpostman.com/2015/09/29/writing-a-behaviour-driven-api-testing-environment-within-postman/.
When I run the newman command to execute tests,  it shows "setTimeout is not defined". Why newman can not recognize setTimeout?

**Comment by czardoz** [comment]
Hi @yyppaag,

This is by design. The Newman sandbox executes tests synchronously, therefore setTimeout is not available in the Newman sandbox.

**Comment by czardoz** [comment]
Oh, and we are working on an Async sandbox too, which will take care of your use-case, but there is no concrete timeline for it yet :)
