### ISSUE TITLE
Global variable rewritten during `newman.run()` ?

### ISSUE THREAD

**Issue by DrakaSAN** [postmanlabs/newman#3042]
1. Newman Version (can be found via `newman -v`): 5.3.2
 2. OS details (type, version, and architecture): Linux
 3. Are you using Newman as a library, or via the CLI? Library
 3. Did you encounter this recently, or has this bug always been there: Appeared recently
 4. Expected behaviour: Calling newman.run multiple times complete without exceptions
 5. Command / script used to run Newman: `newman.run(...)`

For some reasons, we need to instrument tests differently for different folders in a collections, to that end, we have a simple promisification of `newman.run`

This worked well until recently, and I can't target any changes we made to the dependency nor the environment (node v16.14.0 / npm 8.3.1), we started having issues when running `newman.run` two times in the same process:

```sh
$ node test
Running collection 'DDG' ...

/path/to/project/node_modules/newman/lib/run/secure-fs.js:72
    this.isWindows = global.process.platform === 'win32';
                                    ^

TypeError: Cannot read properties of undefined (reading 'platform')
    at new SecureFS (/path/to/project/node_modules/newman/lib/run/secure-fs.js:72:37)
    at /path/to/project/node_modules/newman/lib/run/index.js:179:27
    at /path/to/project/node_modules/newman/lib/run/options.js:394:9
    at wrapper (/path/to/project/node_modules/async/dist/async.js:271:20)
    at /path/to/project/node_modules/async/dist/async.js:3382:19
    at wrapper (/path/to/project/node_modules/async/dist/async.js:271:20)
    at iterateeCallback (/path/to/project/node_modules/async/dist/async.js:427:28)
    at /path/to/project/node_modules/async/dist/async.js:327:20
    at /path/to/project/node_modules/async/dist/async.js:3380:17
    at done (/path/to/project/node_modules/newman/lib/run/options.js:202:17)
    at processCollection (/path/to/project/node_modules/newman/lib/run/options.js:105:9)
    at /path/to/project/node_modules/newman/lib/run/options.js:220:24
    at /path/to/project/node_modules/newman/lib/run/options.js:82:20
    at /path/to/project/node_modules/newman/lib/util.js:222:24
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

When using breakpoints, I can see that for some reason, the `global` variable is replaced by what looks like an internal newman structure (that I guess is the internal representations of postman global variables ?)

![newman-01](https://user-images.githubusercontent.com/5468479/205941287-d9aa806c-e3ae-4438-ae80-555c449cded0.png)
![newman-02](https://user-images.githubusercontent.com/5468479/205941351-6bb10314-cd9f-4b0a-b04f-b2ab24c419ad.png)

Test code and collection: 
[test.zip](https://github.com/postmanlabs/newman/files/10167370/test.zip)

**Comment by dejagerbotha** [comment]
I ran into a similar issue when trying to run collections synchronously. I found a work around, by uncommenting the module "this.isWindows = global.process.platform === 'win32'" in the secure-fs.js file:
![image](https://user-images.githubusercontent.com/65514421/227704526-d5f7cc7e-f8d9-470f-a7b2-886d304bf9ef.png)
Hopefully this solves your issue as well.

**Comment by DrakaSAN** [comment]
Found what line is causing the error, it is not newman itself but `newman-reporter-junitfull` on index.js L58

A better workaround is to not use that reporter until fixed, will see if I can make a PR

**Comment by DrakaSAN** [comment]
Looks like a PR has already been made, but never accepted: https://github.com/martijnvandervlag/newman-reporter-junitfull/pull/1

Looks like newman should take over maintenance of this package, or drop its usage

**Comment by DrakaSAN** [comment]
Since I identified the issue, I created another workaround and published it in npm: https://www.npmjs.com/package/newman-reporter-junitfull-globalfix

Run this reporter along with `junitfull` to fix the issue.

**Comment by dejagerbotha** [comment]
Thank you, appreciate it. Will run it in the morning!
