### ISSUE TITLE
Feature Request - Store results in CSV format

### ISSUE THREAD

**Issue by fluidjeel** [postmanlabs/newman#309]
I would like to see a feature to generate CSV reports on test execution completion. There's a similar feature already provided in SOAP UI. This feature would then help to parse the CSV and either log bug in JIRA, send email etc

**Comment by kunagpal** [comment]
This is not a part of our current roadmap, but has been marked as a feature request and added to our internal tracker. We'll update this thread when any progress occurs on this. :)

**Comment by kunagpal** [comment]
@fluidjeel This can be accomplished by creating and using your own custom Newman reporter: https://github.com/postmanlabs/newman#creating-and-using-custom-reporters

Feel free to get back if you're facing issues. 😄
