### ISSUE TITLE
runtime: could not find a handler for auth: jwt

### ISSUE THREAD

**Issue by strongpauly** [postmanlabs/newman#3100]
1. Newman Version (can be found via `newman -v`): 5.3.2
 2. OS details (type, version, and architecture): Mac OSX
 3. Are you using Newman as a library, or via the CLI?: CLI
 3. Did you encounter this recently, or has this bug always been there: Yes
 4. Expected behaviour: Should work as postman does
 5. Command / script used to run Newman:  `newman run ` ... the collection.json

Steps to reproduce the problem:

1. Create a collection in postman with Authorization type "JWT Bearer" and requests to inherit auth
2. Ensure it works in postman
3. Export collection to json
4. Run in newman

**Comment by imir2580** [comment]
Getting the same on Windows Newman 5.3.2

**Comment by imir2580** [comment]
Geting the same with postman CLI, but works ok with scheduled runs.

**Comment by codenirvana** [comment]
This is fixed in Newman v6.
