### ISSUE TITLE
newman via postman-runtime and localhost doesn't play nice with node 20.1.0

### ISSUE THREAD

**Issue by vgw-chriskruger** [postmanlabs/newman#3104]
Attempts to contact localhost are not resolved. One gets an exception.

```
GET http://localhost:8080/api/collection/0b023ef7-90cd-4d64-b4c4-d8122738b61c [errored]
     Invalid IP address: undefined
```

I have started debugging this myself. It seems to be an interaction between node v20.10 and Newman in the postman-runtime. It works fine under node 18. In fact I believe the problem begins with the PR https://github.com/nodejs/node/pull/44731.

The lookup function within https://github.com/postmanlabs/postman-runtime/blob/8d3d3a870b691583645c696acd5bb7330ce99473/lib/requester/core.js#L303 ends up being called here https://github.com/nodejs/node/blob/24615bd409d148c9ef2d03d6706d0807d5df4557/lib/net.js#L1380 and goes awry around here https://github.com/nodejs/node/blame/24615bd409d148c9ef2d03d6706d0807d5df4557/lib/net.js#L1425 as there is only a string "127.0.0.1" - no object to destructure.

I think it is a newman problem because of the surprising way the lookup function is bound within the postman-runtime.

 1.  Newman 5.3.2 + node v20.1.0
 2. OSX Ventura - Apple Silicon
 3. CLI installed via homebrew 
 3. Recently appeared on my new mac
 4. Expected behaviour - it should resolve localhost to 127.0.0.1 and not throw an exception.
 5. `newman run API.postman-collection.json`

**Comment by sqageek** [comment]
I'm encountering the same problem with the latest Node.js version, but on another machine with an older version (<= 19), there are no issues.

**Comment by codenirvana** [comment]
This is fixed in Newman v6.

**Comment by webdev408** [comment]
Yes!!! the solution to Invalid IP address is 127.0.0.1:port number. I had this issue for about 2 days and found out this. I did not dig into newman for e2e testing but just used 127.0.0.1 and it worked. I have latest version of node.js LTS (20.13.1). Thanks for the comments!!!
