### ISSUE TITLE
in Newman '-O, --outputFileVerbose [file]'  is printing only request headers, it doesnot print request body parameters

### ISSUE THREAD

**Issue by srbangre** [postmanlabs/newman#311]
when i use newman to run my collections, i used -O, --outputFileVerbose [file] comman which is supposed to print request and response in output file. it prints request headers but not the request body parameters.
Here is one report from newman where you can see request data is empty- 
------------------------------------------------------------
Request headers:
{
 "content-type": "application/json",
 "authorization": "Basic YW5kcmGtdFwcF91czpqVsdw97EdhNUVKODR0",
 "host": "localhost:7014",
 "accept-encoding": "gzip",
 "content-length": 164
}
Request data:
{}
------------------------------------------------------------
Response headers:
{
 "date": "Fri, 15 Jan 2016 18:10:46 GMT",
 "content-type": "application/json",
 "content-length": "209",
 "connection": "close"
}
Response body:
{
  "code" : "Error- 001",
  "message" : "Request validation failed. Invalid TestReason found for ServiceTestGroup Random.",
  "requestID" : "9e1a04d7-4f12-4f77-a7c1-a8824dd8c7e7"
}
-------------------------------------------------------------------------------------------
200 525ms Service Test Group = Test Data [POST] http://localhost:7014/test_requests
------------------------------------------------------------

**Comment by srbangre** [comment]
This issue still exists.

**Comment by czardoz** [comment]
@srbangre I'm not able to reproduce this with Newman v2.0.1

What version of newman are you using?

**Comment by srbangre** [comment]
2.0.0-beta.5

**Comment by czardoz** [comment]
It was fixed after that version was released. You'll have to update Newman to get the fix :)

npm install -g newman@2.0.1

**Comment by srbangre** [comment]
yep its working with new version of newman.
thanks :) 
once you close the issue please specify if we need to install new version of Newman. Bcoz unlike postman, newman doesnot  get updated automatically. 
Thanks anyways. new report looks good :)
