### ISSUE TITLE
When attempting patch using a column name of "name", receiving a 500 error that "name" is reserved

### ISSUE THREAD

**Issue by willrichboa** [postmanlabs/newman#312]
"response": { "statusCode": 500, "faultId": "common.error.general", "message": "ClientError - An error occurred (ValidationException) when calling the UpdateItem operation: Invalid UpdateExpression: Attribute name is a reserved keyword; reserved keyword: name" } 

This only occurs on PATCH requests that contain a column name of "name" in the Body of the request.  These requests work in postman and jetpacks, but not in newman.

Using version 2.0.0-beta.1

**Comment by czardoz** [comment]
@willrichboa what do you mean column name? If possible, can you give me a sample collection that reproduces this issue? (If you'd rather not post it publicly, you can mail it to help@getpostman.com)

**Comment by willrichboa** [comment]
Hey thanks for the reply, however this ended up being something internal.  Issue resolved.
