### ISSUE TITLE
clarify usage as library

### ISSUE THREAD

**Issue by deyhle** [postmanlabs/newman#315]
The usage of newman as a library is not very well documented and does not respect common node conventions. Especially the following issues should be described better in the readme or documentation:

* which options are required/optional? Also document undocumented properties (like `html`)
* which options have to be provided as JSON data, which as filepath?
* clarification about usage of JSON5.parse instead of standard JavaScript JSON.parse
* what are the arguments the callback gets called with?
* is the input validated in any way (e.g. using the collection json schema)? What is the error output?

What makes usage especially hard is the lack of error handling. If an error occurs, apparently one of the following happens:

* nothing at all, the callback gets never called and the process idles, or
* the callback gets called with a 1 as error (instead of an Error object and a message)

Also, as a node library it would be useful to drop all the dependencies on files and to just accept JSON input everywhere, as well as producing output in a readable way (instead of having to read out files afterwards that may or may not contain information about occurred errors and successful runs).

**Edit:** also, the callback is obviously called multiple times if errors occur, which practically breaks about everything in node.

**Comment by czardoz** [comment]
Yes, we are aware of issues around using Newman as a Node library. The ample use of singletons, and globals makes it very difficult to use it as a library is especially painful. 

A major rewrite of Newman is in the works to solve these issues, I will probably have more updates in the first week of Feb :)

**Comment by deyhle** [comment]
Well we have February now, any news on the _major rewrite?_ :blush:

**Comment by czardoz** [comment]
@deyhle Yes, apologies for not updating you here. The rewrite is indeed coming along fine, but it does not have any reporting functionality yet, and there are a few inconsistencies between the current Newman and the rewritten one. 

Will keep you updated :-)

**Comment by stiasta** [comment]
What is the progress on the rewrite?

**Comment by czardoz** [comment]
Hi, the rewrite is being worked upon in this branch (https://github.com/postmanlabs/newman/tree/feature/v3), and is quite usable, especially if you want to use it as a Node library. Do give it a shot :)

**Comment by shamasis** [comment]
https://github.com/postmanlabs/newman#api-reference api for library usage of newman v3
