### ISSUE TITLE
Newman Install Errors

### ISSUE THREAD

**Issue by qrobinson** [postmanlabs/newman#316]
Disclaimer: i'm new to filing public bugs, but am a quick study
=
@qubuntu:/opt/node-v5.5.0-linux-x64/bin$ uname -a
Linux qubuntu 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

@qubuntu:/opt/node-v5.5.0-linux-x64/bin$ ./npm install -g newman
/opt/node-v5.5.0-linux-x64/bin/newman -> /opt/node-v5.5.0-linux-x64/lib/node_modules/newman/bin/newman

> contextify@0.1.15 install /opt/node-v5.5.0-linux-x64/lib/node_modules/newman/node_modules/contextify
> node-gyp rebuild

*/opt/node-v5.5.0-linux-x64/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: 3: /opt/node-v5.5.0-linux-x64/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: node: not found*
npm WARN install:contextify@0.1.15 contextify@0.1.15 install: `node-gyp rebuild`
npm WARN install:contextify@0.1.15 spawn ENOENT
/opt/node-v5.5.0-linux-x64/lib
└── (empty)

*npm ERR! code 1*

**Comment by czardoz** [comment]
Since you are using Node v5, please install Newman Beta. 

`npm install newman@beta `

**Comment by qrobinson** [comment]
Build process of newman@beta succeeds but produces a broken symlink in its bin/:
![image](https://cloud.githubusercontent.com/assets/7408749/12519682/3ecde5e8-c10e-11e5-9b3c-ad3ccf7a6049.png)

**Comment by czardoz** [comment]
That's weird. What is your `npm prefix` set to?

Newman doesn't really control where symlinks go, but this is rather annoying..

**Comment by czardoz** [comment]
Oh wait, I just realized. You need to run `npm install -g newman@beta` for the symlink to be added. (Note the "-g").
