### ISSUE TITLE
“--color off” not woking after 6.0.0 upgrade

### ISSUE THREAD

**Issue by mminot-yseop** [postmanlabs/newman#3169]
1. Newman Version: Gone from 5.something to 6.0.0
 2. OS details:
     * Local machine: Xubuntu 20.04, x86_64
     * CI/CD machine: Amazon Linux 2, x86_64
 4. Using Newman via the CLI, `npm install -g newman`.
 3. Encountered this recently.
 5. Expected behaviour: No color when asked, as in v5.
 6. Command / script used to run Newman: Any `newman run` command, even with a dummy collection: `newman run --color off <(echo '{}')`

Today I noticed that part of our CI/CD was broken due to a regex not matching anything. It turned out that our Newman logs were suddenly full of color-related control characters, despite `--color off --disable-unicode` being used:

![CI/CD screenshot](https://github.com/postmanlabs/newman/assets/36635838/4e289c54-b5b4-493b-87b6-f7e2d0f58a1b)

I could reproduce this on my machine: even with `--color off`, the final summary (table + failure list) is colorized:

![Local machine screenshot](https://github.com/postmanlabs/newman/assets/36635838/c1bb479f-55d9-40a7-b683-96fe5ddc0c3e)

I’ve seen old tickets mentioning `--no-color` but it seems that it does not exist (at least in v6) for `run`.

**Comment by luprochazka-cen63872** [comment]
I`ve seen the same behavior in Jenkins console. Could fix the issue please?

**Comment by mminot-yseop** [comment]
> I`ve seen the same behavior in Jenkins console. Could fix the issue please?

On our side, we’re using https://stackoverflow.com/a/18000433 while waiting for a fix.

**Comment by Mapmo** [comment]
Same here, jenkins console output is unreadable.

**Comment by codenirvana** [comment]
This is fixed in Newman v6.1.2.

Thank you @yardenshoham for the fix. 🙌🏻

**Comment by mminot-yseop** [comment]
Thanks. I guess they’re watching the issues even when they’re silent. 😆
