### ISSUE TITLE
Newman -u URL doesn't receive headers from postman collection

### ISSUE THREAD

**Issue by marianosckerl** [postmanlabs/newman#321]
My requests In Postman works perfectly. But i need to add a (Accept: *) header in postman request to work in newman.

Another trouble:

I use newman 1.2.28, when i run newman -u url_collection, headers do not appear.
Only works if i run newman -c exported_collection.json

the request headers in the log (-O user.log) when i send -u url_collection
{
 "host": "xxxxxxx.com",
 "accept-encoding": "gzip",
 "content-type": "multipart/form-data; boundary=--------------------------657341298630810124292013",
 "content-length": 299
}
Response body:
{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Not Acceptable","status":406,"detail":"Cannot honor Accept type specified"}
-------------------------------------------------------------------------------------------

Is it some kind of bug?
Is possible to set the headers from command line?
Thanks. Mariano

**Comment by czardoz** [comment]
Sounds like there's a difference between the downloaded collection and the collection that exists at the URL.

Can you share a sample collection that has this problem?

**Comment by marianosckerl** [comment]
Hi, here paste the json exported from postman:

In postman works perfect. in Newman don't (-u url or -c collection).
{
	"id": "3169771f-96ea-fae8-4067-5da91d880898",
	"name": "prueba",
	"description": "",
	"order": [
		"469ca211-a588-cea1-8e54-241e200c5717"
	],
	"folders": [],
	"timestamp": 1454081438133,
	"owner": "155921",
	"remoteLink": "https://www.getpostman.com/collections/8f547fa9dd0524e9c539",
	"public": false,
	"requests": [
		{
			"id": "469ca211-a588-cea1-8e54-241e200c5717",
			"headers": "",
			"url": "http://local-m.xxxxxx.com/apirest/v6/user_session",
			"preRequestScript": "",
			"pathVariables": {},
			"method": "POST",
			"data": [
				{
					"key": "user",
					"value": "own_mail@patmail.it",
					"type": "text",
					"enabled": true
				},
				{
					"key": "pass",
					"value": "123456789",
					"type": "text",
					"enabled": true
				}
			],
			"dataMode": "params",
			"version": 2,
			"tests": "",
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1454434269981,
			"name": "/user_session",
			"description": "Create the user session:\n\n",
			"collectionId": "3169771f-96ea-fae8-4067-5da91d880898",
			"responses": []
		}
	]
}

Then add the header ---> "headers": "Accept: *",

	"requests": [
		{
			"id": "469ca211-a588-cea1-8e54-241e200c5717",
------>		"headers": "Accept: *\n",
			"url": "http://local-m.xxxxxxxx.com/apirest/v6/user_session",

In postman always works. 
with the new add "headers": "Accept: *", in newman works only (-c collection). With (-u url) don't.

Thanks.
Best Regards. Mariano.

**Comment by czardoz** [comment]
I am not able to reproduce the issue. 

Are you sure you are updating the uploaded collection after adding the header? 
You will need to click on the collection > Share > "Update Link"

**Comment by marianosckerl** [comment]
Hi, I try this and now works!! I'm sure i do this before. Well, my fault! Thanks 4 all. 
Ticket Solved.

**Comment by PVoola** [comment]
how to enable any authentication on these newman calls if company has an additional authentication before making these calls ?

**Comment by shamasis** [comment]
@PVoola - please post in community.getpostman.com
