### ISSUE TITLE
RequestError while using HTTP url in server with SSL in newman v1.2.28 

### ISSUE THREAD

**Issue by jackrabb1t** [postmanlabs/newman#324]
Postman works fine with those calls.

I tried disabling strict ssl. Also tried with the -l option, but no luck.

**Comment by czardoz** [comment]
Can you show the exact error?
Or can you share a collection that can help me reproduce the issue?

**Comment by jackrabb1t** [comment]
I have given the output. The collection hits a server behind a firewall, so is not of much use.

Any other diagnostics I can run?

TIA!

`
➜  postman git:(COM-657-2-RestURLs) newman  -c stb-web.json.postman_collection -e Stage2.postman_environment --tls

Iteration 1 of 1
{}
evalmachine.<anonymous>:1
 an error during JSON.parse(): " + e.message);                throw e;
                                                                    ^
Encountered an error during JSON.parse(): Unexpected token uRequestError: [18169a13-9e65-1232-d1dd-6bfc2d9b611d] '1. List of blogs' terminated. Complete error:
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)
    ✗ Response Code for request is 200
evalmachine.<anonymous>:1
 an error during JSON.parse(): " + e.message);                throw e;
                                                                    ^
Encountered an error during JSON.parse(): Unexpected token uRequestError: [5d4e2ce7-d7bb-8982-b9fe-ff616675cce8] '1.02. List of blogs - paginated tests' terminated. Complete error:
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)
    ✗ Response Code for request is 200

Summary:

Parent                   	Pass Count	 FailCount
-------------------------------------------------------------
Folder content-articles  	         0	         2

Total                    	         0	         2
`

**Comment by czardoz** [comment]
EREFUSED means that Newman was not able to open a connection to your
server, so this is probably the firewall doing something.
Are you able to run it fine without the firewall?

Also, make sure your server is running, and its SSL configuration is
correct.

**Comment by jackrabb1t** [comment]
1) Does Postman do this differently? the Postman call succeeds.

2) I have to work with the sysadmins to check running without the firewall, and also about the SSL. I am assuming SSL is good, because of the other testing going on.

**Comment by czardoz** [comment]
What is the output of running this:

```newman -u https://www.getpostman.com/collections/4144667d1b2a8688d64d```

**Comment by jackrabb1t** [comment]
I have pasted the output below...

``


Iteration 1 of 1
200 575ms https://google.com/ [GET] https://google.com/

Summary:

Parent                   	Pass Count	 FailCount
-------------------------------------------------------------
Collection ssl-connect...	         0	         0

Total                    	         0	         0

``

**Comment by czardoz** [comment]
Well, this SSL url works just fine, so I am guessing it's a server side issue.

**Comment by czardoz** [comment]
@jackrabb1t I'm closing this issue, feel free to reopen if you think Newman is the culprit! :)
