### ISSUE TITLE
Add Nunit Report XML output option

### ISSUE THREAD

**Issue by beatsbears** [postmanlabs/newman#326]
This would be very useful for companies that use test report generators and want to add Newman results to their pretty results dashboards. 

https://github.com/nunit/nunit/wiki/XML-Formats

**Comment by saeliux** [comment]
Already exists. - t is the option you want. Take a look at the readme.md at the command line options available.

**Comment by czardoz** [comment]
@saeliux 's solution is correct.

**Comment by a7ger** [comment]
I'm trying to set newman to report in nunit as well. @saeliux, @czardoz  I looked at the README.md file and see three options that start with "t". All of them are for specifying time settings though. Am I looking at the wrong README.md file? Can you link the correct one that specifies how to use said "-t" flag to format the report to nunit ?

**Comment by gluip** [comment]
Whats the nunit solution? -t Seems pretty irrelant?
