### ISSUE TITLE
Allow formatting test errors in 'tests' object to show them in output (CLI or report)

### ISSUE THREAD

**Issue by igsoblechero** [postmanlabs/newman#327]
Currently, Postman and newman only allow to pass boolean values to the `tests` object, which provides information to know if a test has passed or failed, but nothing about the reason of a failure. For example, it would be very useful to retrieve the error from `tv4.error` when using the JSON schema validator and to save it in a way it was shown as part of the failure (i.e.: inside the failure tag at the XML JUnit report) and not as ordinary output with `console.log`.

**Comment by shamasis** [comment]
newman v3 lays the foundation for this. it would be added soon.

**Comment by kunagpal** [comment]
@igsoblechero: Apologies for the delay, Newman v3.x comes with improved reporting, do go ahead and check it out.
