### ISSUE TITLE
Tests failing where constructor check is used to validate object is String

### ISSUE THREAD

**Issue by arushi26** [postmanlabs/newman#329]
I have added following check for my API
tests["Name has valid value"] = Name !== undefined && Name !== null && Name.trim()  !== "" && Name.constructor === String;

The check is passing in Postman but fails on running through Newman.

As soon as I remove "Name.constructor === String" condition from the check, it passes in Newman.

**Comment by czardoz** [comment]
@arushi26 What version of Node and Newman are you using?

**Comment by arushi26** [comment]
I have the following versions:
Node => v4.3.0
Newman => v2.0.0-beta.7

**Comment by czardoz** [comment]
Okay, I was able to reproduce the issue, and I'll fix it in the next release. Until then, here's a work-around that should do the same thing:

```
tests["Name has valid value"] = Name !== undefined && Name !== null && Name.trim() !== "" && (typeof Name === "string");
```

The `typeof` condition will ensure that your variable is a string.

**Comment by arushi26** [comment]
Thank you
