### ISSUE TITLE
Catch exceptions in tests and mark them as failures?

### ISSUE THREAD

**Issue by davidrudder23** [postmanlabs/newman#330]
Hello!
I'm struggling to properly report test failures.  When tests["whatever"] is set to false, it properly reports the failure.  But, when the test itself gets a failure, such as trying to access an element that doesn't exist, the test throws an exception.  No failures are reported.  So, I might have this json returned:
  {}
And my tests do:
  var data = JSON.parse(responseBody);
  tests["has a child with an id"] = data.child.id && data.child.id != "";

This won't give me a failure because it will throw an exception instead.

In responseHandlers/TestResponseHandler.js, we can add a single line of code.  I'm going to put it here and not in a pull request because I'm not a node programmer and I'm not sure if this is the right way to do it.  But, it works:

        try {
            vm.runInNewContext(testCases, sandbox);
        } catch (err) {
            if (err.toString() === "SyntaxError: Unexpected token u") {
                ErrorHandler.exceptionError("No response from URL");
            }
            else {
                // Add a test to the sandbox which marks this exception as a failure
                sandbox.tests["Exception caught: "+err]=false;
                ErrorHandler.exceptionError(err);
            }
        }

What do you guys think?

**Comment by czardoz** [comment]
Hey @davidrudder23 
A better way to handle this would be to show the stack trace before/after the summary. Adding an extra key to a users tests may not be the best way to handle this :)

**Comment by davidrudder23** [comment]
Hi @czardoz,
Thank you for the response.  My concern is running these from Jenkins. I would like these kinds of errors to be marked in the FailCount column.  Is it possible to do that without adding a new key into the tests?
Thanks,
Dave

**Comment by shamasis** [comment]
The upcoming newman v3 shows stack trace and failures for syntax and script errors! Check it out https://github.com/postmanlabs/newman/tree/feature/v3

**Comment by shamasis** [comment]
Closing since this is fixed in v3.0-beta.1
