### ISSUE TITLE
Include Postman Collection name in xml root element

### ISSUE THREAD

**Issue by jonbr** [postmanlabs/newman#331]
*New feature request*
I would like to run several collections based up on there name, but the xml outputted from Newman does not include the collection name, just it's folders and test cases. This would little feature would be greatly appreciated.

*Is now like this*
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite name="MyTestCase1" id="c122f550-4be6-4451-1e7d-8c1d2ad91cfc" timestamp="2016-02-18T21:00:30.541Z" time="0.00 ms" tests="0" failures="0">
	</testsuite>
```

*Would love to see it more like this*
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Project Name1">
	<testsuite name="MyTestCase1" id="c122f550-4be6-4451-1e7d-8c1d2ad91cfc" timestamp="2016-02-18T21:00:30.541Z" time="0.00 ms" tests="0" failures="0">
	</testsuite>
```

Otherwise keep up the good work, really love your product.

**Comment by czardoz** [comment]
Noted! I'll try to push this in the next release :)

**Comment by jonbr** [comment]
@czardoz Excellent, this feature will help much executing multiply collection in an automated fashion.
