### ISSUE TITLE
Add summary to html report - Feature Request

### ISSUE THREAD

**Issue by MAOliver** [postmanlabs/newman#332]
Just the same style of summary that is available in the text output would be fine.

Example:

> Summary:
>
> | Parent | Pass Count | FailCount |
> | --- | --- | --- |
> | Folder Owner | 164 | 72 |
> | Total | 164 | 72 |

**Comment by shamasis** [comment]
This is WIP in v3. The current html template is crude and by 3.1 (hopefully) we will have a richer HTML

**Comment by kunagpal** [comment]
@MAOliver The HTML template has been improved in Newman `v3.1.0`, do go ahead and try it out.

**Comment by MAOliver** [comment]
@kunagpal very nice. Thanks for the attention.
