### ISSUE TITLE
TypeError: reqData.sort is not a function

### ISSUE THREAD

**Issue by hackintoshrao** [postmanlabs/newman#335]
Newman fails to execute this collection. The screenshot below shows the complete log 

<img width="851" alt="screen shot 2016-02-24 at 7 11 05 pm" src="https://cloud.githubusercontent.com/assets/2609511/13286981/868d23ae-db2a-11e5-9ca8-5f76af52cf58.png">

Here are the fields of the request from the postman collection under scrutiny 
<img width="915" alt="screen shot 2016-02-24 at 7 41 03 pm" src="https://cloud.githubusercontent.com/assets/2609511/13287743/931fcf5a-db2e-11e5-929a-ad278c9e9963.png">

<img width="944" alt="screen shot 2016-02-24 at 7 41 28 pm" src="https://cloud.githubusercontent.com/assets/2609511/13287766/a3ba937c-db2e-11e5-9066-a12cd4bb2195.png">

**Comment by hackintoshrao** [comment]
The error vanishes when the body is changed from xxx-www-form-urlencoded  to form-data , but  the body was anyways empty !

**Comment by harshavardhana** [comment]
For the time being use raw mode and it works @hackintoshrao , Additionally there is also no need to set 'Content-Length'  is handled internally by aws4 library to verify if body is indeed empty. 

But there is a bug in side 

```
_getRequestBody: function (request) {
        var numParams, params, retVal;
        var i;
        if (request.method.toLowerCase() === "post" || request.method.toLowerCase() === "put") {
            if (request.dataMode === "urlencoded") {
                params = this._parseFormParams(request.transformed.data);
                return queryString.stringify(params);
            }
``` 

if the request.transformed.data is empty there is no reason to even go entirely into this function,  one can return quickly and it should work fine. 

For example using dataMode: "params" adds unnecessary body with dummy boundaries

```
   retVal = this._getDummyFormDataBoundary();
                for (i = 0; i < numParams; i++) {
                    if (params[i].type === "text") {
                        retVal += '<br/>Content-Disposition: form-data; name="' + params[i].key + '"<br/><br/>';
                        retVal += params[i].value + "<br/>";
                    }
                    else if (params[i].type === "file") {
                        retVal += "<br/>Content-Disposition: form-data; name=\"" + params[i].key + "\"; filename=";
                        retVal += "\"" + params[i].value.name + "\"<br/>";
                        retVal += "Content-Type: " + params[i].value.type;
                        retVal += "<br/><br/><br/>";
                    }
                }
                retVal += this._getDummyFormDataBoundary();
```

**Comment by czardoz** [comment]
Absolutely :+1:

Thanks for pointing these issues out, will release a fix in the next version :)
