### ISSUE TITLE
running individual test cases using newman command?

### ISSUE THREAD

**Issue by srbangre** [postmanlabs/newman#337]
Can we run individual test cases using newman command?
I know we can run entire collection or folders inside the collection. I need to a way to run individual test cases using newman command. is it possible?

**Comment by srbangre** [comment]
benefit of this is :- integration with test management tools will be super easy.

**Comment by shamasis** [comment]
Use it programmatically now with newman v3 where programmatic usage has now become stable enough to use. Try https://github.com/postmanlabs/newman/tree/feature/v3

In v3, try

```
newman.run({
    collection: {
        item: {
          // ..... pass your single collection JSON here.
        }
    }
}, function (err) {
});
```
