### ISSUE TITLE
Support line feed in csv cell values

### ISSUE THREAD

**Issue by jgroom33** [postmanlabs/newman#339]
The following csv content should be supported:

```
name,address
"Smith, John","123 Main Street
Sometown, AB 0553"
```

The above should be interpreted as:

```
"Smith, John","123 Main Street\nSometown, AB 0553"
```

**Comment by praphull** [comment]
Tried to implement this, but it's a little difficult to figure out CsvHelper, as it is minified.

**Comment by kunagpal** [comment]
@jgroom33 Newman `v3.0.1` includes improved CSV support. Could you try running with CSV content included?

**Comment by shamasis** [comment]
@kunagpal could you try checking if it's fixed now. If yes, we may close this issue.

**Comment by kunagpal** [comment]
@shamasis @praphull @jgroom33 Apologies for the delay, but we have confirmed that line feed content is not presently supported. We'll be adding this issue to our internal tracker, and provide updates here, whenever any progress occurs. Thanks for contributing! :)

**Comment by jgroom33** [comment]
Thanks for the updates. Good effort.

**Comment by czardoz** [comment]
Keeping this issue open in the meantime, just so that everyone knows this is still something that needs to be addressed.

**Comment by shamasis** [comment]
This has been addressed. Quite some time back. Guess we forgot to close this ticket.
