### ISSUE TITLE
Newman Imports Empty Strings from CSV as Null Unlike Postman

### ISSUE THREAD

**Issue by bwolski** [postmanlabs/newman#343]
Hi, my requests sometimes require empty query parameter values, which I am importing from CSV. Postman does not have an issue with importing empty strings from CSV, but Newman sets these values as Null.

That logic is in the CsvHelper, so I just removed it: [Pull Request](https://github.com/postmanlabs/newman/pull/342)

Thanks!
Benjamin

**Comment by czardoz** [comment]
Fixed with 6d817faa2d9632a310230142c7466cc5769f6fb6

**Comment by czardoz** [comment]
Thanks, @bwolski for the PR!
