### ISSUE TITLE
The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by willrichboa** [postmanlabs/newman#345]
Hey I am attempting to execute a POST request that is signed by AWS signature v4.   My POST request is using the header "Content-Type":"application/json".  This works great as long as you don't use a variable in the body of the POST request.  When you attempt to use a variable (environment or data) in the request body the signature calculation fails and I get the error message in the title.  I suspect that the signature might be calculated before the variables are substituted causing the inconsistency.

Could you take a look at this and let me know if you can reproduce this?

**Comment by abhijitkane** [comment]
@willrichboa Thanks for reporting this. We've fixed this in our internal build, and will be rolling out the fix to users over this week.
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/1663

**Comment by czardoz** [comment]
Re-opening this, @abhijitkane this is a Newman issue, not a Postman issue. Will check before closing..

**Comment by JeromeSimmonds** [comment]
Hi guys, just so you know I get the "The request signature we calculated does not match the signature you provided" with version 4.7.2 when I use the DELETE HTTP method.

**Comment by elinbacklund** [comment]
I get `The request signature we calculated does not match the signature you provided.` when I try to use the `Range` and `Start` parameters of the Alexa `TrafficHistory` endpoint.

**Comment by shamasis** [comment]
Hello all, can you report new issues? With more details on the endpoint that’s failing and perhaps with a sample collection to reproduce the issue at our end?
