### ISSUE TITLE
Variable as query parameter works in Postman but not in Newman

### ISSUE THREAD

**Issue by sterfa02** [postmanlabs/newman#346]
I've been attempting to use Newman to run a collection with a single GET request which has one query parameter along with several oauth 1.0 header parameters (at least I've distilled it down to this). Giving the query parameter explicitly (URL Parameter key is start, value is 2016-03-07) works perfectly in both Postman and Newman, BUT when I try to give start using a variable instead (URL Parameter key is start, value is {{date}}, and date is stored as an environment variable with the value 2016-03-07, the response is a 401 error in Newman, but it works perfectly when running in Postman even in Collection Runner, and weirdly the request as printed by Postman AND Newman looks exactly the same (it's filling in the variable with 2016-03-07 properly). So as far as I can tell the only difference is the interpretation of the variable {{date}} in Newman vs Postman.

newman -c Testing.json.postman_collection -e Schoology.postman_environment (I've tried -k and -l to no avail).

https://api.schoology.com/v1/sections/{{courseId}}/attendance?oauth_consumer_key=(key)&oauth_signature_method=HMAC-SHA1&oauth_timestamp=(timestamp)&oauth_nonce=(nonce)&oauth_version=1.0&oauth_signature=(signature)&start={{date}} where of course () indicates actual values I'm not going to post.

**Comment by czardoz** [comment]
@sterfa02, very weird. If possible, can you send a small collection that reproduces this issue to help@getpostman.com

**Comment by sterfa02** [comment]
I have been using a workaround for this, and I'm having trouble reproducing the error, so I'm closing the issue. If it resurfaces, I'll probe the issue some more. Thanks!
