### ISSUE TITLE
EventEmitter memory leak detected

### ISSUE THREAD

**Issue by jeremyrader** [postmanlabs/newman#347]
If I try to call Newman.execute within the callback of another Newman.execute call I get the following error: 
    `(node) warning: possible EventEmitter memory leak detected. 11 requestExecuted listeners added.     Use emitter.setMaxListeners() to increase limit.`

I was hoping to be able to call Newman twice and then compare the results.

```
Newman.execute(collection, optionsBuildA, function() {

    Newman.execute(collection, optionsBuildB, function() {

        //Read in results from build A output file
        //Read in results from build B output file

        //Compare build A results to build B results
    }); 
});
```

I have already posted a question on [SO](http://stackoverflow.com/questions/35855585/compare-results-of-2-different-postman-collection-test-runs-using-newman) related to this issue.

**Comment by czardoz** [comment]
@jeremyrader Newman core is being rewritten, and we hope to have an alpha release out soon.

**Comment by shamasis** [comment]
Newman v3 (beta) should have this fixed. We tested and checked. Can you test in your environment and let us know: https://github.com/postmanlabs/newman/tree/feature/v3

Closing this issue. Reopen if it misbehaves in your environment @jeremyrader.
