### ISSUE TITLE
Feature-Request: Responsetime in JUnit Reports

### ISSUE THREAD

**Issue by roeschjohannes** [postmanlabs/newman#348]
Could you add the responsetime to the JUnit report?
With response times in the reports, its possible to compare different runs of newman in jenkins.

**Comment by shamasis** [comment]
This is on its way in v3. + @czardoz

**Comment by kunagpal** [comment]
Hey @roeschjohannes, the all new JUnit reporter in Newman v3 comes with response times included within the report, do give it a spin with: `newman run collection.json -r junit,cli --reporter-junit-export report.xml`. :)
