### ISSUE TITLE
Different behavior in Newman vs. Postman for empty requests

### ISSUE THREAD

**Issue by DCamillus** [postmanlabs/newman#349]
We have a test collection on my team involving an empty request for a negative test.  We stumbled on what I believe to be a bug in that the test results are different for the same collection against the same URL from the same requesting machine based on whether we use Newman to run the collection, or use Postman Collection Runner to run it.  In Postman, we had the request setup to send an empty request as Text rather than as JSON.  Our API returned a 500 response, presumably because the API only accepts application/json.  Without setting anything differently in Newman, the response was the expected 403 that results from an empty JSON document.

If there's a setting in Newman that would override the collection setup from Postman and send JSON instead of Text, please point me there.  In any case I was surprised by the differing results.

In case it matters, we're new to both tools, so we're using the latest version as of last week (3/9/16) for both.

**Comment by czardoz** [comment]
@DCamillus were you setting a `Content-Type` header?

**Comment by DCamillus** [comment]
In the Postman builder’s body section for the POST, we had chosen “Text” where our positive tests all use “JSON (application/json)”.  Does that answer your question?  We didn’t do anything explicit about the Content-Type header in Newman.  We just saved the collection to a file and ran it with newman –c.

**Comment by RangerDan** [comment]
Does your target server have case-sensitive header parsing (content-type != Content-Type)?  I encountered a difference in the capitalization of headers between Postman and Newman, and it tripped up an older HTTP parser on a mainframe.

**Comment by czardoz** [comment]
Ah, I think I found out the issue. Postman adds a "Content-Type: text/plain" header by default, while Newman does not. 

@DCamillus You can select "text/plain" when creating the collection (which will explicitly add the header for you), until I push out a fix for this :)

**Comment by DCamillus** [comment]
@czardoz That makes sense as a problem that would cause our symptom.  Thanks!

**Comment by shamasis** [comment]
We are on our way to unify the underlying runtime of Postman and Newman. The v3 beta has this implemented. https://github.com/postmanlabs/newman/tree/feature/v3

You should now see unified behaviour in Postman Canary and Newman v3. http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/

**Comment by shamasis** [comment]
Postman Mac app and Newman v3 now has same behaviour
