### ISSUE TITLE
Import as Copy copies existing collection rather than importing from file and appending 'copy'

### ISSUE THREAD

**Issue by RangerDan** [postmanlabs/newman#350]
When I import a collection that has the same name as a collection in my repository, it copies the collection already in Postman rather than using data from the file as I expect.  No data from the file is used.
1) Create a collection and add a request (I used a  GET to http://www.google.com)
2) Export the collection
3) Change the request (I changed to POST)
4) Import the collection
5) Click Import as Copy
6) Collection appears named "...copy"
7) Tests are from existing collection in Postman.  I expected it to use the data from the file.

I'm not using Cloud. Here's my About page: 4.0.2, ( linux / x86-64 ), ( Chrome 49.0.2623.87 )

[TestCollection.txt](https://github.com/postmanlabs/newman/files/172427/TestCollection.txt)

**Comment by abhijitkane** [comment]
@RangerDan Thanks for pointing this out. Not sure how we missed this. Will be pushing a fix for this tomorrow.

**Comment by czardoz** [comment]
@abhijitkane Is this fixed?

**Comment by abhijitkane** [comment]
Yep
@RangerDan Can you confirm this fixed in v4.1.2 of the Chrome app?

**Comment by RangerDan** [comment]
Confirmed as fixed.
- Export collection
- Delete requests wholesale
- Import as Copy or Replace: restores content
- Modify contents in place
- Import as Copy or Replace: restores content
- Do not modify contents
- Import as Copy or Replace: does not adversely affect content.
