### ISSUE TITLE
How to import swagger file to collection with command line? 

### ISSUE THREAD

**Issue by allexeye** [postmanlabs/newman#351]
Is it possible to do that automatically? f/e I updated a URL with swagger.json and I want to run all the tests against the new version of API? Are there any options to do that?

**Comment by abhijitkane** [comment]
@allexeye You'll need to import the updated URL into Postman (there's an import link in the top navigation bar). The will add a collection in your app, which you can then run in the Runner.

**Comment by allexeye** [comment]
@abhijitkane yes, but I want to do it automatically via command line. 
I need something like:
`newman convert -u http://www.myapi.com/swagger.json > postman_collection.json`
and then 
`newman -c postman_collection.json`

**Comment by czardoz** [comment]
@allexeye We use this library for our imports:
https://github.com/postmanlabs/swagger2-to-postman

It should be easy to write a small CLI to convert a file from Swagger to a Collection. Check out the tests for an example use: https://github.com/postmanlabs/swagger2-to-postman/blob/b28db9cf42a95456a658e40046ffa88bd5db4b75/test/converter-spec.js

We don't really plan on adding this functionality to Newman anytime soon :)

**Comment by allexeye** [comment]
@czardoz ok, thanks for the links :+1:
