### ISSUE TITLE
Issue with AWS signature using variables in the signature

### ISSUE THREAD

**Issue by willrichboa** [postmanlabs/newman#353]
More AWS signature issues.

This works in postman.  Set up a get request that has an AWS signature.  Use environment variables in the "Access Key" and "Secret Key" columns.  The values are replaced and the Get request works.

If you then download the collection and environment file and run them in newman the authorization header that is calculated has the "Credential" value as undefined and the request fails.

Example authorization header from using -O in newman.
"authorization": "AWS4-HMAC-SHA256 Credential=undefined/20160315/us-east-1/execute-api/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-security-token;SomeHeader;SomeOtherHeader, Signature=SomeHashKeySignatureValue",

**Comment by czardoz** [comment]
Are you setting "Save Params to Request" in the AWS Auth helper?

**Comment by willrichboa** [comment]
Yeah I have "saveToRequest": true in the collection.

Newman
2.0.2
Postman
4.0.4
( win / x86-32 )
( Chrome 49.0.2623.87 )

**Comment by willrichboa** [comment]
I think I might have figured this out.  I noticed that some of the other requests had a slightly different format for their AWS helperattributes.

"currentHelper": "awsSigV4",
			"helperAttributes": {
				"accessKey": "{{aws-access-key}}",
				"secretKey": "{{aws-secret-key}}",
				"awsRegion": "{{aws-region}}",
				"serviceName": "{{aws-service}}",
				"saveToRequest": true
			},
instead of the format I posted in the previous comment.

Seems to be a legacy from a previous version of postman.

**Comment by czardoz** [comment]
That's not normal. Is this from Postman v4.0.4?

**Comment by willrichboa** [comment]
Doesn't appear to be happening when saving in 4.0.4.  I've cleaned up the collection to use the correct format, and I don't see it any of my other collections either.  Not sure what might have caused it, but it doesn't appear to be occurring any more.  If you can't reproduce this on your end may as well close this issue.

**Comment by czardoz** [comment]
Yes, it seems to be an issue in an older version of Postman. 
It's definitely been fixed in newer versions, but do reopen the issue if you face it again :)

**Comment by YoshihisaHachiro** [comment]
検証がなかなか始まらないようなの個人環境で試験をはじめました。
IAMの場合、Dateもヘッダーに設定が必要なようで、最終試験まで行っていませんが、設定内容について共有します。






####Cognito
ユーザプールの作成

|ユーザプール名|用途|プールID|プールARN|アプリクライアント名|アプリクライアントID|
| ---- | ---- | ---- | ---- | ---- | ---- |
|userPoolA|LINE会員を想定し、email属性を必須としない|us-east-1_d0obUAHha|arn:aws:cognito-idp:us-east-1:829493565365:userpool/us-east-1_d0obUAHha|userPoolA-App|6lh00s2ku1s3cqkubtocgfte80|
|userPoolB|Web会員を想定し、email属性を必須とする|us-east-1_IuOSq82GL|arn:aws:cognito-idp:us-east-1:829493565365:userpool/us-east-1_IuOSq82GL|userPoolB-App|6iovp98utul0m19aai82bnv99b|
|userPoolC|指定Poolでのみ呼出可能であることを確認するためのPool|us-east-1_LIlngVYzy|arn:aws:cognito-idp:us-east-1:829493565365:userpool/us-east-1_LIlngVYzy|userPoolC-App|7hq67a9ka8opf72mh9j2j0esga|

ユーザの登録

|ユーザプール名|ID|パスワード|備考|
| ---- | ---- | ---- | ---- |
|userPoolA|usera|multitesta||
|userPoolB|yhachiro@gmmail.com|multitestb|userpoolの作成時にemailアドレスをログインIDにするとしているため|
|userPoolC|userc|multitestc||

認証トークンがそれぞれ取得できたかJSで確認
```
hacbook:ssosample hac$ node testauth.js
eyJraWQiOiJUOUdPSThsQWk4Ylc3UEF0bGVCQVhxVllMVHpmVG02NDJcL1RZa2pvSmhFST0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI2NzllZjQxYS1jODg2LTRlMTItYmU3OS1iMGZmOTM0MzRmNjciLCJhdWQiOiI2bGgwMHMya3UxczNjcWt1YnRvY2dmdGU4MCIsImV2ZW50X2lkIjoiY2Q4ZDQ1NTItN2E2NC00NGEwLWI5NzgtZjA1YzY5NDgxYTQ1IiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE1NzQyMTY4MTAsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX2Qwb2JVQUhoYSIsImNvZ25pdG86dXNlcm5hbWUiOiJ1c2VyYSIsImV4cCI6MTU3NDIyMDQxMCwiaWF0IjoxNTc0MjE2ODEwfQ.cZR6DQerCDGDPp6nvSaKJdCOOCw9J46Os166XY2Av4kniuP2XRrWm-THheLcyNna3aQdOj195gu1AZW6B1vvHsFPe4f7r_YlYZYddeeV1oTeI8fvctaIkLspzdoJ0k6Y6UD5F5_DgJT5ntkAbb-L3iiql8WXAMit5p1bToiFxeSnzQ2-BrCFRP-jBIjFqByb4RAeafcvF0GIyJruX_gFW-VMV4hfXHeyHK8Ov-ZDRASXp5lIllGsY8-k1i0hO2RO1gC_rbPtSAuVezpWAT3rMsZermxWt7xkAt7hPbCiZnwn4W8ymwXHhlzkh-fFh6NfxcKEvRn3M6T_Abvf9YmobQ
{
  sub: '679ef41a-c886-4e12-be79-b0ff93434f67',
  aud: '6lh00s2ku1s3cqkubtocgfte80',
  event_id: 'cd8d4552-7a64-44a0-b978-f05c69481a45',
  token_use: 'id',
  auth_time: 1574216810,
  iss: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_d0obUAHha',
  'cognito:username': 'usera',
  exp: 1574220410,
  iat: 1574216810
}
```
```
hacbook:ssosample hac$ node testauth.js
eyJraWQiOiI0MVwvWjZqREZzeHZ6dDFGb2k4QnBaZU1GYjJBYjVLNGl1ZjZ4WWdqTkpLST0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJiNThlMzY0OS05ZDVlLTQ2NmYtYTQ4Ni05N2I2MmU2NGJkOTUiLCJhdWQiOiI2aW92cDk4dXR1bDBtMTlhYWk4MmJudjk5YiIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJldmVudF9pZCI6IjA2YTg4ZTRiLTZkZjQtNDc2MC1iNTQ4LWQ3Y2FkMWJhNTFhMiIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNTc0MjE3MjEzLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9JdU9TcTgyR0wiLCJjb2duaXRvOnVzZXJuYW1lIjoiYjU4ZTM2NDktOWQ1ZS00NjZmLWE0ODYtOTdiNjJlNjRiZDk1IiwiZXhwIjoxNTc0MjIwODEzLCJpYXQiOjE1NzQyMTcyMTMsImVtYWlsIjoieWhhY2hpcm9AZ21haWwuY29tIn0.O2q57SzFATwujWycxTV7oAIwp45yWPmGaTfLB_AGTPoF-D4XRcrvMCYC-G-_bCDp2q0gQSyIdvZ3MhOJC3Zm6WuhWykFeRwgtmrA6XG3AumWGVpqcfoUV7hD8behxISr4BqhFUsT57_rIF0kBuFmAjmwgu_8Isgx5YfUzPzCeDXaxSwxmhs7TbTAys90fmObG0dguJgM8oXXp9TJMLAdQdWxg7j_Xx1tdlFHzH03Lz3zOeGcKiPBudXLC9wB00ukx-ZW59mtG_v8mI-GrrWSsFpW-fBPdW4rCvCAHr8jIWj-RXufUkdO54xPS4u_gB2OleLbgAHn05gemj0e0nbQZQ
{
  sub: 'b58e3649-9d5e-466f-a486-97b62e64bd95',
  aud: '6iovp98utul0m19aai82bnv99b',
  email_verified: true,
  event_id: '06a88e4b-6df4-4760-b548-d7cad1ba51a2',
  token_use: 'id',
  auth_time: 1574217213,
  iss: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_IuOSq82GL',
  'cognito:username': 'b58e3649-9d5e-466f-a486-97b62e64bd95',
  exp: 1574220813,
  iat: 1574217213,
  email: 'yhachiro@gmail.com'
}
```
```
hacbook:ssosample hac$ node testauth.js
eyJraWQiOiJ6SzZYeFFzcEtYamRhaW5LV2JERmRoRzBRNDg1ZkxuampJTjhxZUVKdXVBPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIzNWY5ZDEwZC1kMDVkLTRjZjAtYjFhNi05NWE3MjkzNGZmZjkiLCJhdWQiOiI3aHE2N2E5a2E4b3BmNzJtaDlqMmowZXNnYSIsImV2ZW50X2lkIjoiMDcyZGU3YjUtYjJlYS00M2YyLTlkZTItZjZjNGViN2JhMGIyIiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE1NzQyMTczNzcsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX0xJbG5nVll6eSIsImNvZ25pdG86dXNlcm5hbWUiOiJ1c2VyYyIsImV4cCI6MTU3NDIyMDk3NywiaWF0IjoxNTc0MjE3Mzc3fQ.uv37utQzoQAlDaLqQzDbH_nkV-4JxzjVjVQhz1gV7Z567pkZ7NS1swTA1XAEsgeX_uzRxVU0WVHV5LeF_G4Tc-X_WvJ6XGsPVCD_6sapRwsfi1sblrtWQA6LeCQHoIezew7hnDHb6bts05vvJDPdXntTfIxdkmGV6su3TWtBSmslDeUXrfL3KJKfEkewF0xpoSyRBHfI9Lv5SGaLVtjfjMwRkF_KoKTUNTTmYqI7ZJ8ASUIxJanfgRN7r6r6kxvJR3i9TqHAaZZbzZRcP1txWr87l5cbr4eHw3ar2vWKyXS9rkSTKMS3W36YpY5gCtiIhwla2RLgfpwQg_HPKFOtBA
{
  sub: '35f9d10d-d05d-4cf0-b1a6-95a72934fff9',
  aud: '7hq67a9ka8opf72mh9j2j0esga',
  event_id: '072de7b5-b2ea-43f2-9de2-f6c4eb7ba0b2',
  token_use: 'id',
  auth_time: 1574217377,
  iss: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_LIlngVYzy',
  'cognito:username': 'userc',
  exp: 1574220977,
  iat: 1574217377
}
```

#### API Gateway
デフォルトで作成できるPetStoreで作成
arn:aws:execute-api:us-east-1:829493565365:atafvt1ug2/*/GET/pets
ステージ：hactest にデプロイ
呼出URL：  https://atafvt1ug2.execute-api.us-east-1.amazonaws.com/hactest

リソースの'/GET'に認可設定を追加する。
認可はAWS_IAMを選択する
！チェックをクリックするのを忘れずに

#### Cognito Identity Pool
CognitoのIdentity Poolを作成する
IDプール名: mtest
IDプールのID:us-east-1:1a631117-3dbb-4ccd-998d-1020c9126578
IDプールのARN:arn:aws:cognito-identity:us-east-1:829493565365:identitypool/us-east-1:1a631117-3dbb-4ccd-998d-1020c91
認証されていないIDに対してのアクセスを有効にするのチェックは入れない
基本（クラッシック）フローを許可するのチェックを入れない
認証プロバイダでUserPoolAとUserPoolBのユーザプールID、アプリクライアントIDをそれぞれ登録する
次にIAMロールの作成画面が出るので、詳細を表示させポリシードキュメントを表示させる。
ロール名"Cognito_mtestAuth_Role"
アクセスさせたいのではAPI Gateway作成時のARNなのでResourceの指定を"*"から"ARNの内容"に変更する
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "execute-api:Invoke"
      ],
      "Resource": [
        "arn:aws:execute-api:us-east-1:829493565365:atafvt1ug2/*/GET/"
      ]
    }
  ]
}
```

アクセス制限の検証
GET以降がアクセス制限がかかっている。
https://atafvt1ug2.execute-api.us-east-1.amazonaws.com/hactest
これはアクセス成功する。

https://atafvt1ug2.execute-api.us-east-1.amazonaws.com/hactest/GET
アクセスは失敗し以下のメッセージを取得する
```{"message":"Missing Authentication Token"}```
