### ISSUE TITLE
Newman Cloud

### ISSUE THREAD

**Issue by aaronweatherall** [postmanlabs/newman#354]
Hey Team,

With your new cloud service we *really* want to run newman against our cloud based collections for CI/CD.

I know that as an individual user I can share a URL then use the -u parameter to run against that remote colllection. The problem is that this link is associated with my account, not the team and it';s not auto-updated.

What's the timeline on this?

**Comment by sobtiankit** [comment]
@aaronweatherall A few weeks actually! I'll keep you posted.

**Comment by aaronweatherall** [comment]
Perfect!

**Comment by shamasis** [comment]
You can now use our Cloud API service to use synchronised collections and share using an API Key. https://api.getpostman.com/
