### ISSUE TITLE
JUnit (XML) detail on failure #278

### ISSUE THREAD

**Issue by roeschjohannes** [postmanlabs/newman#355]
Could you please merge the pull request [278](https://github.com/postmanlabs/newman/pull/278)? This feature would be very helpful.

**Comment by czardoz** [comment]
@roeschjohannes I'm working on a different way of showing errors.. adding a new test does not seem right. I'll update this issue :+1:

**Comment by anyone-can-test** [comment]
I like this feature.

**Comment by shamasis** [comment]
The v3 of newman should be the target for achieving this. Maybe more details can be posted in this issue as a requirement and then we can work together on the new branch

https://github.com/postmanlabs/newman/tree/feature/v3

**Comment by kunagpal** [comment]
Apologies for the delay, Newman v3 provides a shiny new JUnit reporter, do go ahead and try it out. :)
