### ISSUE TITLE
how to install newman behind corporate proxy (with command npm install -g newman@beta)

### ISSUE THREAD

**Issue by DaisySu** [postmanlabs/newman#357]
32 error Windows_NT 
33 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "newman@beta"
34 error node v5.9.0
35 error npm  v3.7.3
36 error code ETIMEDOUT
37 error errno ETIMEDOUT
38 error syscall connect
39 error network connect ETIMEDOUT 
40 error network This is most likely not a problem with npm itself
40 error network and is related to network connectivity.
40 error network In most cases you are behind a proxy or have bad network settings.
40 error network
40 error network If you are behind a proxy, please make sure that the
40 error network 'proxy' config is set properly.  See: 'npm help config'
41 verbose exit [ 1, true ]

**Comment by DaisySu** [comment]
Type with the command:
npm --proxy http://myusername:mypassword@proxy.us.somecompany:8080 \
--without-ssl --insecure -g install
See http://stackoverflow.com/questions/7559648/is-there-a-way-to-make-npm-install-the-command-to-work-behind-proxy

**Comment by czardoz** [comment]
Hi @DaisySu, Newman stable now supports Node v4+, so you can drop the '@beta' tag during installation :)
