### ISSUE TITLE
How to include the common collection while run a scenario case in postman and newman

### ISSUE THREAD

**Issue by DaisySu** [postmanlabs/newman#358]
For tester, some case, like login/logout cases are frequently used before/after business scenario. I want to extract them to one common file,  instead of importing them to each collection, to avoid maintain each case once some common change. How to reach this target in postman and newman?

**Comment by czardoz** [comment]
There's currently no way to have a "common" subfolder. One workaround is to create your own collection, but that is a bit of work :)

**Comment by shamasis** [comment]
The programmatic use can make it super easy in newman v3.
Maybe we could create a sample JS file elaborating this. @czardoz :-P

Also, supporting multiple collections through CLI? ;-)

**Comment by kunagpal** [comment]
@DaisySu On a related note, newman v3.9.0 supports collection and folder level auth and scripts. These can be set within v5.4.1 of the Postman app and above 😄

**Comment by shamasis** [comment]
It's been a while. I still think the best way to do this is to use a simple script to extract relevant info and passing it to newman.

**Comment by huguesbr** [comment]
@DaisySu

Hey. I’ve build NewmanScenario just for this!

https://github.com/huguesbr/newman_scenario

It basically allow you to create on the fly scenario by cherry picking requests ( and store this list into a file ) and chain play them.
