### ISSUE TITLE
When using AWS signature PATCH requests fail.  

### ISSUE THREAD

**Issue by willrichboa** [postmanlabs/newman#360]
Take a look at https://github.com/postmanlabs/newman/blob/develop/src/utilities/HelperProcessor.js

Line 51 in _useAWSSigV4Auth  is  var body = this._getRequestBody(request);

Within _getRequestBody line 322 is  if (request.method.toLowerCase() === "post" || request.method.toLowerCase() === "put") {

PATCH also requires a request body so should be included in this if. 

PATCH with AWS signature works in POSTMAN but not newman v 2.0.3

**Comment by czardoz** [comment]
Thanks, @willrichboa for reporting this :smiley: 

Fixed this in v2.0.4
