### ISSUE TITLE
feature request - test description needs formatting in html report option

### ISSUE THREAD

**Issue by srbangre** [postmanlabs/newman#361]
Hi,
I have following as my test description in the postman tool - 
Test ID: TC_MemberDetails_01 

Test Objective: Test to verify if Get Member web service is returning all the Member Details like Name, Address, Email ID

Test Expected Result: web service returning all Member Details 

Pre-conditions: Auth token request should be submitted before executing this test case 

Data: 
1. User = XXXX  
2. Auth Token generated from Auth web service in request header

when newman generates the html report, it prints all the test description in one single line like - 
Test ID: TC_MemberDetails_01 Test Objective: Test to verify if Get Member web service is returning all the Member Details like Name, Address, Email ID Test Expected Result: web service returning all Member Details Pre-conditions: Auth token request should be submitted before executing this test case Data: 1. User = XXXX  2. Auth Token generated from Auth web service in request header

Can you please let me know how can i have this in better readable format? at least in separate rows

**Comment by czardoz** [comment]
@srbangre I've fixed the issue, it will be available in the next release

**Comment by srbangre** [comment]
@czardoz can you also see if test run summary can also be at the end of the report? just like the one displayed in the newman. 
and if you can then is it possible to tell in the summary that no of test cases failed/passed instead of numbers of assertions?

**Comment by czardoz** [comment]
The summary is best kept at the top of the report, which is generally the norm.

Also, if you'd like to do more processing around test results, check out the "-t" option, which outputs the results in an easy to use XML format. You'll be able to process the file using any XML parsing library :smiley:

**Comment by czardoz** [comment]
@srbangre This has been released in Newman v2.0.5. You'll need to update newman to get this fix :)
