### ISSUE TITLE
tests results pass in postman but fail in newman

### ISSUE THREAD

**Issue by wkuckro** [postmanlabs/newman#367]
Using the exact same environment , a test that passes when run in postman doesn't pass when run in Jenkins. 

```
var responseJSON1 = JSON.parse(responseBody); 
tests["Survey number is as created"] = responseJSON1.Survey.SurveyNumber.toString() === postman.getEnvironmentVariable("SurveyNumber");
```

Is there anything about this that wouldn't work properly in newman

**Comment by abhijitkane** [comment]
@wkuckro Can you include the raw response body from Postman here?

**Comment by wkuckro** [comment]
{
  "ApiMessages": [
    "API Message: Response initialized.",
    "API Message: UpdateSurveyFromModel successful."
  ],
  "ResultCount": 1,
  "Survey": {
    "AccountID": 1,
    "SurveyStatusCode": "06",
    "SurveyPriority": 11,
    "SurveyNumber": 121615,
  }
}

I had to truncate it for business purposes

**Comment by mstaalesen** [comment]
Try console.log to see if there is a differense in response in postman and newman.

console.log("Comparing: " + responseJSON1.Survey.SurveyNumber.toString() + " with: " + postman.getEnvironmentVariable("SurveyNumber"));

Or, instead of doing toString() on the response, you can do:
tests["Survey number is as created"] = responseJSON1.Survey.SurveyNumber === parseInt(postman.getEnvironmentVariable("SurveyNumber"));

**Comment by wkuckro** [comment]
I changed to ParseInt( ) and that solved the issue. thanks

**Comment by czardoz** [comment]
Thanks, @mstaalesen! 

Keeping this issue open until I resolve the discrepancy :)

**Comment by kanishka84** [comment]
I am facing similar problem.
tests["Status code is 500"] = responseCode.code === 500;
tests["Body matches string"] = responseBody.has("conflict: Document update conflict.");

these tests passes in Postman but fails in Newman

**Comment by czardoz** [comment]
@kanishka84 could you open a new issue with more details? I'm specifically looking for:
1. Does Newman show any error message?
2. Does your request use any specific content type?
3. Is it an HTTPS request?
Thanks!

**Comment by kanishka84** [comment]
@czardoz 
I introduced delay while running the tests in newman. Initially the test's started passing but they fail time to time. I do not believe using using delay is a good solution and i am still looking for a better solution. For your answers
1. Does Newman show any error message?
- No it shows no error, only the tests fail.
2. Does your request use any specific content type?
- Content type for this is application/json; charset=utf-8
3. Is it an HTTPS request?
- No its is a HTTP request.

I am opening a new issue
https://github.com/postmanlabs/newman/issues/398

**Comment by shamasis** [comment]
Can you try this in latest Newman v3 and let us know? Newman v3 and Postman native apps will have the same behaviour.

**Comment by wkuckro** [comment]
not experiencing in newman 3.0.1

**Comment by cesarsousa** [comment]
how to force newman recognize postman variable? ex. my URL uses variable like {{ur}}/blablabla. when i run the tests using newman the test brokes...
how to solve this issue?

**Comment by kunagpal** [comment]
@cesarsousa Let's discuss this on a separate thread, could you create a separate issue with more details here: https://github.com/postmanlabs/newman/issues/new? :smile:

**Comment by cesarsousa** [comment]
Kunagpal thanks for reply, the answer  to my question was use the argument '-e' on my command:

newman run myCollections.json -e myEnvironment.json

**Comment by JessiAlvarez** [comment]
Hello, i´m very new using postman and newman. This is my problem:
tests["Status code is 500"] = responseCode.code.toString() === "500";
tests["Body matches string"] = responseBody.has("User error!")
These tests passes in Postman but fails in Newman

Newman version 3.5.2
No specific content type
HTTP request

**Comment by AcidZeppelin** [comment]
can you share the newman part of the script or command?

**Comment by JessiAlvarez** [comment]
Command to execute the collection:
newman run "WS Dummy.postman_collection.json"

**Comment by AcidZeppelin** [comment]
Please include delayRequest and try once.

**Comment by sujaykundu777** [comment]
I am facing error while handling POST requests using newman v.4.6.1, apparently it works well in postman, but the tests fail in newman when i try to run the collection.json with application/json as content-type as "application/json" 

Gives this error, in express app : 
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```

**Comment by jwhitmarsh** [comment]
@sujaykundu777 I have exactly the same issue - did you ever solve this?
