### ISSUE TITLE
Execute multiple queries simultaneously from multiple threads

### ISSUE THREAD

**Issue by KumG** [postmanlabs/newman#369]
An important kind of type of test for our application is to have simultaneous calls to the same method from multiple threads, to test the concurrency and the data integrity.

Is there a way to reproduce this kind of tests with Postman/Newman, or is it planned ? Otherwise, what do you think about this kind of tests, should I use another tool ?

Thanks

**Comment by czardoz** [comment]
Hi @KumG 

You can run multiple Newman processes to achieve this scenario. While it would probably not be a part of Newman CLI, we'll soon be releasing a library that should allow you to write your own Node programs which concurrently run multiple Newman runs.
