### ISSUE TITLE
Random node request.js timeout when building request

### ISSUE THREAD

**Issue by willrichboa** [postmanlabs/newman#372]
I am getting random timeout errors using newman 2.0.5.  The errors occur occur before the request is sent, and the below stack trace is generated.

The errors are occurring on requests that have passed previous iterations in the same run sometimes. This has happened for all methods, Put, Patch, Del, Get, Post. AWS signatures are included in all requests, as well as parameterized headers and json bodies.

I saw some other issue reported with a similar error about content length headers, but this issue is random and these requests work most of the time.  So they seem to be unrelated.

The requests all look something like this:  (-E and -n may not be on each request)
newman -j -y 2000 -r 20000 -c filepath/collection.json.postman_collection -f folder -e filepath/env.postman_environment -O output.txt -t junit.xml -H html.html -n 1 -E filepath/env.postman_environment 

The message in the console is always something like:

[39m[31mRequestError: [7c94ae4e-2820-0d92-29a2-b4b62c08b7a5] 'Request Name' terminated. Complete error: 
[39m[31mError: ETIMEDOUT
    at null._onTimeout (/scratch/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Newman_install/lib/node_modules/newman/node_modules/request/request.js:808:15)
    at Timer.listOnTimeout (timers.js:92:15)[39m[31m
[39m[31m    ✗ Status code is 200 + responseBody: undefined
[39m[38;5;33m[4m

Junit XML file written to: /filepath/junit.xml
[24m[39m[38;5;33m[4m
HTML Report written to: html.html

**Comment by czardoz** [comment]
Newman has no control over timeouts. They are raised by the internal "request" library which Newman depends upon. 

Could these be intermittent network level issues?

**Comment by kunagpal** [comment]
Hey @willrichboa, do these issues still persist for you?

**Comment by kunagpal** [comment]
Closing issue on our end due to inactivity. Do let us know if this issue still persists. :)
