### ISSUE TITLE
Random HTTP status code 0

### ISSUE THREAD

**Issue by matteogit** [postmanlabs/newman#373]
Hi all, 
we are using postman / newman to have continuous API testing, the flow is:
- make / test requests from Postman
- save and share collection, to get collection link URL
- NodeJS script which runs newman passing each collection URL,  in series

The problem is that, randomly, and in all environments ( local, staging, production ), we are getting an HTTP code 0, while when running them from Postman runner, never gets it.
Example result :
```
  {
            "id": "5c79e93b-72ca-cef6-5148-d5e03c9ceddf",
            "name": "XXX",
            "url": "{{endpoint}}/api/path",
            "totalTime": 0,
            "responseCode": {
                "code": 0,
                "name": "",
                "detail": ""
            },
            "tests": {
                "Status 200": false,
                "Took >1.5s": true
            },
            "totalPassFailCounts": {
                "pass": 1,
                "fail": 1
            },
            "testPassFailCounts": {
                "Status 200": {
                    "pass": 0,
                    "fail": 1
                },
                "Took >1.5s": {
                    "pass": 1,
                    "fail": 0
                }
            },
            "times": [],
            "allTests": [
                {
                    "Status 200": false,
                    "Took >1.5s": true
                }
            ],
            "time": 0,
            "meanResponseTime": 0
        },
```
And these are the tests:
```
try { var responseJson = JSON.parse(responseBody); } catch(e) { }
tests["Status 200"]      = responseCode.code === 200;
tests["Took >1.5s"]      = responseTime < 1500;
```
I already tried to increase timeout to high values, like 10000, but still get the error,randomly.
Is something that even other people experienced ? 
Thanks

**Comment by czardoz** [comment]
@matteogit Response Code 0 happens when there is a network error when the request is sent. Are you seeing any errors on your console?

For reference: https://github.com/postmanlabs/newman/blob/a3c467231e8758a3882bc17fd83533780f9fe41a/src/runners/RequestRunner.js#L189

**Comment by matteogit** [comment]
Thanks for your feedback, unfortunately in Node console there are no errors, maybe would be nice if we get as result the related connection error ( `ECONNRESET` , `ETIMEDOUT` ... ) 
Maybe will try to log whats inside the `error` parameter

https://github.com/postmanlabs/newman/blob/a3c467231e8758a3882bc17fd83533780f9fe41a/src/runners/RequestRunner.js#L181

**Comment by shamasis** [comment]
Newman v3 beta should highlight request errors.
https://github.com/postmanlabs/newman/tree/feature/v3

**Comment by kunagpal** [comment]
Hey @matteogit, do these issues still persist for you in the latest Newman release (v3.1.1) ?

**Comment by kunagpal** [comment]
Closing issue on our end due to inactivity. Do let us know if this issue still persists. :)

**Comment by nadagamal** [comment]
Dear Guys,

I have the same issue. Did anyone solve it.

Thank you
