### ISSUE TITLE
Running newman nodejs library only with url

### ISSUE THREAD

**Issue by IchordeDionysos** [postmanlabs/newman#374]
As I read in your docs, there are at least two ways to select which collection should be run during the test:
1. Via a collection.json file (`newman -c mycollection.json`)
2. Via a Postman url (`newman -u https://www.getpostman.com/collections/cb208e7e64056f5294e5`)

Now I wondered if I could run a collection from url in Node.js as well, so I tried this:

    newmanOptions = {
        url: "https://www.getpostman.com/collections/cb208e7e64056f5294e5"
    };
    Newman.execute(null, newmanOptions, callback);

I would love that running tests in Node.js from postman url would be possible somehow
Thanks in advance

**Comment by czardoz** [comment]
Hi, Newman does allow doing this. The caveat is that you'll have to download the collection from the URL yourself.

Check out https://github.com/postmanlabs/newman#library for more :)
