### ISSUE TITLE
.includes & .split is not a function in newman

### ISSUE THREAD

**Issue by srbangre** [postmanlabs/newman#375]
.includes() and .split() is not working in newman although postman understands the command.
I found it the hard way. my postman collection was running successfully in postman but in newman my tests were always failing. i modified my collection order, use different env variable names, prescript etc. but then i found out that newman does not understand .includes command.

**Comment by czardoz** [comment]
Are these the Lodash commands?

**Comment by srbangre** [comment]
they are javascript commands

**Comment by srbangre** [comment]
.sort() command is not recognized by postman even though it is js command.

**Comment by srbangre** [comment]
how do i check if element exists in an array?

**Comment by czardoz** [comment]
Hi,

While we do a dive deep into this issue, you can use the equivalent lodash commands as a workaround. 

E.g:

**Comment by srbangre** [comment]
okay, i could use _.includes() command but command _.split() is not recognized. i get error - There was an error in evaluating the test script:  _.split is not a function

here is what i am doing - 

var ListOfStores = postman.getEnvironmentVariable('storelist')
var storelist = _.split(ListOfStores, ',', 2)

**Comment by czardoz** [comment]
Okay, I did some digging about this right now.

1. `.includes` is a ES6 feature which is not available in Node yet :-(
You will have to use `_.includes` (which works fine)

2. `.split()` works fine for me in Postman (and Newman).
I wrote a small test: 
```
var myString = '1,2,3,4';

tests['There should be four parts'] = myString.split(',').length === 4;
```
and it passes in Newman as well as Postman.

3. `.sort()` works fine for me in Postman and Newman.
I wrote another small test:
```
function is_sorted(arr) {
    var len = arr.length - 1;
    for(var i = 0; i < len; ++i) {
        if(arr[i] > arr[i+1]) {
            return false;
        }
    }
    return true;
}

var unsortedArray = [3, 4, 1, 9]
var sortedArray = unsortedArray.sort();
console.log("Sorted Array: ", sortedArray);
tests['array should be sorted properly'] = is_sorted(sortedArray);
```
Can you share the exact code you're using?

Thanks

**Comment by srbangre** [comment]
unfortunately i cannot share my code here but i was able to use custom functions just the way you explained above. Thank you so much for that.  so i guess you can close this ticket.

**Comment by czardoz** [comment]
Great, glad to hear things are working fine :)

**Comment by kunagpal** [comment]
**Update** For those stumbling upon this thread, please note that the above-mentioned functions work correctly in newman, but on Node v6 and above. @srbangre 

```json
{
	"variables": [],
	"info": {
		"name": "newman-github-375",
		"_postman_id": "846ca12d-cca8-15ad-aba6-f2fbecee92db",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "Simple GET request",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"var myString = '1,2,3,4';",
							"",
							"tests['There should be four parts'] = myString.split(',').length === 4;",
							"",
							"function is_sorted(arr) {",
							"    var len = arr.length - 1;",
							"    for(var i = 0; i < len; ++i) {",
							"        if(arr[i] > arr[i+1]) {",
							"            return false;",
							"        }",
							"    }",
							"    return true;",
							"}",
							"",
							"var unsortedArray = [3, 4, 1, 9]",
							"var sortedArray = unsortedArray.sort();",
							"console.log(\"Sorted Array: \", sortedArray);",
							"tests['array should be sorted properly'] = is_sorted(sortedArray);",
							"",
							"var array = [1, 2, 3, 4];",
							"tests[\".includes works fine for existent values\"] = array.includes(4);",
							"tests[\".includes works fine for absent values\"] = !array.includes(10);"
						]
					}
				}
			],
			"request": {
				"url": "https://postman-echo.com/get",
				"method": "GET",
				"header": [],
				"body": {},
				"description": "https://github.com/postmanlabs/newman/issues/375"
			},
			"response": []
		}
	]
}
```

**Comment by dwertheimer** [comment]
@kunagpal thanks. I just loaded Newman and have Node with ES6 previously. Am getting these errors. How do I force Newman to use a newer Node.js?

**Comment by kunagpal** [comment]
You'd have to install the desired version of Node, which can be accomplished with a tool like https://www.npmjs.com/package/n to manage multiple node versions on your computer.

**Comment by dwertheimer** [comment]
@kunagpal 

Just checked 
My Node --version is 6.9.4

That should be plenty good for es6 but Newman still gives me TypeErrors which Postman does not. Thoughts?

**Comment by kunagpal** [comment]
@dwertheimer I was unable to reproduce your issue. Could you share the following details?

* The Newman version.
* The error message.
* The collection.

**Comment by dwertheimer** [comment]
Thanks. @kunagpal I am sure I am missing something simple here. It's just frustrating to write and test code in Postman and have it work fine, only to have it fail in Newman. Here are a couple of basic examples.

```
// Both of these statements fail (with TypeErrors) in Newman, but work in Postman app.
const e = postman.getEnvironmentVariable;
console.log(e("abc")); //assuming there is an env var for "abc"
console.log(["foo","bar"].find("foo"));

env> newman --version
3.6.0
env> node --version
v6.9.4

```

**Comment by dskinnerMg** [comment]
Hi, 

I received this issue, today as well. I encountered it when storing an array into an environment variable, this seems to convert it to text. The I used .split(',') converting it back to an array. This works in postman but not newman.

As a work around I used:
`.toString()`
this makes it work in postman and newman.

Test case for the issue:
`{
	"info": {
		"name": "Newman Split Test ",
		"_postman_id": "3f6bbaaa-3491-6233-5f81-de6f83963028",
		"description": "Test Case for .split(',')",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": ".split(',') test",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"pm.test(\".split(',') test\", function () {",
							"    // Works in both postman and newman",
							"    comma_string = \"1,2,3,4,5\";",
							"    pm.environment.set(\"env_string\", comma_string)",
							"    array_from_string = pm.environment.get(\"env_string\").split(',');",
							"    pm.expect(array_from_string.length).to.eql(5)",
							"});",
							"",
							"pm.test(\".split(',') test with array\", function () {",
							"    // works in postman but not newman",
							"    comma_array = [1,2,3,4,5];",
							"    pm.environment.set(\"env_string\", comma_string)",
							"    array_from_string = pm.environment.get(\"env_string\").split(',');",
							"    pm.expect(array_from_string.length).to.eql(5)",
							"});",
							"",
							"pm.test(\".split(',') test with array using toString\", function () {",
							"    // works in postman and newman",
							"    comma_array = [1,2,3,4,5];",
							"    pm.environment.set(\"env_string\", comma_string)",
							"    array_from_string = pm.environment.get(\"env_string\").toString().split(',');",
							"    pm.expect(array_from_string.length).to.eql(5)",
							"});"
						]
					}
				}
			],
			"request": {
				"method": "GET",
				"header": [],
				"body": {},
				"url": {
					"raw": "https://postman-echo.com/get",
					"protocol": "https",
					"host": [
						"postman-echo",
						"com"
					],
					"path": [
						"get"
					]
				},
				"description": "Test Case for .split(',') failing to execute on newman."
			},
			"response": []
		}
	]
}`

**Comment by ManikandanRajendran** [comment]
could someone help me using _.includes(). below is my case where am not getting expected result.

var a = 10.63
var b = 10.635

var c = _.includes(a);  ==> i want to check whether b.includes(a)

but am getting c value as false.

could you please advise. thanks in advance.
