### ISSUE TITLE
Folder name missing from request description in test report file

### ISSUE THREAD

**Issue by aqyblitz** [postmanlabs/newman#380]
The JUnit XML file produced by setting a value to the testReportFile option is great, but it doesn't have the folder the request was in attached to the request's description.

I am using each folder as a way to isolate a functional test case as a part of the sequence, and can't generate a meaningful result summary without having the folder name. Could this be added?

**Comment by ebelanger** [comment]
#392

**Comment by ebelanger** [comment]
#392 
#386 

Both of these issues have been opened afterwards for similar reasons.

**Comment by shamasis** [comment]
JSON reporter now provides extensive run information in newman v3.x+
