### ISSUE TITLE
Feature Request - Run multiple collections from command line

### ISSUE THREAD

**Issue by cwbell1** [postmanlabs/newman#387]
Passing in a run argument you should be able to run more than one collection in a single call to newman. Possibly by passing in the name of a folder, or a filename pattern matcher. Also you should be able to specify if these collections run synchronously or in parallel.

**Comment by czardoz** [comment]
Hi @cwbell1,

In a way, collections are single units by themselves. Running multiple collections in one go sort of goes against that philosophy, so I don't think Newman will support it in the near future. 

That being said, it is fairly straightforward to write a Bash script that can launch multiple Newman processes, so you might want to consider that option :-)

Cheers!
