### ISSUE TITLE
Newman does not dereference variables the same as Postman

### ISSUE THREAD

**Issue by cwbell1** [postmanlabs/newman#389]
I found a situation where newman does not completely dereference a variable.
Assume the following are set in the pre-request script.
```
postman.setGlobalVariable("salutation", "Hello");
postman.setGlobalVariable("{{salutation}}Name"," World");
```
Assuming I do not know the value of salutation ahead of time (as it could change), in the body of the request I send "{{{{salutation}}Name}}". In this situation Postman dereferences 'salutation' to 'Hello', finally dereferencing 'HelloName' to get the end result.
expected value returned by postman:
```
Hello World
```
actual value from newman:
```
{{HelloName}}
```

**Comment by cwbell1** [comment]
I noticed that if I export my globals the following shows:
```
 {
  "key": "{{salutation}}Name",
  "value": "Hello World",
  "type": "text",
  "name": "{{salutation}}Name"
 }
```

**Comment by abhijitkane** [comment]
@cwbell1 In your scripts, the {{..}} notation won't work.

Use `postman.setGlobalVariable(globals.salutation+"Name"," World");`
