### ISSUE TITLE
Newman returning 500 UNEXPECTED_ERROR for a request that worked in Postman

### ISSUE THREAD

**Issue by ronteddu** [postmanlabs/newman#390]
I have a collection with one request that gets content from a micro service. This works fine when run in Postman with a 200 and response body as expected. I have 2 tests to check for status code and body content.

There are no environment variables to this request. When I run this collection in Newman, I am receiving a 500 UNEXPECTED_ERROR response (checked the verbose log). 

Console log of the request appeared fine as well.

**Comment by ronteddu** [comment]
To get this working I had to add Accept:application/json in the header. I still wish Newman could handle this.

**Comment by czardoz** [comment]
@ronteddu If you select "JSON" in the dropdown, Postman will add the header automatically.

![19-apr-2016 01 03 33pm](https://cloud.githubusercontent.com/assets/3726484/14631078/43694078-062f-11e6-9946-4ae319f4e5d2.png)

**Comment by czardoz** [comment]
Unless explicitly specified, Newman will never add any headers, because the header will then be sent to servers which may not support them :)

**Comment by ronteddu** [comment]
@czardoz The request method is GET, so cannot select anything as the body would be disables :)

**Comment by czardoz** [comment]
Actually, I misread your comment. I thought you were talking about the `Content-Type` header, which is inserted when you select a value in the dropdown :)

For the `Accept` header, the same logic applies though, it's not possible to know in advance what the server accepts :)

Glad you got your issue fixed though. We'll update our documentation to mention this common case.

**Comment by ronteddu** [comment]
Thanks @czardoz
