### ISSUE TITLE
Add the collection/folder name to test name in xml result.

### ISSUE THREAD

**Issue by anyone-can-test** [postmanlabs/newman#392]
I run collection in Jenkins.
Test name is only request name in xml result (like JUnit).
If I have several folders and requests, then tests is not structured like class/method.

So, I want that test name has request and folder name.
For example.
[collection name].[folder name].[request name]

Thank you.

**Comment by rapidroamer** [comment]
+1

**Comment by kunagpal** [comment]
@rapidroamer @anyone-can-test Apologies for the delay, Newman v3.x comes with an improved JUnit reporter, which can be used as follows: `newman run collection.json -r junit,cli --reporter-junit-export report.xml`

**Comment by rapidroamer** [comment]
@kunagpal @anyone-can-test

I have been using that already, I still don't get to see folder name in junit report.

**Comment by rapidroamer** [comment]
Hi @anyone-can-test, I think this item still needs to be looked into.. What do you think?

**Comment by kunagpal** [comment]
@rapidroamer We've included folder names JUnit reports (since Newman `v3.5.0`), do check it out 😄 

You can update newman with: `npm i -g newman`

**Comment by svarshney2311** [comment]
I have similar king of issue  for Junit report in Jenkins. I dont see folder name in Jenkins.
I have collection 'DigitalAPI' than I have subfolder under this 'UserProfile'. but in the junit xml, I don't see folder name.

![image](https://user-images.githubusercontent.com/66395814/92167905-8662ea80-ee08-11ea-98eb-abde6c65d909.png)

**Comment by IssacH** [comment]
Hi @svarshney2311 , have you got a solution for this issue? If so could you please share? Thanks a lot!
