### ISSUE TITLE
Newman not executing tests that involve an array when there is an error but moves on to the next request

### ISSUE THREAD

**Issue by ronteddu** [postmanlabs/newman#397]
I do know that -s and -x switches are for stopping on error and continuing on error. However, in this specific scenario I am extracting an array number into a variable when the required data is found in a specific array and use that array number to do my remaining tests passed as a variable. 

Upon encountering an error such as not finding the required data in any of the array results, Newman passed the test as the status code is still 200 (which is the first test) but ignores the remaining tests in that request. This essentially means that the final count shows all passed where the reality is that Newman did not actually execute and fail some tests where the variable is involved.

Example:

I am doing a GET call on a microservice that returns an array object with multiple JSON response data. Within this I need to find a specific key value in the response, extract the index of that array, store it in a  variable and pass it in the remaining tests for other key values within that array.

```
//My variables
var response = JSON.parse(responseBody);
var i;
//Extract array number i where the MemberNumber is found
for (i=0; i<response.Notifications.length; i++)
{
    if (response.Notifications[i].MemberNumber == environment.MemberNumber)
        break;
}
```
```
/* Execute tests */
tests["Status code is 200"] = responseCode.code === 200;
tests["Notifications array has MemberNumber"] = response.Notifications[i].MemberNumber === environment.MemberNumber;
tests["Notifications array with MemberNumber has NotificationType"] = response.Notifications[i].NotificationType === globals.OnlWelcomeNotification;
```

The response is for example, an empty array with no results.
Newman throws "Cannot read property 'MemberNumber' of undefined" in red and passes Status code is 200.
It then moves on to the next request in the collection or folder, so it actually skipped the second test in the above request.
To the end user, who looks at the number of tests passed/failed, would have no clue if something went wrong here.

This seems to be a bug and is critical in my opinion. Can this please be fixed?

**Comment by czardoz** [comment]
With the `-x` option, Newman will return a non-zero exit code, which indicates the run failure. There are two things at play here:
1. Errors <- Meaning Newman was not able to successfully run the test
2. Test failures <- The test did not pass

Newman does not report Errors in the summary currently. One workaround is to wrap your code in a try-catch:

```
try {
   // something that may cause errors
} catch (e) {
    console.log(e.stack || e);
    tests['ran successfully'] = false;
}
```

**Comment by czardoz** [comment]
As an aside, APIs should not return JSON Arrays, for security reasons: http://flask.pocoo.org/docs/0.10/security/#json-security

**Comment by ronteddu** [comment]
Thanks @czardoz. I'll try the try catch above and consider the security reason as well.
It'd be very nice if Newman can try and run those tests and fail them instead of writing error to console which the user may or may not see. If the tests are failed then at least the count will show that there are failed tests in that folder or collection which the user can view in the logs. 

For the time being I am forcing the tests to fail so as to keep the number of tests count to be consistent for any run.

**Comment by kunagpal** [comment]
@czardoz @ronteddu Marking this issue as resolved on our end.
