### ISSUE TITLE
Test Passes in Postman but fails in newman

### ISSUE THREAD

**Issue by kanishka84** [postmanlabs/newman#398]
@czardoz 
I created some tests using Postman, they work fine in postman and the results passes this is what i expected.
Now when I started running these tests in Newman some of the test started failing.
I introduced delay in running the test's in newman. They solved the problem for a while but time to time these tests fail. This has led me to believe that using delay is not a very good solution.

The tests are:
tests["Status code is 500"] = responseCode.code === 500;
tests["Body matches string"] = responseBody.has("conflict: Document update conflict.");

Content-Type: application/json; charset=utf-8

**Comment by czardoz** [comment]
Since these failures are intermittent, they are probably caused by some race condition between the server and Newman.

Can you log the responseBody in your test script and see what it is when the test fails?
```
console.log(responseBody);
```

**Comment by kanishka84** [comment]
I have tried the console.log(responseBody)
The response body contain a bunch of error message which is send from our couch DB. Also the status code is 500 which is verifying in the test bellow as a negative test case
tests["Status code is 500"] = responseCode.code === 500;

Now getting back to the response the response contains a message from couch which is again used in a test.
"message": "conflict: Document update conflict.",
tests["Body matches string"] = responseBody.has("conflict: Document update conflict.");

**Comment by czardoz** [comment]
The next time your negative test case fails, can you check what the response body is, and post it here?

**Comment by kanishka84** [comment]
This is the response body

{
  "name": "CouchError",
  "message": "conflict: Document update conflict.",
  "error": "conflict",
  "reason": "Document update conflict.",
  "headers": {
    "server": "CouchDB/1.6.1 (Erlang OTP/R16B03)",
    "date": "Thu, 05 May 2016 08:59:59 GMT",
    "content-type": "text/plain; charset=utf-8",
    "content-length": "58",
    "cache-control": "must-revalidate",
    "status": 409
  }
}

**Comment by czardoz** [comment]
Well, you're testing for error code 500, but the status in the response is 409. Is that the issue?

**Comment by kanishka84** [comment]
Good point. I have made some changes to see if this is the problem.

I changed my test totests["Status code is ok"] = responseCode.code === 409;; and run the test from postman as well as newman. In both the case the TC failed.
I am attaching a screen shot from postman which captures the status code to be 500
![capture](https://cloud.githubusercontent.com/assets/18544878/15041058/c642fec2-12d6-11e6-9740-de198babd760.PNG)
![capture2](https://cloud.githubusercontent.com/assets/18544878/15041059/c64d34f0-12d6-11e6-869c-9ab319deed83.PNG)

**Comment by czardoz** [comment]
Hmm, hazarding a guess here, since I don't have a concrete test case to reproduce the issue. Can you try changing your test case to this?

```
tests["Status code is 500"] = responseCode.code.toString() === "500";
```

**Comment by pollenflugkalender** [comment]
I have a comparable issue.

I extract content from the response header "location" via postman.getResponseHeader("Location") and save it in the env variable targetUri via postman.setEnvironmentVariable("targetUri", postman.getResponseHeader("Location")); 

Then I request (GET) this URI in the next testcase. This works in postman without problems but if I run the same code in Newman the Variable targetUri is always set to 'null' and therefore the next step fails.

Any suggestions how I can fix that?

**Comment by czardoz** [comment]
@pollenflugkalender Can you try logging the environment variable value after setting it? 
```
console.log(postman.getEnvironmentVariable('targetUri'));
```

**Comment by pollenflugkalender** [comment]
I guess I found the underlying problem. The POST request I do before fails therefore there is nothing to extract. And it seems that Newman sends the request body differently then Postman. The backend returns a 400 an in the server side log I see the following error: INVALID_PAYLOAD|Invalid json format

**Comment by pollenflugkalender** [comment]
Okay, now it becomes weired. According to the server logs the body is empty and therefore invalid. Newman does not send the body in the POST request.

**Comment by czardoz** [comment]
Seems like a bug! Can you tell me the following:
1. Newman version
2. Node version 
3. Can you export your collection from Postman, open it in a text editor, search for your request using the name, and post the entire request JSON block here? 

It should look something like this (but it can have other stuff in it too):
```
		{
			"id": "951fc3e8-c6b6-5c19-9f69-4e7499b3127f",
			"url": "http://echo.getpostman.com/auth/hawk",
			"preRequestScript": "",
			"pathVariables": {},
			"method": "GET",
			"data": [],
			"dataMode": "params",
			"version": 2,
			"tests": "var response = JSON.parse(responseBody); tests['Hawk auth should pass'] = response.status === 'pass';",
			"currentHelper": "hawkAuth",
			"time": 1448888108375,
			"name": "test hawk auth success",
			"description": "",
			"collectionId": "d497d10e-e280-8c83-709a-a4d4ea12ad14",
			"responses": []
		}
```

I am especially interested in the `data`, `dataMode` and `rawModeData` attributes in the request.

If you have any sensitive data, feel free to remove it. Or, you can mail help@getpostman.com with the data. We keep everything confidential.

Thanks!

**Comment by pollenflugkalender** [comment]
1. Node version: v5.3.0  (Windows)

2. Newman version:
└─┬ newman@2.0.9
  ├─┬ jsdom@7.1.0
  │ ├── cssstyle@0.2.36
  │ └─┬ htmlparser2@3.9.0
  │   └─┬ readable-stream@2.1.4
  │     └── buffer-shims@1.0.0
  ├─┬ postman-collection-transformer@1.5.6
  │ └─┬ intel@1.0.2
  │   └── symbol@0.2.3
  └─┬ xml2js@0.4.16
    └─┬ xmlbuilder@4.2.1
      └── lodash@4.13.1

3. This I have to check that with our security guys first...

**Comment by czardoz** [comment]
Okay. Ideally, if the request should have the following:
1. `dataMode` should be "raw"
2. `rawModeData` should contain your JSON body
3. `headers` should contain a `Content-Type` header, set to `application/json`.

**Comment by pollenflugkalender** [comment]
1. "dataMode" : "raw",

2. "rawModeData" : "{\"start\":\"2016-02-22T12:45:37Z\",\"end\":\"2016-10-22T12:45:37Z\",\"displayStart\":\"2016-02-22T12:45:37Z\",\"displayEnd\":\"2016-10-22T12:45:37Z\",\"weight\":30,\"type\":\"Info\",\"text\":{\"en\":{\"title\":\"en Title\",\"text\":\"Text\"},\"fr\":{\"title\":\"fr Title\",\"text\":\"Text\"},\"de\":{\"title\":\"de Title\",\"text\":\"Text\"},\"it\":{\"title\":\"it Title\",\"text\":\"Text\"}},\"channels\":[\"ABCD\"],\"services\":[{\"id\":\"{{serviceId}}\"}],\"source\":{\"creator\":{\"firstName\":\"John\",\"lastName\":\"Smith\",\"phone\":\"+12798758875\",\"email\":\"john.smith@mycorp.com\"}}}" 


3. "headers" : "Authorization: Bearer {{access_token}}\nSCS-Request-ID: {{requestId}}\nContent-Type: application/json\n",

**Comment by rkmresh** [comment]
I also have same issue. How to fix it?

**Comment by GlobalAutomation** [comment]
Hi facing similar issue it seems as if body is not getting parsed in newman but test runs fine in postman.

**Comment by shamasis** [comment]
Does this have same behaviour in [newman v3 beta](https://github.com/postmanlabs/newman/tree/feature/v3) vs [Postman Canary](http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/)?

This issue (and similar ones) should go away once Newman v3 goes out.

**Comment by shamasis** [comment]
This has been fixed when run between Postman Native apps and Newman. Chrome app will get this soon.

**Comment by Pablodotnet** [comment]
As Chrome Apps are going to be obsolete soon, then is there a date for an Ubuntu Desktop App? As we are using the chrome app with newman we continue having this issue.

**Comment by vreinholde** [comment]
Has this issue been resolved?

**Comment by shamasis** [comment]
The original issue has been resolved along with a number of other issues that were mentioned in the thread. Nevertheless, due to platform restrictions in Chrome App variant, not everything can be made 100% same. 

Newman and all native apps should behave uniformly. 

PS: @vreinholde if you're facing similar issue, I suggest you open a new issue with as much details as you can.

**Comment by carlospliego** [comment]
getting the same issue now. version : 3.9.3. Tests pass in postman but not newman. Getting 422 in newman 200 in postman

**Comment by ahaydarcrimson** [comment]
Same issue is happening here in newman 3.9.3.

**Comment by as-beaulieu** [comment]
What is the proper header for the Authorization? In Postman, I'm using a Bearer Token, set to variable {{authToken}}. But when I export it into a collection.json, my header is blank. I've tried the two following for the header:

**Comment by rohitkashyapvatta** [comment]
I am also facing this error, getting following message on console " 1.  ReferenceError    pm is not defined                                     
                       at prerequest-script "

Can you please advise what is the way out for this?

**Comment by djo504** [comment]
I am having this same issue. Any solution at all?

**Comment by xsrvmy** [comment]
Can confirm this is a problem. I am getting fails when postman passes.

**Comment by QuinnBast** [comment]
Agreed, this is still a problem
Local postman: 14/14 pass
Local newman: 14/14 pass
Travis-CI newman: 13/14 pass - failing test will result in a 409 error.

Restarting the Travis-CI build 4-5 times will eventually result in all tests passing. For some reason newman is causing different request status codes.

**Comment by sergiybuch** [comment]
Same here, using pre-request script to get a token. Runner works great but getting errors in Newman.

**Comment by luoenzhen** [comment]
I still have the same issue. Passed on the Postman but failed on the Newman.

**Comment by cah-kavan-singh** [comment]
I have the same issue as well. Multiple endpoints failing while running a collection using newman but passing on postman

**Comment by luoenzhen** [comment]
Would that because the timeout set with too small value caused the test failed?

**Comment by cah-kavan-singh** [comment]
Okay I figured something out. It maybe be pretty obvious but I'll post it anyways. So in postman you have to types of values for environment variables, **current** and **initial**. I noticed that the newman command takes the initial value of the environment variables to run. I set all correct values in the initial section and my newman run worked without issues.

**Comment by luoenzhen** [comment]
> Okay I figured something out. It maybe be pretty obvious but I'll post it anyways. So in postman you have two types of values for environment variables, **current** and **initial**. I noticed that the newman command takes the **initial** value of the environment variables to run. I set all correct values in the **initial** section and my newman run worked without issues.

Would be good if you provide more detailed info or example please.

**Comment by cah-kavan-singh** [comment]
![postman env](https://user-images.githubusercontent.com/64949092/142977819-86971cf3-7166-4d16-9345-9f320901edcb.png)

@luoenzhen The above pic is taken from postman. I'm looking at one of the environment variables **testenv**. Here, there are 2 columns, **initial** value and **current** value. The values of the variables in the **current** column in used by the postman collection runner, but not by newman. Newman takes the **initial** column values for running the collection. So from my previous comment, when I set all the correct values in the **initial** column and then ran my collection using newman the APIs in the collection ran successfully.

**Comment by luoenzhen** [comment]
@cah-kavan-singh First thanks for your quick reply and apology for my belated response. For my case, all the variables are set correctly. I have nearly 200 APIs for testing, they are similar but different, 4/5 of them have no issue when running by newman. No idea why it would fail the other 1/5.
