### ISSUE TITLE
{{$guid}} to generate new GUIDs within the same request

### ISSUE THREAD

**Issue by davenewza** [postmanlabs/newman#399]
Using `{{$guid}}` more than once in the same request yields the same GUID. A new GUID should be generated each time.

**Comment by czardoz** [comment]
Hi, what newman version are you using?

**Comment by davenewza** [comment]
I am using 2.0.8.

**Comment by czardoz** [comment]
Makes sense.. until I fix this, you can use this small snippet to generate one:

```
  function S4() {
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  }

  function guid() {
    return (S4() + S4() + "-" + S4() + "-" + S4() + "-" + S4() + "-" + S4() + S4() + S4());
  }
```

**Comment by davenewza** [comment]
That's great!

Something to consider is that this may be a breaking change for some clients.  The fact that the GUID generated remains the same regardless of the number of {{$guid}}s used may be something that someone out there is intentionally utlising.

**Comment by czardoz** [comment]
Postman only generates a single one, so generating a new one in Newman breaks compatibility. I'm marking this as deferred for now.

**Comment by shamasis** [comment]
Newman v3 genereates a new GUID on every use. try it out - https://github.com/postmanlabs/newman/tree/feature/v3

Closing this issue meanwhile
