### ISSUE TITLE
Auth issue for helperAttributes formatting

### ISSUE THREAD

**Issue by bclodius** [postmanlabs/newman#400]
We've run across the following issue for some of our test cases.

Postman exported file creates some helperAttributes like such.

```
"helperAttributes": "{\"id\":\"basic\",\"username\":\"user\",\"password\":\"password\",\"saveToRequest\":true}",
```

This will cause a test case that passes in Postman to fail in Newman until the formatting is updated like such.
```
"helperAttributes": {
                "id": "basic",
                "username": "user",
                "password": "password",
                "saveToRequest": true
            },
```

**Comment by czardoz** [comment]
@bclodius This was a problem, but has been fixed in the latest version of Postman. Can you update Postman and try exporting again?

**Comment by bclodius** [comment]
@czardoz I've imported and exported a number of postman collections and used them with newman since and haven't seen any issues.  I think the formatting issue was left from a much older export from a much older version of postman.
