### ISSUE TITLE
JSON.parse(): Unexpected end of input200

### ISSUE THREAD

**Issue by ckingsbu** [postmanlabs/newman#403]
Hello, I have a set of tests that are working fine from Postman, but randomly failing when run from newman.  The output of newman has the following:

200 1069ms TICK QuoteTicks [GET] https://private:443/api
    ✔ Check 2 bars returned
    ✔ Check instrument
    ✔ Check timeStamp
    ✔ Check bidPrice
    ✔ Check askSize
    ✔ Status code is 200
Encountered an error during JSON.parse(): Unexpected end of input200 757ms TICK TradeBars [GET] https://private:443/api
200 934ms TICK TradeTicks [GET] https://private:443/api2
    ✔ Check 2 bars returned
    ✔ Check instrument
    ✔ Check timeStamp
    ✔ Check price
    ✔ Check size
    ✔ Status code is 200

Using the outputFileVerbose, I can see when it fails, it seems to think the Response body is missing:   

-------------------------------------------------------------------------------------------
200 757ms TICK TradeBars [GET] https://private:443/api
------------------------------------------------------------
Request headers:
{
 "authorization": "Basic xxx",
 "host": "private:443",
 "accept-encoding": "gzip, deflate"
}
Request data:

------------------------------------------------------------
Response headers:
{
 "date": "Thu, 12 May 2016 08:01:44 GMT",
 "content-type": "application/json",
 "content-length": "0",
 "connection": "close"
}
Response body:

-------------------------------------------------------------------------------------------
200 934ms TICK TradeTicks [GET] https://private:443/api2
------------------------------------------------------------

But I've verified that is not the case, the Response body was properly returned.

**Comment by czardoz** [comment]
Weird. Can you try logging the response body using:
```
console.log("This is the response body: ", responseBody);
```
in your Test script?

**Comment by ckingsbu** [comment]
Hi @czardoz, please ignore my email.  After further investigation, it actually appears to be a bug in the server thats triggered when the test run in a particular order.   Newman actually did exactly what its supposed to, great!
