### ISSUE TITLE
Custom TestResponseHandler

### ISSUE THREAD

**Issue by tk-codes** [postmanlabs/newman#404]
Now I just pass the existing reponse handler.
`responseHandler: "TestResponseHandler"`

This is very limited. Is it possible to write a custom response handler, which extends the TestResponseHandler?
If yes, could you please instruct me, how to do it?

**Comment by spark85** [comment]
I'd like to know this as well, I'd like to use Newman for response scrapping as well

**Comment by shamasis** [comment]
The upcoming newman v3 will allow one to listen to `test` as an event. :-) https://github.com/postmanlabs/newman/tree/feature/v3

**Comment by shamasis** [comment]
Newman v3 now has event driven API. It has `test` event you can use
https://github.com/postmanlabs/newman#newmanrunevents

sample to use events - https://github.com/postmanlabs/newman/blob/develop/examples/find-unique-urls-in-run.js

**Comment by tk-codes** [comment]
Thank you for the implementation and example.

**Comment by shamasis** [comment]
@tk-codes - we would love to hear if the new newman API helps you. :-)
