### ISSUE TITLE
html report inline CSS style can not display properly in jenkins workspace

### ISSUE THREAD

**Issue by Scottsuen** [postmanlabs/newman#412]
newman version: 2.0.9
OS: os x 10.11.5

chrome console report that：
```
Refused to apply inline style because it violates the following Content Security Policy directive: 
"style-src 'self'". Either the 'unsafe-inline' keyword, 
a hash ('sha256-TBh6eBDliEJQ34boSLJOrwxW04VSaggUrCFINLnjdbI='), 
or a nonce ('nonce-...') is required to enable inline execution.
```

**Comment by michaelajr** [comment]
Same in Safari.
```Blocked script execution in 'https://.../output/index.html' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.```

**Comment by shamasis** [comment]
We are removing all CSS styles in newman v3 HTML report and using pure HTML tables.

**Comment by shamasis** [comment]
addressed in newman v3. the output is very crude now and will be uplifted soon.
