### ISSUE TITLE
handle file download request from Newman

### ISSUE THREAD

**Issue by swapnilpatne** [postmanlabs/newman#413]
How to handle file download request from Newman? Can someone please answer?

**Comment by czardoz** [comment]
@swapnilpatne You mean saving the request to a file?

**Comment by swapnilpatne** [comment]
I mean when a response of a request is file e.g. pdf or zip or xml file etc

**Comment by czardoz** [comment]
Hmm, Newman will expose the responseBody as the `responseBody` parameter in your tests, but there's currently no way to save responses to a file.

**Comment by swapnilpatne** [comment]
Is there a way by which from "tests" tab in Postman I can read the filename returned in response header and then write a javascript code to get that response written in file? And then can run those requests from newman?

**Comment by kunagpal** [comment]
@swapnilpatne Well, writing to a file will require using one of the write methods from [fs](https://nodejs.org/api/fs.html), which is currently not included within the Postman Sandbox.

**Comment by kunagpal** [comment]
@swapnilpatne This is not a part of our current roadmap, but has been marked as a feature request and added to our internal tracker. We'll update this thread when any progress occurs on this. :)

**Comment by shikhartanwar** [comment]
Is this being targeted for the next release? As a newman user I feel that this is a very important feature and blocks of lot of API operations that are centered around files or storage.

**Comment by kiranwilson** [comment]
Do we have any update regarding this feature?

**Comment by kunagpal** [comment]
@kiranwilson This isn't in the works presently, but we'll update this thread when any progress is made.

**Comment by kiranwilson** [comment]
@kunagpal Thanks for the response

**Comment by kunagpal** [comment]
@swapnilpatne @kiranwilson @shikhartanwar As a workaround, you can have the following snippet in a file, say `newman-run.js`:
```js
var i = 0,
    fs = require('fs'),
    newman = require('newman'); // ensure that you have run "npm i newman" in the same directory as this file

newman.run({
  // run options go here
}, function (err, summary) {
  // handle collection run err, process the run summary here
}).on('request', function (err, execution) { // This is triggered when a response has been recieved
   if (err) { return console.error(err); }

   // ensure that the file name used below has a unique suffix, or the file will keep getting
   fs.writeFile(`response${i++}.txt`, execution.response.stream, function (error) {
      if (error) { console.error(error); }
   });
});
```

You can then run the script above with `node newman-run.js`, which will save responses to any file of your choice.

**Comment by chitzinwin** [comment]
I run as  `node newman-run.js collection.json `  but no file was created. do I have to change in the script?

**Comment by kunagpal** [comment]
@chitzinwin Could you share your collection?

**Comment by kunagpal** [comment]
@chitzinwin You'll have to specify the collection as an option in the first argument to `newman.run`. See https://github.com/postmanlabs/newman#newmanrunevents for a working example.

**Comment by chitzinwin** [comment]
Perfect!  It's working now. @kunagpal Thank for prompt response!

**Comment by shamasis** [comment]
Closing issue. Also on another note, someone can create a newman reporter that saves all responses to file :-p

**Comment by RSUIAutomation** [comment]
So the send and download feature is not available in newman? 

Postman always relies on third party code to handle its upload data?

You cant actually fully automate sending files using newman? You always have to add some third party code to get files completely separately?

Every time you want to share a postman collection with other developers you also have to send them dependencies of the postman tests completely separately? 

Newman can't manage files it needs for its tests on its own?

Why isn't this being worked on?
