### ISSUE TITLE
Verbose output file is not logged in the end of execution

### ISSUE THREAD

**Issue by hantuzun** [postmanlabs/newman#414]
Verbose output file is logged at the end of execution like output file and html report.

options:
<img width="346" alt="screen shot 2016-06-03 at 12 43 24" src="https://cloud.githubusercontent.com/assets/2770895/15790888/e20c3cc2-2988-11e6-94ac-fb1b9a361c5b.png">

output:
<img width="423" alt="screen shot 2016-06-03 at 12 42 53" src="https://cloud.githubusercontent.com/assets/2770895/15790889/e20f52e0-2988-11e6-80de-768d5eda1dd2.png">

**Comment by shamasis** [comment]
The new v3 newman will have a JSON reporter which is always verbose!

**Comment by shamasis** [comment]
fixed in newman v3 - though the format is a lot different
