### ISSUE TITLE
Parent column is too narrow in execution summary

### ISSUE THREAD

**Issue by hantuzun** [postmanlabs/newman#415]
For our use case Parent names are longer than the space provided in summary table.

For example: 
<img width="438" alt="screen shot 2016-06-03 at 12 41 49" src="https://cloud.githubusercontent.com/assets/2770895/15790943/5a0d9d24-2989-11e6-8189-2c518291bf28.png">

This makes it harder to follow individual errors.

A solution can implement the followings:
 * Parent column may have a minimum number of characters. For example, 20.
 * Redundant `Folder` prefix could be removed.
 * `Pass Count` and `FailCount` could be renamed to `Pass` and `Fail`. This would save some space in the table and make it easier to read the numbers.
 * The whole table could have a maximum length like 80 characters.

I can work on this issue.

**Comment by shamasis** [comment]
Try the new newman v3 output - it has a tree style output owing to popular demand
https://github.com/postmanlabs/newman/tree/feature/v3
