### ISSUE TITLE
Response time of the first request in collection is longer

### ISSUE THREAD

**Issue by hantuzun** [postmanlabs/newman#416]
Response time of the first request in collection is around 200ms longer than the real request time.

Currently we work around this issue in our performance critical application by adding a dummy request on top.

**Comment by czardoz** [comment]
This is the DNS resolution happening. I don't see any way of working around this.

**Comment by emrehan** [comment]
I see. We can try to resolve all the domains in the collection initially. Would it worth the complexity it will bring?

**Comment by shamasis** [comment]
It is not just DNS... the TCP connection itself is established first time and cached next time onwards.

**Comment by kunagpal** [comment]
This is not a part of our current roadmap, but has been marked as a feature request and added to our internal tracker. We'll update this thread when any progress occurs on this. :)

**Comment by czardoz** [comment]
TCP connection pooling is implemented in https://github.com/postmanlabs/postman-runtime/blob/328f3ba050dee9ec2aa21efedebff895d1069915/lib/requester/util.js#L63

**Comment by shamasis** [comment]
@czardoz is this implemented and closed? If so, please remove the labels and close it.

**Comment by shamasis** [comment]
@hantuzun did the TCP pooling config change fix your issue?

**Comment by czardoz** [comment]
@shamasis Sorry, didn't see your ping. 
This is implemented and released. @hantuzun, feel free to re-open this issue if you're still facing it.
