### ISSUE TITLE
Newman says- "Error: read ECONNRESET" but postman test runs fine 

### ISSUE THREAD

**Issue by gauravphoenix** [postmanlabs/newman#425]
Using newman version "2.1.1" in a pretty standard way:

`newman -c myCollection.json -e myEnv.json
`
There is only one request in the collection which makes an HTTP POST to localhost:8080. 

When I run the test using PostMan Runner  everything works fine but newman gives error- 

```
Encountered an error during JSON.parse(): Unexpected token uRequestError: [82cea0cb-bd36-3d70-3a2e-a4ab937b2e27] 'login' terminated. Complete error:
Error: read ECONNRESET
    at exports._errnoException (util.js:855:11)
    at TCP.onread (net.js:544:26)
```
How can I debug this further? I tried using "-O" option but the file isn't created. When I use "-o" option I see output file being created but it doesn't have any relevant error details. 

Edit- 
The request in myCollection.json looks like this- 

`"url": "{{scheme}}://{{api_host}}/login"`

The variable {{scheme}}  and {{api_host}} are defined in in myEnv.json as  "http" and "localhost:8080" respectively

**Comment by czardoz** [comment]
What do your server logs say? That error is coming from Node, and your server seems to be closing the connection.

**Comment by gauravphoenix** [comment]
Server gives no error at all! I am running postman and newman side by side and postman and all other clients are working fine. Only newman is having trouble.

**Comment by gauravphoenix** [comment]
Just did a packet capture. I observe that when Postman makes connections, the request headers look like this- 


```
POST /login HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Content-Length: 64
Cache-Control: no-cache
Origin: file://
Content-Type: application/json
Postman-Token: 1391ff81-1d9d-edc1-f713-9d92e4b5ef1f
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US
```

When newman makes connection, the request headers are- 

```
POST /login HTTP/1.1
Content-Type: application/json
host: 127.0.0.1:8080
accept-encoding: gzip, deflate
content-length: 64
Connection: close
```

As you can see , the Connection header is being set to close. I think that is the culprit. 

My node version is v5.3.0

**Comment by gauravphoenix** [comment]
Thanks to docker for Mac, I was able to quickly spin off a docker container with node version v6.2.1 installed. Everything works fine with that version. 

I guess something is off with node HTTP client that comes with v5.3.0.

**Comment by shamasis** [comment]
Seems this is beyond our control as of now. Marking as closed.

**Comment by gauravphoenix** [comment]
Perhaps the newman documentation can be updated to reflect the fact the one must use node version 6+
