### ISSUE TITLE
Error running in Jenkins after upgrade to v2 format

### ISSUE THREAD

**Issue by qinfeng** [postmanlabs/newman#428]
after I upgrade the collection format to v2,  I got "Missing request: undefined" error when running the testing in Jenkins:

jenkins@f4ce0b0af0ee:~/jobs/postman_test/workspace$ newman -c grid_test.json.postman_collection
Missing request: undefined

**Comment by qinfeng** [comment]
Here are some details on the environment I was running the newman:

it's a jenkin container with node v4.4.5, npm 3.9.6, newman 2.1.1

**Comment by czardoz** [comment]
@qinfeng Can you share the collection file with help@getpostman.com? (If it contains sensitive information, feel free to remove those parts)

**Comment by qinfeng** [comment]
@czardoz the same error happens even i run against the default Postman Echo collection exported as v2. However, it works fine with default Postman Echo collection exported as v1.

**Comment by abhijitkane** [comment]
Could be related to https://github.com/postmanlabs/postman-app-support/issues/2143

**Comment by qinfeng** [comment]
@abhijitkane I am still using Postman 4.3.2 and don't have the folder issue mentioned in #2143

1. Postman Version: 4.3.2
2. App (Chrome app or Mac app): Chrome 51.0.2704.84
3. OS details: OS X / x86-64

I have no issue to run the test with newman in my local Mac terminal. I have the issue to run v2 collection exported from my local Postman App in my Jenkin Container with node v4.4.5, npm 3.9.6, newman 2.1.1

Anyway, I will run my test in v1 collection for now. Thanks for investigating the issue.

**Comment by shamasis** [comment]
@qinfeng both formats should work for now

**Comment by qinfeng** [comment]
@shamasis I still have the same error with newman 2.1.1. But it works with newman 3.0.1 after I upgrade newman in my jenkins container.

Anyway it works now, I'll close the issue. Thanks.
