### ISSUE TITLE
403 error when running tests via newman.

### ISSUE THREAD

**Issue by gerrymcgovern1** [postmanlabs/newman#430]
I am receiving a 403 error when attempting to run my tests via newman. The same tests run fine when I run them via the collection runner in Postman. We are using basic auth and my tests add the authorization header as a custom header. I have added the following to my tests in an attempt to glean more information:

`console.log(responseCode);`
`console.log(JSON.stringify(request.headers["Authorization"]));`

which results in the following when run via newman:

`Iteration 1 of 1`
`{ code: 403,
  name: 'Forbidden',
  detail: 'The request was a legal request, but the server is refusing to respond to it. Unlike a 401 Unauthorized response, authenticating will make no difference.' }`
`Basic  dGVzdF9hdXRvbWF0aW9uOjVhZTRjYWY2YjQ2Mjc1NDI1ZGI4MDlmOWU1NmRkOGIw"`

`403 266ms https://api-general.staging.companyname.com/data/user/2/venue/3/entity_type/V/campaigns/undefined 
[POST] https://api-general.staging.companyname.com/data/user/2/venue/3/entity_type/V/campaigns/undefined
    ✗ Status code is 200`

So the authorization header is added and seen by newman, but yet I get a 403. 

I have used the postman interceptor to create this test and this test is not currently using any global or env variables. Currently running newman from my mac(not a separate CI machine) which is the same machine as postman is running from so I don't believe it's a firewall issue.

Can anyone provide any insight into why this is occurring?

**Comment by abhijitkane** [comment]
@gerrymcgovern1 The message says the request was legal, so the auth header is probably being sent. Can you check why the server might return a 403?

**Comment by czardoz** [comment]
@gerrymcgovern1 Can you also add a `console.log(responseBody)` and see if the response contains any information about what is failing?

**Comment by gerrymcgovern1** [comment]
@abhijitkane - I can't figure out why it is returning a 403 hence the question here! Seems very odd as it passes using the Postman collection runner.

**Comment by gerrymcgovern1** [comment]
@czardoz - Hi, in the response body I get an "Unauthorized access token" message. I have edited my collection, to include 2 tests. The first test makes a request for an access token using valid credentials and gets a response with the access token. I then saved this token into a global variable and pass this in the body of my next test. Works fine via collection runner, but not in newman. I have also hardcoded passing a valid token (to ensure there was no problem with expired tokens in the global variables file) but same issue via newman. Please see below for the entire response I get. If you would like some more information please let me know!

`200 314ms Get access Token basic auth [POST] https://api-general.staging.companyname.com/access`

`{ code: 403,
  name: 'Forbidden',
  detail: 'The request was a legal request, but the server is refusing to respond to it. Unlike a 401 Unauthorized response, authenticating will make no difference.' }
undefined
{"errors":[{"message":"Unauthorized access token","errorType":{"message":"Unauthorized access token","stack":"Error\n    at Error.NoPermissionError (/var/www/libs/errors/NoPermissionError.js:3:18)\n    at authenticate (/var/www/server/middleware/clientAuth.js:28:23)\n    at allFailed (/var/www/node_modules/passport/lib/middleware/authenticate.js:87:18)\n    at attempt (/var/www/node_modules/passport/lib/middleware/authenticate.js:160:28)\n    at Strategy.strategy.fail (/var/www/node_modules/passport/lib/middleware/authenticate.js:277:9)\n    at Strategy.authenticate (/var/www/node_modules/passport-http-bearer/lib/strategy.js:113:29)\n    at attempt (/var/www/node_modules/passport/lib/middleware/authenticate.js:341:16)\n    at authenticate (/var/www/node_modules/passport/lib/middleware/authenticate.js:342:7)\n    at authenticateWithToken (/var/www/server/middleware/clientAuth.js:34:6)\n    at Layer.handle [as handle_request] (/var/www/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/var/www/node_modules/express/lib/router/index.js:312:13)\n    at /var/www/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/var/www/node_modules/express/lib/router/index.js:330:12)\n    at next (/var/www/node_modules/express/lib/router/index.js:271:10)\n    at initialize (/var/www/node_modules/passport/lib/middleware/initialize.js:62:5)\n    at Layer.handle [as handle_request] (/var/www/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/var/www/node_modules/express/lib/router/index.js:312:13)\n    at /var/www/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/var/www/node_modules/express/lib/router/index.js:330:12)\n    at next (/var/www/node_modules/express/lib/router/index.js:271:10)\n    at validateRequest (/var/www/server/middleware/validateRequest.js:11:3)\n    at Layer.handle [as handle_request] (/var/www/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/var/www/node_modules/express/lib/router/index.js:312:13)\n    at /var/www/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/var/www/node_modules/express/lib/router/index.js:330:12)\n    at next (/var/www/node_modules/express/lib/router/index.js:271:10)\n    at /var/www/node_modules/body-parser/lib/read.js:129:5\n    at invokeCallback (/var/www/node_modules/raw-body/index.js:262:16)\n    at done (/var/www/node_modules/raw-body/index.js:251:7)\n    at IncomingMessage.onEnd (/var/www/node_modules/raw-body/index.js:308:7)\n    at emitNone (events.js:86:13)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:926:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)","code":403,"errorType":"NoPermissionError"}}]}
`

**Comment by czardoz** [comment]
Hmm, there are a number of reasons why this could happen:

1. Are you using the Interceptor in Postman? If yes, are you logged in to some website which has set Cookies for this domain?
2. Do you need to use an environment with this collection? If yes, are you giving it to Newman?
3. Are you using any Auth helpers in your requests? If yes, have you saved the helper data to the request? (There's a checkbox in each Auth helper that allows you to save the Auth parameters in the request)

**Comment by gerrymcgovern1** [comment]
Hi, sorry about the delay in getting back to you on this, was on vacation.

And yes, I had used Interceptor for creating my tests. I re-wrote my test manually and it now works via newman! I believe your theory was correct regarding some cookies been set by Interceptor.

Thanks for your help!

**Comment by nuubis-mso** [comment]
Hi!

I'm sorry but would you mind posting how you got around this issue?  I'm having similar issues - PUT request (i.e. file upload in binary mode) works fine via Postman collection runner, but newman returns 403 Forbidden ("{ code: 403, name: 'Forbidden', detail: 'The request was a legal request, but the server is refusing to respond to it. Unlike a 401 Unauthorized response, authenticating will make no difference.' }").  I'm not using Interceptor - should I be?  --Thanks!

**Comment by gerrymcgovern1** [comment]
Hi nuubius

The issue for me seemed to be that Interceptor seemed to be setting some cookies that were not available when the tests were run via newman. I created a new test and using the dev tools in Chrome, grabbed the request URL, form data, access token etc and put them manually into my test. It then worked via newman. As you are not using Interceptor this probably is not much help to you.

**Comment by nuubis-mso** [comment]
Hi!

Thanks for the quick reply.  In Newman, I have the PUT requests in a loop using environment variables to control the looping and setting the values for urls/headers/body for each iteration in the loop.  Within this loop, some PUT request passes w/ no issues and others fail with 403.  This seems to be totally random.  When I manually run the loop within Postman’s collection, all the PUT requests pass with no issues, consistently.  So, I’m stumped - any lead on debugging this would be greatly appreciated.  Again, I’m not using Interceptor in Postman or Newman.

Thanks,
Maz So
Nuubis, Inc.

**Comment by czardoz** [comment]
@nuubis-mso Can you open a new issue? Your problem seems to be different than @gerrymcgovern1 

Also, it would be great if you could tell me:

1. The version and platform (Windows/OSX/Linux) of Postman you use.
2. Your Newman version. (`newman -v`)
3. How exactly are you using file uploads?

**Comment by nuubis-mso** [comment]
Sure - I’ll open up a new issue.  Thanks for the quick reply.

**Comment by nuubis-mso** [comment]
New ticket is #788.
