### ISSUE TITLE
Postman - newman responseBody

### ISSUE THREAD

**Issue by garylogin** [postmanlabs/newman#431]
Hi 
all works good in postman...but in newman I get this in as part of output log...
"tests": "//Convert the response to JSON\nvar jsonObject = xml2Json(responseBody);

Using this collection...
https://www.getpostman.com/collections/60634c131d78f0956559
the response is soap
it appears that in newman there is no responseBody returned.
Must be doing something wrong?

**Comment by czardoz** [comment]
@garylogin Your collection is missing the `Content-Type` header in every request. Can you try adding one? Usually the value should be `application/xml` :)

**Comment by garylogin** [comment]
fixed!
for a simple get on an html page I assume
Content-Type:text/html ?

**Comment by garylogin** [comment]
running through newman where does console.log() write to?

**Comment by garylogin** [comment]
thanks

**Comment by kunagpal** [comment]
@garylogin `console.log` will write to `stdout`. It appears that your issue has been resolved, and we're closing it on our end. Feel free to get back to us for any other queries / suggestions / issues you might have.
