### ISSUE TITLE
Scheduling tests/collections to run at various intervals

### ISSUE THREAD

**Issue by Singh400** [postmanlabs/newman#432]
I know I can export my requests/tests to a collection and run them via Newman, and I know I have some control over test execution. By using the `--number` and `--delay` arguments.

But I was hoping that I could just run a collection every x minutes indefinitely.

Many thanks,
Singh

**Comment by drpoggi** [comment]
Use [Cron](https://en.wikipedia.org/wiki/Cron).

**Comment by Singh400** [comment]
I saw that, but I was hoping that Newman could do it directly. Thanks though.

**Comment by czardoz** [comment]
There are no immediate plans to add something like this to Newman, there certainly are more elegant solutions like @drpoggi pointed out.

**Comment by Singh400** [comment]
Alright, that's fair.

Many thanks,
Singh
