### ISSUE TITLE
XmlHttpRequest() is not defined in Newman but works in Postman

### ISSUE THREAD

**Issue by IgnasiAA** [postmanlabs/newman#433]
Hi,
I have this snippet in my tests code in Postman for reading a file from local disk:

**_var ref_file = globals.referenceFileVTT;
var request = new XMLHttpRequest();
request.open("GET", ref_file, false);
request.send(null);_**

It works fine when launching the tests in Postman, but when I run the collection in Newman, I get the following error:

**_XMLHttpRequest is not defined_**

Any help on it?
Many thanks in advance!

**Comment by czardoz** [comment]
@IgnasiAA XMLHttpRequest is not supported in the Postman Sandbox, The only supported libraries and objects are documented here: https://www.getpostman.com/docs/sandbox :-)

**Comment by IgnasiAA** [comment]
Thanks @czardoz.
Do you know by chance if there is any way to read a file from you local disk using any of the supported libraries?
Thanks again!

**Comment by czardoz** [comment]
@IgnasiAA No, there's no way to do that in Newman. It's a security issue, allowing collections to read files. You could however spin up a small server,

```python -m SimpleHTTPServer 8080```

And add requests to get the files you need to use.

**Comment by IgnasiAA** [comment]
Many thanks again, @czardoz.
I got it working the way you said. I really appreciate your help :).
Cheers,
Ignasi

**Comment by czardoz** [comment]
Awesome!

**Comment by dmitry-gerasimov** [comment]
@czardoz In the test I need to download an image by URL and check that it's not empty. How can I do that without XMLHttpRequest?

**Comment by czardoz** [comment]
@dmitry-gerasimov You can create a new request in your collection with the proper URL, and then check whether `responseBody.length` is a non-empty string.

**Comment by czardoz** [comment]
For information on supported libraries inside the sandbox, check out https://www.getpostman.com/docs/sandbox
