### ISSUE TITLE
Newman not updating global variables

### ISSUE THREAD

**Issue by testkptest** [postmanlabs/newman#436]
Hi,
I am having problem with newman not updating global variables when i have response in html format.
It works fine when i run it thru postman but thru newman it is not updating global variables.
Could you please help !!

var doc = document.implementation.createHTMLDocument("none");
doc.documentElement.innerHTML = responseBody;
var value = doc.getElementsByClassName('test')[0].innerHTML;
postman.setGlobalVariable("var", value);

Thanks!!

**Comment by shamasis** [comment]
Hi,

Newman does not play well with HTML when used inside DOM since it is not a browser. Any chance you can achieve what you are using without DOM?

**Comment by shamasis** [comment]
Any update? Your script might be erroring out (due to DOM issues) before event it reaches the `setGlobalVariable` line. Can you check that?

PS: You should seriously consider moving away from DOM since we have already discontinued DOM. Newman v3 will not support it at all.

**Comment by kunagpal** [comment]
@testkptest: We're closing the issue due to inactivity. Please let us know if the issue still persists.
