### ISSUE TITLE
Is newman has problem with using 'localhost' as a host, but Postman can do fine

### ISSUE THREAD

**Issue by xenogew** [postmanlabs/newman#437]
Hello newman team

I have a problem with using `newman`. I try to follow your instruction, run `newman` with my `collection.json` and `env.json`.

But just the little different host name specific return different result, even it should be the same because I use '`localhost`' and '`172.31.98.128`'. That's my machine, it's the same, and yeah `Postman` can do it fine, or even call with my web browser, it can call without problem.

I attached the picture that show the result for what I found.
![newman-problem-with-localhost](https://cloud.githubusercontent.com/assets/756484/16686112/0980bc2a-453a-11e6-8747-2e4dd89865b4.PNG)

Node.js version 6.3.0 (and before this, I tried 4.4.2, it found the same problem)
Windows 7

I want to use the `newman` tool with my colleagues by sharing the code with Git. So this will make pain for sharing the same `environment.json` file that cannot use the same common environment file and must specific for each machine.

Hope you have any solutions for this.
Best Regards.

**Comment by czardoz** [comment]
@xenogew Your server is responding with a status code of 404. Can you add a 
```
console.log(responseBody)
```
to your test script and paste the output here?

**Comment by xenogew** [comment]
Here I found.

```HTML
<HTML><HEAD>
<TITLE>Network Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Network Error (dns_unresolved_hostname)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your requested host "localhost" could not be resolved by DNS.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">

</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>
```

And what after this is the same as the picture I posted before.

**Comment by czardoz** [comment]
This is a problem with your network configuration. You're probably using some sort of a firewall or proxy which is not able to resolve the DNS name "localhost".

**Comment by xenogew** [comment]
So how can I solve this?

And yes, my working network has proxy setting. Can you guide me like Google keyword, I'll try to find a way myself then.

Thanks for your help.

**Comment by xenogew** [comment]
I found it.

For everyone who may found same problem with me.
If you running `newman` under network with proxy setting.

Set the environment variable `NO_PROXY` with value `localhost,127.0.0.1` (or some kind like this)

Thanks very much to @czardoz who concern with my problem.
