### ISSUE TITLE
$timestamp is a different number of digits than in Postman

### ISSUE THREAD

**Issue by re010ma** [postmanlabs/newman#438]
I need a 10-digit, random, unique number that does not start with zero. Unix epoch time is perfect. When I run my collection in Postman, $timestamp returns a 10-digit number, like this: 1468271500. However, when I run the collection in newman, I get a 12-digit number, like this: 1468271587648. I can write a few lines of script to get what I want and pass it in on the command line. However, is there a way to do this without writing a script? Thank you.

**Comment by re010ma** [comment]
FYI, I worked around this by putting the following in my pre-request script:
'var my_timestamp = new Date();
postman.setEnvironmentVariable('phone', my_timestamp.getTime().toString().slice(0,10))'

**Comment by shamasis** [comment]
This is being addressed in upcoming newman v3.x. In fact it is already fixed there. Try it out if possible - https://github.com/postmanlabs/newman/tree/feature/v3

Once released, it will unify the underlying runtime of Postman and Newman. More info on the upcoming runtime at http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/

**Comment by shamasis** [comment]
Closing as of now. Please reopen if it is not fixed for your use case
