### ISSUE TITLE
Cyrillic is broken in Newman, but works fine in Postman

### ISSUE THREAD

**Issue by dmitry-gerasimov** [postmanlabs/newman#439]
I'm creating an environment variable in one request and I'm using it in another request as value of the "person" parameter. This is what the variable contains:
`"name_middle":"Александрович"`

When I run the request in Postman I see the following in the server logs:
`&person=%22name_middle%22:%22%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87%22`

That is the correct url encoding. But when I run it in Newman I get:
`&person=%22name_middle%22:%22;5:A0=4@>28G%22`

How can I make work correctly in Newman?

**Comment by shamasis** [comment]
This is being addressed in upcoming newman v3.x. In fact it is already fixed there. Try it out if possible - https://github.com/postmanlabs/newman/tree/feature/v3

**Comment by lts8989** [comment]
@shamasis I try it in newman v3.x .But it doesn't work.
Please test this bug again。

{{B_host}}black/index/test?param=Александрович

172.16.2.113 - - [08/Aug/2016:15:00:13 +0800] "GET /black/index/test?param=\x10;5:A0=4@>28G HTTP/1.1" 200 99 "-" "PostmanRuntime/2.2.5"

**Comment by shamasis** [comment]
@kunagpal - can you take this up?

**Comment by kunagpal** [comment]
@shamasis: Yes.

**Comment by shamasis** [comment]
@lts8989 can you send a sample collection file?

**Comment by kunagpal** [comment]
@dmitry-gerasimov @lts8989 Could you re-try with the latest release of Newman (v3.1.1)?

**Comment by dmitry-gerasimov** [comment]
@kunagpal Encoding looks good in v3.1.1. Thanks.

**Comment by kunagpal** [comment]
@dmitry-gerasimov 👍
