### ISSUE TITLE
Feature request:  Show subfolder names in the test run output

### ISSUE THREAD

**Issue by dmitry-gerasimov** [postmanlabs/newman#444]
There could be requests with similar names in different subfolders. Testing for different usage, fails, etc. So when you're looking into the long output to find out details of a failed test it's quite easy to loose context. Sectioning of the output by subfolder names would help a lot.

**Comment by shamasis** [comment]
This is addressed in v3 https://github.com/postmanlabs/newman/tree/feature/v3 closing
