### ISSUE TITLE
launch AWS API Gateway Postman export as collection gives no output

### ISSUE THREAD

**Issue by robizz** [postmanlabs/newman#454]
Hi,

I'm trying to automate my  AWS API Gateway testing using newman with a API GW Postman export json file.

I tried to launch the following command adding also global variables and method specific variable

newman -c dldxxxse-qa-postman.json -f v0 -e get_asset.postman_environment.json -g globals.postman_globals.json

with 

"dldxxxse-qa-postman.json" is the API GW postman export
"get_asset.postman_environment.json" is the method specific variable files exported from postman
"globals.postman_globals.json" is the global variable json exported from postman

but no output at all is returned by the command.
The same API GW postman export  loaded in postman works flawlessly with the same variables and params.

let me know if you need further details

cheers
Roberto

**Comment by czardoz** [comment]
@robizz Can you share your Newman version and your Node version?

**Comment by robizz** [comment]
@czardoz 

newman --version                                                                                                                                                                                                                     
2.1.2

node --version
v4.4.1

I noticed that the operation that I do in postman to execute an AWS API GW collection is to import the aws generated json via the "import" button

in fact an api gw postman export is totally different from an exported postman collection.

maybe am I missing something?

thanks!

**Comment by czardoz** [comment]
Yep, API Gateway exports a Swagger based format that Postman supports, not a collection file. 
You would have to import it into Postman, and export it from Postman, so that Newman understand the file :)

**Comment by robizz** [comment]
Ok, I did missed something :)
would be great if also newman could support the format, in this way I could automate the download of the export from api gw whenever change the API set / create a new one, and with the same json env globals and params launch the testing.

importing the collection and export it manually from postman introduces a manual step in the flow unfortunately! :)

is there something that is possible todo to have a workaround for this problem?

thakns a lot!

ROberto

**Comment by czardoz** [comment]
You could use this library to convert that file to a Collection before passing it to Newman: 
https://github.com/postmanlabs/swagger2-to-postman

There are no immediate plans to support running Swagger files directly though :)
