### ISSUE TITLE
newman does not update the aws token before sending request

### ISSUE THREAD

**Issue by robizz** [postmanlabs/newman#470]
Hello,

I have a problem launching newman using AWS Signature option to authenticate my call to my AWS API Gateway Endpoint. Configuring AWS access key and secret key as global variables in postman (exported for newman in the globals.postman_globals.json),and exporting the collection and launching it in newman I obtain this error

```
Response headers:
{
 "content-type": "application/json",
 "content-length": "114",
 "connection": "close",
 "date": "Mon, 25 Jul 2016 13:18:07 GMT",
 "x-amzn-errortype": "InvalidSignatureException",
 "x-amzn-requestid": "xxxxxx-526a-xxxx-8308-559ea66978e3",
 "x-cache": "Error from cloudfront",
 "via": "1.1 1215b20e825091002cc9421604422697.cloudfront.net (CloudFront)",
 "x-amz-cf-id": "JI_vREebTOOxovzl3phg3yPwXhCtjaItzgL7crXxeKmLIrAcS8YXVw=="
}
Response body:
{"message":"Signature expired: 20160725T125405Z is now earlier than 20160725T131307Z (20160725T131807Z - 5 min.)"}
```

the configuration regarding the api is the following (extracted from the postman_collection.json)
```

{
			"name": "v0",
			"description": "Folder for v0",
			"item": [
				{
					"name": "https://xxxxxxx.execute-api.eu-west-1.amazonaws.com/qa/v0/public/systems/:system_id/assets",
					"event": [
						{
							"listen": "test",
							"script": {
								"type": "text/javascript",
								"exec": "tests[\"Status code is 200\"] = responseCode.code === 200;\n\nvar jsonData = JSON.parse(responseBody);\ntests[\"return asset name\"] = jsonData.asset_name === 'original.jpg';"
							}
						}
					],
					"request": {
						"auth": {
							"type": "awsv4",
							"awsv4": {
								"accessKey": "{{aws_access_key_id}}",
								"secretKey": "{{aws_secret_access_key}}",
								"region": "{{region}}",
								"saveToRequest": true
							}
						},
						"url": "https://xxxxx.execute-api.eu-west-1.amazonaws.com/qa/v0/public/systems/{{system_id}}/assets",
						"method": "POST",
						"header": [
							{
								"key": "Content-Type",
								"value": "application/json",
								"description": ""
							},
							{
								"key": "Host",
								"value": "xxxxx.execute-api.eu-west-1.amazonaws.com",
								"description": ""
							},
							{
								"key": "Content-Length",
								"value": "1671",
								"description": ""
							},
							{
								"key": "X-Amz-Date",
								"value": "20160725T131600Z",
								"description": ""
							},
							{
								"key": "Authorization",
								"value": "AWS4-HMAC-SHA256 Credential=AKIAxxxxxxxxxx/20160725/eu-west-1/execute-api/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=2fdd94dfd523485fdf881fbd52ddeaa9f6ec91a0771b5a787bce55e014974365",
								"description": ""
							}
						],
						"body": {
							"mode": "raw",
							"raw": "{  ..omitted..  }"
						},
						"description": ""
					},
					"response": []
				}

```
Seems that newman does not update the aws token before submitting the request (in fact by clicking on "update request" in postman in the "Authorization section" and launching newman with the updated postman_collection.json the call to my API Gateway endpoint works but only for 5 minutes)

Am I missing something with the configuration maybe?

version details:
```
postman 4.4.3 on
linux / x86-64
Chrome 51.0.2704.103

newman 2.1.2
node v4.4.1

```
thanks a lot

Roberto

**Comment by shamasis** [comment]
What if you delete the headers before saving the request, then export and run in Newman?

**Comment by robizz** [comment]
@shamasis it worked thanks, removing all headers from requests and exporting makes newman regenerate correctly the token. 

Also this time I was missing something :) 

Thanks a lot

Roberto

**Comment by shamasis** [comment]
@czardoz in latest runtime do we override saved headers when it comes to AWS auth and other such auths?

**Comment by czardoz** [comment]
@shamasis yes

This has been fixed in Newman v3.0

**Comment by cbarrerah-sogeti** [comment]
I seem to be having an issue related to this, i get the following error:
  #  failure           detail                                                                          
                                                                                                       
 1.  TypeError         handler._sign is not a function                                                 
                       at request                                                                      
                       inside "PF_073_002_Send a Message to the Created queue / SendMessages to queue" 

When running the collection in newman , but works flawlessly in Postman.

Any hints?

**Comment by kunagpal** [comment]
@cbarrerah-sogeti This has been fixed in #1111, and will be rolled out with the next Newman release.

**Comment by cbarrerah-sogeti** [comment]
Ok, thanks. :)

**Comment by kunagpal** [comment]
@cbarrerah-sogeti Could you try this out with v3.7.6 and let us know if you're facing issues? 😄

**Comment by ankit-tripathi** [comment]
Hi All,

I have a very simple POST request to login to my application. Using Postman it works fine, but when I try to run it from Newman it gives error **handler._sign is not a function**.
![image](https://user-images.githubusercontent.com/9364431/38189482-017dbc62-367e-11e8-880a-51541d25eeaf.png)

My collection looks like this:
![image](https://user-images.githubusercontent.com/9364431/38189835-589d7a36-367f-11e8-9b72-a1ac870398f0.png)

NodeJs: 8.11.1
Newman: 3.8.2
Postman: 6.0.10

Please help!
