### ISSUE TITLE
The certificate is expired

### ISSUE THREAD

**Issue by zxning** [postmanlabs/newman#476]
In Mac OS X,  I want to capture https request from mobile，so  I  refer to the following page 
http://www.getpostman.com/docs/self_signed_certs

but, the certificate is expired

what should I do next????

**Comment by czardoz** [comment]
Hi, you can toggle off the certificate verification in Postman Canary: http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/

If you're using Newman, you can specify the `-k` or `--insecure` option on the command line to turn what SSL verification.

**Comment by zxning** [comment]
I want to using Postman Proxy to Capture https requests  from  Android Devices,  but ,according to the following:
http://blog.getpostman.com/2016/06/26/using-postman-proxy-to-capture-and-inspect-api-calls-from-ios-or-android-devices/

In Android Devices my app's request failed
