### ISSUE TITLE
Add Authorization Header to Each Request 

### ISSUE THREAD

**Issue by obender** [postmanlabs/newman#479]
Hi, 
At firs great job, very useful product.

I am wondering if there is an option to add a Header to each executed collection of postman ?

**Comment by czardoz** [comment]
If you add headers to your collection on the Postman UI, Newman will automatically use them. If your auth method is supported, you can also use https://www.getpostman.com/docs/helpers :)

**Comment by obender** [comment]
Yes, But I mean 1 Header per Collection , not add it to Each request by hand.

**Comment by czardoz** [comment]
Ah, that's not supported yet unfortunately, but we are working on inherited auth helpers. Will that solve the issue for you?

**Comment by obender** [comment]
Yes, 
If you wish I can assist to develop it.
