### ISSUE TITLE
The Chinese character can't display properly

### ISSUE THREAD

**Issue by zxning** [postmanlabs/newman#483]
In the cmd,  enter the following content:
newman -c XXXXX.postman_collection.json -H result.html

Because the collection  and  description used by Chinese character in the result.html，so，the result.html can't display properly(gibberish)

what should I do ?

**Comment by shamasis** [comment]
@zxning can you try with newman v3 (beta) and tell us if the output is readable?

```
$ npm install newman@next --global

$ newman run XXXXX.postman_collection.json --reporters cli,html --reporter-html-export result.html
```

If it does not work, please attach a scaled down sample collection.

**Comment by shamasis** [comment]
I had recently tested that Chinese and Russian characters rendered just fine in HTML for Newman v3. However for best compatibility, we should set charset UTF8 meta in head tag. 

@kunagpal 👆🏼

Closing this issue. Please reopen if the issue persists.
