### ISSUE TITLE
Exporting Postman tests containing "true" or "false" do not run as desired in Newman

### ISSUE THREAD

**Issue by PFarrell89** [postmanlabs/newman#522]
**Newman Version: 2.1.2**

Forgive me as I'm not massively technical:

I've been exporting my Postman test collections and running them using Newman for a couple of weeks now, however the issue below is one I always have to manually amend in a text editor. 

Would like some idea if this is a genuine issue with Newman or with something that I'm doing when exporting/writing my tests.

**Issue:**
The below conditions will fail in Newman, but run fine in Postman Chrome/Windows application:
```
if (environment.canCancel == \"true\")
if (environment.canCancel == \"false\")
```

Postman saves all environment variables as strings, so in a previous request I'm saving the Boolean as a postman variable, thus changing it to string and hence why the condition isn't written as:

`if (environment.canCancel == true)`

If I manually change the condition to the one above, the tests run correctly like Postman.

Thanks!

**Comment by kunagpal** [comment]
@PFarrell89 As a workaround, you could alter the given condition within the Postman Client test editor, like so:

```javascript
if (environment.canCancel == "true")
if (environment.canCancel == "false")
```

Exporting a collection with the above saved request (and it's corresponding environment file, of course), will maintain consistency with the type checks all over. Postman variables (environment, global, or data)  are stored as strings, which in turn may require intermediate processing to be used.

**Comment by PFarrell89** [comment]
Apologies!
That's exactly how I'm writing my tests in Postman as it converts variables to string.
`if (environment.canCancel == "true")`

When exporting the test collection from Postman it changes to:
`"if (environment.canCancel == \"true\")`

The tests in Newman fail at that point when they pass in Postman.

I've just re-tested this on Newman v3 and it's still occurring.

**Comment by kunagpal** [comment]
I see. I am unable to replicate this issue, could you share your collection and environment, sans the sensitive details?

**Comment by PFarrell89** [comment]
Hi, feel free to close this issue.
After updating to v3 this appears to be working fine now.
Thanks!
