### ISSUE TITLE
cannot upgrade to newman 3.0

### ISSUE THREAD

**Issue by wkuckro** [postmanlabs/newman#524]
Ubuntu 16.04, node v6.3.0

Already have newman 2.1.2 installed

Cannot upgrade to 3.0 using `npm upgrade newman --global:`

Attempted to remove newman and reinstall using `npm install newman --global;`  : still failure

**Comment by kunagpal** [comment]
Hey @wkuckro, could you provide more details on the error you faced?

**Comment by srbangre** [comment]
I am also facing this issue. 
i have windows 7 64 bit, newman installed 2.1.2

i don't receive any error. neither i am seeing any progress bar.
![image](https://cloud.githubusercontent.com/assets/16723968/17672870/7d8ed99c-62ec-11e6-8268-7e22b739484d.png)

**Comment by wkuckro** [comment]
with the 3.0.1 update, using `npm install newman --global;` now works on Ubuntu 16.04

**Comment by kunagpal** [comment]
@srbangre: Could you please re-try by running `npm i -g newman` with a command prompt / Power Shell instance opened in administrative mode?
