### ISSUE TITLE
Invalid xml generate if test name contains an ampersand.

### ISSUE THREAD

**Issue by leejoon** [postmanlabs/newman#526]
Suppose you gave a postman collection that starts with:
{
	"variables": [],
	"info": {
		"name": "This & That",
		"_postman_id": "c032ff0c-2480-62a1-c09f-24ef6c45bb89",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
....

After using newman to run the test and generate the junit report, the generated xml will have the fragment:
<testsuites name="This & That" ...

As a result, the unescaped ampersand results in invalid xml.

Expect:
The ampersand should be escaped to &amp;

**Comment by shamasis** [comment]
Which Newman version are you using?

**Comment by leejoon** [comment]
We are using newman 2.1.2

**Comment by shamasis** [comment]
This issue should already be addressed in v3 since we are building the XML as an object instead of string. Can you check if it works?

**Comment by leejoon** [comment]
I confirm that this is fixed in v3. Thanks for the quick replies!

**Comment by shamasis** [comment]
Thank you @leejoon. 😊
