### ISSUE TITLE
cannot pass --environment url

### ISSUE THREAD

**Issue by wkuckro** [postmanlabs/newman#536]
Where are --environment urls supposed to come from? Are they from the hosted environments in Postman?

Currently there isn't a way to create a URL link to an environment itself from Postman. I tried hosting my own .json file and it wouldn't pull that file from the URL either

**Comment by kunagpal** [comment]
@wkuckro: Environments specified as URLs need not necessarily be hosted on Postman, they can be any valid URL that returns a valid environment JSON. If possible, do send us the link to your remote environment, and we'll be happy to help you out.

**Comment by czardoz** [comment]
@wkuckro Environment URLs can come from the Postman Cloud API: api.getpostman.com

**Comment by wkuckro** [comment]
@czardoz THanks. Using the Cloud API, i was able to get it. might be useful to include that in your documentation for newman somewhere
