### ISSUE TITLE
empty globals file is generated when using --export-globals option

### ISSUE THREAD

**Issue by mykhaylo-** [postmanlabs/newman#537]
Hi
My collection has the following code in one of the tests:
``` javascript
var token = postman.getResponseHeader("x-auth-token");
postman.setGlobalVariable("x_auth_token", token);
```
When I run the following command
```bash
newman run -r cli,html -e pub_env.json --bail --export-globals globals.json https://api.getpostman.com/collections/808581-9c4c8735-e0bc-cd88-16f7-b7600d75f416?apikey=$API_KEY
```
newman executes my collection successfully and generates globals.json file. But it is generated without any global variables while I expect "x_auth_token" to be there:
```javascript
{
  "values": [],
  "_postman_exported_at": "2016-08-15T20:53:08.375Z",
  "_postman_exported_using": "Newman/3.0.1"
}
```
Please suggest.

**Comment by kunagpal** [comment]
@mykhaylo- Thanks for reporting this issue! A fix for this bug has been added within Newman `v3.1.0-beta.1`.

Please re-try exporting your run variables after installing Newman with `npm i -g newman@beta`, and let us know if your issue has been resolved.

**Comment by mykhaylo-** [comment]
@kunagpal many thanks. it works in v3.1.0-beta.1

**Comment by miguelC** [comment]
I am running into this issue with version 3.8.3 :(
