### ISSUE TITLE
[newman v3.0] X-CSRFTOKEN authentication not working 

### ISSUE THREAD

**Issue by snk20501** [postmanlabs/newman#540]
I usually login my RESTful Web with X-CSRFTOKEN header and token value. In v2.1.2, it works fine but not in v3.0.1. Please kindly refer to my test steps and help to advice.

[Test Steps]
Step 1. Provide username and password to RESTful Web to get "CSRFToken" value, then create a global var first.
`var data = JSON.parse(responseBody);`
`postman.setGlobalVariable("spx-rest-csrftoken", data.CSRFToken);`
Step 2. GET other Web resources with X-CSRFTOKEN header and "spx-rest-csrftoken" value I set in Step 1. .
Headers:
`X-CSRFTOKEN: {{spx-rest-csrftoken}}`
`Content-Type application/json`

Step3. always get "400 - Bad Request"

Thanks~

**Comment by snk20501** [comment]
Hi~ Anyone can help on this? Thanks~

**Comment by czardoz** [comment]
Hi, @snk20501 can you send a sample collection where we can reproduce the issue? I tried setting a header in a global variable and it worked fine for me :)

**Comment by snk20501** [comment]
Hi @czardoz , Thank you so much for the reply. The global variable setting works on my side, too. The issue I'm facing is the authentication mechanism via X-CSRFTOKEN doesn't work with v3.x Newman but  ok with v2.x or POSTMan. I use the same collection to get above result. Our RESTful API use X-CSRFTOKEN to build session. I send a mail with test collection attached to you. Please check the mail and let me know if you need more detail info. I'm not sure is this issue related to cookies.

Thanks for your kindly help again :) .

**Comment by snk20501** [comment]
Hi folks, 
I think I find the cause. When I create the test collection, I didn't remove content in request body even if I use "GET" method. Seems Newman v3 will always sent request body no matter which request method used. This might need to be addressed?

After I remove the body and re-export collection, issue fixed, so I close this issue. Let me know if any.
