### ISSUE TITLE
retry in case of failure

### ISSUE THREAD

**Issue by alowenst** [postmanlabs/newman#545]
Use case is using Newman as a monitor tool and tests to make sure that response code is correct, response time is reasonable and that response values are correct. 
In some cases, due to network hiccups or some other system conditions, some requests might end up with timeouts or incorrect values that will resolve if the same request was processed a few seconds later.
in such cases I would like to retry the same request x times with a Y timeout between requests. 
If an iteration pass after a retry, I would like the Newman exit code to be 0 (successful run).

**Comment by shamasis** [comment]
@alownst - I understand making this feature work if there is a timeout or other network level error, but retry based on incorrect response from server is something that is best done at your test level and then control the flow of collection using our workflow functions - https://www.getpostman.com/docs/workflows

**Comment by shamasis** [comment]
@alowenst 👆🏼

**Comment by kunagpal** [comment]
@alowenst This is not a part of our current roadmap, but has been marked as a feature request and added to our internal tracker. We'll update this thread when any progress occurs on this. :)

**Comment by rapidroamer** [comment]
@alowenst workaround using workflows as below:

`
Set Env vars as below:
retry-limit = 5
retry-counter = 0
retry-interval = 2000

Use this code snippet under Tests tab:

function pausecomp(millis)
 {
  var date = new Date();
  var curDate = null;
  do { curDate = new Date(); }
  while(curDate-date < millis);
}

if(failure-condition)
{
//needs retry
    if ( parseInt(environment['retry-counter']) <= parseInt(environment['retry-limit']))
    {
       postman.setEnvironmentVariable('retry-counter', parseInt(environment['retry-counter'])  + 1);
       pausecomp(environment['retry-interval']);
       postman.setNextRequest("CurrentRequestName");    
    }
    else
    {
        postman.setEnvironmentVariable('retry-counter', 0);
        console.log("Resetting, retry counter: to " + environment['swagger-retry-counter']);
        tests["Retries Expired"] = true === false;
    }
}
else
{
//doesn't need retry
    postman.setEnvironmentVariable('retry-counter', 0);    
//tests 
}

`

**Comment by obender** [comment]
This is what I Ended with:

```
function retryOnFailure(successCode, numberOfRetrys) {
    var execCounter = postman[request.name + '_counter'] || 0;
    var sleepDuration = 1000;
    var waitUntilTime = new Date().getTime() + sleepDuration;
    if (responseCode.code !== successCode && execCounter < numberOfRetrys) {
        while (new Date().getTime() < waitUntilTime) {
            // Do Nothing -> Wait
        }
        console.log('Retrying: ' + request.name + '\nGot: ' + responseCode.code + ' Expected: ' + successCode + '\nWaited: ' + sleepDuration / 1000 + 'sec ,Retry Number: ' + execCounter + ' of ' + numberOfRetrys);
        execCounter++;
        postman[request.name + '_counter'] = execCounter;
        postman.setNextRequest(request.name);
    }
}
```

**Comment by shamasis** [comment]
Closing this since programmatic approach is more feasible. And with the new setTimeout support in scripts, collection and folder level scripts and future plan to expose execution control from scripts, this issue should be addressed

**Comment by yakhira** [comment]
Solution/workaround is quite weird since tests fail anyway.

**Comment by glb** [comment]
@shamasis what should a person do if there is a timeout or other network-level error and we want to trigger a retry? I can't figure out where to tell newman to retry -- pre-request doesn't seem appropriate and the test script doesn't get run if there is an error making the request.
