### ISSUE TITLE
timeout-request option is not working with newman 3.0.1

### ISSUE THREAD

**Issue by rishivishnoi** [postmanlabs/newman#547]
I tried using the new available option 'timeout-request ' in place of '-r' with newman 3.X but its throwing error as "Unrecognized arguments" 

a) Using --timeout-request option with non zero value  -> Fails
argcmd = "newman -c PreCheckCollection.json -g GlobalInput.json --timeout-request 200 -S -C -x -O C:\out.log"

Error in logs:
8/18/2016 18:44:35,fsbkrestore,DEBUG,
08/18/2016 18:44:35,fsbkrestore,DEBUG,newman: error: Unrecognized arguments: --timeout-request 200.
08/18/2016 18:44:35,fsbkrestore,DEBUG,

b) Using --timeout-request option with zero value :  Supported in newman3.x but doesn't work
argcmd = "newman -c PreCheckCollection.json -g GlobalInput.json --timeout-request 0 -S -C -x -O C:\out.log"
 
Error in logs:
08/18/2016 14:39:37,fsbkrestore,DEBUG,
08/18/2016 14:39:37,fsbkrestore,DEBUG,newman: error: Unrecognized arguments: --timeout-request 0.

c)  Using -r option with zero value -> Fails [ This was working fine for newman 2.x ]
argcmd = "newman -c PreCheckCollection.json -g GlobalInput.json -r 0 -S -C -x -O C:\out.log"

Error in logs:
08/18/2016 18:46:29,fsbkrestore,DEBUG,argument "-r/--requestTimeout": Invalid <function> value: 0
08/18/2016 18:46:29,fsbkrestore,DEBUG,The value of iteration count must be an integer greater than zero

**Comment by czardoz** [comment]
@rishivishnoi 
Newman's CLI arguments have changed in v3.0, check the migration guide: https://github.com/postmanlabs/newman/blob/develop/MIGRATION.md

a) `--timeout-request` can be specified with the run options:
Example:
```
newman run PreCheckCollection.json -g GlobalInput.json \
     --timeout-request 200 --reporters json,cli \
    --reporter-json-export C:\out.log 
```
b) `--timeout-request` only works with the `run` subcommand, like above
c) I've created a fix for this. However, the value is assumed to be zero by default (which means that the requests will wait for an infinite amount of time to complete).
