### ISSUE TITLE
--export-globals possibly exporting in wrong postman format for Newman v3.0.1 

### ISSUE THREAD

**Issue by jangchoe** [postmanlabs/newman#553]
I noticed with the `--export-globals` option, I get a .json file in this format: 

```
{
  "values": [
    {
      "id": "user-email",
      "name": "user-email",
      "value": "email@mailinator.com",
      "type": "text"
    }
    // and so on.
}
```

shouldn't there be a `key` field instead of an `id` field? eg.
```
{
  "values": [
    {
      "key": "user-email",
      "name": "user-email",
      "value": "email@mailinator.com",
      "type": "text"
    }
    // and so on.
}
```

When I try to read the exported globals using `--globals <source>` it's not able to substitute the variables because it isn't using the `key` field.

**Comment by shamasis** [comment]
@jangchoe - we are fixing this. we also spotted that environment name is not exported. will fix that too

**Comment by kunagpal** [comment]
This has been fixed in https://github.com/postmanlabs/newman/pull/697, and shall be rolled out in a future Newman release.
