### ISSUE TITLE
GET request with access token/access token secret not working

### ISSUE THREAD

**Issue by nick2060** [postmanlabs/newman#555]
I've got a postman test which is not working on newman. All tests are OAuth 1.0, but this one is the only GET Request which uses the access token and I believe this is what I believe may be causing the issue.

So to add a bit more context, I run a test which gets the request token, and then another test which uses the request token to get the access token. I run a POST request that uses the access token, and this test works fine in both Newman and Postman. The next test however, is a GET Request with the access token and this test works fine on POSTMAN but for some reason it fails with a 401 forbidden on Newman.

Should also note the accessToken and accessToken secret are stored in environment variables. Has anybody else run into this issue? Did you find any way to fix this?

**Comment by nick2060** [comment]
1. I'm running the entire collection of tests which is inside a .json file with `newman run xxx.json`
2. Newman 3.0.1

**Comment by kunagpal** [comment]
@nick2060 Apologies for the delay, but does this issue still persist for you?

**Comment by nick2060** [comment]
@kunagpal Just re-tested this and can confirm it's still happening with Newman v3.1.2

**Comment by kunagpal** [comment]
@nick2060 Thanks for letting us know, we'll cross examine this on our end.

**Comment by kunagpal** [comment]
@nick2060 We're unable to reproduce this issue. Could you share your collection and environment file, without the sensitive details?

**Comment by nick2060** [comment]
@kunagpal Upon reviewing this issue on my end, I noticed the body of the postman collection had url-encoded parameters set which shouldn't have been there. Not sure where they came from, but upon removing them my test works fine in Newman. You can close this issue.

**Comment by kunagpal** [comment]
@nick2060 Do these parameters persist when re-exporting the collection from the Postman Client?

**Comment by nick2060** [comment]
Yes - really not sure where they're coming from but for now I will live with just removing them from the collection manually.


________________________________

**Comment by czardoz** [comment]
@nick2060 It's app's behavior that it adds auth information to the request when sent. This is to enable users to see exactly what is sent.

This is now redundant because of [Postman Console](http://blog.getpostman.com/2016/08/26/the-postman-console/), so we will be phasing it out over the next few releases :)

**Comment by maxherson** [comment]
Hello! Not sure is this the same problem, but all my get request have response 401 {"error_code":"UNAUTHORIZED","message
  │ ":"Invalid signature"}'
How can I add params to header like in POSTMAN https://goo.gl/iCfkDQ at newman
