### ISSUE TITLE
reporter summary is not correct

### ISSUE THREAD

**Issue by srbangre** [postmanlabs/newman#562]
cli reporter summary is not correct.
when i run collection having 15 requests, one of the request's assertion is failing. but in the summary report, it shows that the assertion failed = 1, but requests failed = 0. Shouldn't it be requests failed = 1 too?
see below - 
![image](https://cloud.githubusercontent.com/assets/16723968/17939778/21e9f346-69fa-11e6-97c4-25aabada3f4b.png)

**Comment by czardoz** [comment]
@srbangre, "request" in the summary refers to the actual HTTP request. If Newman had issues sending the request (connection errors, etc), those will show up in the failed request count.

**Comment by srbangre** [comment]
so in case of multiple assertions failure across tests, how will i make sure how many test cases are failed just by looking at the summary report?

**Comment by srbangre** [comment]
one more question - how do i run 2 folders in a collection? --folder folder1 --folder folder2 command is running only folder2

**Comment by shamasis** [comment]
@srbangre - maybe an assertion failure could mark its corresponding scripts as failed. But that would add no extra information than what you're getting now except whether tests failed in one request or in more than one. Also, in future we will have more than one script per request, that would further make it difficult to know if one request failed or more. Adding to that, using setNextRequest, a request can be executed more than once. That further complicates things. 

So, referring to the failure summary at the end is what provides maximum info. 

What could potentially help you if we add a feature where we summarise at a per-request level that can be turned on as a CLI switch. 

We should also add support for multiple folders. Let's split this into two appropriate feature requests.

**Comment by srbangre** [comment]
yeah i agree to your point above. 
thanks for your quick reply.  do you want me to close this one and create 2 feature requests or you can do it?

**Comment by shamasis** [comment]
I think you've already taken efforts to bring this to the notice of this community. 😊 Let me save you some time and will create two issues, link it here and then you can review whether I interpreted your issues accurately. 

Thanks again.

**Comment by bijoej** [comment]
Can we have a report with total number of assertions on each test script?
