### ISSUE TITLE
Add ability to run multiple folders

### ISSUE THREAD

**Issue by shamasis** [postmanlabs/newman#567]
Derived from #562. https://github.com/postmanlabs/newman/issues/562#issuecomment-242155183

```
one more question - how do i run 2 folders in a collection? --folder folder1 --folder folder2 command is running only folder2
```

**Comment by tomhall** [comment]
This would be very good - if it could also run the specified folders in the specified order too, even better.

**Comment by kunagpal** [comment]
This is not a part of our current roadmap, but has been marked as a feature request and added to our internal tracker. We'll update this thread when any progress occurs on this. :)

**Comment by shamasis** [comment]
https://github.com/postmanlabs/newman/issues/276 marking duplicate and closing
