### ISSUE TITLE
Add a request-level summarisation in CLI output

### ISSUE THREAD

**Issue by shamasis** [postmanlabs/newman#568]
Derived from #562 
https://github.com/postmanlabs/newman/issues/562#issuecomment-242157641

```
What could potentially help you if we add a feature where we summarise at a per-request level that can be turned on as a CLI switch.
```

**Comment by kunagpal** [comment]
This is not a part of our current roadmap, but has been marked as a feature request and added to our internal tracker. We'll update this thread when any progress occurs on this. :)

**Comment by kunagpal** [comment]
To be done via custom reporters: https://github.com/postmanlabs/newman#creating-and-using-custom-reporters
