### ISSUE TITLE
v3 Migration Guide doesn't mention --insecure flag

### ISSUE THREAD

**Issue by darrylkuhn** [postmanlabs/newman#574]
The [v3 Migration guide](https://github.com/postmanlabs/newman/blob/develop/MIGRATION.md) doesn't make mention of the insecure flag to interact with self signed certificates (e.g. `newman run collection.json --environment foo.json --insecure`) which is critical for us to allow developers perform testing on their sandboxes. So two questions?

 * Is this an option that is staying around?
 * Would you like me to up the guide and issue a pull request?

**Comment by kunagpal** [comment]
@darrylkuhn The `--insecure` option is indeed available, and has not been mentioned within the migration guide as it has remained unchanged during the transition from Newman v2 to v3. Please see the [list of available CLI options](https://github.com/postmanlabs/newman#newman-run-collection-file-source-options) for more details.

**Comment by darrylkuhn** [comment]
Fair enough - thanks for the quick response
