### ISSUE TITLE
Getting error:  newman run: error: Unrecognized arguments: --disable-unicode

### ISSUE THREAD

**Issue by umesh-bhalerao** [postmanlabs/newman#578]
I tried using the --disable-unicode option that replaces the --noTestSymbols option for V2 but I end up getting the following error:

C:\test>newman run mycollection.json -g myenv.json --disable-unicode --reporters json,cli --reporter
-json-export C:\test\out.log
usage: newman [-h] [--version] {run} ...

The command line Collection runner for Postman. More information:
https://github.com/postmanlabs/newman

Optional arguments:
  -h, --help  Show this help message and exit.
  --version   Prints the version and exits

Available Commands: (Use -h with each to see the supported arguments):
  {run}

newman run: error: Unrecognized arguments: --disable-unicode.

C:\test>

Following is the newman version.
C:\test>newman --version
3.1.0

I referred the following link for the new options:
https://github.com/postmanlabs/newman/blob/develop/MIGRATION.md

**Comment by umesh-bhalerao** [comment]
The unicode characters in the output breaks our logger that worked with newman 2.X, any update on this defect ?

**Comment by kunagpal** [comment]
@umesh-bhalerao We're working on a fix that works correctly, regardless of the presence / absence of unicode encoding support, please stay tuned for more updates.

**Comment by kunagpal** [comment]
@umesh-bhalerao This bug has been fixed in #593 and #597, and will be out in the next Newman release.

**Comment by umesh-bhalerao** [comment]
Thanks @kunagpal, when can we expect the next Newman release ?

**Comment by kunagpal** [comment]
@umesh-bhalerao A release is expected this week, I'll update this thread accordingly.

**Comment by kunagpal** [comment]
@umesh-bhalerao This bug should have been fixed in Newman `v3.1.1`, please check it out and get back to us if your issue persists. Thanks!

**Comment by umesh-bhalerao** [comment]
Thanks @kunagpal , I see most of the issues observed earlier fixed with Newman v3.1.1.
But in certain cases I still see a unicode character "?" in the output, in this case step3, step4, step5 pasted below.

The "--disable-unicode" switch was used in the newman command:

Command:
newman run TestCollection.json -g GlobalInput.json --export-globals RuntimeEnv.json --timeout-request 0 --no-color --disable-unicode --reporters json,cli --reporter-json-export log.json

Output:
Root step1
  POST http://XXXXXXXXXXXXXXXXXXXXXX
[200 OK, 309B, 343ms]
  Pass  step1

Root step2
  POST http://XXXXXXXXXXXXXXXXXXXXXX [404 Not Found,
605B, 15ms]
  1. step2

Root step3
  GET http://XXXXXXXXXXXXXXXXXXXXXX [504 Gateway Timeout, 7
44B, 1m 0s]
  2? SyntaxError in test-script

Root step4
  GET http://XXXXXXXXXXXXXXXXXXXXXX [504 Gateway Timeout, 7
44B, 1m 0s]
  3? SyntaxError in test-script

Root step5
  GET http://XXXXXXXXXXXXXXXXXXXXXX [504 Gateway Timeout, 7
44B, 1m 0s]
  4? SyntaxError in test-script

Root step6
  PUT http://XXXXXXXXXXXXXXXXXXXXXX [504 Gateway Timeout, 744B, 1m 0s]

Root step7
  POST http://XXXXXXXXXXXXXXXXXXXXXX
  Pass  step7

Root step8
  POST http://XXXXXXXXXXXXXXXXXXXXXX
  5. step8

Root step9
  PUT http://XXXXXXXXXXXXXXXXXXXXXX
  6. step9

Root step10
  PUT http://XXXXXXXXXXXXXXXXXXXXXX [504 Gateway Timeout, 744B, 1m 0.1s]

**Comment by shamasis** [comment]
@kunagpal @czardoz - we need to make print module do the Unicode replacement. Otherwise these teeny tiny Unicode items will keep cropping up.

**Comment by shamasis** [comment]
But before that we can address this single issue and push a fix?

**Comment by kunagpal** [comment]
@umesh-bhalerao @czardoz @shamasis Working on it

**Comment by kunagpal** [comment]
@umesh-bhalerao The reported issue was fixed in #634, and will be rolled out in the next Newman release.

**Comment by umesh-bhalerao** [comment]
@kunagpal When is the next Newman release scheduled ?

**Comment by kunagpal** [comment]
@czardoz :point_up:

**Comment by kunagpal** [comment]
@umesh-bhalerao Newman 3.1.2 comes with a fix for this issue, do go ahead and try it out.
