### ISSUE TITLE
HTML Reporter

### ISSUE THREAD

**Issue by Mkoopajr** [postmanlabs/newman#581]
So I'm not sure if this is a Windows issue or not. However I'm getting an error when running newman in the cli or as a node-module and using the html reporter. The cli and json reporters seem to be fine. The error is "TypeError: Expected a finite number" and seems to stem from the pretty-ms call [here](https://github.com/postmanlabs/newman/blob/develop/lib/reporters/html/index.js#L75).

**Comment by lightswitch05** [comment]
Getting this on a mac too - so not windows specific

**Comment by kunagpal** [comment]
@Mkoopajr @lightswitch05 The bug has been confirmed, successfully reproduced on our end, and fixed in #582. It should be added to the next Newman release.
