### ISSUE TITLE
Unable to specify multiple reporters

### ISSUE THREAD

**Issue by imthefrizzlefry** [postmanlabs/newman#583]
When I specify multiple comma separated reporters with newman 3.0.1 or 3.1.0, I get an error indicating the last reporter is an unrecognized argument.
Example command (altered collection and environment names):
`newman run .\My.postman_collection.json' --delay-request 4000 --environment .\My.postman_environment.json --reporters cli,html`

Output:
`newman run: error: Unrecognized arguments: html.`

- If I specify `--reporters html` alone it works
- If I specify `--reporters cli,html,json` I get the same error for "html json"
- If I specify `--reporters cli,html --reporter-html-export htmlOutput.html`, I get the same error
- OS Windows 7
- Terminal environment: Powershell and cmd
- Node version 4.4.5

**Comment by kunagpal** [comment]
@imthefrizzlefry In the command provided, there appears to be a stray `'` mark right after your collection file name.

**Comment by imthefrizzlefry** [comment]
That is because the original file name has a space in it.  I missed that when I changed the file name.  Please note that the command I ran does work properly if I only specify one reporter.

**Comment by kunagpal** [comment]
@imthefrizzlefry Could you re-try the command, but with quotes around the list of reporters, like so:
```terminal
newman run .\My.postman_collection.json --delay-request 4000 --environment .\My.postman_environment.json "--reporters cli,html"
```

**Comment by imthefrizzlefry** [comment]
so, the specific placement of the quotes you wrote didn't work, but when I moved the quotes around just the reporters (not including the parameter name) the command executed as expected.

`newman run .\My.postman_collection.json --delay-request 4000 --environment .\My.postman_environment.json --reporters "cli,html"`

**Comment by kunagpal** [comment]
Alright, that cold be thought of as a workaround, while we look for a better fix. Thanks a lot for informing us about this issue, we'll get back to you when we have updates on the same.

**Comment by imthefrizzlefry** [comment]
Yea, I think it works.  Also note that the README.md and MIGRATION.md files both contain examples that cause this issue.  I'm not sure if this is an issue you want to update the documentation for, or perhaps it is better to fix the issue.  I would be happy either way!

**Comment by shamasis** [comment]
It could be an argparse or Windows command interpretation difference - @czardoz
