### ISSUE TITLE
newman.run doesn't work in nodejs module

### ISSUE THREAD

**Issue by shaishab** [postmanlabs/newman#596]
I am trying to run newman.run from grunt task but it doesn't work. I tried

```
grunt.registerTask('postman-test', function() {
  newman.run({
    collection: require('./postman-tests/postman_collection.json'),
    environment: require('./postman-tests/postman_environment.json'),
    reporters: 'cli'
  }, function (err) {
    if (err) { throw err; }
    console.log(' Postman collection run complete!');
  });
});
```

no error shown and also not shown "Postman collection run complete!" what I am doing wrong. please help me 

also tried using promise:  [Stackoverflow question](https://stackoverflow.com/questions/39367385/newman-nodejs-module-does-not-work)

**Comment by kunagpal** [comment]
@shaishab By default, grunt treats all task registrations synchronously. Please follow  http://gruntjs.com/creating-tasks#why-doesn-t-my-asynchronous-task-complete for steps on how to fix this.

**Comment by shaishab** [comment]
yes now it's working :)

**Comment by kunagpal** [comment]
@shaishab That's great! We're marking the issue as resolved, feel free to get back to is if you face any other issues.
