### ISSUE TITLE
It shouldn't be possible to create GET-requests with a 'body'

### ISSUE THREAD

**Issue by max-preuschen** [postmanlabs/newman#599]
I had a couple of GET-requests failing with newman v3.1.0, which did work before with v2.1.2

I realised, that the GET-requests were failing, because the requests had a body specified in the collection:
```JSON
{
  "name": "Get request (with request body)",
  "request": {
    "url": "{{host}}/request",
    "method": "GET",
    "header": [],
    "body": {
      "mode": "raw",
      "raw": "{\n\t\"should_not\": \"have a body\"\n}"
    },
    "description": ""
  },
  "response": []
}
```

This happened by accident and took me quite some time to figure out, what was wrong.

This is how you can create a GET-request with a body:

1. Create a new POST-request in Postman and enter some value for the body
![screen shot 2016-09-08 at 17 25 26](https://cloud.githubusercontent.com/assets/3458659/18357677/bfcccaac-75e9-11e6-8e51-ef45522f35c3.png)

2. Then you change the POST-request into a GET-request
![screen shot 2016-09-08 at 17 26 32](https://cloud.githubusercontent.com/assets/3458659/18357709/de9ddafc-75e9-11e6-8184-5016ca046bcf.png)

3. The body is now greyed out, but if you export the collection, the GET-request will still have a body
![screen shot 2016-09-08 at 17 27 29](https://cloud.githubusercontent.com/assets/3458659/18357722/ea724ea8-75e9-11e6-8b4d-794f3923e097.png)

This didn't seem to be a problem before and I admit, it's kind of a user mistake and happens probably most often, if you copy a request with body and then change the request type without clearing the body manually.

But the question stands: **Does a GET-request with body even make sense?**
If yes: **Why is it greyed-out in Postman?**

**observed with:**
Postman v4.7.0 (Mac)
newman v3.1.0

**Comment by kunagpal** [comment]
@madebysid :point_up_2:

**Comment by madebysid** [comment]
@max-preuschen We've seen this issue before [here](https://github.com/postmanlabs/postman-app-support/issues/2308) and are working on a fix and it'll be out ASAP

**Comment by max-preuschen** [comment]
Great! 👍
Thanks for the reply.

**Comment by kunagpal** [comment]
@max-preuschen Closing, as this issue is related to the app, and not Newman. Please see https://github.com/postmanlabs/postman-app-support/issues for any other app related issues.
