### ISSUE TITLE
Error : Self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by chit786** [postmanlabs/newman#603]
Newman is throwing error using newman run <collection.json> -e <environment.json> command,

Getting error "SELF SIGNED CERTIFICATE IN CERTIFICATE CHAIN"

ut when I execute same collection in postman it runs perfectly.

![image](https://cloud.githubusercontent.com/assets/18376182/18380124/2cb1f0f2-7676-11e6-965a-c7db4ffe8a7a.png)

I am using Win7 - 32 bit machine 
Node version -  v4.5.0
npm version - 2.15.9

Please advice.

**Comment by czardoz** [comment]
@chit786 Try running Newman with the `-k` flag:
```
newman run <collection> -k <... other options>
```

**Comment by chit786** [comment]
Awesome it worked! Could you please advice if there is some info about this documentation.

**Comment by kunagpal** [comment]
@chit786 The complete set of available CLI options can be found at https://github.com/postmanlabs/newman#command-line-options.

**Comment by arikhaz** [comment]
Hi

How can run the command with javascript :
const newman = require ('newman');
....
...
collection : require('c:/tmp/aaa.json -k ) ,reporters:'cli'
...
..
It always failed , any suggestion ? 
Thanks

**Comment by priyaporwal2992** [comment]
newman run collection.json -k 

it worked for me too !!

**Comment by bibianabossio** [comment]
Excelente dato! Funcionó!

**Comment by samaronesilvadev** [comment]
> @ chit786 Tente executar Newman com a `-k`bandeira:
> 
> ```
> newman run <collection> -k <... other options...>
> ```

Ajudou muito!!!!
