### ISSUE TITLE
Allow async tasks in event callbacks

### ISSUE THREAD

**Issue by rmarczynski** [postmanlabs/newman#612]
My use-case is that I would like to perform some async tasks before each iteration, i.e. in the`'beforeIteration` event callback.  Specifically, I'd like to update the database so that it aligns with the iteration-data.  Currently there seems to be no way to pause the execution of an iteration's tests while we wait for the async task to complete.

**Comment by kunagpal** [comment]
@czardoz

**Comment by shamasis** [comment]
As of now you can set fixed delay between requests. But that's not ideal. Newman is running on an evented model - I would need to think deeper as to how your usecase can fit in. @czardoz i have an idea where we can do event third argument as a resolver function to resolve the event. However it has to be noted that it would be a total anti pattern for evented paradigm.

Thirdly, Can we do a .pause from inside events?

**Comment by czardoz** [comment]
Yep, we can to a `.pause()` inside events. That is actually a better solution than accepting a resolver function, since that essentially turns our events into callbacks.

**Comment by kunagpal** [comment]
@rmarczynski Asynchronous tasks in pre-request and test-scripts are supported in Newman v3.8.1, do go ahead and try it out 😄

**Comment by FCesar** [comment]
Hello everybody, I not understand, how to `.pause()` works .

In my case, I wish get data in my db on event "beforeItem" . But interaction not await query result and execute request. I wish that newman awaiting, before execute request

I use async/await
