### ISSUE TITLE
Async tests / libraries

### ISSUE THREAD

**Issue by soundstep** [postmanlabs/newman#615]
Feature request.
It would be nice to allow async tests.

```
var done = postman.done();
tests["Status code is 200"] = responseCode.code === 200;
// do something that takes time
done();
```

I give you a use case, if I need a library to do some special assertions, I would be able to load it using whatever it is running on (xhr, request).
For example, [tv4](https://github.com/geraintluff/tv4) has been included, but I might need other means of validation.
I could also look at [pact dsl](https://github.com/DiUS/pact-consumer-js-dsl).
This is just an example, async tests would extend the postman/newman testing capabilities greatly.
Any thoughts?

**Comment by czardoz** [comment]
+1

This is on our near-term roadmap. In fact, we've already [implemented it](https://github.com/postmanlabs/postman-runtime/blob/f6634b58e9adb655152a8abee40281fbd1efe030/lib/uvm/host.js#L114). There are some concerns about backwards compatibility that we want to address before allowing this functionality though :)

**Comment by czardoz** [comment]
Closing this in favor of #612
