### ISSUE TITLE
Encoded strings in response. Postman vs newman

### ISSUE THREAD

**Issue by samcayford** [postmanlabs/newman#630]
Rather than blather on, here is an example of the issue:

`tests["Message"] = jsonData.message == "Import Successful";`
return success in Postman, but fails in Newman. In Newman the string is encoded with + replacing the space.
In order to get the test to pass in both apps i had to do:
`tests["Message"] = jsonData.message.replace(/\+/g,  " ") == "Import Successful";`

Doesn't bother whether the string is encoded or not, but it should be consistent between Newman and Postman.

**Comment by shamasis** [comment]
What's jsonData? Is it `JSON.parse(responseBody)`?

**Comment by samcayford** [comment]
Yep!

**Comment by shamasis** [comment]
One more question - which version of postman and which variant (native or chrome)? And what's the version of Newman in question. 

@kunagpal can you reproduce it and see if new runtime is handling this?

**Comment by samcayford** [comment]
Run and exported using 4.7.2 Chrome app on windows. 
Newman was 3.1.1 also on windows.

**Comment by samcayford** [comment]
I don't see the issue on newman 2.1.2 on Windows either.

**Comment by shamasis** [comment]
Right. @kunagpal can you check whether the behaviour is same for Newman and postman native app on Windows?

**Comment by kunagpal** [comment]
@shamasis Checking.

**Comment by kunagpal** [comment]
@samcayford The collection below worked correctly within both: Newman and Postman. Could you share your collection (sans the sensitive details) with us?

```json
{
	"variables": [],
	"info": {
		"name": "response-consistency-test",
		"_postman_id": "e5c8d64f-7447-c7eb-cb2f-40fbecb8dee7",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "Consistency test",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": "var form = JSON.parse(responseBody).form;\n\ntests[\"Status code is 200\"] = responseCode.code === 200;\ntests[\"Form alpha is correct\"] = form.alpha === \"lorem ipsum\";\ntests[\"Form beta is correct\"] = form.beta === \"ipsum lorem\";"
					}
				}
			],
			"request": {
				"url": "https://echo.getpostman.com/post",
				"method": "POST",
				"header": [],
				"body": {
					"mode": "formdata",
					"formdata": [
						{
							"key": "alpha",
							"value": "lorem ipsum",
							"type": "text",
							"enabled": true
						},
						{
							"key": "beta",
							"value": "ipsum lorem",
							"type": "text",
							"enabled": true
						}
					]
				},
				"description": "A simple POST request to test the consistency of responses provided across different outlets of `postman-runtime`."
			},
			"response": []
		}
	]
}
```

**Comment by kunagpal** [comment]
Hey @samcayford, does this issue still exist for you?

**Comment by samcayford** [comment]
Sorry, i stopped using newman as i was encountering too many issues. It never stopped happening.

**Comment by kunagpal** [comment]
@samcayford We're sorry to hear that. Could we know more about your issues?

**Comment by shamasis** [comment]
Closing this issue. @samcayford - would really have loved to hear the specifics of your issues so that we can make things better for others with similar use case as yours.

I am available on Slack if direct chat is your thing. https://www.getpostman.com/slack-invite
