### ISSUE TITLE
reporter-junit-export does not handle directories

### ISSUE THREAD

**Issue by ractive** [postmanlabs/newman#643]
The documentation for the reporter-junit-export command line argument states:

> Specify a path where the output XML file will be written to disk.

When setting it to a directory with `--reporter-junit-export /etc/newman/foo`, newman reports:

> error writing file "/etc/newman/foo" for junit-reporter
> EISDIR: illegal operation on a directory, open '/etc/newman/foo'

If the directory does not exists, a file called /etc/newman/foo with the junit report gets created.

IMHO newman should handle the argument like:
- if it's a directory, create the files with the default naming scheme in this directory
- if it's a file, create the file with this name

**Comment by kunagpal** [comment]
Hey @ractive, thanks a lot bringing this issue to our notice, we're working on a fix for the same :)

**Comment by kunagpal** [comment]
Hey @ractive, the could you send us a command used to run the collection?

**Comment by ractive** [comment]
I use it with the newman docker image like:

If ~/devel/bla exists as a directory I get...
`docker run -v ~/devel:/etc/newman -t postman/newman_ubuntu1404 run --no-color -e stg.postman_environment.json --reporter-junit-export /etc/newman/bla -r cli,junit my.postman_collection.json`

> error writing file "/etc/newman/bla" for junit-reporter
> EISDIR: illegal operation on a directory, open '/etc/newman/bla'

**Comment by ractive** [comment]
If the ~/devel/bla directory does not exist, a file ~/devel/bla is created with the junit report.

**Comment by kunagpal** [comment]
@ractive I see. I'll take a closer look and get back to you.

**Comment by kunagpal** [comment]
Hey @ractive, could you try with the latest version to the `newman-docker` image?

**Comment by ractive** [comment]
Hi @kunagpal. The problem still exists:
```
[14:23:56] [~/devel]$ ls -l -d ~/devel/bla
drwxr-xr-x  2 james  staff  68 29 Sep 14:17 /Users/james/devel/bla
[~/devel]$ docker pull postman/newman_ubuntu1404
Using default tag: latest
latest: Pulling from postman/newman_ubuntu1404
f25e451100bc: Already exists
2dbe4abf311d: Already exists
7ae2bc99836a: Already exists
a3ed95caeb02: Pull complete
aba838e05dc4: Already exists
d4ea16786d0f: Already exists
a9d828dbe119: Already exists
3c4452bd2d92: Pull complete
Digest: sha256:3b261a5a5309ee2cafa07ab668f471ed4603df4ce255857e3514f3a6f8d43bfd
Status: Downloaded newer image for postman/newman_ubuntu1404:latest
[~/devel]$ docker run -v ~/devel:/etc/newman --rm -t postman/newman_ubuntu1404 run --no-color -e stg.postman_environment.json --reporter-junit-export /etc/newman/bla -r cli,junit Ratings%20and%20reviews.postman_collection.json
...
error writing file "/etc/newman/bla" for junit-reporter
EISDIR: illegal operation on a directory, open '/etc/newman/bla'
```

**Comment by kunagpal** [comment]
@ractive Could you try this command and see if it works for you?
```terminal
docker run -v ~/devel:/etc/newman --rm -t postman/newman_ubuntu1404 run --no-color -e stg.postman_environment.json --reporter-junit-export ~/newman/bla.xml -r cli,junit Ratings%20and%20reviews.postman_collection.json
```
(A file called bla.xml will be generated in `~/newman/`)

Under ordinary circumstances, `/etc/*` should not be written to, given that it is a system protected directory.

**Comment by ractive** [comment]
the file does not get created:
```
[15:21:38] [~/devel]$ docker run -v ~/devel:/etc/newman --rm -t postman/newman_ubuntu1404 run --no-color -e stg.postman_environment.json --reporter-junit-export ~/newman/bla.xml -r cli,junit Ratings%20and%20reviews.postman_collection.json
...
[15:21:45] [~/devel]$ ls -l ~/newman/bla.xml
ls: /Users/james/newman/bla.xml: No such file or directory
```
And there's no error message either...

**Comment by shamasis** [comment]
@kunagpal what's the status of this. cc @czardoz

**Comment by kunagpal** [comment]
@shamasis I believe this is blocked by https://github.com/postmanlabs/newman-docker/issues/29, specifying a mount volume for reports will help here.

**Comment by shamasis** [comment]
Maybe someone can send a PR.

**Comment by shamasis** [comment]
By the way, I think the original issue and this is not connected. 

Newman expects a file name for the export path. If user provide a directory, the feature request is to export the file inside that directory.

I think we already have an undocumented option to set the report directory for all reporters. I maybe wrong, need to verify.
