### ISSUE TITLE
Not able to generate HTML file Report

### ISSUE THREAD

**Issue by nitinEd** [postmanlabs/newman#645]
ran command
newman run /Users/nimeshshah/Desktop/api.edcast.com.postman_collection.json --reporters html --reporter-html-export

but didn't find any HTML report file in /usr/local/lib/node_modules/newman
   please help me out me with this

**Comment by kunagpal** [comment]
Hey @nitinEd, you would also have to provide a path for the HTML report to be created at, like so:
`newman run /Users/nimeshshah/Desktop/api.edcast.com.postman_collection.json --reporters html --reporter-html-export <path-to-html-report.html>`

If no path is specified, the report is generated within `/Users/nimeshshah/Desktop/newman`, and not within the installation directory of Newman itself.

**Comment by nitinEd** [comment]
Thanks for the info.But when I ran the above command I didn't get any HTML report and newman didn't run any test.
Please find the attached screenshot
![screenshot](https://cloud.githubusercontent.com/assets/19796842/18913773/583522f4-85a7-11e6-8c59-87db5a56b02b.png)

**Comment by kunagpal** [comment]
@nitinEd For the above command, no output us expected, as the CLI reporter was not specified along with HTML (`--reporters cli,html`). Also, there should have been a report generated in the directory from where Newman was run.

**Comment by nitinEd** [comment]
@kunagpal thnx buddy worked for me 👍

**Comment by edwinboy0312** [comment]
@kunagpal Hey is there anyway i can trim the name of the report generated to just 'newman-run-report' , i dont want the file name to be suffixed with the timestamp.

**Comment by kunagpal** [comment]
@edwinboy0312 You can append the `--reporter-html-export newman-run-report.html` option to your `newman run` command in order to achieve this.

**Comment by edwinboy0312** [comment]
@kunagpal Thanks ...It worked.
