### ISSUE TITLE
Newman OAuth1 Helper introduces non-compliant comma in header

### ISSUE THREAD

**Issue by tranhungt** [postmanlabs/newman#653]
Oauth spec requires that the Authorization header to be in the form

```
Authorization: OAuth realm="http://photos.example.net/",
                oauth_consumer_key="dpf43f3p2l4k3l03".........etc.
```

However, using the oauth1 helper, Newman sends the request with a comma behind the `OAuth` word, like so.

```
Authorization: OAuth, realm="http://photos.example.net/",
                oauth_consumer_key="dpf43f3p2l4k3l03".........etc.
```

Oauth1 Spec example header can be found at `Appendix A.5.3.  Requesting Protected Resource`:
https://oauth.net/core/1.0a/

**Comment by kunagpal** [comment]
@czardoz

**Comment by tranhungt** [comment]
I found that this only happens when I don't specify a "realm".

**Comment by czardoz** [comment]
@tranhungt are you still seeing this happen? It was fixed in https://github.com/postmanlabs/node-oauth1/commit/6bc1f3b544d74dbcbfe284a4ef7982da4171709f :)

**Comment by tranhungt** [comment]
It's good now, thanks @Cz!
