### ISSUE TITLE
Auto encoding of URL params while running collection through newman on Linux

### ISSUE THREAD

**Issue by numaanashraf** [postmanlabs/newman#664]
Issue moved from `postmanlabs/postman-app-support`. Originally filed by @seekdageek at https://github.com/postmanlabs/postman-app-support/issues/2376

> I am passing a URL parameter as {date} instead of {{date}} in a collection. Expected behavior is that the URL param {date} should be passed as it is. However when I am running the collection through newman, which is installed on Linux machine, the characters { and } are getting encoded.

**Comment by shamasis** [comment]
@czardoz can you look into whether this is a difference of behaviour in chrome and native?

**Comment by tormoseng** [comment]
I believe I more or less have the same issue on OSX, where I call solr with some query parameters. Within these parameters there are + e.g. to bind the queries with OR (example: q=(name:STA*)%2BOR%2B(foreignId:STA*) should be q=(name:STA*)+OR+(foreignId:STA*)). This is not happening on Postman - on did not either happen on Newman 2.0.7 (just recently updated to 3.2.0)

**Comment by czardoz** [comment]
This is definitely a bug, since we started forcibly encoding URL params (otherwise Russian/Chinese characters did not work). The problem lies here: https://github.com/postmanlabs/postman-request/blob/c4d2feb91c682b0aabd81f8fa5851aa3b3457fda/lib/url-parse.js#L21

**Comment by rkmax** [comment]
I think I'm having these encoding issues, my tests are working fine on postman I just exported json and write a variables.json file and all my test are failing 

![image](https://cloud.githubusercontent.com/assets/395707/21856760/26c4154e-d7f1-11e6-9f65-179b8646f82b.png)

**Comment by shamasis** [comment]
That's odd. The variable braces should not get encoded. Maybe your variables are not getting resolved and as such it is going like that to the URL. Can you check whether you are providing the environment with the variable `baseUrl` defined in it?

**Comment by rkmax** [comment]
I'm passing the envars.json file with the following structure

```
{
  "baseUrl": "http://localhost:8000"
}
```

I'm running the command in this way

    $ newman run --environment envars.json collection.json

**Comment by shamasis** [comment]
That environment file structure is not correct. If you export one from app or see an example in Newman repo, you'll see the correct JSON structure. 

See: https://github.com/postmanlabs/newman/blob/develop/test/fixtures/run/simple-variables.json

**Comment by rkmax** [comment]
thanks @shamasis I'll try with that format

**Comment by rkmax** [comment]
@shamasis now is working thanks

**Comment by shamasis** [comment]
Good to hear @rkmax

Just for general info. The original issue still persists and a fix is on its way. We are targeting of turning off any form of decoding on URL and doing a special encoding on Russian and Chinese character ranges.

**Comment by rapidroamer** [comment]
+1 for the #664 fix

**Comment by kunagpal** [comment]
This should have been fixed in the latest releases of the Postman app, and Newman.
