### ISSUE TITLE
econnrefused when running collection in newman

### ISSUE THREAD

**Issue by jburdeos** [postmanlabs/newman#666]
I am new to API, API testing and postman. ok so i have a collection of GET api tests that i created in Postman. There is no authentication and everthing (26 tests) is passing. However when i do "newman run https://www.getpostman.com/collections/xxxx" im getting the error 

> unable to fetch data from url https://www.getpostman.com/collections/xxxx. connect ECONNREFUSED xx.xx.xx.xxx : xxx <--- some kind of ip address

i tried exporting the collection and running it using the command "newman run xxx.postman_collection.json". it goes through the 26 tests but it fails. i get a message "401 unauthorized" on each tests. at the bottom, i get an AssertionFail. 

ive been racking my head trying to find a solution for 2 days now and i need some help/guidance. 

thank you.

npm version: 3.10.3
node version: 6.7.0
newman version: 3.1.2

**Comment by kunagpal** [comment]
Hey @jburdeos, please see https://github.com/postmanlabs/newman#using-newman-with-the-postman-cloud-api for details on using / running collections via postman links. Also, could you share the collection, sans the sensitive details?

**Comment by jburdeos** [comment]
hi @kunagpal . I just tried that, same error. here is the collection https://www.getpostman.com/collections/96d5a8a3aecfb61b1273

i have also set my https-proxy and proxy to "http://username:password@proxy:port", locally and globally

**Comment by kunagpal** [comment]
@jburdeos The base URL in the collection above appears odd, please confirm if it is meant to be that way. Newman does support proxy, please see https://github.com/postmanlabs/newman/tree/feature/proxy-readme-docs#proxy.

**Comment by jburdeos** [comment]
@kunagpal are you referring to "devtranspar1"? if so, yes, it is meant to be that way. it is an intranet site.  i clicked on the link you provided but im getting a 404 error.

**Comment by kunagpal** [comment]
@jburdeos The link has been updated, do go ahead and check it out.

**Comment by jburdeos** [comment]
@kunagpal i checked out the link. so i deleted the http-proxy and https-proxy from the config and set HTTP-PROXY and HTTPS-PROXY. i ran "newman run https://www.getpostman.com/collections/...." and i still get the "connect econnrefused" error. however, when i ran "newman run http://www.getpostman.com/collections/..." (http instead of https), i get the error "read econnreset". is this progress somehow or is it worse?

**Comment by kunagpal** [comment]
@jburdeos `read econnreset` could indicate a potentially unstable network connection, also, you mentioned that the tests work correctly without authentication. Please review your proxy link and see if it works correctly.

**Comment by jburdeos** [comment]
@kunagpal ok. ill go ahead and review the proxy link. thanks! ill keep you posted.

**Comment by kunagpal** [comment]
Marking this issue as resolved on our end :)
