### ISSUE TITLE
Using newman with postman-interceptor 

### ISSUE THREAD

**Issue by Abhikos** [postmanlabs/newman#685]

**Comment by czardoz** [comment]
@Abhikos This is not on our immediate roadmap, because it involves a number of things such as opening up a communication channel with the interceptor, authenticating it, etc. 

I will take this as a feature request though, and make sure we track it :)

**Comment by softbrada** [comment]
any updates on this? this would be really helpful. It is really a pain to debug failed tests right now when runing them with Newman
