### ISSUE TITLE
JUnit XML output does not conform to standard

### ISSUE THREAD

**Issue by mcdan** [postmanlabs/newman#687]
The output emitted by the JUnit reporter is not correct. It is missing a required attribute on the testsuite node, "tests". This per the xsd available here: http://llg.cubic.org/docs/junit/.

**Comment by mcdan** [comment]
This appears to be a regression around the refactor to v3 because other people report this working in v2.

**Comment by shamasis** [comment]
The associated PR is merged and is out for release. Thanks everybody.
