### ISSUE TITLE
tv4 schema cache will clear itself

### ISSUE THREAD

**Issue by snk20501** [postmanlabs/newman#719]
Version and environment information:
1. Newman Version (can be found via `newman -v`): v3.2.0
2. OS details (type, version, and architecture): Ubuntu Server 14.04 64bit
3. Are you using Newman as a library, or via the CLI? CLI
4. Did you encounter this recently, or has this bug always been there: seen from v3.1.1, but v3.1.0 works fine.
5. Expected behaviour: the schema was added by tv4.addSchemas() should exits until tv4.dropSchemas() executed.
6. Command / script used to run Newman: newman run "$i" --environment "$ENVIRONMENT_FILE" --insecure
7. Sample collection, and auxilliary files (minus the sensitive details):
8. Screenshots (if applicable):

Steps to reproduce the problem:
1. Create a new test collection in POSTMan.
2. Create two get request items in collection.
   COLLECTION_1
                        |- GET_Request_1 -> GET http://{{ip}}/redfish/v1
                        |- GET_Request_2 -> GET http://{{ip}}/redfish/v1
3. In GET_Request_1, write below test script to add reference($ref) schema used in DMTF ServiceRoot.v1_0_2.json schema by using tv4.addSchemas(). Then do the schema missing check.

```
tv4.dropSchemas();
for (var key in environment) {
    if(key.slice(0, 7) === "http://" && key.slice(-4) === "json") {
        tv4.addSchema(key, JSON.parse(environment[key]));
    }
}
var schema = {<ServiceRoot.v1_0_2_schema_content>};
var result = JSON.parse(responseBody);
var testResult = tv4.validate(result, schema);
var err2 = tv4.missing.length ? " | missing - " + JSON.stringify(tv4.missing) : "";
tests["All Schema found " + err2] = tv4.missing.length === 0;
```
1. In GET_Request_2, write below test script to do the schema missing check only.

```
var schema = {<ServiceRoot.v1_0_2_schema_content>};
var result = JSON.parse(responseBody);
var testResult = tv4.validate(result, schema);
var err2 = tv4.missing.length ? " | missing - " + JSON.stringify(tv4.missing) : "";
tests["All Schema found " + err2] = tv4.missing.length === 0;
```
1. Export test collection and run test collection by Newman.
2. Will see GET_Request_1 can't find any missing schemas, but GET_Request_2 does. All added schema was dropped after GET_Request_1 complete.
   ![1](https://cloud.githubusercontent.com/assets/21072491/19593577/d7979900-97b3-11e6-8b80-86f360998bd6.JPG)

**Comment by czardoz** [comment]
@snk20501 This is by design. We use an entirely different Sandboxed environment for each script, to ensure minimum interference.

**Comment by snk20501** [comment]
@czardoz Got it. Thanks for your explanation.
