### ISSUE TITLE
cannot install 3.2 in Ubuntu 16.04 

### ISSUE THREAD

**Issue by wkuckro** [postmanlabs/newman#723]
1. Newman Version (can be found via `newman -v`): Attempting install 3.2
 2. OS details (type, version, and architecture): Ubuntu 16.04 , Linux USER 4.4.0-22-generic #39-Ubuntu SMP Thu May 5 16:53:32 UTC 2016 x86_64 GNU/Linux
nvm 0.32.0
node 6.9.0
npm 3.10.8
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Recently
 4. Expected behaviour: should respond with newest version of newman
 5. Command / script used to run Newman: attempting to run `newman run https://www.getpostman.com/collections/{UID} --environment https://api.getpostman.com/environments/{UID}' gives me errors since it is looking for v 2.x options

Steps to reproduce the problem:
This may also be an npm issue, a dependency issue, a system setup issue and/or a newman issue. Please advise.

After install of either `npm install newman --global;` or `npm install newman@3.2 --global;` I get this and the subsequent resource tree.
```
/home/USER/.nvm/versions/node/v6.9.0/lib
└─┬ newman@3.2.0 
```

However, when you run `newman --version` you get `2.0.1`

This means I can't run newman 3.x collections

**Comment by kunagpal** [comment]
@wkuckro Please see https://github.com/postmanlabs/newman#using-newman-with-the-postman-cloud-api, you'll need to generate an API key as well.

**Comment by wkuckro** [comment]
@kunagpal The issue isn't the command. I just didn't want to post the API keys here. The issue is the _install_ of newman, not running newman itself. This worked on my OSX machines already when upgrading to 3.2 when it came out

**Comment by wkuckro** [comment]
Close this. I restarted my box for a third time, and ```newman -v``` now returns 3.2.0

**Comment by kunagpal** [comment]
That's great, thanks for letting us know!
