### ISSUE TITLE
Command line reporter does not provide detail for failed assertions

### ISSUE THREAD

**Issue by cdanielsen** [postmanlabs/newman#724]
Feature request: When a test assertion fails, it would be helpful for information/debugging purposes if Newman detailed the expected result vs. the actual result.

e.g. `Expected 'foo' and got 'bar'`

Currently, the reporter only relays the title of the test that failed, which explains what test failed, but not why.

**Comment by kunagpal** [comment]
@cdanielsen We've added this issue to our internal tracker, as it is not a part of our current roadmap. We'll be more than happy to keep you updated on it's progress, whenever any changes occur. Thanks for your contribution! :)

**Comment by shamasis** [comment]
What version of Newman are you on? The latest Newman outputs the exact request where test failed along with a tentative line number and test count position.

**Comment by cdanielsen** [comment]
I'm using 3.1.0, and the feature you're describing is helpful, but requires looking into the source, instead of immediately conveying why a test assertion failed in the reported output.

**Comment by shamasis** [comment]
Hmm. So, like Newman v2, v3 gives output of failed tests. If I'm not mistaken what you're saying is that just showing the name of the failing test in red is not enough indicator for the failure. 

If that's the case, then the only way to get better message of failure is to write more descriptive test name? Or consider the possibility of adding an assertion library in future? Am I thinking in right direction?

**Comment by passsy** [comment]
The output doesn't include the request (with all parameters) or the complete response. When something fails I have to run the request manually to find the problem. Most problems can be found with a glance at the raw request/response. 
Especially when running newman on the CI (every hour) a better output would be great. Sometimes errors disappear over time.

**Comment by kunagpal** [comment]
@cdanielsen Work on a better way to handle such cases is in progress, we'll update this thread when it's available. 😄

**Comment by shamasis** [comment]
This has been addressed using the new `pm.test` https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference

A test that looks like the following on URL that returns non 400 status, yields an output as appended:

```
pm.test('expect response be 40
0', function () {
    pm.response.to.have.status(400);
});
```

```
  #  failure                  detail

 1.  AssertionError           expected response to have status code 400 but got 200
                              at assertion:0 in test-script
                              inside "A simple GET request"
```
