### ISSUE TITLE
Is it possible to import csv or json file in pre-request script?

### ISSUE THREAD

**Issue by mahekmerchant** [postmanlabs/newman#728]
I have variables stored in csv file. Now I want to import that variables from csv file in pre-request script and set as environment variable. As my objective is to run this collection file in newman without passing environment file in command line. So is this approach possible?

**Comment by kunagpal** [comment]
@mahekmerchant You can use the `-d` CLI flag to pass your CSV file, which will be loaded as data variables (not environment). A sample command for your workflow would be as follows:

```terminal
newman run path/to/collection/file.json -d path/to/data/file.csv
```

**Comment by mahekmerchant** [comment]
ok. But can I import external files in sandbox?
eg 
import(filepath)
var j= data.name
postman.setGlobalVariable("name", "j");

**Comment by kunagpal** [comment]
Marking issue as resolved, feel free to get back to us for any other suggestions / concerns / issues you may have :)

**Comment by shamasis** [comment]
@mahekmerchant - let us know if you managed to get things working. 😊

**Comment by nitinEd** [comment]
Hi Kunal,

In above context how can I pass the environment variables to the collection.
$newman run path/to/collection/file.json  -d /path/to/QA.postman_environment.json --reporters cli,html --reporter-html-export

This is not working for Environment variables.

**Comment by kunagpal** [comment]
Hey @nitinEd, you'll have to have to use the `-e` flag, like so: 

```terminal
$newman run path/to/collection/file.json -e /path/to/QA.postman_environment.json --reporters cli,html --reporter-html-export
```

**Comment by Abhijitofss** [comment]
Hi @kunagpal ,

I am trying to run :-newman run D:\newman\ACMTestSuiteCreationpostman_collection.json -d  D:\newman\ACMwithLoanOrigination.csv

but getting error message: Invalid closing quote at line 2; found "\"" instead of delimiter ","

**Comment by Abhijitofss** [comment]
Hi @kunagpal ,

if i remove the -d & trying to run the command then its working but its not loading the  ACMwithLoanOrigination.csv file...

**Comment by kunagpal** [comment]
@Abhijitofss Looks like you have an unescaped double quote in your CSV file. If this is intentional, you can escape the double quote with a backslash, like so: `\"`

**Comment by Abhijitofss** [comment]
I have changed my payload accordingly ...but still facing the same issue...this is my json payload inside csv file 
{
   \"applicationCategoryName\":\"NEWACM3\",
   \"applicationCategoryDesc\":\"na\",
   \"productPreferences\":[
      {
         \"productCode\":\"WCAP\",
         \"productDesc\":\"Working Capital loan\",
         \"defaultValue\":\"Y\"
      }
   ],
