### ISSUE TITLE
Disabled header => TypeError Header name must be a valid HTTP Token ["//Authorization"] 

### ISSUE THREAD

**Issue by jmfayard** [postmanlabs/newman#729]
Hello, I have a request like this which was working just fine in Postman & the postman runner

![image](https://cloud.githubusercontent.com/assets/459464/19804900/881c65aa-9d11-11e6-98b5-c978af5aec00.png)

Running from newman gave me an error that had me puzzled

```
→ Register
  POST https://example.com/openapi/v1/user [errored]
....

01.  TypeError         Header name must be a valid HTTP Token ["//Authorization"]                                    
                        at request    inside "Register" of "Example"  
```

I found out that the collection (v2) export contains this

``` json
        {
            "name": "Register",
            "request": {
                "url": "{{base}}/openapi/v1/user",
                "method": "POST",
                "header": [
                    {
                        "key": "Accept",
                        "value": "application/json",
                        "description": ""
                    },
                    {
                        "key": "//Authorization",
                        "value": "{{admin}}",
                        "description": ""
                    },
                    {
                        "key": "//Content-Type",
                        "value": "text/html",
                        "description": ""
                    }
                ],

            }
        }

```

The problem here is the disabled headers `Authorization` and `Content-Type`, not used in the request but stored in the collection as `//Authorization` and `//Content-Type`. 

Removing them from the file fix the problem

My environment:

``` bash
$ echo 'newman -v && node -v && npm -v && mac info' | bash -x
+ newman -v
3.1.2
+ node -v
v6.9.1
+ npm -v
3.10.8
+ mac info
ProductName:    Mac OS X
ProductVersion: 10.12
BuildVersion:   16A323
```

**Comment by kunagpal** [comment]
Hey @jmfayard, this appears to be a bug within the app, as the field `"disabled": true` should also be included within the second element of the header array, like so:

```json
        {
            "name": "Register",
            "request": {
                "url": "{{base}}/openapi/v1/user",
                "method": "POST",
                "header": [
                    {
                        "key": "Accept",
                        "value": "application/json",
                        "description": ""
                    },
                    {
                        "key": "//Authorization",
                        "value": "{{admin}}",
                        "description": "",
                        "disabled": true
                    },
                    {
                        "key": "//Content-Type",
                        "value": "text/html",
                        "description": "",
                        "disabled": true
                    }
                ],
            }
        }
```

As a temporary workaround, you could manually include the `"disabled": true` field. Also, please open a bug report with a reference link to this issue at https://github.com/postmanlabs/postman-app-support/issues/new. Thanks for letting us know about this issue! :)

**Comment by jmfayard** [comment]
reported https://github.com/postmanlabs/postman-app-support/issues/2443

**Comment by little-boy** [comment]
I encountered this problem particularly when i export the collection to use it with newman, with "Headers" disabled but also with form-data disabled (in a POST request).

I cleaned my collection of all disabled properties to avoid getting errors with newman.

**Comment by jmfayard** [comment]
@little-boy I didn't have the chance to test it yet, but Postman 4.8.3 is supposed to have fixed the source of the bug as of https://github.com/postmanlabs/postman-app-support/issues/2443

**Comment by rajkbhawsar** [comment]
i encountered same issue when i used headers in quoted like below
"Content-Type":"application/json"
"Authorization":"Bearer  ***"
I Just removed the quotes and its working
Content-Type:application/json
Authorization:Bearer  ***

**Comment by shamasis** [comment]
It’s working most probably because of a gap in validation. Ideally it shouldn’t and would cause issues. Setting “disabled”: true in the json should work. Also this is an old issue for postman v4. It’s now in v7. If you’re facing errors, please file a new issue.
