### ISSUE TITLE
Response body of single item within a collection

### ISSUE THREAD

**Issue by zalow517** [postmanlabs/newman#730]
I want to get the response body of a single item within a collection which is specified by folder. Is that possible?

Currently if I try and get the response body after the requests are performed, I get back all of the responses from all items within the collection's folder.

The main issue is that these are not being saved in one array as objects, but separate objects which makes it hard to manipulate and target.

**Comment by kunagpal** [comment]
Hey @zalow517, at present, there is no configurable modifier that allows filtering one particular request's response. Parsing the verbose JSON collection run report (via `--reporters cli,json --reporter-json-export report.json`), and parsing the generated report to acquire the response body of your choice is the way to go. However, we can consider adding this in a future Newman release.

**Comment by zalow517** [comment]
@kunagpal Thank you for your quick and accurate response :)

**Comment by kunagpal** [comment]
@zalow517 You're welcome! We hope this helps you out. :)

**Comment by kunagpal** [comment]
Marking this issue as closed, as we have added it to our internal tracker. We'll keep you posted on it's progress, as it happens. Thanks for contributing! :)

**Comment by czardoz** [comment]
@kunagpal Re-opening this issue, so other community members can comment on the same issue without having to open a new issue every time.

**Comment by shamasis** [comment]
@zalow517 - you could use Newman as a node library and for the particular request, identify it and save its response manually. What say?

That's the only way to address it for now. Beyond that, in future anyone can develop this feature using the upcoming Newman custom reporter feature.

@czardoz seems like we should close this.

**Comment by zalow517** [comment]
@shamasis Yes that's exactly what I'm doing. The main issue here is that the response (when it contains more than one response - therefore multiple requests), is not comma-separated and therefore is not a proper object which I can manipulate easily. Here is an example of the output:

`{ sessionToken: 'ew0KICAiYWxnIjogIkhTMjU2IiwNCiAgInR5cCI6ICJKV1QiDQp9' }
{ customerId: '53b75d17-630b-40ca-a725-178886f271d4' }`

This is after parsing the summary.response.body through `JSON.parse`.

**Comment by zalow517** [comment]
I managed to find the data I want in isolation. I am now using on `done` instead of `request`. In this particular state, the summary contains the run executions which nicely store the response bodies in a well-structured object :)

**Comment by shamasis** [comment]
That's great. A heads up that we will soon make the executions object optional to save memory usage. It will become a flag that you'll need to add during run.
