### ISSUE TITLE
[FEATURE REQUEST] reuse codes in postman/newman

### ISSUE THREAD

**Issue by keithmork** [postmanlabs/newman#734]
For example, many of my tests look like this:

```js
tests[`[INFO] Request params: ${JSON.stringify(request.data)}`] = true;
let json;
try {
  json = JSON.parse(responseBody);
} catch (err) {
  tests['Expect response body to be valid JSON'] = false;
  tests[`[INFO] Response body: ${responseBody}`] = true;
  console.error(err);
}

if (json) {
  const { resultCode, resultMsg, detailMsg } = json;
  if (resultMsg) tests[`[INFO] Response body: ${resultMsg}`] = true;
  if (detailMsg) tests[`[INFO] Response body: ${detailMsg}`] = true;
  
  tests[`Expect "resultCode" to equal 1, actual: ${resultCode}`] = resultCode === 1;
}

// all APIs need codes like above : (

if (json && json.data) {
  const { accountNum, accountType, userId, userType, password } = json.data;
  tests['Expect "accountNum" to be string'] = typeof accountNum === 'string';
  tests['Expect "accountType" to be string'] = typeof accountType === 'string';
  tests['Expect "userType" to be number'] = typeof userType === 'number';
  tests['Expect "userId" to be number'] = typeof userId === 'number';
  tests['Expect "password" to be string'] = typeof password === 'string';
} else {
  tests['Expect response body to have "data"'] = false;
}
```

For now, all I can do is put those codes in globals:

![image](https://cloud.githubusercontent.com/assets/5634347/19879397/21c378ce-a02d-11e6-8d65-2c44e78daee7.png)

![image](https://cloud.githubusercontent.com/assets/5634347/19879385/0ab97e94-a02d-11e6-989c-1ef9b4b74aa3.png)

Otherwise it's a nightmare to write assertions like this: ( Imagine how many times you need to type `tests['blahblahblah'] = foo === bar` ...)

![image](https://cloud.githubusercontent.com/assets/5634347/19879403/2d12466a-a02d-11e6-95fc-21aca634cb65.png)

And sometimes we may even want to reuse the whole assertions above, as multiple APIs may return same object, e.g. user object, auth object etc.

### request

Need a place to store code snippets and can be called globally with something better than eval.

**Comment by czardoz** [comment]
This is coming soon. The route we've chosen is, we will allow having common scripts at the folder/collection level. 

Since each script runs independently of the others, there's little chance of having persistent functions defined across different scripts.

**Comment by x-iron** [comment]
Exciting feature, can't wait!

**Comment by kunagpal** [comment]
@x-iron You can use `postman.setNextRequest("list");` in the test script of the `add` request to achieve this. Please see https://www.getpostman.com/docs/workflows for more details.

**Comment by x-iron** [comment]
Hi @kunagpal, thanks for your info. but in my case:
step 1. list
step 2. add
step 3. list again
if I change to the following steps with work flow feature:
step 1. list
step 2. add then setNextRequest("list")

I think step 1 and step 2 will come into an infinite loop?

**Comment by kunagpal** [comment]
@x-iron Plainly setting the next request will indeed cause an infinite loop, but `postman.setNextRequest(null);` can be used to break out of the request cycle, based on a condition of your choice. For instance, the test script of the `add` request can have:

```javascript
postman.setEnvironmentVariable("flag", true);`
```

Within the test script of `list`, you could use the following logic:

```javascript
if (postman.getEnvironmentVariable("flag")) {
    postman.setEnvironmentVariable("flag", "");
    postman.setNextRequest(null);
}
```

**Comment by anugupta007** [comment]
@czardoz any update on reusing the test code?

**Comment by kunagpal** [comment]
@anugupta007 Apologies for the delay, we're in the process of polishing the user experience for collection and folder level entities. Thanks for all your patience 😄

**Comment by kunagpal** [comment]
@anugupta007 @keithmork @x-iron Newman v3.9.0 supports collection and folder level auth and scripts. These can be set within v5.4.1 of the Postman app and above 😄
