### ISSUE TITLE
Set next request in Newman

### ISSUE THREAD

**Issue by duyetmai** [postmanlabs/newman#750]
Hi,

I'm trying to set next request in Newman in Event Handle of request event not IDE (Because of some issues,I don't want to put the next request in a collection). 
.on('test', function (err, args) {
if(requestName == "Login"){ 
    postman.setNextRequest("Check Token Status");
}
However, it doesnot work. Could you please assist me?

**Comment by czardoz** [comment]
@duyetmai Can you give more information about how you're using `setNextRequest`? Your request has to be a part of the collection you are running in order to be used with `setNextRequest`.

**Comment by duyetmai** [comment]
Hi, 
My request is apart of the collection. Because i wanted to re-use the code ,i decided to put the  Test (the script run after sending request) including postman.setNextRequest into the the new man instead into IDE of Post Man

**Comment by kunagpal** [comment]
Hey @duyetmai, could you share your collection, and other associated files, the command used to run the collection, the operating system, and the Newman version (obtained by `newman -v`)?

**Comment by duyetmai** [comment]
Hi,
My version is 3.2.0, windows 7, 64bit
Actually, i just need if we have anyway to set next request, set global variable value in the comandline of node js not via IDE of postman. 
In IDE of postman we can use "postman.setNextRequest("Check Token Status");" or "postman.setEnvironmentVariable("parent_object", responseData). But how about in command line of node js. I used postman.setNextRequest("Check Token Status") but node js does not understand. I tried to read newman library and found that in postman-runner we have object PostmanApi and we have same method with postman object in postman IDE. However i don't how to call it so that i can use it such as PostmanApi.setEnvironmentVariable?

Thanks

**Comment by kunagpal** [comment]
Hey @duyetmai!

To start off, the `postman` object is not available for use within the Node CLI, so what you have described would simply not work.

In order to utilise the `postman` sandbox object, you would have to use it within collection request scripts, like pre-request and post request scripts. Please see the sample here: https://github.com/postmanlabs/newman/blob/develop/test/integration/super-sandbox-test.postman_collection.json#L327, this should provide some clarity on `postman` object usage. 

With the `postman` references in your collection file, you can proceed with using Newman as usual:
```terminal
newman run collection.json <other options>
```

or if you prefer, using Newman as a library
```terminal
var newman = require('newman');

newman.run({
   collection: 'path/to/collection/file.json'
}, function (err, summary) {
   if (err) {console.error(err);}
   else {
     console.info('Collection run was successful!');
  }
});
```

**Comment by duyetmai** [comment]
Dear kunagpal,

Thank for your fast answer. I know this way. However, as i said before, i don't really want to put every thing in collection file/Postmand IDE because we cannot reuse code and import some external library.
That's why I want to customize it to use in command line. So how about PostmanApi in  postman-runtime (not runner sorry). Is there anyway to call it out or define it and use it?

**Comment by czardoz** [comment]
@duyetmai There's no way to use the postman API outside of the script sandbox right now. 

One way of getting around this, is to use the [Postman SDK](https://www.npmjs.com/package/postman-collection) and update your collection before actually running it.

**Comment by duyetmai** [comment]
Thanks for your answer czardor. Actually i know Postman SDK. I tried to create/modify a collection before. However i suppose that it cannot help me to solve this issue. I just want to modify global variable/ set next request during my test run. If you can, could you please give me some suggestions/hints to implement it. I just think perhaps i will write the value which i want to set to global variable to a file and write a script to read data from that file and embeded this script as a global variable in request part of the collection and. After getting this value, in the request we will assign this value to global variable. Do you think that it is possible?

**Comment by duyetmai** [comment]
Hi czardoz,
Firstly, Thank you for your great support. I really appreciate it.
Secondly, because i really need to change environment  variables in order to proceed my project, could you please tell me some ways to read file from postman-api.js. I suppose that i can find solutions to overcome this issue by modifying something in postman-api.js file. Unfortunately, i cannot read file in postman-api.js. For example, when i put something like "var data = require('./variable.json');" in postman-api.js, it does not work.  

I really need your help this issue. 

Thank you very much.

**Comment by duyetmai** [comment]
Thank czardoz. I hope that it will be a new feature in future.

**Comment by shamasis** [comment]
Closing this.
