### ISSUE TITLE
report location path

### ISSUE THREAD

**Issue by galak06** [postmanlabs/newman#759]
i am not able to set the report path. 
-o d:\reports\......

**Comment by kunagpal** [comment]
@galak06 The `-o` CLI option has been deprecated. The right command would be something like this:
```terminal
newman run collection.json -r json,cli --reporter-json-export d:\reports...
```

Please see the [Newman v2 to v3 migration guide](https://github.com/postmanlabs/newman/blob/develop/MIGRATION.md) for more details.

**Comment by galak06** [comment]
Thanks for the fast response
