### ISSUE TITLE
HTML reports doesn't have the console output details.

### ISSUE THREAD

**Issue by Freakishmahesh** [postmanlabs/newman#763]
1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by kunagpal** [comment]
Hey @Freakishmahesh, welcome to the Newman GitHub issue tracker :)

At present, the following details are present in both: the console reports, and the HTML report as well:

* The name of the collection being run.
* Total and failed iterations, requests, test scripts, prerequest scripts, and assertions.
* The URL, average response code, response size, test details, and response size (across all iterations) for every request.

The following details from the console output are **not** present in the HTML report:
* Total run duration
* Total data received
* Average response time across all requests.

Does this cover everything, or are there additional details that you were looking for?

**Comment by kunagpal** [comment]
@Freakishmahesh A quick update: With the above pull request, total run duration, total data received, and average response times have been added to the HTML report. Please let us know if there's anything else you had in mind as well :smile:

**Comment by Freakishmahesh** [comment]
@kunagpal 
Verified and am still, not getting the messages that I give inside console.log. Ex : if(status_message=="success"){
consle.log("Passed")
}
else{
consle.log("FAIL")
}
If I get the console.log messages printed in ma reports, would be convenient. Isn't it?

**Comment by kunagpal** [comment]
Yes, we could consider adding a special section for console logs, where applicable.

**Comment by Freakishmahesh** [comment]
Yes. Right.! In case of printing list of names that we get in response, we might not be able to achieve with the tests[] thing.
var people=jsonData.students;
for(var i=0;i<=people.length;i++){
            console.log(i+1+"Student name is -->:"+people[i].name);
        }
 Please correct me, if I'm wrong.

**Comment by kunagpal** [comment]
@Freakishmahesh Yes, that sounds about right. Another possible option is to allow a collapsible section for responseBody, as has been requested in #712

**Comment by kunagpal** [comment]
@Freakishmahesh Although this isn't supported by default, you can accomplish the same with custo reporters: https://www.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman#custom-reporters
