### ISSUE TITLE
Can I modify environment variables in any events of Newman?

### ISSUE THREAD

**Issue by duongnapham** [postmanlabs/newman#767]
Hi,

I have a question about Newman feature. It is great if someone helps me make clear it
I need to automation both API above in NodeJS using Newman as library. I can not develop code directly into Postman tool because we need to use external library to support our project. My scenario just want to test Login and Logout API
1- Call Login API to get authorization string.
2- Call Logout API to revoke the authorization string from Login API.
I used some environments to transfer variables (authorization string) between Login and Logout API. In addition, I have used the Postman tool to generate collection that contains Login and Logout request.
When calling the newman.run in nodejs, I have use 
  + 'prerequest' event : assign data into the request.
  + 'request' event: get response data, handle our business and assign authorization to environment of postman.

My issue is:
 I can not modify environment variables in request event.

My question is: Can I modify environment variables in any events of Newman?

My environment is below:
1. Newman version 3.2.0
2. OS detail: (Windows 7)
3. I am using Newman as a library

Thanks,

**Comment by czardoz** [comment]
Hi @duongnapham this is not possible currently. This is basically the same as #750, so I am closing this, and tracking the issue there :)
