### ISSUE TITLE
--disable-unicode does not change Console.log output

### ISSUE THREAD

**Issue by larsmeldgaard** [postmanlabs/newman#770]
When using the `--disable-unicode` option, the output should only consist of non-unicode characters.

However if I use something like this in a test:

`var jsonData = JSON.parse(responseBody);
console.log(jsonData);
`

...the output has a left margin with a straight line. This look great in CLI, but not-so-great in a ascii text logfile from vsts.

![image](https://cloud.githubusercontent.com/assets/16798392/20464482/70e53486-af48-11e6-8337-5329882cb68c.png)

In the sample picture, you can see that the "Pass" is written as letters - not the unicode checkmark, but the Console.out is still Unicode.

Example command line:
`newman run postman_collection.json --reporters cli --disable-unicode`

**Comment by kunagpal** [comment]
Hey @larsmeldgaard, thanks for bringing this to our attention. We've added a fix on our end, this will go out in the next Newman release. :smile:

**Comment by kunagpal** [comment]
@larsmeldgaard This has been fixed in Newman `v3.3.1`, do go ahead and check it out :smile:

**Comment by larsmeldgaard** [comment]
Awesome! Kudos to the team.

**Comment by kunagpal** [comment]
:grin:
