### ISSUE TITLE
ReferenceError in test-script while  running  newman   https 

### ISSUE THREAD

**Issue by KristinaGu** [postmanlabs/newman#774]
Hi,I have a postman collection which runs fine from postman. In the script, i have some tests that do  some basic validations on the responseData.
But when launching it with newman in my machine, i get error as: "ReferenceError in test-script".

Kindly give a solution.
Thanks,

In detail:

 1. Newman Version : 3.3.0
 2. Mac 10.10.5
 
**Error Snapshot:**
![image](https://cloud.githubusercontent.com/assets/9940156/20595001/3f034240-b273-11e6-8053-44dd946585ec.png)

but it  gets correct responsebody,And i set it into next interface as a paramater ,and the interface is ok

![image](https://cloud.githubusercontent.com/assets/9940156/20595304/6037d830-b274-11e6-9d0e-db084d893a4a.png)

command :newman run /Users/Kristina/Downloads/12.postman_collection 

**Below is the snippet of test written for the microservice validation:**

var jsonData = JSON.parse(responseBody);

postman.setEnvironmentVariable("Authorization", jsonData.token_type +" "+jsonData.access_token );

tests["Status code is 200"] = responseCode.code === 200;

Hope this helps.

**Comment by czardoz** [comment]
Hi, it looks like your server uses a self signed certificate. You need to specify `-k` options with newman:
```
newman run <collection> -k ... <other options>
```

**Comment by KristinaGu** [comment]
@czardoz  thanks a lot 。I  have solve this question by your answer.
