### ISSUE TITLE
When used environment variable to compare the response, failed to compare.

### ISSUE THREAD

**Issue by Freakishmahesh** [postmanlabs/newman#776]
Ex : If a id value is set as environment variable and tried to compare the response with the environment variable, failed.
Enviroment variable : id and value is newman

When the request is sent, in response, we get the Id value

In tests, if we use like tests["Id value matched"]=JsonData.properties.id=="{{id}}";

The above failed, although in the response, we get the Id value as newman.

**Comment by kunagpal** [comment]
Hey @Freakishmahesh, use `postman.getEnvironmentVariable` to access environment variables in test / pre-request scripts, like so:

```javascript
 // set JsonData here
 tests["Id value matched"] = JsonData.properties.id === postman.getEnvironmentVariable("id");
```

**Comment by Freakishmahesh** [comment]
Thanks @kunagpal . It worked.
