### ISSUE TITLE
Can we skip a particular network request from execution, in a collection? postman.setNextRequest is to swich to some request. Byt here I need to skip particular request from execution.

### ISSUE THREAD

**Issue by Freakishmahesh** [postmanlabs/newman#777]
1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by kunagpal** [comment]
Hey @Freakishmahesh, `postman.setNextRequest` can help achieve request skipping as well. Consider the following workflow:

1. A collection has three requests, A, B, and C.
2. You decide to skip request B, say. (Or any intermediate lying request, for that matter).
3. The test script of request A would include a `postman.setNextRequest("C");`.
4. Thus, request `B` would never be run.

This will not work if you wish to skip the first / last request in a collection, however.

**Comment by kunagpal** [comment]
@Freakishmahesh How did this go for you? :thinking:

**Comment by Freakishmahesh** [comment]
@kunagpal Thank you for words. As you said, cannot skip first/last in a collection. Even if setNextRequest("C"), I cannot see anywhere in the reports that Request B has skipped :(

**Comment by kunagpal** [comment]
That's odd. How exactly did you use `postman.setNextRequest`? Please check out the following example collection in Newman, and the Postman collection runner:

```json
{
	"variables": [],
	"info": {
		"name": "skipped-requests",
		"_postman_id": "3ae56cc9-f7dd-f70d-f1c0-45d19fbf32e3",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "A",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"tests[\"Status code is 200\"] = responseCode.code === 200;",
							"postman.setNextRequest(\"C\");"
						]
					}
				}
			],
			"request": {
				"url": "https://echo.getpostman.com/get?val=a",
				"method": "GET",
				"header": [],
				"body": {
					"mode": "formdata",
					"formdata": []
				},
				"description": "This request always runs first"
			},
			"response": []
		},
		{
			"name": "B",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"tests[\"Status code is 200\"] = responseCode.code === 200;"
						]
					}
				}
			],
			"request": {
				"url": "https://echo.getpostman.com/get?val=b",
				"method": "GET",
				"header": [],
				"body": {
					"mode": "formdata",
					"formdata": []
				},
				"description": "This request is always skipped in the collection runner / Newman"
			},
			"response": []
		},
		{
			"name": "C",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"tests[\"Status code is 200\"] = responseCode.code === 200;"
						]
					}
				}
			],
			"request": {
				"url": "https://echo.getpostman.com/get?val=c",
				"method": "GET",
				"header": [],
				"body": {
					"mode": "formdata",
					"formdata": []
				},
				"description": "This request always runs last"
			},
			"response": []
		}
	]
}
```

**Comment by Freakishmahesh** [comment]
I didn't see information about skipped requests details in the command prompt summary . What do I expect is to have, requests count and names of skipped requests.
┌─────────────────────────┬──────────┬──────────┐
│                         │ executed │   failed │
├─────────────────────────┼──────────┼──────────┤
│              iterations │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│                requests │        6 │        0 │
├─────────────────────────┼──────────┼──────────┤
│            test-scripts │        6 │        0 │
├─────────────────────────┼──────────┼──────────┤
│      prerequest-scripts │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│              assertions │        5 │        0 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 15s                       │
├───────────────────────────────────────────────┤
│ total data received: 3.45KB (approx)          │
├───────────────────────────────────────────────┤
│ average response time: 2.3s                   │
└───────────────────────────────────────────────┘

**Comment by kunagpal** [comment]
@Freakishmahesh Well, this would be a good addition to Newman, thanks for bringing this up! :+1:

**Comment by hkgill** [comment]
+1

**Comment by jayanthktn** [comment]
I don't want to run request C. 
How can i do that ?
Req : A, B and C
@kunagpal

**Comment by kunagpal** [comment]
@jayanthktn In the test script of request `B`, you can add the following statement:
```js
postman.setNextRequest(null);
```

**Comment by jayanthktn** [comment]
Thanks @kunagpal

**Comment by shamasis** [comment]
This will be taken up as part of execution control support in scripts

**Comment by qb-sneha** [comment]
How to skip the execution of request A ?

**Comment by zMacu** [comment]
I need to skip request A and B for de 2nd iteration. How can I do it? Please help

**Comment by SumaVeeranna** [comment]
Is there a way to skip Req A and Req B  for the 2nd iteration and only execute Req C  ?

**Comment by remy90** [comment]
> This will be taken up as part of execution control support in scripts
Is there an issue reference that can be shared here to track for support for this feature?

**Comment by Hima2021-rajesh** [comment]
Hi ,

I need to Skip the request from collection, I dont want to use postman.setNextRequest. if any possible solution please help!
