### ISSUE TITLE
Error "newman :command not found" while execute shell script in jenkin Job

### ISSUE THREAD

**Issue by nitinEd** [postmanlabs/newman#778]
![screen shot 2016-11-25 at 3 39 45 pm](https://cloud.githubusercontent.com/assets/19796842/20621696/7bdbb690-b325-11e6-8294-988d9097f6b6.png)

Steps:
1.Started Jenkins on localhost.
2.Create Job-->Select Freestyle project-->Add Build step-->Exceute shell-->Enter "newman run PATH/to/collection -r html,cli"
3.Build now

Result is in attached screenshot.
-->Newman: command not found

newman version: 3.2.0
OS : OSX yosemite 10.10.5
jenkins: 2.19.3

**Comment by nitinEd** [comment]
Had some issues with PATH
changed to this PATH=/usr/local/bin:$PATH newman -v

**Comment by kunagpal** [comment]
That's great @nitinEd, have a good one!

**Comment by jltoo** [comment]
@nitinEd I also replicated the issue you've mentioned here. How did you fixed it? I didn't get how to setup the PATH.. A step for fixing this would really help. Thanks in advance.

**Comment by jltoo** [comment]
Nevermind. I figured it out now.

1. Go to Jenkins > Configure Jenkins > Search for Environmental Variables
2. Add the env PATH /usr/local/bin:$PATH newman -v

**Comment by songxing10000** [comment]
it works
![image](https://user-images.githubusercontent.com/10040131/37952758-77650afc-31d3-11e8-846d-7e5ce9b29a07.png)

**Comment by yavkurt** [comment]
Thanks it works

**Comment by pgroot91** [comment]
So much trouble and no clear answers on the web and then i stumbled upon @jltoo comment and solution. Thanks that work like a charm! 👍

**Comment by Htamoukraytt** [comment]
anybody can help me out it dose not work for me i am using mac , thanks
