### ISSUE TITLE
 Executing concurrent requests

### ISSUE THREAD

**Issue by duyetmai** [postmanlabs/newman#780]
Hi,
I'm using Newman as library.

In the past, it is impossible because postman is just a plugin of chrome 
https://github.com/postmanlabs/postman-app-support/issues/493

Now Newman makes postman collection work without chrome. 

So can we  execute concurrent request now? I would like to use postman/newman in load test.

**Comment by kunagpal** [comment]
Hey @duyetmai, please see https://github.com/postmanlabs/newman/blob/develop/examples/parallel-collection-runs.js for an example of parallel collection runs.

**Comment by stofte** [comment]
Is there any actual support for parallel execution, esp the report generation aspects? That script is hardly much better then a batch file, and you stilll need to agg. the data you care about yourself.

**Comment by duddu** [comment]
@stofte If you are still interested, please review this PR which tries to introduce proper concurrency: https://github.com/postmanlabs/postman-runtime/pull/867
