### ISSUE TITLE
Output is confusing in html report when timed out

### ISSUE THREAD

**Issue by keithmork** [postmanlabs/newman#785]
(Newman 3.2.0, node 6.9.1, win 10)

I used to use data files and use this to print params in the report:

```
tests[`params: ${JSON.stringify(request.data)}`] = true;
```

Sometimes the tests fail with odd results

![image](https://cloud.githubusercontent.com/assets/5634347/20694641/926f2ef6-b621-11e6-8284-091925f8d5c2.png)

It's due to timeout but **my boss always blames ME for passing the wrong params in the data file**

Yes I can see `ETIMEOUT` and `ESOCKETTIMEOUT` in console log but my boss won't do that.  He only checks the html report.

proof: (set timeout to 10ms)

![image](https://cloud.githubusercontent.com/assets/5634347/20694782/9dfc2214-b622-11e6-8f62-d8d125dc0430.png)

pls fix this   : (

**Comment by kunagpal** [comment]
Hey @keithmork, a value of 10 ms for `--timeout-request` is far too low, please consider removing it altogether, or increasing it to something like `5000`, at least.

**Comment by keithmork** [comment]
@kunagpal that's just a test to locate the problem.  I used to set 15000 and now I set 60000 in production.

The real problem is, as mentioned above, whenever there's a time out, my boss blames me because no useful info is shown on the html report.

It would be nice to have something to indicate whether a time out has occurred in the html report, as it's the most common exception.

**Comment by shamasis** [comment]
@kunagpal - we get error message from runtime when things time out. we can do something on the html reporter around this.

**Comment by kunagpal** [comment]
@keithmork Apologies for the delay, this is being worked on in https://github.com/postmanlabs/newman/pull/1584
