### ISSUE TITLE
responseTime and responseBody result in "ReferenceError in test-script" when timed out

### ISSUE THREAD

**Issue by keithmork** [postmanlabs/newman#786]
(Newman 3.2.0, node 6.9.1, win 10)

Even if `Tests` contains any of these, the tests will throw `ReferenceError in test-script` when timed out.

```
tests[`WTF!!`] = responseBody || false;

tests[`WTF!!`] = responseBody != null;

tests[`WTF!!`] = responseBody ? true : false;

if (!responseBody) {
  // xxx
}
```

Same is true for `responseTime`

"Thanks" to this, my boss thought I didn't write any assertions...

![image](https://cloud.githubusercontent.com/assets/5634347/20695114/b81fb51e-b624-11e6-9cae-207371608115.png)

For now, I use this to work around it.   
But it will be much better to have a better official html report template.   : )

```
tests[`server does return something before timeout`] = postman.getResponseHeader('Content-Type') || false;
```

**Comment by kunagpal** [comment]
Hey @keithmork, welcome to the Newman GitHub issue tracker!

A few points: :smile:

1 `tests` is an object used to specify test assertions. Adding duplicate keys (`WTF!!`, in this case) will effectively **overwrite** previously added tests. So, please use unique values for test names. You'll see the right number of assertions after making this adjustment.

2. `ReferenceError in test-script`s are understandable, as there will be no `responseBody` to work with when a request times out. If your endpoint times out often, please consider using a higher value of `--timeout-request`.

3. In your last example (`tests['server does return something before timeout']`), I understand that you are trying to check if the request was made successfully. It would be more appropriate to use the `responseCode`, like so:
```javascript
tests[`Status code is 200`] = responseCode.code === 200;
```

Hope this helps!

**Comment by keithmork** [comment]
1. Oops, I meant any of those checks, but thx : )

![image](https://cloud.githubusercontent.com/assets/5634347/20700643/86e36a66-b649-11e6-8548-7be971df9a34.png)

2. 👍

3. Alas, `responseCode.code` doesn't work

![image](https://cloud.githubusercontent.com/assets/5634347/20700799/633a11cc-b64a-11e6-9615-2529b5f89cfa.png)

**Comment by kunagpal** [comment]
In this case, `--timeout-request` has been set to `10`, which is far too low. Consider removing it altogether, or increasing it to something like `5000`.

**Comment by keithmork** [comment]
@kunagpal I intentionally set it to 10ms to reproduce the problem.  In production it's 15000.
This number is not important because sometimes it may take forever to get a response(eg. service is dead)

It's vital for CI and test automation that the report should contain enough info for developers to find the root cause, and for managers to grasp the testing progress, without having specific knowledge of the test framework itself (ie. dig deep into the console logs with thousands of lines).

IMHO this html report file as-it-is is sort of unusable : (

**Comment by czardoz** [comment]
I think, if a request errors out (it could be a timeout, connection error, anything), there should be an indication of that in the HTML report :thumbs-up:

**Comment by shamasis** [comment]
I have one more point here. Even if things timed out, is it okay to have RefeferenceError? Instead, should the global variables not be set to undefined (or whatever appropriate to indicate timed out)? By that, scripts will not error out and will fail tests properly.

**Comment by shamasis** [comment]
HTML reporter should expose more info around the error.

**Comment by shamasis** [comment]
Update on the issue. Since 2017, a lot has changed.

1.  The new pm.* functions have superceeded the global variables concept. Functions are easier to test and trap errors for, unlike global variables.
2. Work is in progress to configure scripts to be run even on network error of requests

The above two combined, this issue will be auto addressed.
