### ISSUE TITLE
Newman does not handle encoded url parameter values correctly

### ISSUE THREAD

**Issue by NoBaloneyTony** [postmanlabs/newman#792]
1. Newman Version (can be found via `newman -v`): 3.3.0
 2. OS details (type, version, and architecture): Windows 10
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: started using newman recently
 4. Expected behaviour: to duplicate result in Postman api
 5. Command / script used to run Newman: newman -c json_postman_collection.json
 6. Sample collection, and auxilliary files (minus the sensitive details): 
 7. Screenshots (if applicable):

1. Run Postman JSON collection which includes a GET request for a url encoded value (e.g. 'B%26B') using Postman Runner.
2. Run above Postman collection using Newman.
3. Newman incorrectly responds with a 400 Bad Request Error.

Identical collections were run. The problem described specifically relates to an individual GET request in Newman as Postman handles the GET request correctly by returning a 200 OK response whereas Newman complains with a 400 Bad Request error.
![newman](https://cloud.githubusercontent.com/assets/4326856/20774772/e015ee7a-b7ab-11e6-916f-21978a0fd745.PNG)
![postman](https://cloud.githubusercontent.com/assets/4326856/20774487/a5fa4570-b7aa-11e6-83e7-bc5277a17798.PNG)

**Comment by rodrigogs** [comment]
+1

**Comment by X-Benedict** [comment]
+1

**Comment by shamasis** [comment]
This should be resolved in latest Newman and Postman app combination.
