### ISSUE TITLE
Feature Request: Ability to get the values of Environment variables in html-reporter-template-data.json

### ISSUE THREAD

**Issue by Vijayabaskar03** [postmanlabs/newman#796]
It would be great if there is a way get the values used for Environment Variables in the HTML report. This can also be used to pass on external values that are needed only for the sake of reporting.

**Comment by hkgill** [comment]
+1

**Comment by kunagpal** [comment]
@hkgill @Vijayabaskar03 This will be available in the next Newman release.

**Comment by hkgill** [comment]
Thanks @kunagpal

**Comment by kunagpal** [comment]
@hkgill @Vijayabaskar03 This is available in Newman `v3.3.1`, do go ahead and check it out :smile:
