### ISSUE TITLE
Follow JS/HTML redirects

### ISSUE THREAD

**Issue by miry** [postmanlabs/newman#799]
Currently Postman support follow redirects only if 3xx status and has header Location. It would great to have option to follow the JS redirects and HTML meta tags redirection.

**Comment by czardoz** [comment]
@miry Postman or Newman do not execute any Javascript in the response, nor do they try to parse it. As an HTTP client, this is out of scope for Newman as well as Postman :)

**Comment by shamasis** [comment]
Agree with @czardoz. @miry - you are supposed to pare the response body yourself in test script and do the needful redirection of you want to.

**Comment by miry** [comment]
@shamasis thanks for clarification. I use postman for checking 3rd party links pointing to correct domain. The redirect chain is big :( Sometime HTTP redirection, sometime HTML or JS. I think to create post-script with dynamic  Postman requests chain to parse the page for links and try again.

**Comment by shamasis** [comment]
I understand your pain. Your solution is the right way. Let me know when done. Maybe you could write something about it. 😊
