### ISSUE TITLE
Upgrade to newman 3.3.0 broke environment variable functionality

### ISSUE THREAD

**Issue by punkosu** [postmanlabs/newman#804]
1. Newman Version (can be found via `newman -v`): 3.1.2
 2. OS details (type, version, and architecture): OS-X Sierra
 3. Are you using Newman as a library, or via the CLI?:  I'm using the CLI
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
     Environment Variable in the data.json file should be replaced in the requests of the collection

Steps to reproduce the problem:

1. Install newman version 3.1.2
2. Run a collection, providing a data file (should succeed): 
```newman run collection.json -e data.json```
3. Upgrade newman to version 3.3.0
4. Re-run command, the environment variable isn't being read or replaced.

**Comment by kunagpal** [comment]
Hey @punkosu, welcome to the Newman issue tracker!

I'm unable to reproduce your issue, please verify / do the following:
* As per point 2 in the steps to reproduce the problem, you've mentioned using Newman with a `JSON` data file, which should be in the format:
```json
[
    {
         "variable1": "value1",
         "variable2": "value2"
    },
...]
```
If `data.json` is indeed in this format, change your command to `newman run collection.json -d data.json`.

* If however, the `data.json` file is actually an environment file, please ensure that it is of the following form:
```json
{
        "id": "4454509f-00c3-fd32-d56c-ac1537f31415",
        "name": "test-env",
        "values": [
            {
                "key": "foo",
                "value": "bar",
                "type": "text",
                "enabled": true
            }
        ],
        "timestamp": 1404119927461,
        "_postman_variable_scope": "environment",
        "_postman_exported_at": "2016-10-17T14:26:34.940Z",
        "_postman_exported_using": "Postman/4.8.0"
    }
```
For this case, the command remains the same (`newman run collection.json -e data.json`).

**Comment by shamasis** [comment]
@punkosu could it be that there is some issue with your environment file format? Could you try a simple environment file exported from the latest postman app and see if it works? If it doesn't then we need to dig deeper. If it does, then you'll need to compare and check what's the difference between your environment file and the one exported.

**Comment by punkosu** [comment]
My data file didn't have surrounding square brackets, after adding those and switching to -d it's working for me. Strange it was working in the old version that way, thanks for the help!
