### ISSUE TITLE
NewMan v3. Add an option to enable color output for CI systems like TeamCity and Jenkins

### ISSUE THREAD

**Issue by romadrobishevski** [postmanlabs/newman#808]
Once you run Newman in Teamcity
the v3 automatically switches of the color output
and it is not possible to turn this feature on.

Please add such an option.

**Comment by uadev** [comment]
There is a `--no-color` option if newman poorly detects ability to colorize output. But there also should be an option to force color mode e.g. `--color`.

**Comment by sheluchin** [comment]
It checks if Newman is being executed in a real interactive terminal, and if not, it disables color output. There used to be an option to explicitly enable color output, but as of v3, there is only the option to explicitly disable it, while enabling it is left to the internal check. When using Newman with Jenkins and other similar systems, there is no interactive terminal, so color is never enabled.

**Comment by kunagpal** [comment]
@sheluchin, @romadrobishevski, @uadev: The `--color` option has been added in #824, it will be rolled out with the next release.

**Comment by sheluchin** [comment]
@kunagpal thank you.

**Comment by kunagpal** [comment]
@romadrobishevski @uadev @sheluchin Newman `v3.4.0` has been released, which includes a `--color` option to force colored output in noTTY environments. Do go ahead and try it out! :smile:

**Comment by romadrobishevski** [comment]
Hey guys. Thanks a lot for this feature. Works perfect with TeamCity.

**Comment by chrisgbaker** [comment]
@uadev was `--no-color` removed? when running `npx newman run ./postman_collection.json -e ./postman_environment.json -r cli,junit --reporter-junit-export ./Test-Results.xml --disable-unicode --no-color` the command now fails `  error: unknown option `--no-color'` as the output.
