### ISSUE TITLE
Is it possible to add authorization to collection?

### ISSUE THREAD

**Issue by mahekmerchant** [postmanlabs/newman#811]
I have a access token, I don't want to add access token to each url under collection,instead I want to  add access token per collection,is it possible in newman?

**Comment by shamasis** [comment]
Save the token in an environment and refer it in your collection. Then export the collection and environment to use them together in Newman.

**Comment by mahekmerchant** [comment]
Thanks. One more thing I am already using csv for environment variables, so if I add access token as an variable, where do I have to declare access token variable in collection?

**Comment by czardoz** [comment]
@mahekmerchant If you add the access token to your CSV data, it can be used as described here: https://www.getpostman.com/docs/multiple_instances 

Feel free to re-open the issue if you're still having trouble! :smile:
