### ISSUE TITLE
Issue in using '#' char

### ISSUE THREAD

**Issue by vishgupta92** [postmanlabs/newman#812]
Hi,

i am trying to pass a json object as input params in postman.
ex.
{"task_type":{"name":"Sample_Task_Type_1","color":"#999901","description":"Sample Task Type 1","deleted":false}}

but from # character nothing get inputted.
ex.

{"task_type":{"name":"Sample_Task_Type_1","color":

Please tell me how to pass the string having # char in input object.

**Comment by czardoz** [comment]
@vishgupta92 You need to encode your URL before saving your request, I think. The `#` character is used as an anchor tag, and anything after that is not sent, even by browsers.

**Comment by vishgupta92** [comment]
@czardoz thanks for reply, i also tried with URLEncoding but did'nt get succeeded. After that i sent the JSONObject as formdata not in the url params and it works...

**Comment by czardoz** [comment]
@vishgupta92 glad you got it working! Closing this issue :)
