### ISSUE TITLE
Unable to create html objects in Newman

### ISSUE THREAD

**Issue by Gans79** [postmanlabs/newman#813]
We need to get data from a HTML webpage so extracting the response using the below javascript command which runs fine on Newman, but giving error(reference error)  while running in Newman .
Is there any fix or alternate . 

    var responseHTML = document.createElement("html");
    responseHTML.innerHTML = responseBody;
    var responseJSON=xml2Json(responseHTML.querySelector("#txtResponse").value);

 1. Newman Version (can be found via `newman -v`): 3.3.0
 2. OS details (type, version, and architecture): Windows 8.0
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: always there

**Comment by shamasis** [comment]
Newman and Postman scripts are not browser environments. As such document and other variables are not available. It's advised to manually manipulate HTML. To ease that, we have a jquery like library called cheerio available. 

Read
