### ISSUE TITLE
HTML reporter templates should be able to access folder information for a request.

### ISSUE THREAD

**Issue by czardoz** [postmanlabs/newman#825]
1. Newman Version (can be found via `newman -v`): latest
 2. OS details (type, version, and architecture): all
 3. Are you using Newman as a library, or via the CLI? both
 3. Did you encounter this recently, or has this bug always been there: It's a feature request
 4. Expected behaviour: The HTML reporter data should contain information about folders
 5. Command / script used to run Newman:
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by czardoz** [comment]
For example, instead of just "DigestAuth Request" here, we should also be able to indicate which folder this request is in. The folder information (basically just the name) should be a part of the template data.

![image](https://cloud.githubusercontent.com/assets/3726484/21256773/431e3e92-c39a-11e6-89ba-6e6872339900.png)

**Comment by kunagpal** [comment]
:+1:

**Comment by shamasis** [comment]
A path like approach is best like it is done in Newman failure table.

**Comment by kunagpal** [comment]
Done in #826

**Comment by kunagpal** [comment]
Pending on the `v3.4.0` release.

**Comment by kunagpal** [comment]
Released with Newman `v3.4.0`.
