### ISSUE TITLE
Issue with integrating newman exit codes with jenkins

### ISSUE THREAD

**Issue by ShilAggarwal** [postmanlabs/newman#827]
Issue with Jenkins integration

 1. Newman Version: 3.3.0
 2. OS details : Windows - 64 bit machine
 3. Are you using Newman as a library, or via the CLI : CLI
 3. Did you encounter this recently, or has this bug always been there: Always been there
 4. Expected behaviour: Should integrate the exit codes with Jenkins seamlessly.
 5. Command / script used to run Newman: 
newman run application_collection.json -e application_environment.json --folder "folder1" --exitCode 1.

Errors:
newman run: error: Unrecognized arguments: --exitCode 1..

**Comment by kunagpal** [comment]
@ShilAggarwal `--exitCode` is  Newman `v2.x` CLI option and won't work with `newman run ...`, which is in Newman `v3.x` style. The following command would suffice for your use case:

```terminal
newman run application_collection.json -e application_environment.json --folder "folder1"
```

More details: https://github.com/postmanlabs/newman#command-line-options
Feel free to get back for any other questions you might have :smile:

**Comment by kunagpal** [comment]
Closing issue on our end, do let us know if your issue persists. :+1:
