### ISSUE TITLE
Is there any way in Postman pro a collection can be called from other collection

### ISSUE THREAD

**Issue by Sripathi1983** [postmanlabs/newman#833]
1. Newman Version (can be found via `newman -v`):
 2. OS details (type, version, and architecture):
 3. Are you using Newman as a library, or via the CLI?
 3. Did you encounter this recently, or has this bug always been there:
 4. Expected behaviour:
 5. Command / script used to run Newman:
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

**Comment by czardoz** [comment]
@Sripathi1983 No, there's no way to do that, because Collections are designed to be independant units by themselves.

For advanced use cases, you can use Newman as a library for maximum flexibility, check the [examples](https://github.com/postmanlabs/newman/tree/develop/examples) to get started :)
