### ISSUE TITLE
Is there a way to fetch the basic authentication username and passwords from environment

### ISSUE THREAD

**Issue by gkumbhat** [postmanlabs/newman#836]
I have a set of tests which need username and password to access the service. For security reasons I cannot post the credentials directly in the generated test json file. Therefore, I need to fetch these credentials from running terminal environment. Is there a way to fetch them from environment or any work around?

**Comment by kunagpal** [comment]
Although fetching values directly from the process environment is currently not supported, you can use environment files to isolate potentially sensitive data from the test collection file. More details here: https://www.getpostman.com/docs/environments. Once your environment has been created, you can export it and use it as follows:
```
newman run collection.json -e env.json
```
Here, `env.json` is the environment exported from the Postman Client.

**Comment by kunagpal** [comment]
@gkumbhat Marking issue as resolved. 😄
