### ISSUE TITLE
Allow adding custom snippet for tests

### ISSUE THREAD

**Issue by npadhya** [postmanlabs/newman#838]
Feature request

Currently, Postman's Test tab have the list of Code snippet that helps the beginner.
Can we have a way to add custom snippets so working with tests and helping team become more easy ?

**Comment by kunagpal** [comment]
@npadhya The concept of shareable/customizable code snippets sounds intriguing, could you open a feature request at https://github.com/postmanlabs/postman-app-support/issues/new? We'll take a look at your feature request. :smile:
