### ISSUE TITLE
How to replace a cookie value in next corresponding requests?

### ISSUE THREAD

**Issue by Freakishmahesh** [postmanlabs/newman#843]
Here is a case.
When request A is triggered, we do set few cookie values. (Lets say A,B,C). When the second request is triggered, we set few cookie values with same names, although the cookie values of second request are different. Now, should replace the cookie value of second request, with the first requests value.

I have saved the cookie value as an environment variable and I got the value. Now, how will I be replacing second requests cookie value? Please help.

**Comment by czardoz** [comment]
@Freakishmahesh Newman automatically handles cookies for requests. In order to replace the cookie value, you will have to replace it from your server with a `Set-Cookie` header.

**Comment by czardoz** [comment]
@Freakishmahesh Closing the issue for now, do let me know if this does not answer your question :)
