### ISSUE TITLE
Folder names for test cases are not shown in html report

### ISSUE THREAD

**Issue by sinaa2000** [postmanlabs/newman#844]
1. Newman Version (can be found via `newman -v`):  3.3.1
 2. OS details (type, version, and architecture):  Win 7 Pro 64 bit
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Recently after downloading changes made to html reporter
 4. Expected behaviour: Should show folder names but its not
 5. Command / script used to run Newman: newman run collection.json-e env --reporters cli,html --reporter-html-export report.html

 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

The issue is I have test case folders each one with multiple API calls(steps) but only these calls(steps) are shown in the html report and its unclear which test step goes to which folder!
Is there a way to show the folder name when each series of tests under each folder is run?
Already uploaded and used your changed version with if folder and aggregations.hbs template but still getting no folder shown under the html report.
Tested with both collection v1 and 2, same issue.

Thanks

**Comment by kunagpal** [comment]
@sinaa2000 Folder name support for the HTML report has been added in https://github.com/postmanlabs/newman/pull/826, and will be available in the next Newman release :smile:

**Comment by sinaa2000** [comment]
Thanks for your quick response!
So it's not possible in anyways on this 3.3.1 I'm running?

**Comment by sinaa2000** [comment]
And if not, when can we expect the new release?

**Comment by kunagpal** [comment]
The next release can be expected in a week or two.

**Comment by sinaa2000** [comment]
Ok, cool, thanks!

**Comment by kunagpal** [comment]
Duplicate of #825

**Comment by kunagpal** [comment]
@sinaa2000 Newman `v3.4.0` has been released, which includes collection folder name support for the HTML reporter, do go ahead and try it out! :smile:

**Comment by sinaa2000** [comment]
Great!
Thanks for the heads up!
