### ISSUE TITLE
newman junit reporter doesn't include test statuses to junit xml

### ISSUE THREAD

**Issue by Hi-Fi** [postmanlabs/newman#845]
1. Newman Version (can be found via `newman -v`): 3.3.1
 2. OS details (type, version, and architecture): Windows 7, x64
 3. Are you using Newman as a library, or via the CLI? CLI and as a library
 3. Did you encounter this recently, or has this bug always been there: Don't know
 4. Expected behaviour: junit xml's testcase -element should contain also "status" (at least for failed ones)
 5. Command / script used to run Newman: newman.cmd run sample.postman_collection.json -r cli,html,junit
 6. Sample collection, and auxilliary files (minus the sensitive details):

> {
	"variables": [],
	"info": {
		"name": "sample",
		"_postman_id": "0baa5e51-a827-4151-4931-19baf7ea156a",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "http://www.thomas-bayer.com/sqlrest/CUSTOMER/",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"tests[\"Status code is 404\"] = responseCode.code === 404;"
						]
					}
				}
			],
			"request": {
				"url": "http://www.thomas-bayer.com/sqlrest/CUSTOMER/",
				"method": "GET",
				"header": [],
				"body": {},
				"description": ""
			},
			"response": []
		}
	]
}

1. run attached collection with newman
2. check craeted junit XML for test statuses

**Comment by czardoz** [comment]
@Hi-Fi Can you provide a format of the expected XML?

**Comment by Hi-Fi** [comment]
Seems that the problem was caused by Bamboo somehow, now it's able to parse the jUnit file correctly. I initially thought it would need the "status" attribute.

**Comment by shamasis** [comment]
Closing.
