### ISSUE TITLE
Issue in exporting  globals using --export-globals in newman cli 

### ISSUE THREAD

**Issue by Sripathi1983** [postmanlabs/newman#851]
Hi,

I'm creating few global variables in POSTMAN and saving them as json file in hard disk, when I test collections using newman I'm exporting globals file as well using --export-globals switch to update all the global variables with new values when test collection fired using newman 
eg - newman run col1  --export-global global.json
this updates the global file perfectly, as I mentioned earlier the global file contains many other global variables also , those are getting overridden.

if I do  newman run col2.json --export-global global.json again, it completely flushes out previous variable and the reflects only the last executed newman command value.

I want to re-use the global file for all test collections , can be specify what corrections need to be done.

**Comment by Sripathi1983** [comment]
I resolved it

**Comment by krogold** [comment]
Hello,
would you mind describing how you solved it ? 
thank you

Alexandre
