### ISSUE TITLE
How do I make Jenkins build fail when Newman  tests fail

### ISSUE THREAD

**Issue by Sripathi1983** [postmanlabs/newman#853]
eg- I have 2 collections  one passes and one fails , both are fired by two separate newman commands

newman run col1.json  this contains failure test case
newman run col2.json  this passes

when integrated with jenkins as last executed is col2 and it successfull the build result is success, but it should be failure, do have any idea 

FYI, tried with --bail option but it  is not working as expected.

**Comment by kunagpal** [comment]
@Sripathi1983 `--bail` will merely stop the collection run when the first error occurs. In order to server your use case better, you would want to change the command to use a single statement, like so:
```terminal
newman run col1.json --bail && newman run col2.json --bail
```

**Comment by ericmacfa** [comment]
My (naive) solution doesn't quite fit @Sripathi1983's use case (OP is using the CLI), but I'll post it for reference:

Newman can be [used as a Node.js module](https://www.npmjs.com/package/newman#using-newman-as-a-nodejs-module). If you're using this method, then notice that [`newman.run`](https://www.npmjs.com/package/newman#newmanrunoptions-object--callback-function---run-eventemitter) takes a `callback` argument (which is executed once the collection run finishes).

The `callback` function is passed, among other things, a [summary](https://www.npmjs.com/package/newman#newmanruncallbackerror-object--summary-object-) object. The array of assertion failures is located at `summary.run.failures`.

Using this information, we can implement a naive solution by simply adding the below code to the `callback` passed to `newman.run`:
```
...
if(summary.run.failures.length !== 0){
    process.exit(-1);
}
```

The non-zero exit code will then be picked up by Jenkins and be interpreted as a build failure.

**Comment by shamasis** [comment]
Newman already exits with non zero code on failure. Is that not happening?

**Comment by Sripathi1983** [comment]
Thanks but it is resolved in a different way

**Comment by tonitech** [comment]
My solution is to separate your build into several steps. The first step is to build your application. The later steps are newman executions. In your case, after building your application, you can set a shell execution for 
`newman run col1.json`
and the other shell execution for
`newman run col2.json`
