### ISSUE TITLE
Allow (process) env vars to be used as Environment Variables

### ISSUE THREAD

**Issue by DanielLarsenNZ** [postmanlabs/newman#856]
Similar to #647 but instead of passing variables as command line switches, allow `process.env` vars to be used as (Postman) Environment Variables where none already exists. In other words a Postman Environment Variable (`api_url`) would have precedence over `process.env.API_URL`.

This is desirable because there are some environment specific settings (passwords) that I don't want to store in the `.postman_environment.json` file (which is checked in to source control). Yes, I can rewrite my `.postman_environment.json` file before I call `newman run` but using `process.env` would be more convenient.

Any other suggestions welcome 😃

**Comment by shamasis** [comment]
@DanielLarsenNZ - exposing process.env inside sandbox is something that I've always felt to end up having a greater security concern.

If we do something towards it, the things that go through my mind is allowing global variable overrides via command line param. Thinking aloud.

@a85 thoughts?

**Comment by DanielLarsenNZ** [comment]
Good point about security. Command line switch to enable the feature is a good idea. 👍

**Comment by gaieges** [comment]
You could always utilize only prefixed environment variables: ie `NEWMAN_API_URL` would be populated in the `api_url` var.  Less ideal but equally as useful would be command line switches to add individual variables to a newman run: ie `-i api_url=http://google.com`.

Not sure if this alleviates your security concern (could you elaborate a little @shamasis?) 

My use case, and the reason I got excited about this was that I could have a single static test file that lived in the repo, and have jenkins or other tools be responsible for pointing those tests dynamically to whatever location needed.  

Seems like in its current form I would need to drop in some environment files that populate those variables for me (to all 20 of my repos), or have jenkins create a variable file (which I'll likely end up doing).

**Comment by shamasis** [comment]
The prefix idea is great! It does not alleviate security issues. My question still remains - will your use case be fulfilled if there was a command line argument to set individual global variables?

That's much straightforward approach IMHO. And more "on the face" solution with visibility as to what is being passed to Newman.

**Comment by kunagpal** [comment]
Related to #836

**Comment by gaieges** [comment]
@shamasis yes - as long as those command line switches for global args would allow me to modify the environment parameters as well (ie anything in the `{{var}}` templates).

Could you elaborate more on your security concerns?  Would like to help think through workarounds but not sure what your concern is regarding that.

**Comment by shamasis** [comment]
1. People can run a lot of collections even from third party sources. Environment variables contain sensitive information and without a whitelist it is risky. 

2. Environment variables can also contain large amount of data. That can end up slowing down the script execution sandbox since the environment variables will require to be serialised and sent over IPC and deserialised back again. 

3. Collection runs can be affected adversely if unexpected variables creep in without the collection writer or user is not aware of the collection script's internal working.

These are my concerns.

**Comment by gaieges** [comment]
Correct me if I'm wrong, but I believe adding the prefix to the env vars would solve all of those.

**Comment by shamasis** [comment]
Like I mentioned - yes - the prefix solves point 1 partly and not the rest. More than that, CLI argument path totally negates all points.

**Comment by gaieges** [comment]
I think it solves all of them.  Either way no need to debate that, CLI options would work perfectly for me!

**Comment by shamasis** [comment]
Glad to hear that. We will schedule something for this or wait to see if we get a PR.

**Comment by gaieges** [comment]
Any timeline around a resolution for this @shamasis ?  I see some other issues that indicate users are looking for a similar feature.

**Comment by kunagpal** [comment]
@gaieges @DanielLarsenNZ With Newman v3.8.0 and above, you can pass in variables via the CLI as follows:
```
newman run collection.json --global-var key=$variable
```

If you're on Windows, replace `$variable` with `%variable%` or `$env:variable` for cmd and PowerShell respectively.

**Comment by gaieges** [comment]
@kunagpal This ticket is about env vars, not cli vars.  CLI stuff works fine for me just making sure you want to close this ticket since that's not what its about.

**Comment by kunagpal** [comment]
The idea here is that `process.env.VAR` and `$VAR` are equivalent. For instance,
```shell
$ VAR=my_value node -e 'console.log(process.env.VAR):'
```

would result in:
```
my_value
```

To add more clarity, if you'd like to add the environment variable called `URL` in the newman collection run, you could do it as follows:
```
newman run collection.json --global-var url=$URL
```

This will cause all occurrences of `{{url}}` in your collection to be replaced with the corresponding process environment variable.

**Comment by gaieges** [comment]
Yeah understood on the latter part.  On the former, are you saying I can do 

```
VAR=blah newman run collection.json
```

And have anything in `collection.json` with `$VAR` or `VAR` get the value `blah`?  That's sort of how I'm defining env vars vs cli vars - just automatically inserted.

**Comment by kunagpal** [comment]
As discussed earlier, automatic insertion bring with it security concerns. You'd have to use the `--global-var` option as demonstrated above

**Comment by englishm-llnw** [comment]
I understand the concern for users who may inadvertently allow the exfiltration of sensitive environment variables by malicious collections. However, there is another security concern to consider here, too.

On many UNIX-family operating systems, the full command line (including arguments) for each process is visible to all. This means that if I want to pass an API token to a collection and use `newman run collection.json --global-var token=$token`, the value of `$token` (expanded by the shell) will be visible to all users on the host where `newman` is running. This is not ideal, especially on shared hosts like build servers.

I like @gaieges's suggestion of filtering by a `NEWMAN_` prefix. 

Alternatively, a list of specific variable names to import could be provided as a command line argument. For example:

```
newman run collection.json --shell-env-vars token,url
```

With considerations like the above, shell environment variables could actually be _more_ secure than command line arguments.

**Comment by DavidIMcIntosh** [comment]
Could we perhaps at least have a small collection of standard environment variables available through some mechanism?  I am thinking, for example, in the Windows environment, it would be soooo useful to have the "COMPUTERNAME", "USERNAME", "USERDOMAIN" environment variables available.  Think of the current Windows authentication headers: you need the three variables just mentioned for the authentication, and it is a pain to have each user create an environment variable file.  (I gather from the documentation that Domain and Workstation will default, I presume appropriately, but apparently Username will not.)
