### ISSUE TITLE
POSTMAN Exporting Collection issue when special characters are in the message body

### ISSUE THREAD

**Issue by mattia19** [postmanlabs/newman#865]
I've just created a new collection in POSTMAN collecting some POST methods. I've successfully  exported the collection but when i tried to import the new collection the POST method with special characters in the body (i.e *, #) wasn't successfully imported. See in attach the body for further details
![issue-postman](https://cloud.githubusercontent.com/assets/25059451/21854486/32e1c752-d81b-11e6-9845-4618db54ff8a.jpg)

POSTMAN application version

4.9.2
win / x86-32
Chrome 55.0.2883.87

**Comment by czardoz** [comment]
Hi I've created an issue for you on the correct issue tracker, do add any additional comments over there :)

https://github.com/postmanlabs/postman-app-support/issues/2644
