### ISSUE TITLE
Drill down on Failed cases is good to have in the HTML reports.

### ISSUE THREAD

**Issue by chaitanyasivalanka** [postmanlabs/newman#873]
On html reporting which gets generated from new man after a run - 

It gives a full list of API's executed and assertions passed or failed
however, it doesnt drill down on the failed cases.. to only have a look at the APi's
do we have any custom reports which gives this kind of reporting to check the failed ones? I had to scroll through the report completely till the end.

Its good to have the dfrilled down options on failed cases to understand which APi's failed to a quick overview

**Comment by jbnok** [comment]
If there is a way to increase the emphasis on this issue please consider this an escalation as my org is looking for this functionality as well.

**Comment by kunagpal** [comment]
@chaitanyasivalanka Unfortunately, this is beyond the scope of the built in Newman reporters. However, you're more than welcome to create your very own custom reporter for the same. For more details, check out https://www.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman#custom-reporters.
