### ISSUE TITLE
output not set to 1 on failed test

### ISSUE THREAD

**Issue by jaimeMerino** [postmanlabs/newman#881]
1. Newman Version (can be found via `newman -v`):

3.4.2 the latest on newman_alpine33 docker image.

 2. Are you using Newman as a library, or via the CLI?

CLI on a docker run

 3. Expected behaviour:
When running a collection, if one or more test failed the container output must be 1.

Using -x flag forces a 0 return.

  #  failure           detail

 1.  AssertionFailure  Status code is 200
                       at test-script:33:21
                       inside "Get ES country" of "Country"

 2.  AssertionFailure  Status code is 200
                       at assertion:1 in test-script
                       inside "Get ES country" of "Country"
0
Staging integraction test passed

**Comment by elssar** [comment]
Hi @jaimeMerino, I'm a bit confused. Are you using the `-x` flag? If so, then that is expected behaviour.

Prior to Newman v3, the `-x` would return an exit code 1 if a test failed, but the behaviour has changed in v3.

**Comment by jaimeMerino** [comment]
Hi @elssar,
no, i'm not using the -x flag. 

this is a portion from a deployment jenkins pipeline bash.

````
eval docker run --rm registry_host/newman/newman:latest run collections/postman_collection.json \
    --environment postman_environment.json --bail;

if [ "$?" != "0" ]; then

    echo "Staging integration tests failed, rollback to previous version"
    # build failed, rollback

    exit 1
else
    echo "Staging integraction test passed"
fi
````

this not generates any exit, and with -x flag always exit 0 (and return an ok of test passed). 

there's a simple way of doing this?

**Comment by elssar** [comment]
Hey @jaimeMerino, I could not reproduce this.

I can two collections using the latest alpine image, one that fails and another that passes, and on all occasions, I got the expected exit code. Attaching screen shots.

![newman-exit-code-test](https://cloud.githubusercontent.com/assets/1042301/22336157/4270144c-e407-11e6-94b5-55860eb6e5a9.png)
![newman-exit-code-test-with-eval](https://cloud.githubusercontent.com/assets/1042301/22336248/8ca05b30-e407-11e6-90e4-0a3f9f2cb666.png)

**Comment by jaimeMerino** [comment]
lol.
after all it's a bash script error and a "set -e" before.

thanks
