### ISSUE TITLE
"TypeError: Cannot read property '0' of undefined" when test fail in jenkins

### ISSUE THREAD

**Issue by dmnlk** [postmanlabs/newman#885]
1. Newman Version (can be found via `newman -v`):
newman -v
3.4.2
 2. OS details (type, version, and architecture):
CentOS 6.8 and newman_alpine33 docker image
 3. Are you using Newman as a library, or via the CLI?
CLI
 3. Did you encounter this recently, or has this bug always been there:
when 
 4. Expected behaviour:

 5. Command / script used to run Newman:
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

when  newman  in jenkins  and if fail test, newman gets error in cell.js

![image](https://cloud.githubusercontent.com/assets/909198/22411313/d9edf362-e6e5-11e6-8d6d-3482a6a7068d.png)

but sucessful in CLI
![image](https://cloud.githubusercontent.com/assets/909198/22411300/b41b34ec-e6e5-11e6-9957-1545863b5899.png)

**Comment by kunagpal** [comment]
@dmnlk This appears to be a `noTTY` conflict issue, could you try adding `export TERM=xterm` before the `newman` command runs in your Jenkins environment?

**Comment by dmnlk** [comment]
@kunagpal 
i tried this , but get same error

`sudo docker run -e TERM=xterm --volume=/jenkins/workspace/:/var/newman -t newman run /var/newman/collection/fail.postman_collection.json --environment=/var/newman/environment/dev.postman_environment.json`

**Comment by kunagpal** [comment]
@dmnlk There shouldn't be a `=` between `--environment` and `/var/newman/environment/dev.postman_environment.json`, the command should be:
```terminal
sudo docker run -e TERM=xterm --volume=/jenkins/workspace/:/var/newman -t newman run /var/newman/collection/fail.postman_collection.json --environment /var/newman/environment/dev.postman_environment.json
```

**Comment by dmnlk** [comment]
@kunagpal 
ok, thanks.
but i got same error  still now 
![image](https://cloud.githubusercontent.com/assets/909198/22417109/d4b9b8f6-e715-11e6-982a-56c7b61b8628.png)

**Comment by jnyborg** [comment]
@dmnlk Not sure if this is applicable to you, but I got the exact same error and fixed it by testing against http instead of https.

**Comment by kunagpal** [comment]
@czardoz This could be due to a missing `.toString()` call here: https://github.com/postmanlabs/newman/blob/develop/lib/reporters/cli/index.js#L60, as compared to https://github.com/postmanlabs/newman/blob/develop/lib/reporters/cli/index.js#L65

**Comment by czardoz** [comment]
@grioja, any chance you could share the collection causing this problem?

**Comment by grioja** [comment]
@czardoz 

Attached my collection, and associated error. This is blocking our Jenkins build process currently...
[GoldenPath.postman_collection.json.zip](https://github.com/postmanlabs/newman/files/987128/GoldenPath.postman_collection.json.zip)


```/usr/local/lib/node_modules/newman/node_modules/cli-table2/src/cell.js:52
  var fixedWidth = tableOptions.colWidths[this.x];
                                         ^

TypeError: Cannot read property '0' of undefined
    at Cell.mergeTableOptions (/usr/local/lib/node_modules/newman/node_modules/cli-table2/src/cell.js:52:42)
    at Table.<anonymous> (/usr/local/lib/node_modules/newman/node_modules/cli-table2/src/table.js:29:12)
    at /usr/local/lib/node_modules/newman/node_modules/cli-table2/node_modules/lodash/index.js:2874:23
    at /usr/local/lib/node_modules/newman/node_modules/cli-table2/node_modules/lodash/index.js:3049:15
    at Function.<anonymous> (/usr/local/lib/node_modules/newman/node_modules/cli-table2/node_modules/lodash/index.js:3346:13)
    at Table.<anonymous> (/usr/local/lib/node_modules/newman/node_modules/cli-table2/src/table.js:28:7)
    at /usr/local/lib/node_modules/newman/node_modules/cli-table2/node_modules/lodash/index.js:2874:23
    at /usr/local/lib/node_modules/newman/node_modules/cli-table2/node_modules/lodash/index.js:3049:15
    at Function.<anonymous> (/usr/local/lib/node_modules/newman/node_modules/cli-table2/node_modules/lodash/index.js:3346:13)
    at Table.toString (/usr/local/lib/node_modules/newman/node_modules/cli-table2/src/table.js:27:5)```

**Comment by grioja** [comment]
I think this is strictly related to printing out the results of the test (which it happens when my collection succeeds or fails). I'm using `--no-color --bail`

**Comment by grioja** [comment]
I am now explicitly setting `cli` as the reporter, and use `--insecure` and it appears to be working now

**Comment by schobster** [comment]
Running into the same problem as well. I am seeing the problem when running the [newman-docker image](https://github.com/postmanlabs/newman-docker) within a Jenkins build pipeline.

**Comment by LowcodeLogan** [comment]
I'm seeing this same issue as well using the newman-docker image running from jenkins. Everything works good except the failure-details summary

**Comment by jeroenheijmans** [comment]
I was also experiencing this issue. My hypothesis is that this occurs because newman explicitly calls `cli-table2` with `colWidths = undefined`. You can see this exact behavior for example with a free-style jenkins pipeline project with this definition:

```sh
sh """
    npm install cli-table2
    
    echo "var Table = require('cli-table2');" > script.js
    echo "var table = new Table({ head: ['TH 1 label', 'TH 2 label'], colWidths: undefined });" >> script.js
    echo "table.push(['First value', 'Second value']);" >> script.js
    echo "console.log(table.toString());" >> script.js
    
    node script.js
"""
```

This will provide output like this:

```
+ node script.js
/var/jenkins_home/workspace/test3/node_modules/cli-table2/src/cell.js:52
  var fixedWidth = tableOptions.colWidths[this.x];
                                         ^

TypeError: Cannot read property '0' of undefined
    at Cell.mergeTableOptions (/var/jenkins_home/workspace/test3/node_modules/cli-table2/src/cell.js:52:42)
```

I think the error is inside the `parseFailures` function in `index.js` [when setting `colWidths`](https://github.com/postmanlabs/newman/blob/849f86ab96304a159de282aaf8425e17f25ebc97/lib/reporters/cli/index.js#L296). Here's the relevant snippet:

```javascript
colWidths: cliUtils.noTTY() ? [] : (function (size, indexOrder) {
    var colWidths;

    if (size.exists && size.width && (size.width > 20)) {
        colWidths = [];
        colWidths[0] = indexOrder + 3;
        colWidths[1] = parseInt((size.width - colWidths[0]) * 0.2, 10);
        colWidths[2] = parseInt(size.width - (colWidths[0] + colWidths[1] + 5), 10);
    }

    return colWidths;
}(cliUtils.dimension(), Number(failures.length.toString().length)))
```

In cases where the `if` statement is false the `colWidths` will end up with the invalid value of `undefined`.

The fix at first sight seems to be simply to initialize the `var` directly with `[]`.

**Comment by jeroenheijmans** [comment]
Forgot to mention, you can also repro this issue by running `newman run coll.json` locally on this collection:

```json
{
	"item": [{
        "name": "Test",
        "request": { "url": "http://bogus.url.here" }
	}]
}
```

If you do it in a *really* small window (under 20 characters wide). Which makes sense given the `if` statement mentioned in previous comment.

**Comment by mikeder** [comment]
I'm running into this issue running the newman docker container in a Jenkins pipeline, I've found that adding the `--reporter-cli-no-failures` flag to my command gets me past the failure until this is fixed.

**Comment by wallyuva** [comment]
What worked for me was not using `-t` in the `docker run` command. My exact syntax was 
``` bash
docker run -v $temp_folder/postman:/etc/newman \
  postman/newman_alpine33 \
  --collection="my_collection.json" \
  --environment="my_environment.json" \
  --testReportFile="/path/to/results.xml"
```

**Comment by stephanos** [comment]
Just hit this as well. I'm running newman on CircleCI (ie a Docker environment) and don't have a lot of control about how it's being run.

**Comment by filfreire** [comment]
@kunagpal what was the solution to close this issue?

**Comment by kyungmi** [comment]
With GitHub Actions, the same issue has been occurred.
How to solve this problem?

```
//  local execution using `act`
...
[test api] docker build -t npm:master /var/folders/l6/hmb_c4h54t576pkg2dr6df740000gn/T/act/actions/npm@master
...
```

**Comment by ahajimir** [comment]
so is there no way to run this with tty and not get this error?

**Comment by ionutzp** [comment]
any news here?

**Comment by tanzencoder** [comment]
What's interesting is that I can run it with -t when the postman files are local files mounted but when I run the collection through the API it fails.

**Comment by unmultimedio** [comment]
Still running into this issue. I'm on `newman@5.2.1` and also I can't control the `-t` flag in the docker command. From the CLI it works ok.

```
/usr/local/lib/node_modules/newman/node_modules/cli-table3/src/cell.js:60
    let fixedWidth = tableOptions.colWidths[this.x];
                                           ^

TypeError: Cannot read property '0' of undefined
    at Cell.mergeTableOptions (/usr/local/lib/node_modules/[4mnewman[24m/node_modules/[4mcli-table3[24m/src/cell.js:60:44)
    at Table.<anonymous> (/usr/local/lib/node_modules/[4mnewman[24m/node_modules/[4mcli-table3[24m/src/table.js:27:14)
    at Array.forEach (<anonymous>)
    at Table.<anonymous> (/usr/local/lib/node_modules/[4mnewman[24m/node_modules/[4mcli-table3[24m/src/table.js:26:11)
    at Array.forEach (<anonymous>)
    at Table.toString (/usr/local/lib/node_modules/[4mnewman[24m/node_modules/[4mcli-table3[24m/src/table.js:25:11)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/[4mnewman[24m/lib/reporters/cli/index.js:90:22)
    at EventEmitter.emit (/usr/local/lib/node_modules/[4mnewman[24m/node_modules/[4meventemitter3[24m/index.js:203:33)
    at /usr/local/lib/node_modules/[4mnewman[24m/lib/run/index.js:328:33
    at wrapper (/usr/local/lib/node_modules/[4mnewman[24m/node_modules/[4masync[24m/internal/once.js:12:16)
    at iteratorCallback (/usr/local/lib/node_modules/[4mnewman[24m/node_modules/[4masync[24m/eachOf.js:56:13)
    at /usr/local/lib/node_modules/[4mnewman[24m/node_modules/[4masync[24m/internal/onlyOnce.js:12:16
    at wrapper (/usr/local/lib/node_modules/[4mnewman[24m/node_modules/[4masync[24m/dist/async.js:268:20)
    at next (/usr/local/lib/node_modules/[4mnewman[24m/node_modules/[4masync[24m/dist/async.js:4582:24)
    at /usr/local/lib/node_modules/[4mnewman[24m/node_modules/[4masync[24m/dist/async.js:321:20
    at /usr/local/lib/node_modules/[4mnewman[24m/lib/run/export-file.js:41:13
```

Also, from @jeroenheijmans [comment](https://github.com/postmanlabs/newman/issues/885#issuecomment-328867015), the current branch still has the issue exposed.

In [here](https://github.com/postmanlabs/newman/blob/98d08bd4690b5922ab8c48430a7f8e84a321397d/lib/reporters/cli/index.js#L405-L415), `var colWidths;` should be `var colWidths = [];`, right?
