### ISSUE TITLE
[Feature] - Ability to run collection from a single dump file

### ISSUE THREAD

**Issue by tariqghalib** [postmanlabs/newman#891]
**Feature Definition:**
Currently we do not have the ability to run a collection from a single dump file. The single dump file is created by exporting all tests, environments into one file from postman through (Settings --> Data --> Export data --> Download)

**Version and environment information:**
-->
 1. Newman Version (can be found via `newman -v`): 3.1.1
 2. OS details (type, version, and architecture): Windows professional 64
 3. Are you using Newman as a library, or via the CLI? via CLI
 3. Did you encounter this recently, or has this bug always been there: Have been like this since start
 4. Expected behaviour: Able to run collections from a single dump file that contains collections, environments as a single json file
 5. Command / script used to run Newman: newman run <collection.json>
 7. Screenshots (if applicable):

 Data --> Export data --> Download)
2. Run newman collection as:
newman run <singledump.json>
-->
![newman_notrun_from_single_dump](https://cloud.githubusercontent.com/assets/1693324/22484170/2e824b88-e7ce-11e6-9c7b-2eff1f36001d.JPG)

**Comment by shamasis** [comment]
Someone can write a simple script to do that using newman programmatically. :-p This does not seem to be a feasible feature to have built inside newman considering what newman is meant to be and how big dump files can get for many users.
