### ISSUE TITLE
[Bug] - Newman cannot handle 302 redirects properly

### ISSUE THREAD

**Issue by tariqghalib** [postmanlabs/newman#892]
**Description:**
During a sign in to a web app to retrieve the authentication Code, there are few redirects involved and newman fails to preserve all query parameters during the redirects, while the postman chrome app can handle that properly.

**Version and environment information:**
-->
 1. Newman Version (can be found via `newman -v`): 3.1.1
 2. OS details (type, version, and architecture): Windows professional x64
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Always been like this
 4. Expected behaviour: Newman handles the redirects and able to chain calls properly
 5. Command / script used to run Newman: Newman run

**Steps to reproduce the problem:**
This happens when we have an api call that involves few 302 redirects in it. (Chrome app can handle it properly but native apps cant). Few steps are:

A GET call to get to the login page. During this call there's a resumePath thats generated. We store the resumePath as a variable.

A POST call to pass login credentials and resumePath along with it

The second call can be divided into 4 sections:
a. First a post call to login page by passing the login information and resumePath
b. A 302 redirect that passes this information back to the authentication server. This also contains a redirect URL.
c. Another 302 redirect that moves the authenticated user alongside a referrer location. This also contains few query string parameters (clurl, resumePath and a custom variable called cd) that build up the final call to retrieve the authentication code
d. A GET call to retrieve the auth Code from the redirectURI

I have built a nodejs app that does the above 4 steps. Now if we change the query string parameters during the 302 redirects (indirectly changing the referrer location where it needs to go after the 302) we get exactly same error that postman windows app is showing which is:
Your login credentials could not be resolved. Please try logging in again.

Above is happening because we do pass the right credentials but it fails to bring back the success authentication from the server after the 302 redirect.

**Comment by tariqghalib** [comment]
@kunagpal This was recently fixed for postman native apps but with newman this is still an issue. Any update on this issue?

**Comment by tariqghalib** [comment]
@kunagpal @mcdan @chrisscott @jimthedev @piotrowski  Any update on this guys? This was fixed for native apps recently. Can we fix this for Newman please.

**Comment by shamasis** [comment]
Newman and postman native apps share similar code base. It should behave similarly in Newman. 

Cc @czardoz @kunagpal

**Comment by tariqghalib** [comment]
@shamasis Verified above and its working as mentioned above. We can close this Ticket
