### ISSUE TITLE
Customize HTML report template in Command line call for both "template-default.hbs" and "aggregations.hbs"

### ISSUE THREAD

**Issue by malaubay** [postmanlabs/newman#893]
If the html report template is separated into 2 ".hbs" files, is it possible to customize both the "template-default.hbs" and "aggregations.hbs", and define the templates used in command line call (e.g. --reporter-html-template )?

**Comment by kunagpal** [comment]
@malaubay Customization is currently limited to the main template only, but we could think about adding something like `--reporter-html-aggregation` to override the aggregation partial.

**Comment by davidschwab** [comment]
I too would like to see full control over the template(s), although my first preference would be to just have a single template. Is there a way to consolidate <template>.hbs and aggregations.hbs into one?

**Comment by kunagpal** [comment]
@davidschwab @malaubay #951 will merge the aggregation partial back into the base template, which will allow containing all customizations to one file 😄

**Comment by davidschwab** [comment]
@kunagpal awesome, thanks!

**Comment by malaubay** [comment]
@kunagpal Thanks!

**Comment by kunagpal** [comment]
Released with Newman `v3.5.1`.
