### ISSUE TITLE
Reference error - response code is not defined

### ISSUE THREAD

**Issue by DanielStoica85** [postmanlabs/newman#894]
So I was trying to run some of my collections for the first time in newman. I will mention from the start that these collections work fine in the Collection Runner. But when using Newman, I get the error from the title, for absolutely every request I make, in every collection.

I asked about this on the #help channel and someone suggested that it's a Newman bug. 

Is there anything I can do about this?

![errors](https://cloud.githubusercontent.com/assets/16979375/22558453/073755f4-e96e-11e6-8c6e-b978c2c25ecd.JPG)

**Comment by czardoz** [comment]
You're using a self signed certificate, so you need to run Newman with the `-k` option. Do let me know if that doesn't solve your issue.

**Comment by DanielStoica85** [comment]
You are right, @czardoz, thank you for the suggestion, works fine now!

**Comment by czardoz** [comment]
:cake:
