### ISSUE TITLE
options.iterationData add support for argument as an object type in newman.run

### ISSUE THREAD

**Issue by aaleks** [postmanlabs/newman#895]
It would be great to have the possibility to pass the object for options.iterationData in newman.run(options: object , callback: function) => run: EventEmitter

For options.collection for instance it is possible to specify JSON object not only the path.

This feature would enable some JSON manipulating and have the same way of passing data when used along with options.collection.

The goal is to have something like : 

options.iterationData
Type: object|string

**Comment by kunagpal** [comment]
@aaleks Thanks for the feature request, we'll take a closer look at this and update the thread with time.

**Comment by kunagpal** [comment]
@aaleks #952

**Comment by aaleks** [comment]
great news  :+1:

**Comment by kunagpal** [comment]
Released with Newman `v3.5.1`.

**Comment by ankitps1807** [comment]
Hi @kunagpal I am trying to use the 'newman.run((options.iterationData: object , callback: function)' feature via a Jenkins job, but no luck. Without the use of csv option it works fine as a Jenkins job, no issues there. Could you please advise?:

![image](https://user-images.githubusercontent.com/69150051/96614485-ced55980-131d-11eb-84cc-a7e21a1a79ed.png)
![image](https://user-images.githubusercontent.com/69150051/96614869-368ba480-131e-11eb-8340-e939f0f5f5c9.png)
