### ISSUE TITLE
Newman is not sending SSL cert on API calls

### ISSUE THREAD

**Issue by hmaich** [postmanlabs/newman#897]
I'm using Newman CLI v 3.4.3 to run a postman collection.
My service requires a SSL cert so I'm using --ssl-client-cert cert.pfx --ssl-client-passphrase Password.
The problem is that, apparently the cert is not been sent to the service and the requests are been rejected with 401 No Client Certificate.
I tried to use certs with both .pfx and .pem without success.
I also tried to use the -insecure (just in case) but that didn't help ether.

When sending the request via Postman or Chrome, everything works fine.

Is there anyway I can troubleshoot and check why the cert is not been sent to the service?

Thanks

**Comment by hmaich** [comment]
Adding to this...
I just installed the native Postman and tried to use the certificate, in which case the same issue happened. So using the chrome version of Postman, all is good, native version as well as Newman do not work. Any thoughts?

**Comment by hmaich** [comment]
Another update...
I finally managed to work around this issue. Basically I had to convert the pfx into a pem WITH a Key file. Removing the key and using the pfx with the password didn't work.

Hope this helps others :)

**Comment by SaranyaJothi6101** [comment]
@hmaich - Am also facing the same issue. Could you please help me how to resolve that issue in newman
