### ISSUE TITLE
Powershell script exiting with 0 even some of the tests are failing in collection

### ISSUE THREAD

**Issue by laxmanrapolu** [postmanlabs/newman#907]
1. Newman Version (can be found via `newman -v`): 3.4.3
 2. OS details (type, version, and architecture): Windows 2008 R2
 3. Are you using Newman as a library, or via the CLI? : CLI
 3. Did you encounter this recently, or has this bug always been there: New to Newman
 4. Expected behaviour: Shoud exit with -1. 
 5. Command / script used to run Newman: - newman run https://www.getpostman.com/collections/***** --folder **** -e devenv.json
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):
Some how not able to run script command with -s option. (found -s solution in other posts)

**Comment by shamasis** [comment]
@kunagpal can you try out a failing collection in powershell?

**Comment by kunagpal** [comment]
@laxmanrapolu How are you checking the error code? With a failing collection on my end, `$global:LastExitCode` and `$?`, both provide `1`.

**Comment by laxmanrapolu** [comment]
Thanks Guys. I think it is problem with Octopus Deploy. I thought Octopus would automatically check for this exist code and fail the deployment, but somehow it is not happening. So I am manually checking for ($? -eq True) and failing the deployment(Seems to be $global:LastExitCode is not working on octopus). I have depended on below hack for all these days.

$json = (Get-Content "C:\newman\outputfile.json" -Raw) | ConvertFrom-Json
if($json.run.stats.assertions.failed -gt 0){
exit 1
}
else{
write-host "success"
}

**Comment by shamasis** [comment]
It's good to hear that your problem is solved. Do you think that something needs to be done with Newman CLI to handle it better?

**Comment by laxmanrapolu** [comment]
I have one :) . I am only running tests in specific folder, but report contains information about all tests in collection. Somehow I felt generating the report of only running tests (in this case only one folder tests) would be helpful and will become easy for us to debug and see.

**Comment by kunagpal** [comment]
@laxmanrapolu Good point, I see that the HTML and JSON reporters will have to be update to respect filtering by `--folder`.
