### ISSUE TITLE
Integration with thirdparty reporters from command line, e.g. teamcity

### ISSUE THREAD

**Issue by sergiorykov** [postmanlabs/newman#910]
1. Newman Version (can be found via `newman -v`): **3.4.3**
 2. OS details (type, version, and architecture): **Windows 10**
 3. Are you using Newman as a library, or via the CLI? **CLI**
 3. Did you encounter this recently, or has this bug always been there: recently
 4. Expected behaviour: **I can use custom reporters from CLI**
 5. Command / script used to run Newman: newman ... **-r=cli,teamcity** or **-r=cli,newman-reporter-teamcity**
 6. Sample collection, and auxilliary files (minus the sensitive details): any
 7. Screenshots (if applicable):

Is it possible to use thirdparty reporters from command line?
To be precise I need integration with TeamCity. 
As a workaround I know about **-r=cli,junit --reporter-junit-export out_junit.xml** with TeamCity [XML Report processing](https://confluence.jetbrains.com/display/TCD10/XML+Report+Processing) + JUnit on **+:out_junit.xml**

But I want to see test results as they are available. I found exactly one package that it does: [newman-reporter-teamcity](https://github.com/leafle/newman-reporter-teamcity). Actually it doesn't matter which one to use - it's published as a npm package. I've installed it in the directory where I execute newman. 

Do you have mechanism to use thirdparty reporters from command line?
Or may be do you have plans to support TeamCity/Jenkins as it requires just special output formatting?

**Comment by kunagpal** [comment]
@sergiorykov Thanks for reporting this, #912  should serve as a starting point. :smile:
