### ISSUE TITLE
Newman didn't change data in Environment variable file.

### ISSUE THREAD

**Issue by nitinEd** [postmanlabs/newman#913]
Newman version : 3.4.3
OS: MacOS 10.10

I have written some script in Pre-request Script of a POST API.

var id = postman.getEnvironmentVariable("i");
id++;
postman.setEnvironmentVariable("i", id);

whenver I run this API in postman, above env variable's value has been changed which is ok but when i hit this api using newman , env variable didn't change its value in file.

Do i need any additional permisison or this is a bug
I need help here. this is blocking me.

Thanks

**Comment by kunagpal** [comment]
@nitinEd Could you provide your Newman version as well?

**Comment by nitinEd** [comment]
@kunagpal 
 newman verison : 3.4.3

**Comment by czardoz** [comment]
@nitinEd Can you share the complete command you are using to run newman?

**Comment by nitinEd** [comment]
newman run /Users/nitinkumar/Desktop/API/V2-Edcast.postman_collection.json -r html,cli -e /Users/nitinkumar/Desktop/API/QA.postman_environment.json

**Comment by kunagpal** [comment]
@nitinEd You'll have to use `--export-environment`, like so: 
```terminal
newman run /Users/nitinkumar/Desktop/API/V2-Edcast.postman_collection.json -r html,cli -e /Users/nitinkumar/Desktop/API/QA.postman_environment.json --export-environment /Users/nitinkumar/Desktop/API/QA.postman_environment.json
```

This will ensure that your environment is updated after the run has completed.

**Comment by nitinEd** [comment]
It worked. Thanks @kunagpal
