### ISSUE TITLE
Add support for providing custom cookie jar 

### ISSUE THREAD

**Issue by hipparchus2000** [postmanlabs/newman#918]
1. Newman Version =   3.4.3
 2. OS details (type, version, and architecture):  =   Windows 10 x64.
 3. Are you using Newman as a library, or via the CLI?   =  CLI
 3. Did you encounter this recently, or has this bug always been there:   probably always there
 4. Expected behaviour:  =  work as Postman does
 5. Command / script used to run Newman:   =  
newman run ".\dirname\dirname\PostmanFiles\Proj.postman_collection.json" --environment ".\dirname\dirname\PostmanFiles\Proj%%20localhost.postman_environment.json" --folder apiFunctions

 6. Sample collection, and auxilliary files (minus the sensitive details): = none relevant
 7. Screenshots (if applicable): = N/A

Steps to reproduce the problem:

1. Run above CLI command.

**Comment by rohit-gohri** [comment]
@codenirvana Is there anything stopping this? 

For the library API, we can directly support https://github.com/salesforce/tough-cookie CookieJar or through `postman-request` if the option of changing the base library is required sometime in the future. 

For the CLI a json file can be used, tough-cookie has fromJSON/toJSON methods (https://github.com/salesforce/tough-cookie#cookiejarfromjsonstring).

If this looks okay then I can open a PR for the same.

**Comment by codenirvana** [comment]
@rohit-gohri Yes, the underlying `postman-runtime` library accepts a tough-cookie jar instance.
Refer: https://github.com/postmanlabs/newman/blob/develop/lib/run/index.js#L176

**Comment by rohit-gohri** [comment]
@codenirvana Could you take a look at the PR? It would be really great if it got merged before the next release.

**Comment by rohit-gohri** [comment]
@codenirvana Sorry for pinging again, but this would be really helpful for my use-case. If you could have a look, it'd be great

**Comment by codenirvana** [comment]
Hey @rohit-gohri, sorry for getting back to you so late. I will definitely review this PR today.

**Comment by codenirvana** [comment]
Newman v5.2.0 adds support for providing custom Cookie Jar using the new `--cookie-jar` option.

Thanks @rohit-gohri for your contribution! 🙌
