### ISSUE TITLE
junit reporter format?

### ISSUE THREAD

**Issue by mattaylor** [postmanlabs/newman#92]
Any chance of adding support for custom templates for rendering test reports? A Junit test reporter would be particularly usefull for example to allow jenkins and similar CI tools process and render test results effectively .

**Comment by abhijitkane** [comment]
A <testsuite> element corresponds to a request.
A single request can have multiple tests (represented by the tests[] array). 
Each test corresponds to a <testcase>.

In case of multiple iterations, each test is run multiple times. So having a single <failure> element inside the <testcase> isn't suitable.

The next newman version (v1.2.5) will have `successes` and `failures` attributes in the <testsuite> element, that'll aggregate the counts in the constituent <testcase>s

**Comment by goldcougar** [comment]
just tested 1.2.6.  successes and failures are in the testsute and testcase node.  The testsuite node is aggregating the test case node. However Jenkins still isn't parsing that and then Jenkins reads that junit output, it shows them all as successful.

**Comment by goldcougar** [comment]
To add some additional detail to this, the Jenkins xsd for jUnit is located here: https://svn.jenkins-ci.org/trunk/hudson/dtkit/dtkit-format/dtkit-junit-model/src/main/resources/com/thalesgroup/dtkit/junit/model/xsd/junit-4.xsd

So, an example file would like like below, if all options turned on.  Seems like the current version that newman creates is missing the failures sumed up in the testsuites node, and its also missing the failure node within the testcase (if it had an error).  For example:
```xml
<testsuite failures="1" tests="3">
    <testcase classname="foo1" name="ASuccessfulTest"/>
    <testcase classname="foo2" name="AnotherSuccessfulTest"/>
    <testcase classname="foo3" name="AFailingTest" failures="1">
        <failure type="NotEnoughFoo"> details about failure </failure>
    </testcase>
</testsuite>
```

**Comment by rclayton-the-terrible** [comment]
+10

**Comment by goldcougar** [comment]
Tested the patch from commit #184 and it worked.  Thanks!

**Comment by Ernesto-Maserati-CH** [comment]
I don't understand the latest state of this issue.
Is it now built into Newman?
Or does it to be converted with a custom script by each guy who wants a xUnit report?
