### ISSUE TITLE
Need Folder Level Highlighting in the HTML report for Newman

### ISSUE THREAD

**Issue by jbnok** [postmanlabs/newman#923]
**_Version and environment information:_**

 1. Newman Version (can be found via `newman -v`): **3.4.3**
 2. OS details (type, version, and architecture): **Red Hat Enterprise Linux Server 7.2 (Maipo) 3.10.0-327.el7.x86_64**
 3. Are you using Newman as a library, or via the CLI? **CLI**
 3. Did you encounter this recently, or has this bug always been there: **Presumably always been there**
 4. Expected behaviour: **We should have some highlighting at the folder level if there is a failure with in that folder if there is one for ease of tracability**
 5. Command / script used to run Newman: **/usr/local/lib/node_modules/newman/bin/newman.js run ${COLLECTION_NAME} -e ${ENVIRONMENT_NAME} -r html,cli,json,junit --insecure via Jenkins**
 6. Sample collection, and auxilliary files (minus the sensitive details): **details are sensitive. Not Provided**
 7. Screenshots (if applicable): **Not Applicable**

**_Steps to reproduce the problem_**:

1. Run a test collection in newman that contains multiple folders and at least one test that will fail

_OBSERVE:_ There is no highlighting to be able to see where there is a failed test (i.e. in which folder) in the HTML Report

_PROPOSED MITIGATION:_ It would be nice if the folder name could be highlighted (Red or Pink) to demonstrate that there was a failure with a test in that folder in the HTML report

**Comment by kunagpal** [comment]
@jbnok Unfortunately, this is beyond the scope of the built in Newman reporters. However, you're more than welcome to create your very own custom reporter for the same. For more details, check out https://www.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman#custom-reporters.
