### ISSUE TITLE
Global X-Auth-Token?

### ISSUE THREAD

**Issue by r0zar** [postmanlabs/newman#925]
Is there a way from CLI to supply a X-Auth-Token to use for requests?

Thanks!

**Comment by kunagpal** [comment]
Although there is no way to specify global tokens via the CLI, you can add the header by clicking on `Headers` below the request url bar in Postman. The value of this header can be obtained via an environment variable. For instance:

collection.json
```
{
	"variables": [],
	"info": {
		"name": "newman-github-925",
		"_postman_id": "9180f5ec-509c-bb8e-fc0c-008d12a89440",
		"description": "https://github.com/postmanlabs/newman/issues/925",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "Simple `GET` request",
			"request": {
				"url": "https://postman-echo.com/get",
				"method": "GET",
				"header": [
					{
						"key": "X-Auth-Token",
						"value": "{{auth_token}}",
						"description": ""
					}
				],
				"body": {},
				"description": "A simple get request to demonstrate the use of custom headers in Postman and Newman."
			},
			"response": []
		}
	]
}
```

environment.json
```
{
  "id": "6641db72-f39b-2e44-38be-ea920c9124dd",
  "name": "newman-github-925",
  "values": [
    {
      "enabled": true,
      "key": "auth_token",
      "value": "ADD_YOUR_AUTH_TOKEN_VALUE_HERE",
      "type": "text"
    }
  ],
  "timestamp": 1487830556322,
  "_postman_variable_scope": "environment",
  "_postman_exported_at": "2017-02-23T06:16:32.741Z",
  "_postman_exported_using": "Postman/4.10.2"
}
```

You can run this as usual, using the `-e` flag for the environment file.

**Comment by r0zar** [comment]
Okay, thanks for that.

I'm trying to set up Newman tests run via jenkins for acceptance testing, so as a requirement I need a new auth token for each run of the suite.

I may end up running a find and replace on the newman collection if that my best option.

**Comment by kunagpal** [comment]
In that case, you can use `postman.setNextRequest` to keep switching back and forth between the auth token request and the other requests.You can read more about conditional workflows here: http://blog.getpostman.com/2016/03/23/conditional-workflows-in-postman/

**Comment by czardoz** [comment]
@r0zar 

Another thing you can try, is creating a globals file before running Newman, and passing that file as a command line argument.

e.g (in a bash script)
```
AUTH_TOKEN="some-token";

cat > secret_globals.json << EOF
[
	{
		"key": "auth_token",
		"value": "$AUTH_TOKEN",
		"type": "text",
		"name": "auth_token",
		"enabled": true
	}
]
EOF

newman run -c $COLLECTION_FILE -g secret_globals.json;
```
