### ISSUE TITLE
Newman does not recognize environment variables set in collection test scripts

### ISSUE THREAD

**Issue by drishticode** [postmanlabs/newman#929]
1. Newman Version (can be found via `newman -v`): 3.4.3
 2. OS details (type, version, and architecture): Linux, OEL7, x86_64
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Started using newman recently
 4. Expected behaviour: Environment variables, set/created dynamically in test scripts via postman.setEnvironmentVariable("key", "value"), should be available in the newman run.
 5. Command / script used to run Newman: newman run ./foo.json --environment ./bar.json --reporters cli,junit,html --reporter-junit-export report.xml --reporter-html-export report.html
 6. Sample collection, and auxiliary files (minus the sensitive details):
Env json:
{
  "id": "2750c2dc-028a-8f7a-369a-04554b5c52b5",
  "name": "Environment variables",
  "values": [
    {
      "enabled": true,
      "key": "FOO",
      "value": "",
      "type": "text"
    },
    {
      "enabled": true,
      "key": "BAR",
      "value": "BAR",
      "type": "text"
    }
  ],
  "timestamp": 1487975785826,
  "_postman_variable_scope": "environment",
  "_postman_exported_at": "2017-02-24T23:58:57.817Z",
  "_postman_exported_using": "Postman/4.10.2"
}

 7. Screenshots (if applicable): NA

Steps to reproduce:
Chain scripts by dynamically setting some environment variable via postman.setEnvironmentVariable("FOO", "FOO") and use it in next request, for example GET http://foo.bar/{{FOO}}
Run the collection through newman command in CLI mentioned above.

In the URL, the variables do not reflect new values and it run as http://foo.bar/{{FOO}}

With Postman app it works fine (even without defining FOO).

**Comment by kunagpal** [comment]
@drishticode I'm unable to reproduce this with the provided information, please see https://github.com/postmanlabs/newman/blob/develop/test/integration/request-chaining-test.postman_collection.json for a working example.

**Comment by drishticode** [comment]
Thanks @kunagpal. It worked. Looks like the api under test was not correctly returning the values and that resulted in variables values to be undefined. Thanks for looking into it and my bad for not debugging deep enough.

**Comment by sophiecdd** [comment]
@kunagpal when running the "newman run collection.json -e env.json", if in one request, it does setEnvironmentVariable("value", "value"), does it automatically update the env file? so that in the following request can I do as below? It seems doesn't work for me from command line, but it works fine from POSTMAN client.
"request": {
	"url": "http://{{base_url}}/login/security_check",
	"method": "POST",
	"header": [
		{
			"key": "Cookie",
			"value": "**{{value}}**",
			"description": ""
		}
	],
	"body": {
		"mode": "raw",
		"raw": "j_username=user&j_password=pass"
	},

**Comment by shamasis** [comment]
Newman is not supposed to update the environment file unless you instruct it to specifically export the environment data to a file using --export-* commands. See README.

If you still have issues, I suggest we continue the conversation in a new issue as that will help us keep better track of it.

**Comment by dpburgess** [comment]
Im actually getting this error.  On a windows machine I have the collection and the environment json files on my desktop and am running the newman process from there.

**Comment by mipatter** [comment]
Hi Guys, 

I see that Newman is not exporting the failures that postman is.  Here is the snippet from the log from newman: 
Attempting to set next request to User: Create a User - addUser

Root User: Create a User - addUser
  POST https://10.30.10.27/fcgi/scrut_fcgi.fcgi   4. Status code is 2020
  5. The newly created name matches what is in the environment
  6. Username is not a duplicate.
  -
  | 'User: Create a User - addUser'

The Failing Request: "4. Status code is 2020"
The above "4. Status code is 2020" is a clear failure in postman.  Newman executes all requests and tests but, provides no evidence of a failure.  Any suggestions on what I might be doing wrong? 

thank you.
