### ISSUE TITLE
Getting Syntax and 'TypeError' when running the collection from Newman

### ISSUE THREAD

**Issue by sgriffiths** [postmanlabs/newman#93]
Suite of tests run fine from Postman. When I try and run them from Newman using: **newman -c testcollection1.json -e Staging.postman_environment

the following error is shown in the console:

```
Iteration 1 of 1
EXCEPTION - SyntaxError: Unexpected token u
RequestError: e9a710e9-486f-3fc6-2838-d70082368c68 terminated. Error: undefined
RequestError: 41713c16-f095-8c35-1629-eba1f52eea20 terminated. Error: undefined
x Successful POST request
EXCEPTION - TypeError: Cannot call method 'has' of undefined
RequestError: 92d62b99-1cea-e6d2-bba1-ff5c7a2cc5df terminated. Error: undefined
x Status code is 200
RequestError: 41026d39-43b9-168d-b94f-263836e3cbab terminated. Error:      undefined
RequestError: 743f8ce7-94f0-2639-7420-eac88e28369e terminated. Error: undefined
```

Image attached containing the Json
![testcollect1](https://cloud.githubusercontent.com/assets/1687746/3049283/4ecaf4e8-e15b-11e3-9da0-85e31432d595.png)

Looks like its not handling the access_token variable

**Comment by adeshmukh123** [comment]
I'm getting "TypeError in test-script" error when i try to run a collection through new man. The Get calls are failing particularly. I'm attempting to parse the JSON response i get and trying to get value
of id key from the response and storing it in an environment variable.

The same call is running fine when i run it via postman.

Following is the JSON Response
{
    "httpStatusCode": 200,
    "body": [
        {
            "id": 2177,
            "FieldValue": "String"
        }
                ],
     "errors":[]
}

**Comment by modosteve** [comment]
I have found that sometimes I have scripts in the collection level Pre-request or Test tab which have errors that are easy to overlook. :)

**Comment by Sha-123** [comment]
if anyone got solution for typescript error and json script error in newman ,  please shareit.

**Comment by shamasis** [comment]
@Sha-123 - please post your queries on how-to issues at community.getpostman.com.
Debugging script errors in Newman is same as debugging any JavaScript code on browser or NodeJS.
