### ISSUE TITLE
Environment variables not substituting

### ISSUE THREAD

**Issue by scenage** [postmanlabs/newman#942]
Version/App Information:
-->
 1. Newman Version: v 3.5.0
 2. OS details: Windows 10
 3. Are you using Newman as a library, or via the CLI? CLI
 4. Did you encounter this recently, or has this bug always been there: Recently may have always been there.
 5. Expected behaviour: Parameters / variable substituted.
 6. Console logs 
newman

SuperDiary - Build Verification Tests

□ Attachments - BVT
└ Obtain Leap Auth Token
  POST https://{{auth_url}}/oauth/token [errored]
  2⠄ ReferenceError in test-script

└ POST Attachments
  POST https://{{sd_baseURL}}/attachments [errored]
  4⠄ ReferenceError in test-script

└ POST Attachment Refresh
  POST https://{{sd_baseURL}}/attachments/refresh [errored]
  6⠄ ReferenceError in test-script

└ Create Appointments w Attachment
  POST https://{{sd_baseURL}}/appointments [errored]
  8⠄ ReferenceError in test-script

└ DELETE Appointment
  DELETE https://{{sd_baseURL}}/appointments/{{appointment_id}} [errored]
 10⠄ ReferenceError in test-script

┌─────────────────────────┬──────────┬──────────┐
│                         │ executed │   failed │
├─────────────────────────┼──────────┼──────────┤
│              iterations │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│                requests │        5 │        5 │
├─────────────────────────┼──────────┼──────────┤
│            test-scripts │        5 │        5 │
├─────────────────────────┼──────────┼──────────┤
│      prerequest-scripts │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│              assertions │        0 │        0 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 262ms                     │
├───────────────────────────────────────────────┤
│ total data received: 0B (approx)              │
├───────────────────────────────────────────────┤
│ average response time: 0ms                    │
└───────────────────────────────────────────────┘

   #  failure         detail

 01.  Error           Invalid URI "https:///%7B%7Bauth_url%7D%7D/oauth/token"
                      at request
                      inside "Obtain Leap Auth Token" of "Attachments - BVT"

 02.  ReferenceError  responseBody is not defined
                      at test-script
                      inside "Obtain Leap Auth Token" of "Attachments - BVT"

 03.  Error           Invalid URI "https:///%7B%7Bsd_baseURL%7D%7D/attachments"
                      at request
                      inside "POST Attachments" of "Attachments - BVT"

 04.  ReferenceError  responseBody is not defined
                      at test-script
                      inside "POST Attachments" of "Attachments - BVT"

 05.  Error           Invalid URI "https:///%7B%7Bsd_baseURL%7D%7D/attachments/refresh"
                      at request
                      inside "POST Attachment Refresh" of "Attachments - BVT"

 06.  ReferenceError  responseCode is not defined
                      at test-script
                      inside "POST Attachment Refresh" of "Attachments - BVT"

 07.  Error           Invalid URI "https:///%7B%7Bsd_baseURL%7D%7D/appointments"
                      at request
                      inside "Create Appointments w Attachment" of "Attachments - BVT"

 08.  ReferenceError  responseBody is not defined
                      at test-script
                      inside "Create Appointments w Attachment" of "Attachments - BVT"

 09.  Error           Invalid URI "https:///%7B%7Bsd_baseURL%7D%7D/appointments/%7B%7Bappointment_id%7D%7D"
                      at request
                      inside "DELETE Appointment" of "Attachments - BVT"

 10.  ReferenceError  responseBody is not defined
                      at test-script
                      inside "DELETE Appointment" of "Attachments - BVT"

Running this newman command: 
newman run https://www.getpostman.com/collections/b05c7fb5abe123341f30 --environment https://api.getpostman.com/environments/1487933-4e1f6f9e-61e1-d895-370d-00276aed6f63 --iteration-data "data.json"  -n 1 --folder "Attachments - BVT"

Collection to be run is this one: 
https://www.getpostman.com/collections/b05c7fb5abe123341f30

The console logs are showing that the substitution is not happening anywhere...

**Comment by scenage** [comment]
This works in Postman via Collection Runner

**Comment by kunagpal** [comment]
@scenage The collection and environment urls must also include an `apiKey` query param, whose value should be your secret api key. You can manage your api key(s) here: https://app.getpostman.com/dashboard/integrations

**Comment by scenage** [comment]
Hi @kunagpal, how do you add the api-key to the newman command? I've done it via postman but not through newman as there is no argument option for it. Are you expecting people to not use the URL when a apikey is involved and just export them from postman?

**Comment by scenage** [comment]
I just made a new collection that has the API-key inside the single request in the collection and I'm still not getting access to the environment variables. The reason I am doing this is I'm trying to tie this to a Continuous Integration job and I need this to work so I can pull the latest code cuts. If there is another way, please let me know.

newman run https://www.getpostman.com/collections/36c8147ae0280dad10d1 --export-environment $EnvFile

**Comment by scenage** [comment]
So I worked out how to do it.
I did it through powershell and used the Invoke-RestMethod and outputted the information to a file which I piped back into the newman request.

**Comment by shamasis** [comment]
Great that you found a workaround. That's a genius idea by the way. 😊

To answer your previous question, refer to API.getpostman.com documentation. 

You can provide API key as a URL query parameter https://www.getpostman.com/collections/36c8147ae0280dad10d1?apikey=<<your-key-here>>

Closing the issue for now.
