### ISSUE TITLE
Https calls return empty results

### ISSUE THREAD

**Issue by crnattress** [postmanlabs/newman#944]
1. 3.5.0
 2. Windows Server 2012 R2
 3. CLI
 3. Recently
 4. Response includes failures and success
 5. newman run https://www.getpostman.com/collections/3084cc848ff93a48b5d3
 6. None
 7. Screenshots (if applicable):
![image](https://cloud.githubusercontent.com/assets/10875104/23729500/67d9e464-041f-11e7-9e59-5cd52ec8aaad.png)

Steps to reproduce the problem:

1. Run the following command in the command prompt: newman run https://www.getpostman.com/collections/3084cc848ff93a48b5d3
2. Result grid always returns 0 executed and 0 failed.

Note: Result grid is always accurately populated when executed with a file.

**Comment by shamasis** [comment]
Just checked your collection URL. It seems that the collection in URL contains no postman requests and as such newman is working fine. 

It could be that you shared the URL and then updated your collection. The public URL sharing feature requires you to explicitly go and update your collection in the URL (using the same share dialog box) after you make any changes. 

If you want to keep your collections always updated with latest changes in your app, use the Posman API to fetch the collection instead (api.getpostman.com)

**Comment by shamasis** [comment]
For reference the content of your URL is

```
{"id":"e4b27ebe-3a7b-32cd-f7c3-edd67b0d9545","name":"CustomerApi.Reporting","description":"","order":[],"folders":[],"timestamp":1488999844971,"owner":"1695306","public":false,"requests":[]}
```

Notice how the folders and requests arrays are empty.

**Comment by srpramod** [comment]
Https calls returns empty results in windows Postman version 4.10.5, but same when we hit from Chrome app - postman version 4.10.5, response is displayed for the Https call.

**Comment by kunagpal** [comment]
@srpramod You issue is slightly different from the one above, I've opened up a dedicated issue here: https://github.com/postmanlabs/postman-app-support/issues/2874

@crnattress We're marking this issue as resolved on our end, feel free to re-open if you're facing difficulties 😄
