### ISSUE TITLE
Add option for newman CLI to import shell env vars

### ISSUE THREAD

**Issue by dudeofawesome** [postmanlabs/newman#945]
1. Newman Version 3.4.0
 2. OS details (macOS, 10.11, x86_64):
 3. Newman via CLI?
 3. Feature request
 4. Expected behaviour: Newman CLI should have an option to import shell environment variables.

**Comment by shamasis** [comment]
Will your use case be fixed if we have a CLI option to provide global variable overrides?

For example 
newman run collection.json --variables "var1=value1&var2=value2"

**Comment by shamasis** [comment]
Using above you can pass environment variables like "var1=$my_env_var"

**Comment by dudeofawesome** [comment]
Yeah, I suppose that would work pretty well.

The reason this came up is because I was using newman as part of my CI testing. I wanted to be able to have it use some sensitive auth keys, so I'd like to be able to have those set inside of my CI env, instead of in a file committed to my git repo.

The way I ended up making it work for now is with a short JS script to read in env vars and output a Postman environment JSON file. https://gist.github.com/dudeofawesome/21033004a7d407d39a7da6bcc72a695f
It's not exactly pretty, but it works.

**Comment by dudeofawesome** [comment]
When you pass variables in using the `--variables` flag, do they end up being globals or environment? I don't see any mention of that flag when I run `newman run --help`

**Comment by kunagpal** [comment]
@dudeofawesome The `--variables` option suggested by @shamasis is not provided by Newman yet, the premise of loading environment of global variables via the CLI will have to be addressed first.

**Comment by kunagpal** [comment]
@dudeofawesome As of Newman v3.8.0, you can pass variables via the command line with the `--global-var key=value` option.
