### ISSUE TITLE
Syncing is not happening properly

### ISSUE THREAD

**Issue by scenage** [postmanlabs/newman#946]
Version and environment information:

 1. Newman Version (can be found via `newman -v`): 3.50
 2. OS details (type, version, and architecture): Windows 10 Pro, 64 bit
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: Always been there
 4. Expected behaviour: Syncing occurs immediately after a force sync or the clicking of the syncing icon
 5. Command / script used to run Newman: 
newman run https://www.getpostman.com/collections/5f488027a160c1ef24c8 -e https://api.getpostman.com/environments/1697279-887cd14f-7390-389f-9d35-91298d27f966?apikey=<API KEY> --iteration-data $DataFile -n $Iterations --folder "Attachments - BVT"
 6. Sample collection, and auxilliary files (minus the sensitive details): https://www.getpostman.com/collections/5f488027a160c1ef24c8

Steps to reproduce the problem:

Comparing the response from: https://www.getpostman.com/collections/5f488027a160c1ef24c8 (server version) to my local, it is clear that the changes I recently made are not being synced.

Please refer to the screenshot.

![image](https://cloud.githubusercontent.com/assets/8476191/23738698/a55c942e-04ee-11e7-86f7-86aad8414811.png)

I've tried to force sync but it's not saying there are any conflicts.

The only workaround that has worked for me thus far is to export the local version and re-import the collection by replacing the existing one. This is not ideal. Any help would be appreciated.

**Comment by scenage** [comment]
You can close this. There was a publishing issue yesterday and it has since been resolved. As a result, I tried a few tests today and it seems to be synced up.
Thanks!

**Comment by scenage** [comment]
There was a publishing issue yesterday that was partly the cause for the sync issue. It's now resolved.
What I am finding is that anything coming from https://**api.getpostman.com/**collections/1697279-16dd32f8-9c71-0797-d59f-1c6ac847ab46 is in sync HOWEVER, anything coming from https://**www.getpostman.com**/collections/5f488027a160c1ef24c8 is out of sync.

**Comment by shamasis** [comment]
Well. Can you go to that collection's share dialog box and then go to the tab with the link and click "update link"?

The www.getpostman/… links are manually kept updated - can you confirm that even that is it happening?

**Comment by czardoz** [comment]
@scenage The collection links (http://www.getpostman.com/collections/...) are not updated in real time. Also, the links are public, so if you want to ensure maximal security, I would encourage you to use `api.getpostman.com` for fetching collections. 

We have documentation about how to go about this: https://github.com/postmanlabs/newman#using-newman-with-the-postman-cloud-api

I'm marking this issue as solved, do re-open it in case you're still having issues. :)
