### ISSUE TITLE
Newman template.hbs aggregation problem

### ISSUE THREAD

**Issue by Jack85811** [postmanlabs/newman#950]
1. Newman Version: 3.5.0
 2. OS details: windows 7 and Openshift Enterprise 3.
 3. Using Newman as a library.
 3. Recent Encounter with this  newman version
 4. Expected behaviour: My template testaggregation should be shown as usual

Hello,

firstoff, i'am a big fan of newman and i love using your library!
I've been using a custom template *.hbs file, which serves my needs.  This one runs perfectly fine on the library version 3.4.3 and behaves as expected.
Yesterday i noticed a sudden change, as my application runs on Openshift 3, i conifguered it in a way, that Openshift would get the newest version of the newman library, when i deploy it.

It seems like, newman 3.5.0 is somehow ignoring, or not finding any folders of the collection in my {{#if folder}} statment in the template. he will always switch to the {{else}} case.

Unfourtanatley i somehow can not upload pictures.
i will try to update that, if necessary.

Best Regards 
Jack

**Comment by kunagpal** [comment]
@Jack85811 Could you share your custom template?

**Comment by Jack85811** [comment]
As is said, i will try to uplaod some images as soon as i can, somehow github says that it can process them:/.

This is the part where it starts to bug:

`{{#each aggregations}}
{{#if folder}}
    <div  id="collapse-folder-{{@index}}" role="tablist" aria-multiselectable="true" >
        <div role="tab" id="folderHead-{{@index}}">
            <div><a data-toggle="collapse" data-parent="#accordion" <strong>Folder: {{folder}}</strong></a></div >
        </div>
        <div  id="folderData-{{@index}}" role="tabpanel" aria-labelledby="folderHead-{{@index}}">
            {{#each contents}}
         <div  id="collapse-request-{{item.id}}" role="tablist" aria-multiselectable="true">
          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="requestHead-{{item.id}}">
              <div>Test Collection Name: {{item.name}}</div>
            </div>
            <div>&nbsp;</div>
            <div id="requestData-{{item.id}}" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="requestHead-{{item.id}}">
              <div class="panel-body">
                <table class="table2">
                {{#with request}}
                  {{#if description.content}}
                    <tr>
                    <td>Description</td>
                    <td>{{description.content}}</td>
                    </tr>
                  {{/if}}
                <tr>
                  <td>Method</td>
                  <td>{{method}}</td>
                </tr>
                <tr>
                  <td>URL</td>
                  <td><a href="{{url}}" target="_blank">{{url}}</a></td>
                </tr>
                {{/with}}
                <tr>
                  <td>Mean time per request</td>
                  <td>{{mean.time}}</td>
                </tr>
                <tr>
                  <td>Mean size per request</td>
                  <td>{{mean.size}}</td>
                </tr>
                <tr>
                  <td>Total passed tests</td>
                  <td>{{cumulativeTests.passed}}</td>
                </tr>
                <tr>
                  <td>Total failed tests</td>
                  <td>{{cumulativeTests.failed}}</td>
                </tr>
                <tr>
                  <td>Status code</td>
                  <td>{{response.code}}</td>
                </tr>
                </table>
                {{#if assertions.length}}
                  <div class="">&nbsp;</div>
                  <div>Tests</div>
                    <table class="table2">
                      <tr>
                        <th>Name</th>
                        <th>Pass count</th>
                        <th>Fail count</th>
                      </tr>
                      <tbody>{{#each assertions}}<tr><td>{{this.name}}</td><td>{{this.passed}}</td><td>{{this.failed}}</td></tr>{{/each}}</tbody>
                    </table>
                {{/if}}
                <div class="">&nbsp;</div>
                <div class="">&nbsp;</div>
                <div class="">&nbsp;</div>
              </div>

          </div>
        </div>
      {{/each}}
        </div>
    </div>
{{else}}
    <div class="panel-group" id="collapse-request-{{item.id}}" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="requestHead-{{item.id}}">
                <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#requestData-{{item.id}}" aria-controls="collapseOne">{{item.name}}</a></h4>
            </div>

            <div id="requestData-{{item.id}}" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="requestHead-{{item.id}}">
                <div class="panel-body">
                    {{#with request}}
                        {{#if description.content}}
                            <div class="col-md-4">Description</div><div class="col-md-8" style="white-space: pre-wrap;">{{description.content}}</div>
                            <div class="col-md-12">&nbsp;</div>
                        {{/if}}

                        <div class="col-md-4">Method</div><div class="col-md-8">{{method}}</div>
                        <div class="col-md-4">URL</div><div class="col-md-8"><a href="{{url}}" target="_blank">{{url}}</a></div>
                    {{/with}}

                    <div class="col-md-12">&nbsp;</div>
                    <div class="col-md-4">Mean time per request</div><div class="col-md-8">{{mean.time}}</div><br/>
                    <div class="col-md-4">Mean size per request</div><div class="col-md-8">{{mean.size}}</div><br/>

                    <div class="col-md-12">&nbsp;</div>
                    <br/><div class="col-md-4">Total passed tests</div><div class="col-md-8">{{cumulativeTests.passed}}</div>
                    <div class="col-md-4">Total failed tests</div><div class="col-md-8">{{cumulativeTests.failed}}</div><br/>

                    <div class="col-md-12">&nbsp;</div>
                    <br/><div class="col-md-4">Status code1111</div><div class="col-md-8">{{response.code}}</div><br/>

                    {{#if assertions.length}}
                        <div class="col-md-12">&nbsp;</div>
                        <div class="col-md-4">Tests</div>

                        <div class="col-md-8">
                            <table class="table table-responsive table-condensed">
                                <thead><tr><th>Name</th><th>Pass count</th><th>Fail count</th></tr></thead>
                                <tbody>{{#each assertions}}<tr><td>{{this.name}}</td><td>{{this.passed}}</td><td>{{this.failed}}</td></tr>{{/each}}</tbody>
                            </table>
                        </div>
                    {{/if}}
                </div>
            </div>
        </div>
    </div>
{{/if}}
{{/each}}`

**Comment by kunagpal** [comment]
@Jack85811 Could you make the following changes to your custom template and let me know if that works for you?

1. Append the following block at the end of your report:
```handlebars
{{#*inline "aggregations"}}
    {{#each executions}}
        <div class="panel-group" id="collapse-request-{{item.id}}" role="tablist" aria-multiselectable="true">
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="requestHead-{{item.id}}">
                    <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#requestData-{{item.id}}" aria-controls="collapseOne">{{item.name}}</a></h4>
                </div>

                <div id="requestData-{{item.id}}" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="requestHead-{{item.id}}">
                    <div class="panel-body">
                        {{#with request}}
                            {{#if description.content}}
                                <div class="col-md-4">Description</div><div class="col-md-8" style="white-space: pre-wrap;">{{description.content}}</div>
                                <div class="col-md-12">&nbsp;</div>
                            {{/if}}

                            <div class="col-md-4">Method</div><div class="col-md-8">{{method}}</div>
                            <div class="col-md-4">URL</div><div class="col-md-8"><a href="{{url}}" target="_blank">{{url}}</a></div>
                        {{/with}}

                        <div class="col-md-12">&nbsp;</div>
                        <div class="col-md-4">Mean time per request</div><div class="col-md-8">{{mean.time}}</div><br/>
                        <div class="col-md-4">Mean size per request</div><div class="col-md-8">{{mean.size}}</div><br/>

                        <div class="col-md-12">&nbsp;</div>
                        <br/><div class="col-md-4">Total passed tests</div><div class="col-md-8">{{cumulativeTests.passed}}</div>
                        <div class="col-md-4">Total failed tests</div><div class="col-md-8">{{cumulativeTests.failed}}</div><br/>

                        <div class="col-md-12">&nbsp;</div>
                        <br/><div class="col-md-4">Status code</div><div class="col-md-8">{{response.code}}</div><br/>

                        {{#if assertions.length}}
                            <div class="col-md-12">&nbsp;</div>
                            <div class="col-md-4">Tests</div>

                            <div class="col-md-8">
                                <table class="table table-responsive table-condensed">
                                    <thead><tr><th>Name</th><th>Pass count</th><th>Fail count</th></tr></thead>
                                    <tbody>{{#each assertions}}<tr><td>{{this.name}}</td><td>{{this.passed}}</td><td>{{this.failed}}</td></tr>{{/each}}</tbody>
                                </table>
                            </div>
                        {{/if}}
                    </div>
                </div>
            </div>
        </div>
    {{/each}}
{{/inline}}
```

2. Replace the snippet you had provided earlier with the following:
```handlebars
    {{#each aggregations}}
        {{#if parent.name}}
        <div class="panel-group" id="collapse-folder-{{parent.id}}" role="tablist" aria-multiselectable="true">
            <div role="tab" id="folderHead-{{parent.id}}">
                <h4 style="font-size: 18px;" class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#folderData-{{parent.id}}" aria-controls="collapseOne"><strong>{{parent.name}}</strong></a></h4>
            </div>
            <br/>
            <div id="folderData-{{parent.id}}" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="folderHead-{{parent.id}}">
            {{> aggregations}}
            </div>
        </div>
        {{else}}
        {{> aggregations}}
        {{/if}}
    {{/each}}
```

**Comment by Jack85811** [comment]
It doesn't end up perfectly as i wanted, but you fixed the main issue!
Best Regards

jack
