### ISSUE TITLE
Documentation incorrect README.md line 145

### ISSUE THREAD

**Issue by fredsmithjr** [postmanlabs/newman#953]
1. Newman Version (can be found via `newman -v`): 3.5.0
 2. OS details (type, version, and architecture): Windows
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there:  Recently
 4. Expected behaviour: --color outputs color 
 5. Command / script used to run Newman:
**Attempted 1**: newman.cmd -k -e ..\Env\TST_VPay.postman_environment.json -c ..\Tests\<my>.postman_collection.json -r 6000 -x **--color true** -S -H ..\Results\TST_<datafile>_%mm%%dd%%yyyy%.html -t ..\Results\TST_<datafile>_%mm%%dd%%yyyy%.xml

**Attempted 2**: newman.cmd -k -e ..\Env\TST_VPay.postman_environment.json -c ..\Tests\<my>.postman_collection.json -r 6000 -x **--color** -S -H ..\Results\TST_<datafile>_%mm%%dd%%yyyy%.html -t ..\Results\TST_<datafile>_%mm%%dd%%yyyy%.xml

**Original:** newman.cmd -k -e ..\Env\TST_VPay.postman_environment.json -c ..\Tests\<my>.postman_collection.json -r 6000 -x -p -S -H ..\Results\TST_<datafile>_%mm%%dd%%yyyy%.html -t ..\Results\TST_<datafile>_%mm%%dd%%yyyy%.xml

**Working:** newman.cmd -k -e ..\Env\TST_VPay.postman_environment.json -c ..\Tests\<my>.postman_collection.json -r 6000 -x **-p true** -S -H ..\Results\TST_<datafile>_%mm%%dd%%yyyy%.html -t ..\Results\TST_<datafile>_%mm%%dd%%yyyy%.xml

 6. Sample collection, and auxilliary files (minus the sensitive details):

 7. Screenshots (if applicable):

**Comment by czardoz** [comment]
@fredsmithjr You're using the older newman options, which have been deprecated since Newman v3.0.

Check this table for how to migrate to the newer options: https://github.com/postmanlabs/newman/blob/develop/MIGRATION.md#cli-migration-table
