### ISSUE TITLE
side question: Is this a reference to Seinfeld?

### ISSUE THREAD

**Issue by brimchan** [postmanlabs/newman#963]
... just curious ...

**Comment by kunagpal** [comment]
Yes, it is 😄

**Comment by brimchan** [comment]
that's awesome!

**Comment by Grepsy** [comment]
Haha, that's hilarious. I wasn't sure it was a reference :-)

**Comment by csforbes** [comment]
![AcceptableHeartyBarasingha-size_restricted](https://user-images.githubusercontent.com/19981645/165641321-57b10a74-36bb-4bbf-be87-7cf40e789ea8.gif)

**Comment by mjohnston-rightnow** [comment]
![giphy](https://github.com/postmanlabs/newman/assets/42212266/99b66099-d71d-470b-97f9-0598dad4496b)
