### ISSUE TITLE
Newman Error messages

### ISSUE THREAD

**Issue by jdiaz4517** [postmanlabs/newman#964]
Hello

While running a collection I get sometimes errors which are not as descriptive as they are if you run same collection directly from postman. 

For example running a collection using newman, I get this error:
 _- 1⠄ TypeError in test-script_

However if I run the exactly same collection from Postman, the error looks like:
_2- There was an error in evaluating the test script:  TypeError: Cannot read property 'passengerFares' of undefined_

The Postman error is pointing me out directly to where the issue is while the way is present in newman does not really help. So I finding myself either adding console.log(...) statements or going back to postman to manually run the collection and find exactly what the problem is.

As we are using newman for our functional tests would be great if could get the same error details we get in Postman in the newman console output. Is there any way to achieve that?

Thanks
Javier

**Comment by kunagpal** [comment]
![newman github 964](https://cloud.githubusercontent.com/assets/7289840/26055167/3d7d302e-398d-11e7-8bf4-7375d48f11d9.png)

@jdiaz4517 The complete error messages are displayed together, at the end of the collection run.

**Comment by Sha-123** [comment]
if found solution please share it.

**Comment by shamasis** [comment]
The issue was in script and the way to debug the same was highlighted in the screenshot posted. The actual underlying error has to be debugged by the programmer of the script within the collection or the code be posted in community.getpostman.com to get how-to help. :-)

**Comment by rakyarrows** [comment]
I am facing the same issue while running on newman, It is working fine on postman runner.

![image](https://user-images.githubusercontent.com/21131320/101368276-f30cdb80-3874-11eb-810d-2cf42e9cb0cf.png)
