### ISSUE TITLE
Error in Running collection using multiple variables from external CSV File

### ISSUE THREAD

**Issue by PriyaKumaar** [postmanlabs/newman#966]
Hi

I have done a collection and read the data from external CSV file but the tests failed while asserting the response

Below the Script which i have used

tests["Body contains address"] = responseBody.has(data.address);

Is there any other test script to check that the data has been read from the external file only?

Thanks in advance..!

**Comment by kunagpal** [comment]
@PriyaKumaar Could you add the following snippet to your script and share the exact response?

```javascript
console.log('DATA: ', data);
console.log('RES: ', responseBody);
```

**Comment by PriyaKumaar** [comment]
Thanks..!I got the output...The tests script succeed..

**Comment by kunagpal** [comment]
Glad it worked out for you. Have fun developing with Newman and Postman! 😄
