### ISSUE TITLE
Newman report path.

### ISSUE THREAD

**Issue by urosjarc** [postmanlabs/newman#969]
I could not find in documentation for newman module how can i set export path for html when I run it incode. It will export to `./newman` dir, how can I set that it will export to `./build/newman`?

```
  newman.run({  "reporters": ["cli","html"]}, (err, summary) => {
  });
```

**Comment by kunagpal** [comment]
You can use the following snippet to export HTML reports to a custom location:
```javascript
newman.run({
    collection: '/path/to/collection.json',
    reporters: ['cli', 'html'],
    reporter: { html: { export: './build/newman/report.html' } }
  }, (err, summary) => {
});
```
