### ISSUE TITLE
HTML reporter is not generating right report.

### ISSUE THREAD

**Issue by RatanShreshtha** [postmanlabs/newman#986]
Newman - 3.5.2
Fedora - 25
node - v7.6.0
I am using Newman for API testing and I have observed that the report generated by default HTML template is not right if I run the same request with different data from a CSV file.
It gives me the wrong URL in report and number of assertion for each request is also wrong.

I would like to fix this but I don't know how to write a template for Newman.

**Comment by kikesilva** [comment]
Same issue here. Html report always shows first URL in every request block of the report. And data belongs to the first call of iterations

**Comment by kunagpal** [comment]
@RatanShreshtha @kikesilva This behaviour is intended, as the HTML reporter aggregates statistics across multiple iterations. Details like the response code and url are shown as per the first iteration. If complete details on all requests across all iterations are needed, you can check out the JSON report:
```
newman run collection.json -r cli,json --reporter-json-export report.json
```

The file `report.json` will now contain the complete summary of the collection run. A sample file can be viewed here: https://github.com/postmanlabs/newman/blob/develop/examples/reports/sample-collection-report.json

**Comment by RatanShreshtha** [comment]
Yeah but the JSON produced is too large, I want to write a template for my use, can you guide me for this.

**Comment by czardoz** [comment]
@RatanShreshtha You would have to write your own reporter and use it. We don't have proper documentation on how to go about writing one yet, but in a nutshell,

1. Create a new npm package using `npm init` (the name should be `newman-reporter-<something>`)
2. Add an index.js file. You can listen to all the Newman events documented in the [Readme](https://github.com/postmanlabs/newman#newmanrunevents). Here's an example of a simple reporter: https://github.com/postmanlabs/newman/blob/376af8fddd72ef3f350134f49df57bf4fd7d7be5/lib/reporters/emojitrain.js
3. Install your reporter using `npm install`. If Newman is installed globally (using `npm install -g newman`), you will need to install the reporter globally too.
4. Use the reporter by passing the name you gave in the list of reporters to use `newman run collection.json --reporters <something>`

**Comment by RatanShreshtha** [comment]
Ok thanks

**Comment by RatanShreshtha** [comment]
Can you tell me how to use a custom reporter for newman from a node script ?

**Comment by kunagpal** [comment]
@RatanShreshtha https://github.com/postmanlabs/newman#creating-and-using-custom-reporters

**Comment by kunagpal** [comment]
@RatanShreshtha More detailed information can be found here: https://www.getpostman.com/docs/newman_intro#custom-reporters

**Comment by jayanthktn** [comment]
Anyone did for proper html report.

**Comment by Kal6** [comment]
Yes, it is hard drill down the report and find out the root cause if any failures occurred, I am also having the same issue with it. I have multiple folders in the collection, each folder has some tests which will access the csv file to drive the data, when i see the report it is not understandable as i have working as qa automation architect i would recommend to have this resolved. As you folks know when we dont have proper reporting there is no sense of running the script, we can't find the actual root cause.

Greatly appreciated if you folks could provide the solution.
Thanks - Kal
