### ISSUE TITLE
Customize html report 

### ISSUE THREAD

**Issue by SMohamedMubarish** [postmanlabs/newman#988]
I wish to do some customization in HTML report generated from newman.
I wish to display the request data in the html report if request method is not a get method. How could I acheive that?

I tried something like
`{{#if method EQUALS "POST|PUT"}
                                <div class="col-md-4">Payload Parameters</div><div class="col-md-8" style="white-space: pre-wrap;">{{request.data}}</div>
                                <div class="col-md-12">&nbsp;</div>
							 {{/if}}`
but fails..

**Comment by RatanShreshtha** [comment]
As far as I know Newman uses mustache templating engine for HTML reports, which is a Logic-less templating engine.
Mustache expressly forbids things like this. That's logic, and you're trying to put it in your template :)

**Comment by czardoz** [comment]
@RatanShreshtha, we actually use handlebars, which allows some logic in the templates​ :)

**Comment by kunagpal** [comment]
@SMohamedMubarish This can be accomplished using a combination of Handlebars helpers (http://handlebarsjs.com/expressions.html), and Newman custom reporters: https://github.com/postmanlabs/newman#creating-and-using-custom-reporters. Feel free to get back if you're facing issues :smile:
