### ISSUE TITLE
Generic tests to HTTPS passing in Postman but not in Newman ?

### ISSUE THREAD

**Issue by maknoon** [postmanlabs/newman#99]
I'm writing very simple tests to pass against some calls made to an https ASP.Net Web API. These tests run and pass as predicted in Postman, but I get different results when I attempt the same in the commandline. I've checked the Collection json file that I am using; all the appropriate header declarations are present and nothing is different.

for comparison:

![zz](https://cloud.githubusercontent.com/assets/5428281/3166474/1963c2de-eb61-11e3-99cb-16c84bbcb633.png)

and 

![zzzz](https://cloud.githubusercontent.com/assets/5428281/3166220/4fd3ded8-eb5e-11e3-8327-c19766675590.png)

The specific tests that I am running are also very basic:

```
tests["Response time is less than 500ms"] = responseTime < 500;
tests["Status code is 200"] = responseCode.code === 200;
tests["Content-Type is present"] = responseHeaders.hasOwnProperty("Content-Type");
```

(Edited to add additional screenshots. I've also tried using both Content-Type and content-type.)

Any ideas? Apologies in advance if I have just overlooked something completely obvious.

**Comment by Mason240** [comment]
I am also having the same issue. I have a Web API project that I am running locally. I have no problem writing tests using the Postman chrome app, however Newman is unable to connect to the api. I get the following message: EXCEPTION - No response from URL
RequestError: 49e74537-8f72-0b7e-74bd-a9d16fbdf0f6 terminated. Error: ENOTFOUND

Here is a very basic test that works in Postman, does not in Newman: https://www.getpostman.com/collections/dab9a7aed8e42c12fb01 

The endpoint I am trying to hit is: https://localhost:44301/api/Health

 Could this be header issue?

**Comment by abhijitkane** [comment]
Can you try using the "-k" option? This disables strict SSL checking (documented here - https://www.npmjs.com/package/newman)

**Comment by Mason240** [comment]
Yes, I tried using the -k and -l options.

**Comment by abhijitkane** [comment]
ENOTFOUND sounds like a DNS issue. What about replacing localhost with 127.0.0.1?

**Comment by Mason240** [comment]
Using https://127.0.0.1:44301/api/Health I get no response, even from using the regular Postman collection runner.

**Comment by abhijitkane** [comment]
What OS are you on? Can you try running newman as sudo?

Yes, 1.2.7 is the current version.
