### ISSUE TITLE
Outdated Jenkins/newman documentation

### ISSUE THREAD

**Issue by mtoothman** [postmanlabs/newman#992]
1. Newman Version (can be found via `newman -v`): 3.4.2
 2. OS details (type, version, and architecture): macOS Sierra 10.12.3
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: n/a
 4. Expected behaviour: n/a
 5. Command / script used to run Newman: `newman -c jenkins_demo.postman_collection --exitCode 1`
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

Steps to reproduce the problem:

1. Visit [Postman docs' "Integrating With Jenkins"](https://www.getpostman.com/docs/integrating_with_jenkins)

Several deprecated switches are referred to: 

`-c` for passing in a collection (now a positional parameter), and 
`-exitCode` (deprecated).
I see `--exitCode` and `--collection` in https://github.com/postmanlabs/newman/blob/develop/lib/cli/index.js, but using it with the CLI results in `newman run: error: Unrecognized arguments:`.

Can this document be updated with a working command? I'm happy to submit a PR if the documentation is open to submissions from external users. I'm unclear on whether these options are "deprecated" == "no longer maintained & may be completely removed at any time" or "deprecated" == "don't work".

**Comment by shamasis** [comment]
We are updating the docs. Even then, the postman-docs repository is open source for contribution. 😊

**Comment by shamasis** [comment]
By the way, there's a MIGRATION.md that outlines the changes between Newman v2 and v3. They should be deprecated but not discontinued. We will look into whether any old command has any issue.

**Comment by mtoothman** [comment]
Sounds good, thanks. I'll send a PR in future.
