### ISSUE TITLE
Deprecated node_module installed with newman

### ISSUE THREAD

**Issue by mtoothman** [postmanlabs/newman#993]
1. Newman Version (can be found via `newman -v`): 3.5.0
 2. OS details (type, version, and architecture): alpine 3.3
 3. Are you using Newman as a library, or via the CLI? cli
 3. Did you encounter this recently, or has this bug always been there: always
 4. Expected behaviour:
 5. Command / script used to run Newman: part of `docker build`
 6. Sample collection, and auxilliary files (minus the sensitive details):
 7. Screenshots (if applicable):

Steps to reproduce the problem:
[in Dockerfile:]
```
RUN npm install -g newman@${NEWMAN_VERSION};
 ---> Running in 25fb6996362d
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
```

**Comment by shamasis** [comment]
node-uuid is used by one of our dependencies and not directly by newman. This shouldn't cause any problem since the deprecation is merely semantics to use the uuid package name.
