### ISSUE TITLE
oAuth 2.0 - Authorization Code request results in  error - proper client ssl certificate was not presented

### ISSUE THREAD

**Issue by sivakrishnajee** [postmanlabs/newman#997]
Hi,

When trying to get a new access token for oAuth 2.0 - Grant type of "Authorization Code" results in the following error:

error: invalid_request
Description: proper%20client%20ssl%20certificate%20was%20not%20presented

Version and environment information:

 1. Postman Version ): Version 4.10.7 - win32 6.1.7601 / x64
 2. OS details (type, version, and architecture): Windows 7
 3. Are you using Postman as a library, or via the CLI? - Postman native app from desktop
 3. Did you encounter this recently, or has this bug always been there: happening for last 3 months
 4. Expected behaviour: Postman should generate a new access token
 5. Command / script used to run Newman:start the native postman app from desktop
 6. Sample collection, and auxilliary files (minus the sensitive details):N.A.
 7. Screenshots (if applicable):
![image](https://cloud.githubusercontent.com/assets/17912926/25292352/c12c821e-26a3-11e7-82de-6b2e1bf61502.png)

![image](https://cloud.githubusercontent.com/assets/17912926/25292399/efbe09d6-26a3-11e7-8733-0ec4ccd514df.png)

Steps to reproduce the problem:

1. {{Start Postman native app by clicking the same from windows desktop}}
2. {{Click the "Get New Access Token"}}
3. {{Click Request Token}}
4. {{Following error is displayed:
     error: invalid_request
     Description: proper%20client%20ssl%20certificate%20was%20not%20presented
     }}

**Comment by kunagpal** [comment]
@sivakrishnajee I've created a new issue at https://github.com/postmanlabs/postman-app-support/issues/2975, this repository is for Newman related issues only 😄

**Comment by sivakrishnajee** [comment]
Kunagpal, Thank you for moving the ticket into the appropriate queue.
