### ISSUE TITLE
Postman is not getting oAuth 2.0 - Access Token when there are 2 SSL certificates in windows certificate store 

### ISSUE THREAD

**Issue by sivakrishnajee** [postmanlabs/newman#998]
Hi,

When there are multiple SSL certificates are attached to the Windows certificate store, Postman is having issues in getting the oAuth 2.0 - Access Token.  Postman is responding with the error message:

Error getting access token from client_credentials flow. Could not send request

**Note the following conditions:**
1. There are 2 certificates attached with the windows certificate store.
2. Postman is configured with 1 of those certificates as shown in the screen shot.
3. Under the above conditions, postman is not getting the access token.
4. But, if i remove one of the certificate from windows certificate store(which is not used by postman), then postman is getting the access token.

So, the issue i am having is, postman is not working when there are 2 certificates attached to the windows certificate store.

**Version and environment information:**

1. Postman Version ): Version 4.10.7 - win32 6.1.7601 / x64
2. OS details (type, version, and architecture): Windows 7
3. Are you using Postman as a library, or via the CLI? - Postman native app from desktop
4. Did you encounter this recently, or has this bug always been there: happening for last 3 months
5. Expected behaviour: Postman should generate a new access token
6. Command / script used to run Newman:start the native postman app from desktop
7. Sample collection, and auxilliary files (minus the sensitive details):N.A.
8. Attach the SSL certificates with Postman

 8. Screenshots (if applicable):

![image](https://cloud.githubusercontent.com/assets/17912926/25293996/3b9d7a10-26ab-11e7-9bdf-d26c5d543484.png)

![image](https://cloud.githubusercontent.com/assets/17912926/25294281/77d605e6-26ac-11e7-8d7b-7b1fe31cd56f.png)

**Steps to reproduce the problem:**
1. {{Make sure that there are 2 certificates attached to windows certificate store.}}
2. {{Make sure that 1 certificate is configured with postman.}}
3. {{Start Postman native app by clicking the same from windows desktop}}
4. {{Click the "Get New Access Token"}}
5. {{Click Request Token}}
6. {{Following error is displayed:
error: invalid_request
Description: proper%20client%20ssl%20certificate%20was%20not%20presented
}}
7. {{Now, start Internet Explorer and remove the one of the certificate(not being used by postman) from the Internet Options -> content -> certificates}}
8. {{Now, repeat above steps 3-6.  Postman will get the access toen.}}

**Comment by kunagpal** [comment]
@sivakrishnajee As was the case with #997, this issue has been transferred to https://github.com/postmanlabs/postman-app-support/issues/2976, you can track it's progress there 😄
